### ISSUE TITLE
[Node.js VM] ENOENT on a file that seems to exist

### ISSUE THREAD

**Issue by cedx** [travis-ci/travis-ci#10016]
On one of my Node.js projects (cf. [cedx/cookies.js](https://travis-ci.com/cedx/cookies.js/builds/82224730)), I get a `ENOENT` error that does not seem justified.

My `.travis.yml` file:

```yaml
addons: {chrome: stable}
dist: trusty
language: node_js
node_js: 10
notifications: {email: false}
sudo: required

install: npm install
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script: npm test
after_success:
- pwd
- ls src/
- cat src/cookie_options.ts
- npm run coverage
```

The issue is on the last step of `after_success` phase : the command `npm run coverage` does not find the file `/home/travis/build/cedx/cookies.js/src/cookie_options.ts` (cf. [build #82224730](https://travis-ci.com/cedx/cookies.js/builds/82224730)).

But the previous steps seem to indicate that this file exists:

```shell
$ pwd
/home/travis/build/cedx/cookies.js

$ ls src/
cookie_options.ts  cookies.ts  index.ts  map.ts  simple_change.ts

$ cat src/cookie_options.ts
# the contents of the file
```

The command `npm run coverage` lauches the `coveralls` executable from the package [@cedx/coveralls.js](https://www.npmjs.com/package/@cedx/coveralls). I'm alread using this package on my other Node.js projects and everything is fine.

So, I don't understand where this issue comes from.
