### ISSUE TITLE
Secret variable not used in build.

### ISSUE THREAD

**Issue by rhpvorderman** [travis-ci/travis-ci#10020]
I have `CODACY_PROJECT_TOKEN` defined as a secret variable. Unfortunately, this variable is consistently not found. Tox has `passenv` correctly configured, so this is not causing the issue. I do not see the variable in printenv, or with echo "$CODACY_PROJECT_TOKEN". It seems as the variable is not passed to the build environment at all. This works in other projects, so I suspect `.travis.yml` to be the cause, but I can't locate the issue. Can anyone help me with this?
```YAML
language: python
sudo: false
matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27-lint
    - python: 3.5
      env: TOX_ENV=py35-lint
    - python: 2.7
      env: TOX_ENV=py27-lint-readme
    - python: 3.5
      env: TOX_ENV=py35-pytest
      services:
      - docker
    - python: 2.7
      env: TOX_ENV=py27-pytest
      services:
      - docker
    - python: 2.7
      env: TOX_ENV=py27
      services:
        - docker
    - python: 3.5
      env: TOX_ENV=py35
      services:
        - docker

install:
    - pip install tox

script:
    - tox -e $TOX_ENV
```
