### ISSUE TITLE
dotnet-sonarscanner doesn't work

### ISSUE THREAD

**Issue by equiman** [travis-ci/travis-ci#10044]
I'm trying to install this tool, to work with sonarscanner:
`dotnet tool install --global dotnet-sonarscanner --version 4.3.1`

https://www.nuget.org/packages/dotnet-sonarscanner

But not work:
`The command "dotnet sonarscanner begin /k:"dein:toolbox" /n:"ToolBox" /v:"1.4.1" /o:"dein" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$SONAR_KEY" /d:sonar.language="cs" /d:sonar.exclusions="**/bin/**/*,**/obj/**/*" /d:sonar.cs.opencover.reportsPaths="$TRAVIS_BUILD_DIR/lcov.opencover.xml"" exited with 1.`

My .travis.yml:
```yml
language: csharp
mono: none
dotnet: 2.1.401

install:
  - dotnet tool install --global dotnet-sonarscanner
  - dotnet restore ToolBox/ToolBox.csproj
  - dotnet restore ToolBox.Tests/ToolBox.Tests.csproj

script:
  - dotnet sonarscanner begin /k:"dein:toolbox" /n:"ToolBox" /v:"1.4.1" /o:"dein" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$SONAR_KEY" /d:sonar.language="cs" /d:sonar.exclusions="**/bin/**/*,**/obj/**/*" /d:sonar.cs.opencover.reportsPaths="$TRAVIS_BUILD_DIR/lcov.opencover.xml"
  - dotnet build ToolBox/ToolBox.csproj
  - dotnet test ToolBox.Tests/ToolBox.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=\"opencover,lcov\" /p:CoverletOutput=../lcov
  - dotnet sonarscanner end /d:sonar.login="$SONAR_KEY"

after_success:
  - dotnet pack ToolBox/ToolBox.csproj /p:NuspecFile=/ToolBox/ToolBox.nuspec -o Package/ -c release
  
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push Package/dein.ToolBox.*.nupkg -k $NUGET_KEY -s $NUGET_URL
  on:
    branch: master
```

Job Log:
https://travis-ci.com/deinsoftware/toolbox/jobs/142169452

CC: @akoeplinger @nterry
