### ISSUE TITLE
Clarification on using `travis encrypt` for passwords

### ISSUE THREAD

**Issue by maphew** [travis-ci/travis-ci#10051]
I'm following the instructions for pypi deployment, https://docs.travis-ci.com/user/deployment/pypi/. 

I ran `travis encrypt deploy.password` it doesn't ask for a password, yet still returns a long secure string. Where is it getting this from? I would expect a _"nothing to encrypt"_ error response.

Then I thought the docs are literal, that I should actually write my password in the .travis.yml file and that then the client will rewrite it. So i did that and ran the command `travis --add encrypt deploy.password`. Nope. This added a global env section to the file and left my password in plain text. Subsequent runs append additional `secure` entries, each one different.

```
~/.gem/ruby/2.3.0/bin/travis encrypt deploy.password --add
Environment variables in env.global should be formatted as FOO=bar
```

```
deploy:
  provider: pypi
  user: mypipyusername
  password: password1234
env:
  global:
    secure: anTy29nDryAbGk/RtHGmbmEChfXANmHgyK/aTNMv6J{....snip...}
    secure: R23pwVI/TJwWgBL6iheZbpKNNCgnz5ZDmvy+cSNmHs{....snip...}
```

[A comment to #8339](https://github.com/travis-ci/travis-ci/issues/8339#issuecomment-327633364) from last year indicates there is supposed to be an interactive mode described in the PyPi deploy document, but that's not there now.

I figured out interactive mode is triggered by `travis {command}` without parameters.

```
~/.gem/ruby/2.3.0/bin/travis encrypt
password1234<enter><ctrl-d>
Reading from stdin, press Ctrl+D when done
Please add the following to your .travis.yml file:

  secure: "n1OouRnbgRRZ6P89b7lm8IoUb5L6+G3KLX7YvLT{...snip...}
````

So here are 3 different ways of returning a `secure` string. All of them produce a different string each time. What is the correct method and how to verify?
