### ISSUE TITLE
"Skipping because this is not a tagged commit" after `git checkout $TAG`

### ISSUE THREAD

**Issue by maphew** [travis-ci/travis-ci#10052]
In my travis.yml I checkout a tagged release but Travis later tells me it's not a tagged release and won't deploy it: _"Skipping a deployment with the pypi provider because this is not a tagged commit"_

 Log: https://travis-ci.org/leo-editor/leo-editor/builds/422253973

Relevant portions of config (full file [here](https://github.com/leo-editor/leo-editor/blob/b17c76e192d929acb984323e06492661ebd087ab/.travis.yml)):
```
install:
    - git fetch --tags --depth=500
    - git checkout 5.8-b2
{...snip...}
deploy:
  provider: pypi
{...snip...}
  on:
    tags: true
    branch: travis
```

I've read many similar issues here but they don't seem to map to my situation. The release tag is created by someone else. To be safe I issued `git push origin --tags` anyway, but that didn't change anything (git said _"Everything up-to-date"_).
