### ISSUE TITLE
D: allow_failures matrix can't handle d array

### ISSUE THREAD

**Issue by ljmf00** [travis-ci/travis-ci#10063]
Basically Travis-CI ignore allow_failures rule when:
```yml
matrix:
  allow_failures:
    d:
      - gdc
```

![image](https://user-images.githubusercontent.com/5050669/44938488-454a2280-ad77-11e8-9200-119938ef8aa8.png)
