### ISSUE TITLE
bug(sonarcloud): Build failed, if non-internal pull-request

### ISSUE THREAD

**Issue by Kristinita** [travis-ci/travis-ci#10062]
Related issues: **#8379**, **#9791**.

### 1. Summary

**If** I add to my `.travis.yml` sonarcloud addon **and** external pull request for my repository:

    build failed.

I think, that skip sonarcloud step will be better in this case.

### 2. Data

Part of [**my `.travis.yml`**](https://github.com/Kristinita/SashaErichekCodeClimate/blob/ff6718e0380a09d5cf3eba54c3681711ec15ad11/.travis.yml):

```yaml
language: python
python: 3.7
dist: xenial
sudo: true
addons:
  sonarcloud:
    organization: "kristinita-github"
    token:
      secure: l25Sq44wt7NOHXfqlOr7hdS3i4VjP1Anh5INkischOk4TLrvwZMd+8P1e4LqA8cnkTSzaSoQHYNElYVzwKWrWiJnxrHLceXVCw7htzCPHV36Krl/mZogDmuqK9B2rMArqKybHex9i9ncRfL/+R9e8oz0dkNf1ZS48/Qu+kJ4Q2RUEUeVU3/trRJKbCYmmqqk6jC0tyxna5lrnevxkQvw8i3EtUp/lB/zZkI4pyhkBPWkQqoJSK32RTNj1oIkk2O+3LQFTNujnZhsMYNks911ZxbiahPAHpJHZ1JccM6zOzQtd1XsaTkGQCeBcUy6P6ouxigC/HkB681PQ/Sw4kcaR5QrAzxHcG96TrMbi9bZ3w2V+lFfKAc4ytB0Xq3FviHej21pu/tppPpoVZbn9WbkEndtOvqtFy/WG26kYrrA+VMMVam2rajL3myuq46YjIvK2mtuaCTZnNgz3WbPzVv5qUp50uYZOMfkoFKh7J6vXzW1qWW2ubmAaRNFz/wevMh3tkg+VcU94cj1p6Zz6HZFVuhYm7JO2+BwSerJjH+VRDPHkItZWIjN2BOEghZSwUn6V6c+f6PXfEVeYlg9cj+3Bz5e5eOXYSip2936XApcP/sKXBPAwqlBAOLctEgicEU13+ySq/6ljul9J09Kps0bg3PR8iralQAPRBSwSvXGPRY=
install:
- pip install --upgrade pip
script:
- sonar-scanner
```

### 3. Steps to reproduce

[**I add SonarCloud to Travis CI**](https://docs.travis-ci.com/user/sonarcloud/#inspecting-code-with-the-sonarqube-scanner) → external user KristinitaTest [**create a pull request**](https://github.com/Kristinita/SashaErichekCodeClimate/pull/1) to my repository.

### 4. Expected behavior

Skip SonarColud step, if external user create a pull request.

### 5. Actual behavior

[**Travis CI build failed**](https://travis-ci.org/Kristinita/SashaErichekCodeClimate/builds/422984962#L460-L464):

```text
$ sonar-scanner
sonar-scanner: command not found


The command "sonar-scanner" exited with 127.
```

### 6. Next actions

I add KristinitaTest user to collaborator → [**KristinitaTest create a pull request again**](https://github.com/Kristinita/SashaErichekCodeClimate/pull/2) → [**build successful passed**](https://travis-ci.org/Kristinita/SashaErichekCodeClimate/builds/422990995). So I think the problem is not my personal settings.

Thanks.
