### ISSUE TITLE
PHPUnit exists with status 2

### ISSUE THREAD

**Issue by jackthehack21** [travis-ci/travis-ci#10098]
Hi, I have a project I. My organisation setup with Travis-ci.com and I’ve set my .travis.yml to 
```yaml
language: php
php:
- '7.2.0'

before_script:
  - if find . -name "*.php" ! -path "./vendor/*" -exec php -l {} \; | grep -v "No syntax errors detected"; then exit 1; fi

after_success:
  - wget https://raw.githubusercontent.com/FusionCraft/FusionEssentials/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/FusionCraft/FusionEssentials/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
```
With all variables named and setup but no matter what phpunit seems to run after my lint and always return exit code 2

Build log:
https://api.travis-ci.com/v3/job/144775242/log.txt
