### ISSUE TITLE
Cannot select a subfolder to deploy on Azure 

### ISSUE THREAD

**Issue by iwannabebot** [travis-ci/travis-ci#10103]
This is my yml file:

```
language: node_js
node_js:
  - "stable"
env:
  - NODE_ENVIRONMENT= $NODE_ENVIRONMENT
cache:
  directories:
  - website/node_modules
script:
  - npm run build

deploy:
  - provider: azure_web_apps
    skip_cleanup: true
    username: $azure_deployment_user       # If AZURE_WA_USERNAME isn't set
    password: $azure_deployment_password   # If AZURE_WA_PASSWORD isn't set
    site: $azure_deployment_sitename       # If AZURE_WA_SITE isn't set
    verbose: true
    on:
      branch: master
```

The build command would build the distributable in a subfolder. 

### **How can I select that subfolder to deploy on Azure Web App?**

**Comment by BanzaiMan** [comment]
Could you try changing into the app's directory in `before_deploy`?

```yaml
deploy:
  - provider: azure_web_apps
    before_deploy:
      - cd $TRAVIS_BUILD_DIR/subdir
    ⋮ # rest
```
