### ISSUE TITLE
Travis allow_failures AND condition

### ISSUE THREAD

**Issue by dakshinai** [travis-ci/travis-ci#10114]
I have a travis build file that looks like as described below (retracted). With allow_failures I would like to select rows from build matrix to meet condition go=tip AND JOB=check However travis evaluates it as go=tip OR JOB=check

Is there a way to achieve the AND condition for my specific case?

```
go:
    - 1.8
    - 1.9
    - tip

env:
    global:
        - GOARCH=amd64
    matrix:
        - JOB=docker
        - JOB=deb
        - JOB=rpm
        - JOB=check

matrix:
    allow_failures:
        - go: tip
        - env: JOB=check
```

**Comment by iriberri** [comment]
Hi @dakshinai!

I think you could achieve what you need with:

```
matrix:
    allow_failures:
        - go: tip
          env: JOB=check
```

Note that the `env` is no longer included as a new item in the `allow_failures` list, but nested into the `go: tip` one.

Would you like yo try this and let us know if this helps?

Thanks!
