### ISSUE TITLE
fastlane: command not found

### ISSUE THREAD

**Issue by barreeeiroo** [travis-ci/travis-ci#10124]
Hello
I get the following error when trying to deploy using a custom script:

> Successfully installed fastlane-2.104.0
> 56 gems installed
> INFO -> Pushing to Play Store
> /home/travis/build/Makeroid/Makeroid-Builder/.travis/deploy-to-play.sh: **line 7: fastlane: command not found**
> Script failed with status 127

The deploy section of my travis.yml looks like this:
```
language: java

...

deploy:
  - provider: script
    script: bash $TRAVIS_BUILD_DIR/.travis/deploy-to-play.sh
    on:
      branch: Makeroid/BETA
    skip_cleanup: true
```

The deploy-to-play.sh is this fle:

```
#!/bin/bash
set -e

printf "INFO -> Installing Fastlane\n\n"
gem install fastlane
printf "INFO -> Pushing to Play Store\n\n"
fastlane supply --apk $TRAVIS_BUILD_DIR/appinventor/build/buildserver/Makeroid.apk --track alpha --json_key $TRAVIS_BUILD_DIR/.travis/play-store.json --package_name io.makeroid.companion
```

---

Why does this happen?
