### ISSUE TITLE
Overridden TRAVIS_TAG results in push build loop

### ISSUE THREAD

**Issue by atrauzzi** [travis-ci/travis-ci#10127]
I've been getting build loops as a result of using the github release plugin.  All my builds have been using `if: tag IS blank` at the top to prevent builds of tags from happening.

Seems to have started happening ~Friday of last week for me.

**Comment by asalom** [comment]
We have exactly the same problem, we started encountering it since today Monday in the morning. Our build generates a GitHub release which in turn fires a new build, thus making an infinite loop.

We only allow build from `develop` and `master` branches 

```yml
branches:
  only:
    - master
    - develop
```

**Comment by BanzaiMan** [comment]
Hello, there. We are looking into this issue now. Could you tell us where the issue is observed?

**Comment by asalom** [comment]
Is this enough?
https://travis-ci.com/crvshlab/goat-ios/builds

**Comment by atrauzzi** [comment]
- https://travis-ci.com/artmoi/artmoi-server/builds
- https://travis-ci.com/artmoi/artmoi-api/builds

**Comment by BanzaiMan** [comment]
Thank you for the info.

**Comment by BanzaiMan** [comment]
I'm looking at the repositories mentioned, but it appears to me that the conditions are working as expected. (Go to the repository's respective "requests" tab—e.g., https://travis-ci.com/artmoi/artmoi-api/requests—to confirm.)

What is happening is that something is creating a build request infinitely (apart from these rejected requests), and we are building them.

See also: https://www.traviscistatus.com/incidents/0y7jrv67j81x

**Comment by atrauzzi** [comment]
These requests are coming as a result of travis builds.  Travis is the only system triggered by my source control as well as the only system that writes to my source control.  You can see that on Friday night into Saturday, I had a substantial number of repeated builds for the same hash.

**Comment by BanzaiMan** [comment]
@atrauzzi Understood. I am pointing out that the issue is not the condition as the description suggests, but that we are creating excess builds.

**Comment by BanzaiMan** [comment]
During the builds, do you push anything to GitHub: a tag, a branch, etc.?

**Comment by atrauzzi** [comment]
Not during the build, no.  I only reach out to git through the travis-ci releases plugin.

**Comment by meatballhat** [comment]
@atrauzzi Are you able to share if/how your job is configured to run `git tag`?  I can see that for a series of "echoed" jobs for the same commit that the tag detected at GitHub release deploy time is different each time.

**Comment by atrauzzi** [comment]
I don't call git tag at all, but I do overwrite `TRAVIS_TAG` as part of my initial setup so that the release plugin triggers and uses the correct semver string.

```
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    target_commitish: $TRAVIS_COMMIT
    file: "${VERSIONED_PACKAGE}.zip"
    on:
      tags: true
```

**Comment by meatballhat** [comment]
@atrauzzi that's very helpful, thank you!

**Comment by meatballhat** [comment]
@atrauzzi Thanks to your feedback, I've been able to reproduce the problem, although I don't yet have an explanation for why this started affecting you in the last few days.  Non-deterministic tagging, when combined with the deploy `on.tags: true` and a top condition `if: tag IS blank` should _always_ result in this kind of job creation loop.  I'm confused about why it wasn't happening earlier.

@atrauzzi @asalom Are you able to confirm the presence of a dynamically defined `TRAVIS_TAG` env var with a non-deterministic value, or at least a value that isn't strictly tied to the commit?

**Comment by asalom** [comment]
I don't understand, do you want to know how we name the tags? We use a different way to create releases and their names are date and time based. In the following screenshot you can see all tags having the same commit. After the last one shown there I manually stopped the next build.

<img width="224" alt="screen shot 2018-09-18 at 10 19 20" src="https://user-images.githubusercontent.com/1466079/45673966-5c856000-bb2c-11e8-8795-f1d320c355b6.png">

**Comment by sacreman** [comment]
Same exact deal for us. We create a tag on merge to master after a successful pull request.

Up until Friday last week the merge to master simply ran the tag script to push a tag back to Github and that was it.

Now it triggers a new Travis job. Which generates a new tag. Which creates a new Travis job. Forever in a loop until we cancel.

I've logged a support ticket too via support@travis-ci.com

**Comment by asalom** [comment]
I recreated the issue here: https://github.com/asalom/travis-build-loop
Making a Release (pushing a tag), triggers the next build

**Comment by asalom** [comment]
I reproduced the issue in this repo: https://github.com/asalom/travis-build-loop

What caused the infinite loop was to dynamically generate a file that gets deployed each time

```yml
branches:
  only:
    - master

script:
  - echo `date "+%Y-%m-%d_%H_%M_%S"` > deploy.txt

before_deploy:
  - git config --local user.name asalom
  - git config --local user.email $GITHUB_EMAIL
  - git add deploy.txt
  - git commit -m "add deploy.txt"
  - git tag `date "+%Y-%m-%d_%H_%M_%S"`

deploy:
  on:
    branch: master
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: deploy.txt
```
<img width="780" alt="screen shot 2018-09-18 at 11 33 06" src="https://user-images.githubusercontent.com/1466079/45678471-b854e680-bb36-11e8-97e7-76c9c64be813.png">
