### ISSUE TITLE
add on_error configuration option for notifications

### ISSUE THREAD

**Issue by ericcj** [travis-ci/travis-ci#1013]
so one could do the following, for example:

```
notifications:
  email:
    on_error: never
```

this would be especially handy if you're using the before scripts to selectively abort builds like we are

**Comment by psprint** [comment]
I think that the feature would be very useful, because the builds often error from random reasons, like e.g.: lack of memory on the given build machine. So, if one has:
```
notifications:
  email:
    recipients:
    - …
    on_success: change
    on_failure: change
```

Then this will lead to a series of emails – on change from errored to success/failure and vice-versa.
