### ISSUE TITLE
Documentation how to use SONAR_TOKEN

### ISSUE THREAD

**Issue by tillias** [travis-ci/travis-ci#10138]
I'm trying to integrate sonarcloud with Travis CI. In the documentation there is written 

> Encrypt this token travis encrypt abcdef0123456789 or define SONAR_TOKEN in your Repository Settings
https://docs.travis-ci.com/user/sonarcloud/ 

How can I use this SONAR_TOKEN inside .travis.yml without "secure"? Can you please provide example and update documentation?

**Comment by macedoj** [comment]
@tillias, so simple, just following the steps below :+1: 

1.   First of all, go to https://sonarcloud.io/, make login with your GitHub account and enable the Sonar scan in your repository;

2. After enable Sonar scan, following the steps indicates and create new token called __SONAR_TOKEN__;

3. Copy the value of the token and go to __travis-ci__;

4. Then, go to your repository, click in __More options__ > __Settings__ and create an _Environment Variables_ called __SONAR_TOKEN__ with the value you are copied before;

> Travis-ci and SonarCloud configs are done!

5. Now, in your root project you need to create two files,
    > [__.travis.yml__](https://github.com/macedoj/java-new-features/blob/master/.travis.yml)
    >  [__sonar-project.properties__](https://github.com/macedoj/java-new-features/blob/master/sonar-project.properties)

6. Put in your __.travis.yml__ the code below:

```yml 
dist: trusty

addons:
  sonarcloud:
    organization: "your-sonar-organization-name" # To find your organization, go to: https://sonarcloud.io/account/organizations

script:
  # Put before sonar-scanner your other script steps
  - sonar-scanner -Dsonar.verbose=true -X
```

7. Edit your __sonar-project.properties__ and change the values with your values:

```gradle
    sonar.projectKey=your_project_key
    sonar.organization=your-sonar-organization-name
    sonar.host.url=https://sonarcloud.io
    sonar.projectName=your-project-name
    sonar.projectVersion=1.0-SNAPSHOT

    sonar.language=your-application-programming-language
```

8. Well done, just make some commit in your repository and things work :metal: 

Hope this helps! :+1: 
Keep code :coffee:
