### ISSUE TITLE
addons homebrew not working 

### ISSUE THREAD

**Issue by untereiner** [travis-ci/travis-ci#10149]
Hi everyone,

I try to use the homebrew addons on travis-ci.org but it is not working.
The script below outputs a log that shows [Qt is not installed](https://travis-ci.org/cgogn/SCHNApps/jobs/432908050)
```
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: "ppa:beineri/opt-qt58-trusty"
    packages:
      - gcc-5
      - g++-5
      - libglu1-mesa-dev
      - qt58base
  homebrew:
    packages:
      - qt5 
```
replacing the last part of this script by the lines below enables Qt on macos

```
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5 ; fi

```

Has anyone experienced the same issue ?
