### ISSUE TITLE
Changing value to `Xcode10` in .travis.yml makes build fail

### ISSUE THREAD

**Issue by abinrm** [travis-ci/travis-ci#10176]
My Xcode project developed in Swift 4, passes CI when the xcode9.3 is given in .travis.yml, but when I changed this to Xcode10, the project fails to build. My .travis.yml file is 
```
language: objective-c
osx_image: xcode10

cache:
  directories:
    - Carthage
    - CookIslands/Carthage

env:
  #environment variables
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - PROJECT_NAME="MyProject.xcodeproj"
    - SCHEME_IOS_FRAMEWORK="MyFramework_iOS"
    - SCHEME_IOS="myAppScheme"
    - IOS_SDK=iphonesimulator12.0
  matrix:
    - DESTINATION="OS=12.0,name=iPhone X" SCHEME="$SCHEME_IOS" SDK="$IOS_SDK"
before_install:
  - git submodule update --remote
  - gem install license_finder

script:
  - xcodebuild test -project "$PROJECT_NAME" -scheme "$SCHEME" -destination "$DESTINATION" -sdk "$SDK" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO

```
The log from travis when it fails is 
```
*** Checking out cryptoswift at "0.12.0"
*** Checking out Alamofire at "4.7.3"
*** Checking out SwiftyJSON at "4.2.0"
*** Cloning Alamofire
*** Cloning cryptoswift
*** Cloning SwiftyJSON
*** No cache found for Alamofire, building with all downstream dependencies
*** No cache found for cryptoswift, building with all downstream dependencies
*** No cache found for SwiftyJSON, building with all downstream dependencies
*** xcodebuild output can be found in /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/carthage-xcodebuild.T5YzvO.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/travis/build/riskmethods/mobile-companion-ios/CookIslands/Carthage/Checkouts/Alamofire/Alamofire.xcworkspace -scheme Alamofire\ iOS -configuration Release -derivedDataPath /Users/travis/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A255/Alamofire/4.7.3 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/Alamofire SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/travis/build/riskmethods/mobile-companion-ios/CookIslands/Carthage/Checkouts/Alamofire)
This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/carthage-xcodebuild.T5YzvO.log
Command PhaseScriptExecution failed with a nonzero exit code
Testing failed:
	Command PhaseScriptExecution failed with a nonzero exit code
	Testing cancelled because the build failed.
** TEST FAILED **
The following build commands failed:
	PhaseScriptExecution Carthage /Users/travis/Library/Developer/Xcode/DerivedData/Rarotonga-gggnxivmhwydckhizgntpnbeystt/Build/Intermediates.noindex/CookIslands.build/Debug-iphonesimulator/CookIslands_iOS.build/Script-8302CBBB1FE7DD2F00C93991.sh
(1 failure)
The command "xcodebuild test -project "$PROJECT_NAME" -scheme "$SCHEME" -destination "$DESTINATION" -sdk "$SDK" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO" exited with 65.
cache.2
store build cache
0.01s
2.77snothing changed, not updating cache
Done. Your build exited with 1.
```
When I revert back value to xcode9.3 and iphonesimulator11.3, passes CI tests. What could be the reason for this? In my local machine I am using Xcode 10.0 (Swift 4), and everything works fine.

**Comment by BanzaiMan** [comment]
What does the log say? I believe you can get it by:

```yaml
after_failure:
  - cat $TMPDIR/carthage-*.log
```

**Comment by cotsog** [comment]
Could you include a link to a build showing where this is happening? If it's for a private repository, please send it over at support [at] travis-ci [dot] com. Thanks!

**Comment by abinrm** [comment]
This is from the log 
```
<unknown>:0: error: unable to load standard library for target 'arm64-apple-ios8.0-simulator'
** ARCHIVE FAILED **
The following build commands failed:
	CompileSwift normal armv7
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
	CompileSwift normal arm64
(4 failures)
```

**Comment by abinrm** [comment]
@cotsog  It is a private repository. I will mail it over the email id provided.

**Comment by mjm** [comment]
@abinrm I can't say with certainty what's going on, but it my top theory right now is that this is an issue somehow caused by the new build system in Xcode 10. While present in Xcode 9, it became the default in Xcode 10 and can affect the behavior of the build in some subtle ways.

Is there more in the log file from Carthage? The end of the log will show that some commands failed, but higher up in the log there are probably more specific error messages that might reveal what is going on.

**Comment by abinrm** [comment]
Here is the complete log
[log.txt](https://github.com/travis-ci/travis-ci/files/2442660/log.txt)

**Comment by mjm** [comment]
Thanks for the info! The error looks to me like the xcodebuild that is being triggered for your dependencies is getting some confusing information about whether it should be building for a real iOS device (ARM architectures) or a simulator (x86 architectures). It's using the iOS SDK, but then trying to pass an iOS simulator deployment target, but not quite, because that target has an ARM architecture. That's not a valid target for the build, so Xcode fails.

Can you tell me what commands you have in script phases in your project that are calling Carthage? It seems Carthage is building your dependencies during your Xcode build, and I suspect that is what is causing your issue. There are a lot of environment variables present in scripts invoked from a script phase in Xcode, and running other builds inside that could inherit that environment and cause problems.

I don't see any calls to Carthage in your .travis.yml. I think you may want to add this to your Travis config:

```
before_install:
- carthage bootstrap
```

And remove any similar command from your Xcode build phases. This will take your builds out of the Xcode build environment, which may produce more predictable results.

**Comment by abinrm** [comment]
@mjm These are the commands I use in build phase
![screenshot 2018-10-04 at 14 50 20](https://user-images.githubusercontent.com/36157771/46475117-f1eb4a00-c7e4-11e8-8182-71e6a80d1186.png)

I added the following to .travis.yml and removed the scripts from build phases
```
before_install:
- carthage bootstrap
```
Still having the same error, 
The complete log 
[log.txt](https://github.com/travis-ci/travis-ci/files/2446438/log.txt)

**Comment by mjm** [comment]
Looking at your logs, it seems like the `carthage bootstrap` command in `before_install` is working! You can actually change that to be the same bootstrap command you have in your script phase (with all those extra arguments) and probably have the build be faster.

The log also shows that Carthage builds are still happening while building your Xcode project, and that is still where the failure is happening. The script phase named "Carthage" (which runs `carthage bootstrap`) should be removed, though the "Carthage Copy Frameworks" phase can and should stay.

**Comment by abinrm** [comment]
I followed it still having the same issue
![screenshot 2018-10-05 at 09 56 16](https://user-images.githubusercontent.com/36157771/46523085-f23b2200-c884-11e8-8e06-f59466fc4026.png)

Log file : 
[log.txt](https://github.com/travis-ci/travis-ci/files/2449428/log.txt)

The time for the build was reduced to half.

**Comment by abinrm** [comment]
Thanks To @mjm. I updated my .travis.yml file like below and now my project builds in Travis Environment
```
language: objective-c
osx_image: xcode10

cache:
  directories:
    - Carthage
    - CookIslands/Carthage

env:
  #environment variables
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - PROJECT_NAME="MyProject.xcodeproj"
    - SCHEME_IOS_FRAMEWORK="MyFramework_iOS"
    - SCHEME_IOS="myAppScheme"
    - IOS_SDK=iphonesimulator12.0
  matrix:
    - DESTINATION="OS=12.0,name=iPhone X" SCHEME="$SCHEME_IOS" SDK="$IOS_SDK"

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - git submodule update --remote
  - gem install license_finder
  - carthage bootstrap --no-use-binaries --platform iOS
  - cd CookIslands && carthage bootstrap --no-use-binaries --platform iOS && cd ..

script:
  - xcodebuild test -project "$PROJECT_NAME" -scheme "$SCHEME" -destination "$DESTINATION" -sdk "$SDK" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO

after_failure:
  - cat $TMPDIR/carthage-*.log 
```
