### ISSUE TITLE
environment variables are not set in a deterministic order

### ISSUE THREAD

**Issue by benoit-pierre** [travis-ci/travis-ci#10173]
Config:
```yaml
env:
  PYTHON_VERSION: 3.6
  PYTHON_VERSION_MICRO: 2
  PYTHON_INSTALLER: python-$PYTHON_VERSION.$PYTHON_VERSION_MICRO-macosx10.6.pkg
  PYTHON_INSTALLER_URL: https://www.python.org/ftp/python/$PYTHON_VERSION.$PYTHON_VERSION_MICRO/$PYTHON_INSTALLER
  PYTHON_INSTALLER_MD5: 86e6193fd56b1e757fc8a5a2bb6c52ba
  PATH: /Users/travis/Library/Python/$PYTHON_VERSION/bin:$PATH
```

Results:
* https://travis-ci.com/benoit-pierre/python-rtmidi/builds/86705733#L59
* https://travis-ci.com/benoit-pierre/python-rtmidi/builds/86705204#L48
