### ISSUE TITLE
Job doesn't start

### ISSUE THREAD

**Issue by vincentcox** [travis-ci/travis-ci#10195]
I don't know why, but somehow the job doesn't start. I have a build which triggers 3 jobs: 2 finish normally, the last one (with docker=true) is not working. Any idea why?

https://travis-ci.org/vincentcox/StaCoAn/jobs/438240383

![image](https://user-images.githubusercontent.com/9286611/46582430-ded7b480-ca46-11e8-82a3-62660af70c0e.png)

**Comment by BanzaiMan** [comment]
Sorry, but `os: windows` is not usable. Please cancel the job and remove this job.

**Comment by vincentcox** [comment]
Ok, I will use a different parameter then because the OS is build in. My program builds for different platforms (for windows it uses a program to build a .exe from python code).

Instead of the "os: windows" I will use "os: linux", but add a variable "targetOS" like this:

```
matrix:
  include:
   - os: linux
        targetOS="windows"
```
But that doesn't work. How can I set a variable in Travis so I can use it in my IF functions?

**Comment by BanzaiMan** [comment]
What `if` function are you talking about? Besides, the segment you've shown doesn't look like valid YAML.

**Comment by BanzaiMan** [comment]
It seems to me that `TARGETOS` should go in `env`. In other words, something like (untested):

```yaml
matrix:
  include:
    - os: linux
      env:
        - TARGETOS=linux
      dist: trusty
      sudo: required
      language: python
      python: 3.6.2
    - os: osx
      env:
        - TARGETOS=osx
      sudo: required
    - os: linux
      language: python
      python: 3.6.2
      env:
         - DOCKER=true TARGETOS=windows
      services:
        - docker
```
