### ISSUE TITLE
Using jobs disables matrix jobs

### ISSUE THREAD

**Issue by Flamefire** [travis-ci/travis-ci#10229]
Related to #1500 

How are the jobs/stages/matrix stuff to be used? There are currently 3 things:

1. Toplevel `compiler`, `env`, ... expand to the cartesian product of those options as jobs in an undefined/default(?) stage
2. `matrix` `exclude` removes such jobs and `include` adds more
3. `jobs` `include` is given as an example. It seems to do the same as `matrix.include`. Are there more options?

Judging from https://github.com/travis-ci/travis-yml/blob/b962dfdf91ebeebb606d3dfa71c9984891e19d34/spec/travis/yaml/doc/spec/map_spec.rb it seems that `jobs` is the same as `matrix`. Is this correct? If yes, then the behaviour can be explained by the `jobs.include` replacing `matrix.include`.

**Comment by BanzaiMan** [comment]
Yes. `jobs` is an alias for `matrix`. If you have both at the top level, the last one wins.

**Comment by BanzaiMan** [comment]
Yes, we will look into that.

**Comment by plaindocs** [comment]
Hey @Flamefire 

Both of these things are in our backlog. I'll what I can do about a quick fix.

**Comment by jasonkarns** [comment]
I think this is the issue I'm running into but I'm thoroughly confused:

```
language: node_js
os:
  - linux
  - osx
jobs:
  include:
    - stage: verify definitions
      script: npm run verify-definitions
```

This results in 3 jobs (first 2 in parallel), exactly as desired:

1. linux + npm test
2. macOS + npm test
3. linux + npm run verify definitions

However, removing the OS array doesn't reduce the jobs by 1, as one would expect. The OS still defaults to linux, so I would expect that removing the macOS line would result in the same default linux + npm test job as above, as well as the linux + npm run verify definitions job. Instead, removing the os array reduces the jobs by _two_!

```
language: node_js
jobs:
  include:
    - stage: verify definitions
      script: npm run verify-definitions
```

Results in only a single job that _only_ runs the verify-definitions script. Where did the default linux + npm test job go?
