### ISSUE TITLE
Building openssl using musl fails on Travis

### ISSUE THREAD

**Issue by kaushalmodi** [travis-ci/travis-ci#10226]
Hello,

Here is my Travis config file: https://github.com/kaushalmodi/hello_musl/blob/master/.travis.yml

Travis job fail log: https://travis-ci.org/kaushalmodi/hello_musl/builds/440273887#L1377

Here is the apt package installation section:

```
addons:
  apt:
    packages:
      # For building MUSL static builds on Linux.
      - musl-tools
      # To fix "engines/e_afalg.c:24:27: fatal error: linux/version.h: No such file or directory" on Travis
      #  - https://travis-ci.org/kaushalmodi/hello_musl/builds/440269504
      #  - https://travis-ci.org/kaushalmodi/hello_musl/builds/440268459
      #  - https://github.com/mirage/mirage-block-unix/issues/45#issuecomment-196892988
      #  - https://github.com/travis-ci/travis-ci/issues/5616
      - linux-headers-4.4.0-98-generic
```

Failure:

```
musl-gcc -static  -I. -Iinclude -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -fPIC -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/home/travis/build/kaushalmodi/hello_musl/openssl/1.1.1/ssl\"" -DENGINESDIR="\"/home/travis/build/kaushalmodi/hello_musl/openssl/1.1.1/lib/engines-1.1\"" -DNDEBUG -DOPENSSL_NO_SECURE_MEMORY -MMD -MF ssl/bio_ssl.d.tmp -MT ssl/bio_ssl.o -c -o ssl/bio_ssl.o ssl/bio_ssl.c
engines/e_afalg.c:24:27: fatal error: linux/version.h: No such file or directory
 #include <linux/version.h>
                           ^
musl-gcc -static  -I. -Iinclude -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -fPIC -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/home/travis/build/kaushalmodi/hello_musl/openssl/1.1.1/ssl\"" -DENGINESDIR="\"/home/travis/build/kaushalmodi/hello_musl/openssl/1.1.1/lib/engines-1.1\"" -DNDEBUG -DOPENSSL_NO_SECURE_MEMORY -MMD -MF ssl/d1_lib.d.tmp -MT ssl/d1_lib.o -c -o ssl/d1_lib.o ssl/d1_lib.c
compilation terminated.
```

How can I resolved that "engines/e_afalg.c:24:27: fatal error: linux/version.h: No such file or directory" error?
