### ISSUE TITLE
Allow nested lists for script and install

### ISSUE THREAD

**Issue by Flamefire** [travis-ci/travis-ci#10234]
Similar to https://github.com/travis-ci/travis-ci/issues/3505:

Can you allow list of lists for the scriptish keys (`script`, `install`,...)?

This is useful for yaml references:

```
install: &defInstall
  - get foo
  - get bar
matrix:
  include:
    - install:
      - *defInstall
      - get baz
```

**Comment by junaruga** [comment]
@Flamefire  I think you can run without nested list like this with `<<:`.

```
install: &defInstall
  - get foo
  - get bar
matrix:
  include:
    - install:
      - <<: *defInstall
      - get baz
 ```

See https://github.com/ruby/ruby/blob/trunk/.travis.yml#L269
