### ISSUE TITLE
toplevel os key does not expand matrix

### ISSUE THREAD

**Issue by DanielRuf** [travis-ci/travis-ci#10237]
See https://travis-ci.org/zurb/foundation-sites/builds/441371097

I thought the toplevel os key would expand it.

**Comment by BanzaiMan** [comment]
It did. https://github.com/zurb/foundation-sites/blob/4da6731c521ecc40b4120c1aaccf5e8136560c10/.travis.yml#L3-L6 correspond to the first 3 jobs, Windows, Linux, and macOS. https://github.com/zurb/foundation-sites/blob/4da6731c521ecc40b4120c1aaccf5e8136560c10/.travis.yml#L8-L17 correspond to jobs 4-7, which inherited the first `os` value of the top level, which is `windows`.

**Comment by DanielRuf** [comment]
> inherited the first `os` value of the top level, which is `windows`

Why not all? I expected that the matrix jobs are expanded.

**Comment by DanielRuf** [comment]
And the `include` statement is a bit unclear how it would look like for the same command but all three OS.

So far it feels repetitive to include / define them again with the same command.

**Comment by DanielRuf** [comment]
In contrast, I see no `matrix` key at https://github.com/BanzaiMan/travis_production_test/blob/824441d5e4be2dd79dbe03cb4f07cd08a4c55f15/.travis.yml

**Comment by BanzaiMan** [comment]
> Why not all? I expected that the matrix jobs are expanded using all three OS.

`matrix.include` *adds* to the build matrix that was created by the dimensions. It is not a dimension of matrix expansion.

> In contrast, I see no `matrix` key at https://github.com/BanzaiMan/travis_production_test/blob/824441d5e4be2dd79dbe03cb4f07cd08a4c55f15/.travis.yml

You don't have to have a `matrix` key, if your build doesn't require anything extra.

https://docs.travis-ci.com/user/customizing-the-build/#build-matrix has more information on how this works.

If your intentions is to have a build matrix of 12 jobs defined by:

```yaml
  - node_js: "lts/boron"
    env: ZF_TRAVIS_COMMAND=test:javascript:units
  - node_js: "lts/carbon"
    env: ZF_TRAVIS_COMMAND=test:javascript:units
  - node_js: "stable"
    env: ZF_TRAVIS_COMMAND=test:javascript:units
  - node_js: "stable"
    env: ZF_TRAVIS_COMMAND=test:javascript:browserstack
```
but with 3 OS values for each pair of `node_js` and `env` values, then unfortunately there is no easy way to achieve it without a little complex `matrix.include` and/or `matrix.exclude`, since you cannot combine multiple matrix dimensions into a single one when you construct the build matrix.
