### ISSUE TITLE
Unable to deploy to npm: 'you must be logged in'

### ISSUE THREAD

**Issue by mrichar1** [travis-ci/travis-ci#10232]
I can't get travis to deploy to npm, and keep seeing errors following the docs here: https://docs.travis-ci.com/user/deployment/npm/

```
Preparing deploy
NPM version: 6.4.1
Authenticated with email <my-email> and API key ****************8pw=
npm ERR! publish Failed PUT 401
npm ERR! code E401
npm ERR! You must be logged in to publish packages.
```

I first created a token (with read and publish permissions) on npmjs.com. Then to set up travis to deploy to npm I did the following (in my project dir) and answered the quesitons with npm login info etc:

```
travis login
travis whoami  # returns "You are mrichar1"
travis setup npm
```

.travis.yml now contains:

```
deploy:
  provider: npm
  email: <my-email>
  api_key:
    secure: ****************8pw=
  on:
    tags: true
    repo: <my-repo>
```

Is there some step or config option I'm missing?

https://travis-ci.com/mrichar1/jsonapi-vuex/builds/87788438
