### ISSUE TITLE
stage build not stopped after script run failed

### ISSUE THREAD

**Issue by AlloVince** [travis-ci/travis-ci#10248]
Hi guys

Here is my config:

``` yml
language: python
python: 3.6
node_js: 10
install:
- pip install -r requirements.txt
jobs:
  include:
    - stage: test
      if: branch = master AND tag IS blank
      script:
        - pytest tests/
        - npm install
...more
```

Also here is build log:
https://travis-ci.org/bmqb/EvaScrapy/builds/442510777

The first script `pytest tests/` already failed, but follow scripts still started, please check whether it is work correct, thanks
