### ISSUE TITLE
Feature Request: Add support for PHP on windows.

### ISSUE THREAD

**Issue by ADmad** [travis-ci/travis-ci#10255]
Currently when using `language: php` with `os: windows` results in error message 
`The language 'php' is currently unsupported on the Windows Build Environment.`

**Comment by BanzaiMan** [comment]
As indicated in the blog, please redirect your Windows-related issues to https://travis-ci.community/c/windows. In particular, your issue has been reported as https://travis-ci.community/t/where-to-contribute-php-support-for-windows/304.

**Comment by TomasVotruba** [comment]
Solution is to use `sh`.

```yaml
os: windows
language: sh
before_install:
  - choco install php
  - export PATH=/c/tools/php72:$PATH
```
