### ISSUE TITLE
Ruby on Rails - ActionCable (Websockets) does not update DOM in js spec

### ISSUE THREAD

**Issue by januszm** [travis-ci/travis-ci#10259]
With the following Travis configuration and the Ruby on Rails code:

```yaml
# .travis.yml
language: ruby
rvm:
  - 2.5.1
cache: bundler
sudo: false
branches:
  only:
    - master

services:
  - mysql
  - redis-server
  - elasticsearch

before_script:
  - mysql -e 'CREATE DATABASE myproject_test;'
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/
  - bundle exec rails assets:precompile

addons:
  apt:
    sources:
      - mysql-5.7-trusty
      - google-chrome
    packages:
      - chromium-chromedriver
      - mysql-client
      - mysql-server
  chrome: stable
```

```ruby
# inside the background job ProcessSomethingJob:
def perform(input_data)
  # ...
  ActionCable.server.broadcast "operation-#{uuid}", message: "work is done!"
end
```

```javascript
# web/template part contains this JS script, which should react to the message when the background job above is done:
(function() {
  this.App || (this.App = {});
  App.cable = ActionCable.createConsumer();
}).call(this);
```

Test below passes on the local development machine (Mac OS X) and in a virtual machine (Ubuntu 18.04, VirtualBox).

```rspec
scenario "when it is ok", js: true do
    visit "/somestuff/#{uuid}/status"
    ProcessSomethingJob.perform_now(input_data)
    expect(page).to have_selector "h4", text: "work is done!"
end
```

but it fails only in Travis (Ubuntu) with the following error:

```bash
Failure/Error: expect(page).to have_selector "h4", text: "work is done!"
   expected to find visible css "h4" with text "work is done!" but there were no matches
```

It looks like the DOM is not being updated with a change from ActionCable. ActionCable correctly generates the text that is sent using the broadcast to the browser (I verified this with some hand-crafted `puts` based debugging and build logs), but in TravisCI for some reason the ActionCable's Javascript code which should update the HTML tree of the page is either not executed or fails for some reason.

Just to clarify, test passes on both Mac OS X and Linux, including virtual environment (Virtual Box, 1-core, 1GB RAM)
