### ISSUE TITLE
Script from .travis.yml does not run when including matrix script

### ISSUE THREAD

**Issue by fernandoaleman** [travis-ci/travis-ci#10268]
In my `.travis.yml` file (file contents listed below), I run a command via the `script:` but also include another `script` via the matrix include. However, when my build runs on `travis-ci.com` for my private github repo, only the last script runs (the one included in the matrix include). The original command in the `script:` does not run at all. If I remove the script from the matrix include, then the original `script:` will run. This exact `travis.yml` file has been working fine on several of my other repos until today.

Here is a link to my last travis build that passes, however only the last `script` ran:
https://travis-ci.com/1000Bulbs/okb_cookbook/jobs/152866901

Here is my `.travis.yml` file:

```
sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

install: echo "skip bundle install"

branches:
  only:
  - master

services: docker

env:
  matrix:
  - INSTANCE=test-centos-7

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify ${INSTANCE}

after_script:
  - docker images
  - docker ps -a
  - cat .kitchen/logs/kitchen.log

matrix:
  include:
  - script:
    - delivery local verify
    env: UNIT_AND_LINT=1
```
