### ISSUE TITLE
travis-web doesn't show `python` column if python image is only specified as part of matrix section

### ISSUE THREAD

**Issue by ghost** [travis-ci/travis-ci#1027]
Example build: [https://travis-ci.org/y-p/t/builds/6066930](https://travis-ci.org/y-p/t/builds/6066930)

travis.yml:

```
language: python
matrix:
  include:
    - python: 2.7
      env: FOO=true BAR=False
    - python: 2.7
      env: FAZ=true BOO=False
    - python: 2.6
      env: FOZ=true BAO=False

```
