### ISSUE TITLE
How do I prevent duplication deploys due to auto-tagged "untagged-NNNNN.." created by Travis?

### ISSUE THREAD

**Issue by kaushalmodi** [travis-ci/travis-ci#10272]
Hello,

Here is the Travis page for nim-lang/nightlies: https://travis-ci.org/nim-lang/nightlies/builds

I am deploying nightly builds with `tags: false`. It works, except that `tags: false` causes Travis to created an `untagged-NNNNN....` dummy tag, and that tag then kicks off another build:

![image](https://user-images.githubusercontent.com/3578197/47250938-0b051500-d3f9-11e8-9d00-9d7a8088fb40.png)

Here are the deploy settings from .travis.yml: https://github.com/nim-lang/nightlies/blob/c62374aec20b06d8ec0a1702675a0aea72990eb8/.travis.yml#L73-L92

```yaml
before_deploy:
  - cd "${TRAVIS_BUILD_DIR}"
  - export DEPLOY_VERSION="$(nim --version | head -n 1 | perl -pe 's/.*Version ([0-9.]+).*/\1/')"
  - export ASSETFILE="nim-${DEPLOY_VERSION}-${NIMVERSHORT}-${TRAVIS_OS_NAME}.tar.xz"
  - cp -f "${NIMDIR}/build/nim-${DEPLOY_VERSION}.tar.xz" "${ASSETFILE}"
  - echo '[phase n-1] The deploy will start now ..'

deploy:
  provider: releases
  api_key: "${GITHUB_OAUTH_TOKEN}"
  file: "${ASSETFILE}"
  name: "Nightly build $(date +'%Y-%m-%d') ${NIMVERSHORT}"
  body: >-
    This nightly release is built using https://github.com/nim-lang/Nim/tree/${NIMVER}.
    The *-linux.tar.xz release archive is built on linux, and likewise for the *-osx.tar.xz archive.
    But either file can be used to build Nim on Linux, OSX and even Windows.
  skip_cleanup: true
  on:
    condition: "! -z ${DO_DEPLOY+x}"
    tags: false
```

As you see, I am already using a condition: `condition: "! -z ${DO_DEPLOY+x}"`, and the [docs][1] say:

> `condition:` deploy when a **single** bash condition evaluates to true.

So how do I set multiple conditions that are ANDed.. I need to trigger a deploy when:

1. The `$DO_DEPLOY` env var is set, **and**
2. the tag (`$TRAVIS_TAG`?) does not begin with `untagged-`.
 
[1]: https://docs.travis-ci.com/user/deployment/#conditional-releases-with-on

**Comment by BanzaiMan** [comment]
`"! -z ${DO_DEPLOY+x}"` will always evaluate to `true`, since `${DO_DEPLOY+x}` will always contain `x`, whether or not `${DO_DEPLOY}` is empty.

**Comment by kaushalmodi** [comment]
DO_DEPLOY is not the problem. I got it working with that. The "+x" is a known trick. 

The issue is that I cannot figure out a condition when that "untagged-.." branch is building. 

How do I detect that, and prevent redeployment of that?

**Comment by BanzaiMan** [comment]
Try skipping building `/untagged-.*/`. https://docs.travis-ci.com/user/customizing-the-build/#building-specific-branches

**Comment by kaushalmodi** [comment]
@BanzaiMan thanks. So the below will probably work:

```yaml
branches:
  only:
    # Prevent building the auto tagged "untagged-*" commits.
    # https://docs.travis-ci.com/user/customizing-the-build/#safelisting-or-blocklisting-branches
    - master
```

*I cannot test that yet because GitHub has disabled web-hooks due to the issues seen today and yest.* I'll update this thread and close this issue once that is confirmed.

Thanks!
