### ISSUE TITLE
Build failed some licences have not been accepted

### ISSUE THREAD

**Issue by KKaKa** [travis-ci/travis-ci#10291]
Can any one help me?

Stuck from my side.

https://travis-ci.org/KKaKa/KotlinDouban/builds/445533183

my .travis.yml is
```
language: android
jdk: oraclejdk8
sudo: required

before_cache:
 -rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
 -rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
 directories:
 -$HOME/.gradle/caches/
 -$HOME/.gradle/wrapper/

env:
 global:
 - ANDROID_API=28
 - ANDROID_BUILD_TOOLS=27.0.3
 - ADB_INSTALL_TIMEOUT=5 # minutes

android:
 components:
 - tools
 - platform-tools
 - tools
 - build-tools-$ANDROID_BUILD_TOOLS
 - android-$ANDROID_API
 - extra-google-m2repository
 - extra-android-m2repository # for design library

 licenses:
 - 'android-sdk-license-.+'
 - 'android-sdk-preview-license-.+'

before_install:
- yes | sdkmanager "platforms;android-28"

lintOptions {
    abortOnError false
}

before_script:
  - chmod +x gradlew

script:
  - ./gradlew assembleRelease

before_deploy:
  - ls app/build/outputs/apk/

deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file: app/build/outputs/apk/app-release-unsigned.apk
  skip_cleanup: true
  on:
    tags: true
```

and my build.gradle is
```
android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.laizexin.sdj.kotlindouban"
        minSdkVersion 23
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        targetCompatibility JavaVersion.VERSION_1_8
        sourceCompatibility JavaVersion.VERSION_1_8
    }
    buildToolsVersion '27.0.3'
}
```
it always told me
```
Checking the license for package Android SDK Build-Tools 27.0.3 in /usr/local/android-sdk/licenses
Warning: License for package Android SDK Build-Tools 27.0.3 not accepted.
Checking the license for package Android SDK Platform 28 in /usr/local/android-sdk/licenses
Warning: License for package Android SDK Platform 28 not accepted.
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':app'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     platforms;android-28 Android SDK Platform 28
     build-tools;27.0.3 Android SDK Build-Tools 27.0.3
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
  
  Using Android SDK: /usr/local/android-sdk
```
i have tried  sdkmanager.bat --licenses 
```
All SDK package licenses accepted.======] 100% Computing updates...
```
I have tried 27.0.1 as well, same failed.
