### ISSUE TITLE
Cannot convert URL 'xxx/xxx.jks' to a file.

### ISSUE THREAD

**Issue by KKaKa** [travis-ci/travis-ci#10299]
I build failed with an exception

`Cannot convert URL 'F:/KotlinDouban/app/keyStore/my.jks' to a file.`

https://travis-ci.org/KKaKa/KotlinDouban/builds/448128471

my .travis.yml is
```
language: android
jdk: oraclejdk8
sudo: true
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - ANDROID_API=28
  - ANDROID_BUILD_TOOLS=27.0.3
  - ADB_INSTALL_TIMEOUT=5
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - android-sdk-license-.+
  - android-sdk-preview-license-.+
before_install:
- openssl aes-256-cbc -K $encrypted_9503677af408_key -iv $encrypted_9503677af408_iv
  -in my.jks.enc -out my.jks -d
- yes | sdkmanager "platforms;android-28"
before_script:
- chmod +x gradlew
script:
- "./gradlew assembleRelease"
before_deploy:
- ls app/build/outputs/apk/release
- mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/kotlinDb-release.apk
deploy:
  provider: releases
  api_key:
    secure: "${GH_TOKEN}"
  file: app/build/outputs/apk/release/kotlinDb-release.apk
  skip_cleanup: true
  on:
    tags: true

```
and my build.gradle is
```
    signingConfigs {
        releaseConfig {
            storeFile file('F:/KotlinDouban/app/keyStore/my.jks')
            storePassword project.hasProperty("KEYSTORE_PASS") ? "KEYSTORE_PASS" : System.getenv("KEYSTORE_PASS")
            keyAlias project.hasProperty("ALIAS_NAME") ? "ALIAS_NAME" : System.getenv("ALIAS_NAME")
            keyPassword project.hasProperty("ALIAS_PASS") ? "ALIAS_PASS" : System.getenv("ALIAS_PASS")
        }
    }
```
i can build success in Window AndroidStudio Terminal but fail in TravisCi .
Is there any difference between window and Linux?
