### ISSUE TITLE
Phantom build is added  to the build matrix if travis.yml doesn't contain a python: section

### ISSUE THREAD

**Issue by ghost** [travis-ci/travis-ci#1029]
Example build: [https://travis-ci.org/y-p/t/builds/6066930](https://travis-ci.org/y-p/t/builds/6066930)

travis.yml:

```
language: python
matrix:
  include:
    - python: 2.7
      env: FOO=true BAR=False
    - python: 2.7
      env: FAZ=true BOO=False
    - python: 2.6
      env: FOZ=true BAO=False
```

as you can see, the matrix contains 3 builds, but the build page shows 4 entries.
