### ISSUE TITLE
[community:r] R version 3.5.0 does not work for Mac 

### ISSUE THREAD

**Issue by jalazawa** [travis-ci/travis-ci#10300]
Travis cannot download a file. But, if I go directly to the site and click on the link then I get the file. 

here the logs 

```C
$ rm /tmp/R.pkg
3.37s$ curl -fLo /tmp/gfortran61.dmg http://coudert.name/software/gfortran-6.1-ElCapitan.dmg
curl: (22) The requested URL returned error: 404 
The command "eval curl -fLo /tmp/gfortran61.dmg http://coudert.name/software/gfortran-6.1-ElCapitan.dmg " failed. Retrying, 2 of 3.
curl: (22) The requested URL returned error: 404 
The command "eval curl -fLo /tmp/gfortran61.dmg http://coudert.name/software/gfortran-6.1-ElCapitan.dmg " failed. Retrying, 3 of 3.

```

The file is [here](https://www.coudert.name/software). 

The Travis log job is [here](https://travis-ci.org/rte-antares-rpackage/antaresProcessing/jobs/448242633). 

My Travis  file (part of) : 

```YAML 
language: R
sudo: true
cache: packages

bioc_required: true
bioc_use_devel: true

os:
 - linux
 - osx

r:
 - oldrel
 - release
 - devel

bioc_packages:
  - rhdf5
  - zlibbioc


after_success:
  - Rscript -e 'library(covr); codecov()'

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=FALSE


```

/cc @jimhester and @jeroen
