### ISSUE TITLE
matrix key ignored in local travis build

### ISSUE THREAD

**Issue by dingo-d** [travis-ci/travis-ci#10326]
Hi!

I've manage to get my travis compile working by following these steps: https://github.com/travis-ci/travis-ci/issues/9709#issuecomment-401241580

After cloning my repo with `.travis.yml` in it, when I run
```bash
travis compile > build.sh
```

I get `matrix key is ignored` message. Also linting will report error in

```bash
in matrix.include section: unexpected key dist, dropping
```

which looks like this:

```yml
matrix:
  fast_finish: true
  include:
    - php: "5.3"
      env: SHORT_OPEN_TAGS=true PHAR_LINT=1
      dist: precise
    # Current minimum $required_php_version for WordPress: 5.2.4
    - php: "5.2"
      env: SHORT_OPEN_TAGS=true PHAR_LINT=1
      dist: precise
```

How can I fix this? If I need to add this manually in the `build.sh` where would I add this? Thanks!
