### ISSUE TITLE
R devel 404 error on OSx

### ISSUE THREAD

**Issue by irenecrsn** [travis-ci/travis-ci#10322]
@jimhester @jeroen

When trying to build an R package for r-devel on OSx, for example [here](https://travis-ci.org/irenecrsn/gmat/jobs/451303585),
```
$ curl -fLo /tmp/R.pkg https://r.research.att.com/el-capitan/R-devel/R-devel-el-capitan-signed.pkg
curl: (22) The requested URL returned error: 404 Not Found
```
Going to the url https://r.research.att.com/el-capitan/R-devel and looking at the directory contents, maybe it should attempt to download `R-devel-el-capitan.pkg` instead of `R-devel-el-capitan-signed.pkg`? (which indeed does not exist at that address). 

My Travis file is:
```yml
language: R
sudo: true 
cache: packages
branches:
    only:
        - master
os:
    - linux
    - osx
r:
    - oldrel
    - release
    - devel
install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install libgit2; fi
before_script:
- Rscript -e 'install.packages(c("igraph", "testthat"))'
```

Also related, [this issue](https://travis-ci.community/t/r-devel-el-capitan-signed-pkg-fails-to-download-when-testing-on-r-devel/672) on the community page.

Thank you.
