### ISSUE TITLE
Expand variables in job names

### ISSUE THREAD

**Issue by mbrodala** [travis-ci/travis-ci#10329]
It would be useful to have variables in [job names](https://docs.travis-ci.com/user/build-stages/#naming-your-jobs-within-build-stages) expanded. This would allow to automatically label jobs with some useful info depending on the job setup:

```yaml
- &test
  name: Unit tests (PHP ${TRAVIS_PHP_VERSION})
  php: 7.2
  script: phpunit
- <<*test
  php: 7.3
```

This should result in two jobs labelled _Unit tests (PHP 7.2)_ and _Unit tests (PHP 7.3)_.
