### ISSUE TITLE
Skipping a deployment with the script provider because this branch is not permitted: advanced-1.0.0

### ISSUE THREAD

**Issue by runzexia** [travis-ci/travis-ci#10338]
I tried to push the tag to the master branch. But the deploy is not being executed correctly
https://travis-ci.org/kubesphere/devops/builds/454893079
```
language: go

go_import_path: kubesphere.io/devops

go:
  - "1.10.3"

sudo: required

services:
- docker

before_script:
- docker --version

install:
  - chmod +x hack/*.sh
  - go get golang.org/x/tools/cmd/goimports

scripts:
  - make check
  - make test

deploy:
  - provider: script
    script: bash hack/docker_push.sh latest
    on:
      branch: master
      repo: kubesphere/devops
  - provider: script
    script: bash hack/docker_push.sh $TRAVIS_TAG
    on:
      tags: true
      repo: kubesphere/devops

```
