### ISSUE TITLE
how to run conditional deploys for multiple os? 

### ISSUE THREAD

**Issue by skygragon** [travis-ci/travis-ci#10348]
Hi experts, currently my app is built on 3 different platforms, now I'm trying to deploy those 3 arifacts to GitHub release. Not sure why but there is only one job created to run the deploy?
```
os:
  - linux
  - osx
  - windows

stages:
  - test
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: test
      script: npm test
    - stage: deploy
      script: npm run travis
      deploy:
        provider: releases
```
