### ISSUE TITLE
Not skip build for deploy

### ISSUE THREAD

**Issue by filips123** [travis-ci/travis-ci#10357]
Add support to not skip build for deploy even if it has `[ci skip]` or something like this. This is because sometimes new tag will not be deployed because it's last commit is marked as skipped.

There could be something like this `allow_skip: false` in config file:

```yaml
deploy:
  allow_skip: false
  skip_cleanup: true
  on:
    tags: true
```
