### ISSUE TITLE
Error deploying multiple files to github releases

### ISSUE THREAD

**Issue by wlbr** [travis-ci/travis-ci#10389]
Hi, 

according to the [docs](https://docs.travis-ci.com/user/deployment/releases#uploading-multiple-files) the deployment of a list of file like this:

```yaml
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: Garbelgnarz=
  file:
    - bin/feiertage_linux_x86_64
    - bin/hohoho_osx_x86_64
    - bin/hohoho_win32
    - bin/hohoho_win64
  on:
    repo: santa/hohoho
    tags: true
```
should be fine. While this worked on travis.org, it does **not work** on **travis.com**. The linter is complaining about the list as well.

Using file globbing one can work around that, but it might not be intended to deploy possibly more than expected.

It should be possible to use a list of files to deploy as well.

Additional info:
the linter complains 
`Warnings for .travis.yml:
[x] in deploy section: dropping file section: unexpected sequence`, which led me to the problem.

On the other hand the actual error message during the build job is completely misleading and wrong:
```
/home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/user: 401 - Bad credentials // See: https://developer.github.com/v3 (Octokit::Unauthorized)
```
