### ISSUE TITLE
Github plugin reports build is queued (forever) if .travis.yml contains parsing error

### ISSUE THREAD

**Issue by cowwoc** [travis-ci/travis-ci#10413]
Here is my `.travis.yml` file:

```
dist: bionic
sudo: false
# Avoid re-downloading dependencies on every build
cache:
  yarn
  directories:
    - "$HOME/.m2/repository"
services:
  - docker
script:
  - cp .travis/settings.xml $HOME/.m2/settings.xml
  - ./mvnw --batch-mode --show-version install
  # Don't cache artifacts that keep on getting replaced
  - rm -rf $HOME/.m2/repository/com/weareadaptive/reactivetrader
branches:
  only:
    - master
```

The parsing error is caused by `cache` containing multiple entries that are not prefixed by a hyphen. When I view my job on `https://travis-ci.com/` (requests tab) I see `Could not parse [job id]` but when I go on my Github pull request, "checks" tab I see a "Queued X minutes ago".

Expected behavior: Github plugin should report that the yml file cannot be parsed, instead of reporting the build is queued forever.
