### ISSUE TITLE
How to run xunit test on travis-ci?

### ISSUE THREAD

**Issue by NMSAzulX** [travis-ci/travis-ci#10442]
### Configuration
```yaml
language: csharp
solution: Natasha.sln
mono: none
dotnet: 2.2
dist: xenial
sudo: required


before_install:
  - sudo apt-get install nuget
  - sudo apt-get update -qq


env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1


install:
- dotnet restore
# - sudo nuget install xunit.runner.console -OutputDirectory testrunner -Source https://api.nuget.org/v3/index.json

script:
- dotnet build -c Release
# - dotnet ./testrunner/xunit.runner.console*/tools/xunit.console.dll ./NatashaUT/bin/Release/netcoreapp2.2/NatashaUT.dll
```

### Error:
WARNING: Error: SendFailure (Error writing headers)
WARNING: An error occurred while loading packages from 'https://api.nuget.org/api/v3/': Error: SendFailure (Error writing headers)
Unable to find package 'xunit.runner.console'.
The command "sudo nuget install xunit.runner.console -OutputDirectory testrunner -Source https://api.nuget.org/api/v3/" failed and exited with 1 during .
