### ISSUE TITLE
Provide a way to install Postgresql 11

### ISSUE THREAD

**Issue by tristanbes** [travis-ci/travis-ci#10444]
Hello,

It's been 10 minutes i've been searching on the web for a proper way to install postgresql 11 without any success.

Please can you help us ?

I tried:
```
addons:
    postgresql: '11'
    apt:
        packages:
            - postgresql-11
            - postgresql-client-11
```

but the error is : 
```
Refused to start PostgreSQL 11, because PostgreSQL 9.2 is currently running! You should first stop 9.2 instance...
```
