### ISSUE TITLE
`travis lint` cannot exit cleanly with deploy.skip_cleanup variable on non-edge deploy

### ISSUE THREAD

**Issue by jensim** [travis-ci/travis-ci#10513]
Type: Bug

Description:
`travis lint` is great. But edge-version has regressions that doesn't work for me (multi asset deploy to github releases from different jobs on same build).
And non edge deploy has started giving warning that skip_deploy *WILL* be deprecated. 
I have removed `travis lint --exit-code` from my `pre-commit hooks`, and have to run it manually.

Reproduce:
```yml
deploy:
  provider: releases
  token: "${GH_TOKEN}"
  file: my-release-file-${TRAVIS_OS_NAME}.tar.gz
  name: Draft-travis-${TRAVIS_BUILD_NUMBER}
  skip_cleanup: true
  draft: true
  file_glob: true
  overwrite: false
  on:
    branch: master
    tags: false
#  Cannot use edge deploy yet
#  edge: true
#  cleanup: false
```
```shell script
travis lint --exit-code
echo $?  # 1
```
