### ISSUE TITLE
MariaDB support

### ISSUE THREAD

**Issue by staabm** [travis-ci/travis-ci#1081]
Since MariaDB is more and more present it would be nice to test apps with it.

MariaDB claims to be compatible with MySQL in most places therefore MySQL based apps tend to improve/verify support for MariaDB.

**Comment by Nicofuma** [comment]
Hello,
I would like to know if there is any update on this issue and if at least it could be possible to whitelist the sources `http://ftp.osuosl.org/pub/mariadb/repo/5.5/ubuntu precise main` and the package `mariadb-server` to be able to install mariadb manually on the new container based stack.

**Comment by jcoffland** [comment]
@BanzaiMan, MaraiDB is a drop in replacement for MySQL.  It's backwards compatible so replacing MySQL with it should not be a problem.

**Comment by simi** [comment]
You can inspire [here](https://github.com/brianmario/mysql2/blob/master/.travis.yml) how to setup MariaDB (5.5 and 10) and MySQL 5.7 on Travis meanwhile.

**Comment by Nicofuma** [comment]
but that's the issue: we need sudo

**Comment by jcoffland** [comment]
BTW, MariaDB is supported through the ATP addon like this:

```
addons:
  apt:
    sources:
      - mariadb-10.0

    packages:
      - mariadb-server
      - mariadb-client
      - libmariadbclient-dev
```
