### ISSUE TITLE
Allow updating multiple .travis.yml files at once by using a single external .travis.yml file

### ISSUE THREAD

**Issue by Raynos** [travis-ci/travis-ci#1131]
## Use-case:

I want to update the .travis.yml config for all my projects to say add node version 0.11 to tests.

All my projects have the exact same .travis.yml file.

It looks like:

``` yml
language: node_js
node_js:
  - 0.8
  - 0.9
  - 0.10
script: node ./test/index.js
```

Manually updating all of .travis.yml files in all my repos to use - 0.11 is a pain in the ass.

Ideally I want to configure all these projects to point to a .travis.yml file on say `raynos.com/travis.yml` and then I can update configuration in a single place.
