### ISSUE TITLE
Conditional e-mail notifications

### ISSUE THREAD

**Issue by mloskot** [travis-ci/travis-ci#1206]
This is a feature request I've come up with after asking on the forum about [preventing build notifications from forks](https://groups.google.com/d/msg/travis-ci/naDUvd_w9Mw/5TJCuaIhA94J). This is also directly related to old issue #280, but it is slightly different.

Would it be possible to have syntax for condition based on external (shell) command?

```
notifications:
   email:
      - one@example.com
      condition: /usr/bin/test "x$TRAVIS_REPO_SLUG" = "xmyorg/myrepo"
```

Similarly to return code of the `script:` command, the syntax above could simple mean that if command specified in the `condition` returns success, Zero, then e-mail is sent; if condition command returns non-zero, no e-mail is sent.

This way, for example, one could filter out notifications from forks, and more.
