### ISSUE TITLE
Add build add-on for package installers

### ISSUE THREAD

**Issue by sarahhodne** [travis-ci/travis-ci#1222]
I discussed this with @joshk a while ago, but I thought it would be nice to add an addon for installing packages.

``` YAML
addon:
  packages:
    - some-package
    - another-package
```

is equivalent to

``` YAML
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install some-package another-package
```

We could also make it use Homebrew for Mac builds.

The reason I want this is because it's easy to forget the `apt-get update` step.
