### ISSUE TITLE
Build jobs running that aren't specified in the matrix

### ISSUE THREAD

**Issue by cjbottaro** [travis-ci/travis-ci#1228]
Given a travis-ci config file:

``` yaml
matrix:
  include:
    - rvm: 1.9.2
      gemfile: .gemfiles/Gemfile.activerecord-3.2
    - rvm: 1.9.3
      gemfile: Gemfile
```

I would expect only two build jobs to run, but instead three are:  http://d.pr/i/omuW

https://travis-ci.org/cjbottaro/schizo

Thank you.

**Comment by bilderbuchi** [comment]
I get this issue currently. `exclude`ing the empty build does not help. I got a env.global.secure section, but even moving this into the only build that actually needs it does not remove the "extra" build. See https://travis-ci.org/openframeworks/openFrameworks/builds/75852482 and https://github.com/openframeworks/openFrameworks/blob/2acf77d89495c38dc67578fe13316aac79909384/.travis.yml

**Comment by bilderbuchi** [comment]
Yes, definitely [hit](https://travis-ci.org/openframeworks/openFrameworks/builds/76285208) by this issue, as a really ugly workaround I have added an additional build, which just does nothing except pulling down our repo, until this is fixed again.

**Comment by bilderbuchi** [comment]
OK, simple repo .travis.yml, makes two builds, one without environment variables defined. One build with TARGET=linux was intended:
```

language: c++
compiler: gcc
matrix:
  include:
    - os: linux
      env: TARGET="linux"

install: true

script: true
```
https://travis-ci.org/bilderbuchi/travis_production_test/builds/76336816
