### ISSUE TITLE
matrix.exclude needs global env vars to work

### ISSUE THREAD

**Issue by sarahhodne** [travis-ci/travis-ci#1237]
``` YAML
language: ruby

env:
  global:
    - FOO=bar

rvm:
  - 1.9.2
  - 2.0.0

gemfile:
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-4.0.x

matrix:
  exclude:
    - rvm: 1.9.2
      gemfile: gemfiles/Gemfile.rails-4.0.x
```

One would expect the config above to generate three builds, but in fact it generates four and "ignores" the exclude. A workaround is to copy the "env" block (with "global" and all) into the exclude block, but that shouldn't be necessary.
