### ISSUE TITLE
If only matrix.include jobs are specified, the default job is included as well

### ISSUE THREAD

**Issue by sarahhodne** [travis-ci/travis-ci#1260]
Given the .travis.yml file below, you actually get three builds instead of the two that I would expect.

``` YAML
language: ruby
matrix:
  include:
    - rvm: 1.9.3
      gemfile: Gemfile.1
    - rvm: 2.0.0
      gemfile: Gemfile.2
```

Related to #803.
