### ISSUE TITLE
Could not export environments with bash scripts

### ISSUE THREAD

**Issue by hoatle** [travis-ci/travis-ci#1313]
Hi,

I tried with bash script to export variables, however, it did not work as expected.

This is my test `.travis.yml`:

```
branches:
  only:
  - feature_47_docs_auto_deployment
language: python
install: pip install -r docs/requirements.txt
before_script:
- export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
- sh -c "if [ '$TRAVIS_BRANCH' = 'feature_47_docs_auto_deployment' ]; then echo 'matched'; export DEPLOY_HTML_DIR=test; fi"
- echo $REPO_URL
- echo $DEPLOY_HTML_DIR
- cd docs
- make setup_gh_pages
script: make generate
after_script: make deploy
env:
  global:
  - GH_REPO="hoatle/teracy-dev"
  - secure: PXdIZQP5nCjfA/z22FnNl6zfrqPD8ccO5TRHsYiq53Yqx7dqUGmdcqLohw60IHYm6C2z4Wnkp9fqhDtkQ/eGM0UHcr33mBop0/pOypiPz/utjePFHonTTYNjl9X7+TYHpp1V+TaKtJK4J25lK7GuJUPmNLJD6jvUKcENesh984E=
```

Expect: `echo $DEPLOY_HTML_DIR` should print `test`
Actual: `echo $DEPLOY_HTML_DIR` print nothing.

This is the detail build: https://travis-ci.org/hoatle/teracy-dev/builds/10051337

Please help me to see if there is anything wrong here. Thank you very much!
