### ISSUE TITLE
App not deployed after successful build

### ISSUE THREAD

**Issue by anero** [travis-ci/travis-ci#1325]
We set up Travis to deploy after a successful build but after running the tests it doesn't perform the deployment. We were able to deploy locally using the `dpl` gem so I'm guessing it's a config issue. Our [.travis.yml](https://github.com/fiuba/alfred/blob/develop/.travis.yml) is the following:

```
language: ruby
version: 1.9.3
before_script:
- sh -e /etc/init.d/xvfb start
script: PADRINO_ENV=travis padrino rake
bundler_args: --without development
deploy:
  provider: heroku
  api_key:
    secure: UwPIT+7muEe3R0U64q/3WkaVhynGWiR61k9i51TPosR8joFc1EWgzTKCtNrl+vMOuW5YMUewJaKjj8zq5nfJRH5QaIBQkpHh8s/CcwDgT3Re8/v6kBu2dB4VKGfKhkUsHipPt/LSdIHERuAuCl+3b3dZu2Teju/35SfvNm1xj+Q=
  app: alfred-preview
  on:
    branch: develop
```

At first I thought the `script` setting could be messing it up, but as you can see [here](https://travis-ci.org/fiuba/alfred/builds/10162889), it's exiting with code 0.
Are we missing something here?
