### ISSUE TITLE
bower install not working

### ISSUE THREAD

**Issue by localnerve** [travis-ci/travis-ci#1424]
My "bower install" before-install step fails mysteriously (looks like a package is not working). However, I cannot replicate this on any clean Ubuntu VM of my own. It looks like it is running a local bower pkg from a local npm pkg dep and not the global one, which I didn't expect. Do I need to change dir at that step or do something special to have local and global bower? Any help is appreciated...

.travis.yml:

``` YAML
language: node_js
node_js:
  - 0.10

before_install:
  - sudo apt-get update
  - sudo apt-get install rubygems
  - gem install compass

before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install --verbose
```

Build Error:

```
$ bower install --verbose
module.js:340
    throw err;
          ^
Error: Cannot find module './dist/lodash.compat.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/travis/build/localnerve/wpspa/node_modules/bower/node_modules/update-notifier/node_modules/configstore/node_modules/lodash/index.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
The command "bower install --verbose" failed and exited with 8 during before_script.
```
