### ISSUE TITLE
Feature Request: Publish to npm

### ISSUE THREAD

**Issue by Joshua-Anderson** [travis-ci/travis-ci#1429]
Travis CI is very popular among the nodejs community, and is used for almost every popular node project. Mostly though, the people using it the most are the module creators, who often have hundreds of tests set up. I would really like to have the ability to publish to npm, much like how you can publish to RubyGems. The fact that npm uses that package.json means that the publishing interface is very simple because all you have to do is call _npm publish_.

You could do it like this:

``` yml
deploy:
  provider: npm
  username: ...
  password: ...
```
