### ISSUE TITLE
Support different config syntax for environment variables

### ISSUE THREAD

**Issue by sarahhodne** [travis-ci/travis-ci#1446]
I'd like to propose the following syntax to be allowed for environment variables:

``` YAML
env:
  global:
    - FOO: bar
    - BAR: baz
  matrix:
    - FOOBAR: bar bar bar
      BAZ: "baz baz baz"
    - FOOBAR: foo bar baz
      BAZ: foobar
```

This should be functionally equivalent to this config:

``` YAML
env:
  global:
    - FOO=bar
    - BAR=baz
  matrix:
    - FOOBAR="bar bar bar" BAZ="baz baz baz"
    - FOOBAR="foo bar baz" BAZ=foobar
```

(See #1444—apparently this is currently sort of working, but has a bug)

**Comment by cben** [comment]
As discussed on #1444, #1566 and probably more, a big annoyance with current `env: ['FOO="abc def"']` array structure is the need for shell quoting.  It's essentially a shorthand for `'export FOO="abc def"'` commands.  This does have the upside that you can interpolate dynamic data eg. `PR="https://github.com/${TRAVIS_REPO_SLUG}/pull/${TRAVIS_PULL_REQUEST}`. 
But a lot of time, you want fixed values, and shell quoting on top of YAML is error-prone (especially when values already contain complex data with quotes, e.g. JSON as in #1566).

Is there any chance to define `env: {"FOO": "abc def"}` mapping to mean higher-level "do whatever needed to set this var to this value"?

A mapping structure would have 2 more benefits for generated configs triggered via API:
- programatic shell quoting of dynamic values is hard
- arrays of strings can't be merged, mappings can (cf. https://github.com/travis-ci/docs-travis-ci-com/issues/1485).

**Comment by ZyX-I** [comment]
Regarding the last benefit: don’t know about Ruby’s YAML parsing library, but Python one allows making

```YAML
env:
  global:
    FOO: !!expand "$HOME/foo"
    BAR: "$HOME/bar"
```

an equivalent of

```YAML
env:
  global:
    - FOO="$HOME/foo"
    - BAR="\$HOME/bar"
```

. Proposed variant has the following benefits:

- It allows to have both mappings-based merging and string expansion.
- That still is stricter: I would expect

  ```YAML
  env:
    global:
      LUA_INIT: !!expand >-
        require('foo').init()
        require('bar').init()
        ci = "$TRAVIS_JOB_NUMBER"
  ```

  to define multiline $LUA_INIT without needing to bother with proper escaping.
- This introduces a natural way to make currently static configuration variables depend on the results of execution shell code should it be needed. I have no candidates currently though.
