### ISSUE TITLE
Allow not specifying all matrix keys in matrix exclusions

### ISSUE THREAD

**Issue by sarahhodne** [travis-ci/travis-ci#1492]
I'd like to make a .travis.yml like such:

``` YAML
language: ruby
bundler_args: --without development
script: 'bundle exec rake test'
services:
  - mongodb
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
env:
  - DB=mongodb
  - DB=redis
  - DB=mysql
gemfile:
  - Gemfile
  - gemfiles/rails3.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: Gemfile
```

Right now, this would not exclude any matrix entries.

The proposed feature is that if a matrix key (such as `env`) is not used in any given matrix exclusion entry, then it matches all values.

I think this is as simple as changing [this line](https://github.com/travis-ci/travis-core/blob/edc16c815bfdca37355b66bd4f804ce943305680/lib/travis/model/build/matrix/config.rb#L67) to the following

``` ruby
exclude_configs.to_a.any? { |excluded| config.include?(excluded) }
```
