### ISSUE TITLE
No concise way to specify multi-dimensional build matrix.

### ISSUE THREAD

**Issue by dreid** [travis-ci/travis-ci#1519]
https://github.com/dreid/treq/blob/master/.travis.yml specifies a 3-dimensional build matrix whose axes are python version, twisted version, and the existence of PyOpenSSL.  As you can see the expression of this matrix is incredibly verbose and requires a lot of duplication.  It also requires manual enumeration of the environment variables used.  It would be nice if I could just describe the axes and the values along the axes.

For example:

```yaml
python:
 - 2.6
 - 2.7
 - pypy

env:
  matrix:
    - TWISTED:
      - git+git://github.com/twisted/twisted/
      - 13.1.0
      - 13.0.0
      - 12.1.0
   - PYOPENSSL:
      - true
      - false
```

I would expect this to result in a matrix calculated as the cartesian product of python version, TWISTED var values, and PYOPENSSL var values.
