### ISSUE TITLE
Environment variables with special characters in the .travis.yml file

### ISSUE THREAD

**Issue by julweber** [travis-ci/travis-ci#1566]
Hey,

i'm writing an application that uses env variables for reading configuration values in a json format.

The main problem exists with the " character. I tried various combinations including \", but had no success. How could i manage to insert my configuration into the environment for running test.

The result is that the export commands are invalid:

```
$ export CF_BILLING_BASIC_CONFIG={
$ export EXECUTE_MIGRATIONS=true
$ export INSERT_SEED_DATA=false
$ export CF_BILLING_ERP_CONFIG={
$ export CF_BILLING_SAMENESS_CONFIG={
$ export CFOUNDRY_HELPER_CONFIG={
$ export VCAP_SERVICES={
```

This is the env part of my current .travis.yml file:

``` YAML
env:
  - CF_BILLING_BASIC_CONFIG={"billing_start_date":"2013-10-01","accounting_run_frequency":"month","default_price_group":"default"} EXECUTE_MIGRATIONS=true INSERT_SEED_DATA=false CF_BILLING_ERP_CONFIG={"api_endpoint":"http://erp.vserver9.omikron.railshoster.de/api/effort_accounting","user":"test_user","password":"test_password","anynines_brand_id":"5"} CF_BILLING_SAMENESS_CONFIG={"api_endpoint":"http://sameness.de.a9sapp.eu","user":"sameness_user","password":"sameness_password","caching_time":1200} CFOUNDRY_HELPER_CONFIG={"http://ccng.de.a9s-stage.de":{"uaa":{"site":"http://uaa.de.a9s-stage.de","client_id":"my_client_id","client_secret":"my_client_pass"},"cloud_controller":{"site":"http://ccng.de.a9s-stage.de","username":"my_cc_user","password":"my_cc_pass"}}} VCAP_SERVICES={"mysql-5.5":[{"name":"mysql-instance-name","label":"mysql-5.5","tags":["relational"],"plan":"mysql_plan_name","credentials":{"name":"cf_billing_test","hostname":"localhost","host":"localhost","port":3307,"user":"travis","username":"travis","password":null,"uri":"mysql://travis@localhost:3307/cf_billing_test"}}],"mongodb-2.0":[{"name":"mongodb-instance-name","label":"mongodb-2.0","tags":[],"plan":"mongodb_plan_name","credentials":{"hostname":"localhost","host":"localhost","port":27017,"username":null,"password":null,"name":"my_name","db":"cf_billing_test","url":"mongodb://localhost:27017/cf_billing_test"}}]}
services:
  - mongodb
  - mysql
```

Could you help me with this problem please? 

Regards,
Julian
