### ISSUE TITLE
exclude seems to differ between com and org

### ISSUE THREAD

**Issue by rkh** [travis-ci/travis-ci#1581]
From a customer:

``` yaml
env:
  global:
    - SK_ENABLE_TRACE_LOGS=true
    - RAILS_ENV=development

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby

gemfile:
  - gemfiles/Gemfile.rails-3.0.x
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-4.0.x
# - gemfiles/Gemfile.rails-edge

matrix:
  exclude:
    # As far as I can tell, Magnum wants the env, public doesn't
    - rvm: 1.9.2
      gemfile: gemfiles/Gemfile.rails-4.0.x
      env:
        - SK_ENABLE_TRACE_LOGS=true
        - RAILS_ENV=development
    - rvm: 1.9.2
      gemfile: gemfiles/Gemfile.rails-4.0.x
```

public repo: skylightio/skylight-ruby
