### ISSUE TITLE
Unable to use encryption for my channel key

### ISSUE THREAD

**Issue by akerl** [travis-ci/travis-ci#1628]
I'm trying to do IRC notifications with an encrypted channel key. I've tried various formats in .travis.yml, including having channel_key be a list or a hash, but it's not successfully using the key. Here's my repo and config:

https://github.com/akerl/basiccache

```
language: ruby
rvm:
- ruby-head
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-19mode
notifications:
  email: false
  irc:
    channels:
      - irc.oftc.net#akerl
    channel_key:
      secure: "AFEdB/WjJAI7N1LJcdBS/qtyR7hwrY0HEUp1Tq2Wyr9ieFl8VpN+GjRdncjGq+rtZe5jpE1Ind5GErHStg6UTLkocOo1ITcxLwpUhMatox6RdGLsFwTVWymV00KwRTD4S+X5cU9dfGlmGOTNuvDEjh6IarAmnQ/qb9ZX0slJHQg="
    template:
      - '%{repository}/%{branch}/%{build_number}: %{message} -- %{build_url}'
```

If I encrypt the channel name but not the key, it works fine, so it doesn't appear to be a decryption issue
