### ISSUE TITLE
GitHub Releases Deployment

### ISSUE THREAD

**Issue by guybedford** [travis-ci/travis-ci#1648]
Hope I'm posting this in a suitable place, I couldn't find this mentioned anywhere else.

Are there any considerations to allow a deployment to Github releases?

**Comment by hawkw** [comment]
I'm still having issues finding files in a subdirectory. My filenames are the same each time. I get the following [output](https://travis-ci.org/MeteorCode/Pathway/builds/66089143#L1411) from Travis, and my `.travis.yml` looks like this:
```yaml
deploy:
  provider: releases
  api_key:
    secure: 
  file:
    - "build/libs/pathway.jar"
    - "build/libs/pathway-scaladoc.jar"
    - "build/libs/pathway-javadoc.jar"
    - "build/libs/pathway-sources.jar"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
```
Is anybody else still having this problem?
