### ISSUE TITLE
Build Matrix support for PostgreSQL versions

### ISSUE THREAD

**Issue by danmcclain** [travis-ci/travis-ci#1651]
The new addon support for PostgreSQL is awesome, and what would make it even better is if I could specify multiple versions of PostgreSQL that my suite should run against

**Comment by m6w6** [comment]
How about revisiting this now, since there's there no-sudo limitation on containers?

**Comment by joshk** [comment]
I'm sorry, but we will not be adding this to the automatic matrix expansion. You can instead use the following config to define the versions you want to use:

```yaml
matrix:
  include:
    - addons:
        postgresql: 9.3
    - addons:
        postgresql: 9.4
```
