### ISSUE TITLE
Support a deployment provider which just executes a custom script

### ISSUE THREAD

**Issue by joshk** [travis-ci/travis-ci#1714]
This would allow users to use the deployment DSL but just have Travis run a custom script.

cc. @jcassee

**Comment by BanzaiMan** [comment]
@jcassee Sorry for the long silence. You can make use of various environment variables to selectively execute the command. Conditional deployments are just a syntactical sugar around that.

If you have specific cases, we can also advise. Thanks.

**Comment by jcassee** [comment]
Had already forgotten about this one. :-) Well, the request was for syntactic sugar anyway, as most sections from `.travis.yml` could be replaced by a well-written build script. This would just read well:

```
deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: release
    condition: $MY_ENV = super_awesome
```

But if supporting something like it is just not in the cards, feel free to close the issue.

**Comment by joshk** [comment]
@BanzaiMan this issue is already on the backlog, issue 341 in Team Teal

**Comment by BanzaiMan** [comment]
Hi, @jcassee,

I've pushed a straightforward, no-frills implementation of the `Script` provider to the `master` branch. Could you try testing it with `edge: true`? Your deploy section would look like this:

```yaml
deploy:
  provider: script
  edge: true
  script: scripts/deploy.sh
  on:
    branch: release
    condition: $MY_ENV = super_awesome
```

Thanks!
