### ISSUE TITLE
Best way to deal with many (or large) secure env vars?

### ISSUE THREAD

**Issue by simon-weber** [travis-ci/travis-ci#1736]
I run my builds against a few test users. I store their credentials in secure env vars, which, when decrypted, looks something like:

```
env:
  matrix:
    - user=foo pass=foo2 token=foo3 id=...
    - user=bar pass=bar2 token=bar3 id=...
```

The trouble is that due to the key size, I can only store 117 characters in each of these lines, and I'm out of room. I've already trimmed down the variable names as far as I can; I need a general solution for splitting these lines up.

The only thing I can think of is doing something like:

```
env:
  global:
    - user1=foo
    - pass1=foo2
    ...
    - user2=bar
    - pass2=bar2
    ...
  matrix:
    - userid=1
    - userid=2
```

since that would let me declare each piece of the user auth with a separate `secure:` line.

There's got to be a better way, though.
