### ISSUE TITLE
compiler has no effect under language: perl

### ISSUE THREAD

**Issue by JRaspass** [travis-ci/travis-ci#1756]
Using Travis to test a Perl module written with C/XS I thought it might be useful to test clang too. Setting the following matrix causes the overview UI to show the correct Perl and compiler values but inside the build no CC env is set nor is cc symlinked anywhere but gcc:

```
matrix:
    include:
        - compiler: clang
          perl: "5.19"
        - compiler: gcc
          perl: "5.19"
        - compiler: gcc
          perl: "5.18"
        - compiler: gcc
          perl: "5.16"
        - compiler: gcc
          perl: "5.14"
        - compiler: gcc
          perl: "5.12"
```

A build showing the problem is located here - https://travis-ci.org/JRaspass/JavaBin/builds/15469665

I've ran a few commands in the script section (echo $cc, which cc, etc) to highlight the problem. I also have a terrible hack where I attempt to set cc to clang for build 1. Incidentally I'd like to remove that default build 1, is there a way I can just list the matrix at the exhaustive list of jobs, no default job.

Thanks in advance, your tool really is superb!
