### ISSUE TITLE
Inconsistency on commit author name variable used on IRC templates

### ISSUE THREAD

**Issue by hvelarde** [travis-ci/travis-ci#1816]
on [Configuring Build Notifications: IRC notification](http://about.travis-ci.org/docs/user/notifications/#IRC-notification) you state that the **%{author}** variable is the commit author name.

you say also that the following template is the default one:

``` yml
notifications:
  irc:
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
```

there is an inconsistency on this: if I declare no template Travis CI notifications on IRC channel are made using the commit author **usename** which is, in fact, the right thing to do:

```
<travis-ci> [travis-ci] collective/collective.aviary#31 (master - 32d7ded : hvelarde): The build passed.
```

https://github.com/collective/collective.aviary/blob/master/.travis.yml#L26

if I declare a template, the notification is made using the author **full name**, which is wrong because on an IRC channel I don't get an alert:

```
<travis-ci> [travis-ci] collective/collective.cover#1320 (master - 8924a55 : Héctor Velarde): The build passed.
```

https://github.com/collective/collective.cover/blob/master/.travis.yml#L30
