### ISSUE TITLE
Allow file pattern build skip

### ISSUE THREAD

**Issue by lucasmichot** [travis-ci/travis-ci#1819]
Hi Travis-CI team,

I've carefully searched for issues or feature related to build skip but could not find any duplicate.

Right now it's possible to skip a build using a specific keyword in the commit message (http://about.travis-ci.org/docs/user/how-to-skip-a-build). This is great.
But this implies the commiter is aware of this.
In some case, a committer could also skip a build with a commit message, but the repo owner is not necessary OK with it.

I thing the ability to "force build skip based on pattern" or to "disallow build skip commits" could be set in `.travis.yml` file ?
See `skip`

``` yaml
language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

skip:
  - commit: false
  - pattern:
    - "docs/*"
    - README.md
    - "*.rst"

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit -d memory_limit=1024M

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
```

What do you think of this feature ?
BTW happy new year in Berlin ;)
