### ISSUE TITLE
Disable build skip commits message in .travis.yml

### ISSUE THREAD

**Issue by lucasmichot** [travis-ci/travis-ci#1820]
Hello,

It would be great to allow repo owner to disable `[ci skip]` build message. This setting could be enabled or disabled into the `.travis.yml` file.

See `skip` entry in this example:

``` yaml
language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

skip:
  - commit: false

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit -d memory_limit=1024M

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
```
