### ISSUE TITLE
travis ci can't deploy the newest codes?

### ISSUE THREAD

**Issue by zjh459** [travis-ci/travis-ci#1835]
I have a simple java web (built by spring mvc) project on travis ci .

And I want to deploy it on appfog.

but i found that i can't get the newest codes deployed.

in fact , it deployed my oldest codes , version 1.

here is my .travis.yml

``` YAML
language: java
jdk:
- oraclejdk7
- openjdk6
script:
- mvn clean package
deploy:
  provider: appfog
  email: zjh459@gmail.com
  password:
    secure: RSn6ve64vjvkDREzQpc8qURze+pOqo80krNsu2Jlcj3F/IMbjBZwH6jKlFl47EDYE4byWTiOnwX2otywMedAbgtVOHfojXGnVyDqvQX3YL/BSK9UpS6BA0qAtV6YcLAItIT34wlKRcc5sPto9xdmec14hLUSUW3+DNjL8g4WRSU=
  app: oftest3
  on:
    repo: zjh459/git-projects
```
