### ISSUE TITLE
on_success/on_failure config fails when given as arrays

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-ci#1866]
If campfire (and I'd suspect any) notification config is given like:

```
notifications:
  campfire:
    rooms: [...]
    on_success:
      - always
    on_failure:
      - always
```

then no notification will be sent at all.

Even though the docs state these values need to be given as plain strings, not arrays, this might still be confusing to the user, and I would guess this could be easily normalized?
