### ISSUE TITLE
on tags:true does not appear to be working for node project.

### ISSUE THREAD

**Issue by elliotstokes** [travis-ci/travis-ci#1876]
Im trying to auto deploy my project to npm with the following:

``` yaml
deploy:
  api_key: <encrypted>
  email: email@andaddress.com
  provider: npm
  on:
    tags: true
    node: 0.10
```

On the build the script is returning nothing for 'git fetch --tags'

You should be able to see this here

https://travis-ci.org/elliotstokes/gpx-parse/jobs/17364696

Am I doing something wrong?
