### ISSUE TITLE
Filter notification triggers based on branches

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#1896]
For example:

``` YAML
notifications:
  hipchat:
    branches:
      only: master
      except: lp-5543-something, lp-2343-otherthing
    rooms:
      secure: REOQ1iqGVaaL7...
```

where only/except are mutually exclusive, that I might specify branch-specific notification targets.

https://secure.helpscout.net/conversation/20301870/4558/
