### ISSUE TITLE
multiple "secure:" entries not supported in matrix section

### ISSUE THREAD

**Issue by ghost** [travis-ci/travis-ci#1923]
related https://github.com/travis-ci/travis-ci/issues/1024

from: http://docs.travis-ci.com/user/encryption-keys/#Usage

```
You may add multiple entries to your .travis.yml with key "secure." 
They will all be available to your program.
```

however, the following travis.yml snippet:

```
matrix:
    include:
    - python: 2.7
      env:
      - secure: "Bx5umgo6WjuGY+5XFa004xjCiX/vq0CyMZ/ETzcs7EIBI1BE/0fIDXOoWhoxbY9HPfdPGlDnDgB9nGqr5wArO2s+BavyKBWg6osZ3dmkfuJPMOWeyCa92EeP+sfKw8e5HSU5MizW9e319wHWOF/xkzdHR7T67Qd5erhv91x4DnQ="
      - secure: "BCH/+S8wIVabGiufTmvxFNgXx4/7hKQ4Jmhk17zGs+lzXdk3kBCBZ+NAohqyWKYsYamVMPnSve46Lp6psSnm54jUXgNbkIRNEUXTvWHlxIB10vK/A8T+McnC5oRnBMt8d25goxviQFVmm1dP+y22GDlI0iMA4Lif4/a1OuYbvn0="
```

Seems to only include the envars from the last `secure:` entry in the build's environment.
