### ISSUE TITLE
Not receiving email notifications for builds

### ISSUE THREAD

**Issue by paulspencerwilliams** [travis-ci/travis-ci#1957]
I'm not, and have not for a while received email notifications for builds. I've explicitly added

```
notifications:
  email:
    on_success: always # default: change
    on_failure: always # default: always
```

on https://travis-ci.org/paulspencerwilliams/joy-of-clojure but following several successive builds, still haven't received any notifications. 

This repo only has a single owner / committer, so it's the simplest configuration. 

I've also received no email notifications for other repos so believe it to be a wider account setting, but I can't locate an appropriate one.
