### ISSUE TITLE
Reducing build matrix when using coverity_scan addon

### ISSUE THREAD

**Issue by waja** [travis-ci/travis-ci#1975]
We are using gcc and clang as compiler and so we have (actual) 2 jobs for each build. We also want to use the coverity_scan addon, so normally we would have 2 coverity jobs for each build, which is a waste of resources.

We tried to avoid that with adjusting (https://github.com/waja/monitoring-plugins/blob/ef46dabffaa3a7ca60faf4e9eac79b4245265549/.travis.yml) the build matrix:

matrix:
  exclude:
    - compiler: clang
      env: COVERITY_SCAN_BRANCH=1

As $COVERITY_SCAN_BRANCH seems not available when the matrix is evaluated, both jobs are running when the coverity_scan addon is triggered.

It would be very nice (at least for the coverity people) to be able to reduce the build matrix when the coverity_scan addon is triggered.

**Comment by roidrage** [comment]
Closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.

**Comment by cperciva** [comment]
In case it helps anyone who finds this issue later on, in my .travis.yml I have:

env:
  global:
    - secure: "<XXX>"
    - COVERITY_SCAN_PROJECT_NAME="XXX"
    - COVERITY_SCAN_BRANCH_PATTERN="XXX"
    - COVERITY_SCAN_NOTIFICATION_EMAIL="XXX"
    - COVERITY_SCAN_BUILD_COMMAND="XXX"

before_install:
- 'if [[ "${TRAVIS_JOB_NUMBER##*.}" == "1" ]]; then curl -s "https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh" | bash || true ; fi'

with appropriate XXXs.  The before_install command only executes the Coverity code on build *.1, i.e., the first out of a matrix of jobs.

**Comment by Dridi** [comment]
FWIW I managed to combine both the add-on and a matrix by using @cperciva's tip (thanks!) backwards:

```yaml
addons:
  coverity_scan:
    project:
      name: [...]
      description: [...]
    notification_email: [...]
    build_command_prepend: [...]
    build_command: [...]
    branch_pattern: coverity_scan
before_install:
  - test $TRAVIS_BRANCH != coverity_scan -o ${TRAVIS_JOB_NUMBER##*.} = 1 || exit 0
script:
  - test $TRAVIS_BRANCH != coverity_scan || exit 0
  - [...]
```

It's a bit more twisted but I don't have to maintain the `curl bash` logic or global environment variables (other than the secure one). I have successfully pushed `origin master:coverity_scan` several times.

**Comment by pali** [comment]
I'm using this configuration in which coverity scan is running in separate build (with env COVERITY=1) as part of build matrix:

```
language: c
compiler:
  - gcc
  - clang
matrix:
  include:
    - compiler: gcc
      env: COVERITY=1
before_install:
  - if [ "$COVERITY" = "1" -a "$TRAVIS_BRANCH" != "<branch>" ]; then exit 0; fi
  - <prepare>
  - if [ "$COVERITY" != "1" ]; then <configure> && <build>; exit $?; fi
script: true

env:
  global:
    - secure: <secure>

addons:
  coverity_scan:
    project:
      name: "<name>"
      description: "Build submitted via Travis CI"
    notification_email: <email>
    build_command_prepend: "<configure>"
    build_command: "<build>"
    branch_pattern: <branch>
```

As coverity addon is called after before_install it is working fine. Just the whole procedure needs to be in before_install section.

**Comment by tanzislam** [comment]
I should mention that I have only the following in [my `.travis.yml`](https://github.com/tanzislam/cryptopals/blob/master/.travis.yml):

```
sudo: false
language: cpp

os:
- linux
- osx

dist: trusty
osx_image: xcode8.2

addons:
    coverity_scan:
        # COVERITY_SCAN_TOKEN and COVERITY_SCAN_NOTIFICATION_EMAIL should be set
        # in Travis settings. They depend on repo owner so aren't included here.
        project:
            name: $TRAVIS_REPO_SLUG
            version: $TRAVIS_COMMIT
        # Coverity refuses to run on OSX due to System Integrity Protection
        # being enabled, so we need no hackery here to limit it to Linux only.
        build_command: make -k
        branch_pattern: master

script:
- make -kj 2
- ./test
```

It turns out that Coverity Scan doesn't run on the latest OSX image due to a conflict with System Integrity Protection, so the plugin only does its work on the container-based Linux job. So I needed none of the hackery with `$TRAVIS_BRANCH` and/or `$TRAVIS_JOB_NUMBER`.
