### ISSUE TITLE
Problem with deploy as an array form

### ISSUE THREAD

**Issue by drogus** [travis-ci/travis-ci#2020]
One of the customers had a problem with dpl when putting deploy config as an array, like:

```yaml
deploy:
  - provider: opsworks
    access_key_id: key
    secret_access_key: secret
    app-id: id
    on:
       branch: production
```

Changing it to hash fixed things:

```yaml
deploy:
  provider: opsworks
  access_key_id: key
  secret_access_key: secret
  app-id: id
  on:
     branch: production
```
