### ISSUE TITLE
Unexpected travis matrix when include and allow_failures are used

### ISSUE THREAD

**Issue by Sannis** [travis-ci/travis-ci#2073]
For this configuration:

``` yaml
compiler:
  - gcc
  - clang
matrix:
  include:
    - compiler: clang
      env: SANITIZE=address
    - compiler: clang
      env: SANITIZE=undefined
  allow_failures:
    - compiler: clang
      env: SANITIZE=address
    - compiler: clang
      env: SANITIZE=undefined
```

I've got:
Build Matrix:

| Compiler | ENV |
| --- | --- |
| gcc |  |

Allowed Failures:

| Compiler | ENV |
| --- | --- |
| clang |  |
| clang | SANITIZE=address |
| clang | SANITIZE=undefined |

But I expect that clang + empty ENV will be in build matrix.

Example build: https://travis-ci.org/Sannis/protobuf2json-c/builds/20895166

**Comment by BanzaiMan** [comment]
OK. I understand this now. This is a variation of a much more recent issue https://github.com/travis-ci/travis-ci/issues/7124.

With this configuration:

```yaml
compiler:
  - gcc
  - clang
matrix:
  include:
    - compiler: clang
      env: SANITIZE=address
    - compiler: clang
      env: SANITIZE=undefined
  allow_failures:
    - compiler: clang
      env: SANITIZE=address
    - compiler: clang
      env: SANITIZE=undefined
```

The top level config does not have any `env` key defined, so the `env` value in `allow_failures` are not considered when we find jobs for `allow_failure`.
