### ISSUE TITLE
Don't disable all addons for pull requests

### ISSUE THREAD

**Issue by henrikhodne** [travis-ci/travis-ci#2135]
We currently remove the entire `addons` block for pull request from other repositories. I think some of them should be allowed to stay. Maybe keep everything that doesn't have encrypted variables?

**Comment by jrjohnson** [comment]
@roidrage - Did this get any traction?  Can we enable the sauce connect addon for pull requests with unencrypted access keys?  
Otherwise we have to pull in the binary every time from some external source which wastes time and I'm guessing some incremental networking cost on your end.

**Comment by joshk** [comment]
I believe this has been fixed.

**Comment by kingcody** [comment]
@joshk do we need to set anything other than:
```yaml
addons:
  sauce_connect:
    username: "USERNAME"
    access_key: "XXXXX-XXXX-XXXX-XXXX-XXXXX"
```

That alone doesn't seem to allow the sauce_connect addon to load for pull requests.
