### ISSUE TITLE
Expand environment variables in cache directories

### ISSUE THREAD

**Issue by bendavies** [travis-ci/travis-ci#2153]
It would be good to expand env variables in cache directory configuration.

for example

``` yaml
cache:
    directories:
      - $CACHE_DIRETORY
```

It took me a while (asking in support channel) to find out why caching wasn't working when doing this
