### ISSUE TITLE
Android: Installation of tools component erases Travis helper scripts

### ISSUE THREAD

**Issue by gabrielemariotti** [travis-ci/travis-ci#2279]
I am trying the new (beta) feature with Android as described here:
http://docs.travis-ci.com/user/languages/android/

simple .travis.yml

```
language: android
android:
  components:
    - tools
    - build-tools-19.0.3
    - android-19
    - extra-android-support
    - extra-android-m2repository

jdk: oraclejdk7
```

Error:

```
Switching to Oracle JDK7 (java-7-oracle), JAVA_HOME will be set to /usr/lib/jvm/java-7-oracle
update-alternatives: error: no alternatives for apt.
update-alternatives: error: no alternatives for apt.
Installing Android dependencies
$ android-update-sdk --components=tools
Installing tools
spawn android update sdk --no-ui --all --filter tools
Refresh Sources:
.....
Installing Archives:
  Preparing to install archives
  Downloading Android SDK Tools, revision 22.6.3
  Installing Android SDK Tools, revision 22.6.3
    Installed Android SDK Tools, revision 22.6.3
null  Done. 1 package installed.
$ android-update-sdk --components=build-tools-19.0.3
/home/travis/build.sh: line 215: /usr/local/android-sdk/tools/android-update-sdk: No such file or directory
The command "android-update-sdk --components=build-tools-19.0.3" failed and exited with 127 during setup.
```

**Comment by arctouch-rafaelcamargo** [comment]
@BanzaiMan my company suddenly started having this error. We didn't change anything on our side, do you guys made any changes?

https://www.dropbox.com/s/6953sfoycw4b3nh/Screenshot%202016-05-02%2017.15.42.png?dl=0

Here's a piece of my .travis file:

```
language: android
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
```
