### ISSUE TITLE
Node.js runtime is not yet available on OS X

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#2311]
No version of Node.js is available on OS X workers.

https://travis-ci.org/BanzaiMan/travis_production_test/builds/25121953

**Comment by xzyfer** [comment]
Sounded like this moving along nicely, any particular reason for the holdup?

**Comment by justinmchase** [comment]
:+1: 

I'm stuck on this now. Any workaround? I'm thinking I remove the `node_js: "iojs"` and then manually install nvm and then iojs? I'm cross building this on linux so I hope it works.

**Comment by vladikoff** [comment]
So currently the output is:
```
0.00s$ sudo service redis-server start
sudo: service: command not found
1.00s$ nvm install 0.10
/Users/travis/build.sh: line 41: nvm: command not found
The command "nvm install 0.10" failed and exited with 127 during .
Your build has been stopped.
```
is this a known issue?

**Comment by BanzaiMan** [comment]
For the time being, please use `brew install nvm` before the first invocation of `nvm`. That `service` is unavailable is a separate issue.

**Comment by vladikoff** [comment]
@BanzaiMan I don't invoke nvm, Travis CI does it automatically.
I'm not sure where I can add `brew install nvm` first

**Comment by TooTallNate** [comment]
For the record, here's the [.travis.yml file that NodObjC uses](https://github.com/TooTallNate/NodObjC/blob/master/.travis.yml):

``` yml
# Mac OS X (https://github.com/travis-ci-tester/toolchain-table)

language:
  - objective-c

env:
  - NODE_VERSION="0.8"
  - NODE_VERSION="0.10"
  - NODE_VERSION="0.12"

before_install:

install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - node --version
  - npm install

script:
  - make test
```

Works great!
