### ISSUE TITLE
Python runtime is not yet available on OS X

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#2312]
No version of Python is available via `virtualenv` on OS X workers.

https://travis-ci.org/BanzaiMan/travis_production_test/builds/25122306

**Comment by gildegoma** [comment]
Subscribe myself (@gildegoma) for direct e-mail notifications (sorry guys, for the mailing noise)

**Comment by ogrisel** [comment]
In the mean time, you might be interested in @matthew-brett's https://github.com/MacPython/terryfy to have bash utilities to install either Python.org, homebrew or macports installation of Python in a travis-ci OSX environment.

**Comment by blueyed** [comment]
Any progress in this regard?

I am seeing the following errors for the (changed) Neovim builds:

With Python 2.7 (https://travis-ci.org/neovim/neovim/jobs/58621371):

> $ source ~/virtualenv/python["2.7"]/bin/activate
/Users/travis/build.sh: line 41: /Users/travis/virtualenv/python[2.7]/bin/activate: No such file or directory

Here the `["2.7"]` seems odd.

And for Python 3.4 (https://travis-ci.org/neovim/neovim/jobs/58621375):

> No output has been received in the last ... minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated

**Comment by giampaolo** [comment]
Any news about this? I'm really looking forward to use travis on Python/OSX.

**Comment by matthew-brett** [comment]
Did you try https://github.com/MacPython/terryfy ?

You could do something like:

```
git clone https://github.com/MacPython/terryfy
source terryfy/travis_tools.sh
get_python_environment  macpython 2.7.10
```

**Comment by giampaolo** [comment]
@matthew-brett I don't understand what that is

**Comment by matthew-brett** [comment]
These are suggested lines in your `.travis.yml` file to automatically install a Python environment for testing against.   Olivier Grisel gave a good one-line summary above.  There are many examples of use in the repositories at https://travis-ci.org/MacPython.

**Comment by duncanwp** [comment]
I don't know how scalable this is, or if it's a long term solution, but on our project we've used miniconda to allow python builds on OS X, using e.g::

    install:

      # Install miniconda
      #  -----------------
      - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          wget http://repo.continuum.io/miniconda/Miniconda-3.7.0-MacOSX-x86_64.sh -O miniconda.sh;
        else
          wget http://repo.continuum.io/miniconda/Miniconda-3.7.0-Linux-x86_64.sh -O miniconda.sh;
        fi
      - bash miniconda.sh -b -p $HOME/miniconda
      - export PATH="$HOME/miniconda/bin:$PATH"

This has the added bonus of giving you access to many pre-built python libraries. It does require you to set the project language as 'c', but that's not a deal breaker for us.

**Comment by The-Compiler** [comment]
I do something similar with homebrew:

```python
brew update
brew install python3
```

**Comment by gappleto97** [comment]
Any news on this?

**Comment by tysonclugg** [comment]
Just to be clear, https://github.com/funkybob/django-classy-settings/issues/23 was closed because we disabled OSX builds on Travis CI -- not because the OSX builds are magically working again.  OSX builds using Python virtual environments still need to be fixed.

**Comment by gappleto97** [comment]
Can we please get an update on this? How high of a priority is this for you?

**Comment by williamjmorenor** [comment]
Python is available to test in OSX?

**Comment by matthew-brett** [comment]
Guys - it's really easy to get Python for testing on OSX.  You can use something like https://github.com/MacPython/terryfy to test against Python.org Python, or you can use something like conda.

**Comment by gappleto97** [comment]
That's not really the point, though. The problem is that this issue has been up for almost two years, and that they've been assuring us it would be solved for about as long.

At this point even a status update would be welcome.

**Comment by matthew-brett** [comment]
Sure - only pointing out that there are at least two easy workarounds for this problem, hence not very surprising that it's low priority for the travis-ci folks.

**Comment by ulope** [comment]
Is there anything we as contributors can do to help getting python jobs to work on OS X?

**Comment by williamjmorenor** [comment]
A example could good, current examples do not show how to get a python3 enviroment running.

https://docs.travis-ci.com/user/installing-dependencies#sts=Installing Packages on OSX

**Comment by ulope** [comment]
Well I meant more something the community could do along the lines of how to get "proper" python support to work on the OS X images. 

That it's possible to hack your way around it by specifying another language in `.travis-ci.yml` shouldn't even be documented IMO since it would cement the current broken status quo.

**Comment by enkoder** [comment]
Hey guys, just wanted to show everyone how I got my python app running on Travis on linux and OSX. Pretty easy IMO. 
```
language: python

matrix:
    include:
        # Use the built in venv for linux builds
        - os: linux
          sudo: required
          python: 3.5
        # Use generic language for osx
        - os: osx
          language: generic
# Perform the manual steps on osx to install python3 and activate venv
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
install:
    - pip install -r requirements.txt
# run those tests!
script: py.test
```

**Comment by gappleto97** [comment]
If anyone is looking for a cookie-cutter solution, I have a template repo that works for OSX, Windows, and Linux:

https://github.com/gappleto97/CITest

**Comment by BanzaiMan** [comment]
In #6247, @jayvdb writes:

----

When using the pre-installed pip to `pip install --user x` on osx , pip places scripts into `~/Library/Python/2.7/bin/` (contrary to [PEP 370]( https://www.python.org/dev/peps/pep-0370/ ) . however this isnt in the PATH.

It would be useful to include the following to workaround that:

```bash
export PATH=$PATH:~/Library/Python/2.7/bin/
```

**Comment by ale5000-git** [comment]
Is it fine to just use python on OS X with "language: generic" without install it (apparently already exist) or will it possibly break?

My .travis.yml:
> sudo: false
> language: python

> matrix:
>   include:
>     - os: linux
>       python: "2.6"
>     - os: linux
>       python: "3.4"
>     - os: linux
>       python: "pypy"
>     - os: osx
>       language: generic
>   allow_failures:
>     - os: osx

> install: true
> script: python script_to_test.py

**Comment by untitaker** [comment]
There exists one Python 2.7, other versions have to be installed via homebrew.

**Comment by Badg** [comment]
This is getting long, but for others' reference: I was constantly running into very annoying permissions errors. After much ado about essentially nothing, I realized that anything I was doing in ``before_install:`` was not being copied over into the actual install process (namely, the virtualenv was not persisting, so it was trying to use system python). My successful .travis.yml file, in its entirety, is:

```yaml
language: python
env:
  global:
    - CI=true

matrix:
  include:
    - os: linux
      python: 3.5
    
    - os: osx
      sudo: required
      language: generic
      
#  Manually install python on osx
install: |
  if [[ $TRAVIS_OS_NAME == 'osx' ]]; then

      brew update;
      brew install python3;
      python3 -m venv venv;
      source venv/bin/activate;
      pip install . test
      
  else
      pip install . test
  fi
  
script: python tests/supervisor.py

branches:
  only:
    - master
```

**Comment by denfromufa** [comment]
@Badg your script was very helpful, but here is improvement from @andyli when having too large if-else blocks:

https://github.com/travis-ci/travis-ci/issues/3448#issuecomment-250075501

**Comment by yan12125** [comment]
Seems https://github.com/travis-ci/cpython-builder/pull/3 should be fixed first

By the way, here's my current workaround: https://github.com/yan12125/python3-android/blob/master/travis/install-python-nightly.sh

**Comment by hobarrera** [comment]
This solution worked for me, and, importantly, isn't at all invasive (eg: doesn't involve adding commands/conditionals/script to non-OSX builds).

```yaml
matrix:
  include:
    - language: generic
      os: osx
      before_install:
        - brew update
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate

```
