### ISSUE TITLE
system_site_packages + Python 3.x = build error

### ISSUE THREAD

**Issue by dan-blanchard** [travis-ci/travis-ci#2328]
With a .travis.yml that looks like this:

``` yml
language: python
python:
  - 2.7
  - 3.4

notifications:
  email: false

# Install stuff
virtualenv:
  system_site_packages: true
before_install:
  - travis/install_sge.sh
  - export SGE_ROOT=/var/lib/gridengine
  - export SGE_CELL=default
  - export DRMAA_LIBRARY_PATH=/usr/lib/libdrmaa.so.1.0
  - export SEND_ERROR_MAIL=False
  - sudo mkdir /scratch/
  - sudo chmod 777 /scratch/
  # Work around for multiprocessing permission bug with Travis
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install python-coveralls --use-mirrors
  - pip install nose-cov --use-mirrors
  - python setup.py install

# Run test
script:
  - nosetests -x -d -v --with-cov --cov gridmap --cov-config .coveragerc --logging-level=DEBUG

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc

# Print out scratch job info if failed
after_failure:
  - tail -n 1000 /scratch/*
```

I consistently see this error with Python 3.3 and 3.4:

```
$ source ~/virtualenv/python3.4_with_system_site_packages/bin/activate
/home/travis/build.sh: line 206: /home/travis/virtualenv/python3.4_with_system_site_packages/bin/activate: No such file or directory

[31;1mThe command "source ~/virtualenv/python3.4_with_system_site_packages/bin/activate" failed and exited with 1 during setup.[0m
```

In this particular case, I think I can actually work around it by disabling `system_site_package`, but I still thought you guys should know.
