### ISSUE TITLE
Nested "secure:" not reported as a violation

### ISSUE THREAD

**Issue by zupo** [travis-ci/travis-ci#2341]
The following .travis.yml is reported as OK on http://lint.travis-ci.org, but it fails if you run it on Travis, due to the nested "secure:" key:

```
language: python
python:
  - 2.7

deploy:
    provider: heroku
    strategy: git
    api_key:
    secure:
      secure: |-
        SECRET HERE
```
