### ISSUE TITLE
Linter should accept sequences in deploy.run

### ISSUE THREAD

**Issue by kristjan** [travis-ci/travis-ci#2368]
The [Heroku deployment](http://docs.travis-ci.com/user/deployment/heroku/) docs indicate a `run` key that the linter doesn't accept:

``` yaml
deploy:
  provider: heroku
  api_key: ...
  run:
    - "rake db:migrate"
    - restart
    - "rake cleanup"
```

```
in deploy section: dropping run section: unexpected sequence
```
