### ISSUE TITLE
Displaying incorrect node version

### ISSUE THREAD

**Issue by adam-lynch** [travis-ci/travis-ci#2376]
Config:

``` yaml
language: node_js
node_js:
  - 0.10
  - 0.11
```

Then, I see:

![image](https://cloud.githubusercontent.com/assets/1427241/3143081/fdc586b6-e9e4-11e3-8c48-6e698396ff3c.png)
