### ISSUE TITLE
Silent failure on invalid secure string

### ISSUE THREAD

**Issue by jdanbrown** [travis-ci/travis-ci#2383]
## Repo 1

Valid secure string, i.e. encrypted with the repo's public key:

```
env:
  global:
    - secure: "MmgqwX2LE2mfIp18ZiAp0e6hPcgqDNDbZrIpN+h78eMcNEL8HHG92NqUnHZkyOy+8WPuWFIL0mzB4He5TqA991SCNuK5ILmsQCNVf8sdovdywHTTcciz5Axfa3dySqNp32B3Zms9HxuC9+WkRPAYeYp0LvpnapFVI4aDRfNMrD4="
  matrix:
    - 'TEST_MYSQL=true'

...
```

Build log showing `AWS_*` env vars, which come from the secure string:

```
Using worker: worker-linux-6-2.bb.travis-ci.com:travis-linux-1

$ export AWS_ACCESS_KEY_ID=[secure]
$ export AWS_SECRET_ACCESS_KEY=[secure]
$ export TEST_MYSQL=true

...
```
## Repo 2

Invalid secure string, i.e. encrypted with the wrong key:

```
env:
    global:
    - secure: "lUiqQlzEdNED52mHc4WvDr+lPP9FAP8ozQE7ugnaV632CB2RBAYlXY8vvXEsDtDoP2Qck4rSjCNI1y2ekh/zi4nGe1/pe1UFNEQpEvwOMlf2tm8z+vhXxq9S75m/83UGfSFfWioalBrorr5mLtOU0+OcY7rEb7h3IEMTA1IXq+k="
    matrix:
    - APP=true  DIR=app        ANDROID_SDKS=             ANDROID_TARGET=            ANDROID_ABI=
    - APP=false DIR=commons    ANDROID_SDKS=             ANDROID_TARGET=            ANDROID_ABI=
    - APP=true  DIR=pricespot  ANDROID_SDKS=android-19   ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

...
```

Build log showing no `AWS_*` env vars, which would be present except we accidentally encrypted the secure string with the wrong key:

```
Using worker: worker-linux-13-1.bb.travis-ci.com:travis-linux-10

$ export APP=true
$ export DIR=pricespot
$ export ANDROID_SDKS=android-19
$ export ANDROID_TARGET=android-19
$ export ANDROID_ABI=armeabi-v7a

...
```
## Problem

The build for repo 2 should fail upon failing to decrypt the secure string, but it instead silently ignores the failed decrypt and ends up failing on some later command that needed the env vars from the secure string. In our case the downstream error wasn't obviously related to the missing env vars, so failing fast and loud on this kind of error would be helpful.
