### ISSUE TITLE
Unit testing of mouse move events in Qt.

### ISSUE THREAD

**Issue by oddkiva** [travis-ci/travis-ci#2387]
Dear travis-CI team,

I am not sure if the problem is actually a non-issue.

I have set up a mini C++ project (https://github.com/davidok8/QtTestExample) that unit-tests mouse move events that happens in a Qt widget.
Travis can build the unit test example without any problem but the unit-test fails when it runs. In constrast, the unit test runs fine on my local machine.

Do I somehow need to "activate" the mouse in Travis? If yes, how to do this? Thanks.

Here is a copy-paste of my `.travis.yml` (https://github.com/davidok8/QtTestExample/blob/master/.travis.yml):

``` yml
language: cpp
compiler:
  #- clang
  - gcc
before_install:
  # Print working directory
  - pwd
  # Check CMake version.
  - cmake --version
  # Remove the rabbitmq source file since it currently times out and 
  # we don't need it.
  - sudo rm -f /etc/apt/sources.list.d/rabbitmq-source.list
  # Update apt repositories to get GNU compiler 4.8.
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  # Update apt repositories to get Qt5.
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  # Install Qt5
  - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
  # Fake X server
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
```
