### ISSUE TITLE
Cannot find right scheme for iOS project

### ISSUE THREAD

**Issue by dailycafi** [travis-ci/travis-ci#2412]
This is my .travis.yml

``` YAML
language: objective-c
before_install:
    - export LANG=en_US.UTF-8
    - gem install cocoapods
    - pod install

branches:
    - AppTestBranch

script:
    - xctool -workspace Zynch.xcworkspace -scheme Zynch -sdk iphonesimulator test -only ZynchTests:LoginTests
```

on Travis, the error is: 

```
$ xctool -workspace Zynch.xcworkspace -scheme Zynch -sdk iphonesimulator test -only ZynchTests:LoginTests
ERROR: Can't find scheme 'Zynch'.
Possible schemes include:
  Pods-DTCoreText
  Pods-DTFoundation
  Pods
TIP: This might happen if you're relying on Xcode to autocreate your schemes
and your scheme files don't yet exist.  xctool, like xcodebuild, isn't able to
automatically create schemes.  We recommend disabling "Autocreate schemes"
in your workspace/project, making sure your existing schemes are marked as
"Shared", and making sure they're checked into source control.
The command "xctool -workspace Zynch.xcworkspace -scheme Zynch -sdk iphonesimulator test -only ZynchTests:LoginTests" exited with 1.
```

It is running perfectly locally on my computer.

I've set both Zynch and Pods Scheme to be shared.

I've tried checked and unchecked the autocreate schemes in Xcode.

What should I try next.
