### ISSUE TITLE
Even though there are tags I get: "Skipping deployment with the releases provider because this is not a tagged commit."

### ISSUE THREAD

**Issue by peterwilli** [travis-ci/travis-ci#2498]
Hi guys,

I have tried this serveral times but the build keeps not recognizing tags, see build job here: https://travis-ci.org/Gameeso/openkit-android/jobs/29407750

If you look at the commit, there clearly is a tag. Why does it keep rejecting my release?
Travis config:

```
language: java
jdk:
  - openjdk7
before_script: travis/before_script.sh
script: travis/script.sh
branches:
  only:
  - development
  - master
deploy:
  provider: releases
  api_key:
    secure: xxx
  file: Gameeso-Android-SDK.zip
  skip_cleanup: true
  on:
    repo: Gameeso/openkit-android
    tags: true
    all_branches: true
```

Thanks!
