### ISSUE TITLE
xvfb failing to start again

### ISSUE THREAD

**Issue by hecbuma** [travis-ci/travis-ci#2500]
I'm having problems starting xvfb this is my `.travis.yml`

```
language: ruby
cache:
  - bundler: true
rvm:
  - ruby-1.9.3-p484
script: bundle exec rspec $TESTFOLDER

before_install:
  - sudo apt-get install libicu-dev
before_script:
  - mysql -e 'create database travis_test;'
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:schema:load
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
services:
  - redis-server
after_failure: # this will of course run only on failure
  - gem install --version 0.8.0 faraday
  - gem install travis-artifacts
  - travis-artifacts upload --path /home/travis/build/project/little_bits/tmp/capybara
env:
  global:
    - "RAILS_ENV=test"
  matrix:
    - TESTFOLDER="spec/models spec/controllers spec/presenters spec/services spec/services spec/workers"
    - TESTFOLDER=spec/features
```

and this is the output
![travis_ci_-_hosted_continuous_integration_that_just_works_and_sparrow](https://cloud.githubusercontent.com/assets/363669/3511901/c51ee384-06b3-11e4-94d8-8de97e7c9b23.png)

Any thoughts?
