### ISSUE TITLE
travis-lint errors about unsupported Python version 3.4

### ISSUE THREAD

**Issue by Mikaela** [travis-ci/travis-ci#2534]
Trying to update the gem:

``` bash
# gem update travis-lint
Updating installed gems
Nothing to update
```

Running `travis-lint .travis.yml`

```
/home/mikaela/src/git/Mkaysi/supybot-plugins/.travis.yml has issues:
  Found an issue with the `python:` key:
    Detected unsupported Python versions. For an up-to-date list of supported Python versions, see Travis CI documentation at http://bit.ly/travis-ci-environment
```

`.travis.yml` that I was trying to validate and hope the `allow_failures` part is valid:

``` yml
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install -vr https://raw.githubusercontent.com/ProgVal/Limnoria/testing/requirements.txt
    - pip install -v git+https://github.com/ProgVal/Limnoria.git@testing
    - pip install -vr requirements.txt
# command to run tests, e.g. python setup.py test
script:
  - echo $TRAVIS_PYTHON_VERSION
  - export PYTHON_MAJOR_VERSION=$(echo $TRAVIS_PYTHON_VERSION|head -c 1)
  - if [ "$PYTHON_MAJOR_VERSION" = "3" ]; then export DISABLED_PLUGINS="--exclude=./NoLatin1"; else export DISABLED_PLUGINS=""; fi
  - supybot-test --plugins-dir=. --no-network $DISABLED_PLUGINS
notifications:
    on_success: never
    on_failure: never
matrix:
    # REMOVE THIS SECTION WHEN ALL BUILDS ALWAYS PASS!
    allow_failures:
        - python:
            - pypy
    fast_finish: true
```
