### ISSUE TITLE
Using bash aliases inside .travis.yml

### ISSUE THREAD

**Issue by hamiltont** [travis-ci/travis-ci#2552]
Is this possible? If so, could there be some documentation? 

I've tried echo'ing the aliases to ~/.bashrc and ~/.bash_profile, and using alias directly inside each section of the yml. No luck so far, but this seems like it should be possible

**Comment by bblacey** [comment]
I've managed to use aliases on Travis-Ci by including ```shopt -s expand_aliases``` because aliases are disabled by default for non-interactive shells.

**Comment by kenorb** [comment]
You can use the variables, here is the example (note `$DOCKER_LOGIN` and `$DOCKER_PUSH`):

```
env:
  global:
  - DOCKER_REPO="foo/bar"
  - DOCKER_LOGIN='eval [[ -n "$DOCKER_PASSWORD" ]] && docker login -u $DOCKER_USERNAME --password-stdin <<<$DOCKER_PASSWORD || exit 0'
  - DOCKER_PUSH='docker push $DOCKER_REPO'
  matrix:
  - CMD="$DOCKER_LOGIN && docker build --target foo -t ${DOCKER_REPO}:mytag . && [[ '$TRAVIS_PULL_REQUEST' = 'false' ]] && ${DOCKER_PUSH}:mytag"
script:
- echo $CMD
- eval $CMD
```

**Comment by max-rocket-internet** [comment]
Here's an update with what I did as I've found this issue via Google searches multiple times now...

> I've managed to use aliases on Travis-Ci by including shopt -s `expand_aliases`

This didn't work for me. I don't know why. Travis just shows a `build_and_push: not found` error with my `.travis.yaml` looking like this:

```yaml
install:
  - alias build_and_push="echo "building tag $VERSION" && docker build . -t $DOCKER_IMAGE_NAME:$VERSION && $(aws ecr get-login --no-include-email --region eu-west-1) && docker push $DOCKER_IMAGE_NAME:$VERSION"

deploy:
  - provider: script
    script:
      - build_and_push && .....
```

So I used @kenorb's method using `eval`. I think this actually a better way as it can behave almost like a function:

```
$ export function_example='expr $VAR1 + $VAR2'
$ VAR1=5 VAR2=8 eval $function_example
13
$ VAR1=20 VAR2=8 eval $function_example
28
```

Where an if an alias has variables inside it, they are fixed when the alias is defined.

So in the end here's part of our `.travis.yaml` file:

```yaml
env:
  global:
    - check_image='aws ecr list-images --repository-name $ECR_NAME | jq -e ".imageIds[] | select(.imageTag == \"$VERSION\")" > /dev/null'
    - build_and_push='echo "building tag $VERSION" && docker build . -t $DOCKER_IMAGE_NAME:$VERSION && $(aws ecr get-login --no-include-email --region eu-west-1) && docker push $DOCKER_IMAGE_NAME:$VERSION'
    - run_deploy='some commands here for our deployment'

deploy:
  - provider: script
    skip_cleanup: true
    script: >-
      (eval $check_image || eval $build_and_push) && eval $run_deploy
```

With this logic if the docker images doesn't exist in AWS ECR, it will be built and then pushed. And then as long as the image already exists or it was successfully built then it will be deployed.
