### ISSUE TITLE
Job priorities

### ISSUE THREAD

**Issue by tobyink** [travis-ci/travis-ci#2566]
So if I have [twenty-three jobs](https://travis-ci.org/tobyink/p5-type-tiny/builds/30795844) kicked off by a git push, it would be nice if my `.travis.yml` file could tell Travis which ones I care the most about (so would like to be built first).

Something like:

```
matrix:
  include:
    - perl: "5.18"
      env: COVERAGE=1 EXTENDED_TESTING=1
      priority: 1
```
