### ISSUE TITLE
The command "nvm use 0.1" failed and exited with 1 during .

### ISSUE THREAD

**Issue by it-ony** [travis-ci/travis-ci#2591]
For the first time I saw this error `The command "nvm use 0.1" failed and exited with 1 during .` with the following .travis.yml

``` yaml
language: node_js
node_js:
  - 0.10
...
```

For complete output see https://travis-ci.org/rappid/rAppid.js/builds/31216474
