### ISSUE TITLE
Add apache to the standard environment

### ISSUE THREAD

**Issue by AD7six** [travis-ci/travis-ci#2600]
After chatting a little in #travis with josh-k.

To make it possible to _not_ use sudo and therefore take advantage of the new travis setup - please preinstall apache.

Ideally, and I don't know if this is viable, such that it can be added to the build matrix like so:

```
matrix:
  include:
    - apache: "2.2.x"
    - apache: "2.4.x"
```

The repo I'm making this ticket for currently has a [sizable setup script](https://github.com/h5bp/server-configs-apache/blob/master/test/setup/setup.sh) to install the desired version of apache for each build.
