### ISSUE TITLE
nvm 0.1

### ISSUE THREAD

**Issue by morganherlocker** [travis-ci/travis-ci#2601]
.travis.yml:

``` yml
language: node_js
node_js:
  - 0.10
```

The build has been failing since yesterday because nvm is trying to switch to node 0.1.

![img](https://dl.dropbox.com/s/icbdvm4chky3bge/Screenshot%202014-07-31%2011.53.18.png)
