### ISSUE TITLE
Unable to find jruby-2*mode

### ISSUE THREAD

**Issue by alexfalkowski** [travis-ci/travis-ci#2671]
Apologies if this is not the right medium to raise these issues. I just thought I would flag it with you guys. I have my configuration

``` yaml
language: ruby
rvm:
  - 2.0
  - 2.1
  - jruby-20mode
  - jruby-21mode
```

Though I get the following errors:

```
Requested binary installation but no rubies are available to download, consider skipping --binary flag.
Gemset '' does not exist, 'rvm jruby-d20 do rvm gemset create ' first, or append '--create'.
```

```
Requested binary installation but no rubies are available to download, consider skipping --binary flag.
Gemset '' does not exist, 'rvm jruby-d21 do rvm gemset create ' first, or append '--create'.
```
