### ISSUE TITLE
Question about npm publish security

### ISSUE THREAD

**Issue by thaiat** [travis-ci/travis-ci#2685]
Hi,

I have a public github repo that I'm successfully publishing to `npm` using travis on every new tag.
My `.travis.yml` file looks like this:

```
deploy:
  provider: npm
  email: my@email.com
  api_key:
    secure: XX8AMRt...

```

Can you explain how the api_key (also it is encrypted) offers security, if someone would just copy my `.travis.yml` into its own repo and simply use it for building his own repo?
