### ISSUE TITLE
libgearman-dev

### ISSUE THREAD

**Issue by till** [travis-ci/travis-ci#2691]
We current install `libgearman-dev` via `apt`. This prevents us from moving to docker.

cc @joshk

**Comment by meatballhat** [comment]
See travis-ci/travis-build#372 :smiley_cat:

**Comment by BanzaiMan** [comment]
Add

```yaml
addons:
  apt_packages:
    - libgearman-dev
```
