### ISSUE TITLE
Feature Request: Use of environment variable for email receipients

### ISSUE THREAD

**Issue by tgraf** [travis-ci/travis-ci#2711]
It would be useful to be able to specify the email notification list as an environment variable configurable through the travis-ci settings page. This would allow for a main repo to have this template committed with the actual recipients configurable per fork.

Bonus: If the env variable is empty, the default of author/comitter is used as fallback.

```
notifications:
  email:
    recipients:
      - ${NOTIFY_LIST}
```
