### ISSUE TITLE
Chromedriver support?

### ISSUE THREAD

**Issue by zspencer** [travis-ci/travis-ci#272]
Would be nice if we could have chromedriver and/or firefox for ui testing.

**Comment by LaiaPR** [comment]
Hi!
I am just trying to run Protractor tests on Travis using Chrome (with xvfb). Is it possible by now?

Thanks!

**Comment by LaiaPR** [comment]
Sorry, it's me again!

I have found this: http://blog.500tech.com/setting-up-travis-ci-to-run-tests-on-latest-google-chrome-version/
And following it, I have been able to run my Protractor tests on Travis CI on Chrome :)

**Comment by wikibootup** [comment]
From good references 
- https://github.com/travis-ci/travis-ci/issues/272#issuecomment-14402117
- http://jellyms.kr/804

I used it in Django environment. like below
```yml
language: python

python:
  - "3.5"

dist: trusty
sudo: required
addons:
  packages:
    - unzip
    - google-chrome-stable

before_install:
    # Install Chrome driver
    - wget http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - sudo chmod u+x chromedriver
    - sudo mv chromedriver /usr/bin/

    # For selenium in headless linux system
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
...
```

**Comment by gruppjo** [comment]
@LaiaPR, I tried the link you posted. However I ran into issues while executing my protracotor commands.
![image](https://cloud.githubusercontent.com/assets/1370779/16299131/00e0752c-3939-11e6-9298-62fe0f72041e.png)
Would you mind sharing your `.travis.yml`?

**Comment by wikibootup** [comment]
@gruppjo I hope it works out

https://github.com/wikibootup/hashtags/blob/develop/.travis.yml
https://travis-ci.org/wikibootup/hashtags

**Comment by LaiaPR** [comment]
hi  @gruppjo !!

Sorry for the delay ... Now I am using a more complex configuration, because I am using Gulp to launch my tests with Protractor and the tests are executed in Saucelabs ... But I hope this example can help you!


```
language: node_js

sudo: false

node_js:
  - "4.2.1"

cache:
  apt: true
  directories:
  # cache for all npm packages needed
    - $(npm config get prefix)/bin/gulp
    - node_modules

before_script:
  - npm install -g gulp
  - ./node_modules/protractor/bin/webdriver-manager update

script:
  # run unit tests with gulp
  - gulp test 
  # start xvbfb, required for e2e tests
  - Xvfb :99 &
  - export DISPLAY=:99
  - sleep 5 # give xvfb some time to start
  # start the webdriver and run e2e tests with protractor
  - ( ./e2e_tests/node_modules/protractor/bin/webdriver-manager start &> /tmp/selenium.log ) & (sleep 10 && gulp e2e_tests && sleep 5 )

```

Also, I am worried that can be some error with the code itself, because the error you get is like protractor is not finding the element you are requesting because it is not visible ... Maybe you should take a look at the Expected Conditions you can use with Protractor and wait for the element, for example, to be clickable : [http://www.protractortest.org/#/api?view=ExpectedConditions.prototype.elementToBeClickable ]

Hope this helps!!

**Comment by Harshdeep1996** [comment]
I think Travis does support chromium, if you add these in your travis.yml
``` 
before_script:
  - wget http://chromedriver.storage.googleapis.com/2.10/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.9/
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 
```

Plus when you call selenium or any testing automation library,

```
options = webdriver.ChromeOptions()
	options.binary_location = '/usr/bin/chromium-browser'
	#All the arguments added for chromium to work on selenium
	options.add_argument("--no-sandbox") #This make Chromium reachable
	options.add_argument("--no-default-browser-check") #Overrides default choices
	options.add_argument("--no-first-run")
	options.add_argument("--disable-default-apps") 
	driver = webdriver.Chrome('/home/travis/virtualenv/python2.7.9/chromedriver',chrome_options=options)
```

**Comment by pomle** [comment]
If you came here looking for the solution in JavaScript
```javascript
const webdriver = require('selenium-webdriver');
const chrome = require('selenium-webdriver/chrome');

const options = new chrome.Options();
options.addArguments('no-sandbox');

const builder = new webdriver.Builder();
builder.forBrowser('chrome');
builder.setChromeOptions(options);

const driver = builder.build();
```

**Comment by mileo** [comment]
Hi, here is my repo, with chrome/selenium and travis working https://github.com/kmee/odoo-travis-robotframework

**Comment by fulls1z3** [comment]
Hope it helps:

```
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - "6"
cache:
  directories: node_modules
branches:
  only: master

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i -g npm@^3
  - sleep 3
```

**Comment by timp** [comment]
It would be good to have a way of using chromedriver, as per the issue title: 
"Would be nice if we could have chromedriver and/or firefox for ui testing."

**Comment by reach2jeyan** [comment]
Has anybody succeeded in debugging the issue?

I still get this error

```
Unable to find chromedriver. Please download the server from http://chromedriver.storage.googleapis.com/index.html and place it somewhere on your PATH. More info at https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver.
 (Selenium::WebDriver::Error::WebDriverError)
```

**Comment by LaiaPR** [comment]
Hi @reach2jeyan 

it seems that new Linux version comes with Chrome pre-installed, you can see an example here:https://github.com/antonsamper/gulp-webpack-boilerplate/blob/master/.travis.yml

Hope it helps!

**Comment by reach2jeyan** [comment]
@LaiaPR Thanks! I ll try this out and let you know.

**Comment by reach2jeyan** [comment]
@LaiaPR I still get the error

```
Unable to find chromedriver. Please download the server from http://chromedriver.storage.googleapis.com/index.html and place it somewhere on your PATH. More info at https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver.
 (Selenium::WebDriver::Error::WebDriverError)
/home/travis/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.0.8/lib/selenium/webdriver/common/service.rb:59:in `binary_path'
/home/travis/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.0.8/lib/selenium/webdriver/common/service.rb:49:in `initialize'
/home/travis/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.0.8/lib/selenium/webdriver/chrome/bridge.rb:35:in `new'
/home/travis/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.0.8/lib/selenium/webdriver/chrome/bridge.rb:35:in `initialize'
/home/travis/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.0.8/lib/selenium/webdriver/common/driver.rb:61:in `new'
/home/travis/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.0.8/lib/selenium/webdriver/common/driver.rb:61:in `for'
/home/travis/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.0.8/lib/selenium/webdriver.rb:82:in `for'
/home/travis/.rvm/gems/ruby-2.3.1/gems/watir-6.1.0/lib/watir/browser.rb:46:in `initialize'
/home/travis/build/divhegde/CucmbrEx/features/step_definitions/test_steps.rb:7:in `new'
/home/travis/build/divhegde/CucmbrEx/features/step_definitions/test_steps.rb:7:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.3.1/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96:in `load'
/home/travis/.rvm/gems/ruby-2.3.1/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96:in `load_code_file'
/home/travis/.rvm/gems/ruby-2.3.1/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:142:in `load_file'
/home/travis/.rvm/gems/ruby-2.3.1/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:84:in `block in load_files!'
/home/travis/.rvm/gems/ruby-2.3.1/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:in `each'
/home/travis/.rvm/gems/ruby-2.3.1/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:in `load_files!'
/home/travis/.rvm/gems/ruby-2.3.1/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:253:in `load_step_definitions'
/home/travis/.rvm/gems/ruby-2.3.1/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:61:in `run!'
/home/travis/.rvm/gems/ruby-2.3.1/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:32:in `execute!'
/home/travis/.rvm/gems/ruby-2.3.1/gems/cucumber-2.4.0/bin/cucumber:8:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.3.1/bin/cucumber:23:in `load'
/home/travis/.rvm/gems/ruby-2.3.1/bin/cucumber:23:in `<main>'
/home/travis/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
The command "bundle exec cucumber" exited with 2.
Done. Your build exited with 1.
```

My latest `.travis.yml` file looks like this. Kindly let me know if any changes are required. My project is built on cucucmber/gherkin with ruby using `WATIR` for browser testing.

```

sudo: required
language: ruby
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable


script: bundle exec cucumber


before_script:
        - bundle install
        - gem install watir
        - gem install colorize
        - gem install rspec
        - gem install cucumber
        - gem install rake
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3
        

branches:
  only:
    - master

notifications:
  email:
    - iamsmj@gmail.com

```

**Comment by reach2jeyan** [comment]
@LaiaPR I updated my `.travis.yml` to this now, and the new error is 

```
0.90s$ gem install watir
Successfully installed watir-6.1.0
1 gem installed
before_script.3
0.45s$ gem install colorize
Fetching: colorize-0.8.1.gem (100%)Fetching: colorize-0.8.1.gem (100%)
Successfully installed colorize-0.8.1
1 gem installed
before_script.4
0.64s$ gem install rspec
Successfully installed rspec-3.5.0
1 gem installed
before_script.5
0.74s$ gem install cucumber
Successfully installed cucumber-2.4.0
1 gem installed
before_script.6
0.44s$ gem install rake
Successfully installed rake-12.0.0
1 gem installed
before_script.7
0.65s$ gem install chromium
Fetching: mustache-0.99.8.gem (100%)Fetching: mustache-0.99.8.gem (100%)
Successfully installed mustache-0.99.8
Fetching: chromium-0.1.0.gem (100%)Fetching: chromium-0.1.0.gem (100%)
Successfully installed chromium-0.1.0
2 gems installed
before_script.8
0.05s$ wget http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip
--2017-02-14 11:00:45--  http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip
Resolving chromedriver.storage.googleapis.com (chromedriver.storage.googleapis.com)... 74.125.129.128, 2607:f8b0:4001:c0b::80
Connecting to chromedriver.storage.googleapis.com (chromedriver.storage.googleapis.com)|74.125.129.128|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2692616 (2.6M) [application/zip]
Saving to: ‘chromedriver_linux64.zip’
 0% [                                       ] 0           --.-K/s              100%[======================================>] 2,692,616   --.-K/s   in 0.01s   
2017-02-14 11:00:45 (173 MB/s) - ‘chromedriver_linux64.zip’ saved [2692616/2692616]
before_script.9
0.08s$ unzip chromedriver_linux64.zip
Archive:  chromedriver_linux64.zip
  inflating: chromedriver            
before_script.10
0.01s$ sudo chmod u+x chromedriver
before_script.11
0.01s$ sudo mv chromedriver /usr/bin/
before_script.12
0.00s$ export CHROME_BIN=chromium-browser
before_script.13
0.00s$ export DISPLAY=:99.0
before_script.14
0.01s$ sh -e /etc/init.d/xvfb start
Starting virtual X frame buffer: Xvfb.
before_script.15
3.01s$ sleep 3
2.55s$ bundle exec cucumber
end of file reached (EOFError)
The command "bundle exec cucumber" exited with 2.
Done. Your build exited with 1.
```

My `.travis.yml` looks like this now. Any ideas to get this fixed?

```

sudo: required
language: ruby
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable


script: bundle exec cucumber


before_script:
        - bundle install
        - gem install watir
        - gem install colorize
        - gem install rspec
        - gem install cucumber
        - gem install rake
        - gem install chromium
        - wget http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip
        - unzip chromedriver_linux64.zip
        - sudo chmod u+x chromedriver
        - sudo mv chromedriver /usr/bin/
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3
        

branches:
  only:
    - master

notifications:
  email:
    - iamsmj@gmail.com

```

**Comment by reach2jeyan** [comment]
@LaiaPR I tried pushing a feature file and it seems like now the error is, it cannot access `chromedriver` ?

```
/home/travis/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect': Failed to open TCP connection to 127.0.0.1:9515 (Connection refused - connect(2) for "127.0.0.1" port 9515) (Errno::ECONNREFUSED)
	from /home/travis/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
	from /home/travis/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	from /home/travis/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
	from /home/travis/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:878:in `connect'
	from /home/travis/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1476:in `begin_transport'
	from /home/travis/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1433:in `transport_request'
	from /home/travis/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1407:in `request'
	from /home/travis/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1156:in `get'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.0.8/lib/selenium/webdriver/common/service.rb:116:in `block in stop_server'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.0.8/lib/selenium/webdriver/common/service.rb:97:in `block in connect_to_server'
	from /home/travis/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:853:in `start'
	from /home/travis/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:584:in `start'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.0.8/lib/selenium/webdriver/common/service.rb:93:in `connect_to_server'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.0.8/lib/selenium/webdriver/common/service.rb:116:in `stop_server'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.0.8/lib/selenium/webdriver/common/service.rb:79:in `stop'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.0.8/lib/selenium/webdriver/common/service.rb:69:in `block in start'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.0.8/lib/selenium/webdriver/common/platform.rb:138:in `block in exit_hook'


The command "bundle exec cucumber" exited with 2.

Done. Your build exited with 1.
```

**Comment by reach2jeyan** [comment]
@LaiaPR Finally I could pass the `chromedriver` error only to see a new error, which wont build my tests

https://api.travis-ci.org/jobs/201587885/log.txt?deansi=true

```
My updated `.travis.yml`

sudo: required
language: ruby
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable


script: bundle exec cucumber


before_script:
        - bundle install
        - gem install watir
        - gem install colorize
        - gem install rspec
        - gem install cucumber
        - gem install rake
        - gem install chromium
        - wget http://chromedriver.storage.googleapis.com/2.7/chromedriver_linux64.zip
        - unzip chromedriver_linux64.zip
        - sudo apt-get install libnss3
        - sudo apt-get --only-upgrade install google-chrome-stable
        - sudo cp chromedriver /usr/local/bin/.
        - sudo chmod +x /usr/local/bin/chromedriver
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3


branches:
  only:
    - master

notifications:
  email:
    - iamsmj@gmail.com

```

**Comment by reach2jeyan** [comment]
@LaiaPR Finally! I am able to run it. Looks like the issue with `chromedriver` latest 2.7 version. I had to downgrade to `2.27`

Thanks

**Comment by zeljkofilipin** [comment]
It is even simpler now.

```yaml
sudo: required
dist: trusty
language: ruby
rvm:
 - 2.2
before_install:
 - sudo apt-get update
 - sudo apt-get install chromium-chromedriver
before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
```

From: https://github.com/zeljkofilipin/mediawiki-selenium-rb/blob/master/.travis.yml
Job: https://travis-ci.org/zeljkofilipin/mediawiki-selenium-rb/

**Comment by yeukhon** [comment]
Okay.. I am confused how to support headless mode while using chromedriver WITHOUT XVFB. I am trying to run Chrome in headless mode.

Here is my travis.yml
```yaml
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: python
python:
  - "2.7"
before_install:
  - wget https://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -O /tmp/chromedriver
  - chmod 777 /tmp/chromedriver
install:
  - python setup.py develop
env:
  - CHROME_DRIVER_PATH=/tmp/chromedriver
script: pytest
```

Here is my code in Python.

```python
ef setup_browser():
    """Returns a Chrome browser instance."""
    try:
        driver_path = os.environ["CHROME_DRIVER_PATH"]
    except KeyError as e:
        raise KeyError("Expect CHROME_DRIVER_PATH as environment variable")

    chrome_options = SOptions()
    chrome_options.add_argument("--headless")
    return webdriver.Chrome(driver_path, chrome_options=chrome_options)
```

This code works on local. Travis failed with:

```shell
_____________________________ test_non_exist_gmail _____________________________

non_exist_gmail = 'name.taken.yet.test.b60f5f51@gmail.com'

    def test_non_exist_gmail(non_exist_gmail):
>       result = check_account_exists(non_exist_gmail)

tests/test_check_gmail.py:39: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
name_taken_yet/check_gmail.py:41: in check_account_exists
    with open_browser(GMAIL_SIGNUP_URL, account_name) as browser:
/opt/python/2.7.13/lib/python2.7/contextlib.py:17: in __enter__
    return self.gen.next()
name_taken_yet/check_gmail.py:31: in open_browser
    browser = setup_browser()
name_taken_yet/check_gmail.py:27: in setup_browser
    return webdriver.Chrome(driver_path, chrome_options=chrome_options)
../../../virtualenv/python2.7.13/lib/python2.7/site-packages/selenium-3.4.3-py2.7.egg/selenium/webdriver/chrome/webdriver.py:62: in __init__
    self.service.start()
../../../virtualenv/python2.7.13/lib/python2.7/site-packages/selenium-3.4.3-py2.7.egg/selenium/webdriver/common/service.py:96: in start
    self.assert_process_still_running()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <selenium.webdriver.chrome.service.Service object at 0x7f4bfb0ad090>

    def assert_process_still_running(self):
        return_code = self.process.poll()
        if return_code is not None:
            raise WebDriverException(
                'Service %s unexpectedly exited. Status code was: %s'
>               % (self.path, return_code)
            )
E           WebDriverException: Message: Service /tmp/chromedriver unexpectedly exited. Status code was: 1

../../../virtualenv/python2.7.13/lib/python2.7/site-packages/selenium-3.4.3-py2.7.egg/selenium/webdriver/common/service.py:109: WebDriverException
=========================== 3 failed in 3.16 seconds ===========================
```

My code: https://github.com/yeukhon/name-taken-yet/blob/8e57a1b386575a4d8f869491e6779adb0c71cb9e/name_taken_yet/check_gmail.py

I appreciate if someone can provide me a pointer.
