### ISSUE TITLE
Linter crashes on notifications block

### ISSUE THREAD

**Issue by daenney** [travis-ci/travis-ci#2756]
I was working on a Web hook receiver for Travis and I wanted to lint my `.travis.yml`. However, it keeps throwing internal server errors at me:

``` yaml
script: exit 1

notifications:
  webhooks:
    urls:
      - https://781a43dc.ngrok.com/travis
    on_success: always
    on_failure: always
    on_start: true
```

Removing the web hooks key still makes it crash, when I completely empty out the notification block it 'validates' and tells me what's wrong instead of the Internal Server Error.
