### ISSUE TITLE
Allow to specify branches in the build matrix

### ISSUE THREAD

**Issue by thedrow** [travis-ci/travis-ci#2778]
This is useful for example if I want to build only the python3 branch with Python 3.x and PyPy3.
I encountered this use case with: https://github.com/chtd/psycopg2cffi where Python 3 support has not been added to the mainline yet but we should still test it for the relevant branch that provides support for Python 3.

**Comment by untitaker** [comment]
I think I need this feature to have a different build matrix for pull requests and master pushes.

The full build matrix includes about 40 jobs -- just spinning that many VMs up takes up a serious amount of time. I'd like to give the PR author quick feedback using the stripped down testsuite (which is only one job), while keeping the master branch running on the full testsuite.

**Comment by lasote** [comment]
For a regular workflow with branches in Github is not an option to maintain different `.travis.yml` files in different branches, you will be merging and solving conflicts in every feature, release, hotfix branch.
Why don't you enable something more dynamic than a `travis.yml' to describe the build matrix? A ruby/python script would be nice and simpler.

**Comment by kennytm** [comment]
This feature is now supported via [conditional jobs](https://docs.travis-ci.com/user/conditional-builds-stages-jobs/#Conditional-Jobs), by using the `if` entry inside `matrix.include`. For instance, OP's `.travis.yml` may be written as:

```yaml
matrix:
  fast_finish: true
  include:
    - python: 2.6
    - python: 2.7
    - python: 3.2
      if: branch = python3
    - python: 3.3
      if: branch = python3
    - python: 3.4
      if: branch = python3
    - python: 3.5
      if: branch = python3
    - python: pypy
    - python: pypy3
      if: branch = python3
```
