### ISSUE TITLE
IRC credentials are not decrypted by Travis-CI.

### ISSUE THREAD

**Issue by Minecrell** [travis-ci/travis-ci#2813]
I'm trying to let Travis join a password-protected IRC Server. The documentation says nothing about how that could be done, but after looking at the [travis-tasks IRC addon source](https://github.com/travis-ci/travis-tasks/blob/master/lib/travis/addons/irc/task.rb#L82) it looks like I can use `nick` and `password` to join a password-protected server.

This is working fine, but of course I want to encrypt the IRC credentials so not everyone can just log on the IRC server. I'm trying to use the configuration like this ([from the example project I'm testing with](https://github.com/Minecrell/TravisTest/blob/master/.travis.yml)):

```yaml
notifications:
  irc:
    channels:
    - secure: "NDM9YsUdXrLEp2LTy+vJS+w+c23+O1zJLvx2Cw2fpkK27Ok7bgKwxd6Qd0kR8cRE487+J1TNNHaczUviOJx0N+CM4oCbVdGCqwYotnTQpGVIuxsFNArEGR6NPozGiIjsRyG4VupRPjUyZGzDHMTZjAKXs8GBOGPfrwCBoweopKo="
    nick:
      secure: "NpfuWy7mno4HC1tAMcD9ttSGlCab6W4rWJW6NRriDD9dd9aptusJVXpnGZlubrEOqEgQLVil1nY0Lb2IltSegqjK0rIabOOLrIZ3lB3vDlWK5dH+9s2zxPh5y0+fkuolJViodgut1gs7irCX89p+D8oY51UYLLLrwOe2nNwSLrs="
    password:
      secure: "KHWzA7BukwroBAeS3ncdmdGk5f3v77HO3rXqA0mlGdWfgn/RMn1hew3/zObR6MQPyaXT7yKv/NI5+BsSD/zb7JsUCdUxqP8WCa8QQEtQ2J67MgnlKos5YbrLB0A1c4Gy0jxRvqmrbIzwKk3saXRvRCjPzjZ3dZDSNQT4a/5HEM8="
```

Travis decrypts the `channels` correctly and is joining the server, but it doesn't decrypt the `nick` and `password` so it connects with something like this:
```
_LISTENER == ConnectionFrom(hidden, hidden) [Allowed]
CLI -> IRC [PASS {:secure=>"KHWzA7BukwroBAeS3ncdmdGk5f3v77HO3rXqA0mlGdWfgn/RMn1hew3/zObR6MQPyaXT7yKv/NI5+BsSD/zb7JsUCdUxqP8WCa8QQEtQ2J67MgnlKos5YbrLB0A1c4Gy0jxRvqmrbIzwKk3saXRvRCjPzjZ3dZDSNQT4a/5HEM8="}]
CLI -> IRC [NICK {:secure=>"NpfuWy7mno4HC1tAMcD9ttSGlCab6W4rWJW6NRriDD9dd9aptusJVXpnGZlubrEOqEgQLVil1nY0Lb2IltSegqjK0rIabOOLrIZ3lB3vDlWK5dH+9s2zxPh5y0+fkuolJViodgut1gs7irCX89p+D8oY51UYLLLrwOe2nNwSLrs="}]
CLI -> IRC [USER {:secure=>"NpfuWy7mno4HC1tAMcD9ttSGlCab6W4rWJW6NRriDD9dd9aptusJVXpnGZlubrEOqEgQLVil1nY0Lb2IltSegqjK0rIabOOLrIZ3lB3vDlWK5dH+9s2zxPh5y0+fkuolJViodgut1gs7irCX89p+D8oY51UYLLLrwOe2nNwSLrs="} {:secure=>"NpfuWy7mno4HC1tAMcD9ttSGlCab6W4rWJW6NRriDD9dd9aptusJVXpnGZlubrEOqEgQLVil1nY0Lb2IltSegqjK0rIabOOLrIZ3lB3vDlWK5dH+9s2zxPh5y0+fkuolJViodgut1gs7irCX89p+D8oY51UYLLLrwOe2nNwSLrs="} {:secure=>"NpfuWy7mno4HC1tAMcD9ttSGlCab6W4rWJW6NRriDD9dd9aptusJVXpnGZlubrEOqEgQLVil1nY0Lb2IltSegqjK0rIabOOLrIZ3lB3vDlWK5dH+9s2zxPh5y0+fkuolJViodgut1gs7irCX89p+D8oY51UYLLLrwOe2nNwSLrs="} :{:secure=>"NpfuWy7mno4HC1tAMcD9ttSGlCab6W4rWJW6NRriDD9dd9aptusJVXpnGZlubrEOqEgQLVil1nY0Lb2IltSegqjK0rIabOOLrIZ3lB3vDlWK5dH+9s2zxPh5y0+fkuolJViodgut1gs7irCX89p+D8oY51UYLLLrwOe2nNwSLrs="}]
```

In #1628 only the `channels` were decrypted so I believe this is the same problem here. But maybe I'm just using the wrong syntax?

Thanks in advance!

**Comment by Minecrell** [comment]
Any chance to get this fixed?

**Comment by jkcclemens** [comment]
+1 on a fix for this. I would like to use Travis, but without being able to have IRC notifications connect to my bouncer, which I'd rather not share the password to, it's hardly worth it.

**Comment by turt2live** [comment]
Also just ran across this for a similar issue to @jkcclemens. Wanted to send IRC notifications but didn;t want to leave the password in the repository.

Hopefully this gets fixed/looked at soon.

**Comment by MineDev2014** [comment]
+1. This has been open for more than an half year already, can we get this fixed? (@meatballhat?)

**Comment by meatballhat** [comment]
So sorry, everyone! :heart: :heart: :heart:  We'll update soon with a plan o' action.

**Comment by MineDev2014** [comment]
@meatballhat Any news on this issue?

**Comment by MineDev2014** [comment]
@meatballhat Any news on this issue?

**Comment by akerl** [comment]
Ping? We're fast approaching the 1 year mark for this issue

**Comment by MineDev2014** [comment]
@meatballhat Any news on this issue? This issue has been open for almost a year now.

**Comment by MineDev2014** [comment]
Bump. Can we get this fixed?

**Comment by akerl** [comment]
@meatballhat What's up here? To be honest, things like this mean that while I'll continue futzing around with Travis for my personal stuff that doesn't matter, anytime anybody asks me about using TravisCI for a serious or business task, I have to warn them that the response for security-related concerns is lackluster

**Comment by meatballhat** [comment]
@akerl What's up here is that this particular issue is not a high priority, and tbh I'm not the one who sets priorities, and as much as I'd love to see this addressed, there's a backlog of work that needs to get done ahead of adding encrypted variable support to the IRC notifier.  Your perspective is very much understood.  You are not being ignored.  This issue will be addressed when it can be addressed.

**Comment by joshk** [comment]
Hi @akerl 

I'm sorry for the delay in us looking into this issue.

I will talk to the team on Monday to see what we can do about this, at least providing you an ETA.

Our long term goal is to move all notifications into the UI, but that became delayed due to other issues and features which took priority.

Have a great Sunday

Josh

**Comment by BanzaiMan** [comment]
Hello, everyone!

Sorry for the delay. I spent much of yesterday looking at this issue.

In the end, I have been unable to reproduce this problem.

Look at https://github.com/BanzaiMan/travis_production_test/blob/baf6d2546a609bcf6613fdec99f12ca9a1d07372/.travis.yml and its corresponding build https://travis-ci.org/BanzaiMan/travis_production_test/builds/80358082

The encrypted string was created by:

```sh-sessoin
$ travis encrypt 'chat.freenode.net#travis' --org -r BanzaiMan/travis_production_test
Please add the following to your .travis.yml file:

  secure: "dSznAbLrYmUG1mAAPYi453v4YzMW9zca3RawHrtpvmdLytTAxAxIYhmgG17XLlCO1qT+9/bYaAIYk/JETatxbjI1mi8KIsd6S50pdZaKPtkhLGugU46/5kR7sBq8J4kVOB5MOmVNfrRSHIAOukCb3YZ9j4YUB9CcSyLscKny83c="

Pro Tip: You can add it automatically by running with --add.
```

The message was posted on Freenode, as you can see at https://botbot.me/freenode/travis/2015-09-15/?msg=49725832&page=1

Could you double check how you are creating the encrypted string? If you prefer not to divulge that information publicly, please email support@travis-ci.com with details (which repo, which build, and so on).

**Comment by Minecrell** [comment]
@BanzaiMan Thanks for testing the issue! I will test this again later today, however keep in mind in your test you are only encrypting **the channel name and IRC server** which is working fine as also mentioned in the issue description above. The problem did only happen for the **`nick` and `password’** fields (e.g. If you want to connect to a IRC bouncer) which are much more important to be able to encrypt.

**Comment by BanzaiMan** [comment]
I have also tried encrypting `nick` and `password` (which are currently undocumented). From what I can tell, they are decrypted correctly. If there are issues, it appears to lie elsewhere.

**Comment by Minecrell** [comment]
@BanzaiMan I'm sorry; however I can't test it currently because I can simply not get SSL working for IRC anymore. I'm pretty sure I had that working when I was initially testing the issue, however I don't have the original configuration anymore (only the encrypted addresses) so not exactly sure anymore how it did work; however I'm pretty sure it was something like this:

```yaml
notifications:
  irc:
    channels:
      - 'ircs://irc.example.com:9868#example'
    nick: 'example'
    password: 'example_password'
```

Results in the following for some reason (on my bouncer):
```
_LISTENER == ConnectionFrom(hidden, hidden) [Allowed]
There are [0] clients from [hidden]
src/Csocket.cpp:602 at src/Csocket.cpp:3325
src/Csocket.cpp:607 error:140940E5:SSL routines:SSL3_READ_BYTES:ssl handshake failure
```
I guess that's happening because it's probably not even connecting with ssl....

**Comment by BanzaiMan** [comment]
@Minecrell Thanks for testing. One thing to keep in mind is that we cannot talk to all servers over SSL (http://docs.travis-ci.com/user/notifications/#Note-on-SSL-TLS-Ciphers).

@akerl @jkcclemens @MineDev2014 Do you have tests to confirm that it is not working today?

**Comment by BanzaiMan** [comment]
Is this still an issue?

**Comment by BanzaiMan** [comment]
I will close this at the end of the month (2015-09-30) if no one is objecting.

**Comment by jkcclemens** [comment]
Maybe I'm doing something wrong, but this is what happens to me when I try to use this.

`[2015-10-12 16:18:18] [{] failed to login from 54.145.30.21`

[.travis.yml](https://github.com/Cardstock/Cardstock/blob/master/.travis.yml#L7)

**Comment by BanzaiMan** [comment]
@jkcclemens This is quite peculiar. Our logs indicate that, for your repository, the nick we used was `Cardstock` with a capital C, and it is the string we used for writing the NICK command to the socket: `NICK Cardstock\r\n`.

**Comment by jkcclemens** [comment]
Not sure why this issue is popping up, then. I'm having it connect to my bouncer. If it helps to know the details, I can share them in a more private setting.

**Comment by BanzaiMan** [comment]
Currently, we do not do anything with the responses from the IRC server. We simply read and discard them. I can add more debugging output to our logs. Unfortunately, there is currently no way to communicate the failures to the user.

**Comment by BanzaiMan** [comment]
Still having problems reproducing:

[This empty commit](https://github.com/BanzaiMan/travis_production_test/commit/01343b6f574a6dbb95de3a37568e61c3f6a691bd), with [this configuration](https://github.com/BanzaiMan/travis_production_test/blob/01343b6f574a6dbb95de3a37568e61c3f6a691bd/.travis.yml):

```yaml
notifications:
  irc:
    channels:
      - secure: "HG6NULIEesFw/C46muw1P6CKf645+AROlBTf6+6F9IttsU0baFK8HYzbW5COMy8oag0odSZymLSN3B3vS+vDRRiImxaayJksnaq+Gxn8o/7RklCskeDCEhVghYaJqbZQq6LsiEV1wn+Hfp1ocLPeb90j6YhJsPhRsSBZey8anyY="
    on_success: always
    on_failure: always
```

 created [this build](https://travis-ci.org/BanzaiMan/travis_production_test/builds/86696745), and [notified Freenode successfully](https://botbot.me/freenode/travis/2015-10-21/?msg=52444434&page=3).
