### ISSUE TITLE
Getting "Skipping deployment with the s3 provider because this branch is not permitted to deploy" erroneously

### ISSUE THREAD

**Issue by behemphi** [travis-ci/travis-ci#2824]
I am getting the message at the top of the build output:

`Skipping deployment with the s3 provider because this branch is not permitted to deploy`
- This is on the master branch where there are no restrictions on such a deployment.  
- A branch called "develop" does not seem to have the problem.
- This is happening on two of our three repos (all private).  
- It is, as far as I can tell, non-deterministic as to whether the message appears and the deploy happens.  

That last is to say that just b/c the message appears, does not mean the binary did not get deployed as expected.  Though sometimes when I see the message it does not, in fact, deploy.

Possibly related to #2498?

**Comment by ianaya89** [comment]
I am facing the same issue, I have a conditional deploy based on branches: `master` and `develop`.  The branch master is working ok but `develop` throws this message:
`Skipping a deployment with the elasticbeanstalk provider because this branch is not permitted`

Here is my `.travis.yml` setup:

```
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "sa-east-1"
  app: "mtn"
  env: "dev"
  on:
    branch: develop
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "sa-east-1"
  app: "mtn"
  env: "prod"
  on:
    branch: master
```
