### ISSUE TITLE
Wrong failure message for Python projects if `script` is missing

### ISSUE THREAD

**Issue by mathias-nyman** [travis-ci/travis-ci#2870]
With this as the .travis.yml:

``` yaml
language: python
python:
    - "2.7"
install:
    - make build
```

Travis will say:
...
Please override the script: key in your .travis.yml to run tests.
The command "make build" exited with 1.

The 'make build' succeeds, so the error print get's messed up to think that 'make build' failed, although the non-existant script is the failure. I would have expected that only testing the installation is possible without a 'script:' section.

Workaround:
Add a dummy "script: echo foo" to .travis.yml
