### ISSUE TITLE
Support multiple job configurations as YAML documents

### ISSUE THREAD

**Issue by dbarnett** [travis-ci/travis-ci#2873]
Some repositories need to test more than one configuration. For instance, a single repository might need to run tests for python, C, and "generic" languages. Travis CI should support more than one configuration per repository.

A straightforward way to implement it would be to read multiple [YAML documents](http://yaml.org/spec/1.2/spec.html#id2800132) separated by `---` from the .travis.yml file. For example:

``` YAML
language: python
script: nosetests

---
language: generic
script: somescript

---
language: generic
script: anotherscript
```
