### ISSUE TITLE
HHVM - PDepend - PHPMD

### ISSUE THREAD

**Issue by juliangut** [travis-ci/travis-ci#2896]
I'm experiencing an issue when running pdepend/phpmd on hhvm

``` yaml
language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

install:
  - composer install --dev --no-interaction
  - phpenv rehash

script:
  - ./vendor/bin/phpcs --standard=./phpcs.xml ./src
  - ./vendor/bin/phpmd ./src text ./phpmd.xml
  - ./vendor/bin/phpcpd ./src
  - ./vendor/bin/phpunit --configuration ./phpunit.xml --coverage-clover ./build/logs/clover.xml
```

With this configuration I get:
Unable to parse file "/home/.../vendor/pdepend/pdepend/src/main/php/PDepend/DependencyInjection/../../../resources/services.xml"./home/travis/build.sh: line 41:  3079 Segmentation fault      ./vendor/bin/phpmd ./src text ./phpmd.xml

On any PHP version it works but in HHVM, so I added the `allow_failures`!
