### ISSUE TITLE
Opsworks deployment on specific layer / instance

### ISSUE THREAD

**Issue by Nighthawk14** [travis-ci/travis-ci#2905]
I want to deploy on opsworks on a specific instance / layer, is it possible to configure that with travis ? I have tried different things but nothing is working for the moment :/.

The deployment itself is working but it's launched on all the instances of all layers

last try :

```
deploy:
  provider: opsworks
  access_key_id: <ACCESS KEY>
  secret_access_key:
    secure: <SECURE SECRET KEY>
  app-id: <APP ID>
  on:
    repo: <REPO>
    branch: master
    instance-id: <INSTANCE ID>
```

Thanks !!
