### ISSUE TITLE
rvm get stable failing with signature verification error

### ISSUE THREAD

**Issue by driskell** [travis-ci/travis-ci#2919]
Hi,

Seeing errors on builds today regarding signature verification when calling rvm get stable
https://travis-ci.org/driskell/log-courier/jobs/39367224

Any ideas? I've removed the "rvm get stable" and it now work - though I'm wondering why it all of a sudden stopped working. I'm just hoping I don't actually need to run the get stable, it was originally taken from a template I originally used and I thought it may be needed if the Travis VM didn't happen to have the latest ruby versions available.

Jason

**Comment by jeffdaily** [comment]
Seeing this same issue using the following config.

```yaml


{
  "language": "c",
  "script": "./ci_build.sh",
  "before_deploy": ". ./ci_deploy.sh",
  "install": "set -e\nif [ \"$TRAVIS_OS_NAME\" == \"osx\" ]; then\n  rvm get stable\nfi\n",
  "compiler": "gcc",
  "os": "osx",
  "osx_image": "xcode8.2"
}
```
Here's the build link. https://travis-ci.org/jeffdaily/travis-broken-example/jobs/199837135

I had to add rvm get stable to the build to work-around the problem in #6307 .
`/Users/travis/build.sh: line 148: shell_session_update: command not found`
