### ISSUE TITLE
Environment variable containing the PHP version?

### ISSUE THREAD

**Issue by mnapoli** [travis-ci/travis-ci#2948]
Is there a way to get the current PHP version?

For example:

``` yaml
language: php

php:
  - 5.5
  - 5.4

after_script:
  - php vendor/bin/coveralls
```

In `after_script`, how can I test if PHP == 5.5 so that I can do code coverage only for one job?
