### ISSUE TITLE
mcrypt.so extension is not available in PHP 5.4, 5.5, 5.6

### ISSUE THREAD

**Issue by nazar-pc** [travis-ci/travis-ci#2985]
> Warning: PHP Startup: Unable to load dynamic library '/home/travis/.phpenv/versions/5.6.2/lib/php/extensions/no-debug-zts-20131226/mcrypt.so' - /home/travis/.phpenv/versions/5.6.2/lib/php/extensions/no-debug-zts-20131226/mcrypt.so: cannot open shared object file: No such file or directory in Unknown on line 0

My `.travis.yml` config:

``` yml
language: php
php:
- 5.4
- 5.5
- 5.6
services:
- memcached
env:
global:
- REPORT_EXIT_STATUS=1
before_script:
- mysql -e 'CREATE DATABASE `cscms.travis`;'
- echo 'yes' | pecl install apcu-beta
- echo 'extension = memcached.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- echo 'extension = mcrypt.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script: php run-tests.php -P --show-diff tests
```
