### ISSUE TITLE
What do I need to add to my .travis.yml to build with GDK?

### ISSUE THREAD

**Issue by sciencepro** [travis-ci/travis-ci#3000]
I'm currently getting 

````
failed to find target Google Inc.:Glass Development Kit Preview:19 : /usr/local/android-sdk
````

My .travis.yml looks like this:
````
language: android
android:
  components:
    - build-tools-21.1.1
    - extra-android-support
    - addon-google_gdk-google-19
  licenses:
    - android-sdk-license-5be876d5 # new license!
    - '.*intel.+'
````

What can I change to make this work?
