### ISSUE TITLE
Linter should accept sequences in deploy.files

### ISSUE THREAD

**Issue by leonard84** [travis-ci/travis-ci#3125]
In Section "Uploading Multiple Files" on http://docs.travis-ci.com/user/deployment/releases/

The following snippet is given:
```
deploy:
  provider: releases
  api-key: "GITHUB OAUTH TOKEN"
  file:
    - "FILE 1"
    - "FILE 2"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
```
However `travis lint` fails with 
`[x] in deploy section: dropping files section: unexpected sequence`

**Comment by leonard84** [comment]
Same error if you use file instead of files 

`[x] in deploy section: dropping file section: unexpected sequence`

**Comment by Yimiprod** [comment]
Same problem here.

**Comment by fterrier** [comment]
+1 for this, is it just the linter that displays the wrong problem or is it really not supposed to be used with multiple files ?

**Comment by Jylhis** [comment]
Same problem here, any fixes for this?

**Comment by SorJEF** [comment]
+1 any comments?

**Comment by Yimiprod** [comment]
After some test something like this works (i think it's the double quote who make not work):
```
deploy:
  provider: releases
  skip_cleanup: true
  api-key: "githubtoken"
  file: release/*.zip
  file_glob: true
```

**Comment by leonard84** [comment]
@Yimiprod no this is not using a list of files but one `file` element with the glob flag. This won't work if you can't glob all files you want to deploy in one statement, e.g., different directories or mixed with other files.

**Comment by Yimiprod** [comment]
Forget the glob, put file list without quotes, before glob i managed to make it work this way.
```
deploy:
  provider: releases
  skip_cleanup: true
  api-key: "githubtoken"
  file:
    - fileone.zip
    - filetwo.gzp
```
