### ISSUE TITLE
graphicsmagick on docker based container

### ISSUE THREAD

**Issue by drogus** [travis-ci/travis-ci#3128]
One of the customers asked about installing graphicsmagick on docker based images. Currently this is a blocker for them to start using the new infrastructure.

**Comment by mfornasa** [comment]
+1

**Comment by BanzaiMan** [comment]
Add

```yaml
addons:
  apt_packages:
    - graphicsmagick
```
