### ISSUE TITLE
When build matrix has only one job and it is allowed to fail, show the build matrix

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#3168]
```yaml
language: ruby
sudo: false
install: false
script: false
rvm:
  - 2.2.0
matrix:
  allow_failures:
    - rvm: 2.2.0
```

This shows a build page with a single build page in which the job fails but the build passes. Logically this is sound, but the display is confusing.

In this case (or perhaps even when the only job is not allowed to fail), we should present a build matrix page.
