### ISSUE TITLE
Docker exit directly in launched

### ISSUE THREAD

**Issue by CaptainJojo** [travis-ci/travis-ci#3170]
I need Linux Kernel 3.8 to launch Docker, you have any idea to integrate docker.

Travis.yml
``` yml
language: node_js
node_js:
  - "0.10"
install:
  - sudo sh -c "wget -qO- https://get.docker.io/gpg | apt-key add -"
  - sudo sh -c "echo deb http://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
  - sudo apt-get update
  - sudo apt-get install lxc-docker
  - echo "127.0.0.1  dockerhost" | sudo tee -a /etc/host
before_script:
  - sudo chmod 777 /var/run/docker.sock
  - sudo docker -d
  - npm install
  - npm install -g grunt
script:
  - grunt test
```

![capture du 2015-02-03 16 56 17](https://cloud.githubusercontent.com/assets/1083083/6023551/a6828284-abc5-11e4-9c86-5fc11e8a954b.png)

Any idea ?
