### ISSUE TITLE
Github release with multiple files fails travis-lint

### ISSUE THREAD

**Issue by jayjanssen** [travis-ci/travis-ci#3179]
I am trying to upload multiple files to a Github release following the example given here: http://docs.travis-ci.com/user/deployment/releases/

Here is my .travis.yml:

```
language: go
go:
  - 1.4
install:
  - go get github.com/mitchellh/gox
script:
  - go test -bench=. ./...
  - gox -os="linux darwin freebsd" -arch="386 amd64 arm" -build-toolchain
  - gox -os="linux darwin freebsd" -arch="386 amd64 arm" -output="bin/myq_status.{{.OS}}-{{.Arch}}"
  - tar cvzf myq_tools.tgz bin/*
  - zip myq_tools.zip bin/*
git:
  submodules: false
notifications:
  email:
    recipients:
    - jay.janssen@gmail.com
    on_success: change
    on_failure: change
deploy:
  provider: releases
  api_key:
    secure: Zpb1YS6oYPf+KJPWp/ye8bW+pULxmZkhoBBkFIgyM30FbiCmPuZJLqm7Kkw4gUAYisj90lrsGedpvK4aHlE4BZXYt5yBuXHapjImACzX2rm1ssPbtAoyx/68SARSTB3Bm2/MCfI8Py5IRlJCzyTmK1quopWYyUGd/uSbmbsmJzQ=
  file: 
    - "myq_tools.tgz"
    - "myq_tools.zip"
  skip_cleanup: true 
  on:
    repo: jayjanssen/myq-tools
    all_branches: true
    tags: true
```

However, travis-lint does not like the multiple files:

```
$ travis-lint
- deploy: dropping "file" section: unexpected sequence
```

What am I missing?
