### ISSUE TITLE
Cannot add iojs as allowed failure

### ISSUE THREAD

**Issue by hassankhan** [travis-ci/travis-ci#3217]
Hi there, I tried adding iojs to my build matrix but also setting it as an allowed failure. [It didn't work](https://travis-ci.org/hassankhan/emojify.js/builds/50251771).

I ran this:
```yaml
language: node_js
node_js:
  - "0.10"
  - "0.11"
  - iojs

matrix:
  allow_failures:
    - node_js: "0.11"
    - node_js: "iojs"
```

through the validator and it gives the following error: `in node_js section: value iojs is not a valid version`
