### ISSUE TITLE
npm on standard image is too old (1.4.28)

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#3252]
https://github.com/travis-ci/travis-cookbooks/blob/71544db8ba0da66eadbf9ffbf20dd1d8d68559ab/ci_environment/nodejs/recipes/multi.rb#L63 suggests we should have the latest version of npm installed on all VMs, but it is not.

**Comment by DaAwesomeP** [comment]
Run `sudo npm install -g npm`

**Comment by BanzaiMan** [comment]
Prepending `#{nvm} ` before `nvm_download` in the code above updates npm, but this results in:

```
    vmware-iso: ================================================================================
    vmware-iso: Error executing action `run` on resource 'bash[install grunt-cli for node version 0.10.36]'
    vmware-iso: ================================================================================
    vmware-iso:
    vmware-iso: Mixlib::ShellOut::ShellCommandFailed
    vmware-iso: ------------------------------------
    vmware-iso: Expected process to exit with [0], but received '1'
    vmware-iso: ---- Begin output of "bash"  "/tmp/chef-script20150403-1073-1eex5sx" ----
    vmware-iso: STDOUT: Now using node v0.10.36
    vmware-iso: STDERR: npm WARN locking Error: EACCES, open '/home/travis/.npm/_locks/grunt-cli-33c648f8252fa1b0.lock'
    vmware-iso: npm WARN locking  /home/travis/.npm/_locks/grunt-cli-33c648f8252fa1b0.lock failed { [Error: EACCES, open '/home/travis/.npm/_locks/grunt-cli-33c648f8252fa1b0.lock']
    vmware-iso: npm WARN locking   errno: 3,
    vmware-iso: npm WARN locking   code: 'EACCES',
    vmware-iso: npm WARN locking   path: '/home/travis/.npm/_locks/grunt-cli-33c648f8252fa1b0.lock' }
    vmware-iso: npm ERR! Linux 3.13.0-32-generic
    vmware-iso: npm ERR! argv "node" "/home/travis/.nvm/v0.10.36/bin/npm" "install" "-g" "grunt-cli"
    vmware-iso: npm ERR! node v0.10.36
    vmware-iso: npm ERR! npm  v2.7.5
    vmware-iso:
    vmware-iso: npm ERR! Attempt to unlock /home/travis/.nvm/v0.10.36/lib/node_modules/grunt-cli, which hasn't been locked
    vmware-iso: npm ERR!
    vmware-iso: npm ERR! If you need help, you may report this error at:
    vmware-iso: npm ERR!     <https://github.com/npm/npm/issues>
    vmware-iso:
    vmware-iso: npm ERR! Please include the following file with any support request:
    vmware-iso: npm ERR!     /home/travis/npm-debug.log
    vmware-iso: ---- End output of "bash"  "/tmp/chef-script20150403-1073-1eex5sx" ----
```

Which I believe is https://github.com/npm/npm/issues/6309 (or variant thereof).

It is not clear to me how we can specify the version of npm other than the latest (which one?) to install with https://npmjs.org/install.sh.

Perhaps we can just document this and advise users to update npm if necessary.
