### ISSUE TITLE
[NFR] Run matrix PHP & C 

### ISSUE THREAD

**Issue by ovr** [travis-ci/travis-ci#3258]
Hi all :)

https://github.com/owl-framework/owl/blob/master/.travis.yml#L1

I would like to use .travis.yaml

```yaml
language:
  - php
  - c

compiler:
  - gcc
  - clang

php:
  - 5.4
  - 5.5
  - 5.6
```

And get matrix 

PHP
5.4 clang and gcc
5.5 clang and gcc
5.6 clang and gcc

But i am getting 

PHP
5.4
5.5
5.6
without PHP x Compiler

Now I cant do it by default, because travis use only first language for matrix
But i am using 

```
env:
  - CC="gcc"
  - CC="clang"
```

to hack it

Thanks
