### ISSUE TITLE
make it possible to configure notifications for forks separately

### ISSUE THREAD

**Issue by lsmith77** [travis-ci/travis-ci#329]
the fork configuration should be used if the given repository is not the root on github:

```
notifications:
    irc: "irc.freenode.org#foobar"

fork_notifications:
    irc: false
```

The above is just an illustration. Maybe it would be better to allow a single "forks" section that simply overrides the default config?

```
language: php

php:
    - 5.3
    - 5.4

notifications:
    irc: "irc.freenode.org#foobar"

forks:
    php: 5.3

    notifications:
        irc: false
```
