### ISSUE TITLE
APT whitelist request for python-pip

### ISSUE THREAD

**Issue by kkaefer** [travis-ci/travis-ci#3292]
Please whitelist `python-pip` and its dependency `python-setuptools`. It is used to install other tools with `pip`, e.g `awscli`.

**Comment by BanzaiMan** [comment]
Python is available on all images, and you can use `pip install --user` to install scripts into `$HOME/.local/bin`. So:

```yaml
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
⋮
script:
  - aws
```

should work.
