### ISSUE TITLE
Github Release, agnostic file field

### ISSUE THREAD

**Issue by Yimiprod** [travis-ci/travis-ci#3311]
Is there a way to set a file to release without having to naming entirely.
Something like this:
```
deploy:
  provider: releases
  skip_cleanup: true
  file:
    - release/*.zip
```
