### ISSUE TITLE
Specifying jdk versions in non-java projects

### ISSUE THREAD

**Issue by jawshooah** [travis-ci/travis-ci#3433]
I'm working on a node project that uses a Java jar file internally. I'd like to test against multiple Java runtimes in addition to multiple nodejs versions, but Travis seems to ignore my `jdk` settings. How can I include both `node_js` and `jdk` in the build matrix?

For reference, here's my `.travis.yml`.

```yaml
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
before_script:
  - npm install -g grunt-cli
matrix:
  fast_finish: true
```

**Comment by BanzaiMan** [comment]
If you need to test against multiple JDK versions, it is easier to use `language: java`, since multiple JDSs are pre-installed. `nvm` will install whatever Node.js version you tell it to, so you can say, for example:

```yaml
language: java

env:
  - TRAVIS_NODE_VERSION=0.10
  - TRAVIS_NODE_VERSION=0.12
  - TRAVIS_NODE_VERSION=iojs

before_install:
  - nvm use $TRAVIS_NODE_VERSION
⋮
```
