### ISSUE TITLE
/home/travis/build.sh: line 175: brew: command not found

### ISSUE THREAD

**Issue by andyli** [travis-ci/travis-ci#3448]
Since 3 hours ago, the OSX builds have been failing with the error:
```
/home/travis/build.sh: line 175: brew: command not found
```

An example build can be found at https://travis-ci.org/HaxeFoundation/haxe/builds/55650892

**Comment by andyli** [comment]
The build log starts with `Using worker: worker-linux-08b40318-1.bb.travis-ci.org:travis-linux-14`, so it seems it is using a wrong worker (linux instead of mac).
Note that the haxe repo has multi-os enabled long time ago.

**Comment by henrikhodne** [comment]
Thanks for raising this! We changed our queueing logic earlier today, which seems to have affected multi-os jobs. We've fixed the bug now, but unfortunately the queue (and therefore worker type) is assigned when the request comes from GitHub, so restarting the job won't help in fixing this. Any new commits should go to the OS X workers again, though.

**Comment by andyli** [comment]
I confirm the new builds are normal now. Thanks!
BTW, I hope multi-os will be generally available soon, since we've a few more repos would be benefited :)

**Comment by epwalsh** [comment]
I am having a similar problem, I am just trying to build on os x yet the build seems to be reverting to linux. This is my .travis.yml:

```
language: cpp
os: osx
compiler: 
  - clang 
before_install:
  - brew update 
  - brew install boost 
script: 
  - make
notifications:
  - email:
    on_success: change
    on_failure: change
```
