### ISSUE TITLE
Feature request: deploy by updating git branch

### ISSUE THREAD

**Issue by aseemk** [travis-ci/travis-ci#3482]
We continuously deploy web apps & services, with confidence through CI. E.g.:

- Commit freely to master — no extra work necessary;
- Travis tests those commits;
- If they pass, they get deployed. If they don't, they don't.

However, if you're working on a shared module or library rather than a web app or service, there's an extra manual step (for most cases AFAICT, e.g. [RubyGems](http://docs.travis-ci.com/user/deployment/rubygems/) / [PyPI](http://docs.travis-ci.com/user/deployment/pypi) / [npm](http://docs.travis-ci.com/user/deployment/npm/) / [GitHub Releases](http://docs.travis-ci.com/user/deployment/releases/)):

- Manually tag every commit.

(And because tags need to be unique in most cases, there's also the manual step of bumping the version number, e.g. `1.0.5` to `1.0.6`. Tools like `npm version` can help with this though.)

I'd like to propose a new deploy option to solve this problem: update a git branch. E.g.:

```yaml
deploy:
  provider: branch
  branch: stable  # or 'tested' or w/e
  on: master  # this'd be the default, though, like with Heroku, etc.
```

This would update the `stable` branch (i.e. `git push` to it — non-force, to ensure only ffwd pushes) so that it "follows" `master`, but "holds"/"pauses" if `master` introduces a bug.

I'm not very familiar with RubyGems, PyPI, and other platforms, but at least in the Node world, this could be used via npm's [git dependency support](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies) to achieve "live" but *tested* dependencies.

⟹ The result: continuous deployment of modules that's both automatic and safe.

Worth noting: this could also be used on any platform via git submodules too, as git submodules can "track" branches like `stable` too.

Thanks for the consideration!

**Comment by aseemk** [comment]
Also worth noting: this could also work with semantic versioning:

```yaml
deploy:
  provider: branch
  branch:
    master: 3.x
    v2-maint: 2.x
    v1-maint: 1.x
```

This would "deploy" successful master commits to the `3.x` branch, but you could still reference and update previous `2.x` and `1.x` branches.
