### ISSUE TITLE
Travis-build : no implicit conversion of String into Integer when executing `travis compile`

### ISSUE THREAD

**Issue by AugierLe42e** [travis-ci/travis-ci#3601]
When trying to build a Travis build script using `travis compile` I got the following error :

    TypeError: no implicit conversion of String into Integer

The complete report is the following :

```
System
Ruby:                     Ruby 2.1.5-p273
Operating System:         Debian 7.8
RubyGems:                 RubyGems 2.4.3
 
CLI
Version:                  1.7.5
Plugins:                  "travis-build"
Auto-Completion:          yes
Last Version Check:       2015-04-06 08:22:32 -0400
 
Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                no
Verify SSL:               yes
Enterprise:               no
 
Endpoints
org:                      https://api.travis-ci.org/ (current)
 
Last Exception
An error occurred running `travis compile`:
    TypeError: no implicit conversion of String into Integer
        from /var/lib/jenkins/.travis/travis-build/init.rb:62:in `[]'
        from /var/lib/jenkins/.travis/travis-build/init.rb:62:in `sanitize_global_env'
        from /var/lib/jenkins/.travis/travis-build/init.rb:25:in `run'
        from /var/lib/jenkins/.rvm/gems/ruby-2.1.5/gems/travis-1.7.5/lib/travis/cli/command.rb:198:in `execute'
        from /var/lib/jenkins/.rvm/gems/ruby-2.1.5/gems/travis-1.7.5/lib/travis/cli.rb:64:in `run'
        from /var/lib/jenkins/.rvm/gems/ruby-2.1.5/gems/travis-1.7.5/bin/travis:18:in `<top (required)>'
        from /var/lib/jenkins/.rvm/gems/ruby-2.1.5/bin/travis:23:in `load'
        from /var/lib/jenkins/.rvm/gems/ruby-2.1.5/bin/travis:23:in `<main>'
        from /var/lib/jenkins/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
        from /var/lib/jenkins/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by BanzaiMan** [comment]
Could you show what `.travis.yml` looks like?

**Comment by AugierLe42e** [comment]
Sure !

```
language: ruby

rvm:
  - 2.1
  - 2.0

env:
  - DB=postgres BUILD_TYPE=other
  - DB=mysql BUILD_TYPE=other
  - DB=postgres BUILD_TYPE=cucumber
  - DB=mysql BUILD_TYPE=cucumber

sudo: false
cache:
  bundler: true
  directories:
    - app/assets/images

branches:
  only:
    - 'master'
    - 'develop'

before_install: gem install bundler
bundler_args: "--without development production heroku --jobs 3 --retry 3"

script: "./script/ci/build.sh"

notifications:
  irc:
    channels:
      - "irc.freenode.org:6667#diaspora-dev"
```
