### ISSUE TITLE
No environment variables set?

### ISSUE THREAD

**Issue by NobbZ** [travis-ci/travis-ci#3602]
The overview of https://travis-ci.org/NobbZ/boofar/builds/57350728 shows that there were no env-vars set, but the corresponding [`.travis.yml`](https://github.com/NobbZ/boofar/blob/8b1cf926989a627742c4235908b5347368766cc1/.travis.yml) does contain the following:

```yml
env:
  global:
    - CI=true
  matrix:
    - TEST_DOC=false
    - TEST_DOC=true
```

Also the logs display them in the exporting list:

```plain
$ export CI=true
$ export TEST_DOC=false
```

```plain
$ export CI=true
$ export TEST_DOC=true
```

One run earlier (before I added the global-env) `TEST_DOC` showed up properly as a set ENV-var (see https://travis-ci.org/NobbZ/boofar/builds/57334624)

I'd expect that at least matrix variables show up on the summary.
