### ISSUE TITLE
problem when using matrix: include:

### ISSUE THREAD

**Issue by andyli** [travis-ci/travis-ci#3638]
When providing a list of a single value to a key that can be used for matrix expansion, it works as expected usually, but not when `matrix: include:` is used.

For example, this is a config that correctly gives a single build:

``` yaml
language: haxe
haxe:
  - development
```

Problematic config with `matrix: include:`:

``` yaml
language: haxe
haxe:
  - development

matrix:
  include:
    - hxml:
      - build-neko.hxml
    - hxml:
      - build-macro.hxml
```

I would expect there will be 2 builds:
- haxe: development, hxml: build-neko.hxml
- haxe: development, hxml: build-macro.hxml

But, there are 3 builds:
- haxe: development
- haxe: [development], hxml: build-neko.hxml
- haxe: [development], hxml: build-macro.hxml

Notice that the 2nd and 3rd builds will fail because `haxe:` becomes an array (`["development"]`) instead of a single value `"development"`.

**Comment by joshk** [comment]
Technically this is correct.

`matrix.include` adds to any matrix created, it does not override it.

As for haxe being an array, that is strange, can you point to your build on Travis so we can look into this a bit further?

**Comment by andyli** [comment]
I think it is arguable.
If no haxe version is specified, i.e.
```yaml
language: haxe
matrix:
  include:
    - hxml:
        - build-neko.hxml
    - hxml:
        - build-macro.hxml
```
There will be only 2 builds. (example: https://travis-ci.org/andyli/hxparse/builds/57907781)

However, once a version is specified in the `haxe:` key, i.e. 
```yaml
language: haxe
haxe: development
matrix:
  include:
    - hxml:
        - build-neko.hxml
    - hxml:
        - build-macro.hxml
```
There will be 3 builds! (example: https://travis-ci.org/andyli/hxparse/builds/57907992)

Just specifying the version changes the number of builds doesn't sound right to me.

As for haxe being an array, the build is at:
https://travis-ci.org/Simn/hxparse/builds/57768881
