### ISSUE TITLE
Allow os in matrix include entries

### ISSUE THREAD

**Issue by gnzlbg** [travis-ci/travis-ci#3653]
I would like to select the os per matrix entry: 

```yaml
matrix:
  include:
    - env: CLANG_VERSION=3.5 BUILD_TYPE=Debug CPP=11 ASAN=On LIBCXX=On
      os: linux   # This is currently not possible
      addons: &clang35
        apt:
          packages: clang-3.5
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5
```
