### ISSUE TITLE
No way to set alternatives in containerized build

### ISSUE THREAD

**Issue by adamretter** [travis-ci/travis-ci#3668]
We are trying to move to a containerized build and are using the apt package plugin to install GCC 4.9, e.g.

```
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.9
            - g++-4.9
            - zlib1g-dev
            - libbz2-dev
``

That works well, we have no way subsequently to update the alternatives to set gcc and g++ to be the 4.9 version.

In a non-containerized build we would run:

```
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 50
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50
```

How can we update-alternatives in a containerized build please?

**Comment by adamretter** [comment]
Perhaps it would be neat if it was possible to set alternatives from the apt plugin, if that is the correct place? Perhaps by specifying something like this in the YAML:

```
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.9
            - g++-4.9
            - zlib1g-dev
            - libbz2-dev
        alternatives:
            - alternative:
                name: gcc
                link: /usr/bin/gcc
                path: /usr/bin/gcc-4.9
                priority: 50
            - alternative:
                name: g++
                link: /usr/bin/g++
                path: /usr/bin/g++-4.9
                priority: 50
```

**Comment by meatballhat** [comment]
@adamretter This seems doable to me :smiley:  My big concern is how do we sanitize the inputs to prevent security holes?  Are there any potential security holes?

**Comment by lasconic** [comment]
I was really eager to move to the container based infrastructure so I worked around this issue with the following, but I would welcome a proper solution!
```
export CC=/usr/bin/gcc-4.9
export CXX=/usr/bin/g++-4.9
```

**Comment by adamretter** [comment]
@lasconic I also tried something similar here - https://github.com/adamretter/rocksdb/blob/container-vm/Makefile#L20 however my Makefile does not seem to honour it. I am afraid I am not a make expert and normally focus on the Java side of our project.

**Comment by adamretter** [comment]
@meatballhat I am not entirely clear of the security issues. Perhaps we need a whitelist of alternatives, which has to be linked to the fact that the related package is also specified in the packages section. I guess you need to check the link and path are indeed just paths too.

**Comment by grooverdan** [comment]
I don't think there are any security implication of update-alternatives going by the suid/network listening(?)/data ex-filtration risk list in the apt-package-whitelist readme. Alternatives impose symlinks and the right time in packaging processes. Its always the destination file that is where any permissions is picked up. Some suid like sudo and some others ensure they have a full path there too. You could do a check that the destination doesn't end up being a suid or somewhere in /home/travis, but overall I can't think of a way to exploit this (which of course don't mean there isn't one). 

A security scenario would probably look like: An attacker socially engineers a developer to use alternatives in a very specific way (that would look quite suspicious) to make them somehow loose the confidentiality of their code. Doesn't sound that plausible to me.

**Comment by SethTisue** [comment]
this can probably be worked around in most cases (I was able to work around it in my own build), but it would certainly be nice to have.

**Comment by kamalmarhubi** [comment]
This would be an awesome addition to the container infrastructure!

**Comment by adamretter** [comment]
@meatballhat @grooverdan @kamalmarhubi Any update on this please?

**Comment by joshk** [comment]
Sorry, we have no updates on this yet.

**Comment by joshk** [comment]
We will look into it soon, for now I would recommend staying on the legacy stack.

**Comment by wbraswell** [comment]
I was just about to upgrade to the new Docker stack and was on the last line of converting my .travis.yml file, then I realized I need update-alternatives to work!  I will be very happy to upgrade as soon as this issue is resolved.

**Comment by NatalieWolfe** [comment]
Rather than expose `update-alternative` directly, why not do something like you did for Node projects? For those you can specify one or more versions of node to test against, that'd be great with GCC and Clang too.

Something like:
```yml
language: c++
compiler:
  - gcc # This would remain the same as the current meaning for backwards compatibility.
  - gcc-stable # Whatever the highest stable version of GCC is.
  - gcc-4.9
  - gcc-5
```
