### ISSUE TITLE
Issues using matrix.include

### ISSUE THREAD

**Issue by cancan101** [travis-ci/travis-ci#3674]
I am trying to use the following travis.yml file:

``` yml
sudo: false
language: python
python:
 - '2.7'
matrix:
  include:
   - env: SERVICE=s1
   - env: SERVICE=s2
     addons:
       apt:
         packages:
          - pkg-X
```

but this is resulting in two issues:
1) An extra build with no `SERVICE` set.
![image](https://cloud.githubusercontent.com/assets/51059/7161345/a754fe20-e35c-11e4-8178-1eb6011bd11a.png)

2) This:

```
$ source ~/virtualenv/python["2.7"]/bin/activate
/home/travis/build.sh: line 41: /home/travis/virtualenv/python[2.7]/bin/activate: No such file or directory
```

**Comment by cancan101** [comment]
If I change the yaml file to this, I still get issue 2:
```yml
sudo: false
language: python
python:
 - '2.7'
env:
 - SERVICE=s1
matrix:
  include:
   - env: SERVICE=s2
     addons:
       apt:
         packages:
          - pkg-X
```
```
$ source ~/virtualenv/python["2.7"]/bin/activate
/home/travis/build.sh: line 41: /home/travis/virtualenv/python[2.7]/bin/activate: No such file or directory
```
