### ISSUE TITLE
whitelist clang-XX

### ISSUE THREAD

**Issue by gnzlbg** [travis-ci/travis-ci#3688]
All my builds are broken with:

```bash
Installing APT Packages (BETA)
Disallowing packages: clang-3.5 valgrind
If you require these packages, please review the package approval process at: https://github.com/travis-ci/apt-package-whitelist#package-approval-process
```

valgrind seems to work but it seems that all `clang-X` packages are not whitelisted anymore even tho they are listed here: https://github.com/travis-ci/apt-package-whitelist/blob/820e07ef7c750a7820658917fb4ae9c26e682dc1/ubuntu-precise#L126

**Comment by meatballhat** [comment]
@gnzlbg This is very odd.  Are you still experiencing the `Disallowing packages` error message?

**Comment by gnzlbg** [comment]
@meatballhat yes, i'm still experiencing this issue: https://travis-ci.org/gnzlbg/range-v3/jobs/59223915#L102

**Comment by meatballhat** [comment]
I think this is because the packages are being interpreted as a single string: https://github.com/gnzlbg/range-v3/blob/1094fb8d27b40d19150861ae89c271842f97ca94/.travis.yml#L37.  I think it's reasonable to modify the addon to whitespace split each array entry so that this will work.

**Comment by meatballhat** [comment]
@gnzlbg Have you tried making that single line into an array? e.g.:

``` yaml
        apt:
          packages:
            - clang-3.5
            - valgrind
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5
```
