### ISSUE TITLE
[npm deploy] Deploy seems to work but npm install fails with 404

### ISSUE THREAD

**Issue by vwochnik** [travis-ci/travis-ci#3698]
In one of my projects I use Travis-CI to deploy to the NPM registry which seems to work fine. The registry is showing the newer version that Travis just deployed. However, when I try to `npm install` my package, the installer gives me a `404` for the `*.tgz` file in the registry which supposedly has just been deployed.

Here is my `.travis.yml`

```
sudo: false
language: node_js
node_js:
- '0.8'
- iojs
git:
  depth: 10
before_install:
- '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm install -g npm@1.4.28'
- npm install -g npm@latest
- npm install -g grunt-cli
deploy:
  provider: npm
  email: v.wochnik@gmail.com
  api_key:
    secure: Cb7mBQ99gKipP8GlVKEgO0KUAhm3NqQ40PKSg4E3SZ+XsqR9hp0vBSu6c8I0mkf5fSwSAUzkcl81Jht2YPhE4YrKoc8cwHT04NWNDQu/HmWD661sH9/5W2k9iB0ALRGOhV+vb3qmS/Na1INci0OJowrhHaULhNDZ5Tgp2Wr8rtI=
```

Another thing that dazzles me is that in both of my logs (`0.8` and `iojs`) the deployment is `Already up to date.` but the version in the `npm` registry changed.

Here is the deployment part of tye log of one of my builds:

```
Installing deploy dependencies
Preparing deploy
Authenticated with email v.wochnik@gmail.com
Saved working directory and index state WIP on (no branch): c92c21f retry publishing
HEAD is now at c92c21f retry publishing
Deploying application
-npm ERR! publish Failed PUT 403
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "node" "/home/travis/.nvm/v0.8.28/bin/npm" "publish"
npm ERR! node v0.8.28
npm ERR! npm  v2.8.3
npm ERR! code E403
npm ERR! "You cannot publish over the previously published version 0.3.1." : assemble-plugin-index
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/vwochnik/assemble-plugin-index/npm-debug.log
Already up-to-date!
# HEAD detached at c92c21f
nothing to commit, working directory clean
Dropped refs/stash@{0} (e21de84ff2ba4a267859f79c78ea061ed917e937)
```

The deployment *seemed* to have failed. However, why is then the version in the `npm` registry incremented?

Further, why does Travis attempt to deploy twice? I know I've specified two build processes but the deployment should only be attempted once.
