### ISSUE TITLE
`matrix: include:` should ignore `os: osx` if multi-os is not enabled

### ISSUE THREAD

**Issue by andyli** [travis-ci/travis-ci#3715]
We're trying to `matrix: include:` to manually expands the matrix, such that we can specify different apt packages to different builds (it is the approach discussed in #3505).

We have multi-os enabled, so we have to specify two sets, like this:
```yaml
matrix:
  include:
    #########
    # linux #
    #########
    - os: linux
      env: TEST=js
      addons: {apt: {packages: *apt_common}, sauce_connect: true}
    - os: linux
      env: TEST=php
      addons: {apt: {packages: *apt_php}}

    #######
    # osx #
    #######
    - os: osx
      env: TEST=js
    - os: osx
      env: TEST=php
```

It works on our repo. However, our forks do not have multi-os enabled, so all the builds will be run on Linux. ([example](https://travis-ci.org/andyli/haxe/builds/59212681))
My suggestion is to automatically exclude the builds that are `os: osx` if multi-os is disabled.
