### ISSUE TITLE
APT source whitelist request for rstudio R packages

### ISSUE THREAD

**Issue by jimhester** [travis-ci/travis-ci#3729]
`deb http://cran.rstudio.com/bin/linux/ubuntu trusty`

`deb http://cran.rstudio.com/bin/linux/ubuntu precise`

This should allow installation of the debian r binary packages using the [apt packaes addon](http://docs.travis-ci.com/user/apt/). i.e. 

```yaml
# (assuming an alias of r-packages)
addons:
  apt:
    sources:
    - r-packages
```
This should get us closer to not needing `sudo: required` for R builds.

Ideally this source could be added by default to the R build script so you wouldn't have to specify the above.

cc @craigcitro, @eddelbuettel and @hadley
