### ISSUE TITLE
gcc-5 fails to install

### ISSUE THREAD

**Issue by gnzlbg** [travis-ci/travis-ci#3736]
I'm trying to install `gcc-5.0` as follows:

```yaml
    - env: GCC_VERSION=5 BUILD_TYPE=Debug CPP=11 ASAN=Off LIBCXX=Off
      os: linux
      addons: &gcc5
        apt:
          packages:
            - g++-5 # I've also tried with gcc-5 here without any luck
            - valgrind
          sources:
            - ubuntu-toolchain-r-test
```

but it fails to install with the following error:

```bash
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 g++-5:i386 : Depends: gcc-5:i386 (= 5-20150401-0ubuntu12~12.04) but it is not going to be installed
              Depends: libstdc++-5-dev:i386 (= 5-20150401-0ubuntu12~12.04) but it is not going to be installed
              Depends: libc6:i386 (>= 2.11) but it is not going to be installed
              Depends: libgmp10:i386 but it is not going to be installed
              Depends: libisl10:i386 (>= 0.12.1) but it is not going to be installed
              Depends: libmpc2:i386 but it is not going to be installed
              Depends: libmpfr4:i386 (>= 3.1.0) but it is not going to be installed
              Depends: zlib1g:i386 (>= 1:1.1.4) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

see here: https://travis-ci.org/gnzlbg/range-v3/jobs/59517480#L100

Any idea what is wrong or how to fix this?
