### ISSUE TITLE
Build not working with build-tools-22.0.1

### ISSUE THREAD

**Issue by ppamorim** [travis-ci/travis-ci#3808]
Return:

    Could not find com.android.support:recyclerview-v7:22.1.0.

https://travis-ci.org/ppamorim/RecyclerRenderers/builds/60551738

**Comment by BanzaiMan** [comment]
What Android component has this?

**Comment by danielpassos** [comment]
@ppamorim Yes, it works. But you need to add the _extra_ in you `travis.yml`

```yml
language: android

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-m2repository
```
