### ISSUE TITLE
Change `java` version for a Node.js app

### ISSUE THREAD

**Issue by clns** [travis-ci/travis-ci#3827]
I have a basic Node.js app that requires the `java` 8 command to be available when running the tests. I can't seem to change to Java 8 from the default Java 7. I also tried setting `JAVA_HOME` in `env:` without any success. The `java -version` command always outputs **java version "1.7.0_76"**.

This is the test `.travis.yml` file which runs `java -version`:

```yml
language: node_js
node_js:
  - "0.12"

before_script:
  - echo $JAVA_HOME
  - java -version
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle

script:
  - java -version
```

And this is the build log from Travis:

![image](https://cloud.githubusercontent.com/assets/687922/7429768/6e79261a-f010-11e4-93fb-d519c9b5a040.png)

**Comment by BanzaiMan** [comment]
At this time, `language` value dictates which image is used. Node.js image does not have various JDKs, while the Java image has `nvm` to manage Node.js runtimes.

So, in your situation, you should choose `language: java` and switch Node.js yourself.

```yaml
language: java

env:
  - NODE_VERSION=0.12

script:
  - nvm use $NODE_VERSION
```

**Comment by clns** [comment]
Cool, thanks. I ended up using this `.travis.yml` file:

```yml
language: java

jdk:
  - oraclejdk8

env:
  - NODE_VERSION=0.12

install:
  - nvm install $NODE_VERSION
  - npm install

script:
  - nvm use $NODE_VERSION
  - npm test
```

**Comment by vectart** [comment]
It's better to keep using Node.js environment and update Java8
https://github.com/travis-ci/travis-ci/issues/5161#issuecomment-262857664

**Comment by dpwspoon** [comment]
@vectart, it didn't seem to work for me with the node_js image, https://github.com/k3po/npm-k3po/pull/1.  The two commits are pictured below (bottom failed for a test failure I now fixed).  The top failed with "Unsupported major.minor version" which is the indication the top was still on java 7 or 6 (not on 8)

![image](https://cloud.githubusercontent.com/assets/2014623/24770309/57afacee-1abe-11e7-9a17-3ed710c73caf.png)

**Comment by ddebrunner** [comment]
@vectart  I tried that trick but while it installs Java 8 as the default, it leaves `JAVA_HOME` as Java 7.

```
language: python
python: "3.5"
addons:
  apt:
    packages:
      - oracle-java8-set-default
```

results in

```
JAVA_HOME=/usr/lib/jvm/java-7-oracle
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```
