### ISSUE TITLE
Content shell tests fail to run with new Dart test package

### ISSUE THREAD

**Issue by danschultz** [travis-ci/travis-ci#3851]
When running tests using the new [test package](https://pub.dartlang.org/packages/test), Content Shell fails to start with the following error:

```
$ pub run test -p content-shell test
Failed to start content shell: Bad state: Stream has already been listened to..
```

Here's my `.travis.yml` file:

```yaml
language: dart
dart:
  - stable
  - dev
with_content_shell: true
script:
  - pub run test -p content-shell test
```

What's strange is that if I manually install Content Shell, it starts fine and my tests are run. This is the install section of my `.travis.yml` file that I use to install Content Shell:

```yaml
before_install:
  - sudo apt-get update --yes
install:
  - sudo sh -c "echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula
    select true | debconf-set-selections"
  - sudo apt-get install --yes ttf-indic-fonts ttf-mscorefonts-installer ttf-dejavu-core
    ttf-kochi-gothic ttf-kochi-mincho ttf-thai-tlwg
  - curl https://storage.googleapis.com/dart-archive/channels/stable/release/latest/dartium/content_shell-linux-x64-release.zip > content_shell.zip
  - unzip content_shell.zip -d .temp
  - mv .temp/drt-lucid64-full-stable* .temp/content_shell
  - export PATH="$PATH:$TRAVIS_BUILD_DIR/.temp/content_shell"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
```

/cc @a14n, @devoncarew and @sethladd
