### ISSUE TITLE
email notifications - obfuscated emails

### ISSUE THREAD

**Issue by paul-hammant** [travis-ci/travis-ci#3853]
Refer http://docs.travis-ci.com/user/notifications/#Email-notifications

Would be great to have obfuscated, hashed, or obscured references for emails held canonically in travis-ci.org

``` yaml
notifications:
  email:
    - one@example.com
    - #pauls_other_email_2
    - other@example.com
```

Why?  People don't want their email addresses exposed. They might have secret email addresses just for notifications.
