### ISSUE TITLE
Commit tagged, yet deploy doesn't detect tag

### ISSUE THREAD

**Issue by minedev** [travis-ci/travis-ci#3897]
I'd like to auto-deploy my builded .jar with travis. I followed the [tutorial](http://docs.travis-ci.com/user/deployment/releases/) and tagged my [commit](https://github.com/minedev/MooseMachine/releases/tag/v0.1a). It shows as tagged on GitHub, yet when reading the [travis build log](https://travis-ci.org/minedev/MooseMachine/builds/62002625), the tag seems to not be detected. 

My [`.travis.yml`](https://github.com/minedev/MooseMachine/blob/master/.travis.yml) can be trimmed to this: 
```yml
language: java

branches:
  only:
  - master

deploy:
  provider: releases
  api_key:
    secure: [key]
  file_glob: true
  file: "${RELEASE_JAR_FILE}"
  skip_cleanup: true
  on:
    repo: minedev/MooseMachine
    tags: true
    all_branches: true
```

*Additional information:* I had quite some trouble with building on a more recent Java version as you may see. I'm looking forward to the update next month, when Java 8.0_40 might be included, for now I had to use linuxbrew.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/minedev/MooseMachine/builds/62002625 is a build on the master branch. Tag a commit, and push the tag, please.

**Comment by BanzaiMan** [comment]
Ah. The tag was pushed, but you are building the `master` branch only. https://github.com/minedev/MooseMachine/blob/d7e5ccbe748fcbe6104428e8b2a5193e5ff54811/.travis.yml#L3-L5

**Comment by BanzaiMan** [comment]
See https://travis-ci.org/minedev/MooseMachine/requests

**Comment by minedev** [comment]
Yeah, I was confused what you mean by tagging, as the commit was tagged. Is this the only way to fix this? Because I don't need the other branches to be built.

**Comment by BanzaiMan** [comment]
Tags you give are considered a branch name for the purpose of building on Travis, so if you want to build tags, you'll need to change the `branches.only` value. If you know the tag names in advance, you can say something like:

```yaml
branches:
  only:
    - master
    - /v\d+\.\d+[a-z]/
```
