### ISSUE TITLE
Update pip version

### ISSUE THREAD

**Issue by drgarcia1986** [travis-ci/travis-ci#3968]
Currently travis is using version 6.0 of pip but version 7.0 is available.
https://travis-ci.org/drgarcia1986/simple-settings/jobs/64186797#L94

I belive it's a important update for python environment
This [article](https://lincolnloop.com/blog/fast-immutable-python-deployments/) is a great overview about that.

**Comment by BanzaiMan** [comment]
Thanks for opening the ticket. `pip` will be updated to the most recent version when the next build environment image is provisioned.

**Comment by drgarcia1986** [comment]
:+1:

**Comment by ad-m** [comment]
I would like leave workoaround here only.

Put in ```.travis.yml``` eg.:
```yaml
install:
  - pip install -U pip wheel
  - pip install tox
script:
  - tox -e $TOX_ENV
```
