### ISSUE TITLE
How to deploy an .gitignore public folder generated by gulp

### ISSUE THREAD

**Issue by lovedota** [travis-ci/travis-ci#4006]
```
language: node_js
cache:
  directories:
  - node_modules
  - bower_components
node_js:
  - "0.12"
before_script:
  - bower install
script:
 - npm test
before_deploy:
  - gulp
deploy:
  provider: heroku
```
- .gitignore
```
public
````

- The **public** folder will be generated by **gulp**, but it is not deployed to heroku because it is not a part of git repository. Thanks !

**Comment by BanzaiMan** [comment]
http://docs.travis-ci.com/user/deployment/heroku/#Deploying-build-artifacts

Please add `skip_cleanup: true` and try again.

**Comment by BanzaiMan** [comment]
Have you tried it?

**Comment by lovedota** [comment]
@BanzaiMan 
It does not work.
First if i don't use ```skip_cleanup: true```, it will fire an error *The generated files need to be git add to repository*
Second If i use this ```skip_cleanup: true```, it does not fire any errors, but in heroku app these generated files don't exist.

**Comment by carbonrobot** [comment]
I am having the same issue. Gulp builds my content into a folder that is ignored in .gitignore.

**Comment by BanzaiMan** [comment]
Sorry about the delay here. I guess I misunderstood the issue.

One thing I'm curious about is: How do you do it from your machine? Perhaps you can remove `.gitignore` before deploying the app to Heroku.

**Comment by carbonrobot** [comment]
I deploy to azure and not Heroku for my project. Either way this is pretty standard for continuous integration. The CI server builds the artifacts from source code and deploys them to the server. You would not check /public into your source files because it is a generated folder, same as node_modules and bower_components.

**Comment by BanzaiMan** [comment]
@carbonrobot Currently, the only way to deploy an application to Azure is via `git`. If one is to deploy files through it, they have to be visible to `git`. (You might be able to work with this restriction by modifying `.gitignore` before deployment, but I have not tested anything.)

@felixrieseberg Are there any other strategy available (and feasible) for Azure?

**Comment by felixrieseberg** [comment]
For Azure, `skip_cleanup` should work - we're still deploying via Git, but we're also quickly checking everything in right before pushing it to Azure (ignoring .gitignore).

If that fails, one could always deploy via script. Quick example: [Building a Jekyll page on Travis and deploying the `_site` output](https://github.com/felixrieseberg/travis-jekyll-git).

**Comment by carbonrobot** [comment]
To be honest, it has been so long since this bug is filed, I don't remember the specific issue this causes. I will have to look into the sites I have to see which one is affected.

**Comment by brianneisler** [comment]
This same issue seems to affect the npm deploy as well. 

I have a 'dist' folder that is built by gulp. I had this folder listed in my .gitignore. When deploying using npm the folder wasn't included. If I remove my 'dist' folder from .gitignore then the npm deploy will include the 'dist' folder.  

Here is my .travis.yml
```
language: node_js
node_js:
  - '5.3'

cache:
  directories:
    - node_modules
    - $HOME/.npm
    - $HOME/.gem

before_install:
  - npm install -g gulp

script:
  - gulp test

notifications:
  slack: "slack key"

before_deploy:
  - gulp

deploy:
  provider: npm
  email: "my npm email"
  skip_cleanup: true
  api_key:
    secure: "my npm auth key"
  on:
    tags: true
```

Seems like this might be a broader issue affecting more than the heroku deploy.
