### ISSUE TITLE
Custom release github

### ISSUE THREAD

**Issue by Yimiprod** [travis-ci/travis-ci#4023]
I want to release a node-webkit project in continuous integration with travis, at the moment it work well. The release on github is done after merging a pr on master. The app is build then sent to release.

But now we need to use some C++ lib in it, requiring to build each files in specific environment, one for each os we wan't a release (atm osx and win).

I know i can set multiple languages environment, but i don't know how i can set the tag in that process then push the file for each environment.

Here's my current .travis.yml

```
language: objective-c
node_js:
  - '0.12.1'
before_install:
  - npm install -g npm
  - npm install -g grunt-cli grunt bower
install:
  - npm install
script:
  - npm test
before_deploy:
  - brew update
  - brew install jq
  - grunt release
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG='v'`cat package.json | jq -r '.version'`
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$OAUTH_TOKEN@github.com/myrepo/myproject --tags
deploy:
  provider: releases
  skip_cleanup: true
  api-key: $OAUTH_TOKEN
  file: release/*.zip
  file_glob: true
  on:
    tags: false
    branch: master
branches:
  only:
    - master
    - release-nodewebkit
```
