### ISSUE TITLE
Swift support for Linux

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#4053]
Apple announced Swift support on Linux on 2015-06-08.

**Comment by BanzaiMan** [comment]
Currently, in order to compile Swift applications, one must fake it with `language: objective-c`. With the announced support of Swift on Linux, it is reasonable to have `language: swift` with appropriate stages.

**Comment by BanzaiMan** [comment]
The initial setup would be to send all `swift` jobs to the Mac queue. When the Linux compiler is released and the image is ready, we can enable it via the Multi-OS feature.

**Comment by BanzaiMan** [comment]
Swift 2.2 snapshot is available now for Trusty. https://swift.org/download/ The link itself seems a little too slow (if it works at all) at the moment.

**Comment by kylef** [comment]
Just want to mention, I managed to get Swift running on Linux using the new "trusty" distribution, you can find the .travis file at https://github.com/kylef/Currasow/blob/master/.travis.yml:

```yaml
language: generic
sudo: required
dist: trusty
env:
- SWIFT_VERSION=swift-2.2-SNAPSHOT-2015-12-01-b
install:
- mkdir swift
- curl https://swift.org/builds/ubuntu1404/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu14.04.tar.gz -s | tar xz -C swift &> /dev/null
script:
- env PATH=$(pwd)/swift/$SWIFT_VERSION-ubuntu14.04/usr/bin:$PATH swift build
```
