### ISSUE TITLE
Support settings multiple languges in one travis ci file

### ISSUE THREAD

**Issue by paladox** [travis-ci/travis-ci#4090]
Hi please support setting multiple languges in one travis ci file please.

for example like

language: php, ruby, java, js

or 

language: php ruby java js

**Comment by joshk** [comment]
Thanks for the issue.

Can you please explain the use case and how the install steps might work?

**Comment by paladox** [comment]
Use can be if you have one project that has mutple files for different programming langugages like for example having php and js then you want to be able to test both js and php not just one or the other.

It could go like for example

language: php, js

or can go like

language: php js

**Comment by joshk** [comment]
Do you have an open source which is a good example of this?

**Comment by paladox** [comment]
Yes here https://github.com/paladox/Metrolook

**Comment by paladox** [comment]
I haven't got an open source for this since it woulden work.

**Comment by BanzaiMan** [comment]
@paladox Is there a repo that you would like to use this sort of behavior on, or is it just an idea?

**Comment by tecoholic** [comment]
I have a project which uses Python flask for backend and AngularJS for frontend. I have tests for both the language files. I currently have set up npm to run JS tests. Now I would like to add Python nosetests as well. I think this should be a good example. project is at https://github.com/GluuFederation/gluu-webui

**Comment by BanzaiMan** [comment]
@tecoholic I suggest using `language: python` in that case, as you have access to both Python and Node.js runtime (via nvm).

**Comment by tecoholic** [comment]
@BanzaiMan Thanks for the tip. I never knew you could straight away call nvm. Saw some places where people have installed nodejs from scratch. nvm was simple.

**Comment by vielmetti** [comment]
I'm working on a project that depends on both `python` and `go`, though it's mostly written in `go`, but has some vendor dependencies that are in `python` that need to be tested and installed with `pip`. I'd also like to test on `linux` and `osx`, and if all of *that* works, then I'd like to iterate through various versions of python, go, and the vendor dependency.

Needless to say this looks like a messy matrix, and any suggestions or examples would be welcomed.

**Comment by elopio** [comment]
I want to upstream my go version of the subunit library ( https://github.com/elopio/go-subunit ). I have in that project a travis file that runs the go tests.
They already have a travis that runs the python tests ( https://github.com/testing-cabal/subunit ).
So, I have no idea how to combine the two travis files. It would be great to have support for two language tags. I will put my library in a subfolder of the upstream project, so it would also be cool if I could just move my .travis.yml file to the subfolder and the system could find it and run the tests.

**Comment by rw** [comment]
The FlatBuffers project (https://github.com/google/flatbuffers) uses many languages. The compiler is built in C++, and we have runtime code for the following languages: C++, C#, Go, Java, Javascript, and Python, Javascript.

Has there been any progress on this issue?

**Comment by kkaefer** [comment]
We are also having the same issue with https://github.com/mapbox/mapbox-gl-native. Our project is fundamentally implemented in C++, but we are building and testing on a variety of platforms, including Android, plain Linux, Node.js bindings etc. We've selected "Android" as the base image, since it contains the Android NDK; but selecting that affects other parts of the system, like caching ([only one global cache](https://github.com/travis-ci/travis-ci/issues/4393), which doesn't help us much since our build artifacts are vastly varying).

**Comment by evilaliv3** [comment]
:+1: 

[GlobaLeaks](https://github.com/globaleaks/GlobaLeaks) is an other example of this.

GlobaLeaks is a framework composed by a python web backend that servers a javascript client

The language used on travis for what relates to the testing is should so be python(2.7) and node_js (4.2); thos are the two main requirements imposed by the testing frameworks.

The missing possibility for specifying multiple languages and their respective version is causing that we need to use python(2.7) in the language directive and then install node.js with sudo that makes not possible to use the new container.

**Comment by igormukhingmailcom** [comment]
+1
Another example:
Ansible role (needs `python` to install `ansible` via `pip`) that installs some `php` project using `composer` and depending from `doctrine 2.5`. As far as doctrine 2.5 depending from php 5.4 but travis by default have php 5.3 - build fails all the time.

So we need ability to specify both `python 2.7` to install `ansible` and `php 5.4` to install `doctrine 2.5` via `composer`. 

Playing around this and trying to solve problem hadn't succeeded...

**Comment by externl** [comment]
Same here, building and testing [Ice](https://github.com/zeroc-ice/ice) requires C++, Python, Java, Ruby, PHP, and Node.js. Would be great if we could specify various versions of each language.

I tried to do this manually using the various version managers (nvm, phpenv, etc.) but they're not all available at the same time.

**Comment by kengz** [comment]
Tinkered a bit and worked out the below solution using the Travis [Ubuntu 14.04 Trusty beta](https://blog.travis-ci.com/2015-10-14-opening-up-ubuntu-trusty-beta) and `sudo`. Putting it out there if anyone needs it. 

This pretty much let you setup a VM where you can install anything; I have `node_js` and `python3, pip3`, which are not available on the default container-based VMs.

```yml
sudo: required
dist: trusty
language: node_js
node_js:
  - "5.5"
  - "4.2"
python:
  - "3.4"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # nodejs >v4 compiler requirements
      - g++-4.8
      - openjdk-7-jdk
before_install:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrapper
  - python3 -V
  - pip3 -V
  # install Neo4j locally:
  - wget dist.neo4j.org/neo4j-community-2.3.2-unix.tar.gz
  - tar -xzf neo4j-community-2.3.2-unix.tar.gz
  - sed -i.bak s/dbms.security.auth_enabled=true/dbms.security.auth_enabled=false/g neo4j-community-2.3.2/conf/neo4j-server.properties
  - neo4j-community-2.3.2/bin/neo4j start
install:
  - npm install
  - sudo pip3 install -r requirements.txt
env:
  global:
    - CXX=g++-4.8
    - NODE_ENV=development
```
