### ISSUE TITLE
Unable to deploy releases on github

### ISSUE THREAD

**Issue by asamgir** [travis-ci/travis-ci#4093]
I am trying to deploy releases on github using bellow travis script 

```yaml
language: java
node_js:
  - "0.10"

before_script:
  - cd www
  - npm install -g bower
  - npm install
  - bower install -f
  - cd ..

script: gradle build

notifications:
  email:
    recipients:
      - xxxx@gmail.com
    on_success: always
    on_failure: always


branches:
  only:
    - <branch name>
before_deploy:
  - export RELEASE_FILE=$(ls build/libs/*.war)
  - echo "Deploying $RELEASE_FILE to GitHub"
  
deploy:
  provider: releases
  
  api_key:
    secure: xxx
  file:
    - "${RELEASE_FILE}"
  
  skip_cleanup: true
  
  on:
    repo: <user/repo>
    tags: true
    all_branches: true
```

Facing some issues,

1. When I do a tagged commit, travis throws the error "Skipping a deployment with the releases provider because this is not a tagged commit" 
git commands

  1.git tag -a "<tag>" -m "<message>"
  2.git push --tag

  Or if using older tag
      git push --tags

2. If i remove "tags=true" the deploy script run for every commit and throws 401 - Bad credentials 

I have provide access_key which is generated by travis client 
using following command
travis encrypt "GITHUB PASSWORD"

Also tried with  Username and Password.
I have referred http://docs.travis-ci.com/user/deployment/releases/

Please let me know if I am missing something.
