### ISSUE TITLE
Notifications: Allow multiple notification configurations of the same type

### ISSUE THREAD

**Issue by kennethgunn** [travis-ci/travis-ci#4106]
My team uses Travis for builds and Slack for team communication. Currently, we have a channel that shows notifications for all Travis build successes and failures. It works great, but it's not something everyone keeps an eye on all the time.

We also have a team discussion channel that everyone has open all the time.

Desired: In addition, I would like to have Travis report failures only to the team discussion channel, since they are calls to action that shouldn't be frequent enough to flood the channel into uselessness.

Observed: I can configure two Slack channels to receive notifications, but they can only have one set of configuration parameters (e.g., on_success). And the file format doesn't allow me to add two slack sections to the notifications. (I assume it's because that's bad YAML, and definitely doesn't pass https://lint.travis-ci.org .)

**Comment by BanzaiMan** [comment]
Could you show the current notification configuration?

**Comment by kennethgunn** [comment]
The existing notification configuration looks like this:
```
notifications:
  slack:
    rooms:
    - company:build-status-channel-token
    on_success: always
    on_failure: always
    on_start: never
```

I would like to have a second configuration that looks like this:
```
  slack:
    rooms:
    - company:team-discussion-channel-token
    on_success: never
    on_failure: always
    on_start: never
```

**Comment by kennethgunn** [comment]
I am no YAML master, but I think what I want would be isomorphic to this:

```
notifications:
  - slack:
      rooms:
      - company:build-status-channel-token
      on_success: always
      on_failure: always
      on_start: never
  - slack:
      rooms:
      - company:team-discussion-channel-token
      on_success: never
      on_failure: always
      on_start: never
```

**Comment by joshk** [comment]
Thanks for the suggestion, we will look into fitting this into an upcoming improvement for our notification logic.

**Comment by duane-unitive** [comment]
:+1: 

We too use slack for notifications. In addition to different rooms we would like to have different message formats. For example including @channel in the message for a failure to ensure that everyone is notified in slack. 

I believe the proposal from @kennethgunn to add multiple notification names would also allow multiple messages formats.

**Comment by antonsi** [comment]
:+1: for feature request, I would like to see this feature soon.
Currently it's a bit confusing that I can't setup separate configurations. Or at least I don't know how..

**Comment by frankscholten** [comment]
This issue has been updated a while ago. Is it already possible to add notifications to multiple Slack channels?

**Comment by tsamsonbm** [comment]
Any updates on this feature? Would be extremely useful...

**Comment by rts-cwalker** [comment]
Being able to send notifications to different channels based on branch would be useful too. We would like to use `#dev-deploy`, `#stg-deploy`, and `#prod-deploy` channels to track the different environments instead of all of them going to the same channel. So possibly using something similar to the `on:` key from other stages in .travis.yml.

**Comment by mansona** [comment]
@rts-cwalker you could probably do this using stages and jobs 👍

**Comment by proinsias** [comment]
AFAIK, this is still an unresolved issue.

**Comment by erezak** [comment]
@kennethgunn I prefer the following syntax:

`
notifications:
  - slack:
      rooms:
      - company:build-status-channel-token
        on_success: always
        on_failure: always
        on_start: never
      - company:team-discussion-channel-token
        on_success: never
        on_failure: always
        on_start: never
`

What do you think?

**Comment by rmzelle** [comment]
Per #5121, I have the same request for webhook notifications. Similar to @erezak, I was thinking of a YAML structure like:

```yaml
notifications: 
  webhooks: 
    - url: "https://example.com:8826/"
      on_success: always
    - url: "https://example.com:8827/"
      on_success: change
```
