### ISSUE TITLE
If a deployment provider has incorrect encrypted key within it, the entire content of .travis.yml is basically ignored

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#4132]
To reproduce:

``` yaml
rvm:
  - 2.1.6
deploy:
  provider: s3
  api_key:
    secure: FOOBAR
```

This should run with Ruby 2.1.6, but the build will run on default. In fact, all other contents of `.travis.yml` (such as services and PostgreSQL versions, if they are present) are completely ignored.
