### ISSUE TITLE
APT plugin to support shell variables

### ISSUE THREAD

**Issue by phadej** [travis-ci/travis-ci#4173]
I'd like to have:
```yaml
env:
  - GHCVER=7.8.4
  - GHCVER=7.10.1
  - GHCVER=head

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-$GHCVER
```

---

Additionally it would be nice, if one could specify precisely the version of deb-package (using shell variable as well!)
Currently I have to install all packages, which is quite wasteful (luckily they can co-exist).
