### ISSUE TITLE
Allow arrays of exclude

### ISSUE THREAD

**Issue by dblock** [travis-ci/travis-ci#4174]
I would like to test everything for the LATEST of something and only one Ruby version for everything else. This could dry this .travis.yml up quite a bit:

```
language: ruby

cache: bundler

rvm:
  - 2.2
  - 2.1.2
  - 1.9.3
  - rbx-2.2.10
  - jruby-19mode
  - ruby-head
  - jruby-head

matrix:
  exclude:
    - rvm: 1.9.3
      env: RSPEC_VERSION=3.1.0
    - rvm: 1.9.3
      env: RSPEC_VERSION=3.2.0
    - rvm: 2.1.2
      env: RSPEC_VERSION=3.1.0
    - rvm: 2.1.2
      env: RSPEC_VERSION=3.2.0
    - rvm: rbx-2.2.10
      env: RSPEC_VERSION=3.1.0
    - rvm: rbx-2.2.10
      env: RSPEC_VERSION=3.2.0
    - rvm: jruby-19mode
      env: RSPEC_VERSION=3.1.0
    - rvm: jruby-19mode
      env: RSPEC_VERSION=3.2.0
    - rvm: ruby-head
      env: RSPEC_VERSION=3.1.0
    - rvm: ruby-head
      env: RSPEC_VERSION=3.2.0
    - rvm: jruby-head
      env: RSPEC_VERSION=3.1.0
    - rvm: jruby-head
      env: RSPEC_VERSION=3.2.0
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

env:
  - RSPEC_VERSION=3.1.0
  - RSPEC_VERSION=3.2.0
  - RSPEC_VERSION=LATEST
```

I'd like to be able to do:

```
matrix:
  exclude:
    - rvm: 
        - 1.9.3
        - 2.1.2
        - rbx-2.2.10
        - ruby-head
        - jruby-head
      env: 
        - RSPEC_VERSION=3.1.0
        - RSPEC_VERSION=3.2.0
```
