### ISSUE TITLE
Add Java 9 to the list of available JVM

### ISSUE THREAD

**Issue by xcoulon** [travis-ci/travis-ci#4178]
Even thought Java 9 is not final yet, it would be great if we could build and test projects on it, especially when those projects are libraries or frameworks.

**Comment by juherr** [comment]
:+1:

**Comment by BanzaiMan** [comment]
Until we update the build environment (not yet scheduled), you can do this manually.

I've enabled Oracle Java 9 (https://github.com/travis-ci/apt-package-whitelist/commit/d69505b65d0697c99869e1db77074ee8fbdcdfc9). You still need to set up your environment manually, but you can use it.

On containers:
```yaml
sudo: false

addons:
  apt:
    packages:
      - oracle-java9-installer

before_install:
  - remove_dir_from_path $JAVA_HOME/bin
  - export JAVA_HOME=/usr/lib/jvm/java-9-oracle
  - export PATH=$JAVA_HOME/bin:$PATH
  - java -version
```

On standard infrastructure:
```yaml
sudo: required

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install oracle-9-installer
  - remove_dir_from_path $JAVA_HOME/bin
  - export JAVA_HOME=/usr/lib/jvm/java-9-oracle
  - export PATH=$JAVA_HOME/bin:$PATH
  - java -version
```
