### ISSUE TITLE
add email/irc for 'allow_failure' matrix

### ISSUE THREAD

**Issue by mpapis** [travis-ci/travis-ci#418]
for TCS (issue #417) it would be good to have possibility to email/irc notify other developers when only the selected entry fails, this would help to test patches/fixes for rubies via all the tested projects.

Example:

```
  rvm:
    - 1.8.7
    - 1.9.3
    - tcs
  matrix:
    allow_failures:
      - rvm: tcs
        email: mpapis@gmail.com
```

The email should be sent only when tcs fails, not when other tests fail also. 

Initial idea: https://groups.google.com/forum/#!msg/thecodeshop/ErmvJiUfcXY/uj-mQFSfy_AJ
Discussion with @joshk: https://gist.github.com/53fcee446e431b731f66
