### ISSUE TITLE
deploy to npm results in 404

### ISSUE THREAD

**Issue by SpainTrain** [travis-ci/travis-ci#4206]
I am encountering an odd issue with npm deployment method on TravisCI.  Here is the output:

```
Deploying application
npm ERR! publish Failed PUT 500
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v0.12.6/bin/node" "/home/travis/.nvm/versions/node/v0.12.6/bin/npm" "publish"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code E500
npm ERR! unexpected status code: 404 : rest-buddy
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/home-buddy/rest-buddy/npm-debug.log
No stash found.
Done. Your build exited with 0.
```

Link: https://travis-ci.org/home-buddy/rest-buddy/jobs/70175907

These are the same credentials I use locally, and `npm publish` is successful locally (npm 2.12.1, node 0.12.6).  There are some references to strange 404's in issues on npm/npm, but they seem unrelated.

Here is the `.travis.yml`:

```yaml
language: node_js
node_js:
- '0.12'
- '0.10'
deploy:
  provider: npm
  email: mc.s.pain.how.er+npm@gmail.com
  api_key:
    secure: L/QS9TM0cxvJk7sDew/dANuAVTnrLmoLjf7tR92pmoDlE/pICzJ1asZtxjz8UezRInQHmXlRvTizlk2gGpmb6DYul7tv66w/k4/9OrUYMWGZ5wh+A78knGGreA3U9FQXuvyL+01aZi2uZxbJiZRhzfUfnvUawx5QmGhRDCmCeqM9vqicU83zMDlSHodV/gxg0b73bgHzoo0KzN5q56nvhBRgLku5ojB1PyUFrQV6q9IggThGAtNGUHfClPDY58KB/3WQHi6GmNVNKkvb7HNmncUPIYlJIVCXsTQ4nM1kIP8clO//9iK7DPekOJjv1zKoQZRQeJxqmmzSvhttr4Z3LkL1SyAKiPnOLfFb29Y4ybCXaHF6tQgftCFoKIFrS6C+YhbRZuxevTs1Ud7LuKgfqvEIbduARhwXmAVZu8XgkdMO0kz46R39PQ91lgL0ZK3s7xlK98N+5BjXsdtGocFirm3vA5fKdXGqHDbD7mmgceq8haAh8RIzerPeltkKu44LGumP6D44oJiqwC2BGRw1h8zFhYrZvpFctuTc3+gM3OoITUfyCPNluQr52Q4zpTe1J4pzVQhKYy1po2b6WklDmx8OGA2AkM/6AxNfeZXeMfb86eLdYLf08txU/d9q1rJrk+myRD7J3Gt+Lw5eJ7eOXoGj+77hg9BlKhoo7TiWhqw=
  on:
    node: '0.12'
    tags: true
    all_branches: true
    repo: home-buddy/rest-buddy

```
