### ISSUE TITLE
Why is my script erroring?

### ISSUE THREAD

**Issue by bucaran** [travis-ci/travis-ci#4290]
This is not the first time I had this happened to me. I experienced a similar problem before in a repo that was rebased several times. It seems travis was unable to fetch the latest changes. This time however there was no rebase involved.

[Erroring travis job](https://travis-ci.org/flyjs/fly/jobs/70489991)

Travis Script

```yml
language: node_js
node_js:
  - iojs
  - "0.12"
script: "npm test"
```
