### ISSUE TITLE
Build matrix and APT plugin integration

### ISSUE THREAD

**Issue by phadej** [travis-ci/travis-ci#4291]
As https://github.com/travis-ci/travis-ci/issues/4173 - *APT plugin to support shell variables* is not possible, could we have something like:

```yaml
env:
  - GHCVER=7.8.4
  - GHCVER=7.10.1
  - GHCVER=head

addons:
  apt:
    sources:
    - hvr-ghc

matrix:
  config:
    GHCVER=7.8.4:
      addons:
        apt:
          packages:
            ghc-7.8.4
    GHCVER=7.10.1:
      addons:
        apt:
          packages:
            ghc-7.10.1
    GHCVER=head:
      addons:
        apt:
          packages:
            ghc-head
```

So the final full config would be merged from top-level and sub-configs. This approach is generalisable to other configuration, but I'll be ok with other ways to solve this problem.

**Comment by couchand** [comment]
I would also like to see configurable support for package versions.  It would be ideal if we didn't have to muck about in the matrix directly, and instead just do something like:

    addons:
      apt:
        sources:
          - llvm-
            - 3.4
            - 3.5
            - 3.6

And the build matrix would be auto-populated by crossing these options with the other runtime/environment options.

**Comment by phadej** [comment]
@couchand The more general approach would be to implement https://github.com/travis-ci/travis-ci/issues/1519 to handle the verbosity. Yet that, and additional complexities (https://github.com/travis-ci/travis-ci/issues/1519#issuecomment-31658030) one can implement outside of travis, by writing special-purpose `.travis.yml` generator.

So ultimately this could be solved by overly-verbose many-in-one `.travis.yml`:
```yaml
multiplex:
- language: js
  node_js:
  - "0.12"
  before_install:
  - echo Testing JavaScript part of the project with node 0.12

- language: js
  node_js:
  - "0.10"
  before_install:
  - echo Testing JavaScript part of the project with node 0.10

- language: ruby
  before_install:
  - echo Testing Ruby part of the project
```
