### ISSUE TITLE
Cannot install gcc-*

### ISSUE THREAD

**Issue by asartori86** [travis-ci/travis-ci#4354]
Here is the code in my .travis.yml
```
addons:
  apt:
    packages:
      - gcc-4.9
```
 in the log I get
```
E: Unable to locate package gcc-4.9
E: Couldn't find any package by regex 'gcc-4.9'
```
I tried also for different versions but same story. What I am missing? I double checked in the whitelist and I can see gcc-4.9 gcc-4.8 etc

**Comment by BanzaiMan** [comment]
It probably means the sources that we have do not have this.

**Comment by asartori86** [comment]
it works only for `gcc` but I need a full c++11 support

**Comment by BanzaiMan** [comment]
Do you know what package provides that support?

**Comment by asartori86** [comment]
As far as I know from clang >= 3.3 and gcc >= 4.8

I can install `clang-3.4` but I got the same error with `clang-3.7`

**Comment by BanzaiMan** [comment]
You might have to add APT sources. See https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json and http://docs.travis-ci.com/user/apt/#Adding-APT-Sources.

**Comment by asartori86** [comment]
Thanks @BanzaiMan!

that solved my issue

```
addons:
  apt:
    sources: 
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - gfortran-4.8
      - libblas-dev
      - liblapack-dev
      - libopenmpi-dev
      - libboost-dev
```
it works
