### ISSUE TITLE
APT whitelist request for pwgen

### ISSUE THREAD

**Issue by fiedl** [travis-ci/travis-ci#4379]
We use `pwgen` to generate initial user passwords.

Please allow:

```yml
# .travis.yml
sudo: false
addons:
  apt:
    packages:
      - pwgen
```
