### ISSUE TITLE
APT addon can fail to install desired packages and bail

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#4389]
Given:

```yaml
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - debian-sid
      - kalakris-cmake
    packages:
      - build-essential
      - clang-3.6
      - clang-format-3.6
      - llvm-3.6
      - llvm-3.6-dev
      - cmake
```

`apt-get install` basically fails:

```
Preconfiguring packages ...
(Reading database ... 71420 files and directories currently installed.)
Preparing to replace locales 2.13+git20120306-3 (using .../locales_2.19-19_all.deb) ...
Unpacking replacement locales ...
dpkg: error processing /var/cache/apt/archives/locales_2.19-19_all.deb (--unpack):
 trying to overwrite '/usr/sbin/validlocale', which is also in package libc-bin 2.15-0ubuntu10.10
Preparing to replace libc6-dev 2.15-0ubuntu10.10 (using .../libc6-dev_2.19-19_amd64.deb) ...
Unpacking replacement libc6-dev ...
Preparing to replace libc-dev-bin 2.15-0ubuntu10.10 (using .../libc-dev-bin_2.19-19_amd64.deb) ...
Unpacking replacement libc-dev-bin ...
Preparing to replace libnih-dbus1 1.0.3-4ubuntu9.1 (using .../libnih-dbus1_1.0.3-4.3_amd64.deb) ...
Unpacking replacement libnih-dbus1 ...
Preparing to replace libnih1 1.0.3-4ubuntu9.1 (using .../libnih1_1.0.3-4.3_amd64.deb) ...
Unpacking replacement libnih1 ...
dpkg: considering deconfiguration of locales, which would be broken by installation of libc6 ...
dpkg: yes, will deconfigure locales (broken by libc6).
Preparing to replace libc6 2.15-0ubuntu10.10 (using .../libc6_2.19-19_amd64.deb) ...
De-configuring locales ...
Checking for services that may need to be restarted...
Checking init scripts...
Unpacking replacement libc6 ...
Processing triggers for man-db ...
Errors were encountered while processing:
 /var/cache/apt/archives/locales_2.19-19_all.deb
⋮
```

**Comment by stepthom** [comment]
@BanzaiMan I tried pairing down my `.travis.yml` file to the simplest thing possible to see if I could just get llvm-3.6 to work. Here's my file:

```yml
addons:
  apt:
    sources: 
        - llvm-toolchain-precise-3.6
    packages: 
        - llvm-3.6
```

And here's the build log:

```
Adding APT Sources (BETA)
$ export DEBIAN_FRONTEND=noninteractive
0.34s$ curl -sSL "http://llvm.org/apt/llvm-snapshot.gpg.key" | sudo -E apt-key add -
OK
0.66s$ sudo -E apt-add-repository -y "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main"
Installing APT Packages (BETA)
$ export DEBIAN_FRONTEND=noninteractive
5.34s$ sudo -E apt-get -yq update &>> ~/apt-get-update.log
3.02s$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install llvm-3.6
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 llvm-3.6 : Depends: llvm-3.6-runtime (= 1:3.6.2~svn240577-1~exp1) but it is not going to be installed
            Depends: libllvm3.6 but it is not going to be installed
            Depends: libstdc++6 (>= 4.9) but 4.6.3-1ubuntu5 is to be installed
E: Unable to correct problems, you have held broken packages.
```
