### ISSUE TITLE
LOCALE error export locale fr_FR.UTF-8

### ISSUE THREAD

**Issue by CaptainJojo** [travis-ci/travis-ci#4416]
I want use new container docker but I need locale fr_FR.UTF-8

In my travis.yml I have:

```
sudo: false
language: php
addons:
    apt:
        packages:
            - locales
env:
    global:
        - LANG=fr_FR.UTF-8
        - LC_ALL=fr_FR.UTF-8
php:
  - 5.6
  - 5.3
before_script:
  - composer install --dev
  - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - if [ "$TRAVIS_PHP_VERSION" = "5.6" ]; then printf "yes\n" | pecl install -f apcu-4.0.7; fi;
  - if [ "$TRAVIS_PHP_VERSION" = "5.3" ]; then echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  - echo 'apc.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  ## PHPUnit
  - vendor/bin/phpunit
```

And in my console travis I have:

```
export LANG=fr_FR.UTF-8
export LC_ALL=fr_FR.UTF-8
/home/travis/build.sh: line 41: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8): No such file or directory
```

How use locale fr_FR.UTF.8

**Comment by BanzaiMan** [comment]
Does changing locales work without any intervention on the standard infrastructure?

**Comment by farridav** [comment]
I'm also keen to hear how I would change the locale for a travis build, so far I am exporting..
``` 
LANG='en_US.UTF-8' 
LC_ALL='en_US.UTF-8'
```
and doing echo `'en_US.UTF-8 UTF-8' | sudo tee /var/lib/locales/supported.d/local`

Any advice on this is appreciated ..

**Comment by theofidry** [comment]
I would also love to hear how to support new locales without having to use an old container infrastructure with `sudo` to manually do it.

**Comment by ezmiller** [comment]
Likewise, I need to set locales and am unclear how exactly to best do that.

**Comment by jasny** [comment]
Did you try to add the following?

```
addons:
    apt:
        packages:
            - language-pack-fr
```
