### ISSUE TITLE
cache in mac osx

### ISSUE THREAD

**Issue by AbdealiJK** [travis-ci/travis-ci#4526]
Currently, is there any way to cache directories in `osx` ?
This seems to be working in linux (container based) but not in osx

I'm using pyenv for python (as osx doesnt work with python yet) and want to cache it:
```
os:
  - linux
  - osx

language: generic

cache:
  directories:
    - $PYENV_ROOT

env:
  global:
    - PYENV_ROOT=~/.pyenv
    - PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
  matrix:
    - PYTHON_VERSION=3.4.2
```
