### ISSUE TITLE
Error: "Could not find 'bundler' (>= 0)"

### ISSUE THREAD

**Issue by brauliobo** [travis-ci/travis-ci#4536]
I'm getting this error when trying to run bundler inside a script (see https://travis-ci.org/coletivoEITA/noosfero-ecosol/jobs/72158294):
```
/home/travis/.rvm/rubies/ruby-2.1.6/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'bundler' (>= 0) among 85 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/home/travis/build/coletivoEITA/noosfero-ecosol/vendor/bundle/ruby/2.1.0', execute `gem env` for more information
	from /home/travis/.rvm/rubies/ruby-2.1.6/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:324:in `to_spec'
	from /home/travis/.rvm/rubies/ruby-2.1.6/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
	from /home/travis/.rvm/gems/ruby-2.1.6/bin/bundle:22:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.1.6/bin/ruby_executable_hooks:15:in `eval'
	from /home/travis/.rvm/gems/ruby-2.1.6/bin/ruby_executable_hooks:15:in `<main>'
```

After quite a lot of googling, I got the following workaround from http://stackoverflow.com/questions/26481650/travis-could-not-find-bundler-1-7-4:
```yml
install:
  - gem uninstall bundler
  - gem install bundler
```

But I have no idea of why it is necessary :(

**Comment by brauliobo** [comment]
FYI, to keep caching, I had to do something more sophisticated:
```yml
install:
  - gem uninstall bundler && gem install bundler
  - bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
cache:
  directories:
    - vendor/bundle
```

**Comment by brauliobo** [comment]
this worked:
```yml
install:
  - export GEM_HOME=$PWD/vendor/bundle/ruby/2.1.0
  - gem install bundler
  - bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
cache:
  directories:
    - vendor/bundle
```

**Comment by brauliobo** [comment]
a simpler and more elegant solution, which I suggest to be the default for bundle and caching use:
```yml
before_install:
  - export GEM_HOME=$PWD/vendor/bundle/ruby/2.1.0
  - export BUNDLE_PATH=$PWD/vendor/bundle
  - gem install bundler
cache: bundler
```
This will use `bundler` from the cached environment, and not the one provided from RVM, which I think is more appropriate.
