### ISSUE TITLE
Upgrade Elasticsearch

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-ci#4542]
We have 1.4.0 https://github.com/travis-ci/travis-cookbooks/blob/master/ci_environment/elasticsearch/attributes/default.rb, while 1.7.0 is the most recent one https://www.elastic.co/downloads/elasticsearch

Can this be upgraded?

**Comment by pedrocunha** [comment]
Hi @svenfuchs thanks for raising this one up. Looking forward for the update. Cheers :+1:

**Comment by cursedcoder** [comment]
:+1:

**Comment by akovalyov** [comment]
Hope, the update will be soon! :)

**Comment by MariadeAnton** [comment]
:+1: for Elasticsearch 1.7.2 which is the most recent one now :)

**Comment by MariadeAnton** [comment]
See https://github.com/travis-ci/travis-ci/issues/4772 for the issues using:

```
addons:
  apt:
    sources:
      - elasticsearch-1.7
    packages:
      - elasticsearch
```

**Comment by jastix** [comment]
Issue https://github.com/travis-ci/travis-ci/issues/4772 has been resolved and now it is possible to install newer versions of Elasticsearch (1.6 and 1.7).

Does anyone know how to use the newly installed Elasticsearch in container-based environment?

Having: 
```
services:
  - elasticsearch
```
still seem to use Elasticsearch 1.4.

**Comment by MariadeAnton** [comment]
Hey @jastix, you can use Elasticsearch 1.7 by adding:

```
addons:
  apt:
    sources:
      - elasticsearch-1.7
    packages:
      - elasticsearch
```

Alternatively you could add ``- elasticsearch-1.6``to use 1.6 version

**Comment by jastix** [comment]
@MariadeAnton,

In my .travis.yml I have:
```
services:
  - mysql
  - elasticsearch

before_install:

before_script:

script:

addons:
  apt:
    sources:
      - elasticsearch-1.7
    packages:
      - elasticsearch

```

Command:
```
before_install:
  - whereis elasticsearch
```
Shows: 
```
elasticsearch: /etc/elasticsearch /usr/local/bin/elasticsearch /usr/share/elasticsearch
```

Command:
```
before_script:
  - "elasticsearch -v"
```

Shows: `Version: 1.7.2, Build: e43676b/2015-09-14T09:49:53Z, JVM: 1.7.0_76`

Command:
```
before_script:
  - "curl http://localhost:9200/"
```

Shows: 
```
{
  "status" : 200,
  "name" : "Shola Inkosi",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.4.0",
    "build_hash" : "bc94bd81298f81c656893ab1ddddd30a99356066",
    "build_timestamp" : "2014-11-05T14:26:12Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.2"
  },
  "tagline" : "You Know, for Search"
}
```

Command:
```
before_script:
  - "cat /var/log/elasticsearch/elasticsearch.log"
```

Shows:
```
[2015-09-25 12:01:50,442][INFO ][node                     ] [Shola Inkosi] version[1.4.0], pid[1852], build[bc94bd8/2014-11-05T14:26:12Z]
[2015-09-25 12:01:50,565][INFO ][node                     ] [Shola Inkosi] initializing ...
[2015-09-25 12:01:50,573][INFO ][plugins                  ] [Shola Inkosi] loaded [], sites []
[2015-09-25 12:01:54,386][INFO ][node                     ] [Shola Inkosi] initialized
[2015-09-25 12:01:54,386][INFO ][node                     ] [Shola Inkosi] starting ...
[2015-09-25 12:01:55,118][INFO ][transport                ] [Shola Inkosi] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/172.17.2.115:9300]}
[2015-09-25 12:01:55,200][INFO ][discovery                ] [Shola Inkosi] elasticsearch/HPkFIhD9S_uoijN9QLrlCg
[2015-09-25 12:01:58,996][INFO ][cluster.service          ] [Shola Inkosi] new_master [Shola Inkosi][HPkFIhD9S_uoijN9QLrlCg][testing-worker-linux-docker-05143ca6-3350-linux-13][inet[/172.17.2.115:9300]], reason: zen-disco-join (elected_as_master)
[2015-09-25 12:01:59,146][INFO ][gateway                  ] [Shola Inkosi] recovered [0] indices into cluster_state
[2015-09-25 12:01:59,401][INFO ][http                     ] [Shola Inkosi] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/172.17.2.115:9200]}
[2015-09-25 12:01:59,401][INFO ][node                     ] [Shola Inkosi] started
```

Rails specs fail with message:
```
Elasticsearch::Transport::Transport::Errors::InternalServerError:
       [500] {"error":"IndexCreationException[[test_profiles] failed to create index]; nested: ServiceConfigurationError[Error loading SPI class list from URL: jar:file:/usr/share/elasticsearch/lib/lucene-core-4.10.2.jar!/META-INF/services/org.apache.lucene.codecs.PostingsFormat]; nested: FileNotFoundException[/usr/share/elasticsearch/lib/lucene-core-4.10.2.jar (No such file or directory)]; ","status":500}
```

Even though Elasticsearch 1.7.2 is installed, Elasticsearch 1.4.0 is being used.

**Comment by BanzaiMan** [comment]
I see. The services are started before APT packages are installed via the addon, so the service had already started with the old version. We'll look into arranging the order.

Thanks for bringing this to our attention.

In the meantime, if there is a way to start `elasticsearch` without `sudo service` (I couldn't find it in the doc when I looked for such information), you can try removing it from `services` and start it yourself.

**Comment by jastix** [comment]
@BanzaiMan,
Thank you! Hopefully you will fix the order.

Today I have tried this (elasticsearch is removed from `services`) :
```
before_script:
  - "/usr/local/bin/elasticsearch -d --default.path.conf=/etc/elasticsearch/"
  - "sleep 10"
  - "curl http://localhost:9200/"
```

Which resulted in:
```
$ curl http://localhost:9200/
curl: (7) couldn't connect to host
```
No luck here.

**Comment by nickmarden** [comment]
This is unfortunate, but there is a workaround for this - although it requires some phutzing.

The basic idea is to install the elasticsearch APT package but then run the Elasticsearch server manually, as a background process, as the same user that runs your Travis CI tests.

Here's how it goes.

First, you'll need the following in your `.travis.yml`:

```
sudo: false
addons:
  apt:
    sources:
      - elasticsearch-1.7
    packages:
      - elasticsearch
before_script:
  - bash -x config/travis/setup-elasticsearch.sh && curl localhost:9201
```

Note that I'm running Elasticsearch on port 9201, because I don't want to worry about a system Elasticsearch colliding with the one I'm starting up.

Second, you'll need to add four files to your project. I've placed mine in `config/travis/` because, hey, it's Rails:

[config/travis/setup-elasticsearch.sh](https://gist.github.com/nickmarden/2d41661acdad234ea566)
[config/travis/elasticsearch.sh](https://gist.github.com/nickmarden/fc0cbffc8ae468ce824f)
[config/travis/elasticsearch-client.yml](https://gist.github.com/nickmarden/d60aa0a124f3ffa12681)
[config/travis/elasticsearch-server.yml](https://gist.github.com/nickmarden/0a38fd5ac2493af2029c)

This seems to do the trick, and at the end of the script run you get this in the output:

```
{
  "status" : 200,
  "name" : "travis-node",
  "cluster_name" : "travis",
  "version" : {
    "number" : "1.7.2",
    "build_hash" : "e43676b1385b8125d647f593f7202acbd816e8ec",
    "build_timestamp" : "2015-09-14T09:49:53Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by BanzaiMan** [comment]
Something like the following works now.

```yaml
language: ruby

sudo: false

addons:
  apt:
    sources:
      - elasticsearch-1.7
    packages:
      - elasticsearch
services:
  - elasticsearch

before_install:
  - sleep 10

install: true

script:
  - elasticsearch -v
  - curl http://localhost:9200/
```

**Comment by pedrocunha** [comment]
Thanks guys - this is great. Worth the wait. I will give a try as soon as possible.

**Comment by jastix** [comment]
Thank you very much!
Finally Elasticsearch specs have passed.

**Comment by pedrocunha** [comment]
@BanzaiMan with your config file I get this:

```
Adding APT Sources (BETA)
$ export DEBIAN_FRONTEND=noninteractive
$ curl -sSL "https://packages.elastic.co/GPG-KEY-elasticsearch" | sudo -E apt-key add -
OK
$ echo "deb http://packages.elastic.co/elasticsearch/1.7/debian stable main" | sudo tee -a /etc/apt/sources.list > /dev/null
Installing APT Packages (BETA)
$ export DEBIAN_FRONTEND=noninteractive
$ sudo -E apt-get -yq update &>> ~/apt-get-update.log
$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install elasticsearch
Reading package lists...
Building dependency tree...
Reading state information...
The following packages will be upgraded:
  elasticsearch
1 upgraded, 0 newly installed, 0 to remove and 216 not upgraded.
Need to get 27.3 MB of archives.
After this operation, 1,152 kB of additional disk space will be used.
Get:1 http://packages.elastic.co/elasticsearch/1.7/debian/ stable/main elasticsearch all 1.7.3 [27.3 MB]
Fetched 27.3 MB in 1s (19.0 MB/s)
(Reading database ... 71420 files and directories currently installed.)
Preparing to replace elasticsearch 1.4.0 (using .../elasticsearch_1.7.3_all.deb) ...
Unpacking replacement elasticsearch ...
Setting up elasticsearch (1.7.3) ...
Installing new version of config file /etc/default/elasticsearch ...
Installing new version of config file /etc/elasticsearch/logging.yml ...
Installing new version of config file /etc/init.d/elasticsearch ...
services
$ sudo service elasticsearch start
 * Starting Elasticsearch Server       it: error setting limit (Operation not permitted)
error: permission denied on key 'vm.max_map_count'
```

I don't think this is starting correctly? 

Also what is the best way to overwrite the config file? Does any of this makes sense ?

```
script:
  - curl -XPOST 'http://localhost:9200/_shutdown'
  - elasticsearch -d --config=config/elasticsearch.yml
  - elasticsearch -v
  - curl http://localhost:9200/
```

**Comment by BanzaiMan** [comment]
That output seems normal to me. The error message about the limit is documented (http://docs.travis-ci.com/user/database-setup/#Garbled-Output).

If you need to start ES with non-default config, then you can try specifying a different config file. If the config file is binding the process to port 9200, then you need to either: 1) not start ES with `services`, or 2) bind to a different port.

**Comment by pedrocunha** [comment]
@BanzaiMan thanks for tips!

Whoever has same issue with a custom config this should work - this takes the assumption your project has a `config/elasticsearch.yml` and `config/logging.yml`.

```
language: ruby
sudo: false
rvm: 2.2.2

addons:
  apt:
    sources:
      - elasticsearch-1.7
    packages:
      - elasticsearch

services:
  - redis

cache:
  - bundler

script:
  - elasticsearch -d --default.path.conf=config
  - sleep 15
  - elasticsearch -v
  - curl http://localhost:9200/
  - bundle exec rspec
```

**Comment by nbibler** [comment]
Since this thread comes up in search results, it's probably important to mention that Elastic changed their 2.x APT repository structure. The 2.0 and 2.1 repository URLs that Travis is currently using _do not work_. They've been replaced with a "2.x" repository. For now, it'll require custom builds of Elastic until https://github.com/travis-ci/apt-source-whitelist/pull/262 is merged and deployed.

**Comment by jmunowitch** [comment]
It looks like this has been solved!
https://github.com/travis-ci/apt-source-whitelist/commit/a272145410446f5a8c98afb125be9f4d4de8afc6

**Comment by RyanSnodgrass** [comment]
For those who find this thread in search results and are in need of the 2.x version, put the following in your travis.yml
```yaml
addons:
  apt:
    sources:
      - elasticsearch-2.x
    packages:
    - elasticsearch
services:
  - elasticsearch
```

It installed 2.4.4 which as of this writing is the current version.

**Comment by wetneb** [comment]
Actually, this solution did not work exactly for us - we needed to pin the version of elasticsearch because otherwise apt will not downgrade from ES 5 to ES 2. This is our version:

```
addons:
  apt:
    sources:
      - elasticsearch-2.x
    packages:
    - elasticsearch=2.4.5
services:
  - elasticsearch
```

Hope it helps!
