### ISSUE TITLE
How to check if packages were installed successfully in a container build?

### ISSUE THREAD

**Issue by bilderbuchi** [travis-ci/travis-ci#4557]
In a multi-OS matrix build, some builds are container builds (as we work to transition to the new infrastructure). Unfortunately, I need a package, so I specify like this (excerpt, full file [here](https://github.com/openframeworks/openFrameworks/blob/a1a956b5d0d6dbdd1431a582988f55d33f10dd6f/.travis.yml#L21-L26))
```
matrix:
  include:
    - env: TARGET="android" OPT="armv7"
      sudo: false
      addons:
        apt:
          packages:
          - p7zip-full
```
This seems to be according to [docs](http://docs.travis-ci.com/user/migrating-from-legacy/#Adding-APT-Packages). p7zip-full (containing the `7z`binary) is on the precise whitelist, but the build [complains](https://travis-ci.org/openframeworks/openFrameworks/jobs/72432680#L128) about "command not found". I don't see any other errors hinting at something wrong with p7zip-full.

Questions: How do I verify that the package really got installed? What is going wrong in my build?

**Comment by BanzaiMan** [comment]
I don't think it ran the installation step at all. If it had, you would see something like this in the logs: https://travis-ci.org/BanzaiMan/travis_production_test/builds/72462808#L76

This sort of use of `matrix.include` to get around the multi-OS feature limitation is at the moment unsupported, I believe. Something is dropping `apt.packages` along the way, I imagine, but I can't say what.

**Comment by bilderbuchi** [comment]
> This sort of use of matrix.include to get around the multi-OS feature limitation is at the moment unsupported, I believe. 

What is this feature limitation, and what is the supported/canonical way to divide builds up between OSes (e.g. 2 env entries on OSX, rest of the builds on linux, like in our case)?

**Comment by bilderbuchi** [comment]
> What is this feature limitation, and what is the supported/canonical way to divide builds up between OSes (e.g. 2 env entries on OSX, rest of the builds on linux, like in our case)?

Any input on this @BanzaiMan ?

**Comment by BanzaiMan** [comment]
I ran some additional experiments, and I think there is a bug here, though I'm not sure how yet.

When you add a job with `matrix.include`, if the first item in the hash is `env`, it seems to ignore `apt` addon. That is to say,

```yaml
matrix:
  include:
    - env: TARGET="android" OPT="armv7"
      sudo: false
      addons:
        apt:
          packages:
          - p7zip-full
```

fails to pick up the addon, but

```yaml
matrix:
  include:
    - sudo: false
      env: TARGET="android" OPT="armv7"
      addons:
        apt:
          packages:
          - p7zip-full
```

works. See https://travis-ci.org/BanzaiMan/travis_production_test/jobs/73041485 and the corresponding YAML definition: https://github.com/BanzaiMan/travis_production_test/blob/0093d7f7dc024581b2ce1965d8be22fc64db72b9/.travis.yml#L6-L13
