### ISSUE TITLE
Webhook notification delivery issue with multiple webhooks

### ISSUE THREAD

**Issue by henrikhodne** [travis-ci/travis-ci#4585]
If you have a .travis.yml block like this:

``` YAML
notifications:
  webhooks:
    urls:
      - secure: "…"
      - secure: "…"
```

Where one URL is encrypted with one repository's key and another with a different repository's key, then we still try to deliver to the URL that we can't decrypt (we'll use the encrypted string instead). I would expect that URL to be silently removed, similar to how we treat secure environment variables.

The use case here is that the same code base is pushed to two repositories (one public and one private in this case), and both code bases want notifications.
