### ISSUE TITLE
last N versions for each engine

### ISSUE THREAD

**Issue by iamstarkov** [travis-ci/travis-ci#4614]
for example today iojs@3.0 released and [everybody](https://github.com/search?l=yaml&q=iojs-2&type=Code&utf8=%E2%9C%93) needs to update theirs travis configs with new version of iojs. But if travis will support `last N version` notation, then it will simplify things a lot

**Comment by joshk** [comment]
Hi @iamstarkov 

Thanks for creating this.

Sorry, can you please elaborate what you mean by `last N version` notation?

**Comment by iamstarkov** [comment]
now I have this travis file and yesterday it was okay
```yml
language: node_js
node_js:
  - '0.12'
  - '0.10'
  - 'iojs-2'
  - 'iojs-1'
```

but today after iojs@3.0 release I need to update it like this:
```yml
language: node_js
node_js:
  - '0.12'
  - '0.10'
  - 'iojs-3'
  - 'iojs-2'
```
I need to update because I dont want to maintain my project on old engines. I want to support my projects only on latest one and several prev versions, so I ended up with this approach:

```yml
language: node_js
node_js:
  - node: last 2 version
  - iojs: last 2 version
```
which is now exactly the same as current travis config: node 0.10.x and 0.12.x with iojs 2.x and iojs 3.x. But with great benefit: support policy for obsolete engines will be handled automatically, without need to update already existed modules (I have 30+, but @sindresorhus — 680+).
