### ISSUE TITLE
Cache doesn't work for language: objective-c

### ISSUE THREAD

**Issue by kamoljan** [travis-ci/travis-ci#4615]
Hi guys

cache doesn't work for me.
Here my `.travis.yml`:

    language: objective-c
    cache:
      directories:
      - vendor/bundle
      #  - cocoapods  <-- Doesn't work 
      #  - bundler       <-- Doesn't work

    podfile: ShoppingXXX/Podfile

    # enable container mode
    sudo: false

    # whitelist
    branches:
      only:
        - master

    before_install:
      - gem install cocoapods
      - brew update
      - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
      - ./CI/install-creative-sdk.sh

    xcode_workspace: ShoppingXXX/ShoppingXXX.xcworkspace
    xcode_scheme: ShoppingXXX
    osx_image: xcode6.4
    xcode_sdk: iphonesimulator8.4

**Comment by joshk** [comment]
Hi @kamoljan 

Just to confirm, is this project on travis-ci.com or .org?

Are you just wanting to cache your gems?

Thanks a bundle

**Comment by BanzaiMan** [comment]
Hi, @kamoljan 

You cannot mix hash and array in the way described.

Could you try the following and see if it helps?

```yaml
language: objective-c
cache:
  cocoapods: true
  bundler: true
  directories:
  - vendor/bundle
⋮
```

Also, if you are running jobs on the Mac, `sudo: false` has no effect.

**Comment by kamoljan** [comment]
@joshk it is .com
@BanzaiMan let me try

**Comment by kamoljan** [comment]
@BanzaiMan 


after 

    cache:
      cocoapods: true
      bundler: true
    #  directories:
    #  - vendor/bundle

the log is
    ...

    travis_fold:start:cache.2
    [0Kstore build cache

    $ bundle clean

    [31mCleaning all the gems on your system is dangerous! If you're sure you want to remove every system gem not in this bundle, run `bundle clean --force`.[0m

    travis_time:start:00c96fb7
    [0Kchanges detected, packing new archive

    FAILED: tar -Pzcf /Users/travis/.casher/push.tgz 

    tar: no files or directories specified

    uploading archive

    failed to upload cache

    curl: Can't open '/Users/travis/.casher/push.tgz'!

    curl: try 'curl --help' or 'curl --manual' for more information

    travis_time:end:00c96fb7:start=1438788187000000000,finish=1438788189000000000,duration=2000000000
    [0Ktravis_fold:end:cache.2
    [0K

    Done. Your build exited with 0.

is it bug or it works?

**Comment by AndrewDryga** [comment]
Same for me on XCode6.4 image

**Comment by kamoljan** [comment]
@AndrewDryga can you share your full `.travis.yml` file?

**Comment by AndrewDryga** [comment]
@kamoljan 

You can find it in job 21873506:
```
language: objective-c
osx_image: xcode6.4
sudo: false
cache:
  bundler: true
  cocoapods: true
before_install:
...
env:
    global:
        - ...
    matrix:
        - 'APPLICATION="MBank"'
        - 'APPLICATION="BankVRN"'
```


Result:
```
store build cache
$ bundle clean
Cleaning all the gems on your system is dangerous! If you're sure you want to remove every system gem not in this bundle, run `bundle clean --force`.
2.00schanges detected, packing new archive
FAILED: tar -Pzcf /Users/travis/.casher/push.tgz 
tar: no files or directories specified
uploading archive
failed to upload cache
curl: Can't open '/Users/travis/.casher/push.tgz'!
curl: try 'curl --help' or 'curl --manual' for more information
```

**Comment by kamoljan** [comment]
@AndrewDryga accordingly to your result your cache doesn't work?

**Comment by AndrewDryga** [comment]
@kamoljan It looks like it works, but It still produces errors.

It didn't worked with this config:
```
language: objective-c
osx_image: xcode6.4
sudo: false
cache:
  - bundler
  - cocoapods
before_install:
...
env:
    global:
        - ...
    matrix:
        - 'APPLICATION="MBank"'
        - 'APPLICATION="BankVRN"'

```

**Comment by kamoljan** [comment]
Strange it doesn't work in my case.

**Comment by evils** [comment]
same problem here

**Comment by BanzaiMan** [comment]
Sorry for the delay.

Could you test with:

```yaml
cache:
  edge: true
  ⋮ # rest
```
