### ISSUE TITLE
Unable to upgrade CMake to 3.0 from custom PPA

### ISSUE THREAD

**Issue by rcdailey** [travis-ci/travis-ci#4631]
I have the following:

```
before_install:
    - sudo add-apt-repository ppa:george-edison55/cmake-3.x --yes
    - sudo apt-get update

install:
    - sudo apt-get install cmake
```

In the logs, it says there is no upgrade for CMake when I run the `install` command. This *should* give me CMake 3.x. What am I doing wrong? How can I get cmake 3.0 or greater on Travis for my CI builds?

Thanks.

**Comment by Symbitic** [comment]
I think that ppa:george-edison55/cmake-3.x might not have packages for Ubuntu 12.04 Precise. Try something like ``sudo add-apt-repository ppa:george-edison55/precise-backports --yes`` instead.

**Comment by Towerism** [comment]
It's worth mentioning that to get CMake to install from the george-edison precise backports you have to explicitly install `cmake-data` along with `cmake`, otherwise apt-get will try to install the wrong version of `cmake-data`.

**Comment by BanzaiMan** [comment]
Is there something on our side to do?

**Comment by m-kuhn** [comment]
@BanzaiMan the following works for me:

```yaml
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
```
