### ISSUE TITLE
PyPi deployment fails

### ISSUE THREAD

**Issue by thedrow** [travis-ci/travis-ci#4638]
This used to work with setup.py but it doesn't work with twine for some reason.
See https://travis-ci.org/idan/oauthlib/jobs/74887311#L559 for example.

**Comment by smspillaz** [comment]
(Leaving a note to confirm that it is also happening on my own builds as well, does not seem to be an isolated issue).

**Comment by smspillaz** [comment]
Potentially related to travis-ci/dpl#288 ?

**Comment by BanzaiMan** [comment]
We've had a few reports, and pushed some fixes. Could you add the following and see if the issue is resolved?

```yaml
deploy:
  provider: pypi
  edge: true # <= new!
  ⋮ # the rest
```
