### ISSUE TITLE
An error occurred while generating the build script.

### ISSUE THREAD

**Issue by flower-pot** [travis-ci/travis-ci#4673]
I tried to run my tests using docker-compose, see my repo 

https://github.com/flower-pot/travis-docker-example

The build:

https://travis-ci.org/flower-pot/travis-docker-example/builds/76344467

The last two builds the log only said: 

    An error occurred while generating the build script.

So I tried to reproduce it locally by compiling the .travis.yml using travis-build, "unfortunately" the script did not fail. So I was unable to reproduce it locally.

**Comment by BanzaiMan** [comment]
Does the issue persist if you re-run it?

**Comment by flower-pot** [comment]
just repeated twice - same result

**Comment by BretFisher** [comment]
Same issue, I would get that error any time I used the `deploy:` option. If I put my docker commands in something like `after_success:` everything worked.

**Comment by BanzaiMan** [comment]
I see. `deploy` is an array, which is not allowed. Please consult the documentation for the deployment provider of your choice and set it up correctly. https://docs.travis-ci.com/user/deployment/

Thanks.

**Comment by schmunk42** [comment]
I just ran into a similar issue. The web linting tool said everything would be fine.
May you can add a check there...

**Comment by waghanza** [comment]
same issue for me
**changing `markup**` solved it

**Comment by jalazawa** [comment]
same issue for me 

```YML
language: cpp
sudo: false
dist: trusty

addons:
  sonarqube:
    branches:
    - jalazawaSonar
    token:
    secure: "444444"

jdk:
  - oraclejdk8

script:
  #    other script steps might be done before running the actual SonarQube analysis
  - sonar-scanner
  

cache:
  directories:
    - '$HOME/.sonar/cache'

notifications:
  email: true
```
