### ISSUE TITLE
Allow for tag options (only, except) like branches

### ISSUE THREAD

**Issue by mrowles** [travis-ci/travis-ci#4679]
We want to tag successful Travis builds, but obviously we don't want to get caught in a loop when Travis is watching the repository.

Proposing a similar option for tags such as:

```
branches:
  only:
    - master

tags:
  only:
    - /^build-.*$/
```

**Comment by BanzaiMan** [comment]
Could you elaborate on the use case? You want to build only the `master` branch, tag the commit with some convention if successful, and push the tag to GitHub?

In this scenario,

```yaml
branches:
  only:
    - master
```

skips building the tag (unless the tag matches `master` exactly), so I must be missing something.
