### ISSUE TITLE
Defining the build matrix only with matrix.include leads to an additional, unwanted job

### ISSUE THREAD

**Issue by bilderbuchi** [travis-ci/travis-ci#4681]
Simple reproduction of the problem: A .travis.yml, makes two builds, one without environment variables defined. One build only, with `TARGET=linux` is desired:

```
language: c++
compiler: gcc
matrix:
  include:
    - os: linux
      env: TARGET="linux"

install: true

script: true
```

leads to

```
    15.1 Compiler: gcc  no environment variables set
    15.2 Compiler: gcc  TARGET="linux"
```

https://travis-ci.org/bilderbuchi/travis_production_test/builds/76336816

Related issue: #1228

**Comment by BanzaiMan** [comment]
For now, you can exclude the default test:

```yaml
language: c++
compiler: gcc
matrix:
  include:
    - os: linux
      env: TARGET="linux"
  exclude:
    - compiler: gcc
```

**Comment by bilderbuchi** [comment]
Ah, nice workaround, thanks!

**Comment by o11c** [comment]
I think this works if you *omit* the top-level `compiler: gcc` line.

**Comment by ldionne** [comment]
The proposed workaround is very annoying, because some of us might actually need the global `compiler: gcc` (or in my case `compiler: clang`). The other option is to end up with `compiler: gcc` globally and then to redefine `compiler: clang` for each job inside `matrix.include`, but when you have 20+ jobs, that makes a lot of repetition. I beg you for a clean fix.

**Comment by wavexx** [comment]
Is there a *proper* fix planned for this issue?

I use ``language: python`` with matrix expansion to test for optional dependencies and I'm tired to see the build fail for the extraneous entry.

**Comment by BanzaiMan** [comment]
@wavexx Is the workaround shown above not working for you?

**Comment by wavexx** [comment]
I have to work-around basically all projects where I'm using travis.

**Comment by saantiaguilera** [comment]
Do guys keep doing that awful workaround or theres a feature/hotfix for this coming ?

**Comment by ldionne** [comment]
I'm still doing the workaround. If a fix is coming, it would be a coldfix more than a hotfix by now ;-)

**Comment by BanzaiMan** [comment]
Sorry for the delay. The matrix expansion code is one of the hairiest part of our code base, and it has not been prioritized quite yet in order to clean it up and fix this issue.

Thank you for your patience.

**Comment by saantiaguilera** [comment]
Well, workaround works so no problem I guess lol

**Comment by goldylucks** [comment]
@BanzaiMan what would b the equivalent workaround for a nodejs project?

**Comment by BanzaiMan** [comment]
I am alerted to this issue today, and trying to understand the rationale behind it. That is, why exclude the default job when you can override it?

In each build, there is a default job. Defining `matrix.include` _adds_ to it. Unless you exclude the default job (as I showed in an earlier comment), the default job will remain in the build matrix.

If you are trying to construct a build matrix with just `matrix.include`, maybe that is not the best way.

For example, the OP's configuration:

```yaml
language: c++
compiler: gcc
matrix:
  include:
    - os: linux
      env: TARGET="linux"

install: true

script: true
```

is better expressed as:

```yaml
language: c++
compiler: gcc
env:
  - TARGET="linux"

install: true

script: true
```

It is easy to override the default job. Maybe that is the thing to do, rather than excluding it.

**Comment by goldylucks** [comment]
@BanzaiMan
how would u overwrite the default job when u got 3 jobs and a global variable?

ATM my `.yml` file looks like this:

```yml
env:
  global:
  - secure: ...
matrix:
  include:
  - env: SCRIPT=lint
  - env: SCRIPT=test
  - env: E2Eweb=true
```

**Comment by BanzaiMan** [comment]
https://docs.travis-ci.com/user/environment-variables#Global-Variables

```yaml
env:
  global:
  - secure: ...
matrix:
  - SCRIPT=lint
  - SCRIPT=test
  - E2Eweb=true
```

**Comment by goldylucks** [comment]
Indeed, that [worked](https://travis-ci.org/goldylucks/memory-n-back/builds/191407526)!

Thanks for the help @BanzaiMan :)

Judging by the amount of "fuss" around this, I'd say updating the docs might b a good idea.

Thoughts?

**Comment by BanzaiMan** [comment]
Sure, documentation is good. If you have suggestions as to where this would fit, we are happy to discuss that. :-D

**Comment by goldylucks** [comment]
maybe a reference to the default job here:
https://docs.travis-ci.com/user/customizing-the-build#Explicitly-Including-Jobs

Maybe with a link to this issue and your answer

and to your FAQ (which I don't find ATM, not sure u have one)

in anyway I think this issue can b closed right?

**Comment by AraHaan** [comment]
That looks similar to my matrix issue with osx as it has problems getting latest clang and g++. However doing more digging it turns out that Ubuntu 14.04 LTS is too old for updating and seems the current VMs that travis provides on trusty needs upgraded to 16.04 LTS of Ubuntu.

Also with 16.04 it should be able to come with at least gcc and g++ 5.3 or newer so makes building c++14 programs for linux easier (hopefully).

```yaml
matrix:
  include:
    - os: linux
      compiler: clang-3.9
      env: COMPILER=clang++
      addons:
        apt:
          sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.9
    - os: osx
      compiler: clang-3.9
      env: COMPILER=clang++
      addons:
        apt:
          sources:
            - llvm-toolchain-precise
          packages:
            - clang-3.9
```

**Comment by BanzaiMan** [comment]
@AraHaan You should designate one of them as the default job, and leave the other in `matrix.include`; e.g.,

```yaml
compiler: clang-3.9
env: COMPILER=clang++
addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.9
matrix:
  include:
    - os: osx
      compiler: clang-3.9
      env: COMPILER=clang++
      addons:
        apt:
          sources:
            - llvm-toolchain-precise
          packages:
            - clang-3.9

**Comment by AraHaan** [comment]
Ok, that partially works but now the other one just locks up and never starts:
https://travis-ci.org/AraHaan/bin2c/builds/191450083

**Comment by BanzaiMan** [comment]
@AraHaan It's not locking up. You are just waiting for the Mac resources to become available. We are short on Mac build resources at the moment. Please be patient.

**Comment by BanzaiMan** [comment]
@goldylucks I think so. Once we have a good documentation explaining things, we can close this.

**Comment by ssokolow** [comment]
@BanzaiMan 

> It's not locking up. You are just waiting for the Mac resources to become available. We are short on Mac build resources at the moment. Please be patient.

Perhaps there should be a clearer indication of the "waiting in queue for resources" state. Didn't one of the older designs actually show your queue position in the status field?

**Comment by BanzaiMan** [comment]
> Perhaps there should be a clearer indication of the "waiting in queue for resources" state

Besides the `created` state?

**Comment by ssokolow** [comment]
I mean in the top-level "Build Jobs" view where you don't have other details clamoring for attention.

Putting something more explanatory than a `-` to the right of the clock icon (eg. `queued`, `booting`, etc.) would be ideal.

**Comment by BanzaiMan** [comment]
@ssokolow I see what you are saying, and we may consider it in the future. Please keep in mind that this is a different issue from the one we are discussing here.

**Comment by ssokolow** [comment]
Understood. The conversation just sort of wandered off on a tangent and, unfortunately, GitHub has yet to come up with their own version of Discourse's "reply in new thread" feature.

**Comment by goldylucks** [comment]
@BanzaiMan something really weird happened ...
when I first omitted `include` [as u said](https://github.com/travis-ci/travis-ci/issues/4681#issuecomment-272251622), it worked and stopped running the default job. However [now it's running _only_](https://travis-ci.org/goldylucks/memory-n-back/builds/192448226) the default job.

I've even [reverted the change](https://github.com/goldylucks/memory-n-back/commit/712e186587987f1e71860e58281b85cfb107c48f) (re-added `include`),  [merged it](https://travis-ci.org/goldylucks/memory-n-back/builds/191814824), and the problem continues ...

The strangest thing is that even [the build I've told u before worked](https://travis-ci.org/goldylucks/memory-n-back/builds/191407526), now shows only the default job.

Glitch in the matrix? :question:

**Comment by BanzaiMan** [comment]
In [this job](https://travis-ci.org/goldylucks/memory-n-back/builds/192448226), [`matrix.include` is an sequence](https://github.com/goldylucks/memory-n-back/blob/64cb3ba500c228f1a1c8869166d6d3484c773e78/.travis.yml#L15-L19), not a map, so it is ignored.

This problem continues to this build: https://travis-ci.org/goldylucks/memory-n-back/builds/191814824.

**Comment by goldylucks** [comment]
gotcha
[just tried](https://travis-ci.org/goldylucks/memory-n-back/builds/192485220) your solution, doesn't work, only default job gets triggered :(

**Comment by BanzaiMan** [comment]
@goldylucks You removed too much. `include:` should remain on that line.

**Comment by wavexx** [comment]
I see the logic now, however in several cases I'd like to leave all alternatives inside the matrix definition and simply kill the default build. First, because i don't have a "default" build, and second it makes the configuration file cleaner.

Would it be reasonable to have a switch to disable the default build, or something that doesn't "add" builds to the default like include does? (like "set" or "define")

**Comment by BanzaiMan** [comment]
@wavexx That "switch" you speak of is really `matrix.exclude`, no?

**Comment by wavexx** [comment]
On Mon, Jan 16 2017, Hiro Asari wrote:
> @wavexx That "switch" you speak of is really matrix.exclude, no?

To exclude the default build, the quickest way I've found is to define
an extra env.matrix var which *then* you can exclude with
matrix.exclude.

  https://github.com/wavexx/gtabview/blob/master/.travis.yml

It's ugly, also because it shows up in *all* builds.
See:

  https://travis-ci.org/wavexx/gtabview

**Comment by BanzaiMan** [comment]
@wavexx You can exclude with the default value of `python`. See https://travis-ci.org/BanzaiMan/travis_production_test/jobs/192691458 and its config https://github.com/BanzaiMan/travis_production_test/blob/85d19e37a248c3a2adde63a3ebdb2eac4ec3fb29/.travis.yml#L3-L7. (This is vulnerable to future change of the default Python, but you get the idea.)

**Comment by wavexx** [comment]
On Tue, Jan 17 2017, Hiro Asari wrote:
> @wavexx You can exclude with the default value of python. See
> https://travis-ci.org/BanzaiMan/travis_production_test/jobs/192691458 and its config
> https://github.com/BanzaiMan/travis_production_test/blob/85d19e37a248c3a2adde63a3ebdb2eac4ec3fb29/.travis.yml#L3-L7.
> (This is vulnerable to future change of the default Python, but you get the idea.)

Somehow this feels like a worse hack

**Comment by Timmmm** [comment]
@wavexx You can do it more simply by just excluding something that matches the default build. So for your example try something like this:

```
...
env:
  global:
    - DISPLAY=:99.0
    - PIP_DISABLE_PIP_VERSION_CHECK=1

matrix:
  exclude:
    - language: python
  include:
    - python: 2.7_with_system_site_packages
      addons:
        apt:
          packages:
            - python-qt4
      before_install:
        - pip uninstall -qy numpy
...
```

**Comment by wavexx** [comment]
On Sun, Feb 05 2017, Tim wrote:
> @wavexx You can do it more simply by just excluding something that
> matches the default build. So for your example try something like
> this:

Doesn't work:

https://travis-ci.org/wavexx/gtabview/builds/199277854

https://github.com/wavexx/gtabview/commit/e3dcc14e3081b6bcc0524ecded4bb72428b24e4e

**Comment by Timmmm** [comment]
Hmm that's weird, a similar trick worked for me. Ah wait, no I didn't use `language` actually. Here's my config:

https://github.com/Timmmm/soundio-rs/blob/master/.travis.yml

https://travis-ci.org/Timmmm/soundio-rs

I pretty much tried random stuff until it worked (Travis's documentation is ... well anyway). Maybe you need to use a variable that Travis doesn't know about. Maybe this will work?

```
language: python
os: linux
sudo: false
cache: pip

dummy: true
 
env:
  global:
    - DISPLAY=:99.0
    - PIP_DISABLE_PIP_VERSION_CHECK=1

matrix:
  exclude:
    # exclude default build
    - dummy: true
  include:
    - python: 2.7_with_system_site_packages
      addons:
        apt:
          packages:
...
```

Just a guess. It's really frustrating that you have to do a commit to test these, and basically hope it works. Travis needs an online 'paste your config and see what will be built' thing. Kind of like [this](http://lint.travis-ci.org/) but useful.

**Comment by wavexx** [comment]
On Tue, Feb 07 2017, Tim wrote:
> I pretty much tried random stuff until it worked

Yes, me too. I'm tired.

> (Travis's documentation is ... well anyway).

I noticed as well.

> Maybe you need to use a variable that Travis doesn't know about. Maybe
> this will work?

It doesn't:

https://travis-ci.org/wavexx/gtabview/builds/199305690

> Just a guess. It's really frustrating that you have to do a commit to
> test these, and basically hope it works. Travis needs an online 'paste
> your config and see what will be built' thing. Kind of like
> [this](http://lint.travis-ci.org/) but useful.

Frankly, I also had huge problems with the current travis images when it
boils down to python. I did my best to switch over to the container
system, but now I do have random crashes in python 3.2 itself that I
cannot reproduce elsewhere. All made more complicated by the fact that I
need to depend on base packages (pyqt).

Maybe I should switch back to sudo, where at least I could patch the
system. But like I said, I've fought a losing battle here just by trial
and error.

**Comment by vitaly-t** [comment]
Tried everything, nothing works.

Travis always builds for Node.js 0.10 by default, from which I cannot get rid of, and since my module doesn't support it, the build always fails.

**Comment by mikegrima** [comment]
I agree that this is painful. I tried some of the suggestions here, but none were successful.

I ultimately settled on repeating most of the significant fields for each test.  Example: https://github.com/Netflix/security_monkey/pull/689

**Comment by BanzaiMan** [comment]
@mikegrima I understand the pain, but in the case of https://github.com/Netflix/security_monkey, the jobs seem significantly different (in particular, they do not share `script`) and there is no way but to list them all.

**Comment by noloader** [comment]
Man, something is seriously wrong here. Our exclude rules were not being honored, so I removed them. Then I manually unrolled things so the `matrix:` included ***exactly*** what we we wanted. The `matrix` only has 12 rows.

Our count went from 24 (mildly incorrect) to 52 (wildly incorrect). WTF???

Doing the obvious and guessing is not working as expected. Please, for the love of {god|allah|<favorite deity>}, please document what we are supposed to do somewhere. Please provide _lots_ of examples.

Please don't point us to this few sentence explanation: [Customizing the Build | Build Matrix](https://docs.travis-ci.com/user/customizing-the-build#Build-Matrix). I don't use Ruby, so I have no idea how it applies to C and C++.

**Comment by noloader** [comment]
Man, something is seriously wrong here. Our exclude rules were not being honored, so I removed them. Then I manually unrolled things so the `matrix:` included ***exactly*** what we we wanted. The `matrix` only has 12 rows.

Our count went from 24 (mildly incorrect) to 52 (wildly incorrect). WTF???

Doing the obvious and guessing is not working as expected. Please, for the love of {god|allah|\<favorite deity\>}, please document what we are supposed to do somewhere. Please provide _lots_ of examples.

Please don't point us to this few sentence explanation: [Customizing the Build | Build Matrix](https://docs.travis-ci.com/user/customizing-the-build#Build-Matrix). I don't use Ruby, so I have no idea how it applies to C and C++.

**Comment by noloader** [comment]
Man, something is seriously wrong here. Our exclude rules were not being honored, so I removed them. Then I manually unrolled things so the `matrix:` included ***exactly*** what we we wanted. The `matrix` only has 12 rows.

Our count went from 24 (mildly incorrect) to 52 (wildly incorrect). WTF???

Doing the obvious and guessing is not working as expected. Please, for the love of {god|allah|\<favorite deity\>}, please document what we are supposed to do somewhere. Please provide _lots_ of examples.

Please don't point us to this few sentence explanation: [Customizing the Build | Build Matrix](https://docs.travis-ci.com/user/customizing-the-build#Build-Matrix). I don't use Ruby, so I have no idea how it applies to C and C++.

**Comment by noloader** [comment]
Man, something is seriously wrong here. Our exclude rules were not being honored, so I removed them. Then I manually unrolled things so the `matrix:` included ***exactly*** what we we wanted. The `matrix` only has 12 jobs.

Our count went from 24 (mildly incorrect) to 52 (wildly incorrect). WTF???

More fiddling turned out 12 jobs into 4 jobs.

Doing the obvious and guessing is not working as expected. Please, for the love of {god|allah|\<favorite deity\>}, please document what we are supposed to do somewhere. Please provide _lots_ of examples.

Please don't point us to this few sentence explanation: [Customizing the Build | Build Matrix](https://docs.travis-ci.com/user/customizing-the-build#Build-Matrix). I don't use Ruby, so I have no idea how it applies to C and C++.

**Comment by noloader** [comment]
Man, something is seriously wrong here. Our exclude rules were not being honored, so I removed them. Then I manually unrolled things so the `matrix:` included ***exactly*** what we we wanted. The `matrix` only has 12 rows.

Our count went from 24 (mildly incorrect) to 52 (wildly incorrect). WTF???

More knob turning caused the job count to drop to 4. 8 jobs went missing somewhere. 

Doing the obvious and guessing is not working as expected. Please, for the love of {god|allah|\<favorite deity\>}, please document what we are supposed to do somewhere. Please provide _lots_ of examples.

Please don't point us to this few sentence explanation: [Customizing the Build | Build Matrix](https://docs.travis-ci.com/user/customizing-the-build#Build-Matrix). I don't use Ruby, so I have no idea how it applies to C and C++, and testing under Linux and OS X with Clang and GCC.

**Comment by BanzaiMan** [comment]
@noloader Please review your configuration. https://github.com/noloader/cryptopp/blob/01e24c79e04f884bbacc2c7c6cf8763c46daf9f9/.travis.yml has many occurrences of `matrix.include`. By YAML specification, you only get the last one, which is

```yaml
matrix:
    inlcude:	  
      - os=osx   compiler=clang BUILD_MODE="ubsan"
```

Since this string does not define any job, it is used to define `env` value (you can see that in https://travis-ci.org/noloader/cryptopp/jobs/236682339/config).

I'm guessing that you want something like:

```yaml
  matrix:
    inlcude:
      - os: linux
        compiler: gcc  
        BUILD_MODE: "all"
      - os: linux
        compiler: gcc  
        BUILD_MODE: "no-asm"
      - os: linux
        compiler: gcc  
        BUILD_MODE: "asan"
      - os: linux
        compiler: gcc  
        BUILD_MODE: "ubsan"
      - os: linux
        compiler: gcc  
        BUILD_MODE: "codecov"
      - os: linux
        compiler: clang
        BUILD_MODE: "all"
      - os: linux
        compiler: clang
        BUILD_MODE: "no-asm"
      - os: linux
        compiler: clang
        BUILD_MODE: "asan"
      - os: linux
        compiler: clang
        BUILD_MODE: "ubsan"
      - os: osx  
        compiler: clang
        BUILD_MODE: "all"
      - os: osx  
        compiler: clang
        BUILD_MODE: "no-asm"
      - os: osx  
        compiler: clang
        BUILD_MODE: "asan"
      - os: osx  
        compiler: clang
        BUILD_MODE: "ubsan"
```

**Comment by BanzaiMan** [comment]
Equivalently:

```yaml
compiler:
  - gcc
  - clang
env:
  global:
    - BUILD_JOBS=2
  matrix:
    - "all"
    - "no-asm"
    - "asan"
    - "ubsan"
matrix:
  include:
      - os: osx  
        compiler: clang
        BUILD_MODE: "all"
      - os: osx  
        compiler: clang
        BUILD_MODE: "no-asm"
      - os: osx  
        compiler: clang
        BUILD_MODE: "asan"
      - os: osx  
        compiler: clang
        BUILD_MODE: "ubsan"

**Comment by BanzaiMan** [comment]
Incidentally: https://github.com/noloader/cryptopp/blob/ec52b983a8ce2c3e9c878aa6bce60f2139b26ef8/.travis.yml defines 13 entries in `env.matrix`, 2 entires for `compiler`, and 2 entries in `os`, resulting in 52 = 13×2×2 jobs in the matrix. https://travis-ci.org/noloader/cryptopp/builds/236675036

**Comment by noloader** [comment]
Thanks @BanzaiMan.

The complexity is wasting too much of your time and other's time. I want to make this drop dead simple so it always "just works".

Trying to use {`env.matrix` x `compiler` x `os` x `<some other feature>`} is too complex. It does not work as expected, others don't understand it, and its not easy to maintain. I don't want to our users spending hours on the web searching for answers or asking questions on Stack Overflow. Worse, I don't want users asking me how to do something because I don't know (*q.v.*).

How do we build ***only*** what is in the matrix? I want to do it that way because its easy to understand and others will be able to maintain it. Since it "just works", they won't waste their time on the web and they won't ask me questions.

**Comment by noloader** [comment]
Thanks @BanzaiMan.

The complexity is wasting too much of your time and other's time. I want to make this drop dead simple so it always "just works".

Trying to use {`env.matrix` x `compiler` x `os` x `<some other feature>`} + {`exclude` `<some feature>`} is too complex. It does not work as expected, others don't understand it, and its not easy to maintain. I don't want to our users spending hours on the web searching for answers or asking questions on Stack Overflow. Worse, I don't want users asking me how to do something because I don't know (*q.v.*).

How do we build ***only*** what is in the matrix? I want to do it that way because its easy to understand and others will be able to maintain it. Since it "just works", they won't waste their time on the web and they won't ask me questions.

It would also be great of Travis would document it somewhere. Its not covered in the docs, I can't find a mailing list to ask questions, and questions on Stack Overflow go unanswered.

**Comment by BanzaiMan** [comment]
Could you elaborate on what you mean by this?

> Trying to use {`env.matrix` x `compiler` x `os` x `<some other feature>`} + {`exclude` `<some feature>`} is too complex. It does not work as expected, others don't understand it, and its not easy to maintain.

If you have suggestions on improving https://docs.travis-ci.com/user/customizing-the-build#Excluding-Jobs, we are happy to discuss them.

> How do we build only what is in the matrix? I want to do it that way because its easy to understand and others will be able to maintain it. Since it "just works", they won't waste their time on the web and they won't ask me questions.

This is certainly possible if your build configuration has all combinations of every dimension defined in `.travis.yml`. Your example, however, does not fall into this case, so it is not possible. You can add them one by one (https://github.com/travis-ci/travis-ci/issues/4681#issuecomment-304467567), or use the Cartesian product minus the matching jobs (https://github.com/travis-ci/travis-ci/issues/4681#issuecomment-304468124).

**Comment by noloader** [comment]
Thanks @BanzaiMan.

> You can add them one by one (#4681 (comment)) ...

Thanks. We tried that, but it did not work either. Here's the Travis config file update: [Commit 3b9ff6bf807d1b8c](https://github.com/noloader/cryptopp/commit/3b9ff6bf807d1b8c47c75a8fecaf3a618fb096f6); and here's the build result: [Job 236788559](https://travis-ci.org/noloader/cryptopp/jobs/236788559):

```
Setting environment variables from .travis.yml

$ export BUILD_JOBS=2    
$ export inlcude=[{:os=>    
/home/travis/.travis/job_stages: eval: line 54: syntax error near unexpected token `newline'    
/home/travis/.travis/job_stages: eval: line 54: `export inlcude=[{:os=> '    
$ export compiler=>    
/home/travis/.travis/job_stages: eval: line 54: syntax error near unexpected token `newline'    
/home/travis/.travis/job_stages: eval: line 54: `export compiler=> '    
$ export BUILD_MODE=>    
/home/travis/.travis/job_stages: eval: line 54: syntax error near unexpected token `newline'    
/home/travis/.travis/job_stages: eval: line 54: `export BUILD_MODE=> '
...
```

-----

> ... or use the Cartesian product minus the matching jobs (#4681 (comment)).

Thanks again. This does not seem to work either. Excluded jobs are run, the excluded jobs fails, and the failure trickles down into other web services through web hooks.

Here's the original Travis config file where we were trying to use excludes. Its still in upstream master: [`.travis.yml`](https://github.com/weidai11/cryptopp/blob/master/.travis.yml). It produces build failures like those detailed in [Build 236649434](https://travis-ci.org/noloader/cryptopp/builds/236649434).

In the 236649434 build, we specifically excluded Clang/UBsan, Clang/Coverage, OS X/GCC/UBsan (and a few others), but they still ran. The failures broke CodeCov, which looks for a success before it performs its analysis.

-----

Let me ask this (sorry to go off-topic on this bug report)... Are there any Travis consultants available to fix this problem for us? Sorry to have to ask. I've spent 3 days trying to build 12 jobs without success. I've tried to get help from users on [our mailing list](https://groups.google.com/forum/#!topic/cryptopp-users/ZrQ0DibwwBM) (no responses), and I've tried to get [help on Stack Overflow](https://stackoverflow.com/q/44222998/608639) (no answers). I don't know where else to turn.

"We" are a free and open software project. We are trying to add Travis because some users requested it. Travis looks like a good idea, so I'm happy to add it. However, Travis is not our specialty. When we start struggling on side-tasks like Travis, its often better for us to engage a specialist.

I eat my own dog food. When other FOSS projects have trouble with Crypto++, I reach out to them personally. Every distro maintainer has my email address, home phone number and cell phone number. I don't want any FOSS projects struggling with our library.

**Comment by BanzaiMan** [comment]
@noloader The problem with https://github.com/noloader/cryptopp/commit/3b9ff6bf807d1b8c47c75a8fecaf3a618fb096f6 is that it leaves the `matrix` key on line 24 (and its child `include` and the array following it) starting at column 4. This turns `include` and its value into an environment variable definition, leading to the error you saw in https://travis-ci.org/noloader/cryptopp/jobs/236788559.

You need to outdent the `matrix` key, so that there is no space before it on that line. (You might also want to outdent the lines following that, but it is not strictly necessary.)

I am sorry that you have had a tough go on configuring Travis Ci the way you want. It is certainly not meant to be difficult, and we try to explain the behavior in our documents. Perhaps more examples would help. If you could help us identify where we could improve (by pointing out where documentation was unclear, or lacking, or …?), please do.

**Comment by BanzaiMan** [comment]
As for https://github.com/weidai11/cryptopp/blob/814de0f0c722f90f2ed27a53fb0325c063fe6443/.travis.yml, if the goal is to skip the jobs with https://github.com/weidai11/cryptopp/blob/814de0f0c722f90f2ed27a53fb0325c063fe6443/.travis.yml#L31-L42, then adding `matrix:` to line 30 should do. https://github.com/weidai11/cryptopp/pull/432

**Comment by BanzaiMan** [comment]
Hi, everyone.

This issue has now been fixed. In other words, if you have no matrix expansion on the top level, and there is at least one job defined in `matrix.include`, the top level job is no longer included in the build matrix.

Thanks!

**Comment by domenkozar** [comment]
@BanzaiMan this change is backwards incompatible. Our main job just disappeared because of this change on travis-ci

**Comment by szczepiq** [comment]
We are very happy users of Travis CI, thank you for offering this great service to our Open Source projects!!! Some feedback about this particular change:
 - backwards incompatible changes such as this one are confusing. Our main job suddenly disappeared causing Mockito releases to stop happening. We were debugging this problem, contacting Travis CI support to understand what's up.
 - the current behavior seems odd - the top level "jdk" job description is silently ignored if matrix.include is used. If the travis file contains a setting that does not work, why not abort the build with clean message what/how to fix? It's just a suggestion, I'm not involved in Travis configuration UX enough to formulate comprehensive behavior suggestions.

For us, the problem was easy to fix and Travis support was very quick to offer a hand. Thank you, all good now :)

**Comment by BanzaiMan** [comment]
@domenkozar @szczepiq Thank you for the feedback. We are sorry that this change was not carried out seamlessly.

The main motivation for making this change was the introduction of Build Stages, where removing the singular default job is a bit more difficult, and not having that job is more natural.

**Comment by domenkozar** [comment]
@BanzaiMan I don't think the reasoning for the change is at question, but rather communication about backwards incompatibility going off silently :)

Would be good to have such changes communicated well, so when we spot side-effects we can pinpoint what caused them. I spend a couple of hours through our changes to figure out it was a change on travis-ci side and I really hadn't doubted that such major change would be made.

**Comment by BanzaiMan** [comment]
@domenkozar Thanks for the clarification. Yes, we could have done better. And for this, we apologize.

**Comment by domenkozar** [comment]
@BanzaiMan I wanted to give valuable feedback for future, not blaming you guys otherwise :) Thanks again!

**Comment by Randolph-zeng** [comment]
Sorry to bring this up again. But I run into this problem today and can not figure out why this is the case.
I have a simple travis file that have this pattern.

``` 
matrix:
  include:
    - language: node_js
      node_js: "6"
      install:
        - xxx
      script:
        - xxx
      deploy:
        - provider: script
          skip_cleanup: true
          script: bash deploy_js_actions.sh $OW_PROD_SPACE $OW_APIHOST $OW_PROD_AUTH
          on:
           branch: master
    - language: python
      python: "3.6"
      install:
        - xxx
      script:
        - xxx
      deploy:
        - provider: script
          skip_cleanup: true
          script: bash deploy_py_actions.sh $OW_PROD_SPACE $OW_APIHOST $OW_PROD_AUTH
          on:
           branch: master
```
However, for some reason in travis three job instead of two created 
```
 60.1
 Ruby
 no environment variables set
 19 sec

 60.2
 Node.js: 6
 COMMAND_FILE="deploy_js_actions.sh"
 22 sec

 60.3
 Python: 3.6
 COMMAND_FILE="deploy_py_actions.sh"
 50 sec

```
The extra unwanted ruby job is failing because of the following error and comes with the config of 
```
0.16s$ rake
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/home/travis/.rvm/gems/ruby-2.4.1@global/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
The command "rake" exited with 1.

{
  "sudo": "required",
  "dist": "trusty",
  "language": "ruby",
  "group": "stable",
  "os": "linux"
}
```
I have no idea where this extra job comes from and I tried several ways like exclude ruby in the matrix but none of them work. Can anybody shed some light on this?
