### ISSUE TITLE
Build R package on Mac OSX?

### ISSUE THREAD

**Issue by cdeterman** [travis-ci/travis-ci#4690]
@craigcitro, @eddelbuettel, @hadley

I am trying to build an R package using the Mac OS on Travis.  You can see my current `.travis.yml` file below.  The build runs but it doesn't appear to do anything related to the R package?  You can see the output [here](https://travis-ci.org/cdeterman/gpuR/builds/76673356).  Am I missing something to get the Mac OS to build R packages?

```
os:
  - osx

language: 
  - objective-c
  - r

sudo: required

compiler:
  - g++

r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --no-build-vignettes --no-manual

brew_packages:
  - assertive
  - covr
  - devtools
  - BH
  - Rcpp
  - RcppEigen

r_github_packages:
  - cdeterman/RViennaCL

before_install:
  - sudo brew update
  - export CXX="g++-4.8"

after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
```
