### ISSUE TITLE
RubyMotion on osx_image: xcode6.4

### ISSUE THREAD

**Issue by bmichotte** [travis-ci/travis-ci#4692]
Trying to run tests for https://github.com/bmichotte/ProMotion-XLForm which use https://github.com/xmartlabs/XLForm which require xcode 6.3+ (it uses `nullable`, `nonnull`, `null_unspecified` keywords).

If I use the following .travis.yml (using this *[workaround](https://github.com/travis-ci/travis-ci/issues/1286)*)
```yml
language: objective-c
osx_image: xcode6.4
before_install:
    - (ruby --version)
    - sudo chown -R travis ~/Library/RubyMotion
    - mkdir -p ~/Library/RubyMotion/build
    - sudo motion update
gemfile:
  - Gemfile
script:
    - bundle install
    - bundle exec rake pod:install > /dev/null
    - bundle exec rake clean
    - bundle exec rake spec
```
I got this [error](https://travis-ci.org/bmichotte/ProMotion-XLForm/builds/76688154)
```
chown: /Users/travis/Library/RubyMotion: No such file or directory
The command "sudo chown -R travis ~/Library/RubyMotion" failed and exited with 1 during .
Your build has been stopped.
```

If I change the `.travis.yml` and remove
```yml
    - sudo chown -R travis ~/Library/RubyMotion
    - mkdir -p ~/Library/RubyMotion/build
```

I end up with the following [errors ](https://travis-ci.org/bmichotte/ProMotion-XLForm/builds/76686874)
```
Cannot write into the '/Users/travis/Library/RubyMotion/build' directory, please remove or check permissions and try again.
[CLIP]
** BUILD SUCCEEDED **
/bin/cp ".build/libRSColorPicker.a" "build-iPhoneSimulator"
/bin/cp ".build/libXLForm.a" "build-iPhoneSimulator"
Cannot write into the '/Users/t
```

Could you please fix what needs to be fixed ?
