### ISSUE TITLE
PostgreSQL version switching fails randomly

### ISSUE THREAD

**Issue by johanneswuerbach** [travis-ci/travis-ci#4707]
In some of our builds the PostgreSQL version switching is failing:
log:
```
Starting PostgreSQL v9.4
$ sudo service postgresql stop
 * Stopping PostgreSQL 9.4 database server       * Error: Config owner (postgres:102) and data owner (root:0) do not match, and config owner is not root
fail]
$ sudo service postgresql start 9.4
 * Starting PostgreSQL 9.4 database server       * Error: Config owner (postgres:102) and data owner (root:0) do not match, and config owner is not root
fail]
$ sudo -u postgres createuser -s -p 5432 travis &>/dev/null
$ sudo -u postgres createdb -O travis -p 5432 travis &>/dev/null
$ sudo -u postgres createuser -s -p 5433 travis &>/dev/null
$ sudo -u postgres createdb -O travis -p 5433 travis &>/dev/null
```

travis.yml
```
language: node_js

sudo: false

addons:
  postgresql: "9.4"
```

After that our tests are able to communicate with the PG server, but types like `json` are missing so I would assume the default `9.1` is still running.

**Comment by BanzaiMan** [comment]
Do you have an example build log URL that shows this problem? How often (75%? 50%? 25%?) does it fail?

**Comment by johanneswuerbach** [comment]
> Do you have an example build log URL that shows this problem?
At the moment not, as we usually retry those builds.
> How often (75%? 50%? 25%?) does it fail?
Hard to say, but Thursday it was nearly every 2nd build.

**Comment by BanzaiMan** [comment]
Hmm. That's bad. If you see it next time, could you preserve it?

**Comment by harriha** [comment]
I've started to run into this occasionally as well lately, seeing one such build right now. @BanzaiMan, I can provide the full log privately if needed.

**Comment by abrom** [comment]
Hi @BanzaiMan, we're also seeing this. I have kept the failed job (not restarted). Job id `23854664`. Let me know if you need any more info.

**Comment by BanzaiMan** [comment]
Thanks. I've looked at a couple of logs, and so far, the only common property that I've found is that they are on container infrastructure. Has anyone seen anything like this outside of `sudo: false`?

**Comment by johanneswuerbach** [comment]
No, I haven't

**Comment by 21croissants** [comment]
Same here. Running with 

```yaml
sudo: false 
language: ruby
rvm:
  - 2.1.5
cache: bundler
bundler_args: --retry 3 --jobs 2 --without development heroku staging preprod production
before_script:
- cp -n config/database.yml.sample config/database.yml
- bundle exec rake db:create db:migrate RAILS_ENV=$RAILS_ENV
script: $XVFB bundle exec rake ci:$RAKE_TASK
addons:
  postgresql: "9.4"
```

I can give you more details. Shall I contact support too?
