### ISSUE TITLE
OSX D support

### ISSUE THREAD

**Issue by SingingBush** [travis-ci/travis-ci#4721]
@MartinNowak, @klickverbot, @ibuclaw
I've added osx to the os list in my `travis.yml` but it still only builds on Ubuntu. Is there any plan to get dmd and dub onto OSX?

I'm hoping to be able to do:

```
language: d

d:
 - dmd
 - ldc

os:
 - linux
 - osx

matrix:
  allow_failures:
    - os: osx
```
