### ISSUE TITLE
matrix.include defaults to `linux` for `os` value

### ISSUE THREAD

**Issue by jayvdb** [travis-ci/travis-ci#4731]
Builds with `os: osx` and `language: python` start Linux builds if they are in `matrix: include:`.  See builds 9-19 of https://travis-ci.org/jayvdb/pywikibot-core/builds/78131369

(The first 8 builds are from `env: matrix:`)

The relevant `.travis.yml` parts of

``` yaml
language: python

sudo: false

python:
  - '2.7'
  - '3.3'
  - '3.4'
  - '2.6'

os:
  - osx

addons:
  apt:
    packages:
      - python-ipaddr

...

env:
  matrix:
    - FOO=1
    - FOO=0

matrix:
  include:
    - python: '3.3'
```

(originally reported as part of https://github.com/travis-ci/travis-ci/issues/4729 )
