### ISSUE TITLE
Only deploying on certain builds

### ISSUE THREAD

**Issue by jakesyl** [travis-ci/travis-ci#4784]
Here's my ```.travis.yml``` file: 

```yaml
language: php
php:
  - 5.5
  - 5.6
  - hhvm
  - nightly
  - 5.3
  - 5.4
 
matrix:
    allow_failures:
        - php: hhvm
        - php: nightly
        - php: 5.3
        - php: 5.4
    fast_finish: true
before_install:
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=Admin
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=Main
install:
 - cd Admin && php composer.phar install && cd ..
 - cd Main && php composer.phar install && cd ..

script:
 - ls
 - pwd

before_deploy:
 - rm -rf Admin/vendor/
 - rm -rf Main/vendor/
 - find .  -type f -exec sed -i 's/\/var\/www\/html/./g' {} +
 - composer update
 - git rm --cached vendor/; return 0

deploy:
  skip_cleanup: true
  provider: heroku
  api_key: "APIKEY"
  app : APP
  run: restart
```
The problem with this is it redeploys every time, rather than only deploying once, on say version php 5.5.  Is there anyway to only make it deploy at the end of all builds or, say only one build.

Thanks!
