### ISSUE TITLE
`travis setup pypi` to do wheel distributions

### ISSUE THREAD

**Issue by peterbe** [travis-ci/travis-ci#4793]
I often run `travis setup pypi` and it produces something like this on my `.travis.yml`:
```
deploy:
  provider: pypi
  user: peterbe
  password:
    secure: eV46DAh+a4chCo...
  on:
    repo: peterbe/myproject
```

It awesome! But every time, I have to manually go in and add:
```
    distributions: "sdist bdist_wheel"
```
This extra addition makes sure to tell travis to build it as a Python wheel as well as a regular tarball. 
It should be an additional question to the travis cli tool. E.g. "Create a Python wheel file as well?" And this output is all you need.
