### ISSUE TITLE
Bug: on `tags: true` deploys, `$TRAVIS_BRANCH` is set to the tag name instead of the branch

### ISSUE THREAD

**Issue by eteubert** [travis-ci/travis-ci#4802]
Example build: https://travis-ci.org/eteubert/plugin-deployment-demo/builds/80370048 (tag and branch are echoed in the `Deploying Application` block):

```
Starting Build
Tag: 0.1-pre3
Branch: 0.1-pre3 # should be "master", there is no "0.1-pre3" branch
```

Example repo: https://github.com/eteubert/plugin-deployment-demo

```yml
# .travis.yml
sudo: false
language: php
php:
  - 5.4

deploy:
  skip_cleanup: true
  provider: script
  script: bin/deploy.sh
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ (pre|alpha|beta|rc)[0-9]+$"
```

```bash
# bin/deploy.sh
echo "Starting Build"
echo "Tag: $TRAVIS_TAG"
echo "Branch: $TRAVIS_BRANCH"
# ... deploy code
```

/edit:

I realize that the initial git clone already specifies the tag as a branch. Why does it do that?

```bash
git clone --depth=50 --branch=0.1-pre3 https://github.com/eteubert/plugin-deployment-demo.git 
```
/edit2:

Oh, I see. `--branch` on clone also takes tags as an argument but leaves git in a detached HEAD state. I guess it's not really a Travis issue then. Just the `$TRAVIS_BRANCH` value is misleading.
