### ISSUE TITLE
Proposal: custom VM image for PRO users

### ISSUE THREAD

**Issue by darvin** [travis-ci/travis-ci#4825]
Say, there would be some area on Travis PRO site where you could create "custom VM" named `MY-CUSTOM-VM` and edit yaml:

```yaml
language: objective-c
osx_image: xcode6.4
sudo: true
install:
- brew install huge-application
- brew install another-huge-app
- brew install another-huge-app-that-needs-compilation-and-what-not
```

Then, in regular repo's that Travis PRO user can specify:

```yaml
custom_image: MY-CUSTOM-VM
script:
 - ./do-somework-that-depends-on-huge-apps-from-home-brew
```

Problem is, that currently our installation step takes eternity (an hour) and that stuff never changes. We dont want to abuse your service and wait eternity every build. From other hand, we dont want to deal with maintaining image ourselves (and I think its much easier to create image if you can do VM snapshot and preserve it)
