### ISSUE TITLE
Allowed Failures causing build failing error

### ISSUE THREAD

**Issue by jakesyl** [travis-ci/travis-ci#4826]
Hello,

Here's my .travis.yml file: 
```YAML
language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5.0b3"
  - "3.5-dev"
  - "nightly"

env:
  - JYTHON=true
  - JYTHON=false

before_install:
  - export JYTHON_URL='http://downloads.sourceforge.net/project/jython/jython/2.5.2/jython_installer-2.5.2.jar'
  - if [ "$JYTHON" == "true" ]; then wget $JYTHON_URL -O jython_installer.jar; java -jar jython_installer.jar -s -d $HOME/jython; export PATH=$HOME/jython:$PATH; fi

before_script: 
- if [ "$JYTHON" == "true" ]; then export PYTHON_EXE=jython; jython -c "print ''"; else export PYTHON_EXE=python; fi
- ls
- pwd

install:
- pip install -e .
- pip install -r requirements.txt

script:
- nosetests
- cd pytorrent && nosetests && cd ..
- python pytorrent/tests/unitest.py

matrix:
  - fast_finish:true 
  - allow_failures:
    - python 3.2
    - python 3.3
    - python 3.4
    - python 3.5.0b3
    - python 3.5-dev
    - python nightly
    - env JYTHON=true
```
In this build: https://travis-ci.org/jakesyl/pytorrent/builds/81117271, all the required passes are passing and it's still showing build failing.  Additionally, there is no "allowed failures" section.

**Comment by solarce** [comment]
The items in `allow_failures:`  need to be `key: value`, http://docs.travis-ci.com/user/customizing-the-build/#Rows-that-are-Allowed-to-Fail, and your items are **space** separated. 

If you change it to look like this it should work:

```
matrix:
  - fast_finish:true 
  - allow_failures:
    - python: 3.2
    - python: 3.3
    - python: 3.4
    - python: 3.5.0b3
    - python: 3.5-dev
    - python: nightly
    - env: JYTHON=true
```

**Comment by jakesyl** [comment]
@solarce, updated it to:

```YAML
language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5.0b3"
  - "3.5-dev"
  - "nightly"

env:
  - JYTHON=true
  - JYTHON=false

before_install:
  - export JYTHON_URL='http://downloads.sourceforge.net/project/jython/jython/2.5.2/jython_installer-2.5.2.jar'
  - if [ "$JYTHON" == "true" ]; then wget $JYTHON_URL -O jython_installer.jar; java -jar jython_installer.jar -s -d $HOME/jython; export PATH=$HOME/jython:$PATH; fi

before_script: 
- if [ "$JYTHON" == "true" ]; then export PYTHON_EXE=jython; jython -c "print ''"; else export PYTHON_EXE=python; fi
- ls
- pwd

install:
- pip install -e .
- pip install -r requirements.txt

script:
- nosetests
- cd pytorrent && nosetests && cd ..
- python pytorrent/tests/unitest.py

matrix:
  - fast_finish:true 
  - allow_failures:
    - python: 3.2
    - python: 3.3
    - python: 3.4
    - python: 3.5.0b3
    - python: 3.5-dev
    - python: nightly
    - env: JYTHON=true
```

I added the key value part and it's still not working: https://travis-ci.org/jakesyl/pytorrent/builds/81120265.  I don't know what you mean by space separated though.  Thanks for your help!

**Comment by BanzaiMan** [comment]
Please review your build matrix definition and the documentation: http://docs.travis-ci.com/user/customizing-the-build/#Rows-that-are-Allowed-to-Fail

```yaml
matrix: # matrix is a hash in YAML, not an array, so don't use `-`
  fast_finish: true # `fast_finish:true` is invalid here
  allow_failures:
    - python: 3.2
    - python: 3.3
    - python: 3.4
    - python: 3.5.0b3
    - python: 3.5-dev
    - python: nightly
    - env: JYTHON=true
```

**Comment by jakesyl** [comment]
oh alright!  Awesome I got it now, the matrix section was being dropped.  For anyone else with this issue, here's the working `.travis.yml` file:
```YAML
language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5.0b3"
  - "3.5-dev"
  - "nightly"

env:
  - JYTHON=true
  - JYTHON=false

before_install:
  - export JYTHON_URL='http://downloads.sourceforge.net/project/jython/jython/2.5.2/jython_installer-2.5.2.jar'
  - if [ "$JYTHON" == "true" ]; then wget $JYTHON_URL -O jython_installer.jar; java -jar jython_installer.jar -s -d $HOME/jython; export PATH=$HOME/jython:$PATH; fi

before_script: 
- if [ "$JYTHON" == "true" ]; then export PYTHON_EXE=jython; jython -c "print ''"; else export PYTHON_EXE=python; fi
- ls
- pwd

install:
- pip install -e .
- pip install -r requirements.txt

script:
- nosetests
- cd pytorrent && nosetests && cd ..
- python pytorrent/tests/unitest.py

matrix:
  fast_finish: true
  allow_failures:
    - python: 3.2
    - python: 3.3
    - python: 3.4
    - python: 3.5.0b3
    - python: 3.5-dev
    - python: nightly
    - env: JYTHON=true
```
