### ISSUE TITLE
Errors were encountered while processing: /var/cache/apt/archives/locales_2.19-20_all.deb

### ISSUE THREAD

**Issue by TheCycoONE** [travis-ci/travis-ci#4838]
Title says it, I am trying to use debian-sid source because I need sdl2.  This is my packages list:
```
addons:
  apt:
    sources:
      - debian-sid
    packages:
      - cmake
      - p7zip-full
      - build-essential
      - sshpass
      - lua5.2
      - lua-filesystem
      - luasocket
      - luarocks
      - doxygen
      - libsdl2-dev
      - libsdl2-mixer-dev
      - libfreetype6-dev
```

The build output can be seen here: https://travis-ci.org/CorsixTH/CorsixTH/builds/81502495

Due to this the packages did not install.
