### ISSUE TITLE
[Question] Better way to use packages in all build except other one

### ISSUE THREAD

**Issue by moylop260** [travis-ci/travis-ci#4845]
I have next case.

I have 3 builds that depends of packages `apt` but one don't need it (just pylint test).

The better way that I found was:
```
language: python

sudo: false
cache:
  apt: true
  directories:
    - $HOME/.pip-cache/

env:
  global:
    - LINT_CHECK=0 TESTS="0" VERSION="8.0"

matrix:
    include:
        - python: 2.7
          # I don't need extra packages in pylint checks build.
          env: LINT_CHECK=1

        - python: 2.7
          env: TESTS="1"
          addons:
            apt:
              sources:
                - pov-wkhtmltopdf
              packages:
                - expect-dev
                - python-lxml
                - python-simplejson
                - python-yaml
                - wkhtmltopdf

      - python: 2.7
          env: PHANTOM_TEST="1"
          addons:
            apt:
              sources:
                - pov-wkhtmltopdf
              packages:
                - expect-dev
                - python-lxml
                - python-simplejson
                - python-yaml
                - wkhtmltopdf

      - python: 2.7
          env: UNIT_TESTS="1"
          addons:
            apt:
              sources:
                - pov-wkhtmltopdf
              packages:
                - expect-dev
                - python-lxml
                - python-simplejson
                - python-yaml
                - wkhtmltopdf

virtualenv:
  system_site_packages: true

install:
  - ./install.sh

script:
  - ./script.sh

after_success:
  - ./after_success.sh
```

But I have that copy&paste all package lines.
What is the better way of create a similar configuration to use packages in all my build except in one?
