### ISSUE TITLE
Travis pypi deploy is unusable because it doesn't honor "distributions"

### ISSUE THREAD

**Issue by mriehl** [travis-ci/travis-ci#4849]
First things first, this is the relevant config part from my `.travis.yml`:

```yaml
deploy:
  provider: pypi
  user: pybuilder-travis
  distributions: "sdist"
  on:
    branch: master
    repo: pybuilder/pybuilder
```

It's just unusable, unfortunately, because travis does **not** honor the `distributions` section. It still uploads wheels (though I tell it not to), which are broken because they have the travis interpreter hardcoded in them (using `#!python` as shebang is not an option for me because it breaks basic unix rules).
