### ISSUE TITLE
Mac OS X builds won't cache

### ISSUE THREAD

**Issue by peterdemartini** [travis-ci/travis-ci#4869]
Our build of [gateblu-ui](https://github.com/octoblu/gateblu-ui) (Mac OS X) doesn't seem to be able to caching anything. I have tried the following caching configurations:

```yml
cache:
  bundler: true
  directories:
  - node_modules
  - build/cache
```
```yml
cache: bundler
``` 
```yml
cache:
  directories:
  - vendor/bundle
``` 

Nothing seems to work. I also never see anything in the [caches page](https://travis-ci.org/octoblu/gateblu-ui/caches)
