### ISSUE TITLE
Enabling docker service removes mysql command

### ISSUE THREAD

**Issue by johnktims** [travis-ci/travis-ci#4870]
Here's a PR showing the problem: https://github.com/johnktims/travis-docker-mysql/pull/2

I started with
```yml
script: mysql -e 'SELECT NOW()'
```
and got
```bash
$ mysql -e 'SELECT NOW()'
+---------------------+
| NOW()               |
+---------------------+
| 2015-10-01 00:53:52 |
+---------------------+
```
so I added
```yml
services:
  - docker
sudo: required
```
and the build fails with
```bash
$ mysql -e 'SELECT NOW()'
/home/travis/build.sh: line 41: mysql: command not found
The command "mysql -e 'SELECT NOW()'" exited with 127.
```

**Comment by BanzaiMan** [comment]
Thanks for opening the issue. We are aware of this problem, and we will look into it.

In the meantime, you can us `sudo` to install MySQL as you wish.

**Comment by johnktims** [comment]
Will do. Thanks for the quick reply!

**Comment by inodb** [comment]
I'm having a problem with this as well. We're running some end-to-end tests that use docker and a bunch of other tests that use the old mysql service (they're called core tests for whatever reason). I can't however seem to combine them. It's either the end-to-end tests work when I enable the docker service, or the core tests work when I enable the mysql service. Tried a bunch of different things: https://github.com/cBioPortal/cbioportal/pull/1278. I tried the following:

- Set sudo required to true. This way I can install mysql, but somehow it gives me buffer overflow errors when using openjdk7 and running the core tests. It does seem to work with other oraclejdk8 and some other jdk versions, but then somehow all the core tests fail. Maybe they only work for a specific version of jdk? Is that possible?
- Use mysql docker container. Even though this works locally, on Travis I get the error: https://travis-ci.org/cBioPortal/cbioportal/builds/132730182#L199-L216
- Try to start docker services manually using sudo on Travis. (no service found)
- You can run multiple workers if you set multiple environment variables or jdks, but unfortunately I can't get multiple workers with separate services enabled.

If anybody has a suggestion, let me know!

**Comment by matthewpflueger** [comment]
Here's my setup which works for me:

```yml
sudo: required

services:
  - mysql
  - docker

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

before_install:

install:
  - sudo rm -Rf /var/lib/apt/lists/*
  - sudo apt-get update -qq
  - sudo apt-get install -y mysql-server-5.6 mysql-client-5.6 mysql-client-core-5.6  # hack because the mysql service above never starts :(
```

Hope that helps...
