### ISSUE TITLE
Can't specify conditional Rust version for deploy hook

### ISSUE THREAD

**Issue by mthjones** [travis-ci/travis-ci#4878]
I have a project set up to build and test on Rust stable, beta and nightly (skipping failures). It also has a deploy script hook to upload the built docs on a successful build. However, because I'm testing on each Rust branch, it attempts to deploy 3 times. In this case it's not an issue, just inefficient. In other cases, it could be a significant issue.

The [Travis docs](http://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A) state that you can already specify a single version for other languages.

Ideally, it would look something like:

```yaml
deploy:
  provider: script
  script: do-something.sh
  skip_cleanup: true
  on:
    tags: true
    rust: stable
```
