### ISSUE TITLE
<Foundation/Foundation.h> not found

### ISSUE THREAD

**Issue by Danappelxx** [travis-ci/travis-ci#4903]
In my build, Travis is not detecting Foundation (the framework upon which OS X itself is built on).

Here's the build: https://travis-ci.org/Mast-Swift/MastCLI/builds/84435737

and here's my .travis.yml file:
```yaml
language: objective-c
osx_image: xcode7
before_install: brew update && brew install carthage
install: carthage build
script: ./build
```

where the Carthage frameworks are already checked out as submodules (error occurs even if they aren't) and the build script is simply
```bash
# equivalent of `find src/**/*.swift`, but in regex
files=$(find src -regex '.*[^/]swift')
# compile files
swiftc $files -F Carthage/Build/Mac/ -o bin/mast
# Link frameworks through rpath
install_name_tool -add_rpath "@executable_path/../Carthage/Build/Mac/" "bin/mast"
```

I realize that this is a build error (so it might not belong here), but it seems like something to do with Travis considering how Foundation should be on every machine that has Xcode.
