### ISSUE TITLE
Slack notifier not respecting `on_success: change`

### ISSUE THREAD

**Issue by meatballhat** [travis-ci/travis-ci#4905]
We've received reports that the Slack notifier is not respecting the following configuration, instead notifying for successful builds in series:

``` yaml
notifications:
  slack:
    # .... other bits
    on_success: change
```

**Comment by rnicholus** [comment]
I wonder if the key to reproducing this is the presence of an encrypted key, for example:

```yaml
notifications:
  slack:
    on_success: change
    secure: ...
```

**Comment by meatballhat** [comment]
@rnicholus is that what your config looks like?  Because I would have expected `secure:` to be an entry in the `rooms:` array, a la:

``` yaml
notifications:
  slack:
    on_success: change
    rooms:
    - secure: ...
```
