### ISSUE TITLE
Alamofire builds are unstable on the Xcode7 image

### ISSUE THREAD

**Issue by cnoon** [travis-ci/travis-ci#4913]
Prior to the `osx_image: xcode7` release, the Alamofire builds were quite stable. We are now getting a slew of random timeout failures without changing the test suite in really any way. Therefore, I was hoping to rope in the experts to possibly lead us in the right direction. Here's the error message we're now getting sporadically on various builds of the device matrix:

> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Any feedback you could provide would be VERY helpful. We don't see any of this behavior when running locally. This [build](https://travis-ci.org/Alamofire/Alamofire/jobs/84682816) is a good example of what we're now seeing.

Here is our full yaml file.

```yaml
language: objective-c
osx_image: xcode7
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  matrix:
    - DESTINATION="OS=8.1,name=iPhone 4S" SCHEME="Alamofire iOS" SDK=iphonesimulator9.0 BUILD_EXAMPLE="YES" POD_LINT="YES"
    - DESTINATION="OS=8.2,name=iPhone 5" SCHEME="Alamofire iOS" SDK=iphonesimulator9.0 BUILD_EXAMPLE="YES" POD_LINT="NO"
    - DESTINATION="OS=8.3,name=iPhone 5S" SCHEME="Alamofire iOS" SDK=iphonesimulator9.0 BUILD_EXAMPLE="YES" POD_LINT="NO"
    - DESTINATION="OS=8.4,name=iPhone 6" SCHEME="Alamofire iOS" SDK=iphonesimulator9.0 BUILD_EXAMPLE="YES" POD_LINT="NO"
    - DESTINATION="OS=9.0,name=iPhone 6 Plus" SCHEME="Alamofire iOS" SDK=iphonesimulator9.0 BUILD_EXAMPLE="YES" POD_LINT="NO"
    - DESTINATION="arch=x86_64" SCHEME="Alamofire OSX" SDK=macosx10.11 BUILD_EXAMPLE="NO" POD_LINT="NO"
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - open -b com.apple.iphonesimulator
  - xcodebuild -version
  - xcodebuild -project Alamofire.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" 
    -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
  - xcodebuild -project Alamofire.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" 
    -configuration Release ONLY_ACTIVE_ARCH=NO test | xcpretty -c
  - if [ $BUILD_EXAMPLE == "YES" ]; then 
      xcodebuild -project "iOS Example.xcodeproj" -scheme "iOS Example" -sdk "$SDK" -destination "$DESTINATION" 
      -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c; 
    fi
  - if [ $BUILD_EXAMPLE == "YES" ]; then 
      xcodebuild -project "iOS Example.xcodeproj" -scheme "iOS Example" -sdk "$SDK" -destination "$DESTINATION" 
      -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c; 
    fi
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint --quick;
    fi

```
