### ISSUE TITLE
wishlist: support "matrix: include: ..." for one-off configurations

### ISSUE THREAD

**Issue by njsmith** [travis-ci/travis-ci#493]
There are some cases where it'd be convenient to add a one-off configuration to the build matrix. For example, suppose we have a python library that depends on numpy, and are running tests with a matrix like:

``` yaml
python:
 - 2.5
 - 2.6
 - 2.7
env:
 - NUMPY_VERSION=1.4
 - NUMPY_VERSION=1.5
 - NUMPY_VERSION=next-release
```

And then it is announced that the next version of numpy is finally going to support python 3.2, so we want to add this to our matrix and be ready to support 3.2 ourselves once numpy 1.6 is released. But we can't test other versions of numpy against 3.2... it'd be possible to handle this using matrix: exclude:, but more convenient via "matrix: include:" (and the convenience factor grows for more complicated matrices).

This has been discussed on the list some:
 https://groups.google.com/forum/#!msg/travis-ci/hFJXHZ22zqU/-MDLuIcdB2IJ
but I didn't want it to get lost, so, here's an issue!
