### ISSUE TITLE
Error from Renderer Running Dart Tests with Content Shell

### ISSUE THREAD

**Issue by daftspaniel** [travis-ci/travis-ci#4933]
[ CCing  @a14n @devoncarew and @sethladd as requested ]

I am trying to run a set of Dart Unit tests using the content shell.

I am receiving the following error running from the audio server. I don't think it is specific to a test though I do use (but not load or play) AudioElement at one point.

│ [3494:3494:1013/182422:20586486284:INFO:audio_manager_pulse.cc(258)] Failed to connect to the context.  Error: Connection refused

The full test log is here
https://travis-ci.org/daftspaniel/simplegamelib/jobs/85178095

**Comment by daftspaniel** [comment]
Ah this looks like the real error:
[3514:3514:1013/182422:20586582812:ERROR:renderer_main.cc(207)] Running without renderer sandbox

**Comment by a14n** [comment]
You are using the `test` package but the current default travis build was built for `unittest` package.

There's an open PR to support the test package (travis-ci/travis-build#525) but it has not yet landed.

Meanwhile you can add the following content to your `.travis.yml`:

```yaml
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: pub run test -p vm -p content-shell -p firefox
```
