### ISSUE TITLE
trusty + python 2.7 + numpy: undefined symbol: PyUnicodeUCS2_FromUnicode

### ISSUE THREAD

**Issue by nschloe** [travis-ci/travis-ci#4948]
When using numpy with `dist: trusty` and Python 2.7, I'm getting errors of the kind

```
undefined symbol: PyUnicodeUCS2_FromUnicode
```

see https://travis-ci.org/nschloe/matplotlib2tikz/jobs/85524916. Python 3 builds from the same source work fine. Searching this error message on Google [hints](http://numpy-discussion.10968.n7.nabble.com/Got-quot-undefined-symbol-PyUnicodeUCS2-FromUnicode-quot-error-td18721.html) that numpy was compiled with a different version of Python than the one used currently.

**Comment by moylop260** [comment]
I have the same issue here:
https://travis-ci.org/Vauxoo/runbot-addons/jobs/86130240
With next .travis.yml file:
https://github.com/vauxoo-dev/runbot-addons/blob/9.0-vauxoo-fix-travis/.travis.yml

```yaml
language: python

python:
  - "2.7"

cache: pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-dev
      - python-lxml  # because pip installation is slow
      - python-numpy
      - python-simplejson
      - python-serial
      - python-matplotlib  # For runbot badges

sudo: required  # Required for docker
services:
  - docker

env:
  global:
  - VERSION="8.0" TESTS="0" LINT_CHECK="0"
  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - pip install gitlab3 docker-py travis2docker
  - pip install --upgrade numpy
  - python -c "import numpy.core.numeric"  # testing numpy
```
