### ISSUE TITLE
"Code Sign error" when using `xcode_sdk`

### ISSUE THREAD

**Issue by kgn** [travis-ci/travis-ci#4961]
I'm trying to build and test my framework with multiple SDKs, but the following `.travis.yml` file is failing due to: `Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) were found.`.

I've tried to look around and read the docs but can't seem to find a solution.

``` yml
language: objective-c
osx_image: xcode7

xcode_project: KGNColor.xcodeproj
xcode_scheme: KGNColor

env:
  matrix:
    - xcode_sdk: iphonesimulator8.0
    - xcode_sdk: iphonesimulator8.1
    - xcode_sdk: iphonesimulator8.2
    - xcode_sdk: iphonesimulator8.3
    - xcode_sdk: iphonesimulator8.4
    - xcode_sdk: iphonesimulator9.0
```
