### ISSUE TITLE
Mongodb service logging flood

### ISSUE THREAD

**Issue by EppO** [travis-ci/travis-ci#4963]
In this [build](https://travis-ci.org/RolifyCommunity/rolify/jobs/85782524), it looks like the mongodb service writes in the standard output that travis displays but then it logs all queries the test suite makes which busts easily the 4MB log size limit. 
It's not consistent with SQLite for example which doesn't log all the queries. Or at least, is there a flag to disable the mongodb service logs?

**Comment by BanzaiMan** [comment]
I believe we are using the default configuration for MongoDB, which should log to `/var/log/mongodb.log`. Could you double check your mongoid configuration to see where the log output is going? I also see that the log includes DEBUG output, which should not be the default.

**Comment by EppO** [comment]
Here is the content of the `mongoid.yml` file loaded by the specs suite:
```yaml
test:
  clients:
    default:
      logger: false
      database: godfather
      hosts:
        - localhost:27017
```
`logger: false` didn't change anything
