### ISSUE TITLE
`OS=9.0,name=iPhone 6 Plus` not working with `osx_image: xcode7.1`

### ISSUE THREAD

**Issue by kgn** [travis-ci/travis-ci#5001]
I updated my `.travis.yml` file to `osx_image: xcode7.1` and added `iOS 9.1` destinations. They are working, but now my `OS=9.0,name=iPhone 6 Plus` destination is failing with the error: `Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Simulator with name "iPhone 6 Plus" doesn't have configuration with sdk version "9.0".`

All of the other destination in my matrix are working, it's just the `iOS 9.0` that is running in to issue, and use to work with `osx_image: xcode7`

https://travis-ci.org/kgn/KGNAutoLayout

``` yml
language: objective-c
osx_image: xcode7.1

env:
  global:
  - PROJECT=KGNAutoLayout
  - SCHEME=$PROJECT
  matrix:
    - DESTINATION="OS=8.1,name=iPhone 4s"
    - DESTINATION="OS=8.2,name=iPhone 5"
    - DESTINATION="OS=8.3,name=iPhone 5s"
    - DESTINATION="OS=8.4,name=iPhone 6"
    - DESTINATION="OS=9.0,name=iPhone 6 Plus"
    - DESTINATION="OS=9.1,name=iPhone 6s"
    - DESTINATION="OS=9.1,name=iPhone 6s Plus"    

script: 
  - xctool clean test -project "$PROJECT.xcodeproj" -scheme "$SCHEME" -sdk iphonesimulator -destination "$DESTINATION"
```
