### ISSUE TITLE
GitHub releases: Skipping a deployment with the releases provider because this is not a tagged commit

### ISSUE THREAD

**Issue by voltagex** [travis-ci/travis-ci#5026]
I apologise as this is probably a duplicate but I'm getting `Skipping a deployment with the releases provider because this is not a tagged commit` at the end of a very long build and I'm not sure what I'm doing wrong

My travis.yml:

```
sudo: false
language: bash
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/src"
addons:
  apt:
    packages:
    - bison
    - flex
    - gperf
    - libncurses5-dev
    - texinfo
install:
- if [ ! -d 'crosstool-ng' ]; then git clone --depth=1 git://github.com/crosstool-ng/crosstool-ng;
  fi
- pushd crosstool-ng
- "./bootstrap"
- "./configure --enable-local"
- make
env:
- MY_TARGET=armv7-rpi2-linux-gnueabihf
- MY_TARGET=armv6-rpi-linux-gnueabi
script:
- ". ./.travis.sh"
- ct-ng $MY_TARGET
- ct-ng_travis_build
- popd
after_failure:
- tail -n 1000 build.log
before_deploy: "./pack_for_release.sh $MY_TARGET"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: 
  file: release/$MY_TARGET.tar.xz
  on:
    tags: true
    all_branches: true
```

What parameters do I actually need? I see a few issues from 2014 around this but nothing recent.
