### ISSUE TITLE
Wrong install place for ubuntu packages when native gem needed in new infrastrure

### ISSUE THREAD

**Issue by jreidinger** [travis-ci/travis-ci#5043]
Hi, let me briefly explain use case and problem.
I want to try new infrastructure based on docker, so I cannot use sudo. I have dependency on gem that need native C devel library. It is available in ubuntu.

So I use this `.travis.yml`:
```
language: ruby
rvm:
  - 2.2.3
  - 2.1.7
addons:
  apt:
    packages:
      libaugeas-dev
      pkg-config
# use new travis infrastructure
sudo: false
install: gem install rubocop rspec ruby-augeas
script:
    - rake spec
    - rubocop
```

but it failed, because addons are installed after install phase, which is too late for me. It should be done before as ubuntu package do not depend on gem, but other direction is common.

**Comment by BanzaiMan** [comment]
Could you point to a build log URL that shows this problem?

**Comment by jreidinger** [comment]
yes, of course.
For fail with new infrastructure it is e.g. https://travis-ci.org/jreidinger/config_files/jobs/88777778
when I revert it back to old one it is https://travis-ci.org/jreidinger/config_files/jobs/88780820 ( please ignore failure, it is just new project with other problems, but it shows problem, that with new infrastructure and using addons > apt install packages too late for installing gems.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/jreidinger/config_files/jobs/88777778#L75 shows that your packages are not installed because they are not correctly specified. You need an array in addons.apt.packages.

```yaml
addons:
  apt:
    packages:
      - libaugeas-dev
      - pkg-config
```
