### ISSUE TITLE
Allow branch specific whitelisting and blacklisting for after_success

### ISSUE THREAD

**Issue by gravyboat** [travis-ci/travis-ci#5065]
It would be great if I could have whitelisting and blacklisting for `after_success` like this:

```
after_success:
  branches:
    only:
      - master
      - test
      - dev
  - docker login .....
  - docker push blah/blah
```

The use case is for when someone makes a PR with their branch I don't want to do a docker push until AFTER the merge is approved when the second Travis build occurs onto the main branch.
