### ISSUE TITLE
`ARTIFACTS_TARGET_PATHS` does not works properly on Uploading Artifacts

### ISSUE THREAD

**Issue by suzuken** [travis-ci/travis-ci#5070]
Based on documentation of [travis-ci/artifacts](https://github.com/travis-ci/artifacts), `ARTIFACTS_TARGET_PATHS` provides functionality of specify location for uploading artifacts. But it seems not works on our environment.

Reading [Uploading Artifacts on Travis CI - Travis CI](http://docs.travis-ci.com/user/uploading-artifacts/), and I wrote .travis.yml is like that.

```yaml
sudo: false

language: go

go:
  - 1.5.1

before_install:
  - go get github.com/mattn/gom

install: make install

script:
  - make test
  - make build
env:
  - ARTIFACTS_TARGET_PATHS=artifacts/$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH ARTIFACTS_BUCKET=our-artifacts

addons:
  artifacts:
    paths:
      - $(git ls-files -o --exclude-standard | tr "\n" ":")
    debug: true
  s3_region: "ap-northeast-1"
```

The job is successfully passed. But artifacts is not uploaded to `s3://our-artifacts/artifacts/$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH`.

It seems `ARTIFACTS_TARGET_PATHS=artifacts/$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH` not works properly. The job uploads artifacts under the S3 path kind of `$TRAVIS_REPO_SLUG/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER`. (for example, `s3://our-artifacts/our-organization-name/our-repo-name/15/15.1/path/to/artifacts` )
