### ISSUE TITLE
Allow connecting the IRC bot using SSL

### ISSUE THREAD

**Issue by Mikaela** [travis-ci/travis-ci#5093]
Judging by [the documentation](http://docs.travis-ci.com/user/notifications/#IRC-notification) it seems that this isn't possible at the moment. As plain text IRC is supposed to be phased out (like http) I would like everyone and everything to connect to IRC using SSL. Some channels also block plaintext connections entirely (trusting the users to validate SSL certificates etc. (even if it most likely doesn't happen)).

What I think should be done is allowing more formats for the notifications:

```yml
notifications:
    irc:
      channels:
            # Connect to irc.freenode.net in plain text and send the notifications to #channel
            - irc://irc.freenode.net:6667/#channel
            # Connect to irc.freenode.net using TLS and send the notifications to #channel2
            - ircs://irc.freenode.net:6697/#channel2
```

This is the standard syntax which every IRC client also uses for irc/ircs links.
