### ISSUE TITLE
Innosetup in container-based infrastructure

### ISSUE THREAD

**Issue by nripendra** [travis-ci/travis-ci#5110]
I'm trying to create installer using innosetup inside travis-ci. My understanding is that it requires wine. Is it at all possible using container-based infrastructure?

**Comment by nripendra** [comment]
Got it working with following code in .travis.yml:

```yaml
addons:
  apt:
    packages:
    - wine
```
