### ISSUE TITLE
Allow failures with Python version

### ISSUE THREAD

**Issue by ZuluPro** [travis-ci/travis-ci#5113]
I'm building the following configuration:

```yaml
language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

env:
  - RL=24
  - RL=25
  - RL=26
  - RL=27
  - RL=30
  - RL=31
  - RL=32

matrix:
  fast_finish: true
  allow_failures:
    - python: 3.3
    - python: 3.4
    - python: 3.5

install:
    - TOX_ENV=py${TRAVIS_PYTHON_VERSION}-rl${RL}
    - pip install tox

script:
    - tox -e $TOX_ENV

notifications:
  irc: "chat.freenode.net#xhtml2pdf"
```

Unfortunately the allowed failures aren't. I would like to allow failures with all specified Python versions independently from ``env``.

Exemple of result here: https://travis-ci.org/ZuluPro/xhtml2pdf/builds/91178168

**Comment by BanzaiMan** [comment]
Your `python` keys are in Strings, while you are trying to allow failures with numeric values. Aligning them to consistent values should achieve what you want.

**Comment by ZuluPro** [comment]
You've right ! Thank a lot !

**Comment by marscher** [comment]
I'm having the same "issue" here: https://github.com/originell/jpype/pull/165/files

Even after declaring the same type of the build-matrix elements (strings), travis still reports failure for allowed rows.

@BanzaiMan would be nice, if you could take a look. Thanks a lot!

**Comment by BanzaiMan** [comment]
@marscher Try specifying `NUMPY` as well.

```yaml

  allow_failures:
    - python: 'pypy'
      env: NUMPY="--install-option=--disable-numpy"
    - python: 'pypy3'
      env: NUMPY=""
```
