### ISSUE TITLE
erlang build failures using rebar on R14 only

### ISSUE THREAD

**Issue by andytill** [travis-ci/travis-ci#5119]
erlang rebar builds are failing on R14 only, R15 is fine. The build uses the following erlang language yml file:

```yml
language: erlang
notifications:
  webhooks: http://basho-engbot.herokuapp.com/travis?key=be744efd0a393f30d77d2e0076c8456be272e209
  email: eng@basho.com
otp_release:
  - R15B01
  - R15B
  - R14B04
  - R14B03
```
The failure is for PR https://github.com/basho/riak_kv/pull/1268 and the build is at https://travis-ci.org/basho/riak_pb/builds/90661022.

The error message is:

```
=ERROR REPORT==== 12-Nov-2015::04:18:43 ===

Loading of /home/travis/build/basho/riak_pb/rebar/rebar/ebin/rebar.beam failed: badfile

escript: exception error: undefined function rebar:main/1

  in function  escript:run/2

  in call from escript:start/1

  in call from init:start_it/1

  in call from init:start_em/1

=ERROR REPORT==== 12-Nov-2015::04:18:43 ===

beam/beam_load.c(1365): Error loading module rebar:

  use of opcode 153; this emulator supports only up to 152

The command "eval ./rebar get-deps" failed. Retrying, 3 of 3.

=ERROR REPORT==== 12-Nov-2015::04:18:44 ===

Loading of /home/travis/build/basho/riak_pb/rebar/rebar/ebin/rebar.beam failed: badfile

escript: exception error: undefined function rebar:main/1

  in function  escript:run/2

  in call from escript:start/1

  in call from init:start_it/1

  in call from init:start_em/1

=ERROR REPORT==== 12-Nov-2015::04:18:44 ===

beam/beam_load.c(1365): Error loading module rebar:

  use of opcode 153; this emulator supports only up to 152

The command "eval ./rebar get-deps" failed 3 times.
```

We have temporarily removed R14 builds as a workaround.
