### ISSUE TITLE
OSX maven build marked as failed, but exit status = 0

### ISSUE THREAD

**Issue by krzyk** [travis-ci/travis-ci#5120]
Here's and example https://magnum.travis-ci.com/teamed/xockets-hadoop-transport/jobs/27354580

All of the scripts report exit status 0, but the build is still marked as failed, why?

.travis.yml looks like this:
```
language: java
sudo: false
os:
  - linux
  - osx
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=2g -Xmx4g"
    - JAVA_OPTS="-XX:MaxPermSize=2g -Xmx4g"
addons:
  apt:
    packages:
      - libmagic1
      - libmagic-dev
before_install:
  - ssh-keygen -t dsa -P '' -f ~/.ssh/id_dsa
  - cat ~/.ssh/id_dsa.pub >> ~/.ssh/authorized_keys
  - printf '%s\n\t%s\n\t%s\n' 'Host *' 'StrictHostKeyChecking no' 'UserKnownHostsFile=/dev/null' >> ~/.ssh/config
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export JAVA_HOME="$(/usr/libexec/java_home)"; brew update >/dev/null; brew install libmagic; fi
install:
  - mvn install -DskipTests -Dinvoker.skip
script:
  - set -e
  - ARCHFLAGS="-arch x86_64" gem install pdd
  - mvn clean
  - pdd --source=$(pwd) --verbose --file=/dev/null
  - mvn clean install -Pqulice,cobertura,travis --batch-mode --errors
```
