### ISSUE TITLE
Allow per-webhook conditions

### ISSUE THREAD

**Issue by rmzelle** [travis-ci/travis-ci#5121]
Our repository relies on multiple webhooks to tie in various downstream processes. It would be very convenient if we could set separate conditions for each webhook. E.g. instead of

```
notifications:
  webhooks:
    urls:
      - https://example.com:8826/
      - https://example.com:8827/
    on_success: always
```

I'd like to be able to specify

```
notifications:
  webhooks:
    urls:
      - https://example.com:8826/
          on_success: always
      - https://example.com:8827/
          on_success: change
```
