### ISSUE TITLE
MySQL 5.7 support

### ISSUE THREAD

**Issue by Ramoonus** [travis-ci/travis-ci#5122]
Currently travis allows mysql-5.7-dmr as a database format
but it`s been released as GA for production use, so the DMR part is invalid

**Comment by BanzaiMan** [comment]
I am not quite sure what you mean by

> Currently travis allows mysql-5.7-dmr as a database format

Could you elaborate?

**Comment by Ramoonus** [comment]
i can use MySQL-5.7-dmr as a database
but not yet mysql-5.7

**Comment by BanzaiMan** [comment]
Ah. Development Milestone Release. I don't think we plan to support such non-GA releases out of the box. If you want to use it, please use Trusty, and run `sudo` to bend the builds to your will.

We will eventually support MySQL 5.7, but not with DMR.

**Comment by Ramoonus** [comment]
it has been GA for about a month now

**Comment by BanzaiMan** [comment]
So "DMR" doesn't apply any more, right?

**Comment by Ramoonus** [comment]
correct

**Comment by half2me** [comment]
Please let us use 5.7

**Comment by winzou** [comment]
MySQL 5.7 GA has been released on the 21st Oct 2015, it's been a few months now.
What is the status for allowing us to use it in our Travis builds?
It's a blocking point here :-/ Thanks!

**Comment by winzou** [comment]
Hi @BanzaiMan, could you please tell us if this is on your roadmap or not? In case it is, what's the ETA?
We need to move forward on our side, and we can't take any decision for now as we don't have information.
Thanks for your help!

**Comment by half2me** [comment]
@winzou +1

**Comment by Grynn** [comment]
+1  Plz

**Comment by dannyyu92** [comment]
+1

**Comment by LeanderK** [comment]
+1

**Comment by BanzaiMan** [comment]
The following will install necessary packages to install 5.7:

```yaml
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - libmysqlclient-dev
      - libmysqlclient20
      - mysql-community-client
      - mysql-common
      - mysql-community-server
```

See https://travis-ci.org/BanzaiMan/travis_production_test/builds/325208436#L564
