### ISSUE TITLE
Cannot start a android-23 emulator image

### ISSUE THREAD

**Issue by joshkergan** [travis-ci/travis-ci#5158]
This is the commands I use to run the android emulator

```yaml
before_install:
    - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &


before_script:
    - android-wait-for-emulator
    - adb shell input keyevent 82 &
```
It would always print the following message before timing out:
```
$ android-wait-for-emulator
emulator: WARNING: Increasing RAM size to 1GB
Waiting for emulator to start
Creating filesystem with parameters:
    Size: 576716800
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 7040
    Inode size: 256
    Journal blocks: 2200
    Label: 
    Blocks: 140800
    Block groups: 5
    Reserved block group size: 39
Created filesystem with 11/35200 inodes and 4536/140800 blocks
NAND: could not write file /home/travis/.android/avd/test.avd/userdata-qemu.img, No such file or directory
```
