### ISSUE TITLE
[trusty] PostgreSQL 9.4 missing postgis 

### ISSUE THREAD

**Issue by johanneswuerbach** [travis-ci/travis-ci#5178]
When trying to use postgis with PostgreSQL 9.4 I receive the following error:

`could not open extension control file "/usr/share/postgresql/9.4/extension/postgis.control": No such file or directory`

The build works fine when using `precise`.

**Comment by carhartl** [comment]
I second the need for fixing this :)

**Comment by carhartl** [comment]
I can't use the precise dist as I also need the docker service.

**Comment by johanneswuerbach** [comment]
@carhartl I use the following workaround for now:
```
sudo: required
dist: trusty
 
 addons:
   postgresql: "9.4"
  apt:
    packages:
      - postgresql-9.4-postgis-2.1 # Workaround https://github.com/travis-ci/travis-ci/issues/5178
```

Works like a :gem:
