### ISSUE TITLE
Opt-out of Mono in CSharp environment

### ISSUE THREAD

**Issue by natemcmaster** [travis-ci/travis-ci#5189]
Setting `language: csharp` installs [mono by default](https://github.com/travis-ci/travis-build/blob/928f387239d81eac92808969e0ab58e19c27397c/lib/travis/build/script/csharp.rb#L11). With growing support for [CoreCLR](http://dotnet.github.io/) on Linux, Mono is not always necessary or desirable. It is currently [not possible](https://github.com/travis-ci/travis-build/blob/928f387239d81eac92808969e0ab58e19c27397c/lib/travis/build/script/csharp.rb#L64) to opt-out of mono.

Example: [Entity Framework](https://travis-ci.org/aspnet/EntityFramework) tests a C# project and by design does not use Mono.

**Comment by natemcmaster** [comment]
cc @joshua-anderson @akoeplinger @nterry

**Comment by akoeplinger** [comment]
Yeah, we'll need to do something to support that use case. The question I have is with CoreCLR/.NET Core usually being acquired on demand, what would Travis need to do? Allow you to specify a specific version so you don't have to grab the installer yourself? Set up a matrix to test against both Mono and .NET Core?

Would love to hear how you'd like to use it :)

**Comment by natemcmaster** [comment]
The new x-plat dotnet is going to available via debian package (see https://github.com/dotnet/cli#installers). Having this installed (plus all its dependencies) ahead of time could save redundant installs. 

[dotnet](https://github.com/dotnet/cli) is under rapid development so version numbers represent nightly builds. When this settles, some users may be interested in a matrix of runtime versions.

You might be interested in checking out [the dotnet Docker image](https://github.com/dotnet/dotnet-docker/blob/master/0.0.1-alpha/Dockerfile). It's worth noting that dotnet is currenlyt only targeting trusty.

**Comment by natemcmaster** [comment]
One more thing:

> Set up a matrix to test against both Mono and .NET Core?

Yes, definitely interested in this so we could use the `allow_failures` to test Mono but not necessarily break on failures.

**Comment by nterry** [comment]
This is definitely an awesome idea. I wish we would have made the schema
more flexible from the start. Other languages allow for other runtimes, so
why not this language?

Of note, there is a Debian package for coreclr.

**Comment by akoeplinger** [comment]
@natemcmaster 
> The new x-plat dotnet is going to available via debian package (see https://github.com/dotnet/cli#installers).

The most important thing we need is a stable URL, I suppose that Azure blob url isn't guaranteed to not change. Maybe we can get a fwlink that points to the correct location like on get.asp.net?

@nterry I think we can just add a new `runtime` key.

**Comment by natemcmaster** [comment]
> The most important thing we need is a stable URL

@blackdwarf how "stable" is `http://apt-mo.trafficmanager.net/repos/dotnet/`?  (added in  https://github.com/dotnet/dotnet.github.io/commit/64316c19c50f1ed5a7c279e4d621f5568a84339d)

**Comment by nterry** [comment]
@akoeplinger :+1: to the runtime key.

**Comment by blackdwarf** [comment]
@natemcmaster sory for the late-ish reply, should be stable enough to use for this I think.

**Comment by natemcmaster** [comment]
There has been a lot of work since December. dotnet-cli is close to it's first release. It looks like the acquisition story has stabilized. Maybe time to consider this again?

https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/cli-installation-scenarios.md

**Comment by jasonwilliams200OK** [comment]
This can probably be supported via `runtime:` key (similar to Ant support via `install:` key for Java: https://docs.travis-ci.com/user/languages/java#Projects-Using-Ant):

```yml
language: csharp

runtime:
  - name: mono
    version: 4  # can be 4.4, 4.4.1, 4.4.1.0, latest or stable
# or
runtime:
  - name: netcore
    version: 1  # can be 1.0, 1.0.0, latest or stable
```

matrix-specific usage would look like:

```yml
language: csharp

matrix:
  include:
    - os: linux
      dist: trusty # Ubuntu 14.04
      sudo: required
      runtime:
        - name: mono
          version: 4
      env: CONFIGURATION=Debug
    - os: linux
      dist: trusty
      sudo: required
      runtime:
        - name: mono
          version: 4
      env: CONFIGURATION=Release
    - os: osx
      osx_image: xcode7.2 # macOS 10.11
      runtime: 
        - name: mono
          version: 4
      env: CONFIGURATION=Debug
    - os: osx
      osx_image: xcode7.2
      runtime:
        - name: mono
          version: 4
      env: CONFIGURATION=Release

    - os: linux
      dist: trusty # Ubuntu 14.04
      sudo: required
      runtime:
        - name: netcore
          version: 1
      env: CONFIGURATION=Debug
    - os: linux
      dist: trusty
      sudo: required
      runtime:
        - name: netcore
          version: 1
      env: CONFIGURATION=Release
    - os: osx
      osx_image: xcode7.2 # macOS 10.11
      runtime:
        - name: netcore
          version: 1
      env: CONFIGURATION=Debug
    - os: osx
      osx_image: xcode7.2
      runtime:
        - name: netcore
          version: 1
      env: CONFIGURATION=Release
```

Currently, we have https://github.com/nunit/dotnet-test-nunit/blob/9ef34e3/.travis.yml (without mono in martix at the moment). Note that the URLs were taken from https://www.microsoft.com/net/download#core from under `.NET Core SDK binaries only` column.
