### ISSUE TITLE
preinstalled PHPUnit is incompatible with preinstalled PHP 5.5

### ISSUE THREAD

**Issue by jadatkins** [travis-ci/travis-ci#5204]
We need [SASS](http://sass-lang.com/install) to compile our CSS before running Selenium tests.

Our image is this sort:

```yaml
language: php
php:
  - 5.5

services: mysql

group: dev

sudo: required

addons:
    sauce_connect: true
```

and we have, thus far, been installing SASS with

```sh
sudo apt-get install rubygems
gem install sass --no-ri --no-rdoc
```

but this now fails with

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package rubygems
```

Is there another way to install SASS?  Are the images still [based on Ubuntu 12.04](https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments)?

**Comment by jadatkins** [comment]
Ah, you've switched to Ubuntu 14. So I can install the package `ruby-sass` instead. But will that work on Ubuntu 12? ...

**Comment by jadatkins** [comment]
Yes, looks like the `ruby-sass` package is [available in Ubuntu 12.04](http://packages.ubuntu.com/search?keywords=ruby-sass&searchon=names&suite=precise&section=all) as well. So I'll just use that.

I'll leave the issue open in case this information is useful.

**Please be clear what OS your VMs are running!** I've said it before, because 98% of my problems with Travis CI so far have been due to this not being clear. The [750-word blog post](https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future) only mentions it in passing, and only by code name (Trusty vs. Precise) and I wouldn't know what the code names mean.

**Comment by jadatkins** [comment]
Sorry, I have another question.  I've just noticed the line

```yaml
group: dev
```

and I wondered what it did, since your [online validator](http://lint.travis-ci.org/) complains about it.  `git blame` tells me that it's to enable MySQL 5.6, which we still require.  Do we still need this line to use MySQL 5.6 on your new architecture?

**Comment by jadatkins** [comment]
I've just noticed the 'Build System Information' bit at the top of the logs.  It seems that we didn't have MySQL 5.6 in either the build that [automatically used your new architecture](https://travis-ci.com/Tutorfair/TutorfairWebsite/builds/18487099), nor the build where I [tried to test my fix manually](https://travis-ci.com/Tutorfair/TutorfairWebsite/builds/18525423).  I am now completely stuck.  For starters, we need MySQL 5.6 please, and secondly, I still don't know what caused either of the errors in these two builds, because the first of these claims to have been running on Ubuntu 12.04, contrary to what your blog post appears (?) to be saying, and the second just says MySQL isn't available at all.

**Comment by MariadeAnton** [comment]
Hey @jadatkins,

You can use MySQL 5.6 by routing your builds to our Ubuntu Trusty 14.04 infrastructure and get the required packages by adding the following to your .travis.yml: 

```
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
````

Could you try that out and let us know how it goes?

As a bit of explanation we currently have 3 different Linux infrastructures: https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments

* **Standard**, `sudo: required` `dist: precise`  - runs Ubuntu Precise 12.04 and is the one we're migrating to GCE, with the same config, Ubuntu Precise 12.04

* **Container-based**, `sudo:false` - runs Ubuntu Precise 12.04

* **Trusty Beta** , `sudo:required` `dist: trusty` - runs Ubuntu Precise 14.04 and is the one with MySQL 5.6

**Comment by jadatkins** [comment]
I'm still mystified as to what the `group:` setting does, but I guess I don't need it anymore? I'm trying without.

```yaml
language: php
php:
  - 5.5

sudo: required
dist: trusty

addons:
  sauce_connect: true
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

install:
  - ./travis-scripts/install.sh

before_script:
  - ./travis-scripts/before_script.sh

script:
  # Travis will keep trying later commands here even if an earlier command fails
  - make tests
  - ./travis-scripts/run_selenium_tests.sh
```
