### ISSUE TITLE
How do I get xunit to run tests for .net 4.5.2?

### ISSUE THREAD

**Issue by NullVoxPopuli** [travis-ci/travis-ci#5210]
per: C# support for Travis-CI is community maintained.
Please open any issues at https://github.com/travis-ci/travis-ci/issues/new and cc @joshua-anderson @akoeplinger @nterry

I'm having the hardest time figuring out how to get my tests to run on travis.

my repo: https://github.com/NullVoxPopuli/csharp-extensions
on travis: https://travis-ci.org/NullVoxPopuli/csharp-extensions

this is my travis.yml:

``` yml
language: csharp
solution: csharp-extensions.sln
install:
  - nuget restore csharp-extensions.sln
  - nuget install xunit.runners -Version 2.0.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release csharp-extensions.sln
  - mono ./testrunner/xunit.runners.2.0.0/tools/xunit.console.exe ./csharp-extensions-test/bin/Release/csharp-extensions-tests.dll
notifications:
  email: false
```

and the error I'm getting:

```
The command "xbuild /p:Configuration=Release csharp-extensions.sln" exited with 1.
$ mono ./testrunner/xunit.runners.2.0.0/tools/xunit.console.exe ./csharp-extensions-test/bin/Release/csharp-extensions-tests.dll
Cannot open assembly './testrunner/xunit.runners.2.0.0/tools/xunit.console.exe': No such file or directory.

The command "mono ./testrunner/xunit.runners.2.0.0/tools/xunit.console.exe ./csharp-extensions-test/bin/Release/csharp-extensions-tests.dll" exited with 2.

Done. Your build exited with 1.
```

Failing Build: https://travis-ci.org/NullVoxPopuli/csharp-extensions/builds/94955818
