### ISSUE TITLE
Errors with travis compile: "no implicit conversion of String into Integer" and "undefined method `jobs' for nil:NilClass"

### ISSUE THREAD

**Issue by Muffo** [travis-ci/travis-ci#5216]
I am trying to run `travis compile` on my Ubuntu VM, but I am running into the following two issues:

```
➜  openssl git:(master) travis compile
no implicit conversion of String into Integer
for a full error report, run travis report
➜  openssl git:(master) travis report 
System
Ruby:                     Ruby 2.1.5-p273
Operating System:         Ubuntu 15.10
RubyGems:                 RubyGems 2.0.3

CLI
Version:                  1.8.0
Plugins:                  "travis-build"
Auto-Completion:          yes
Last Version Check:       2015-12-05 11:07:44 +0000

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "Muffo"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)

Last Exception
An error occurred running `travis compile`:
    TypeError: no implicit conversion of String into Integer
        from /home/muffo/.travis/travis-build/init.rb:62:in `[]'
        from /home/muffo/.travis/travis-build/init.rb:62:in `sanitize_global_env'
        from /home/muffo/.travis/travis-build/init.rb:25:in `run'
        from /home/muffo/.gem/ruby/2.1.0/gems/travis-1.8.0/lib/travis/cli/command.rb:198:in `execute'
        from /home/muffo/.gem/ruby/2.1.0/gems/travis-1.8.0/lib/travis/cli.rb:64:in `run'
        from /home/muffo/.gem/ruby/2.1.0/gems/travis-1.8.0/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
➜  openssl git:(master) travis compile 1 
undefined method `jobs' for nil:NilClass
for a full error report, run travis report
➜  openssl git:(master) travis report   
System
Ruby:                     Ruby 2.1.5-p273
Operating System:         Ubuntu 15.10
RubyGems:                 RubyGems 2.0.3

CLI
Version:                  1.8.0
Plugins:                  "travis-build"
Auto-Completion:          yes
Last Version Check:       2015-12-05 11:07:44 +0000

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "Muffo"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)

Last Exception
An error occurred running `travis compile`:
    NoMethodError: undefined method `jobs' for nil:NilClass
        from /home/muffo/.travis/travis-build/init.rb:56:in `set_up_config'
        from /home/muffo/.travis/travis-build/init.rb:17:in `run'
        from /home/muffo/.gem/ruby/2.1.0/gems/travis-1.8.0/lib/travis/cli/command.rb:198:in `execute'
        from /home/muffo/.gem/ruby/2.1.0/gems/travis-1.8.0/lib/travis/cli.rb:64:in `run'
        from /home/muffo/.gem/ruby/2.1.0/gems/travis-1.8.0/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

Have I missed something in the installation?

Here is the `.travis.yml`:

```
language: c

addons:
    apt:
        packages:
            - clang-3.6
            - gcc-5
            - binutils-mingw-w64
            - gcc-mingw-w64
            - wine
        sources:
            - llvm-toolchain-precise-3.6
            - ubuntu-toolchain-r-test

os:
    - linux
    - osx

compiler:
    - clang
    - clang-3.6
    - gcc
    - gcc-5
    - i686-w64-mingw32-gcc
    - x86_64-w64-mingw32-gcc

env:
    - CONFIG_OPTS=""
    - CONFIG_OPTS="shared"
    - CONFIG_OPTS="no-asm"
    - CONFIG_OPTS="--debug --strict-warnings"

matrix:
    include:
        - os: linux
          compiler: clang-3.6
          env: CONFIG_OPTS="-fsanitize=address"
        - os: linux
          compiler: clang-3.6
          env: CONFIG_OPTS="no-asm --debug --strict-warnings -fno-sanitize-recover -fsanitize=address -fsanitize=undefined"
        - os: linux
          compiler: gcc-5
          env: CONFIG_OPTS="-fsanitize=address"
        - os: linux
          compiler: gcc-5
          env: CONFIG_OPTS="no-asm --debug --strict-warnings -fno-sanitize-recover -fsanitize=address -fsanitize=undefined"
    exclude:
        - os: osx
          compiler: clang-3.6
        - os: osx
          compiler: gcc-5
        - os: osx
          compiler: i686-w64-mingw32-gcc
        - os: osx
          compiler: x86_64-w64-mingw32-gcc
        - compiler: i686-w64-mingw32-gcc
          env: CONFIG_OPTS="shared"
        - compiler: x86_64-w64-mingw32-gcc
          env: CONFIG_OPTS="shared"
        - compiler: i686-w64-mingw32-gcc
          env: CONFIG_OPTS="no-asm"
        - compiler: x86_64-w64-mingw32-gcc
          env: CONFIG_OPTS="no-asm"
    allow_failures:
        - compiler: i686-w64-mingw32-gcc
          env: CONFIG_OPTS="--debug --strict-warnings"
        - compiler: x86_64-w64-mingw32-gcc
          env: CONFIG_OPTS="--debug --strict-warnings"

before_script:
    - if [ "$CC" == i686-w64-mingw32-gcc ]; then
          export CROSS_COMPILE=${CC%%gcc}; unset CC;
          ./Configure mingw $CONFIG_OPTS -Wno-pedantic-ms-format;
      elif [ "$CC" == x86_64-w64-mingw32-gcc ]; then
          export CROSS_COMPILE=${CC%%gcc}; unset CC;
          ./Configure mingw64 $CONFIG_OPTS -Wno-pedantic-ms-format;
      else
          ./config $CONFIG_OPTS;
      fi

script:
    - make
    - if [ -n "$CROSS_COMPILE" ]; then
          export EXE_SHELL="wine" WINEPREFIX=`pwd`;
      fi
    - make test

notifications:
    email:
        - openssl-commits@openssl.org
```
