### ISSUE TITLE
sudo does not preserve environment

### ISSUE THREAD

**Issue by tmcdonell** [travis-ci/travis-ci#5224]
On the new GCE workers, running a command under `sudo` does not inherit any changes to the environment, e.g. `PATH`. This is not the same behaviour as on the old workers.

See for example the last lines of [this log](https://travis-ci.org/tmcdonell/travis-test/jobs/95122517):

> $ export PATH=$HOME/bin:$PATH
> ...
> $ which stack
> /home/travis/bin/stack
> $ sudo which stack
> The command "sudo which stack" failed and exited with 1 during .
> Your build has been stopped.

Presumably the `env_reset` option is still enabled in `/etc/sudoers`?

**Comment by meatballhat** [comment]
relevant worker & image info:

``` yaml
hostname: travis-worker-gce-org-prod-6:5e3e2a4e-e746-4592-850c-0a134ddf3547
version: v1.4.0
instance: testing-gce-9cd6c31f-2526-4e69-a7eb-9c54f1ea51a5:travis-ci-ruby-precise-1449202414
```
