### ISSUE TITLE
Linux icon shown for an OS X build

### ISSUE THREAD

**Issue by rwhogg** [travis-ci/travis-ci#5272]
I've been trying to set up [Linux builds on Travis](https://github.com/Homebrew/homebrew-emacs/pull/131) for Homebrew/homebrew-emacs.

https://travis-ci.org/rwhogg/homebrew-bob/builds/96196701 shows the Linux icon for one job and the Apple icon for the 3 Mac jobs, as expected. However, looking at the Linux job shows that it's still running on OS X.

This may be due to our .travis.yml specifying `language:objective-c`, but we're not 100% sure.

For reference, our .travis.yml as of the time of failure was:

``` yaml
language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
      rvm: system
    - env: OSX=10.10
      os: osx
      osx_image: xcode7
      rvm: system
    - env: OSX=10.9
      os: osx
      osx_image: beta-xcode6.2
      rvm: system
    - os: linux
      rvm: system

before_install:
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - sudo chown -R $USER $(brew --repo)
  - brew update || brew update
  - mkdir -p $(brew --repo)/Library/Taps/homebrew
  - ln -s $PWD $(brew --repo)/Library/Taps/homebrew/homebrew-emacs
  - cd $(brew --repo)/Library/Taps/homebrew/homebrew-emacs
  - export TRAVIS_BUILD_DIR="$(brew --repo)/Library/Taps/homebrew/homebrew-emacs"
  - env | grep TRAVIS_

script:
  - brew test-bot --tap=homebrew/emacs

notifications:
  email:
    on_success: never
    on_failure: always

```
