### ISSUE TITLE
travis setup s3 does not work with Multiple Providers

### ISSUE THREAD

**Issue by cancan101** [travis-ci/travis-ci#5316]
in my yml file I have:
```
deploy:
  - provider: script
    script: $D/.travis-deploy.sh
    on:
      branch: master
```
but I get:
```
$ travis setup s3
deploy section already exists in .travis.yml, run with --force to override
```
