### ISSUE TITLE
env x OS matrix build?

### ISSUE THREAD

**Issue by zbeekman** [travis-ci/travis-ci#5335]
I'm having a lot of trouble figuring out how to apply an environment variable matrix across a two OS build.

This is what I have for the top of my .travis.yml:

``` YAML
  language: generic

env:
  global:
    - CACHE="$HOME/.local"
    - MPICH_VER="3.1.4"
    - MPICH_URL_HEAD="http://www.mpich.org/static/downloads/$MPICH_VER"
    - MPICH_URL_TAIL="mpich-${MPICH_VER}.tar.gz"
    - MPICH_DIR="$HOME/.local/usr/mpich"
    - MPICH_BOT_URL_HEAD="https://github.com/sourceryinstitute/opencoarrays/files/64308/"
    - MPICH_BOT_URL_TAIL="mpich-3.2.yosemite.bottle.1.tar.gz"
    - OSX_PACKAGES="gcc cmake"

matrix:
  include:
    - os: osx
    - os: linux
      sudo: false
      cache:
        directories:
          - "$CACHE"
          - "$HOME/.cache/pip"
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - gfortran-5
            - binutils
            - cmake-data
            - cmake
env:
  - BUILD_TYPE="CodeCoverage"
  - BUILD_TYPE="Release"
```

The documentation for how to achieve this is quite lacking...
