### ISSUE TITLE
how to use ubuntu 14.04 with android language

### ISSUE THREAD

**Issue by Honry** [travis-ci/travis-ci#5370]
I intend to use android language with Ubuntu 14.04 env, but when I set 
```yaml
language: android
android:
  sudo: required
  dist: trusty
```
It always initialize Ubuntu 12.04 env, can anyone give some help? I would be very appreciate!

**Comment by BanzaiMan** [comment]
You seem to have an extra top-level `android` in your YAML. It should look like this:

```yaml
language: android
sudo: required
dist: trusty
```

If this still fails, please point to the build log URL that shows this problem.

I'm closing this for now.

**Comment by Honry** [comment]
It still fails, this is my very simple YAML: https://github.com/Honry/crosswalk-app-tools/blob/test-travis/.travis.yml
Put key log here:
```
Build system information
Build language: android
Build group: stable
Build dist: trusty
Build image provisioning date and time
Wed Dec 16 00:11:01 UTC 2015
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
```

For details, please see https://travis-ci.org/Honry/crosswalk-app-tools/builds/99264794

**Comment by BanzaiMan** [comment]
Actually, it is available with:

```yaml
language: android
sudo: required
dist: trusty
group: edge
```

Until we update the mega image, use that.
