### ISSUE TITLE
Allow file renaming with s3 deploy

### ISSUE THREAD

**Issue by sirugh** [travis-ci/travis-ci#5373]
travis-ci provides the ability to [upload to a directory](https://docs.travis-ci.com/user/deployment/s3#Deploy-to-a-Specific-S3-Folder).

I think it would be great if we could upload to a specific file as well. I have a deploy job that only needs to deploy a file, but it needs to rename the file at the same time. In the [AWS CLI docs](http://docs.aws.amazon.com/cli/latest/reference/emr/put.html?highlight=put) you can PUT a local file to a filename that is different than the source.

My use case is a gzipped javascript file that I want to upload. Maybe that looks like this?
```yml
deploy:
  provider: s3
  ...
  local_file: "build/my_gzipped_file.gz"
  upload_file: "my_gzipped_file.js"
  detect_encoding: true
```

Currently I have to gzip the file to a separate subdirectory at `build/gz/my_gzipped_file.js` and upload that local_dir.

Thanks!
