### ISSUE TITLE
Firefox exiting unexpectedly

### ISSUE THREAD

**Issue by ImanMh** [travis-ci/travis-ci#5376]
This is my .travis.yml config file: 
```yml
language: node_js
addons:
  firefox: "43.0.3"
node_js:
  - '0.10'
  - '0.12'
  - '0.12.5'
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
```

and this is the last few lines of my build:
```
ok 38 PhantomJS 1.9 - Main Unit Test Suite hasText should pass if a single perian char or number is found
ok 39 PhantomJS 1.9 - Main Unit Test Suite raw letter ASCI ranges should be able to create custom RegExps
ok 40 PhantomJS 1.9 - Main Unit Test Suite raw number ASCI ranges should be able to create custom RegExps
not ok 41 Firefox - Browser "firefox -no-remote -profile /tmp/testem.firefox http://localhost:7357/8564" exited unexpectedly.

1..41
# tests 41
# pass  40
# fail  1

npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
The command "npm test" exited with 1.
Done. Your build exited with 1.
```
Why Travis shows me this line:
```not ok 41 Firefox - Browser "firefox -no-remote -profile /tmp/testem.firefox http://localhost:7357/8564" exited unexpectedly.```

here is my repo URL: https://github.com/ImanMh/persianRex
