### ISSUE TITLE
`brew` addon

### ISSUE THREAD

**Issue by SingingBush** [travis-ci/travis-ci#5377]
I've got my travis build using the apt addon to handle some dependencies:

```
addons:
  apt:
    packages:
    - libev-dev
    - libevent-dev
    - libsqlite3-dev
```

This is really convenient for the linux build but I also build on osx. I'd like to do the following if possible:

```
addons:
  apt:
    packages:
    - libev-dev
    - libevent-dev
    - libsqlite3-dev
  brew:
    packages:
    - libev
    - libevent
    - sqlite
```

**Comment by SingingBush** [comment]
I'm working around this using `before_install` but it's not quite as nice:

```
before_install:
 - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew update; fi"
 - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew install libev libevent sqlite; fi"
```

also, can the addons be specified in one line?

```
addons:
  apt:
    packages: libev-dev libevent-dev libsqlite3-dev
```

**Comment by BanzaiMan** [comment]
You can write arrays on a single line in YAML:

```yaml
key: [ foo, bar, baz]
```

**Comment by kbrock** [comment]
nice feature request

**Comment by sgen** [comment]
An brew addon would be much cleaner than the before install hack

**Comment by drdanz** [comment]
Also support for taps would be useful, i.e. instead of

```yml
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew tap homebrew/science; fi
```

```yml
addons:
  homebrew:
    taps:
      - homebrew/science
    packages:
      - opencv
```
