### ISSUE TITLE
`travis lint` false negative, marking apt addons empty and apt unexpected key

### ISSUE THREAD

**Issue by urda** [travis-ci/travis-ci#5396]
When using `travis lint` with my `.travis.yml` file, my `addons > apt > packages` is considered *invalid* by the linter. My `apt` package is getting installed during builds so it's working correctly remotely [as shown here](https://travis-ci.org/urda/nistbeacon/jobs/99976863#L82).

**Reproduction Steps:**

1. Open my project in terminal
2. Run `travis lint` from project repo.
3. Observe output:

```bash
Warnings for .travis.yml:
[x] value for addons section is empty, dropping
[x] in addons section: unexpected key apt, dropping
```

**Expected behavior:**

I should have observed:

```bash
Hooray, .travis.yml looks valid :)
```

**Version, `yml` info:**

**`travis version`:** 1.8.0

**travis yml [(Source)](https://github.com/urda/nistbeacon/blob/333c617737088cab14f7d439e083f4e16e3648a8/.travis.yml):**

```yml
language: python

matrix:
  fast_finish: true
  include:
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
    - python: "3.5-dev"
    - python: "nightly"
  allow_failures:
    - os: osx
    - python: "nightly"

addons:
  apt:
    packages:
    - python3-dev

branches:
  only:
    - master
    - release

before_install:
  - echo Travis OS Name ... ${TRAVIS_OS_NAME}
  - echo Travis Python .... ${TRAVIS_PYTHON_VERSION}
  - echo Python Version ... $(python --version)

install:
  - pip install --upgrade pip
  - pip install --upgrade --requirement requirements-test.txt

script:
  - make

after_success:
  - coveralls

notifications:
  email: false
  slack:
    secure: >
      VCS7dHeluFzEE+1vuHi/H3CEvDrknqIpxDANxor8tyB2Iu2ZrLHH/s6n7hwnaU6uxiq7oOo1s/
      cSiXw0UfSlY9CkjxKdP8U/RhYF200ngEBpm3vvfFynEZ5otnJNznQs3Vga9AxZKezTT8btkbO0
      pUj4YoswTl2OEl+i1esOk3iWPXA9vZdPFmO1XchmnFC+IzyMeA3V7uxfNwh8d0cvlTsFKDB3M+
      Wx5GpsSaVJbH09oRzDXN3Lsoe9Q+PYQ2dkIP0JkeMMMBi8/D0Zqrjy9m1i/VhW45hA9+h2qKsO
      C2TPjp3Oi6coeCyNaZWPjA8Wf/I6PiGs5LM8PoT7u7+irtRqIRSI9/yerPOzultl/Di/kHDF0D
      r73Zn7tisBGEeAQuqsFYBiwaRJzWoWuzd1tXNARkeF6x9t3lRSf/UMGG3rJSyqWsxvzgzPHtEh
      DhcKo4ZBCeliBlwwJlNpCGhOII687HqI859VOAAfpXyuQsAaAD+gBgFr11SijIiMv6wCgyFyJ0
      MNYFr2jCs+ziqtPunKT85hI4S/hCNiE+SN5IcbjCjFawmxXMHE2tdrOQJHyQbmEIeIfrFJUYWc
      LbSf8avF1iidrrBtQlQ0LqwnvdwzlOfdjaXJoPNeeXa1DwHcGlHQ+g1JENbqXYnFgCSp4LHzXN
      qZdaWaEQbXHRjHqX0=
```
