### ISSUE TITLE
Container infrastructure: APT packages not installed for jobs created with matrix.include

### ISSUE THREAD

**Issue by fwalch** [travis-ci/travis-ci#5405]
For the following `.travis.yml`, APT packages will not be installed for the job created by `matrix.include`:

```yaml
sudo: false
language: c
os:
  - linux
compiler: gcc-4.4
matrix:
  include:
    - compiler: gcc-4.5

addons:
  apt:
    packages:
      - gcc-4.4
      - gcc-4.5

script:
  - which $CC
```

Log (note that "Installing APT Packages (BETA)" is missing):

```text
...
$ export CC=gcc-4.5
$ gcc-4.5 --version
/home/travis/build.sh: line 45: gcc-4.5: command not found
```

This can be fixed by adding `os: linux` to the `matrix.include` job:

```diff
diff --git a/.travis.yml b/.travis.yml
index a8f2082..b03875c 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -5,7 +5,8 @@ os:
 compiler: gcc-4.4
 matrix:
   include:
-    - compiler: gcc-4.5
+    - os: linux
+      compiler: gcc-4.5
 
 addons:
   apt:
```

Log:
```text
Installing APT Packages (BETA)
...
$ export CC=gcc-4.5
$ gcc-4.5 --version
gcc-4.5 (Ubuntu/Linaro 4.5.3-12ubuntu2) 4.5.3
```

**Comment by BanzaiMan** [comment]
`matrix.include` jobs do not inherit from the outside. If you want the APT addon, you can do:

```yaml
sudo: false
language: c
os:
  - linux
compiler: gcc-4.4
matrix:
  include:
    - compiler: gcc-4.5
      addons:
        apt:
          packages:
            - gcc-4.4
            - gcc-4.5


addons:
  apt:
    packages:
      - gcc-4.4
      - gcc-4.5

script:
  - which $CC
```
