### ISSUE TITLE
nested `provider:` keys in cloudfoundry deployment setup generated by `travis setup cloudfoundry`

### ISSUE THREAD

**Issue by LukeWinikates** [travis-ci/travis-ci#5408]
I'm using travis to deploy to cloudfoundry. I used v1.8.0 of the travis gem to generate the relevant setup in `.travis.yml`:

```bash
$ travis setup cloudfoundry --force
Cloud Foundry username: asdfasdf
Cloud Foundry password: *******
Cloud Foundry organization: jasdf
Cloud Foundry space: asdfasd
Deploy only from gfadgsdf/asdfas? |yes| yes
Encrypt Password? |yes| yes
```

the travis gem generated this yaml, which has a second `provider:` key nested under the top-level one:

```yaml
deploy:
  provider:
    provider: cloudfoundry
  api: https://api.run.pez.pivotal.io
  username: asdfasdf
  password:
    secure: ...
  organization: jasdf
  space: asdfasd
  on:
    repo: ...
```

The next travis build failed on the deploy step with the message `missing provider`. I noticed the duplicate key, compared it to [the docs](https://docs.travis-ci.com/user/deployment/cloudfoundry), and changed it to the equivalent of this:

```yaml
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pez.pivotal.io
  username: asdfasdf
  password:
    secure: ...
  organization: jasdf
  space: asdfasd
  on:
    repo: ...
    branch: master
```

The next build passed. Seems like a small bug in the travis gem. I threw in the `edge: true` bit based on the yaml snippet in the documentation. I'm not sure that's actually necessary, but if so the gem should probably generate that too. 

One last note: I also added `branch: master` to the `on:` section of the deploy yaml because travis initially skipped the deploy step with a message that read `Skipping a deployment with the {:provider=>cloudfoundry} provider because this branch is not permitted`. Maybe the travis gem should also generate the branch specifier interactively. The [docs](https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A) about conditional releases mention that `master` may be a default value, but apparently wasn't the case for my repo.
