### ISSUE TITLE
[precise-gce] CppUtest build stopped working - suspect infrastructure

### ISSUE THREAD

**Issue by arstrube** [travis-ci/travis-ci#5409]
Our travis.yml looks like this:
```yaml
language: cpp
os:
 - linux
compiler:
- gcc
- clang
- wcl
rvm:
- 1.9.3
env:
  - BUILD=cmake-coverage
  - BUILD=autotools
  - BUILD=cmake
  - BUILD=autotools_gtest
  - BUILD=cmake_gtest
  - BUILD=test_report
  - BUILD=autotools_old_compilers
  - BUILD=make-dos
matrix:
    include:
    - env: BUILD=cmake-coverage
      compiler: gcc
    - env: BUILD=test_report
      compiler: gcc
    - env: BUILD=make-dos
      compiler: wcl
    exclude:
    - env: BUILD=autotools_old_compilers
    - env: BUILD=make-dos
    - env: BUILD=test_report
    - env: BUILD=cmake-coverage
    - compiler: wcl
```
It used to work perfectly. Now, however, three of the jobs are queued and never run, like this build:
   https://travis-ci.org/cpputest/cpputest/builds/99101779

There are cases where all jobs are queued and none is run.

I tried to force using the old infrastructure, but find the blog page lacking. It is not possible for me to get to run my matrix on the *old infrastructure*. I find the `matrix` generally poorly documented; I learned more from conjecture and looking at other people's travis.yml than from the documentation.

/cc @meatballhat @emdantrim @solarce
