### ISSUE TITLE
Github Releases and webhook

### ISSUE THREAD

**Issue by drundle** [travis-ci/travis-ci#5424]
When the build is complete, it publishes a Zip file to Github releases, using the command below, which is in the yml file.

```
deploy:
  provider: releases
  api-key: "$token"
  file: "release.zip"
  skip_cleanup: true
  on:
    tags: true
```

This creates the release, and Github fires an event to all the consumers listening to the "Release" webhook. the issue is the pay load does not have any assets.

```
    "assets": [

    ],
```

when I manually create the release on github, this works, the asset is listed.

I assume travis is creating the release and then attaching the release.zip, however by then the webhook has published the event

Can this issue be resolved by travis?
