### ISSUE TITLE
Allow to run scripts in a matrix

### ISSUE THREAD

**Issue by mathieujobin** [travis-ci/travis-ci#5426]
The Matrix feature is so great. right now, we can use it for env vars, rvm version, and many other places.

I wish we could use it in the script section such as 

```yml
script:
  matrix:
    - bundle exec cucumber -f progress
    - bundle exec rspec -f progress
```

this way, it would generate 2 different sub-build, the reason being that one may be a lot faster and also, that for some big project we could tolerate some failures in work-in-progress state

like 

```yml
script:
  matrix:
    - bundle exec cucumber -f progress
    - bundle exec rspec -f progress
    - bundle exec cucumber -p wip
  allow_failures:
    - bundle exec cucumber -p wip
```

**Comment by BanzaiMan** [comment]
You can use an environment variable to vary the script:

```yaml
env:
  - SCRIPT='cucumber -f progress'
  - SCRIPT='rake -f progress'
script:
  - bundle exec $SCRIPT
```
