### ISSUE TITLE
Mingw support? It somehow exists.

### ISSUE THREAD

**Issue by IngwiePhoenix** [travis-ci/travis-ci#5430]
For a while now, I had just copied a travis file from another project, which actually seems to use `mingw32msvc`. It also seems to simply work.

```yaml
language: cpp

os:
  - linux
  - osx

env:
  - TRCXX=g++
  - TRCXX=clang++
  - TRCXX=i586-mingw32msvc-g++

script:
  - export CXX=$TRCXX
  - $CXX src/*.cpp -Wno-switch -lpthread -o ./icetea
  - ./icetea -x tests/run_tests.os || ( [ "$?" == "2" ] && exit 0 || exit 1 )

matrix:
  exclude:
    - os: osx
      env: TRCXX=i586-mingw32msvc-g++
  allow_failures:
    - env: TRCXX=clang++
    - env: TRCXX=i586-mingw32msvc-g++
  fast_finish: true
```

So, where is a list of all the compilers? Because cross-compiling against MinGW would be helpful for my project.
