### ISSUE TITLE
When using nodejs version 4.1.1, worker randomly disallows allowed apt sources

### ISSUE THREAD

**Issue by Gum-Joe** [travis-ci/travis-ci#5431]
Hello.
I am running builds on travis-ci using the new ubuntu precise docker infrastructure. I am using the following nodejs versions:
* 5.3.0
* 4.2.2
* 4.2.1
* 4.2.0
* 4.1.2
* 4.1.1
* 4.0.0

I install the apt packages `g++-4.8` and `g++-4.9` during my build.

Problem: On the nodejs version 4.1.1 build, the worker seems to disallow the apt source `ubuntu-toolchain-r-test`, which none of the other builds' workers do. Also, the apt source `ubuntu-toolchain-r-test` is shown in the documentation, which means that the source should be allowed.

Build screen shot:
![image](https://cloud.githubusercontent.com/assets/12299307/12216168/09d065f6-b6d1-11e5-8491-a1f5cb56898a.png)
URL: https://travis-ci.org/Gum-Joe/jakhu/jobs/100917935

Replication:
1. Create a branch called `a1-dashboard-development`
2. File a `.travis.yml` file with the following:
```
language: node_js
node_js:
  - '4.1.1'
  - '5.3.0'
group: edge
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - g++-4.9
services:
  - mongodb
env:
  global:
    - CXX=g++-4.8
    - JAKHU_RUN_TYPE=local
install:
  - echo No install
script: echo No script
```
3. Run the build
4. When installing the apt packages, you should see the following message on the nodejs version 4.1.1 build only:
```
Adding APT Sources (BETA)
Disallowing sources: ubuntu-toolchain-r-test
If you require these sources, please review the source approval process at: https://github.com/travis-ci/apt-source-whitelist#source-approval-process
Installing APT Packages (BETA)
$ export DEBIAN_FRONTEND=noninteractive
$ sudo -E apt-get -yq update &>> ~/apt-get-update.log
$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install g++-4.8 g++-4.9
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package g++-4.8
E: Couldn't find any package by regex 'g++-4.8'
E: Unable to locate package g++-4.9
E: Couldn't find any package by regex 'g++-4.9'
```

Thanks in advance!
