### ISSUE TITLE
Webhooks fail after one host is no longer available

### ISSUE THREAD

**Issue by cwalsh** [travis-ci/travis-ci#5440]
With multiple webhook urls, if one of the hosts times out, or is otherwise inaccessible, all subsequent webhooks are not fired.

```yaml
 notifications:
    webhooks:
      urls:
       - https://this.one.is.received.example.com/result
       - https://this.one.times.out.example.com/result
       - https://never.gets.the.webhook.example.com/result
```
