### ISSUE TITLE
docker: unrecognized service

### ISSUE THREAD

**Issue by karlkfi** [travis-ci/travis-ci#5448]
Added docker to a travis build on a Kubernetes PR and am now getting:

```
$ sudo service docker start
docker: unrecognized service
```

and later

```
exec: docker: not found
```

Full log: https://api.travis-ci.org/jobs/101948276/log.txt?deansi=true

The top of the travis config is:

```
sudo: required

services:
  - docker

language: go

matrix:
  include:
    - go: 1.5.2
```

Potentially related to https://github.com/travis-ci/travis-ci/issues/5444 and https://github.com/travis-ci/travis-ci/issues/5142 which seemed to be caused by some permutations of build images not having docker installed.
