### ISSUE TITLE
Travis lint throws server error

### ISSUE THREAD

**Issue by nfwlpw-mit** [travis-ci/travis-ci#5488]
$ travis lint -E .travis.yml 
/Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/client/session.rb:225:in `raw': server error (500: "{\"error\":\"Travis encountered an error, sorry :(\"}") (Travis::Client::Error)
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/client/session.rb:190:in `post_raw'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/client/methods.rb:95:in `lint'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/cli/lint.rb:24:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/cli/command.rb:198:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/cli.rb:64:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/bin/travis:18:in `<top (required)>'
	from /usr/local/bin/travis:23:in `load'
	from /usr/local/bin/travis:23:in `<main>'

This started happening some time last week.  This is really annoying because even though there's no error in .travis.yml, the exit code is 1.

**Comment by BanzaiMan** [comment]
I think this is an error with API calls.

**Comment by sizmailov** [comment]
Just faced same problem. The cause was erroneous indentation of dict items:

Results to 500 error:
```yml
matrix:
  include:
    - name: "Python 2.7 on Linux"
        os: linux          # next three lines are over-indented 
        language: python
        python: 2.7
```

`Hooray, .travis.yml looks valid :)`:

```yml
matrix:
  include:
    - name: "Python 2.7 on Linux"
      os: linux
      language: python
      python: 2.7
```


Can you consider reopen and give more meaningful error message?

**Comment by DanySK** [comment]
Confirmed, the following systematically makes the linter crash:

```yaml
# System

language: bash
git:
  depth: false
addons:
  apt:
    update: true
  homebrew:
    packages:
      - pyenv
os:
  - osx
  - windows
  - linux
env:
  global:
    - TERM=dumb
    - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
  matrix:
    - JDK="adopt@1.11"
    - JDK="adopt-openj9@1.11"
    - JDK="adopt@" # Should test the latest
    - JDK="adopt-openj9@"


# Utilities

deploy_base: &deploy_base
  provider: releases
    edge: true
    file:
      - "${TRAVIS_BUILD_DIR}/charts/*.tar.gz"
      - "${TRAVIS_BUILD_DIR}/charts/*.pdf"
repo_filter: &repo_filter
  repo: DanySK/Experiment-2019-FGCS-Self-Integration


# Process

stages:
  - name: test
    if: tag is blank
  - name: charts
jobs:
  include:
    - stage: charts
      os: linux
      install:
        - curl "${GRAVIS}.install-python.sh" | bash
        - pip install --upgrade pip
        - pip install -r requirements.txt
      script: travis_wait python process.py
      before_deploy:
        - tar -czvf "charts.tar.gz" $TRAVIS_BUILD_DIR/charts/
        - git config --local user.name "Danilo Pianini"
        - git config --local user.email "danilo.pianini@unibo.it"
        - git describe --exact-match HEAD || git tag $(git log -n1 --date=format:'%Y-%m-%dT%H%m%S' --format=%cd)
      deploy:
        - <<: *deploy_base
          on:
            <<: *repo_filter
            tags: false
        - <<: *deploy_base
          on:
            <<: *repo_filter
            tags: true


# Common

before_install: true
install:
  - travis_retry curl "${GRAVIS}.install-jdk-travis.sh" --output .install-jdk-travis.sh
  - travis_retry source .install-jdk-travis.sh
script:
  - travis_retry ./gradlew clean showAll --parallel
before_cache:
  - travis_retry curl "${GRAVIS}.clean_gradle_cache.sh" --output .clean_gradle_cache.sh
  - travis_retry bash .clean_gradle_cache.sh
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.pyenv

```

**Comment by DanySK** [comment]
(the error is the indentation of deploy_base)

**Comment by andreasabel** [comment]
This failure still exists:
```
$ travis lint
server error (500: "Sorry, we experienced an error.\n\nrequest_id:51ee9da8384a40a2a4fc6a8defce8cb7\n")
$ travis --version
1.8.13
```
(latest homebrew version).

Yaml file:
```yaml
dist: xenial
language: haskell
cabal: "3.2"
cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc
    - $TRAVIS_BUILD_DIR/testing/.cabal-sandbox
    - $HOME/.stack

# Make sure to update tested-with in source/BNFC.cabal when updating these:
ghc:
  - 8.10.1
  - 8.8.3
#  - 8.8.2
  - 8.6.5
  - 8.4.4
  - 8.2.2
  - 8.0.2
  - 7.10.3

env:
  - STACK=yes
  - CABAL=yes PACKAGEDIR="source"
  - CABAL=yes PACKAGEDIR="testing"

matrix:
  exclude:
    # ghc 8.10.1 not yet supported by stack
    - ghc: 8.10.1
      env: STACK=yes

    # haskell-src (dependencies of testing) not yet compatible with ghc 8.10.1
    - ghc: 8.10.1
      env: CABAL=yes PACKAGEDIR="testing"

    # # haskell-src (dependencies of testing) throws off travis ghc 8.8
    # # since travis uses cabal 2.0 when ghc 8.8 wants cabal 3.0
    # - ghc: 8.8.3
    #   env: CABAL=yes PACKAGEDIR="testing"

    # # haskell-src (dependencies of testing) throws off travis ghc 8.8
    # # since travis uses cabal 2.0 when ghc 8.8 wants cabal 3.0
    # - ghc: 8.8.2
    #   env: CABAL=yes PACKAGEDIR="testing"

    # # HTF-0.14 does not build under 8.0 because of cabal version
    # - ghc: 8.0.2
    #   env: CABAL=yes PACKAGEDIR="testing"

    # shelly-1.9 not available for ghc 7
    - ghc: 7.10.3
      env: CABAL=yes PACKAGEDIR="testing"

script:
  - if [ "$CABAL" = yes -a "$PACKAGEDIR" = source  ]; then cabal configure --enable-tests && cabal build && cabal test; fi
  - if [ "$CABAL" = yes -a "$PACKAGEDIR" = testing ]; then source scripts/env && ./scripts/bootstrap; fi # && ./scripts/runtests; fi
  - if [ "$STACK" = yes ]; then stack --no-terminal --stack-yaml stack-$GHCVER.yaml build --test --no-run-tests; fi

before_install:
  - export GHCVER=${GHCVER:-$TRAVIS_HASKELL_VERSION}
  - sudo apt-get update -qq
  - if [ "$CABAL" = yes ]; then sudo apt-get install alex happy; fi
  - if [ "$STACK" = yes ]; then
      mkdir -p $HOME/.local/bin &&
      export PATH=$HOME/.local/bin:$PATH &&
      # Stack releases: 1.9.3 2.1.3
      travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v2.1.3/stack-2.1.3-linux-x86_64-static.tar.gz | tar xz --wildcards --strip-components=1 -C $HOME/.local/bin '*/stack' &&
      stack config set system-ghc --global true;
    fi
  - if [ "$CABAL" = yes -a "$PACKAGEDIR" = testing ]; then sudo apt-get install openjdk-9-jdk-headless jflex antlr4 ocaml texlive-latex-base hlint; fi

install:
  - if [ "$CABAL" = yes ]; then cd $PACKAGEDIR && cabal update && cabal install --enable-tests --dependencies-only; fi
  - if [ "$STACK" = yes ]; then stack --no-terminal --stack-yaml stack-$GHCVER.yaml build --test --dependencies-only; fi
```
Travis web says: "Could not parse"
