### ISSUE TITLE
ES Cluster comes with "twitter" index?

### ISSUE THREAD

**Issue by klahnakoski** [travis-ci/travis-ci#5495]
I noticed the ES cluster that is spun up for testing now comes with a "twitter" index.   This is causing a problem.  Are indexes leaking from other tests?   

Here is my `travis.yml` file

```
language: python
python:
  - "2.7"

install:
  - "sudo service elasticsearch stop"
  - "sudo cp -f tests/travis/elasticsearch.yml /etc/elasticsearch/elasticsearch.yml"
  - "sudo service elasticsearch start"
  - "pip install -r requirements.txt"
  - "sleep 10"
  - "whereis elasticsearch"
  - "curl http://localhost:9200/"

env:
  - PYTHONPATH=.

# command to run tests
script:
  - tests/travis/run.sh


addons:
  apt:
    sources:
      - elasticsearch-1.7
    packages:
      - elasticsearch
```
