### ISSUE TITLE
Elasticsearch: unrecognized service

### ISSUE THREAD

**Issue by rkorkosz** [travis-ci/travis-ci#5497]
Hi. Elasticsearch service is not starting for me.
Relevant part of my `.travis.yml`
```yml
language: python
sudo: false
python:
  - "3.4"
  - "3.5"
services:  
  - docker
  - postgresql
  - elasticsearch
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - sleep 10
```
build output
```
0.01s$ sudo service elasticsearch start
elasticsearch: unrecognized service
```
Is it something in my config?
Thanks

**Comment by BanzaiMan** [comment]
Sorry to hear that. Do you have a build log URL that shows the problem, and please show the entire `.travis.yml`. This [`.travis.yml`](https://github.com/BanzaiMan/travis_production_test/blob/3877c802b247e987b7d0000c63dfe742b8989dc8/.travis.yml) does start the service (https://travis-ci.org/BanzaiMan/travis_production_test/builds/104001046#L79).

**Comment by rkorkosz** [comment]
build url: https://travis-ci.com/3Blades/hubserver/jobs/31494165
```yml
language: python
sudo: false
addons:
  postgresql: "9.4"
python:
  - "3.4"
  - "3.5"
# whitelist
branches:  
  only:
    - master
services:  
# enable docker service inside travis
  - docker
  - postgresql
  - elasticsearch
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - sleep 10
before_install:  
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
# command to install dependencies
install:
  - pip install -r requirements/dev.txt
  - pip install coveralls
# command to run tests
script:
  # run tests
  - nosetests --with-coverage
  # build the image
  - docker build --no-cache -t $DOCKER_IMAGE_NAME .
  # tag the build
  - docker tag $DOCKER_IMAGE_NAME $DOCKER_IMAGE_NAME:build-$TRAVIS_BUILD_NUMBER
  # push the image to the repository
  - docker push $DOCKER_IMAGE_NAME:build-$TRAVIS_BUILD_NUMBER
after_success: 
  - coveralls
notifications:
  slack: 3blades:pTJcjtBur1kawgI9EpmkvC6A 
env:
  - DOCKER_IMAGE_NAME=3blades/hubserver
```

**Comment by BanzaiMan** [comment]
Ah, I overlooked `services: [ docker]`. This routes your builds to Trusty, which does not yet have ElasticSearch (https://docs.travis-ci.com/user/trusty-ci-environment#Data-Stores). Try `group: edge`, which instructs the build to go to a newer image, which might have it.

**Comment by rkorkosz** [comment]
Unfortunately edge doesn't have ElasticSearch :( https://travis-ci.com/3Blades/hubserver/jobs/31572017

**Comment by jsh2134** [comment]
Would love to be able to run elasticsearch service and docker service on the same build

**Comment by Overbryd** [comment]
Here is my workaround (works on **sudo** enabled builds):

```yaml
sudo: required
before_install:
  # install elasticsearch and start it
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.2.1.deb  && sudo dpkg -i --force-confnew elasticsearch-5.2.1.deb && sudo service elasticsearch start
  # wait till elasticsearch comes up
  - echo 'waiting for elasticsearch to come up'; while ! curl --output /dev/null --silent --head --fail http://localhost:9200; do sleep 1; echo -n '.'; done
```

**Comment by wagner-certat** [comment]
Could this problem (elasticsearch not available in trusty-images) be mentioned the docs?

**Comment by jnv** [comment]
There are actually instructions for setting-up ES in trusty containers: https://docs.travis-ci.com/user/database-setup/#Installing-ElasticSearch-on-trusty-container-based-infrastructure

However, I have found a bit neater workaround which works without sudo: just use APT repository through the addon. Example:

```yaml
sudo: false
dist: trusty
addons:
  apt:
    sources:
      - elasticsearch-1.7
    packages:
      - elasticsearch
services:
  - elasticsearch
#optionally wait for ES start
before_script:
  - echo 'waiting for elasticsearch to come up'; wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
```
