### ISSUE TITLE
Extra build jobs

### ISSUE THREAD

**Issue by dantman** [travis-ci/travis-ci#5507]
I think it would be really good if we could specify additional test jobs to run outside the matrix.

In one of my node libraries, linting is one of the slowest parts of testing. And since it's linting the source it only actually needs to be run once, not in every job / every version of node.

If I could specify an extra job I could exclude linting from the normal `npm test` on Travis and have a separate lint run that only lints and runs in node@5, where the building and linting runs the fastest.

Something like:
```yaml
language: node_js
node_js:
  - "5"
  - "4"
  - "0.12"
  - "0.10"
extra_jobs:
  - language: node_js
    node_js:
      - "5"
    env:
      - CI_TEST=lint-only
```
or:
```yaml
language: node_js
node_js:
  - "5"
  - "4"
  - "0.12"
  - "0.10"
extra_builds:
  - language: node_js
    node_js:
      - "5"
    script: npm run lint
```

This would also make the list of travis jobs very explicit as to when a build fails due being rejected by lint error rather than code failure in a version of node.
