### ISSUE TITLE
deploy script fails because node_modules has been stashed (or something)

### ISSUE THREAD

**Issue by thepatrick** [travis-ci/travis-ci#5518]
I need to use a custom deploy script because I cannot use the `npm` deployment provider (it seems to ignore the .npmrc I've included), however my script which runs `npm publish` fails because my `prepublish` script invokes gulp, which it can't find. (Despite the fact that `npm test` which has just run succeeds while also using `gulp`).

If `npm install` before `npm publish` it succeeds (the module is published), but I get enough log messages with `node_modules/... already exists, no checkout` in them to go over the 4MB limit, which then causes the build to be marked as a failure. 

For info, my .travis.yml

```
language: node_js
node_js:
  - '4.2'
sudo: false
deploy:
  provider: script
  script: ./travis-deploy.sh
  on:
    branch: master
  clean_up: false
```

travis-deploy.sh
```
 #!/bin/bash

npm publish
```
