### ISSUE TITLE
Intermittent build failures because python-serial missing

### ISSUE THREAD

**Issue by marcelstoer** [travis-ci/travis-ci#5522]
I'm seeing intermittent build failures because python-serial is missing - sometimes.

The first few lines of my `travis.yml` are as follows:
```yaml
sudo: false
language: cpp
addons:
  apt:
    packages:
    - python-serial
    - srecord
```

When it fails I see
> Disallowing packages: python-serial, srecord

which of course leads to 
> ImportError: No module named serial

when a Python script does `import serial`.

However, python-serial is whitelisted in https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise

It fails with    worker-linux-docker-a371335a.prod.travis-ci.org:travis-linux-8
It works with worker-linux-docker-ffb4f606.prod.travis-ci.org:travis-linux-8
