### ISSUE TITLE
Error 127 with custom script provider

### ISSUE THREAD

**Issue by GandaG** [travis-ci/travis-ci#5538]
I'm trying to use the custom script provider and whenever I use it I get an error 127 (as in [here](https://travis-ci.org/GandaG/UnitySauce/builds/105785797)). 

The script I'm trying to use works since I've tested it on the after_success stage. 

Removing the "sh" command in front of the script path gives the [same error](https://travis-ci.org/GandaG/UnitySauce/builds/105795700).

Relevant yml section:

```
deploy:
  provider: script
  script: sh ./.sauce/travis/deploy_docs.sh
  skip_cleanup: true
  on:
  	all_branches: true
```

**Comment by BanzaiMan** [comment]
The build log URLs seem incorrect.

**Comment by GandaG** [comment]
Oh, the repo name changed in the meantime, [first link](https://travis-ci.org/GandaG/unity-deploy-tools/builds/105785797) and [second link](https://travis-ci.org/GandaG/unity-deploy-tools/builds/105795700).

**Comment by BanzaiMan** [comment]
Where is `deploy_docs.sh`? https://github.com/GandaG/unity-deploy-tools/tree/master/.sauce/travis Is it supposed to be generated?

**Comment by GandaG** [comment]
That was not run on master, it was run on a [feature branch](https://github.com/GandaG/unity-deploy-tools/tree/feature/deploy_docs). [This](https://github.com/GandaG/unity-deploy-tools/blob/c0ec62452d5bb6c1573836071cf8bf40d588d1a5/.sauce/travis/deploy_docs.sh) is the snapshot of the commit in question.

**Comment by BanzaiMan** [comment]
Hmmm. How did this https://github.com/GandaG/unity-deploy-tools/blob/v1.1-alpha01/.travis.yml even trigger a deployment?

**Comment by GandaG** [comment]
Sorry, I keep forgetting to say this upfront. If there is need to deploy, I [trigger a rebuild](https://github.com/GandaG/unity-deploy-tools/blob/feature/deploy_docs/.deploy/travis/deploy_setup.py), the OP has the relevant part of the deploy section (it also deployed to github releases, correctly).

I saw in some other issue this same error for line endings, and I did try with unix style and windows style endings, the result was the same.

**Comment by BanzaiMan** [comment]
I see. I guess, then, the question is: does your build change directories? If so, is it in `$TRAVIS_BUILD_DIR` at the start of deployment?

**Comment by GandaG** [comment]
It is, I take care to always cd back to the initial directory (also I don't think I change directories at all in the build section)

**Comment by BanzaiMan** [comment]
Could you try printing `$PWD`? I have a feeling that the `script` provider might be in a subshell, which might be in `$HOME`. If so, could you try `sh $TRAVIS_BUILD/.sauce/travis/deploy_docs.sh`?

**Comment by GandaG** [comment]
[Build log](https://travis-ci.org/GandaG/unity-deploy-tools/builds/106901107) for:
```
deploy:
  provider: script
  script: sh $TRAVIS_BUILD/.deploy/travis/deploy_docs.sh
  skip_cleanup: true
  on:
  	all_branches: true
```
(the directory was renamed :) )

Same error.

**Comment by GandaG** [comment]
Just wanted to add that after opening the issue I switched to the after_success stage for this script and everything works perfectly, even the other deployments (though having this script as part of the deploy section would make the rest of the scripts prettier and a lot easier to read)

**Comment by BanzaiMan** [comment]
I think my reasoning was correct, but also somewhat faulty. https://travis-ci.org/GandaG/unity-deploy-tools/builds/106901107#L263 shows that `$TRAVIS_BUILD_DIR` is unset, which suggests that the `script` provider uses a sub shell to run the job, and that the sub shell does not inherit many environment variables.

**Comment by GandaG** [comment]
So there's nothing I can do?

**Comment by marvinroger** [comment]
Same issue here, with error 127. So basically, the script provider is unusable?

**Comment by marvinroger** [comment]
@BanzaiMan it seems worst than that. I tried adding $TRAVIS_BUILD_DIR to the script path, and [it is defined](https://travis-ci.org/marvinroger/homie-server/jobs/111991544#L1653). It looks like the files don't even exist in the sub shell environment.

**Comment by BanzaiMan** [comment]
@marvinroger Your case seems different. Namely, your script is not executable. 

```sh-session
$ git clone https://github.com/marvinroger/homie-server.git
Cloning into 'homie-server'...
remote: Counting objects: 1500, done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 1500 (delta 7), reused 0 (delta 0), pack-reused 1480
Receiving objects: 100% (1500/1500), 2.96 MiB | 1.93 MiB/s, done.
Resolving deltas: 100% (628/628), done.
Checking connectivity... done.
$ cd homie-server 
$ ls -l ci
total 8
-rw-r--r--  1 asari  staff  1313 Feb 26 07:31 deploy.sh
drwxr-xr-x  3 asari  staff   170 Feb 26 07:31 windows
```

**Comment by BanzaiMan** [comment]
@GandaG Have you tried this recently?

**Comment by GandaG** [comment]
@BanzaiMan No, I switched to after_success and it's been working that way. Has anything changed?

**Comment by markotom** [comment]
Fix .travis.yml

**Comment by BanzaiMan** [comment]
@GandaG I don't think any recent changes altered the behavior with respect to this issue. I suspect that `after_success` has always worked, while the `script` provider has not.

**Comment by runn-vermel** [comment]
I cannot find how to launch a script using `after_success`, and i'm getting the same `error 127` on `deploy `- how do I launch a script using `after_success`?

**Comment by filipre** [comment]
Hi!
Got the same error. After googling I found pull request: https://github.com/WikiWatershed/docker-rwd/pull/9
Although setting up the u+x flag did not fix my issue, putting the path into quotes (or adding the `./`) did:
```yml
deploy:
  skip_cleanup: true
  provider: script
  script: "./deploy.sh"
  on:
    branch: master
```

You may also want to checkout their `.travis.yml` file: https://github.com/WikiWatershed/docker-rwd/blob/develop/.travis.yml

**Comment by cyberhobo** [comment]
The `./` prefix did not work for me, so I also resorted to after_success with a bunch of test statements.

**Comment by filipre** [comment]
I made a repo providing a working example to experiment a little bit: https://github.com/filipre/travis-deploy-script-yml 

Basically, in case you use a shebang in your script, the script has to be set executable `chmod +x ...` (1) and be referred to with an absolute or relative path `/`, `./` (2) like you would do it in a unix shell. Quotes are not needed.
In case you use an **executable** program to call some files, a prefix isn't needed. For example:
```yml
deploy:
  provider: script
  script: /bin/sh script.sh
  on:
    branch: master
```

@cyberhobo Just curious: Was your  `./vendor/bin/phing` set executable? I like the `deploy` section more than the `after_success` since it's more declarative and is better for larger scripts.

**Comment by cyberhobo** [comment]
Thanks @filipre. In my case `vendor/bin/phing` is created in the `composer install` step. In my local environment it creates an executable script with a shebang.

**Comment by rafaelmagu** [comment]
It took me a few builds to figure this out, but if you're on the container-based infrastructure, any time you have a command `cd` into a folder, the build context remains in that folder until you go back out.

For example:
```yaml
sudo: false
script:
- cd scripts/ && ./build.sh
deploy:
  provider: script
  script: scripts/deploy.sh  # this will fail because we're still inside scripts/
  skip_cleanup: true
  on:
    branch: master
```

**Comment by finom** [comment]
Fixed for me by using ``chmod +x``before a script is run:

```yml
deploy:
  provider: script
  skip_cleanup: true
  script: chmod +x tools/deploy.sh && tools/deploy.sh
```

**Comment by hmedney** [comment]
Ran into this issue as well - here's another variation that worked (used in Travis CI Enterprise):
```yaml
deploy:
  provider: script
  skip_cleanup: true
  script: sh $TRAVIS_BUILD_DIR/deploy/deploy.sh
```

**Comment by thiagolimaa** [comment]
I also ran into it, and then I made it work by running a `chmod +x` to the `.travis.yml`. 

``` deploy:
  provider: script
  skip_cleanup: true
  script: chmod +x deploy/deploy_tadev1.sh
  on:
    branch: development ```

**Comment by geerlingguy** [comment]
For BLT (referenced issue above), this wasn't working:

```yaml
deploy:
  - provider: script
    script: "source $BLT_DIR/scripts/travis/deploy_branch"
    skip_cleanup: true
```

...but this worked:

```yaml
deploy:
  - provider: script
    script: "$BLT_DIR/scripts/travis/deploy_branch"
    skip_cleanup: true
```

**Comment by jakubholynet** [comment]
I run into `127` due to my script not being executable so I created this: https://github.com/travis-ci/dpl/pull/617

**Comment by mloskot** [comment]
My deployment script was also failing with error 127  (https://github.com/mloskot/mateusz.loskot.net/blob/master/.travis.yml)

I've tried double-quoting the script command (as per https://github.com/travis-ci/travis-ci/issues/5538#issuecomment-220135972), using full path based on `$TRAVIS_BUILD_DIR`, fixing `chmod +x` locally and committing, and none of these worked.

Only two of the discussed solutions worked for me:
1. `chmod +x scripts/deploy.sh && scripts/deploy.sh` as per https://github.com/travis-ci/travis-ci/issues/5538#issuecomment-265956466
2. `sh scripts/deploy.sh` as per https://github.com/travis-ci/travis-ci/issues/5538#issuecomment-274290677

**Comment by billdevcode** [comment]
I ran into this issue today and tried **_all_** the approaches here but none worked for me. What did work was moving `chmod +x ./scripts/deploy.sh ` to the outer `script` like this:

```
script:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x ./scripts/deploy.sh
deploy:
  provider: script
  script: ./scripts/deploy.sh
  skip_cleanup: true
```
