### ISSUE TITLE
container-based environment has git 1.9.1

### ISSUE THREAD

**Issue by gotcha** [travis-ci/travis-ci#5544]
Is there a way to get newer version ?

**Comment by BanzaiMan** [comment]
Try using `git-core` apt source and updating `git`.

```yaml
addons:
  apt:
    sources:
      - git-core
    packages:
      - git
```
