### ISSUE TITLE
Cannot add new users in the RabbitMQ service

### ISSUE THREAD

**Issue by vincent-zurczak** [travis-ci/travis-ci#5550]
With container-based infrastructures, it is not possible to add new users (nor virtual hosts) in RabbitMQ. The following travis.yml file always fails the build.

```yml
sudo: false

# blabla...

# Make sure there is a RabbitMq server
services:
  - rabbitmq

# Configure RabbitMQ with new users
before_script:
  - rabbitmqctl add_user myuser mypwd
  - rabbitmqctl set_permissions myuser ".*" ".*" ".*"
```

The *add_user* always fail.
It says the command is not recognized (error from RabbitMQ). It ends by displaying the RabbitMQ options. It also indicates that **rabbitmqctl** should be run as root or as rabbitmq. I have tried to run these commands with `su - rabbitmq`, `sudo -u rabbitmq`, `runuser -l rabbitmq`... I don't even know whether there is a *rabbitmq* user. And no matter what, we cannot execute these commands because only root has these rights.

The documentation indicates new users and new vhosts can be set in the **before_script** step. Either it is wrong for container-based infrastructures and it should be mentioned in the doc. Or it is supposed to work, and then I don't know how. Any help would be welcome. :sweat_drops:
