### ISSUE TITLE
Perl support on the OSX platform

### ISSUE THREAD

**Issue by rfdrake** [travis-ci/travis-ci#5574]
I just noticed you can target an osx box in travis now.  I added it to one of my perl repositories and saw a few problems:

> /Users/travis/build.sh: line 242: lsb_release: command not found
> 
> /Users/travis/build.sh: line 242: lsb_release: command not found
> 
> tar: Unrecognized archive format
> 
> tar: Error exit delayed from previous errors.
> git.checkout
> .....
> 0.00s$ perlbrew use 5.20
> 
> /Users/travis/build.sh: line 45: perlbrew: command not found
> ....
>/Users/travis/build.sh: line 45: cpanm: command not found

travis.yml file looks like this:

```
language: perl

os:
  - linux
  - osx

perl:
    - "blead"
    - "dev"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"

matrix:
  include:
    - perl: 5.18
      env: COVERAGE=1
  allow_failures:
    - perl: blead
    - perl: dev
sudo: false

before_install:
     - eval $(curl https://travis-perl.github.io/init) --auto
```
