### ISSUE TITLE
Parallelizing builds on one VM doesn't seem to work

### ISSUE THREAD

**Issue by pratik60** [travis-ci/travis-ci#5588]
Parallel tests doesn't seem to work as intended on a single VM

Quoting https://docs.travis-ci.com/user/speeding-up-the-build/

> Parallelizing your build on one VM #
> 
> Travis CI VMs run on 1.5 virtual cores. This is not exactly a concurrency, which allows to parallelize a lot, but it can give a nice speedup depending on your use case.
> 
> Parallelizing the test suite on one VM depends on the language and test runner, which you use, so you will have to research your options. At Travis CI we use mainly Ruby and RSpec, which means that we can use parallel_tests gem. If you use Java, you may use the built in feature to run tests in parallel using JUnit.
> 
> To give you an idea of what speedup are we talking about, I’ve tried running tests in parallel on travis-core and I was able to see a drop from about 26 minutes to about 19 minutes across 4 jobs.
> 

```
# .travis.yml
language: ruby
rvm:
  - 2.2.2
env:
  - DB=postgresql
cache: bundler
addons:
  postgresql: "9.4"
services:
  - postgresql
  - mongodb
  - redis
script:
  - RAILS_ENV=test bundle exec rake teaspoon
  - RAILS_ENV=test xvfb-run -a bundle exec rake parallel:spec
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - cp config/database.travis.yml config/database.yml
  - cp config/mongoid.travis.yml config/mongoid.yml
  - export PARALLEL_TEST_PROCESSORS=4
  - RAILS_ENV=development bundle exec rake db:create db:migrate
  - bundle exec rake parallel:create parallel:prepare
```

```
development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: adiq_dev
  pool: 25
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: adiq_test<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 25
  username: postgres
  password:
```

But travis is behaving weirdly and is giving me this

```
 bundle exec rake parallel:create parallel:prepare
You have 174 pending migrations:
....
...
Run `rake db:migrate` to update your database then try again.
The command "bundle exec rake parallel:create parallel:prepare" failed and exited with 1 during .
Your build has been stopped.
```

Any idea what is wrong?
