### ISSUE TITLE
before_script not getting executed

### ISSUE THREAD

**Issue by rnagulapalle** [travis-ci/travis-ci#5592]
I have below script. what i want to do is mvn install dependecy project before packaging actual web app. But it always running war and ignoring dependecy project. can someone please help me.

```
language: java
before_script:
    - echo 'remove schedfox lib directory before cloining...'
    - rm -rf rnagulapalle/schedfoxlib
    - echo 'cloning schedfox lib ....'
    - git clone --depth=50 --branch=master-ci git@github.com:rnagulapalle/schedfoxlib.git rnagulapalle/schedfoxlib
    - cd rnagulapalle/schedfoxlib
    - mvn clean install -DskipTests=true

# blacklist
branches:
  except:
    - master

# whitelist
branches:
  only:
    - master-ci
    
script: mvn clean package -DskipTests=true
```
