### ISSUE TITLE
PHPunit 4.8.11 and HHVM 3.6.6 result in a Segfault on Travis-ci build core dump

### ISSUE THREAD

**Issue by photodude** [travis-ci/travis-ci#5634]
```
Core dumped: Segmentation fault
Stack trace in /tmp/stacktrace.2792.log
/home/travis/build.sh: line 45:  2792 Segmentation fault      (core dumped) libraries/vendor/bin/phpunit --configuration travisci-phpunit.xml
The command "libraries/vendor/bin/phpunit --configuration travisci-phpunit.xml" exited with 139.
```

Example failing build
https://travis-ci.org/photodude/joomla-cms/jobs/109432023

**Comment by BanzaiMan** [comment]
You are calling `libraries/vendor/bin/phpunit`. https://github.com/photodude/joomla-cms/blob/91970a0eca40700d0df649e5fa38c52bdd64291a/.travis.yml#L51 Where are you getting this `phpunit`? That is not the location of `phpunit` we provide.

**Comment by photodude** [comment]
I believe it's composer installed from 4.8.11 in the PHPunit github repository

**Comment by BanzaiMan** [comment]
Where is it coming from?

**Comment by photodude** [comment]
PHPunit 4.8.11 is installed from Composer (link to the composer line)
https://github.com/photodude/joomla-cms/blob/91970a0eca40700d0df649e5fa38c52bdd64291a/composer.lock#L1422

so it's direct from the github repository for PHPunit at the tag for 4.8.11
https://github.com/sebastianbergmann/phpunit.git

**Comment by photodude** [comment]
@BanzaiMan I ran a test updating PHPUnit to 4.8.23, Same Segfault issue.

https://travis-ci.org/photodude/joomla-cms/jobs/111357931
```
Core dumped: Segmentation fault
Stack trace in /tmp/stacktrace.3343.log
/home/travis/build.sh: line 45:  3343 Segmentation fault      (core dumped) libraries/vendor/bin/phpunit --configuration travisci-phpunit.xml
```

**Comment by BanzaiMan** [comment]
Thanks for the update. Is PHPUnit compatible with HHVM 3.6.x?

**Comment by photodude** [comment]
I believe it is, 
I think HHVM and phpunit compatibility started in hhvm3.1.x

Although I think hhvm3.6.x is end of life but that's what is available in the container install.

**Comment by BanzaiMan** [comment]
Sorry for the delay. I tend to think this is best investigated by HHVM team. https://github.com/facebook/hhvm/issues/3982 is an outstanding issue, though it is not clear how recent the issue is.

You could also try Trusty, as it can run a more recent version of HHVM.

```yaml
language: php

php:
  - hhvm

sudo: required
dist: trusty
group: edge # until the next update
⋮
```

If there is anything we should be doing, do let us know.

I'm closing this in the meantime.

**Comment by photodude** [comment]
So If we only wanted to run HHVM on trusty and still use containers for all other php versions, I guess we would do something like
```yaml
sudo: false

language: php

env:
  global:
    - RUN_PHPCS="no"
    - INSTALL_MEMCACHE="yes"
    - INSTALL_MEMCACHED="yes"
    - INSTALL_REDIS="yes"

matrix:
  include:
    - php: 5.3
      env: INSTALL_APC="yes"
    - php: 5.4
      env: INSTALL_APC="yes"
    - php: 5.5
      env: INSTALL_APCU="yes"
    - php: 5.6
      env: RUN_PHPCS="yes" INSTALL_APCU="yes"
    - php: 7.0
      env: INSTALL_APCU="yes" INSTALL_APCU_BC_BETA="no" INSTALL_MEMCACHE="no" INSTALL_MEMCACHED="no" INSTALL_REDIS="no" # Disabled apcu_bc install until https://github.com/travis-ci/travis-ci/issues/5207 is resolved
    - php: hhvm
      env: INSTALL_APCU_BC_BETA="no" INSTALL_MEMCACHE="no" INSTALL_MEMCACHED="no" INSTALL_REDIS="no" # Disabled items that currently do not work in travis-ci hhvm
  allow_failures:
    - php: hhvm

services:
  - memcache
  - memcached
  - redis-server

before_script:
 - if [[ $TRAVIS_PHP_VERSION = hhvm ]]; then sudo: required .; fi
 - if [[ $TRAVIS_PHP_VERSION = hhvm ]]; then dist: trusty .; fi
 - if [[ $TRAVIS_PHP_VERSION = hhvm ]]; then group: edge .; fi
```

Are we going to have issues mixing container builds with legacy infrastructure?

**Comment by photodude** [comment]
Looks like there is no issue mixing Container builds and legacy infrastructure (other than it's slow)

It does need to be set up in the matrix includes from what I have read

```yaml
sudo: false

language: php

env:
  global:
    - RUN_PHPCS="no"
    - INSTALL_MEMCACHE="yes"
    - INSTALL_MEMCACHED="yes"
    - INSTALL_REDIS="yes"

matrix:
  include:
    #- php: 5.3
    #  env: INSTALL_APC="yes"
    #- php: 5.4
    #  env: INSTALL_APC="yes"
    #- php: 5.5
    #  env: INSTALL_APCU="yes"
    - php: 5.6
      env: RUN_PHPCS="yes" INSTALL_APCU="yes"
    #- php: 7.0
    #  env: INSTALL_APCU="yes" INSTALL_APCU_BC_BETA="no" INSTALL_MEMCACHE="no" INSTALL_MEMCACHED="no" INSTALL_REDIS="no" # Disabled apcu_bc install until https://github.com/travis-ci/travis-ci/issues/5207 is resolved
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge # until the next update
      env: INSTALL_APCU_BC_BETA="no" INSTALL_MEMCACHE="no" INSTALL_MEMCACHED="no" INSTALL_REDIS="no" # Disabled items that currently do not work in travis-ci hhvm
  allow_failures:
    - php: hhvm

services:
  - memcache
  - memcached
  - redis-server
```
