### ISSUE TITLE
node_js: "4.2.1" fails silently on container infra

### ISSUE THREAD

**Issue by zbeekman** [travis-ci/travis-ci#5638]
Please see https://travis-ci.org/kvz/bash3boilerplate/builds/109619625#L83

Here is the .travis.yml, but make sure you uncomment `sudo: false` to reproduce the behavior:

```yaml
language: node_js
node_js:
  - "4.2.1"
script: npm run test
# For some reason, this breaks nvm. Tried two times:
# https://s3.amazonaws.com/archive.travis-ci.org/jobs/109619626/log.txt
# sudo: false
```
