### ISSUE TITLE
Travis Build is failing : /home/travis/build.sh: line 45: xcodebuild: command not found

### ISSUE THREAD

**Issue by anilkumarbp** [travis-ci/travis-ci#5641]
Hi Team,

I seem to be getting the below error every time i use travis to build : 
`/home/travis/build.sh: line 45: xcodebuild: command not found`

My .travis.yml looks like this : 
```yaml
language: swift
osx_image: xcode7.1

script: 
  - xcodebuild -scheme Sample -workspace Sample.xcworkspace -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

after_success:
  - bash <(curl -s https://codecov.io/bash)
```

Appreciate if you could assist me in getting the builds completed. Thanks.
