### ISSUE TITLE
"No such file or directory" on deploy release

### ISSUE THREAD

**Issue by dermoritz** [travis-ci/travis-ci#5646]
I am trying to get the binary of my release uploaded to github. This is the project: https://github.com/dermoritz/imageservice.
It's java/maven based. the file i want to be uploaded is <project directory>/target/imageService-distribution.zip.
This is my travis.yml (i used travis cli and modified it a bit):
```
language: java
jdk:
- oraclejdk8
deploy:
  provider: releases
  api_key:
    secure: ...
  file: imageService-distribution.zip
  skip_cleanup: true
  on:
    branch: master
    repo: dermoritz/imageservice
```
[the build](https://travis-ci.org/dermoritz/imageservice/builds/109958751) yields: 
```
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.2.0/lib/octokit/client/releases.rb:86:in `initialize': No such file or directory - imageService-distribution.zip (Errno::ENOENT)
```

so how to fix this?

Is there a way to upload a file with dynamic name (e.g. containing the version)?

i am also not really sure what happens if this works. My intentions is to provide the binary as download for users does this work this way?

thanks in advance
