### ISSUE TITLE
Node.js v4 (or io.js v3) compiler requirements travis examples are invalid

### ISSUE THREAD

**Issue by agconti** [travis-ci/travis-ci#5657]
The travis.yml examples located in the [docs](https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements) are invalid. 

For example, the travis file for using g++:
```yml
language: node_js
node_js:
  - "4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
```

yields the errors: 
- value for node_js section is empty, dropping
- value for addons section is empty, dropping
- in node_js section: value 4 is not a valid version
- in addons section: unexpected key apt, dropping

You can validate this yourself by validating the file above the web tool: http://lint.travis-ci.org/.

What is the correct way to configure travis to correctly compile modules for node version 4+?

**Comment by BanzaiMan** [comment]
The example should be valid, but the linter is not quite up to date with Node.js versions. As such, this is a duplicate of #5609.

**Comment by BanzaiMan** [comment]
If you can't get the example to work, then please indicate the build log URL to show that. Thanks.

**Comment by agconti** [comment]
@BanzaiMan running the example on travis yields the same errors: https://travis-ci.com/ustwo/foursquare-business. Running from the cli does as well.

**Comment by BanzaiMan** [comment]
@agconti That repository is using a different setup. It is a `Python` project, and the sequence of events are not what is shown in the example. Do you want to continue troubleshooting here, or would you like to send us email at support@travis-ci.com for further details?

**Comment by agconti** [comment]
@BanzaiMan thanks for getting back tome; I was able to solve my issue this morning. My personal example is more complex, but  for other's looking at this add additional env variables by:

```yml
language: node_js
node_js:
  - "4"
env:
  global:
  - secure: '< long hash here >'
  - CXX=g++-4.8
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
```
