### ISSUE TITLE
When both CocoaPods and Bundler caches are enabled, only the former is effective

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#5662]
Given:

```yaml
language: objective-c
cache:
  bundler: true
  cocoapods: true
```

Only CocoaPods cache is effective.

**Comment by BanzaiMan** [comment]
A workaround is to specify the Bundler cache directory:

```yaml
language: objective-c
cache:
  cocoapods: true
  directories:
    - "vendor/cache"
```
