### ISSUE TITLE
With `Gemfile.lock`, and no available cache, adding `vendor/cache` breaks the install phase

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#5664]
Related to #5662.

Given:

```yaml
cache:
  directories:
    - "vendor/cache"
```

and `Gemfile.lock` checked in, if `install` is not overridden, the build results in:

```
⋮
bundle install --jobs=3 --retry=3 --deployment
Some gems seem to be missing from your vendor/cache directory.
Could not find i18n-0.7.0 in any of the sources
```
