### ISSUE TITLE
Testing on both Precise and Trusty

### ISSUE THREAD

**Issue by sjackman** [travis-ci/travis-ci#5666]
I'd like to test on multiple Ubuntu distributions. Is the following syntax supported?
```yaml
dist:
  - precise
  - trusty
```

**Comment by sjackman** [comment]
Or does this work?
```yaml
matrix:
  include:
    - dist: precise
    - dist: trusty
```

**Comment by sjackman** [comment]
When I tried `dist: [precise, trusty]` the job sat in the queue for twelve hours and never moved.
https://travis-ci.org/Linuxbrew/linuxbrew/builds/110557403

**Comment by BanzaiMan** [comment]
@sjackman See https://github.com/travis-ci/travis-rubies/blob/build/.travis.yml for the multi-dist example.

**Comment by sjackman** [comment]
This mostly worked! I got four builds instead of the expected three. I requested `rvm: 2.0.0` and got Ruby 1.9.3.
```
$ rvm use ["2.0.0"] --install --binary --fuzzy
Using /home/travis/.rvm/gems/ruby-1.9.3-p551
$ ruby --version
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]
```
https://travis-ci.org/Linuxbrew/linuxbrew/jobs/110641274#L158-L162

**Comment by BanzaiMan** [comment]
An extra build is a known issue: #4681.

**Comment by BanzaiMan** [comment]
I'm closing this, since it's been reduced to another known issue.

**Comment by sjackman** [comment]
Thanks for your help, Hiro. The syntax could be improved to something like:
```
matrix:
  include:
    - dist: precise
    - dist: trusty
```

**Comment by basicmaster** [comment]
Just in case someone wants to build for two dists other than the default one (which currently equals to `precise`) and `trusty`. Specifying the first one at the top level helps:

```yaml
language: c++
dist: trusty
matrix:
  include:
  - #dist: trusty
    compiler: gcc
    os: linux
    sudo: required
  - #dist: trusty
    compiler: clang
    os: linux
    sudo: required
  - dist: xenial
    compiler: gcc
    os: linux
    sudo: required
  - dist: xenial
    compiler: clang
    os: linux
    sudo: required

# (...)
```
