### ISSUE TITLE
R: Check errors on package dependencies?

### ISSUE THREAD

**Issue by droglenc** [travis-ci/travis-ci#5668]
My Travis-Ci build appears to error based on missing package dependencies.  The offending package are available on CRAN.  Here is [the raw log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/110615656/log.txt) (is the ultimate issue related to `lme4`?) and my [travis.yml](https://github.com/droglenc/FSA/blob/master/.travis.yml) file.  Thoughts?   @craigcitro, @hadley, @jimhester

**Comment by jimhester** [comment]
It looks like an error with `nlme` not being updated properly and `lme4` expecting a newer version, possibly the debian package has not caught up to the current CRAN release, It will likely resolve itself in a few days.

Alternatively you could use the [container based builds](https://docs.travis-ci.com/user/languages/r#Basic-configuration) with package caching rather than relying on the binary packages. The following yaml would do so for your current settings.

```yaml
language: r
warnings_are_errors: false
sudo: false
cache: packages

r_github_packages:
  - jimhester/covr
  
after_success:
  - Rscript -e 'library(covr);coveralls()'
```

**Comment by droglenc** [comment]
Thanks for the prompt help, Jim.  Unfortunately, with the changes to my YAML that you suggested (now shown below), I still get the same problems ([log now shown here](https://api.travis-ci.org/jobs/110653943/log.txt?deansi=true)).  I will wait to see if this resolves itself in the near future (though this has been happening for about a week).  Thanks again for your help.

```YAML
language: r
warnings_are_errors: false
sudo: false
cache: packages

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: always
```
