### ISSUE TITLE
Python3 cannot find module

### ISSUE THREAD

**Issue by kengz** [travis-ci/travis-ci#5679]
I'm running a Ubuntu 14.04 Travis instance, with `sudo` and a multi-languages project setup.
Below is my `travis.yml` file, to setup `nodejs` as the main language, and `ruby, python` as the extra languages.

When `node` internally calls a `python` script via child_process.spawn, it throws the `ImportError: No module named 'socketIO_client'` error.

I've tried installign the python modules using `sudo pip3 install <module>`, `pip3 install <module>`, `sudo pip3 install -U <module>`, and python still can't find the modules. 

Any clue? Thanks in advance.

```yml
sudo: required
dist: trusty
language: node_js
node_js:
  - "5.5"
  - "4.2"
virtualenv:
  system_site_packages: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - openjdk-7-jdk
before_install:
  - sudo apt-get -y install python3-pip python-dev
  - python3 -V
  - pip3 -V
  # reinstall bundler to fix it failing to locate gem
  - gem uninstall -aIx bundler
  - gem install bundler
  - ruby --version
  - bundle --version
install:
  - npm install
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrapper
  - sudo pip3 install -U textblob
  - sudo python3 -m textblob.download_corpora
  - sudo pip3 -U socketIO-client
  - bundle install
```

Below is a partial log from Travis:

```
2.47s$ sudo pip3 install --user -U socketIO-client
Downloading/unpacking socketIO-client
  Downloading socketIO_client-0.6.5.tar.gz
  Running setup.py (path:/tmp/pip_build_root/socketIO-client/setup.py) egg_info for package socketIO-client
    
    warning: no files found matching '*.html'
    warning: no files found matching '*.js'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
Downloading/unpacking requests from https://pypi.python.org/packages/2.7/r/requests/requests-2.9.1-py2.py3-none-any.whl#md5=58a444aaa02780ad01983f5f540e67b2 (from socketIO-client)
  Downloading requests-2.9.1-py2.py3-none-any.whl (501kB): 501kB downloaded
Requirement already up-to-date: six in /home/travis/.local/lib/python3.4/site-packages (from socketIO-client)
Downloading/unpacking websocket-client (from socketIO-client)
  Downloading websocket_client-0.35.0.tar.gz (193kB): 193kB downloaded
  Running setup.py (path:/tmp/pip_build_root/websocket-client/setup.py) egg_info for package websocket-client
    
Installing collected packages: socketIO-client, requests, websocket-client
  Running setup.py install for socketIO-client
    
    warning: no files found matching '*.html'
    warning: no files found matching '*.js'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
  Could not find .egg-info directory in install record for socketIO-client
  Running setup.py install for websocket-client
    changing mode of build/scripts-3.4/wsdump.py from 644 to 755
    
    changing mode of /home/travis/.local/bin/wsdump.py to 755
  Could not find .egg-info directory in install record for websocket-client (from socketIO-client)
Successfully installed socketIO-client requests websocket-client
Cleaning up...
install.7
5.85s$ bundle install
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/..
Installing event_emitter 0.2.5
Installing json 1.8.3 with native extensions
Installing multi_xml 0.5.5
Installing websocket 1.2.2
Using bundler 1.11.2
Installing httparty 0.13.7
Installing websocket-client-simple 0.3.0
Installing socket.io-client-simple 1.2.1
Bundle complete! 1 Gemfile dependency, 8 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Post-install message from httparty:
When you HTTParty, you must party hard!
27.68s$ npm test
> peppurr@0.0.1 test /home/travis/build/kengz/peppurr
> istanbul cover ./node_modules/.bin/_mocha
[TypeError: Environment file doesn't exist: /home/travis/build/kengz/peppurr/.env]
Using externally set env vars if exist.
Starting Neo4j:
0
This is in development mode.
starting master io_server.js
starting polyglot io_clients
child process exited with code 1
js io imports
py io imports
err: Traceback (most recent call last):
  File "/home/travis/build/kengz/peppurr/lib/io_import.py", line 2, in <module>
    from py import *
  File "/home/travis/build/kengz/peppurr/lib/py/nlp.py", line 1, in <module>
    from socketIO_client import SocketIO
ImportError: No module named 'socketIO_client'
```
