### ISSUE TITLE
Deploy Failed: heroku: command not found

### ISSUE THREAD

**Issue by shawnmclean** [travis-ci/travis-ci#5680]
I've been trying to get Deployment to Heroku on multiple repositories, all of which is giving the following error:

```
Fetching: dpl-1.8.12.gem (100%)
Successfully installed dpl-1.8.12
1 gem installed
/home/travis/build.sh: line 45: heroku: command not found
invalid option "--api_key="
failed to deploy
```

I have started a project from scratch, with the following yml:

```
language: node_js
node_js:
  - stable
deploy:
  provider: heroku
  api_key:
    secure: <key here>
```
See: https://github.com/Samelogic/Core

I've also copied a working travis-ci project that has deployments to heroku working, with the exact repository except the api_key and I get the same error.

See: https://github.com/shawnmclean/heroku-test copied from the working repo https://github.com/slashroots/slashroots-website-v2

The yml file looks like this:

```
language: node_js
node_js:
- stable
- '0.12'
deploy:
  api_key:
    secure: <key>
  provider: heroku
  strategy: api
  on:
    all_branches: false
  app:
    master: slashroots-website-staging
    production: slashroots-website-prod

```

Build log: https://travis-ci.org/shawnmclean/heroku-test/jobs/111125302

Api key generated by `travis encrypt $(heroku auth:token) --add deploy.api_key`

Is there something I'm missing?
