### ISSUE TITLE
travis-ci updating (user) pip install

### ISSUE THREAD

**Issue by gliptak** [travis-ci/travis-ci#5703]
Running with following ```.travis.yml```:

```
    language: java
    sudo: false
    jdk: oraclejdk8

install:
  - pip --version
  - pip install --user --upgrade pip
  - pip --version
```

I get this output (note ```Successfully installed pip-6.0.8```):

    $ pip --version
    pip 6.0.8 from /usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg (python 2.7)
    $ pip install --user --upgrade pip
    You are using pip version 6.0.8, however version 8.0.3 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    Collecting pip from https://pypi.python.org/packages/py2.py3/p/pip/pip-8.0.3-py2.py3-none-any.whl#md5=b234250205337ff67967dff300001e3d
      Downloading pip-8.0.3-py2.py3-none-any.whl (1.2MB)
         100% |################################| 1.2MB 492kB/s 
    Installing collected packages: pip
    Successfully installed pip-6.0.8
    $ pip --version
    pip 6.0.8 from /usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg (python 2.7)

Is there a recommended way to bring ```pip``` up-to-date (in a ```sudo: false``` environment)?

Thanks
