### ISSUE TITLE
language: r not installing rmarkdown from github

### ISSUE THREAD

**Issue by stephlocke** [travis-ci/travis-ci#5729]
Trying to get the new `language: r` set up working for non-package material.

I have a .travis.yml [file](https://github.com/stephlocke/chartgallery/blob/master/.travis.yml) that contains the following:
```
language: r
cache: packages
r_packages:
  - devtools
r_github_packages:
  - rstudio/rmarkdown
install:
  - chmod 755 .push_gh_pages.sh
  - chmod 755 ghgenerate.R
script:
  - ./.push_gh_pages.sh
```

However, when it comes time to render the rmarkdown document, it says rmarkdown is not installed. See [R output](https://github.com/stephlocke/chartgallery/blob/gh-pages/ghgenerate.Rout)

Hopefully I'm just doing something daft, but I can't see any installation points for rmarkdown in the [travis log](https://travis-ci.org/stephlocke/chartgallery/builds/113157440). How do I most easily verify it's installing and is there anything obviously wrong with my travis file?

cc @craigcitro, @hadley, and @jimhester

**Comment by jimhester** [comment]
The packages are installed during the `install` step, which you are overriding with a custom step. The default install step also expects a package so you can't just use it directly.

I would suggest you just install the package manually

```yaml
language: r
cache: packages
install:
  - Rscript -e 'install.packages("devtools");devtools::install_github("rstudio/rmarkdown")'
  - chmod 755 .push_gh_pages.sh
  - chmod 755 ghgenerate.R
script:
  - ./.push_gh_pages.sh
```
