### ISSUE TITLE
.travis.yml files should support an "include" directive

### ISSUE THREAD

**Issue by branan** [travis-ci/travis-ci#574]
If you have several related repositories, it's not unusual for them to need the same (or very similar) CI configurations. Supporting an "include" directive would allow that common configuration to be in one place, and thus be updated all at once.

For example, I could have my `.travis.tml` file with the simple contents

```
include:
  - http://raw.github.com/branan/modules_common/master/travis.yml
```

and then have `http://raw.github.com/branan/modules_common/master/travis.yml` with

```
language: ruby
rvm:
  - 1.8.7
  - 1.9.3
script: "rake spec"
branches:
  only:
    - master
env:
  - PRODUCT_VERSION=2.7.13
  - PRODUCT_VERSION=2.7.9
  - PRODUCT_VERSION=2.6.9
notifications:
  email: false
gemfile: .gemfile
```

Then when the supported matrix of product versions and rubies changes, I only have to update one file. I'm looking at using Travis for potentially dozens of small repos, so not having this feature would be a maintenance nightmare for me.
