### ISSUE TITLE
Package in subdirectory

### ISSUE THREAD

**Issue by MansMeg** [travis-ci/travis-ci#5775]
Hi @craigcitro, @hadley and @jimhester!

Im trying to run a package in Travis where the package itself is a subdirectory of the github repository. I can't find a way to do this with your Travis file. 

Thanks for all your work with this!

**Comment by jimhester** [comment]
It is says you need to specify your own `install:` and `script:` steps in your `.yaml` if you are using a non-standard repository layout. If your package is in the `Package` directory you could use the following

```r
install:
  - Rscript -e 'devtools::install_deps("Package")'
script:
  - Rscript -e 'devtools::check("Package")'
```

**Comment by MansMeg** [comment]
Hi!

I still get a problem when building:
```
0.01s
0.50sadding /home/travis/R/Library to cache
R-session-info
R session information
$ Rscript -e 'sessionInfo()'
R version 3.2.3 (2015-12-10)
Platform: x86_64-pc-linux-gnu (64-bit)
locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
attached base packages:
[1] stats     graphics  grDevices utils     datasets  base     
0.17s$ Rscript -e 'devtools::install_deps("RPackage")'
Error in loadNamespace(name) : there is no package called ‘devtools’
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
The command "Rscript -e 'devtools::install_deps("RPackage")'" failed and exited with 1 during .
Your build has been stopped.
```
The ```.travis.yml```looks as follows:
``´
# Native R Travis Github

language: r
sudo: required
cache: packages

# Be strict when checking our package
warnings_are_errors: false

# Specify folder
install:
  - Rscript -e 'devtools::install_deps("RPackage")'
script:
  - Rscript -e 'devtools::check("RPackage")'


r_github_packages:
  -  jimhester/covr

#after_success:
#  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
```

**Comment by jimhester** [comment]
Yes you need to install devtools first.

`- Rscript -e 'install.packages("devtools");devtools::install_deps("RPackage")'`

**Comment by MansMeg** [comment]
Hi!

Thanks for the help! I now got it to work with this Travis yml
```
install:
  - Rscript -e 'install.packages(c("devtools","roxygen2","testthat"));devtools::install_deps("RPackage")'
script:
  - Rscript -e 'devtools::check("RPackage")'
```

Maybe add this to the R Travis documentation?

**Comment by ellisp** [comment]
This worked for me too in two different packages with the same directory structure.  It would be great if this example could be added to https://docs.travis-ci.com/user/languages/r.

```
# thanks to https://github.com/travis-ci/travis-ci/issues/5775
sudo: false

language: r
r:
  - oldrel
  - release
  - devel

cache: packages

install:
  - Rscript -e 'install.packages(c("devtools","roxygen2","testthat"));devtools::install_deps("pkg")'
script:
  - Rscript -e 'devtools::check("pkg")'
  
notifications:
  email:
    on_success: change
    on_failure: change
```
