### ISSUE TITLE
R library location in container builds

### ISSUE THREAD

**Issue by karldw** [travis-ci/travis-ci#5776]
Travis successfully installs R packages into `/home/travis/R/Library`, but a call to `.libPaths()` tells me R is searching for packages in `/home/travis/R-bin/lib/R/library` (as well as some `/tmp/` directory).
I think these paths should be the same, yes?

Of course it's possible to work around these differences, but it would be nice if we didn't have to.

The original issue is IRkernel/repr#32.  The Travis log is [here](https://travis-ci.org/IRkernel/repr/builds/115136287).
Here's the .travis.yml; nothing crazy with paths.
```yml
language: r
sudo: false
cache: packages
r_check_revdep: false
repos:
  CRAN: https://cloud.r-project.org
  IRkernel: https://irkernel.github.io/
git:
  depth: 1
r_packages:
  - highr
  - Cairo
  - data.table
  - dplyr
addons:
  apt:
    packages:
      - libcairo2-dev
      - libjpeg-dev
```

cc from original issue: @flying-sheep, @JanSchulz
cc: @craigcitro, @hadley and @jimhester

Related: #4641

**Comment by jimhester** [comment]
https://github.com/karldw/repr/pull/1 fixes the issue.

**Comment by karldw** [comment]
Thanks!

**Comment by flying-sheep** [comment]
thanks for the workaround!

hoever, `r_packages` should still install to a location where R can find the packages, so this issue is still valid, right?

**Comment by jimhester** [comment]
`r_packages` is working properly. The reason the packages weren't being found in your tests is because R CMD check modifies the library path during the check to only include packages specified in `Depends`, `Imports`, `LinkingTo` or `Suggests` in roder to detect packages which fail to list all their dependencies appropriately.

**Comment by flying-sheep** [comment]
ah, got it!

**Comment by flying-sheep** [comment]
OK, you should probably modify how you call R CMD check then.

in the repr package,`data.table` clearly belongs into `Enhances:` (our package provides optional enhancements for it), but i still want to test those enhancements.

[failing build](https://travis-ci.org/IRkernel/repr/builds/125862218) illustrating this.

**Comment by janschulz** [comment]
Probably a `Additional-Test-Depends:` field...

**Comment by jimhester** [comment]
This isn't a travis issue, you will see the same error running `R CMD check` locally unless you are either installing all your packages into the `.Library` location or using the default location of `R_LIBS_USER`. `R CMD check` internally sets `R_LIBS_USER=""`, `R_LIBS_SITE=""`, `R_LIBS=location_with_only_depends_includes_suggests` ([tools/R/check.R](https://github.com/wch/r-source/blob/trunk/src/library/tools/R/check.R#L56-L171)) and runs the tests with `R CMD BATCH --vanilla` (https://github.com/wch/r-source/blob/trunk/src/library/tools/R/testing.R#L436-L439) which disables reading of site or user specific startup files.

[Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Package-Dependencies) clearly states packages in `Enhances:` must always be used conditionally in tests.
> Such packages cannot be required to check the package: any tests which use them must be conditional on the presence of the package.

So you really should be using something akin the the following in your test files
```r
if (requireNamespace("data.table", quietly = TRUE)) {
  # tests using data.table functions
}
```
Only 1.58% of packages on CRAN (131/8314 as of today) have anything in `Enhances` so this is not a very common issue.

One workaround (untested) would be to do the following in your `.travis.yml`, which will override the location of `R_LIBS_USER` set by travis to the default one used by R on linux.

```yaml
env:
  - R_LIBS_USER=~/R/x86_64-pc-linux-gnu-library/3.2

before_install:
  - mkdir -p $R_LIBS_USER
```
