### ISSUE TITLE
Make `composer` run without xdebug

### ISSUE THREAD

**Issue by staabm** [travis-ci/travis-ci#5780]
Per https://getcomposer.org/doc/articles/troubleshooting.md#xdebug-impact-on-composer it is recommended to run `composer` without xdebug extensions beeing loaded to increase runtime performance by 3x. 
would be great when the default `composer` command available in php builds would not run with xdebug.
I guess not loading xdebug with `php` itself would be too much of a Bc break, so doing it on composer only would seem like a good fit. `composer install` takes most of the time in small/mid-sized php-projects (a lot more then most unit suites take)

See e.g. https://travis-ci.org/fruux/sabre-xml/jobs/113732266

**Comment by hkdobrev** [comment]
Just to note if you have configured `composer test` to run PHPUnit tests together with code coverage, that would be a problem.

**Comment by staabm** [comment]
@hkdobrev do you use this setup somewhere? Never seen it in the wild...?

All projects I am aware of use the `phpunit` command

**Comment by hkdobrev** [comment]
Personally I've just started using `composer test`, but I see used by more and more people. Probably the reason is that it is supported without the `run-script` command and is in the official documentation: https://getcomposer.org/doc/articles/scripts.md#writing-custom-commands

**Comment by hkdobrev** [comment]
People could always add a CLI option to load the xdebug extension in `composer test` definition, but this is something to be mindful as most people wouldn't have done that.

**Comment by hkdobrev** [comment]
Another example is Composer repo itself: https://github.com/composer/composer/blob/1dce6442ed2518855d096d1123f04472d9b6f764/composer.json#L64-L66

**Comment by staabm** [comment]
Add a additional extension (with php -d) is way easier then removing one which is loaded by default - as you need to load php without a ini and replicate all settings/extensions which where available/configured  in the default.

Therefore I would still prefer not loading xdebug with `composer` by default (this will also free a lot of travis resources because of saved time of the build jobs). 

People using this composer-scripts can alias any command-name to phpunit, so we can only do a all or nothing IMO

**Comment by hkdobrev** [comment]
I support your thinking. Also Travis CI could probably check how many projects have `script: composer test` and if that is a small number, then this affecting coverage reports has a really small chance.

**Comment by BanzaiMan** [comment]
We have documented how to disable `xdebug` here: https://docs.travis-ci.com/user/languages/php#Disabling-preinstalled-PHP-extensions

Did it not work?

**Comment by staabm** [comment]
@BanzaiMan see e.g. https://github.com/fruux/sabre-xml/blob/master/.travis.yml#L19

Xdebug is required for the `phpunit` call to generate a unit test coverage report but it is not required for the `composer install` call in the before-script.

The `composer install` command would be up to 3x faster without xdebug.

Atm, using the mentioned config, we can only disable xdebug for the whole build. But we instead need it be disabled only for certain commands.

**Comment by BanzaiMan** [comment]
I think the reverse of `config-rm` is `config-add`. You can use these to disable/enable `xdebug` as you see fit.

**Comment by staabm** [comment]
What is the correct path to re-add the xdebug.ini?

```
$ phpenv config-add ~/.phpenv/versions/$(phpenv version-name)/etc/xdebug.ini
File /home/travis/.phpenv/versions/5.4/etc/xdebug.ini does not exist.
```

**Comment by staabm** [comment]
even if we get `phpenv` to run with `config-rm` + `config-add` this will not work as long as `phpenv` doesnt properly support hhvm.

IMO the best "workaround" would be to invoke composer like recommended in the troubleshooting guide:
https://getcomposer.org/doc/articles/troubleshooting.md#xdebug-impact-on-composer
(by creating a local method which invokes composer with xdebug disabled)

see example-code copied from the above url:
```sh
echo 'function composer() { COMPOSER="$(which composer)" || { echo "Could not find composer in path" >&2 ; return 1 ; } && sudo php5dismod -s cli xdebug ; $COMPOSER "$@" ; STATUS=$? ; sudo php5enmod -s cli xdebug ; return $STATUS ; }' >> ~/.bash_aliases
. ~/.bash_aliases
```

**Comment by theofidry** [comment]
Another solution that worked for me @staabm is: to register the following function:

```bash
function composer()
{
  mv /home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/xdebug.ini
  COMPOSER="$(which composer)"
  $COMPOSER "$@"
  STATUS=$?
  mv ~/xdebug.ini /home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini

  return $STATUS
}
```

It's not the most efficient one (you have a double `mv` done on each `composer` call, but it's quite simple and does not require anything extravagant.

**Comment by theofidry** [comment]
Update: this can actually break on some builds (e.g. PHP 7.1) where there is no `xdebug.ini` file. Instead I'm using the following:

```bash
XDEBUG_INI="/home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini"
if [ ! -f "$XDEBUG_INI" ]; then
    return
fi

function composer()
{
  mv $XDEBUG_INI ~/xdebug.ini
  COMPOSER="$(which composer)"
  $COMPOSER "$@"
  STATUS=$?
  mv ~/xdebug.ini $XDEBUG_INI

  return $STATUS
}
```

@BanzaiMan any chance to have than natively on Travis builds? I've been successfully using it from PHP 5.3 to nightly (7.2-dev) works like a charm.

**Comment by Seldaek** [comment]
Note that Composer 1.3 will come with a workaround to disable xdebug automatically, so in the future this won't be needed anymore.

**Comment by PowerKiKi** [comment]
For the record, Seldaek was referencing that PR: https://github.com/composer/composer/pull/5580

**Comment by localheinz** [comment]
Using this for `.travis/xdebug.sh`:

```sh
#!/usr/bin/env bash

# The problem is that we do not want to remove the configuration file, just disable it for a few tasks, then enable it
#
# For reference, see
#
# - https://docs.travis-ci.com/user/languages/php#Disabling-preinstalled-PHP-extensions
# - https://docs.travis-ci.com/user/languages/php#Custom-PHP-configuration

config="/home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini"

function xdebug-disable() {
    if [[ -f $config ]]; then
        mv $config "$config.bak"
    fi
}

function xdebug-enable() {
    if [[ -f "$config.bak" ]]; then
        mv "$config.bak" $config
    fi
}
```

and then `.travis.yml`:

```yml
matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: WITH_CS=true
    - php: 7.1
      env: WITH_COVERAGE=true
    - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - source .travis/xdebug.sh
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then xdebug-disable; fi
  - composer self-update
  - composer validate
  - composer config github-oauth.github.com $GITHUB_TOKEN

install:
  - composer install --prefer-dist

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"
  - mkdir -p build/logs

script:
  - if [[ "$WITH_COVERAGE" == "true" ]]; then xdebug-enable; fi
  - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/phpunit --configuration=test/Unit/phpunit.xml --coverage-clover=build/logs/clover.xml; else vendor/bin/phpunit --configuration=test/Unit/phpunit.xml; fi
  - if [[ "$WITH_COVERAGE" == "true" ]]; then xdebug-disable; fi
  - vendor/bin/phpunit --configuration=test/Integration/phpunit.xml
  - if [[ "$WITH_CS" == "true" ]]; then vendor/bin/php-cs-fixer fix --config=.php_cs --verbose --diff --dry-run; fi

after_success:
  - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/test-reporter --coverage-report=build/logs/clover.xml; fi
```

💁‍♂️ The point is, disable xdebug generally as early as possible (first thing in `before_install` step, basically), and then only enable it for steps where it is actually needed. No need to keep servers busy for no real need, right?
