### ISSUE TITLE
Support for Xamarin.iOS

### ISSUE THREAD

**Issue by mattleibow** [travis-ci/travis-ci#5786]
Hi awesome teams! I just wanted to find out your thoughts on having a Xamarin.iOS Mac image... I am going to be doing a few builds using the Xamarin tools. I know you have the Mono image, but if I want to do iOS or Mac development using C#, I have to install everything myself.

Here is one of my builds: https://travis-ci.org/mattleibow/CrossPlatformBuild/builds/116038684 As you can see, the install takes about 6 minutes just to install Mono and Xamarin.iOS before running the build. Here is the repo that I am building: https://github.com/mattleibow/CrossPlatformBuild

Basically, the Xamarin install is just a mac image with two extra packages:

 - Mono: http://download.mono-project.com/archive/4.3.2/macos-10-universal/MonoFramework-MDK-4.3.2.macos10.xamarin.universal.pkg
 - Xamarin.iOS: http://download.xamarin.com/MonoTouch/Mac/monotouch-9.4.2.27.pkg

And if I was going to do Xamarin.Mac development:

 - http://download.xamarin.com/XamarinforMac/Mac/xamarin.mac-2.4.1.7.pkg

There is the option to do Xamarin.Android development, but that is not so essential as I can do that on Windows using AppVeyor.

The nice thing about the iOS and Mac is that everything else is already there, just the Xamarin bit is missing.

**Comment by brunofarache** [comment]
For those interested, I got it working with Xamarin.Android as well, here's how my travis file looks like:

```yaml
os:
  - osx

env:
  global:
    - MONO_VERSION=4.6.2
    - MONO_ANDROID_VERSION=7.0.2-42

install:
  - export COMPONENTS=build-tools-25.0.1,android-24,extra-android-support,extra-google-google_play_services,extra-google-m2repository,extra-android-m2repository
  - export LICENSES=android-sdk-license-c81a61d9
  - curl -L https://raw.github.com/embarkmobile/android-sdk-installer/version-2/android-sdk-installer | bash /dev/stdin --install=$COMPONENTS --accept=$LICENSES
  - source ~/.android-sdk-installer/env
  - wget "http://download.mono-project.com/archive/${MONO_VERSION}/macos-10-universal/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.universal.pkg"
  - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.universal.pkg" -target /
  - wget "https://dl.xamarin.com/MonoforAndroid/Mac/xamarin.android-${MONO_ANDROID_VERSION}.pkg"
  - sudo installer -pkg "xamarin.android-${MONO_ANDROID_VERSION}.pkg" -target /
  - /Library/Frameworks/Mono.framework/Commands/nuget restore solution.sln

script:
  - /Library/Frameworks/Mono.framework/Commands/xbuild /t:SignAndroidPackage /p:Configuration=Release Droid/solution-name.csproj
```

It takes around 20 minutes to build. We really need an image for Xamarin, it would drop build time to few minutes.

Here's a proposal for a Xamarin image configuration file:

https://gist.github.com/brunofarache/b73e89e52da7da287a91960058b45f89
