### ISSUE TITLE
Android builds failing - failed to find 'android-23'

### ISSUE THREAD

**Issue by andrewlord1990** [travis-ci/travis-ci#5797]
All my Android builds have started failing today with:

failed to find target with hash string 'android-23' in: /usr/local/android-sdk

.travis.yml
```yaml
language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-android-support
    - extra-android-m2repository
```

https://travis-ci.org/andrewlord1990/SnackbarBuilder
https://travis-ci.org/andrewlord1990/materialandroid
