### ISSUE TITLE
postgresql is not installed if language is set to generic

### ISSUE THREAD

**Issue by jgillich** [travis-ci/travis-ci#5799]
I switched from `language: rust` to `generic` and now I'm getting this in the logs:
```sh
$ sudo service postgresql start
postgresql: unrecognized service
```
`.travis.yml`:
```yml
language: generic
sudo: required
dist: trusty
services:
  - postgresql
# ...
```
https://travis-ci.org/jgillich/mp/builds/117094037#L100
