### ISSUE TITLE
Deploy stage creates `.dpl` directory, which can cause problems with building docker images

### ISSUE THREAD

**Issue by ujovlado** [travis-ci/travis-ci#5803]
Assume you have following configuration:

`Dockerfile`:
```Dockerfile
ADD . /somewhere
```

`.travis.yml`:
```yaml
script:
  - docker build -t vendor/image .

deploy:
  provider: script
  script: ./deploy.sh
  on:
    tags: true
```

`deploy.sh`:
```bash
#!/bin/bash

docker build -t vendor/image
docker tag ...
docker login ...
docker push ...
```

Deploy stage creates `.dpl` directory, which causes that current working directory is not the same and will create new layer instead of using cache.

And `.dpl` directory will be added to your image, which can be a bit confusing.
