### ISSUE TITLE
apt sources that are disallowed don't fail a build

### ISSUE THREAD

**Issue by reconbot** [travis-ci/travis-ci#5833]
I've been trying out the docker builds and they're great. I wanted to use the experimental `addons:apt:sources` feature and tried to add a disallowed source. My build ran and failed in a weird way.  The wrong version of the package I wanted was installed, leading to a very long debugging session.

Eventually I figured out my source wasn't added and it all made sense. If the build **failed** when the source couldn't be added, I'd have known right away I couldn't do what I wanted.

The relevant bits of my `.travis.yml`

``` yml
addons:
  apt:
    sources:
      - ppa:ansible/ansible
    packages:
      - ansible
```

I've since requested my source be added too.

Thanks!
