### ISSUE TITLE
hang with misconfigured matrix: include

### ISSUE THREAD

**Issue by jayvdb** [travis-ci/travis-ci#5835]
https://travis-ci.org/jayvdb/travis-oracle/builds/119484395 has hung, and even the cancel build button is missing.

The cause is probably that I added:

```
matrix:
  include:
    dist: trusty
    dist: precise
```

instead of using hyphens

```
matrix:
  include:
    - dist: trusty
    - dist: precise
```
