### ISSUE TITLE
Need node.js v4 with an android project - not working

### ISSUE THREAD

**Issue by djMax** [travis-ci/travis-ci#5838]
The following .travis.yml (abridged a bit) does not yield an build environment with node v4.4. I've tried other potential variants, but no luck:

```
matrix:
  include:
    - language: android
      env: BUILD_ITEM=android
      node_js: "4.4"
      android:
        components:
          - platform-tools
          - tools
          - platform-tools
          - build-tools-23.0.2
          - android-23
```
