### ISSUE TITLE
Deploy to GitHub Releases

### ISSUE THREAD

**Issue by rubak** [travis-ci/travis-ci#5841]
Hi @jimhester, @craigcitro and @hadley,
Thanks for adding official R support on travis-ci. I've been trying it out for a couple of days now.
I would like to use travis-ci to deploy an R package to GitHub Releases. I build the package with both R-devel and R-release and I would like to only deploy for R-release. To achieve this I tried to add conditional deployment like this (only relevant yaml lines shown here):
```yaml
deploy:
  on:
    r: release
```
This is inspired by the ruby yaml [here](https://docs.travis-ci.com/user/deployment#Examples-of-Conditional-Releases-using-on%3A):
```yaml
deploy:
  on:
    rvm: 2.0.0
```
However, in my case deployment happens for both R-devel and R-release (you can see that deployment happens for all the builds [here](https://travis-ci.org/baddstats/polyclip/builds/119751437)). Am I doing something wrong or is this feature simply not available for R?

Somewhat related: From looking at the r.rb on GitHub it appears `TRAVIS_R_VERSION` is exported and I guess I potentially could use the value of that to condition on. Is that correctly understood? Is there a list of all exported environment variables somewhere (I also spotted `PKG_TARBALL` which could potentially be useful)?

If I find a good way to deploy I could offer to write a few lines for the documentation if you like.

**Comment by jimhester** [comment]
That syntax for rvm must be a custom extension for ruby code, so the equivalent for R won't work (as you discovered). (the code in question seems to be https://github.com/travis-ci/travis-build/blame/b7e1109cbc0af202f40b1922a8a7a181815f0f0b/lib/travis/build/addons/deploy/config.rb#L31-L37)

Looking at the code briefly I am not sure you will be able to filter using the built in deploy by any method. As I don't see a way to pass a boolean condition to the `on` block. However we may be able to add `:r` to the `RUNTIMES`, which should then allow (I think) the syntax you suggest. @BanzaiMan please correct me if I am mistaken.

https://github.com/travis-ci/docs-travis-ci-com/pull/531 adds documentation on the available environment variables used in `language: r`, but it has not yet been merged.

**Comment by rubak** [comment]
Thanks for the quick reply. I now found out there is a explicit list of languages that support the syntax I tried to use and R is not on it ( only **`jdk`**, **`node`**, **`perl`**, **`php`**, **`python`**, **`ruby`**, **`scala`**, **`go`** -- see item 3 [here](https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A)).

I think I have found a decent alternative way to deploy which I now use (only relevant lines below):
```yaml
after_success:
- if [[ "$TRAVIS_R_VERSION" != "devel" && ("$TRAVIS_OS_NAME" == "osx") ]]; then R CMD INSTALL --build $PKG_TARBALL; fi
deploy:
  skip_cleanup: true
  file_glob: true
  file: myDefaultPackage_*.t*gz
  on:
    tags: true
    condition: "$TRAVIS_R_VERSION != devel && ($TRAVIS_OS_NAME == osx)"
```
Here `myDefaultPackage` is the name of the package and I only deploy on OSX since that gives me both `.tar.gz` and `tgz`. I use that in my case `$TRAVIS_R_VERSION != devel` implies that R release is running. It might be better to replace by `$TRAVIS_R_VERSION == 3.2.4`, but this would have to be updated every once in a while. Is there another way you could check that R release is running without referring to a specific version number?

From my point of view the issue is solved and we can go ahead and close it. Again, let me know if you want me to draft some lines for documentation.

**Comment by BanzaiMan** [comment]
```yaml
deploy:
  on:
    r: release
```
works now. https://travis-ci.org/BanzaiMan/travis_production_test/builds/140881908#L455
