### ISSUE TITLE
Build using import rgdal fails

### ISSUE THREAD

**Issue by MartinRoth** [travis-ci/travis-ci#5852]
@craigcitro @hadley  @jimhester

Hi,

I am trying to use travis for checking an R package that uses rgdal (https://travis-ci.org/MartinRoth/knmiR). However, I get the following error:
checking package dependencies ... ERROR
Package required but not available: ‘rgdal’

I put GDAL into the system requirements, with no success so far. Any suggestions?

Cheers,
Martin

**Comment by jimhester** [comment]
rgdal requires the gdal and proj4 headers and libraries to be installed on your system.

Try using the following
```yaml
language: r
sudo: false
cache: packages
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
```
