### ISSUE TITLE
Feature request: Template option for Slack Notification like the one that already exists for IRC notifications 

### ISSUE THREAD

**Issue by palewire** [travis-ci/travis-ci#5871]
I am a pro user and I think it would be cool if I could customize our Slack messages much in the way is already allowed for [IRC messages](https://docs.travis-ci.com/user/notifications/#IRC-notification).

**Comment by BanzaiMan** [comment]
The feature is undocumented but it exists. One issue is that, currently, Slack notification uses different templates for Push builds and PR builds. The `template` option does not possess such a functionality.

**Comment by OJFord** [comment]
@BanzaiMan Do you mean [this](https://github.com/travis-ci/travis-tasks/blob/master/lib/travis/addons/slack/task.rb#L6-L7)? As it isn't documented, could you explain? Just adding `template` doesn't work.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-tasks/blob/907d7826/lib/travis/addons/slack/task.rb#L79-L81

It should be defined like this:

```yaml
notifications:
  slack:
    template:
      - FOOBAR
```

**Comment by OJFord** [comment]
@BanzaiMan I'm doing:
```
notifications:
  slack: <team>:<token>#<channel>
    template:
      - "FOOBAR %{result}"
```

But still getting the default message.

**Comment by BanzaiMan** [comment]
That seems invalid YAML to me.

**Comment by BanzaiMan** [comment]
I just tested this and it works (including the typo).

```yaml
notifications:
  email: false
  slack:
    rooms:
      - secure: "XXXXXXXXXXX"
    template:
      - COMPLETELY STATCK AND THEREFORE USELESS MESSAGE
```

![slack](https://cloud.githubusercontent.com/assets/25666/15425230/bb6fbf38-1e22-11e6-9270-55414a0c1633.png)
