### ISSUE TITLE
APT caching doesn't work for packages installed with the APT addon

### ISSUE THREAD

**Issue by tlvince** [travis-ci/travis-ci#5876]
Given a `.travis.yml` that looks something like the following:

```yaml
language: "node_js"
node_js: "stable"
sudo: false
addons:
  apt:
    sources:
      - "ubuntu-toolchain-r-test"
    packages:
      - "g++-4.8"
cache:
  apt: true
  directories:
    - node_modules
```

… I would expect the "g++-4.8" package to be cached between runs. However, both the apt source and package are re-downloaded between runs.

Although it is not my project, commonform-serve-permissions (found via GitHub search for "apt cache addons") uses a near-identical [travis.yml](https://github.com/commonform/commonform-serve-permissions/blob/84adc27b9a472ab53a870fa12a99db15f5bec656/.travis.yml) to mine (private repo). As you can see in its [build](https://travis-ci.org/commonform/commonform-serve-permissions/builds/109075801#L101), both the "Adding APT Sources (BETA)" and "Installing APT Packages (BETA)" blocks are ran and "nothing changed, not updating cache" shown.

Is the following the correct syntax for APT addon caching (with additional arbitrary directories)?

```yml
cache:
  apt: true
  directories:
    - node_modules
```

**Comment by BanzaiMan** [comment]
I think there is a misunderstanding of what APT caching did.

APT caching was meant to speed up apt install for private repositories when the connexion to remote APT sources was slow, by adding mirrors of such remote sources to a local APT server. It worked only for private repositories running on the legacy infrastructure. It never worked for public repositories, and not for containers (which https://travis-ci.org/commonform/commonform-serve-permissions/builds/109075801#L101 is running on).

As the new infrastructures does not have APT caches set up, we have removed the mention of it (https://github.com/travis-ci/docs-travis-ci-com/commit/bd8b56d501dbb47f76d139831c99f55ac69d1314) from our docs.

Caches are restored *after* the APT addon has run, so adding an APT package is not going to be effective.

**Comment by tlvince** [comment]
Makes sense. Thanks!

**Comment by ORESoftware** [comment]
yeah is there any way to cache this:

```yaml
addons:
  apt:
    sources:
      - "ubuntu-toolchain-r-test"
    packages:
      - "g++-4.8"
```

kinda sucks to download it each time
