### ISSUE TITLE
Cannot exclude on OS and multiple ENV

### ISSUE THREAD

**Issue by reconbot** [travis-ci/travis-ci#5877]
Hi,
I'm trying to reduce the number of builds we do on OSX on the x86 environment for [node-serialport](https://travis-ci.org/voodootikigod/node-serialport).

Our yaml looks a bit like this
```yaml
# Build matrix
os:
- linux
- osx
env:
  matrix:
  - TRAVIS_NODE_VERSION="0.10"
  - TRAVIS_NODE_VERSION="0.10" ARCH="x86"
  - TRAVIS_NODE_VERSION="0.12"
  - TRAVIS_NODE_VERSION="0.12" ARCH="x86"
  - TRAVIS_NODE_VERSION="4"
  - TRAVIS_NODE_VERSION="4" ARCH="x86"
  - TRAVIS_NODE_VERSION="5"
  - TRAVIS_NODE_VERSION="5" ARCH="x86"
  exclude:
  - os: osx
    env: TRAVIS_NODE_VERSION="0.10" ARCH="x86"
  - os: osx
    env: TRAVIS_NODE_VERSION="0.12" ARCH="x86"
  - os: osx
    env: TRAVIS_NODE_VERSION="4" ARCH="x86"
  - os: osx
    env: TRAVIS_NODE_VERSION="5" ARCH="x86"
```

But the `exclude` isn't working at all. We still have 8 osx builds when we could have 4. Is there a way to do this?

Thanks!

**Comment by BanzaiMan** [comment]
You only have `env.matrix` and `env.exclude`, and the latter does nothing.

In order to exclude jobs, you need `matrix.exclude`. See https://docs.travis-ci.com/user/customizing-the-build/#Excluding-Jobs

Try something like:

```yaml
# Build matrix
os:
- linux
- osx
env:
  matrix:
  - TRAVIS_NODE_VERSION="0.10"
  - TRAVIS_NODE_VERSION="0.10" ARCH="x86"
  - TRAVIS_NODE_VERSION="0.12"
  - TRAVIS_NODE_VERSION="0.12" ARCH="x86"
  - TRAVIS_NODE_VERSION="4"
  - TRAVIS_NODE_VERSION="4" ARCH="x86"
  - TRAVIS_NODE_VERSION="5"
  - TRAVIS_NODE_VERSION="5" ARCH="x86"
matrix:
  exclude:
  - os: osx
    env: TRAVIS_NODE_VERSION="0.10" ARCH="x86"
  - os: osx
    env: TRAVIS_NODE_VERSION="0.12" ARCH="x86"
  - os: osx
    env: TRAVIS_NODE_VERSION="4" ARCH="x86"
  - os: osx
    env: TRAVIS_NODE_VERSION="5" ARCH="x86"
```
