### ISSUE TITLE
PyPI deployment appears not to build dists

### ISSUE THREAD

**Issue by jtpereyda** [travis-ci/travis-ci#5895]
See [this build](https://travis-ci.org/jtpereyda/boofuzz/builds/122636994) for example.

````
Deploying application
running sdist
running egg_info
writing requirements to boofuzz.egg-info/requires.txt
error: [Errno 13] Permission denied: 'boofuzz.egg-info/requires.txt'
ValueError: Cannot find file (or expand pattern): 'dist/*'
running upload_docs
creating build
creating build/docs
error: no files found in upload directory 'build/docs'
```

Some inserted debug commands show that there is indeed no dist folder. Why is this? The log indicates that it is "running sdist", but how I can I find out why it's not resulting in an actual sdist?

Current `.travis.yml`:

````
language: python
sudo: required
before_install: sudo sed -i -e 's/^Defaults\tsecure_path.*$//' /etc/sudoers
install: pip install tox
script:
- sudo tox
before_deploy:
- pwd
- ls
deploy:
  provider: pypi
  user: jtpereyda
  password:
    secure: fVupJXYZ9JM+nkSZhBHZAxFIh+1Vzpccf3A3IkTvrXAkNu3H1KkfXnvq/3E6ffQSBkNiIBCw1zNn17BYCbcmhyvlk4uvT2T3pG2lHfaqCkyEB//wvjxhKDQCjRwR0Duf30tUXmrSLTZdUDxNP+vXS5Vx0zaEx+srAaj9Ah74xpA6766kTJR95RWtzksZ5ckMSkxOFimrv03zcBcz2jiNkv08ysXoliNTTCdhHNmokkfGAnBNmozyPW+VhIec0uLo4mu7DOopAvGjEO9ObHYCTESXCuTfW/9kTkBDYORPd/aQ4yaR5zJfQlx1DYhITly4g8VH7eSSGKhnTOTeZWVMdsT9gGHjh5oDnKbkPjiWgkm4F45IREZcQGmhKQhn9uqAaCV/RvK8kOygyiIvwo9JZUJaZLOERQF95PboR3vpXHyWYXU+fQbAiR2S53G8YJRS1abCkPYqnwYqlQI4Ig1tK0IJfmSWxtT+qbUvfSd1ghJsl7MK0hFfsv09nZ3Sx+x4tXBQbjKWDrZzEEiAXn4NWH/HpuOpB6Xwy4z43YxU7lXoqJpwr47HmBZE5JpnYtKodnLgCUbYrVdR/opZ8YWLn2/gXqQydBcELWyMnKB+NHk0QSzNbF/1u6bv6nX+NBOHB8inRc8SYd+hFNdcvOhdy1NoMCgUh35hd4CIMhg0unY=
  distributions: "sdist bdist_wheel"
  skip_cleanup: true
  on:
    tags: true
    repo: jtpereyda/boofuzz
    branch: master
after_deploy:
- pwd
- ls
````
