### ISSUE TITLE
Support for non-package R build

### ISSUE THREAD

**Issue by llaniewski** [travis-ci/travis-ci#5913]
First of all, beautiful job on R support for travis @craigcitro. Also pinging @hadley and @jimhester.

It would be nice if non-packages builds could benefit from the same package installation mechanism that is done for package-build.

What I would like to do:
```yaml
language: r
r_github_packages:
  - rstudio/rmarkdown
script:
  - R -e "rmarkdown::render('test.Rmd')"
```

What I have to do now is:
```yaml
language: r
install:
  - R -e "install.packages('devtools')"
  - R -e "devtools::install_github('rstudio/rmarkdown')"
script:
  - R -e "rmarkdown::render('test.Rmd')"
```

Because the first option will fail with "No DESCRIPTION file found, user must supply their own install and script steps". I know that the DESCRIPTION stores the dependencies for the package, but the install step could be still done for the packages selected in the travis.yml

I would propose a code change (pull request), but I understand that "craigcitro/r-travis" is obsolete and I don't know where the native support is stored.
