### ISSUE TITLE
PHP Unit 4.8 and PHP 5.5 + PHP 5.6 Segmentation Fault

### ISSUE THREAD

**Issue by Garethp** [travis-ci/travis-ci#5920]
Hi there

For a while now I've been getting segmentation faults when trying to run automated builds on Traivs, which happens on both of my versions PHP 5.5 and 5.6 Here's the lines copied from the log

```
PHPUnit 4.8.24 by Sebastian Bergmann and contributors.

....................................../home/travis/build.sh: line 45:  3301 Segmentation fault      (core dumped) ./vendor/bin/phpunit --coverage-clover=build/logs/clover.xml
```

I've read that there's been a couple of issues posted about this before, but I've only seen issues about when PHPUnit fails on PHP7, but I'm not testing against PHP7 and I'm using and older version of PHPUnit, so it seems like a separate issue.

Have you got any insight on this?
Thanks,
Gareth

**Comment by BanzaiMan** [comment]
Please update PHPUnit in your `.travis.yml`. See discussion in https://github.com/travis-ci/travis-ci/issues/5752.

**Comment by Garethp** [comment]
Hi

I'm not specifying my PHPUnit in `.travis.yml`, but in my `composer.json`. My `.travis.yml` looks like this

```yml
language: php

php:
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --no-ansi
  - wget https://scrutinizer-ci.com/ocular.phar
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --coverage-clover=build/logs/clover.xml
  - composer cs

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

notifications:
  email: false
```
And my `composer.json` looks like this

```json
{
	"name": "garethp/php-ews",
	"require": {
		"guzzlehttp/guzzle": "~6.0",
		"ext-curl": "*"
	},
	"scripts": {
		"cs": "./vendor/bin/phpcs --standard=ruleset.xml -np src/ tests/",
		"cbf": "./vendor/bin/phpcbf --standard=ruleset.xml -np src/ tests/",
		"generate": "php bin/generateModels.php && composer cbf"
	},
	"autoload": {
		"psr-4": {
			"jamesiarmes\\PEWS\\": "src/",
			"jamesiarmes\\PEWS\\Test\\": "tests/src"
		}
	},
	"require-dev": {
		"phpunit/phpunit": "~4.8",
		"squizlabs/php_codesniffer": "~2.3",
		"mockery/mockery": "~0.9.4",
		"goetas/xsd2php": "2.*@dev",
		"goetas/xsd-reader": "2.*@dev"
	}
}
```

And the version being run on Travis is `PHPUnit 4.8.24 by Sebastian Bergmann and contributors.` which is the latest build that supports PHP 5.5. Does this mean PHPUnit 5+ are the only versions that will work on Travis?
