### ISSUE TITLE
Failed to deploy error on github releases

### ISSUE THREAD

**Issue by rameshthoomu** [travis-ci/travis-ci#5923]
I am trying to upload log files to github releases using Tags: but finally i am ending up with error message saying Failed to deploy. Below is the error message.

I did below command after add the required changes and mentioned files in deploy section is keeping here..

sudo docker daemon -H tcp://0.0.0.0:$port -H unix:///var/run/docker.sock >> logfile.log 2>&1 &
go test > build-result.txt
and docker container log files location

git add v1.12
git commit v1.12 v1.12
git push --tags

deploy section in .travis.yml file:
```
deploy:
  provider: releases
  api_key: "$GITHUB_API_KEY"
  file: "build-result.txt"
  file: "logfile.log"
  file: "/var/log/docker/*.log"
  skip_cleanup: true
  on:
   tags: true
```
**Error Message:
**
Deploying application

/usr/local/rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/client/releases.rb:86:in `initialize': No such file or directory - /var/log/docker/*.log (Errno::ENOENT)
failed to deploy
