### ISSUE TITLE
Update NuGet to version 3.3

### ISSUE THREAD

**Issue by asbjornu** [travis-ci/travis-ci#5932]
The version of `nuget` installed (`2.8.7`) is so old that [some packages fail to install](https://travis-ci.org/asbjornu/GitVersion/builds/124386724#L1101). While requiring sudo and doing `sudo nuget update -self` works, it would be nice to not have to require sudo to be able to install packages requiring NuGet v3.

Cc: @joshua-anderson @akoeplinger @nterry

**Comment by asbjornu** [comment]
Seems like using `sudo` isn't a walk in the park, after all. I'm having severe issues with [hangs](https://travis-ci.org/asbjornu/GitVersion/builds/126429228) during `sudo nuget restore` and [errors like these](https://travis-ci.org/asbjornu/GitVersion/builds/126428280), if I do `nuget restore` without `sudo`:

```
Access to the path "/home/travis/.config/NuGet/nugetorgadd.trk" is denied.
```

I'm using Mono and NuGet without `sudo` in a few other solutions without problems, so I'm thinking that the problems I'm having in this particular solution are due to the use of `sudo`. I really wish I didn't have to use it.

**Comment by asbjornu** [comment]
I ended up solving this by downloading `nuget.exe` myself and using it instead of the global one. Here's how I did it:

```yaml
before_install:
  - mkdir -p .nuget
  - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono .nuget/nuget.exe # Output NuGet's version number
install:
  - mono .nuget/nuget.exe restore <solution.sln> -Verbosity detailed
  - mono .nuget/nuget.exe install NUnit.Runners -Version 3.2.1 -OutputDirectory ./src/packages
```
