### ISSUE TITLE
Slack Notifications are not generating for build results

### ISSUE THREAD

**Issue by rameshthoomu** [travis-ci/travis-ci#5934]
We have created Slack channel and passed the secure token in .travis.yml file.. Below is the code snippet. I observed slack messages are generating for build failure or pass on slack  channel. 

```yaml
notifications:
   slack:
    secure: yAnJ71EOlG3eqQo4zLMV4q66fqMzjbIZiLe54E5jZff6R3vGUIYlXbJGXqqSgy1imRIDcrHi2w3PezY0Ur2LZvEYnv+HJQo8HhNtfmH78jq+tIb8J6L+xElCKuj0hEyU08z18S0UWiLpy82oPQXU4dcGtrhFWaYNHjREZZnUlddbG2ufwn47PWROHBlQMWC6D7E/0Q+anGX++LuzHW0NBPpBW3nGBOXvAyLvfa8fiEOVzq2Bj17FDEurObzxoV1xK5Z8vzDKp3/qnZHJclpf24JF3Jl05SGRqpbHnPbjBSe98r/fS6mKLizTOuDJOQdS06GUZ2ltbYSiTuP+1Fqkx0wH1dDwts9YV95jcPIvjsAlMQMxHCNCSHcmF145JrOr1vVCLeVpNhZ9voRY5IM9UAnY8g8/n4Q7cbxhbljM8gJWdopeHJN4OszJp86oNFSPENx0S8XVGe+tc6bv7QqwwOI5fhwPVKpy35MSKOIKAW/Q94kb/r5E9IsTHL9HwElC/RT0zpWos3ooQMtOu4rXuknXDB7E6wFdHsw7Detqi+TOkL263P/t3eB9zjwjkwtrCDMzpKgK52h/ZTU39nxpZtfoztlsAXsoecualgjDfTLGlppbnZHyt+kCrATvWVfs6EQg4Hf/nSY1a+xCqjCVC2rc/i2Q1Jfs4kTB+0+c+R0=
   on_success: always
   on_failure: always
```

**Comment by Joshua-Anderson** [comment]
> I observed slack messages are generating for build failure or pass on slack channel.

That's what
```
on_success: always
on_failure: always
```

does.

What behavior do you want?

**Comment by rameshthoomu** [comment]
I created a slack channel to send build notifications and copied above code snippet in my .travis.yml file.. What I observed is, slack messages are not coming to this channel other than my build results. What could be the reason? Am I missing something here?

Even I have given below
```
notifications:
  slack:
    rooms:
      secure: yAnJ71EOlG3eqQo4zLMV4q66fqMzjbIZiLe54E5jZff6R3vGUIYlXbJGXqqSgy1imRIDcrHi2w3PezY0Ur2LZvEYnv+HJQo8HhNtfmH78jq+tIb8J6L+xElCKuj0hEyU08z18S0UWiLpy82oPQXU4dcGtrhFWaYNHjREZZnUlddbG2ufwn47PWROHBlQMWC6D7E/0Q+anGX++LuzHW0NBPpBW3nGBOXvAyLvfa8fiEOVzq2Bj17FDEurObzxoV1xK5Z8vzDKp3/qnZHJclpf24JF3Jl05SGRqpbHnPbjBSe98r/fS6mKLizTOuDJOQdS06GUZ2ltbYSiTuP+1Fqkx0wH1dDwts9YV95jcPIvjsAlMQMxHCNCSHcmF145JrOr1vVCLeVpNhZ9voRY5IM9UAnY8g8/n4Q7cbxhbljM8gJWdopeHJN4OszJp86oNFSPENx0S8XVGe+tc6bv7QqwwOI5fhwPVKpy35MSKOIKAW/Q94kb/r5E9IsTHL9HwElC/RT0zpWos3ooQMtOu4rXuknXDB7E6wFdHsw7Detqi+TOkL263P/t3eB9zjwjkwtrCDMzpKgK52h/ZTU39nxpZtfoztlsAXsoecualgjDfTLGlppbnZHyt+kCrATvWVfs6EQg4Hf/nSY1a+xCqjCVC2rc/i2Q1Jfs4kTB+0+c+R0=
  on_success: always
  on_failure: always
```
