### ISSUE TITLE
Installing package flexc++ from apt-get fails

### ISSUE THREAD

**Issue by grodtron** [travis-ci/travis-ci#5936]
The package `flexc++` should be installable (it was supposed to be whitelisted in #4534), but installing it using the following `.travis.yml` fails:

``` yaml
language: cpp

addons:
  apt:
    packages:
      - flexc++

script:
  - which flexc++
```

An excerpt of the apt output is:

```
$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install flexc++
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package flexc+
E: Couldn't find any package by regex 'flexc+'
```

Replacing `flexc++` for `bisonc++` in `.travis.yml` will correctly install `bisonc++`.

#### Test builds

- Failing to install `flexc++`: https://travis-ci.org/grodtron/travis-flexcpp-test/builds/124629905
- Successfully installing `bisonc++` : https://travis-ci.org/grodtron/travis-flexcpp-test/builds/124628200

**Comment by BanzaiMan** [comment]
This originated from https://github.com/travis-ci/apt-package-whitelist/pull/321, and the test is available at https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72284613.

https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72284613#L419 shows that the package was fetched from "debian-sid" source. You should add that to `addons.apt.sources`.

```yaml
addons:
  apt:
    sources:
      - 'debian-sid'
    packages:
      - flexc++
```
