### ISSUE TITLE
list fails to reconize encrypted sections: in deploy section: dropping api_key section: unexpected sequence

### ISSUE THREAD

**Issue by ssbarnea** [travis-ci/travis-ci#5943]
It seems that travis gives a warning when it should not do it.
```
Warnings for .travis.yml:
[x] in deploy section: dropping api_key section: unexpected sequence
```
Here is the line generating the issue https://github.com/pycontribs/jira/blob/develop/.travis.yml#L60

**Comment by BanzaiMan** [comment]
The correct structure is:

```yaml
deploy:
  - provider: releases
    api_key:
      secure: "gr9iOcQjdoAyUAim6FWKzJI9MBaJo9XKfGQGu7wdPXUFhg80Rp6GLJsowP+aU94NjXM1UQlVHDAy627WtjBlLH2SvmVEIIr7+UKBopBYuXG5jJ1m3wOZE+4f1Pqe9bqFc1DxgucqE8qF0sC24fIbNM2ToeyYrxrS6RoL2gRrX2I="
```
