### ISSUE TITLE
ldc-1.0.0-beta1 requires change in LD_LIBRARY_PATH and g++-4.8

### ISSUE THREAD

**Issue by wilzbach** [travis-ci/travis-ci#5952]
As a beta warrior we from [mir](https://github.com/libmir/mir) went ahead and gave the newest ldc-1.0.0-beta1 a try.
It seems the ldc team changed quite a lot from the alpha1 to beta1:

1) `LD_LIBRARY_PATH=~/ldc/bin/:$LD_LIBRARY_PATH`
2) `g++-4.8` is needed

```
addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - g++-4.8
```

Adding this to the `.travis.yml` for ultimate user convenience would be nice.

Ping @MartinNowak, @klickverbot and @ibuclaw 

Thanks for the help to troubleshoot this @redstar
