### ISSUE TITLE
Deploy with multiple providers fails with `after_deploy` script

### ISSUE THREAD

**Issue by dtothefp** [travis-ci/travis-ci#5958]
I have a `deploy` script with multiple providers that I run selenium tests on deployed assets in the `after_deploy` script. When adding multiple providers it seems that the first `provider` with `condtion` that evaluates to `true` will deploy, but then the `after_deploy` script will run without executing additional `providers`

ex.

``` yml
  - provider: lambda #branches not `devel` or `master` with `DEPLOY_BRANCH`
    name: render-$TRAVIS_BUILD_NUMBER
    edge: true
    runtime: nodejs4.3
    handler_name: handler
    module_name: handler
    timeout: 300
    memory_size: 1536
    on:
      condition: $TRAVIS_BRANCH != "master" && $TRAVIS_BRANCH != "devel" && $DEPLOY_BRANCH = "true"
      all_branches: true
  - provider: lambda #branches not `devel` or `master` with `DEPLOY_BRANCH`
    name: render-$TRAVIS_BUILD_NUMBER
    edge: true
    runtime: nodejs4.3
    handler_name: handler
    module_name: handler
    timeout: 300
    memory_size: 1536
    on:
      condition: $TRAVIS_BRANCH != "master" && $TRAVIS_BRANCH != "devel" && $DEPLOY_BRANCH = "true"
      all_branches: true
  - provider: s3 #all branches except `master` `devel` `staging`
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != "master" && $TRAVIS_BRANCH != "devel" && $TRAVIS_BRANCH != "staging"
  - provider: lambda #`devel`
    name: render
    edge: true
    runtime: nodejs4.3
    handler_name: handler
    module_name: handler
    timeout: 300
    memory_size: 1536
    on:
      branch: devel
  - provider: lambda #`devel`
    name: render
    edge: true
    runtime: nodejs4.3
    handler_name: handler
    module_name: handler
    timeout: 300
    memory_size: 1536
    on:
      branch: devel
  - provider: s3 #`devel`
    on:
      branch: devel
  - provider: s3 #`master`
    on:
      branch: master
  - provider: s3 #`staging`
    on:
      branch: staging
after_deploy:
  - if [[ $TRAVIS_BRANCH != "master" ]]; then npm test || travis_terminate 1; fi # this will run after lambda deploy but will cancel any subsequent deploys
```

@michaelefisher @icco
