### ISSUE TITLE
invalid option "---provider=releases"

### ISSUE THREAD

**Issue by rwwagner90** [travis-ci/travis-ci#5968]
I am trying to use the officially documented release to github functionality and it doesn't work for me. I try something like this:

```
  -provider: releases
  api_key:
    secure: "secure token here"
  skip_cleanup: true
  on:
    tags: true
    repo: jibeinc/juice
```

It keeps telling me `invalid option "---provider=releases"` though. The npm deploy works, but github will not.

**Comment by rwwagner90** [comment]
It actually is also not letting me do npm this morning, apparently.

`invalid option "---provider=npm"`

**Comment by rwwagner90** [comment]
Upon further investigation, it seems the issue is it is adding and extra `-`

**Comment by rwwagner90** [comment]
So this was my full deploy section:

```
deploy:
  -provider: npm
  email: rwwagner90@gmail.com
  api_key:
    secure: secure goes here
  skip_cleanup: true
  on:
    tags: true
    repo: jibeinc/juice
  -provider: releases
  api_key:
     secure: "secure goes here"
  skip_cleanup: true
  on:
    tags: true
    repo: jibeinc/juice
```

It seems to do the npm one okay, but then adds the extra dash in front of releases. How can I do multiple deploys?
