### ISSUE TITLE
Folding can cause logs to be displayed out of (temporal) order

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#5971]
# Setup

Consider this [`.travis.yml`](https://github.com/BanzaiMan/travis_production_test/blob/5974478964aa717834cd4e1d379fadb968ae78e3/.travis.yml):

``` yaml
before_deploy:
  - echo "before_deploy"
  - date
deploy:
  - provider: script
    script: bash ./echo.sh first
    on:
      branch: default
  - provider: script
    script: bash ./echo.sh second
    on:
      branch: default

after_deploy:
  - sleep 5
  - echo "after_deploy"
  - date
```

`echo.sh` basically `echo`es the first arg (https://github.com/BanzaiMan/travis_production_test/blob/5974478964aa717834cd4e1d379fadb968ae78e3/echo.sh#L4)
# Expected behavior

In the order of execution, you should see:
1. `before_deploy`
2. `Deploy! first`
3. (sleep)
4. `after_deploy`
5. `before_deploy`
6. `Deploy! second`
7. (sleep)
8. `after_deploy`

The [raw log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/126470981/log.txt) shows that these events do happen in the expected order. (See also the `date` outputs.)
# Actual behavior

However, the [build log](https://travis-ci.org/BanzaiMan/travis_production_test/builds/126470980) shows:
1. `before_deploy`
2. `before_deploy`
3. `Deploy! first`
4. `Deploy! second`
5. (sleep)
6. (sleep)
7. `after_deploy`
8. `after_deploy`
