### ISSUE TITLE
android-update-sdk not found

### ISSUE THREAD

**Issue by aaronjwood** [travis-ci/travis-ci#5976]
I'm unable to get my Android builds working lately. I'm always getting this error: `android-update-sdk: command not found`. See here for the output https://travis-ci.org/aaronjwood/PortAuthority

My `.travis.yml` file:

```
language: android
sudo: required
dist: trusty
android:
  components:
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository

env:
  global:
   - secure: "YT/7/BbtCbOhHpiDCFKsBYl49u7d/+wDCZdkj1QUl+4u54u+2b/p5oX9ASoK8taYrUijE84mdJhBlLrX9Rplo12jQOlCkKdrW4oaDhUq2Mio63hNGIx4JSe+ycuIeDCWNK+JQ2qUnNWdagFlLPM+3KJZKudewkAlfZp+BQAmFA735UmbVoNSTKV2KToitb0H6NbCzu6ZRyfz0ncqM1ZgidJ+9vI5S18Y+l2EPnaLmIuiK34P0Q2hwULdrCsPvkstFWRdukqu3kTSv3ATtlqU/kOzeWiXmqySIG5sZX1EHTW871n3+WF8IF+5D5ocQzzkUI3KpreQWwwO8pfP0v1aiyhi4GfGHgHj1ZGa6JfD3W/uQCUOD9ovow/tkhgdt1DIoPEi4z3Ct0o6JQUC7npDCcRPj/dJAHQ0JT0uo1UcIjq63pibIrW1fT6Bd+iZITR8d18wAOwWOaBhsgHscQ0YVfxqaK/XX13gFwvdxt4TsAnWpWWW3ugG7QsbDya+PO4jfWbSDFDVnDYzbIsABOvJ6CtQhlt3bmbDzii4BAjF82QpDQ+T0xIIMlf5c6TbzyQOrt1Pw1SpK3L5iWit2fZwVUrIuBMP73CbK6F52Hxa763iQqdqWPFRGjsPBwgJOsdkUc/mXD9pbwGEEGSvAvOesJd5ctgmwXWlAkoBKUNew7w="

addons:
  coverity_scan:
    project:
      name: "aaronjwood/PortAuthority"
    notification_email: aaronjwood@gmail.com
    build_command_prepend: "./gradlew clean"
    build_command: "./gradlew build"
    branch_pattern: master
```

I was getting successful builds a few days back without changing anything https://travis-ci.org/aaronjwood/PortAuthority/builds/126018388

**Comment by BanzaiMan** [comment]
This is a fallout from #5973, which fixed the Android Trusty build routing issue. It looks like the Trusty stable image doesn't have the Android tools available.

Try the edge image with 

```yaml 
group: edge
```

Or go back to the Precise image.

**Comment by aaronjwood** [comment]
I'd like to move back to the container infrastructure but I could almost never get it to work because of #5782 

Do you know if things have changed with that since the beginning of March?

**Comment by BanzaiMan** [comment]
@aaronjwood I meant `dist: precise`.

**Comment by BanzaiMan** [comment]
```yaml
language: android
sudo: required
dist: precise
```
works now.

Android is not yet supported on Trusty. See #5370.

**Comment by aaronjwood** [comment]
Thanks, but is it possible to use the container infrastructure for Android yet? I noticed that it would always run out of memory. If not, I'll just switch to precise like you suggested.

**Comment by BanzaiMan** [comment]
Could it be that the memory requirements for Android has increased with recent updates?

**Comment by aaronjwood** [comment]
Hmm...maybe. I'll do some investigating and see what I can find.

**Comment by aaronjwood** [comment]
BTW precise worked just as you said https://travis-ci.org/aaronjwood/PortAuthority/builds/126974260
The container-based infrastructure still seems to run out of memory. I'll do some profiling locally and post back what I find.

**Comment by aaronjwood** [comment]
So when I run the same `gradlew connectedCheck` command locally and watch what happens, I see that about 4-6 Java processes get spawned throughout the build. A few will die for the short lived tasks but then another process will take it's place for the next task (this happens pretty quickly at a few points). Each Java process consumes between 300-500 MB of memory to start, and the more computationally heavy pieces of the build cause a few of the processes to bump up to 550-650 MB. I'm guessing this is what's causing the container to OOM since it always seems to get killed on the same spot (which incidentally is one of the spots where a lot of heavy lifting takes place).

**Comment by Lyoness** [comment]
Hi @aaronjwood circling back here to let you know we've pushed a new trusty-based android image with the following tools: 

to test it, use 

```
language: android
dist: trusty
group: edge
```

```
Assignees
 @meatballhat meatballhat

 Labels
question
ubuntu/trusty
 Projects
None yet
 Milestone
No milestone
Notifications
  Unsubscribe
You’re receiving notifications because you were mentioned.
5 participants
@BanzaiMan @meatballhat @MGaetan89 @solarce @Lyoness
 Lock conversation
 @BanzaiMan
   Owner
BanzaiMan commented on Jan 5
This corresponds to travis-ci/travis-ci#6279.

The components are undoubtedly updated since the issue above was opened, and we need to ensure that a reasonable set exists on our Android image.
 :+1: 1  
 @BanzaiMan
     Owner
BanzaiMan commented on Jan 5
Perhaps this replaces #294?
 @BanzaiMan BanzaiMan added stack/android stack/jvm ubuntu/trusty and removed stack/android stack/jvm labels on Jan 5
 @meatballhat
     Owner
meatballhat commented on Jan 23
@BanzaiMan Is the list of components in travis-ci/travis-ci#6279 complete, meaning everything on the list should be included and anything not on the list should be excluded?
  BanzaiMan was assigned by meatballhat on Jan 23
  meatballhat added the question label on Jan 23
 @BanzaiMan
     Owner
BanzaiMan commented on Jan 26
To be quite honest, I don't know what constitutes a complete list in this context. Probably we need expert advice.
  BanzaiMan removed their assignment on Jan 26
 @MGaetan89
     
MGaetan89 commented on Jan 26
@meatballhat The list I provided in travis-ci/travis-ci#6279 is only the list of components currently missing on Travis. I think that the components that are already preinstalled can stay.

However, Google marked some components as "Obsolete" in the SDK Manager in Android Studio. So maybe those can be deprecated/removed if needed.
For the system images, everything before API 15 (excluded) is marked as obsolete (so API 1-14).
For the Build Tools, here is the full list:
screenshot from 2017-01-26 07-19-22
 @MGaetan89
     
MGaetan89 commented on Feb 27
@BanzaiMan @meatballhat Is there something else I can provide/do to help you move forward with this?
 @solarce
     Owner
solarce commented on Feb 27
Hiro is currently traveling and Dan is focused on some other urgent stability related work, so it'll be a week or two before you can expect to hear anything further back on this issue. Sorry for the delays.
 @MGaetan89
     
MGaetan89 commented on Feb 28
@solarce Ok, no problem. Thanks for the info.
  meatballhat self-assigned this on Mar 9
 @MGaetan89
     
MGaetan89 commented on Mar 23
In case you also want to support Developer Preview of Android, the following components are now also available:

Build tools 26-rc1
sys-img-x86-android-26
sys-img-x86_64-android-26
 @MGaetan89
     
MGaetan89 commented on Apr 26 • edited
Build Tools 25.0.3 is now available as well.
Any update on your side?
 @MGaetan89
     
MGaetan89 commented 19 days ago
We now have:

Build Tools 26.0.0-rc2
Updated system images for Android O
Any update on your side?
 @Lyoness
     Owner
Lyoness commented 16 days ago
#437

Android-only image in active dev for trusty

Cookbook here: travis-ci/travis-cookbooks#838
 @MGaetan89
     
MGaetan89 commented 10 days ago
@Lyoness Thanks for the update. Looking forward to the release.
 @MGaetan89
     
MGaetan89 commented 21 hours ago
Build Tools 26 is now available.
 :+1: 1  
 @Lyoness
     Owner
Lyoness commented 21 hours ago • edited
Ah yes @MGaetan89, they are currently available in our group: edge

language: android
dist: trusty

group: edge
Full list of components here
 @MGaetan89
     
MGaetan89 commented 21 hours ago
Thanks for the info @Lyoness. That's awesome news!
Unfortunately I can not access the link you provide. Could you list the components here?
 @Lyoness
     Owner
Lyoness commented 4 hours ago
@MGaetan89

List of Android SDK components that can be specified in .travis.yml
addon-google_apis-google-10
addon-google_apis-google-11
addon-google_apis-google-12
addon-google_apis-google-13
addon-google_apis-google-14
addon-google_apis-google-15
addon-google_apis-google-16
addon-google_apis-google-17
addon-google_apis-google-18
addon-google_apis-google-19
addon-google_apis-google-21
addon-google_apis-google-22
addon-google_apis-google-23
addon-google_apis-google-24
addon-google_apis-google-3
addon-google_apis-google-4
addon-google_apis-google-5
addon-google_apis-google-6
addon-google_apis-google-7
addon-google_apis-google-8
addon-google_apis-google-9
addon-google_gdk-google-19
addon-google_tv_addon-google-12
addon-google_tv_addon-google-13
android-10
android-11
android-12
android-13
android-14
android-15
android-16
android-17
android-18
android-19
android-2
android-20
android-21
android-22
android-23
android-24
android-25
android-3
android-4
android-5
android-6
android-7
android-8
android-9
build-tools-17.0.0
build-tools-18.0.1
build-tools-18.1.0
build-tools-18.1.1
build-tools-19.0.0
build-tools-19.0.1
build-tools-19.0.2
build-tools-19.0.3
build-tools-19.1.0
build-tools-20.0.0
build-tools-21.0.0
build-tools-21.0.1
build-tools-21.0.2
build-tools-21.1.0
build-tools-21.1.1
build-tools-21.1.2
build-tools-22.0.0
build-tools-22.0.1
build-tools-23.0.0
build-tools-23.0.1
build-tools-23.0.2
build-tools-23.0.3
build-tools-24.0.0
build-tools-24.0.1
build-tools-24.0.2
build-tools-24.0.3
build-tools-25.0.0
build-tools-25.0.1
build-tools-25.0.2
build-tools-25.0.3
build-tools-26.0.0-preview
doc-24
extra-android-m2repository
extra-google-admob_ads_sdk
extra-google-analytics_sdk_v2
extra-google-auto
extra-google-gcm
extra-google-google_play_services
extra-google-google_play_services_froyo
extra-google-instantapps
extra-google-m2repository
extra-google-market_apk_expansion
extra-google-market_licensing
extra-google-play_billing
extra-google-simulators
extra-google-webdriver
platform-tools
platform-tools-preview
source-14
source-15
source-16
source-17
source-18
source-19
source-20
source-21
source-22
source-23
source-24
source-25
sys-img-arm64-v8a-android-24
sys-img-arm64-v8a-google_apis-24
sys-img-arm64-v8a-google_apis-25
sys-img-armeabi-v7a-android-10
sys-img-armeabi-v7a-android-14
sys-img-armeabi-v7a-android-15
sys-img-armeabi-v7a-android-16
sys-img-armeabi-v7a-android-17
sys-img-armeabi-v7a-android-18
sys-img-armeabi-v7a-android-19
sys-img-armeabi-v7a-android-21
sys-img-armeabi-v7a-android-22
sys-img-armeabi-v7a-android-24
sys-img-armeabi-v7a-android-tv-21
sys-img-armeabi-v7a-android-tv-22
sys-img-armeabi-v7a-android-tv-23
sys-img-armeabi-v7a-android-wear-23
sys-img-armeabi-v7a-android-wear-25
sys-img-armeabi-v7a-google_apis-10
sys-img-armeabi-v7a-google_apis-15
sys-img-armeabi-v7a-google_apis-16
sys-img-armeabi-v7a-google_apis-17
sys-img-armeabi-v7a-google_apis-18
sys-img-armeabi-v7a-google_apis-19
sys-img-armeabi-v7a-google_apis-21
sys-img-armeabi-v7a-google_apis-22
sys-img-armeabi-v7a-google_apis-23
sys-img-armeabi-v7a-google_apis-24
sys-img-armeabi-v7a-google_apis-25
sys-img-mips-android-15
sys-img-mips-android-16
sys-img-mips-android-17
sys-img-x86-android-10
sys-img-x86-android-15
sys-img-x86-android-16
sys-img-x86-android-17
sys-img-x86-android-18
sys-img-x86-android-19
sys-img-x86-android-21
sys-img-x86-android-22
sys-img-x86-android-23
sys-img-x86-android-24
sys-img-x86-android-tv-21
sys-img-x86-android-tv-22
sys-img-x86-android-tv-23
sys-img-x86-android-tv-24
sys-img-x86-android-tv-25
sys-img-x86-android-wear-23
sys-img-x86-android-wear-25
sys-img-x86-google_apis-10
sys-img-x86-google_apis-15
sys-img-x86-google_apis-16
sys-img-x86-google_apis-17
sys-img-x86-google_apis-18
sys-img-x86-google_apis-19
sys-img-x86-google_apis-21
sys-img-x86-google_apis-22
sys-img-x86-google_apis-23
sys-img-x86-google_apis-24
sys-img-x86-google_apis-25
sys-img-x86-google_apis_playstore-24
sys-img-x86_64-android-21
sys-img-x86_64-android-22
sys-img-x86_64-android-23
sys-img-x86_64-android-24
sys-img-x86_64-google_apis-21
sys-img-x86_64-google_apis-22
sys-img-x86_64-google_apis-23
sys-img-x86_64-google_apis-24
sys-img-x86_64-google_apis-25
tools
which android && echo -e "\033[33;1mSee http://docs.travis-ci.com/user/languages/android/#How-to-install-Android-SDK-components\033[0m"
/usr/local/android-sdk/tools/android
See http://docs.travis-ci.com/user/languages/android/#How-to-install-Android-SDK-components
```

**Comment by aaronjwood** [comment]
@Lyoness thanks! I'll give this a try sometime soon :)

**Comment by vanniktech** [comment]
I'm having the same warning when trying to install the SDK on osx. This is my configuration:

```yaml
language: android

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      addons:
        apt:
          packages:
            - graphviz
      sudo: false
    - os: osx
      osx_image: xcode9.2 # Will give us JDK 1.8.0_112-b16
      dist: precise # https://github.com/travis-ci/travis-ci/issues/5990#issuecomment-216621501
      sudo: required
      android:
        components:
          - tools
          - platform-tools

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphviz; fi
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"

script: ./gradlew clean build
```
