### ISSUE TITLE
[Request] boot-clj for clojure builds

### ISSUE THREAD

**Issue by flyboarder** [travis-ci/travis-ci#5982]
Please install by default boot-clj for clojure environments.
Boot is a popular alternative to lein for clojure builds.

http://boot-clj.com/
https://github.com/boot-clj/boot

**Comment by BanzaiMan** [comment]
http://blog.cognitect.com/blog/2016/1/28/state-of-clojure-2015-survey-results shows that about 12% of respondents are using it.

My inclination is to wait for a while before we add it.

**Comment by keithmantell** [comment]
I have started using boot since that survey!  I would +1 this request.

**Comment by thomas-shares** [comment]
Hi,
This is the one issue that is stopping me from using Travis at the moment, it would be really great if this could be added!!!

Thank you,
Thomas

**Comment by martinklepsch** [comment]
Using Boot with Travis is perfectly possible, there is a snippet on one of the wiki pages which you can find here: https://github.com/boot-clj/boot/wiki/Running-Boot-on-CI-systems

Copying it here just to give a rough idea but you should probably check the wiki for up to date info:
```
sudo: false
language: java
script: boot run-tests
install:
  - mkdir -p ~/bin
  - export PATH=~/bin:$PATH
  # Could use `latest` tag instead of version number
  - curl -L https://github.com/boot-clj/boot-bin/releases/download/2.5.2/boot.sh -o ~/bin/boot
  - chmod +x ~/bin/boot
env:
  matrix:
    # Runs tests twice, using Clj 1.7 and 1.8
    - BOOT_CLOJURE_VERSION=1.7.0
    - BOOT_CLOJURE_VERSION=1.8.0
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
  - $HOME/.boot/cache/bin
  - $HOME/.boot/cache/lib
  - $HOME/bin
```
