### ISSUE TITLE
Matrix.exclude fail if allow_failures defined

### ISSUE THREAD

**Issue by ad-m** [travis-ci/travis-ci#5992]
Hello,

I would like add support into django-mptt for tests over django v. master.

I fork repo and got travis.yml which pass ( https://github.com/django-mptt/django-mptt/blob/12a4f3b284f1485cade871d4c84615ad2d2cfe0e/.travis.yml , https://travis-ci.org/django-mptt/django-mptt ):
![zaznaczenie_508](https://cloud.githubusercontent.com/assets/3618479/15001556/e7009956-1198-11e6-8b09-9484a73c7580.png)

I made following changes ( https://github.com/watchdogpolska/django-mptt/compare/12a4f3b...f96b6f79d52f ): 
```diff
diff --git a/.travis.yml b/.travis.yml
index cfce1a7..12a0819 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,5 +1,6 @@
 sudo: false
 language: python
+
 python:
   - "3.5"
   - "3.4"
@@ -7,9 +8,12 @@ python:
   - "3.2"
   - "2.7"
   - "pypy"
+
 env:
   - DJANGO="Django>=1.8,<1.9"
   - DJANGO="Django>=1.9,<1.10"
+  - DJANGO="https://github.com/django/django/archive/master.tar.gz"
+
 matrix:
   exclude:
     - env: DJANGO="Django>=1.8,<1.9"
@@ -19,10 +23,11 @@ matrix:
     - env: DJANGO="Django>=1.9,<1.10"
       python: "3.3"
 
+matrix:
+  allow_failures:
+    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
+
 # command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
 install: pip install $DJANGO mock-django==0.6.9
 # command to run tests, e.g. python setup.py test
 script: cd tests/ && ./runtests.sh
-
-# Run on travis' container infrastructure
-sudo: false
```

The matrix.exclude got ignored now ( https://travis-ci.org/watchdogpolska/django-mptt/builds/127664591 ):
![zaznaczenie_509](https://cloud.githubusercontent.com/assets/3618479/15001613/6e3b72a6-1199-11e6-8fbb-960b8c622d34.png)
The mark enviroment in travis.yml was mark as excluded in matrix:
```yaml
matrix:
  exclude:
    - env: DJANGO="Django>=1.8,<1.9"
      python: "3.5"
    - env: DJANGO="Django>=1.9,<1.10"
      python: "3.2"
    - env: DJANGO="Django>=1.9,<1.10"
      python: "3.3"
```

What does it mean?

**Comment by BanzaiMan** [comment]
`matrix.exclude` does not affect how each of these jobs are run.

If you look at https://travis-ci.org/django-mptt/django-mptt/builds/127625120, you will notice that the cases failing in https://travis-ci.org/watchdogpolska/django-mptt/builds/127663007 (i.e., `python: "3.3"` + `DJANGO="Django>=1.9,<1.10"` and `python: "3.2"` + `DJANGO="Django>=1.9,<1.10"`) are not run.

I don't know why they are not included in the builds, or why they fail, but I do not believe this is a Travis CI issue.

**Comment by ad-m** [comment]
Hello,

I am  don't have issues why tests fails. I know exactly how tests works it depends on me.

My issues is that TravisCI tried to build jobs which was excluded. My ```.travis.yml``` contains:
```
(…) 

matrix:
  exclude:
    - env: DJANGO="Django>=1.8,<1.9"
      python: "3.5"
    - env: DJANGO="Django>=1.9,<1.10"
      python "3.2"
    - env: DJANGO="Django>=1.9,<1.10"
      python: "3.3"

(…)
```
Build jobs:
![zaznaczenie_510](https://cloud.githubusercontent.com/assets/3618479/15008378/32e30b78-11e0-11e6-97e7-4fb44494cb3a.png)

I believe marked jobs as "excluded" in image **should not exists** in TravisCI. This jobs  should not created, so it **unable** to fail. 

To make process more transparent in buil.dlog I added ```cat .travis.yml``` to my builds: https://travis-ci.org/watchdogpolska/django-mptt/builds/127730719

Greetings,

**Comment by BanzaiMan** [comment]
You have two `matrix` keys in https://github.com/watchdogpolska/django-mptt/blob/ebc4eb04bc8004919c05b26e9be62992b9050823/.travis.yml. One on lines 17 to 24, the other from lines 26 to 28. The last one wins in YAML.

**Comment by BanzaiMan** [comment]
What you want is:

```yaml

matrix:
  exclude:
    - env: DJANGO="Django>=1.8,<1.9"
      python: "3.5"
    - env: DJANGO="Django>=1.9,<1.10"
      python: "3.2"
    - env: DJANGO="Django>=1.9,<1.10"
      python: "3.3"
  allow_failures:
    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
```
