### ISSUE TITLE
ProcessBuilder in java

### ISSUE THREAD

**Issue by rpau** [travis-ci/travis-ci#6000]
Hi, 

I don't understand why, but if my application is executing a command from java to test if it exists, the process is blocked and finally, sends a timeout. Executing the same process in local machines, works. The source code is: https://github.com/walkmod/walkmod-maven-plugin/blob/master/src/main/java/org/walkmod/maven/providers/MavenProject.java#L242

What really surprises me is that the process is "mvn -version", and "mvn" is the same command used to test the application. My travis.yml is as follows:

```yaml
language: java
sudo: required
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
install:
  - mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test
```
