### ISSUE TITLE
Store build cache doesn't save data and returns error 

### ISSUE THREAD

**Issue by devs-deep** [travis-ci/travis-ci#6004]
Store build cache doesn't store data and returns error.

We use caching for global and local node_modules and some bins to be able to execute them in CI. Please refer in .travis.yml config:

```
language: node_js
sudo: false
node_js:
  - '4.3'
  - '4.4'
cache:
  directories:
    - $(npm root -g)
    - node_modules
    - deep_modules
    - $(npm config get prefix)/bin/deepify
    - $(npm config get prefix)/bin/jspm
    - $(npm config get prefix)/bin/karma
    - $(npm config get prefix)/bin/_mocha
    - $(npm config get prefix)/bin/istanbul
    - $(npm config get prefix)/bin/protractor
branches:
  only:
    - master
    - dev
    - stage
    - test
before_install:
  - cp bin/test/package.json .
after_success:
  - npm run coverage
env:
  matrix:
    - TEST_SUITE=backend
    - TEST_SUITE=frontend
  global:
    - E2E_TESTING=public
```

After successfully installing all dependencies and passing build the error below is displayed:

```
store build cache
0.01s
0.65s/home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:247:in `mkdir': File exists - /home/travis/.nvm/versions/node/v4.3.2/bin/deepify (Errno::EEXIST)
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:247:in `fu_mkdir'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:221:in `block (2 levels) in mkdir_p'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:219:in `reverse_each'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:219:in `block in mkdir_p'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:205:in `each'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:205:in `mkdir_p'
	from /home/travis/.casher/bin/casher:114:in `block in push'
	from /home/travis/.casher/bin/casher:114:in `map'
	from /home/travis/.casher/bin/casher:114:in `push'
	from /home/travis/.casher/bin/casher:52:in `block in run'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/timeout.rb:69:in `timeout'
	from /home/travis/.casher/bin/casher:52:in `run'
	from /home/travis/.casher/bin/casher:233:in `<main>'
```

For more details please refer to the full log: https://travis-ci.org/MitocGroup/deep-microservices-todo-app/jobs/128220561

**Comment by BanzaiMan** [comment]
Ouch. I'll take a look soon.

**Comment by BanzaiMan** [comment]
Ah, I see. You are trying to cache *files*, not directories. This is a use case we haven't thought of.

I'm curious to know why you want to do this.

**Comment by BanzaiMan** [comment]
We'll fix it soon, though. :-)

**Comment by BanzaiMan** [comment]
Could you try the fix with the following?

```yaml
cache:
  edge: true
  directories:
    ⋮ # rest
```

Thanks.
