### ISSUE TITLE
Upgrade docker to 1.10 or 1.11

### ISSUE THREAD

**Issue by Vanuan** [travis-ci/travis-ci#6020]
Looks like I can't use travis installed version of docker:

```
ERROR: The Docker Engine version is less than the minimum required by Compose. 
Your current project requires a Docker Engine of version 1.10.0 or greater.
```

**Comment by BanzaiMan** [comment]
Until we roll out a build environment update, on Trusty, you can use `sudo` to update Docker.

**Comment by Vanuan** [comment]
Yeap, it worked: https://github.com/Vanuan/jspm-cli/blob/docker/.travis.yml

**Comment by Vanuan** [comment]
Would be great to have a shorter syntax like this:

```
docker:
  engine-version: 1.11.1
  compose-version: 1.7.0
composefile:
  global:
    - docker-compose.yml 
  matrix:
    - compose/node-4.yml
    - compose/node-6.yml
```

So that by default it's executed like this:

docker-compose -f docker-compose.yml -f compose/node-4.yml up
