### ISSUE TITLE
travis.yml issues with matrix env with multiple osx and linux

### ISSUE THREAD

**Issue by reconbot** [travis-ci/travis-ci#6023]
With the following yaml I end up with 3 linux builds one for each node version, and two builds (one linux and one osx) with all the env matrix combined. (Total 5 builds, expected 12)

```yaml
# Build matrix
env:
  matrix:
  - TRAVIS_NODE_VERSION="4"
  - TRAVIS_NODE_VERSION="5"
  - TRAVIS_NODE_VERSION="6"
matrix:
  include:
    # Ubuntu 14.04.4 LTS (Trusty Tahr)
    - os: linux
      dist: trusty
    # Xcode 7.3.1 OS X 10.11
    - os: osx
      osx_image: xcode7.3
    # Xcode 7.1.1 GM  OS X 10.10
    - os: osx
      osx_image: xcode7.1
    # Xcode 7.1.1 GM  OS X 10.9
    - os: osx
      osx_image: beta-xcode6.1
```
