### ISSUE TITLE
SDK tools is out of date on Android

### ISSUE THREAD

**Issue by jsotuyod** [travis-ci/travis-ci#6040]
Defining

```
android:
    components:
        - tools
```

is supposed to install the latest Android SDK Tools available, which at the time of this writing is 25.1.3. However, on Travis it's currently installing 24.4.1. This causes differences between our local builds and Travis (for instance, lint rules changed, 24.4 defined an show stopper error on missing App Indexing metadata, on 25 that's gone).

Since the rule is gone un 25, defining a warning level for that rule will make Travis pass but local builds on 25 fail on an invalid config for an unknown rule.

**Comment by BanzaiMan** [comment]
I believe you need to install more components, something like https://github.com/travis-ci/travis-ci/issues/5036#issuecomment-153297292.

The update issue is separate (see https://github.com/travis-ci/travis-ci/issues/5048).

I'm closing this as a duplicate.

**Comment by BanzaiMan** [comment]
OK, so I did looked at this a bit more closely, and it turns out you would need a little more ingenuity.

What I found that works to get Android SDK 25.1.x working is:

```yaml
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install Android SDK tools 25.1.x (x = 6 right now)
    ⋮ # rest
```
