### ISSUE TITLE
HHVM versions like PHP versions

### ISSUE THREAD

**Issue by photodude** [travis-ci/travis-ci#6043]
It would be very helpful if HHVM could be referenced in builds by versions like PHP is.

example build matrix
```yml
matrix:
  include:
    - php: 5.6
    - php: 7
    - php: hhvm3.11
    - php: hhvm3.12
```

or possibly even better
```yml
matrix:
  include:
    - php: 5.6
    - php: 7
    - hhvm: 3.11
    - hhvm: 3.12
```

It would also be helpful to be able to identify in the build matrix [HHVM with the PHP 7 compatibility flag](https://docs.hhvm.com/hhvm/configuration/INI-settings#php-7-settings)

```yml
matrix:
  include:
    - php: 5.6
    - php: 7
    - hhvm: 3.11
    - hhvm.php7: 3.12
```

Exact implementation for the build matrix is arbitrary, but having these HHVM options for builds is as important as the php versions are.

**Comment by BanzaiMan** [comment]
Of the proposed configurations, only the first (I tend to think `hhvm-3.12` looks better) seems reasonable to me. Setting

```yaml
matrix:
  include:
    - hhvm: 3.12
```

for example, is equivalent to defining a new top-level key `hhvm`. HHVM is not a new language, however, so this does not seem correct to me.

Do note that Facebook does not offer all past versions in their repositories. For example, the latest version is 3.13.1 only http://dl.hhvm.com/ubuntu/dists/trusty/main/binary-amd64/Packages, and also for LTS http://dl.hhvm.com/ubuntu/dists/trusty-lts-3.12/main/binary-amd64/Packages. Users, then, are expected to know *exactly* which version they want and use. In other words, `3.11` or `3.12` will not work.

**Comment by photodude** [comment]
3.12 should still be available, especially since it's an LTS release and will be supported until 29 Dec 2016 even 3.9 should still be available since it's LTS with end of support (EOS) of 14 Jul 2016

for example 
- hhvm 3.9 http://dl.hhvm.com/ubuntu trusty-lts-3.9/main/binary-amd64/Packages

or All hhvm updates for Trusty (lts-3.3, lts-3.6, lts-3.9, lts-3.12, and 3.13, hhvm-nightly, )
- http://dl.hhvm.com/ubuntu/dists/

I'm not opposed to something like `hhvm-3.12` or `hhvm.3.12` for the matrix. Like I said, specifics of the implementation are not as important as the implementation.
```yaml
matrix:
  include:
    - hhvm-3.12
```

What about the [PHP 7 compatibility flag](https://docs.hhvm.com/hhvm/configuration/INI-settings#php-7-settings) for 3.12 lts or newer?

would you do `hhvm-3.12-php7` or something like this?
```yaml
matrix:
  include:
    # PHP 5 HHVM
    - hhvm-3.12
    # PHP 7 HHVM
    - hhvm-3.12
      env: hhvm.php7.all = 1
```

**Comment by BanzaiMan** [comment]
Right now, 3.12.1 is available, but 3.12 (or 3.12.0) is not.

Although I've figured out how to install the latest 3.12.x without knowing the precise value of x.

As for PHP 7 compatibility, I am not sure. It can be done with an env var, which is great, but then testing it with and without it in the same build matrix would be a bit cumbersome. :-/

**Comment by photodude** [comment]
Have you tried the [options for the older HHVM LTS releases](https://docs.hhvm.com/hhvm/installation/linux#obtaining-lts-releases)?

As for PHP 7 compatibility could we do something like a new environment variable similar to the DB var? maybe something like this?
```yaml
matrix:
  include:
    - hhvm-3.12
      env:
        global:
          # PHP 5
          - HHVMPHP7 = 0
          # PHP 7
          - HHVMPHP7 = 1
```
where the default of `HHVMPHP7` is 0 corisponding to the default `hhvm.php7.all = 0`
and where `HHVMPHP7` is 1 corisponding to `hhvm.php7.all = 1` such that when two `HHVMPHP7` variables are specified two builds are run, similar to how specifying two DB items runs two builds.

**Comment by BanzaiMan** [comment]
The flag `hhvm.php7.all=1` is a value to be set in `php.ini`, right? Seems to me that it's best left to the user to define it.

**Comment by photodude** [comment]
Yes, `hhvm.php7.all=1` set in the php.ini. 

Normally I would agree, but in this case it's like testing different against php versions. For hhvm 3.11 and newer we literally have 2 different testing versions, one for php 5 and one for php7. Having the ability to test against both in one build matrix is very important for Libraries, Frameworks, and Applications like Joomla where the code is consumed by end users and the project needs to assure that there is comparability with various versions of php and hhvm (both as default php 5 and with php 7 support)

**Comment by BanzaiMan** [comment]
I am against defining a magic environment variable (`HHVMPHP7` in the example above) that is not officially supported.

**Comment by BanzaiMan** [comment]
Something like this should work.

```yaml
language: php
matrix:
  include:
    - php: hhvm-3.12
      env:
        - HHVMPHP7=0
    - php: hhvm-3.12
      env:
        - HHVMPHP7=1
before_script:
   - if [[ z$HHVMPHP7 != z ]]; then DO_STUFF_TO_SET_hhvm.php7.all=1; fi
⋮
```

**Comment by photodude** [comment]
We should be able to test that right now as follows to get 4 builds on trusty. 

```yml
language: php
matrix:
  include:
    - php: hhvm
      env:
        - HHVMPHP7=0
    - php: hhvm
      env:
        - HHVMPHP7=1
    - php: hhvm-nightly
      env:
        - HHVMPHP7=0
    - php: hhvm-nightly
      env:
        - HHVMPHP7=1
before_script:
   - if [[ z$HHVMPHP7 != z ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi
⋮
```
the result should be a build for
- HHVM 3.13 with php5
- HHVM 3.13 with php7
- HHVM Nightly with php5
- HHVM Nightly with php7
