### ISSUE TITLE
iOS tests time out issue

### ISSUE THREAD

**Issue by betzerra** [travis-ci/travis-ci#6046]
Since yesterday my iOS tests are failing the first time. If I click on retry, the tests will pass.

```
69) -[someClass testSomething] (UnitTests.xctest)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Test did not run: Failed to install the test host app 'com.domain.app': Timed out.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

** TEST FAILED: 0 passed, 0 failed, 70 errored, 70 total ** (808148 ms)
```

.travis.yml

```
language: objective-c
osx_image: xcode7.2
xcode_workspace: SomeApp.xcworkspace
podfile: Podfile
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
before_install:
  - gem install cocoapods -v '0.39.0'
notifications:
  slack: 'slack_channel_token'
script:
  - xctool -workspace SomeApp.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.2' -scheme 'SomeApp Store' -sdk iphonesimulator test%
```
