### ISSUE TITLE
Travis sent the negative execution time to Slack for failed build

### ISSUE THREAD

**Issue by vcernomschi** [travis-ci/travis-ci#6047]
Travis sent the negative execution time to Slack for failed build.

We use notification to Slack for Travis:

```
notifications:
  slack:
    secure: 
      GaQIs6r13iVabtmFvmCFebbX*********************
```

On Web Travis is displayed valid values:

```
 Pull Request #313 #310 Separate Credit and AwardedCredit functionality

 #400 errored

 Elapsed time 5 hrs 58 min 4 sec
 Total time 1 min 26 sec
 about 11 hours ago
```

On slack    we received the notification below:
`Build #400 (ef2c7f6) of MitocGroup/livebook@dev in PR #313 by AlexanderC errored in -340 min 26 sec`
![screen shot 2016-05-13 at 10 11 47 am](https://cloud.githubusercontent.com/assets/10863276/15240552/3a799568-18f3-11e6-91fa-2b9db334d818.png)

Please here you can logs for build:
https://travis-ci.com/MitocGroup/livebook/builds/25225149
