### ISSUE TITLE
apt source debian-sid practically unusable due to ubuntu-precise containers

### ISSUE THREAD

**Issue by coldtobi** [travis-ci/travis-ci#6073]
Well, the upgrade to Debian's dpkg fails in ubuntu's precise:

It is usually a bad idea anyway to mix Ubuntu and Debian -- can we have a Debian container, pretty please?
Or an more up-to-date Ubuntu one? (My project needs check > 0.10, that is available in Xenial Xerus )

```
Preparing to replace dpkg 1.16.1.2ubuntu7.5 (using .../archives/dpkg_1.18.7_amd64.deb) ...
Unpacking replacement dpkg ...
dpkg: error: configuration error: /etc/dpkg/dpkg.cfg.d/multiarch:1: unknown option 'foreign-architecture'
Processing triggers for man-db ...
```

Minimal .travis.yaml:

```
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - autoconf-archive

language: cpp

```
