### ISSUE TITLE
Fail to push to GitHub in deployment

### ISSUE THREAD

**Issue by dkhamsing** [travis-ci/travis-ci#6080]
We're trying to update a README and push that back to GitHub

In deploy.sh, we have

> git push --quiet "https://${GH_TOKEN}@github.com/matteocrippa/awesome-swift" master:master > /dev/null 2>&1

Which works as part of the config below

```yml
language: ruby
rvm: 2.2
script:
  - #...
after_success:
  - ./.github/deploy.sh
```

However if we try to do this in deploy (take advantage of `on branch`), it fails

```yml
language: ruby
#...
deploy:
  provider: script
  script: ./.github/deploy.sh
  on:
    branch: master
```

With error `128`
https://travis-ci.org/matteocrippa/awesome-swift/builds/131502586

Here we have more debug info
```
fatal: unable to access 'https://[REDACTED]@github.com/matteocrippa/awesome-swift.git master:master/': The requested URL returned error: 400
Script failed with status 128
```
https://travis-ci.org/matteocrippa/awesome-swift/builds/131490918

Any help or ideas welcome, thanks!
