### ISSUE TITLE
Add option for notifications to apply only on specified branches

### ISSUE THREAD

**Issue by OJFord** [travis-ci/travis-ci#6084]
It would be great to be able to do:

``` yaml
notifications:
  slack:
    branches:
      - 'master'
      - 'foobar'
```

If left unspecified of course defaulting to the current 'all' behaviour.
