### ISSUE TITLE
clang builds fail due to llvm apt down

### ISSUE THREAD

**Issue by ahxxm** [travis-ci/travis-ci#6120]
when addons include clang, travis will try to fetch gpg key from [http://llvm.org/apt/llvm-snapshot.gpg.key](http://llvm.org/apt/llvm-snapshot.gpg.key)

which is [down now](http://lists.llvm.org/pipermail/llvm-foundation/2016-May/000020.html), and blocks every build that relies on clang...

**Comment by cotsog** [comment]
Here's the announcement on the llvm-dev mailing list: http://lists.llvm.org/pipermail/llvm-dev/2016-May/100303.html

**Comment by BanzaiMan** [comment]
Hello. I worked a bit to get recent versions of LLVM to work on Trusty.

https://travis-ci.org/BanzaiMan/travis_production_test/builds/134879963#L181 (See the corresponding [.travis.yml](https://github.com/BanzaiMan/travis_production_test/blob/b79ecfa29727d7f113182a1a0f6489f62e16807b/.travis.yml))

My work is undoubtedly naïve, only up to showing `clang++ --version`. If there are other steps necessary to make other parts of LLVM working, please let us know.

**Comment by BanzaiMan** [comment]
Needless to say, the `apt` addon should be removed before the steps above are able to run.

**Comment by BanzaiMan** [comment]
For completeness, here is an excerpt of the configuration:

```yaml
sudo: required
dist: trusty

env:
  global:
    - LLVM_VERSION=3.7.0
    - LLVM_ARCHIVE_PATH=$HOME/clang+llvm.tar.xz

before_install:
  - wget http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $LLVM_ARCHIVE_PATH
  - mkdir $HOME/clang+llvm
  - tar xf $LLVM_ARCHIVE_PATH -C $HOME/clang+llvm --strip-components 1
  - export PATH=$HOME/clang+llvm/bin:$PATH
```

**Comment by nlohmann** [comment]
I tried this fix, but I cannot get Clang to compile C++11 code. I'm using the same Makefile as before, but the compiler chokes on a non-void version of `std::vector::insert` (see https://travis-ci.org/nlohmann/json/jobs/135778102). I tried with LLVM 3.7.0 and 3.8.0. Any ideas? Any flags needed for a standard library?

**Comment by ahxxm** [comment]
it seems travis still use headers from gcc4.8 according to your [build log](https://travis-ci.org/nlohmann/json/jobs/135778102#L209), try specify `-I`?

**Comment by nlohmann** [comment]
Thanks @ahxxm - I oversaw this. Now (https://travis-ci.org/nlohmann/json/jobs/135802200) I am passing the correct header path, but get a link error, because `libc++.so.1` cannot be found.

**Comment by ahxxm** [comment]
I guess you'll need to modify `LD_LIBRARY_PATH`: `export LD_LIBRARY_PATH=$HOME/clang+llvm/lib:$LD_LIBRARY_PATH` ..  or `ln` that file to existing library path. Or [install prebuilt-binaries](http://stackoverflow.com/questions/17045954/how-to-install-clang-using-precompiled-binaries) other than just decompress it.

**Comment by nlohmann** [comment]
That works. Thanks @ahxxm and sorry for my stupid questions. FYI, here is my [configuration](https://github.com/nlohmann/json/blob/develop/.travis.yml):

```yaml
- os: linux
  env:
    - LLVM_VERSION=3.8.0
    - LLVM_ARCHIVE_PATH=$HOME/clang+llvm.tar.xz
    - CXX=$HOME/clang-$LLVM_VERSION/bin/clang++
    - CPPFLAGS="-I $HOME/clang-$LLVM_VERSION/include/c++/v1"
    - CXXFLAGS=-lc++
    - LD_LIBRARY_PATH=$HOME/clang-$LLVM_VERSION/lib:$LD_LIBRARY_PATH
  before_install:
   - wget http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $LLVM_ARCHIVE_PATH
   - mkdir $HOME/clang-$LLVM_VERSION
   - tar xf $LLVM_ARCHIVE_PATH -C $HOME/clang-$LLVM_VERSION --strip-components 1
```
