### ISSUE TITLE
Github releases draft option

### ISSUE THREAD

**Issue by yasserf** [travis-ci/travis-ci#6132]
Is there a way to tell travis not to publish a release when uploading assets? I need to wait for assets to be uploaded from other places and keep it as a draft. 

Appveyor provides a solution to this with a `draft` flag:

```
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release description'
    auth_token: <auth token>
    artifact: <artifact>
    draft: true <- Specify whether to publish or not
    on:
      appveyor_repo_tag: true
```
