### ISSUE TITLE
linux 32 Bit builds have stopped with my configuration

### ISSUE THREAD

**Issue by reconbot** [travis-ci/travis-ci#6134]
I had linux [32 bit builds](https://github.com/EmergingTechnologyAdvisors/node-serialport/issues/836) that are now building with 64 bit. I suspect I have it configured incorrectly.

Here's a snippit of my travis.yml and [full file](https://github.com/EmergingTechnologyAdvisors/node-serialport/blob/7e20789bf0ef5743448b2b24058311f741218b66/.travis.yml)

```yml
os:
- linux
- osx
env:
  matrix:
  - TRAVIS_NODE_VERSION="0.10"
  - TRAVIS_NODE_VERSION="0.10" ARCH="x86"
  - TRAVIS_NODE_VERSION="0.12"
  - TRAVIS_NODE_VERSION="0.12" ARCH="x86"
  - TRAVIS_NODE_VERSION="4"
  - TRAVIS_NODE_VERSION="4" ARCH="x86"
  - TRAVIS_NODE_VERSION="5"
  - TRAVIS_NODE_VERSION="5" ARCH="x86"
  - TRAVIS_NODE_VERSION="6"
  - TRAVIS_NODE_VERSION="6" ARCH="x86"

```
