### ISSUE TITLE
Upgrade Postgres 9.4.0 to the latest patch level (9.4.8)

### ISSUE THREAD

**Issue by SCdF** [travis-ci/travis-ci#6136]
Currently if you use:
```yamal
addons:
   postgresql: "9.4"
```

You get 9.4.0, which is quite a few patch levels behind the latest 9.4 release. Is it possible to change Travis to use the latest 9.4 build?

**Comment by BanzaiMan** [comment]
Yes. Use `apt` addon to install `postgresql-9.4` (or use `sudo` to stop the service, reinstall the package with `sudo apt-get install postgresql-9.4`).

```yaml
addons:
  apt:
    packages:
      - postgresql-9.4
      - postgresql-client-9.4
      - postgresql-contrib-9.4 # probably optional
      - postgresql-server-dev-9.4 # probably optional
      - libpq-dev # probably optional
```

The default will be updated when the build image is updated (no ETA at this time).
