### ISSUE TITLE
Elasticsearch 2.0 upgrade 

### ISSUE THREAD

**Issue by sonalkr132** [travis-ci/travis-ci#6144]
Using suggestions in [this comment](https://github.com/travis-ci/travis-ci/issues/4542#issuecomment-151848318), I changed my travis.yml file to following:

``` yml
language: ruby

sudo: false

addons:
  apt:
    sources:
      - elasticsearch-2.0  # using 1.7 here works
    packages:
      - elasticsearch
services:
  - elasticsearch

install: true

script:
  - elasticsearch -v
  - curl http://localhost:9200/
```

However I get following on [travis build](https://travis-ci.org/sonalkr132/rubygems.org/builds/136075859#L144):

> elasticsearch is already the newest version.
> 0 upgraded, 0 newly installed, 0 to remove and 245 not upgraded.

ES 2.0 and 2.1 were whitelisted in this commit: https://github.com/travis-ci/apt-source-whitelist/commit/189b706dc54ccbdd99fae5489fcbc71ee1a918c5

**Comment by mkorkmaz** [comment]
Until the day travis start to use latest version of Elasticsearch, I'll use this config [Testing your code with Elasticseach 2 on TravisCI](https://gist.github.com/mkorkmaz/254cd7c46a6fbcf79804158b4a6fb013)

**Comment by BanzaiMan** [comment]
Looks like elastic.io's APT source changed.

I've added `elasticsearch-2.x` source, which makes available the latest 2.x version.

```yaml
addons:
  apt:
    sources:
      - elasticsearch-2.x
    packages:
      elasticsearch
```
