### ISSUE TITLE
Deploy Failure: No such file or directory

### ISSUE THREAD

**Issue by phxvyper** [travis-ci/travis-ci#6179]
I can't shake this issue in my setup:

![http://i.imgur.com/p8jfVht.png](http://i.imgur.com/p8jfVht.png)

this is my current .travis.yml:

```YAML
language: objective-c
osx_image: xcode61
rvm:
- 2.1.2
before_install:
- chmod a+x ./Scripts/install.sh
install:
- "./Scripts/install.sh"
script:
- "./Scripts/build.sh"
deploy:
- provider: s3
  access_key_id: <MY ID>
  secret_access_key: <MY KEY>
  bucket: builds.cygnus.com
  local-dir: Build
  skip_cleanup: true
  acl: 'private'
  on:
    repo: phxvyper/Project-Cygnus
    all_branches: true
```

I've tried a whole load of things including different bucket names, different directories on the bucket, not skipping cleanup, different branches. Nothing has worked so far, whats wrong?

Here is a link to the build job in the picture above: https://travis-ci.org/phxvyper/Project-Cygnus/builds/137977008

(The Build directory should be created via the Build.sh script when it sends jobs to Unity)
