### ISSUE TITLE
Build fails to start when overriding install section in `matrix.include`

### ISSUE THREAD

**Issue by thedrow** [travis-ci/travis-ci#6182]
See https://travis-ci.org/cachelot/cachelot/jobs/138153424
https://github.com/thedrow/cachelot/blob/patch-1/.travis.yml#L21

**Comment by BanzaiMan** [comment]
Is this still the case? I tried this configuration (https://github.com/BanzaiMan/travis_production_test/blob/a9be0e29191fb24d55c4c9bdf7e3fcb148cd260c/.travis.yml#L5-L19):

```yaml
env:
  - DIST=precise STACK=EC2

matrix:
  include:
    - sudo: required
      dist: precise
      env: DIST=precise STACK=GCE
    - sudo: false
      dist: trusty
      env: DIST=trusty STACK=EC2
    - sudo: required
      dist: trusty
      env: DIST=trusty STACK=GCE
      install: echo yes
```

and it worked fine: https://travis-ci.org/BanzaiMan/travis_production_test/jobs/195059227#L246
