### ISSUE TITLE
Redundant "no language set" jobs

### ISSUE THREAD

**Issue by MyLittleRobo** [travis-ci/travis-ci#6213]
I have this matrix in .travis.yml

```
language: d

env:
  - CONFIG=default

os:
  - linux
  - osx
  
matrix:
  include:
    - d: dmd-2.071.0
    - d: gdc-4.9.2
      os: linux
    - d: ldc-1.0.0
      os: linux
    - d: ldc-1.0.0
      os: osx
      env: CONFIG=cocoa
```

So as you see I explicitly set compilers. Still travis runs two jobs with "no language set" and actually installs latest compilers in them.

![travis-no-language-set](https://cloud.githubusercontent.com/assets/5596503/16299583/bed8665c-3943-11e6-833c-632b5a809fa2.png)

Also I have job for dmd-2.071.0 in matrix, and in travis UI it looks like no operating system set (though it runs on linux). My intention was to run jobs for both Linux and OSX. Should I explicitly include jobs for two operating systems?

[Link to build](https://travis-ci.org/MyLittleRobo/standardpaths/builds/139716604)
