### ISSUE TITLE
Problems with gi (Python) : no require_version, no repository

### ISSUE THREAD

**Issue by algorys** [travis-ci/travis-ci#6240]
Hello,

I'm making an application with appindicator and gtk and try to pass some test on travis : https://github.com/Alignak-monitoring-contrib/alignak-app

When I try to run my test, with python2.7 to begin, `gi.repository` and `gi.require_version` are not founds !

For example : https://travis-ci.org/Alignak-monitoring-contrib/alignak-app/builds/141354598

Is there a way to solve this problems because I've attempt many try to make it work but anyway. 

Is there a bug ?
Maybe I missed something in my `.travis.yml` file ?
Or is it impossible to run this kind of application with Travis ?

**EDIT:**
I've seen also on other issues that I have to use python 3.2 ! There is no possiblities to use python 3.5 and python-gi on Travis ?

Thanks for help.

**Comment by algorys** [comment]
I've progress to get it work, but only in python2.7. (inspired by issue #2219)

It seems install `gi` with pip3 does not work (many errors during use). Only pip (or pip2) works fine. 

But on Ubuntu 16.04 LTS, import `gi` ( in python2) and run with Python3 seems work. I've tried to make same environment in Travis, but when I install `gi` in Python2, I fail to import this lib.

Here is the `.travis.yml` file I done:

```yaml
language: python
sudo: true
python:
  - "2.7_with_system_site_packages"
  - "3.5" #python3-gi is bugged and Travis not let to access to python-gi (py2.7)

#virtualenv:
#  system_site_packages: true

before_install:
  - sudo apt-get update
  - sudo apt-get install -qq python-gi gir1.2-gtk-3.0 ibus gir1.2-appindicator3-0.1 gir1.2-notify-0.7 gir1.2-glib-2.0

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - pip install -r requirements.txt
  - pip install -r test/requirements.txt

script:
  # so to help eventual debug: knowing what exact versions are in use can be rather useful.
  - pip freeze
  # Code static analysis
  # - pep8 --max-line-length=100 --exclude='*.pyc, *.cfg, *.log' --ignore='E402' alignak_app/*
  #- pylint --rcfile=.pylintrc alignak_webui/
  # No pep257 currently (Code doc compliance)
  # - pep257 --select=D300 alignak_webui
  # Code dynamic analysis
  # - cd test
  - coverage erase
  - nosetests -xv --nologcapture --with-coverage --cover-package=alignak_app test/test_application.py
  - coverage combine
  - coverage report -m
  # - cd ..

# specific call to launch coverage data into coveralls.io
after_success:
  # to get coverage data with relative paths and not absolute we have to
  # execute coveralls from the base directory of the project,
  # so we need to move the .coverage file here :
  # mv test/.coverage . && coveralls --rcfile=test/.coveragerc -v
  coveralls -v
```

I've tried many other solution like install by pip, pip3, python3-gi, ... but anyway.
