### ISSUE TITLE
Allowed failures in matrix show in regular area

### ISSUE THREAD

**Issue by seancribbs** [travis-ci/travis-ci#626]
My matrix allows failures on certain rvms, but these show in the regular build area after the build has finished. Note that this displays correctly _before_ the build completes.

![allow failures](http://seancribbs-skitch.s3.amazonaws.com/allowedfailures-not-20120706-120128.png)

My `.travis.yml`:

``` yaml
rvm:
  - 1.8.7
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: rbx-18mode
    - rvm: rbx-19mode
bundler_args: --without=guard
before_script:
  - ! 'echo "root: .riaktest" > spec/support/test_server.yml'
  - ! 'echo "source: /usr/sbin" >> spec/support/test_server.yml'
  - "ulimit -n 2048"
notifications:
  webhooks: http://basho-engbot.herokuapp.com/travis?key=d9ab1d53db09fc1760d7a5dde3246201522ca2c7
  email: sean@basho.com
```
