### ISSUE TITLE
Android API Level 24 (Nougat) not found

### ISSUE THREAD

**Issue by kartikarora** [travis-ci/travis-ci#6260]
My current .travis.yml file is as follows:
```yml
language: android
jdk: oraclejdk8
android:
    components:
        - build-tools-24.0.0
        - android-24
        - platform-tools
        - extra-android-support
        - extra-android-m2repository
        - extra-google-m2repository
        - extra-google-google_play_services
    licenses:
        - 'android-sdk-license-.+'
before_script:
    - chmod +x gradlew
```

My build is failing with the message
`> failed to find target with hash string 'android-24' in: /usr/local/android-sdk`

Is API 24 not available on Travis yet? Or am I referencing it incorrectly?
