### ISSUE TITLE
MongoDB 3.2

### ISSUE THREAD

**Issue by shortdudey123** [travis-ci/travis-ci#6261]
Any plans to update the provided version of MongoDB?

```
MongoDB version
MongoDB 2.4.12
```

[2.6](https://github.com/travis-ci/travis-ci/issues/2246) and [3.0](https://github.com/travis-ci/travis-ci/issues/3694) requests have no updates in over a year

2.4 was EOL'd March 2016
2.6 will EOL October 2016 (5 months from now)
3.0 presumebly will EOL March 2017 (10 months from now)
(https://www.mongodb.com/support-policy)

**Comment by BanzaiMan** [comment]
I'm closing this as a duplicate of #3694.

**Comment by shortdudey123** [comment]
@BanzaiMan https://github.com/travis-ci/travis-ci/issues/3694 asks for `3.0`, while this is `3.2` :)

**Comment by BanzaiMan** [comment]
@shortdudey123 I updated the #3694 accordingly. IIRC, mongo's APT package does not allow side-by-side installation, so if we choose 3.2, we cannot support 3.0 on the same image.

**Comment by shortdudey123** [comment]
gotcha and yes, you can't have 2 versions side by side since the binaries are in the same path

**Comment by arve0** [comment]
Unable to comment on #3694. Here is a working `.travis.yml` for 3.2:

```yaml
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
```

Source: https://softinstigate.atlassian.net/browse/RH-176

**Comment by fguillen** [comment]
For support for MongoDB 3.4, this worked for me:

```
services:
  - mongodb

addons:
  apt:
    sources:
      - mongodb-3.4-precise
    packages:
      - mongodb-org-server
```
