### ISSUE TITLE
Question: Is it possible to expose the Gemfile that is used when running builds using a matrix? 

### ISSUE THREAD

**Issue by bogdanRada** [travis-ci/travis-ci#6266]
I am trying to use **appraisal** gem to run my tests for multiple rails versions. 

Currently i have this configuration:
```yaml
sudo: false
cache: bundler
language: ruby
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem install bundler
  - bundle install
gemfile:
  - gemfiles/rails_4.0.0.gemfile
  - gemfiles/rails_4.0.2.gemfile
  - gemfiles/rails_4.1.1.gemfile
  - gemfiles/rails_4.1.4.gemfile
  - gemfiles/rails_4.1.9.gemfile
  - gemfiles/rails_4.2.0.gemfile
  - gemfiles/rails_4.2.1.gemfile
  - gemfiles/rails_4.2.2.gemfile
  - gemfiles/rails_4.2.3.gemfile
  - gemfiles/rails_4.2.4.gemfile
  - gemfiles/rails_4.2.4.gemfile
  - gemfiles/rails_4.2.5.gemfile
  - gemfiles/rails_4.2.6.gemfile
  - gemfiles/rails_5.0.0.gemfile
rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.2
  - 2.3.1
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/rails_5.0.0.gemfile
    - rvm: 2.1.5
      gemfile: gemfiles/rails_5.0.0.gemfile
env:
 - RAILS_ENV=test RACK_ENV=test
notifications:
  email: false
```

This generates some builds that have the names like this:
```bash
 Ruby: 2.1.5 Gemfile: gemfiles/rails_4.0.0.gemfile

  Ruby: 2.1.5 Gemfile: gemfiles/rails_4.0.2.gemfile

  Ruby: 2.1.5  Gemfile: gemfiles/rails_4.1,1.gemfile
  ........

```

However i not sure how can i know in my Rakefile what Gemfile is used currently for the current build. 

I tried this:
````ruby
desc 'Default: run the unit tests.'
task default: [:all]

desc 'Test the plugin under all supported Rails versions.'
task :all do |_t|
  if ENV['TRAVIS']
    if ENV['BUNDLE_GEMFILE'] =~ /gemfiles/
      appraisal_name = ENV['BUNDLE_GEMFILE'].scan(/rails\_(.*)\.gemfile/).flatten.first
      command_prefix = "appraisal rails-#{appraisal_name}"
      exec ("#{command_prefix} bundle install && #{command_prefix} bundle exec rspec ")
    else
    exec(' bundle exec appraisal install && bundle exec rake appraisal spec')
  end
  else
    exec('bundle exec appraisal install && bundle exec rake appraisal spec')
  end
end

```

But seems that ENV['BUNDLE_GEMFILE'] point to the Gemfile that is in the root of the project, and not the one from the build name.

Because of this now all builds are installing the gems for each rails version and running all tests for each of the rails versions i have in my Appraisal file , not just for the current rails version. 

Maybe we can add a new environment variable ?  TRAVIS_GEMFILE ? or something? 

I am not sure if this is possible or is already possible. I have searched everywhere including Google,StackOverflow, Gist, Github and found nothing:( 

Is there a  way to do this? Or any plans in the future for exposing the path of the Gemfile that is used to the build as a environment variable? 

Thank you very much. 

Or maybe just expose the name of the build as a environment variable? That could help also.
