### ISSUE TITLE
Build continues to run after 4 Mb limit has been reached

### ISSUE THREAD

**Issue by joepvd** [travis-ci/travis-ci#6276]
Build continues to run after 4 Mb limit has been reached. This could be reproduced for the `sudo: required`-builds. 

Build logs here: https://travis-ci.org/joepvd/travis-experiment/builds/142996215

`.travis.yml`:

```
language: bash

matrix:
  include:
    - sudo: false
    - sudo: required
      dist: precise
    - sudo: required
      dist: trusty

install: false

script: sh -c 'false'

after_failure: awk 'BEGIN{a="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n";while(1){a=a a;print a}}'
```
