### ISSUE TITLE
shell_session_update error

### ISSUE THREAD

**Issue by afestein** [travis-ci/travis-ci#6307]
I am seeing a new error on an OSX / objective-c project which has previously been running fine: 

`/Users/travis/build.sh: line 109: shell_session_update: command not found`

It seems to be a new issue with the xcode7.3 OSX image, as it passes this stage if I revert back to the default by removing the `osx_image` line.

Contents of my travis.yml: 

```
language: objective-c
osx_image: xcode7.3
cache:
  bundler: true
  cocoapods: true
  directories:
    - build
before_install:
  - (ruby --version)
  - sudo chown -R travis ~/Library/RubyMotion
  - sudo mkdir -p ~/Library/RubyMotion/build
  - sudo chown -R travis ~/Library/RubyMotion/build
  - sudo motion update
after_success:
  - bin/travis_deploy
script:
  - bundle install --jobs=3 --retry=3
  - pod repo update && rake pod:install
  - bundle exec rake clean
  - bundle exec rake spec
```

Link to the build: https://travis-ci.com/cvcnetwork/yesheis-motion-ios/builds/28293964

Any help greatly appreciated.
