### ISSUE TITLE
Cache timeout not working

### ISSUE THREAD

**Issue by lukeyeager** [travis-ci/travis-ci#6317]
I've set the cache timeout for [my repository](https://github.com/NVIDIA/DIGITS/blob/v4.0.0-rc.3/.travis.yml#L17-L22) to be 1 week:
```yml
cache:
    timeout: 604800  # 1 week
    apt: true
    directories:
        - ~/caffe
        - ~/torch
```
And yet I have caches that are many months old.
![travis-cache-age](https://cloud.githubusercontent.com/assets/687269/16887745/ad0fe504-4a90-11e6-806d-ae36550543e4.jpg)

I have the same problem with [a little test repo](https://github.com/lukeyeager/github-testing) for which the timeout is set to 2 seconds. I figured that would essentially disable the cache, and yet each successive build keeps using the same original cached data.

Am I misunderstanding how the cache timeout is supposed to work?
