### ISSUE TITLE
Travis-ci wedged or something stuck tried to build for PHP 5.5 but not in  travis config

### ISSUE THREAD

**Issue by Dragonrun1** [travis-ci/travis-ci#6322]
So I've tried it a few times now and it keeps trying to use PHP 5.5 but I only have PHP 5.6 and above in config. Not sure this is the right way to get hold of somebody to fix it but couldn't find any other options. It from GitHub project Dragonrun1 / event-mediator start with build 23 I think.

**Comment by BanzaiMan** [comment]
I don't see anything stuck in https://travis-ci.org/Dragonrun1/event-mediator/builds.

This part does not do what I think you want to do.

```yaml
matrix:
    allow_failures:
        - php: 7.1
    php:
        - 7.0
        - 7.1
        - 5.6
```

If you want to create a build matrix consisting of 3 jobs, with PHP 7.0, 7.1, and 5.6, but allow 7.1 to fail, what you need is:

```yaml
php:
  - 7.0
  - 7.1
  - 5.6
matrix:
  allow_failures:
    - php: 7.1
```
