### ISSUE TITLE
Build won't run in Trusty

### ISSUE THREAD

**Issue by jbw91** [travis-ci/travis-ci#6334]
In attempting to install Google Chrome for my travis build, I was following the instructions which included using the Trusty Beta Build Environment outlined [here](https://docs.travis-ci.com/user/trusty-ci-environment#Using-the-Trusty-beta). My `.travis.yml` is set up as follows:

```yml
language: node_js
node_js:
  - "5.10"

before_install:
  - "export CHROME_BIN=/usr/bin/google-chrome"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - npm install

script:
  - ng lint
  - ng test --watch=false

sudo: required
dist: trusty

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

notifications:
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/64e4a7be47fac5f5415d"
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
```

As you can see, I'm properly using the `sudo: required` and `dist: trusty` that is required in the instructions in the link about the Trusty Beta. However, when it actually builds, the build logs indicate that it is actually running on Ubuntu 12.04 (Precise). My build log is [here](https://s3.amazonaws.com/archive.travis-ci.org/jobs/145958445/log.txt).

It appears as though it is incorrectly assigning my build to a 12.04 machine. This is problematic, as Chrome is no longer installable on 12.04, and so all Stack Overflow answers and tickets related to this issue say you need to use the Trusty Beta. Happy to give any clarification needed.
