### ISSUE TITLE
Unable to run Espresso UI tests on travis

### ISSUE THREAD

**Issue by kyrogue** [travis-ci/travis-ci#6340]
Hello, have anyone faced this problem before 

```
java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not be requesting layout for over 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Otherwise, something is seriously wrong. Selected Root:

	Root{application-window-token=android.view.ViewRootImpl$W@21339606, window-token=android.view.ViewRootImpl$W@21339606, has-window-focus=false, layout-params-type=1, layout-params-string=WM.LayoutParams{(0,0)(fillxfill) sim=#110 ty=1 fl=#81810100 pfl=0x8 wanim=0x1030461 surfaceInsets=Rect(0, 0 - 0, 0)}, decor-view-string=DecorView{id=-1, visibility=VISIBLE, width=320, height=480, has-focus=true, has-focusable=true, has-window-focus=false, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}}
```

This is my travis .yml config

```
language: android
jdk: oraclejdk8

before_install:
  - chmod +x gradlew
  - android list target

android:
  components:
        - tools
        - platform-tools
        - build-tools-24.0.0
        - android-24
        - extra-android-m2repository
        - extra-android-support
        - sys-img-armeabi-v7a-android-21
  licenses:
      - 'android-sdk-license-.+'

    # Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script: 
  - ./gradlew connectedInmemoryDebugAndroidTest
```

i have tried running the same emulator setup locally by creating that emulator , and running my tests locally the same error appears... is there something wrong with the emulator creation?
