### ISSUE TITLE
Deploy to local ubuntu as part of custom deployment

### ISSUE THREAD

**Issue by JinnaBalu** [travis-ci/travis-ci#6343]
How do we right the script to deploy to the ubuntu local machine.

here is my travis.yml file

```yaml
language: node_js
node_js:
- '0.10'
- '0.11'
env:
  global:
    - "FTP_USER=****" # this i kept in * intentinally
    - "FTP_PASSWORD=*******"  # this i kept in * intentinally
branches:
  only:
  - master
before_script:
- npm install -g bower gulp karma
- bower install
script: gulp
notifications:
  email:
    recipients:
    - test.test@outlook.com
```
  
new ti travis and want to deploy to local ubuntu machine through ftp.
