### ISSUE TITLE
Support `cache: carthage` to automatically cache Carthage dependencies

### ISSUE THREAD

**Issue by cotsog** [travis-ci/travis-ci#6348]
As Travis CI does already for Cocoapods dependencies, it would be nice to cache [Carthage](https://github.com/Carthage/Carthage) dependencies just by adding the following to the .travis.yml file:

```
cache: carthage
```
or
```
cache:
  bundler: true
  carthage: true
```

Right now, Carthage users need to use [the directory caching feature](https://docs.travis-ci.com/user/caching/#Arbitrary-directories) instead.

Thank you! ❤️

**Comment by BanzaiMan** [comment]
See also https://github.com/Carthage/Carthage/issues/1403.

**Comment by alickbass** [comment]
@BanzaiMan are there any news the carthage caching?

**Comment by zocario** [comment]
Would really love to see this feature implemented, any news about this?

**Comment by Nirma** [comment]
This feature would be awesome, sometimes I feel like Travis CI has no love for iOS Devs.

😿 Prove me wrong Travis CI, please prove me wrong. 😿

**Comment by alickbass** [comment]
@Nirma you can already use Travis cache with new versions of carthage as following:

```yaml
language: objective-c
osx_image: xcode8.2

cache:
  directories:
  - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds
```
