### ISSUE TITLE
npm won't install TypeScript 2.0 new @types/* packages although they are public

### ISSUE THREAD

**Issue by Dynalon** [travis-ci/travis-ci#6350]
With TypeScript 2.0 (currently in beta), a [new way of installing type information was introduced](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/). Type information (d.ts files) are now installed via `npm` using the `@types/` scope.

Local workflow for i.e. installing the `es6-promise` dependency:

```
# install the actual code
npm install --save es6-promise

# installs the .d.ts file with type information to make TypeScript 2.0 happy
npm install --save-dev @types/es6-promise
```

The `package.json` will then have an entry like this:

```
"devDependencies": {
    "@types/es6-promise": "0.0.28"
}
```

While this works all locally, the travis build system will not be able to install the scoped `@types/es6-promise` package:

```
1.10s$ npm install
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'types/es6-promise' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'mypackage-name'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.
```

Note while the "@types" is a "private" npm repository managed by the TypeScript team, it's access is actually public - no tokens or authentication is needed to access it.

Given that soon TypeScript 2.0 will be out and this the new default way to install types, travis should be able to handle those cases.

**Comment by BanzaiMan** [comment]
Is `npm` up to date?

**Comment by Dynalon** [comment]
I have the following `.travis.yml` file:

```yml
udo: false
language: javascript
node_js:
  - 'stable'


install:
  # newer npm spinner is just a pain and will mess up in the logfiles
  - npm config set spin=false
  - npm install

script:
  # compile main source
  - npm run build                      
```

So I assume npm is up to date. From the output of travis build I think the `@` sign is somewhat swallowed.

This is the public build output: https://travis-ci.org/pubsub-a/pubsub-a-interfaces/builds/146830243
Building this github repo: https://github.com/pubsub-a/pubsub-a-interfaces (master)
