### ISSUE TITLE
Deploying with multiple custom deployment providers fails

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#6359]
Suppose you have:

```yaml
deploy:
  - provider: script
    edge:
      source: OWNER/dpl
    script: echo "foo"
  - provider: script
    edge:
      source: OWNER/dpl
    script: echo "bar"
```

The first deployment succeeds, but the second will fail:

```
fatal: destination path 'OWNER/dpl' already exists and is not an empty directory.
```
