### ISSUE TITLE
failed and exited with 128 during deploy with custom deploy tool

### ISSUE THREAD

**Issue by sven4ask** [travis-ci/travis-ci#6360]
I have using this configuration for quite some time, but since today it is broken:

```
deploy:
- provider: elasticbeanstalk
  edge:
     source: jasny/dpl
     branch: master
  access_key_id: xxx
  ....
- provider: elasticbeanstalk
  edge:
     source: jasny/dpl
     branch: master
  access_key_id: xxx
  ...
  only_create_app_version: true
  on:
    branch: master
```

I am now receiving the following error:
```
[0Ktravis_time:start:0046f0de
[0Kfatal: destination path 'jasny/dpl' already exists and is not an empty directory.

travis_time:end:0046f0de:start=1469531235989328900,finish=1469531235993804945,duration=4476045
[0K
[31;1mThe command "git clone https://github.com/jasny/dpl jasny/dpl" failed and exited with 128 during .[0m
```

I am doing 2 deploys after each other using a custom deploy tool. But the second time is complains the destination directory already exists.
