### ISSUE TITLE
Cannot use "process.chdir"

### ISSUE THREAD

**Issue by gluons** [travis-ci/travis-ci#6363]
#### Node.js

I've used `process.chdir` and I get this error in build log.
```javascript
process.chdir(targetPath); // Change current working directory

^
Error: EACCES: permission denied, uv_chdir
```

My **.travis.yml**
```yaml
language: node_js
node_js:
  - "6"
  - "5"
  - "4"
before_script:
  - sudo chmod 444 ./test/unwritableTarget
  - sudo chmod 777 ./test/writableTarget
install:
  - npm install -g mocha
  - npm install
```

I've tried to googling but I can't find solution.

Please let me know how to correctly change directory.
