### ISSUE TITLE
Specify JDK version for non java projects

### ISSUE THREAD

**Issue by wisechengyi** [travis-ci/travis-ci#6371]
Hi,

Our project is mainly python, but it also invokes other jvm dependent tools. I was wondering if it would be possible to specify jdk version in this case? 

Currently specifying oraclejdk8 does not do anything.
```
language: python

python:
  - "2.7"

jdk:
  - oraclejdk8
```

Thanks,
Yi

**Comment by BanzaiMan** [comment]
For various reasons, each language image is specialized to accommodate the language for which it was built. Unfortunately, Python and JVM do not mix well.

One thing you can do, however, is to use the newer Trusty image that has (most) everything. https://docs.travis-ci.com/user/trusty-ci-environment#Image-differences-from-Precise With it, you can specify `language: python` and use `jdk_switcher` to switch to a different JVM.

```yaml
sudo: required
dist: trusty
language: python
python:
  - '2.7'
before_install:
  - jdk_switcher use oraclejdk8
```

See https://travis-ci.org/BanzaiMan/travis_production_test/builds/147904108.
