### ISSUE TITLE
Specifying multiple Chef environments fails with old version

### ISSUE THREAD

**Issue by miketheman** [travis-ci/travis-ci#638]
I've got a Knife plugin that needs testing.
I set up a .travis.yml file, as can be seen [here](https://github.com/miketheman/knife-role-spaghetti/blob/master/.travis.yml)

``` yaml
rvm:
  - 1.9.2
  - 1.9.3
env:
  - CHEF_VERSION=0.9.18
  - CHEF_VERSION=0.10.8
  - CHEF_VERSION=10.12.0
```

However, when run, the chef gem that is installed in any of the ruby versions is chef 0.8.10 (log output [here](http://travis-ci.org/#!/miketheman/knife-role-spaghetti/jobs/1913499/L46)).

Since I don't specify the version in my Gemfile, my assumption is that the latest version would be used. However, using the CHEF_VERSION environment variables, my expectation is that it selects the specified one.

Am I doing something wrong? Or have I surfaced a problem?
