### ISSUE TITLE
Builds stall/error without reporting an error of any kind

### ISSUE THREAD

**Issue by jhamman** [travis-ci/travis-ci#6381]
I'm hesitant to report an build error here but I think this might actually be a travis problem. We have a travis yml config that looks like [this](https://github.com/UW-Hydro/VIC/blob/develop/.travis.yml):

```yml

language: c
sudo: false # use container based build
notifications:
  email: false

matrix:
  fast_finish: true
  include:
  # Image Driver
  - compiler: gcc
    os: linux
    env: TESTID='image'
    addons:
      apt_packages:
        - libnetcdf-dev
        - netcdf-bin
        - netcdf-doc
        - gfortran
        - valgrind
        # open-mpi is built from source in image.travis

...
```

Two builds that rely on `apt_packages` have started failing in the last 24 hours that were previously passing.  I restarted [This](https://travis-ci.org/UW-Hydro/VIC/builds/148123729) build, which had previously passed and it is now "erroring" without leaving an error message. Because it is not actually raising an error prior to failing, I'm not sure how to debug further.

The tail of one of the [errored logs](https://s3.amazonaws.com/archive.travis-ci.org/jobs/148123731/log.txt) looks like: 

```
travis_time:end:0093fd38:start=1469822302563455241,finish=1469822371011024482,duration=68447569241
[0Ktravis_fold:end:before_install.3
[0Ktravis_fold:start:before_install.4
[0Ktravis_time:start:303e8539
[0K$ vic_before_install
vic_before_install
/home/travis/miniconda/envs/vic_test_env/bin:/home/travis/miniconda/bin:/home/travis/bin:/home/travis/.local/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/usr/local/phantomjs/bin:/home/travis/.nvm/v0.10.36/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/usr/local/phantomjs/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/home/travis/.rvm/gems/ruby-1.9.3-p551/bin:/home/travis/.rvm/gems/ruby-1.9.3-p551@global/bin:/home/travis/.rvm/rubies/ruby-1.9.3-p551/bin:/usr/local/phantomjs/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/travis/.rvm/bin:/home/travis/.rvm/bin:/home/travis/.rvm/bin
```

xref: https://github.com/UW-Hydro/VIC/pull/561, https://github.com/UW-Hydro/VIC/pull/568
