### ISSUE TITLE
iOS unknown build action 'Simulator'

### ISSUE THREAD

**Issue by daehn** [travis-ci/travis-ci#6408]
I am having trouble setting up an iOS project on travis, the xcodebuild command reports `Unknown build action 'Simulator'` [as seen here](https://travis-ci.org/wireapp/wire-ios-sync-engine/builds/149693958). We set up travis for a couple of iOS projects and use fairly similar xcodebuild commands, which so far worked for all of the other repositories.

The relevant parts of the .travis.yml:

```yml
language: objective-c
osx_image: xcode7.3

install:
  - carthage bootstrap --platform iOS

script:
  - open -b com.apple.iphonesimulator
  - set -o pipefail
  - travis_wait 30 xcodebuild build -scheme zmessaging-ios -destination 'name=iPhone 6s,OS=9.3,platform=iOS Simulator' test | tee >build.log >(xcpretty -s)
```

And the full error:

```
Build settings from command line:
    6s,OS = 9.3,platform=iOS
xcodebuild: error: Unknown build action 'Simulator'.
```

I've tried `xctool` using the following command but get a similar error there `ERROR: Unexpected action: Simulator`:

```
xctool -scheme zmessaging-ios -destination 'name=iPhone 6s,OS=9.3,platform=iOS Simulator' test -sdk iphonesimulator
```
