### ISSUE TITLE
docker registry proxy for travis builders

### ISSUE THREAD

**Issue by KostyaSha** [travis-ci/travis-ci#6418]
Hi, do you have any local to builders docker-registry proxy?
https://blog.docker.com/2015/10/registry-proxy-cache-docker-open-source/

**Comment by janisozaur** [comment]
This would be a really good addition to Travis CI. Many of docker images are based on common images, like the official Ubuntu ones, adding a local cache would certainly speed things up.

I'm looking forward to seeing it implemented.

**Comment by edmorley** [comment]
In case it saves anyone else time who is thinking of testing the same, I tried using Google's Container Registry mirror of Docker Hub:
https://cloud.google.com/container-registry/docs/using-dockerhub-mirroring

Eg using:
```yaml
install:
  - echo 'DOCKER_OPTS="$DOCKER_OPTS --debug --registry-mirror=https://us-mirror.gcr.io"' | sudo tee -a /etc/default/docker > /dev/null
  - sudo service docker restart
  - docker system info
script:
  - docker --log-level debug pull ubuntu:latest
  - docker --log-level debug pull ubuntu:16.04
  - docker --log-level debug pull heroku/heroku:16
  - sudo cat /var/log/upstart/docker.log
```

Example run:
https://travis-ci.org/edmorley/travis-testing/builds/252211908

Log output of note:
```
time="2017-07-10T23:30:16.525306602Z" level=debug msg="Trying to pull ubuntu from https://us-mirror.gcr.io/ v2" 
time="2017-07-10T23:30:16.602624904Z" level=info msg="Attempting next endpoint for pull after error: manifest unknown: Failed to fetch \"16.04\" from request \"/v2/library/ubuntu/manifests/16.04\"." 
time="2017-07-10T23:30:16.602682070Z" level=debug msg="Trying to pull ubuntu from https://registry-1.docker.io v2" 
```

However:
(a) unfortunately the mirror seems to only support official images and even then only of tag `latest` ([see here](https://ahmet.im/blog/google-container-registry-tips/#gcr-tip-6)), 
(b) even for the `ubuntu:latest` image in the example above, the pull time is about the same as with no mirror.

It's possible a Travis registry mirror hosted in the same GCE zone as the sudo-enabled jobs might still be faster of course.
