### ISSUE TITLE
Using node6 `node-gyp rebuild` failing

### ISSUE THREAD

**Issue by frankcash** [travis-ci/travis-ci#6428]
Here is my .travis.yml
```
sudo: required
language: node_js
notifications:
  email: false
node_js:
  - "6.3.1"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
    packages:
      - xvfb


env:
  - CXX=g++-4.8

cache:
  directories:
    - node_modules

before_install:
  - npm install -g npm@latest

install:
  - export CXX="g++-4.8"
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install

script:
  - npm run dev
```

Here is the error 

```
> nslog@3.0.0 install /home/travis/build/henryboldi/felony/node_modules/nslog

> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR

make: Entering directory `/home/travis/build/henryboldi/felony/node_modules/nslog/build'

  CXX(target) Release/obj.target/nslog/src/main.o

make: g++-4.8: Command not found

make: *** [Release/obj.target/nslog/src/main.o] Error 127

make: Leaving directory `/home/travis/build/henryboldi/felony/node_modules/nslog/build'

gyp ERR! build error 

gyp ERR! stack Error: `make` failed with exit code: 2

gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/versions/node/v6.3.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)

gyp ERR! stack     at emitTwo (events.js:106:13)

gyp ERR! stack     at ChildProcess.emit (events.js:191:7)

gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)

gyp ERR! System Linux 3.13.0-63-generic

gyp ERR! command "/home/travis/.nvm/versions/node/v6.3.1/bin/node" "/home/travis/.nvm/versions/node/v6.3.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"

gyp ERR! cwd /home/travis/build/henryboldi/felony/node_modules/nslog

gyp ERR! 35mnode -v v6.3.1

gyp ERR! node-gyp -v v3.4.0

gyp ERR! not ok 

```

Here is a link to the log <https://api.travis-ci.org/jobs/150729882/log.txt?deansi=true>

**Comment by BanzaiMan** [comment]
It appears that your build is not properly set up to use g++-4.8.

> Starting with io.js 3 and Node.js 4, building native extensions requires C++11-compatible compiler, which seems unavailable on this VM. Please read https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements.

In https://github.com/henryboldi/felony/blob/fab2ab2aac40989fdc5be8f92a278a93bfe184af/.travis.yml#L12-L15, you are defining `packages` twice, and only the last one is effective. In the logs, you see that `xfvb` is installed, but `g++-4.8` is not. Fix this, and your build should go.

**Comment by frankcash** [comment]
Okay, I did what you said and the problem persists

https://api.travis-ci.org/jobs/150749283/log.txt?deansi=true


```
sudo: required
language: node_js
notifications:
  email: false
node_js:
  - "6.3.1"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - xvfb


env:
  - CXX=g++-4.8

cache:
  directories:
    - node_modules

before_install:
  - npm install -g npm@latest

install:
  - export CXX="g++-4.8"
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install

script:
  - npm run dev
```
