### ISSUE TITLE
Allow failures with Python & env with PlatformIO are not working

### ISSUE THREAD

**Issue by photodude** [travis-ci/travis-ci#6444]
Allow failures with Python & env with PlatformIO are not working as expected. Specified Allow failures from the **env:** [are not showing up as Allow failures](https://travis-ci.org/photodude/DualVNH5019MotorShieldMod3/builds/151093845)

[My testing .travis.yml set up](https://github.com/photodude/DualVNH5019MotorShieldMod3/blob/master/.travis.yml)
```yml
# Test build your arduino libraries with travis and Arturo
language: python

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
  directories:
    - "~/.platformio"

matrix:
  fast_finish: true
  include:
    - python: "2.7"
      env:
        - PLATFORMIO_CI_EXTRA_ARGS="--board=megaatmega2560" PLATFORMIO_CI_SRC=DualVNH5019MotorShieldMod3/examples/Demo/Demo.ino
    - python: "2.7"
      env:
        - PLATFORMIO_CI_EXTRA_ARGS="--board=due" PLATFORMIO_CI_SRC=DualVNH5019MotorShieldMod3/examples/Demo/Demo.ino
    - python: "2.7"
      env:
        - PLATFORMIO_CI_EXTRA_ARGS="--board=uno" PLATFORMIO_CI_SRC=DualVNH5019MotorShieldMod3/examples/Demo/Demo.ino
    - python: "2.7"
      env:
        - PLATFORMIO_CI_EXTRA_ARGS="--board=megaatmega2560" PLATFORMIO_CI_SRC=DualVNH5019MotorShieldMod3/examples/Test_Motors/Test_Motors.ino
    - python: "2.7"
      env:
        - PLATFORMIO_CI_EXTRA_ARGS="--board=due" PLATFORMIO_CI_SRC=DualVNH5019MotorShieldMod3/examples/Test_Motors/Test_Motors.ino
    - python: "2.7"
      env:
        - PLATFORMIO_CI_EXTRA_ARGS="--board=uno" PLATFORMIO_CI_SRC=DualVNH5019MotorShieldMod3/examples/Test_Motors/Test_Motors.ino
  allow_failures:
    - python: "2.7"
      env:
        - PLATFORMIO_CI_EXTRA_ARGS="--board=uno" PLATFORMIO_CI_SRC=DualVNH5019MotorShieldMod3/examples/Demo/Demo.ino
    - python: "2.7"
      env:
        - PLATFORMIO_CI_EXTRA_ARGS="--board=uno" PLATFORMIO_CI_SRC=DualVNH5019MotorShieldMod3/examples/Test_Motors/Test_Motors.ino

install:
  - pip install -U platformio

script:
  - platformio ci --lib="DualVNH5019MotorShieldMod3" $PLATFORMIO_CI_EXTRA_ARGS
```

[Build showing that the allowed failures are not showing as Allowed Failures](https://travis-ci.org/photodude/DualVNH5019MotorShieldMod3/builds/151093845)

Note: I really just want to specify a specific board as an allowed failure.
