### ISSUE TITLE
PostgreSQL 9.1 is not installed!

### ISSUE THREAD

**Issue by greedo** [travis-ci/travis-ci#6455]
When doing an install of PostgreSQL 9.5 using the cookbook method outlined [here](https://github.com/travis-ci/travis-ci/issues/4264#issuecomment-185987262) by @0x6e6562 I am receiving a message that `PostgreSQL 9.1 is not installed!`

<img width="918" alt="screen shot 2016-08-10 at 1 35 21 pm" src="https://cloud.githubusercontent.com/assets/410872/17563883/61dbc944-5eff-11e6-9239-af90b0be82df.png">

This is my travis yaml

```yaml
sudo: true
dist: trusty
language: python
python:
    - "2.7"

addons:
    apt:
        packages:
            - build-essential
            - python-dev

services:
    - redis-server

env:
    - DJANGO=1.7.4 DB=postgres

install:
    - pip install -r requirements.txt

before_script:
    - sudo /etc/init.d/postgresql stop
    - sudo apt-get -y remove --purge postgresql-9.1
    - sudo apt-get -y remove --purge postgresql-9.2
    - sudo apt-get -y remove --purge postgresql-9.3
    - sudo apt-get -y remove --purge postgresql-9.4
    - sudo apt-get -y autoremove
    - travis_retry sudo apt-key adv --keyserver keys.gnupg.net --recv-keys 7FCC7D46ACCC4CF8
    - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
    - sudo apt-get update
    - sudo apt-get -y install postgresql-9.5
    - sudo sh -c 'echo "local all postgres trust" > /etc/postgresql/9.5/main/pg_hba.conf'
    - sudo sh -c 'echo "local all all trust" >> /etc/postgresql/9.5/main/pg_hba.conf'
    - sudo sh -c 'echo -n "host all all 127.0.0.1/32 trust" >> /etc/postgresql/9.5/main/pg_hba.conf'
    - sudo /etc/init.d/postgresql restart
```
