### ISSUE TITLE
Can't use docker command line on PHP builds

### ISSUE THREAD

**Issue by jaschweder** [travis-ci/travis-ci#6456]
Hi there, I donnuo if is my Yaml file, but for some reason I can't enable the docker service, the log only say that the ```docker``` was not found. See my ```.travis.yml``` file bellow:

```yaml
sudo: required

language: php

services:
  - docker

git:
  depth: 1

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: hhvm
    - php: nightly
  allow_failures:
    - php: nightly
  fast_finish: true

before_install:
  - docker pull mongo
  - docker run -d --name database -p 27017:27017 mongo
  - docker ps -a
  - pecl install mongo
  - echo "extension=mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - if [ "$TRAVIS_PHP_VERSION" != "5.6" ]; then  travis_retry bash -x ./run-tests.sh; fi
  - if [ "$TRAVIS_PHP_VERSION" = "5.6" ]; then  COVERAGE="--coverage-clover=coverage.xml" travis_retry bash -x ./run-tests.sh; fi

after_success:
  - if [ "$TRAVIS_PHP_VERSION" = "5.6" ]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml -B $TRAVIS_BRANCH; fi

```

Can anyone give a tip ?

[se also raw log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/151279178/log.txt)
