### ISSUE TITLE
AWS Codedeploy failing with (Aws::CodeDeploy::Errors::ApplicationDoesNotExistException)

### ISSUE THREAD

**Issue by jplebre** [travis-ci/travis-ci#6485]
Trying to deploy with CodeDeploy from an S3 Bucket.
The s3 portion works fine, and the deployment works fine manually from the AWS Console.

.travis.yml:
```yml
language: csharp

sudo: required
dist: trusty

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8

mono:
  - latest

install:
# Install .net using linux CLI commands
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list' 
  - sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get install -qq dotnet-dev-1.0.0-preview2-003121

script:
  - dotnet restore
  - dotnet build src/Speakr.WebApp.Site
  - dotnet build tests/Speakr.WebApp.Site.Tests
  - dotnet test tests/Speakr.WebApp.Site.Tests -f netcoreapp1.0

before_deploy:
  - zip -r $(date +'WebApp-%F').zip *
  - mkdir -p CodeDeploy_Artifacts
  - mv $(date +'WebApp-%F').zip CodeDeploy_Artifacts/$(date +'WebApp-%F').zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: eu-west-1
    bucket: speakr-travisbuilds
    local_dir: CodeDeploy_Artifacts
    skip_cleanup: true
    upload-dir: WebApp
    on:
        branch: production
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: "speakr-travisbuilds"
    key: WebApp/$(date +'WebApp-%F').zip
    application: speakr-webapp-codedeploy
    deployment_group: speakr-webapp-codedeploy-Fleet
    on:
        branch: production
```

AWS CodeDeploy Application:
![image](https://cloud.githubusercontent.com/assets/5503088/17660133/390013b2-62cf-11e6-9bab-2aec52ea7177.png)

AWS IAM Role for the key provided to travis:
![image](https://cloud.githubusercontent.com/assets/5503088/17660163/655f3230-62cf-11e6-97f8-2e9c8887909c.png)

AWS S3 Bucket policy:
![image](https://cloud.githubusercontent.com/assets/5503088/17665420/cdd635e8-62f2-11e6-8d83-08e6624a38b1.png)

Log:
```
/home/travis/.rvm/gems/ruby-2.2.5/gems/aws-sdk-core-2.5.3/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': Applications not found for 627324970999 (Aws::CodeDeploy::Errors::ApplicationDoesNotExistException)
	from /home/travis/.rvm/gems/ruby-2.2.5/gems/aws-sdk-core-2.5.3/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.5/gems/aws-sdk-core-2.5.3/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.5/gems/aws-sdk-core-2.5.3/lib/seahorse/client/request.rb:70:in `send_request'
	from /home/travis/.rvm/gems/ruby-2.2.5/gems/aws-sdk-core-2.5.3/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
	from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.18/lib/dpl/provider/code_deploy.rb:64:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.18/lib/dpl/provider.rb:144:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.18/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.18/lib/dpl/provider.rb:144:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.18/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.18/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.18/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.5/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.5/bin/dpl:23:in `<main>'
failed to deploy
```

Any help would be greatly appreciated I've been banging my head on this for a few days now.
(note: using aws console to manually trigger a deployment from S3 works fine!)

Link to log: https://travis-ci.org/speakr-rocks/Speakr.WebApp
