### ISSUE TITLE
PHP pecl compiles for the wrong version

### ISSUE THREAD

**Issue by jrbasso** [travis-ci/travis-ci#6490]
We have a script that runs `pecl install` on php 5.5 environment and it compiles and installs the pecl extension for a php 5.6. See a print from the job:

![image](https://cloud.githubusercontent.com/assets/26548/17708759/68086d5e-63b4-11e6-8e41-df5a4753b06d.png)

![image](https://cloud.githubusercontent.com/assets/26548/17708794/831ace8e-63b4-11e6-9176-b71c715c95e3.png)

This causes PHP to fail to load the extension for obvious reasons:
`PHP Warning:  PHP Startup: Unable to load dynamic library '/home/travis/.phpenv/versions/5.5.37/lib/php/extensions/no-debug-zts-20121212/apcu.so' - /home/travis/.phpenv/versions/5.5.37/lib/php/extensions/no-debug-zts-20121212/apcu.so: cannot open shared object file: No such file or directory in Unknown on line 0`

It is happening in a private repo, so I can't share the link.

Part of our `.travis.yml`:
```yaml
dist: trusty
language: php

sudo: required

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

php:
  - 5.5

services:
  - memcached

env:
  matrix:
    - BUILD_TASK=php    CACHE_A=~/.composer

notifications:
  email: false

cache:
  directories:
    - $CACHE_A

install:
  - sh contrib/travis-environment.sh
  - sh contrib/travis-dependencies.sh

before_script:
  - sh contrib/travis-db.sh
  - chmod -R 777 ./app/tmp

script:
  - sh contrib/travis-lint.sh
  - if [ $BUILD_TASK = php ];    then ./app/Vendor/bin/cake test --configuration phpunit.xml -app app app AllTests --stderr; fi;
```

**Comment by BanzaiMan** [comment]
Thanks for opening the issue. Looks like the new images shipped with incorrect `pecl` defaults. We are working to restore working runtimes as fast as we can.

Thank you for your patience.

**Comment by BanzaiMan** [comment]
In the meantime, I've uploaded PHP 5.6.23 and 5.5.38 with what I believe is correct configuration. Could you test those? You'd have to specify with TEENY version:

```yaml
language: php
php:
  - 5.5.38 # for example
```
