### ISSUE TITLE
OS X Builds Halt Abruptly (Scala, SBT)

### ISSUE THREAD

**Issue by michaelahlers** [travis-ci/travis-ci#6496]
Given a minimal configuration:

```yml
language: scala

sudo: required

matrix:
  include:
    # Other operating systems removed.
    - os: osx
      osx_image: xcode8

script:
- sbt test

# Truncated.
```

The build starts but ends abruptly and seemingly at random (it gets further along in the build at some times than others). [In one case](https://s3.amazonaws.com/archive.travis-ci.org/jobs/152969565/log.txt), in the middle of cloning the repository.

This occurs for any `osx_image` setting.
