### ISSUE TITLE
Allow specifying filenames when deploying to Github

### ISSUE THREAD

**Issue by jawher** [travis-ci/travis-ci#6509]
I was just setting up a release pipeline using travis, and it works marvellously, except for the following problem:

I'm building a CLI tool for multiple platforms (linux, darwin, etc.), and have the following config:

``` yaml
deploy:
  provider: releases
  file:
  - bin/linux/jg
  - bin/darwin/jg
```

i.e. multiple files with the same name but in different directories.

When this gets deployed to Github, I end up with a single `jg` file:

<img width="245" alt="screen shot 2016-08-21 at 19 16 24" src="https://cloud.githubusercontent.com/assets/96384/17838738/e294fa88-67d3-11e6-9182-14f0187f9b43.png">

Looking here in [travis-ci/dpl](https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/releases.rb), I can see the basename for the file is used as the filename parameter for Github.

Would it be possible to let the filename be user-settable ? Maybe something like this for example:

``` yaml

deploy:
  provider: releases
  file:
  - bin/linux/jg: "jg (Linux)"
  - bin/darwin/jg: "jg (Darwin)"
```

Or maybe with this syntax (which allows setting more parameters, the label for example):

``` yaml
deploy:
  provider: releases
  file:
  - path: bin/linux/jg: 
    name: "jg (Linux)"
    label: "jg executable for Linux (amd64)"
  - path: bin/darwin/jg: 
    name: "jg (Darwin)"
```

Thanks in advance !

**Comment by jolestar** [comment]
Same request feature for release.
Now, I have to name my release file with different name, such as xxx-linux-amd64, xxx-darwin-amd64. That is not friendly for end user to use it.

**Comment by jawher** [comment]
I tried to path `dpl` to support this feature.
You can see the progress here: https://github.com/travis-ci/dpl/compare/master...jawher:named-releases-files

However, when this is called from travis using the following syntax:

```yaml
deploy:
  provider: releases
  edge:
    source: jawher/dpl
    branch: named-releases-files
  api_key:
    secure: "..."
  file:
  - path: bin/linux/test
    name: test (Linux)
  - path: bin/darwin/test
    name: test (Mac OS)
  skip_cleanup: true
  on:
    all_branches: true
```

the `file` list passed to dpl is empty.
I can't, for the life of me, find where travis parses the file list.
Any pointers would be appreciated !
