### ISSUE TITLE
Slack Notifications not working with Encrypted Credentials

### ISSUE THREAD

**Issue by jesuscreyes** [travis-ci/travis-ci#6528]
I successfully get Slack notifications from Travis CI when I have the following configuration in my .travis.yml file.
```
notifications:
  slack: <MY_DOMAIN>:<MY_TOKEN>
```

However, when I do the following,
```
$ travis encrypt "<MY_DOMAIN>:<MY_TOKEN>" --add notifications.slack
```
I don't receive the notification. I've also tried adding the encrypted credential manually (not using the `--add` feature) and it still doesn't work.

**Comment by BanzaiMan** [comment]
Duplicate of #5106.

**Comment by jesuscreyes** [comment]
Not exactly the same issue, though that feature would be very awesome and helpful.

My issue is that if I try to use an encrypted token, like so:
```
notifications:
  slack:
    secure: <MY_TOKEN_ENCRYPTED>
```
It doesn't work. So for some reason, the Travis machine isn't decrypting my token correctly.

Appreciate the quick follow-up.

**Comment by BanzaiMan** [comment]
Actually, you might be right.

This is a bit difficult to track it from here, though, since we need a lot more information than this.

If running

    travis encrypt "<MY_DOMAIN>:<MY_TOKEN>" --add notifications.slack -r OWNER/REPO

doesn't work (also add `--pro` if it's a private repo), please email support@travis-ci.com with more details (which repository you are using it, the build log URL that shows the problem you're having, and whatever other information you might find relevant).

Thanks.

**Comment by jesuscreyes** [comment]
Your suggestion worked! I'm guessing that the encryption needs the `repo SLUG` to be explicit for it to work.

Thanks again for the help.

**Comment by damianobarbati** [comment]
So what's the final solution to have slack notifications working?

I tried the following encrypting ways, no success so far:
```
travis encrypt -r quant-01/quant01 --pro "quant01:<token>"
travis encrypt -r quant-01/quant01 --pro "quant01:<token>#builds"
travis encrypt -r quant-01/quant01 "quant01:<token>"
travis encrypt -r quant-01/quant01 "quant01:<token>#builds"
```
.travis.yml 
```
notifications:
    email:
        recipients: damiano.barbati@gmail.com
        on_success: always
        on_failure: always
    slack:
        secure: "<secret>" 
        on_success: always
        on_failure: always

```

**Comment by pzelnip** [comment]
I'm having the exact same problem, without encryption integration works fine, but with encryption I can't get it to work.  Have tried with and without -r, tried with and without --add, and no go.

**Comment by AlexShemeshWix** [comment]
I have same problem. Im on private repo. 
More importantly , how do i see what exactly the problem? Where is the log that says "Pushing notification"

**Comment by BanzaiMan** [comment]
For private repos, add the `--pro` flag, as I suggested.

Unfortunately you don't see your error anywhere.

**Comment by emma-sax4** [comment]
It seems this still is a thing. I've tried encrypting my value like this:
```
travis encrypt -r "user_name/repo_name" "slack:token"
travis encrypt -r user_name/repo_name "slack:token"
travis encrypt "slack:token"
```

But Slack notifications don't work. If I put the plain `slack:token` in, then Travis complains that it should be encrypted, but I will receive the notification.

Here's that section of my `.travis.yml`:
```yml
notifications:
  email: false
  slack:
    rooms:
      - secure: "encrypted_value_goes_here"
    on_success: always
    on_failure: always
    on_pull_requests: true
    template:
      - "Build (<%{build_url}|#%{build_number}>) for *%{repository_slug}* `%{result}`."
      - "Commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*."
      - "Message: %{message}"
```
 
Thanks in advance for your help.

And if I'm not missing something... I can't believe Travis hasn't fixed this issue yet.
