### ISSUE TITLE
Not able to pass environment variables specific to a script provider

### ISSUE THREAD

**Issue by rafael-nogueras** [travis-ci/travis-ci#6532]
After my build completes I want to deploy the build output using several script providers; each one needs to be configured slightly differently in order to deploy the code to a different location (specifically, a Cloud Foundry application). I thought it would be as simple as passing an `env` block within each `script` provider block to customize each script, but it does not seem to work.

Let me show you a concrete example of what I am trying:

```
deploy:
    - provider: script
      skip_cleanup: true
      script: cf-blue-green-travis
      env:
        CF_APP: [NAME OF FIRST APP]
      on:
        branch:
        - development
    - provider: script
      skip_cleanup: true
      script: cf-blue-green-travis
      env:
        CF_APP: [NAME OF SECOND APP]
      on:
        branch:
        - development
env:
  global:
    - CF_API=[MY API ENDPOINT]
    - CF_ORGANIZATION=[MY ORGANIZATION]
```

   So, as you can see, I am attempting to use a `script` provider called `cf-blue-green-travis`, whose script requires the `CF_APP` environment variable to be set to deploy the build to the correct location. While some of the Cloud Foundry environment variables the script needs can be specified in an `env.global` section, the `CF_APP` environment variable must be different for each `script` provider block so the build can be deployed to different Cloud Foundry apps. (Yes, I am aware there is a Cloud Foundry provider in Travis, but it does not support zero-downtime deployment, so I am forced to use this particular script provider).

   In any case, when I try the above script, the deploy step fails because `CF_APP` is not defined. I also tried the following format and it didn't work, either:

```
deploy:
    - provider: script
      skip_cleanup: true
      script: cf-blue-green-travis
      env:
        CF_APP=[NAME OF FIRST APP]
      on:
        branch:
        - development
    - provider: script
      skip_cleanup: true
      script: cf-blue-green-travis
      env:
        CF_APP=[NAME OF SECOND APP]
      on:
        branch:
        - development
```

   Am I not using the correct syntax to define per-script provider environment variables, or is that a feature you do not provide? Is there a workaround you could suggest, if the latter case is true?

Thanks!

**Comment by BanzaiMan** [comment]
As you guessed, deployment providers do not consider `env` key.

If you want to pass extra environment variables to your script, try using `env` command instead.

```yaml
deploy:
    - provider: script
      skip_cleanup: true
      script: env CF_API=XXXXXX cf-blue-green-travis
      on:
        branch:
        - development
```
