### ISSUE TITLE
MySql server and Docker doesn't work together

### ISSUE THREAD

**Issue by inspired-geek** [travis-ci/travis-ci#6535]
Hello!
I'm trying to make sure my Dockerfile is building to image and to run it with several db engines to test.
But I have no luck with MySql (MariaDB).

If choose

```
services: 
  - docker
  - mysql

env:
  - DB=mysql
  - DB=sqlite
```

I am getting
```
$ sudo service docker start
start: Job is already running: docker
$ sudo service mysql start
mysql: unrecognized service
```
Here is the [full log and config](https://travis-ci.org/inspired-geek/redmine-alpine/jobs/154496949)

And If choose

```
services: 
  - docker
  - mariadb

matrix:
  include:
    - env: DB=mariadb
      addons:
        mariadb: 10.1
    - env: DB=sqlite
```

I am getting

```
$ sudo service docker start
docker: unrecognized service

Installing MariaDB version 10.1
mysql stop/waiting
...
sudo service mysql start
mysql start/running, process 5654
```

Here is the [full log and config](https://travis-ci.org/inspired-geek/redmine-alpine/jobs/155941879)

Is it bug or am I missing something from the docs?

**Comment by gabetax** [comment]
Including docker as a service appears to opt you into the [trusty environment](https://docs.travis-ci.com/user/trusty-ci-environment/), which currently does not include mysql (check the build logs to verify). You can work around this by [explicitly installing MySQL via apt](https://docs.travis-ci.com/user/database-setup/#MySQL-5.6):

```yaml
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
```
