### ISSUE TITLE
Errors were encountered while processing:  /var/cache/apt/archives/locales_2.23-5_all.deb

### ISSUE THREAD

**Issue by petrroll** [travis-ci/travis-ci#6539]
Title says it, I am trying to use debian-sid source because I need libunwind8. This is my packages list:

```
addons:  
  apt:
    sources:
    - debian-sid
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
```

Complete log is here: https://travis-ci.org/petrroll/MES/builds/156255914
