### ISSUE TITLE
unexpected key in matrix.include for multi-OS

### ISSUE THREAD

**Issue by nebgnahz** [travis-ci/travis-ci#6540]
Following the example provided by Travis documentation [Example Multi OS Build Matrix](https://docs.travis-ci.com/user/multi-os/#Example-Multi-OS-Build-Matrix), I have the following specification:

```
language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.2
```

testing with Travis CLI 1.8.2 and [Weblint](https://lint.travis-ci.org/) both give

```
in matrix.include section: unexpected key osx_image, dropping
in matrix.include section: unexpected key dist, dropping
in matrix.include section: unexpected key sudo, dropping
```
