### ISSUE TITLE
Feature Request: Limit concurrent builds by branch / tag / PR

### ISSUE THREAD

**Issue by colin-air** [travis-ci/travis-ci#6547]
It would be great to be able to limit concurrent builds by branches, tags, and pull requests

For example:

.travis.yml:
```yaml

concurrent_builds:
  pull_request: 0 # unlimited
  branch: 0  # unlimited
  tags: 1
```

Name specific branches

```yaml

concurrent_builds:
  pull_request: 0 # unlimited
  branch:
    - master: 1  # Limit to 1 for the master branch only
    - "*": 4  # All other branches limited to 4
  tags: 1
```

A specific use case would be Continuous deployment for commits to master, or deployment on tag/release
