### ISSUE TITLE
[question] Composed cache?

### ISSUE THREAD

**Issue by mariogintili** [travis-ci/travis-ci#6557]
Hello guys I was reading your pguides around caching](https://docs.travis-ci.com/user/caching/#Caching-directories-(Bundler%2C-dependencies)) and I was wondering if it's possible for a user to

- Choose a cache strategy, i,e: bundler
- AND caching some directories

So a config would look something along the lines of

```yaml
cache:
  - bundler
  - directories:
    - web-client/node_modules
    - web-client/bower_components
```

Is this possible?

**Comment by BanzaiMan** [comment]
Yes. https://docs.travis-ci.com/user/caching/#Enabling-multiple-caching-features

```yaml
cache:
  bundler: true
  directories:
    - web-client/node_modules
    - web-client/bower_components
```
