### ISSUE TITLE
Neo4j service seems broken

### ISSUE THREAD

**Issue by keyvan-m-sadeghi** [travis-ci/travis-ci#6567]
After an hour and half of waiting:
```
Starting Neo4j Server...process [2474]... waiting for server to be
ready.........................................................
..............................................................
............................ (1 page of dots)
```
below is my .travis.yml
```yml
services:
  - neo4j
language: node_js
node_js:
  - "6"
  - "4"
```
