### ISSUE TITLE
Deploying fails on second provider when multiple are specified

### ISSUE THREAD

**Issue by EnKrypt** [travis-ci/travis-ci#6568]
My configuration involves deploying to npm as well as github releases. When only one is specified in the configuration, they both work fine individually. However, when I specify both, the first one (github releases) deploys fine, but deploying to npm fails (without any error message) and the build is indicated to have failed.

Build log : [https://travis-ci.org/EnKrypt/Botato/builds/157879659](https://travis-ci.org/EnKrypt/Botato/builds/157879659)

And here is my .travis.yml file : 
```
language: node_js
node_js:
 - "6"
before_deploy:
 - rm -rf .git/
 - rm -rf jasmine/
 - rm -rf node_modules/
 - rm .travis.yml
 - zip -r botato-${TRAVIS_TAG:1}.zip .
deploy:
  - provider: releases
    api_key: "${GITHUB_KEY}"
    file_glob: true
    file: "botato-*.zip"
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    email: "arvind@enkrypt.in"
    api_key: "${NPM_KEY}"
    skip_cleanup: true
    on:
      tags: true

```
