### ISSUE TITLE
Config option r_check_revdep causing error during build script compilation

### ISSUE THREAD

**Issue by gavinsimpson** [travis-ci/travis-ci#6573]
Whenever I set `r_check_revdep: true` my builds fail almost immediately with:

```
An error occurred while compiling the build script: undefined method `/' for "library(\"devtools\");":String
```

An example build can be seen [here](https://travis-ci.org/gavinsimpson/permute/builds/158270130)

My full `.travis.yml` file is:

``` yaml
language: r
cache: packages

r:
  - release
  - devel

sudo: false

addons:
  apt:
    packages:
      - qpdf

r_binary_packages:
  - testthat
  - vegan
  - Rcpp
  - crayon
  - lazyeval
  - jsonlite
  - htmltools

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

r_build_args: " --compact-vignettes=gs+qpdf"

notifications:
  email:
    on_success: change
    on_failure: always

r_check_revdep: true
```

CCing @hadley @jimhester @craigcitro as per [Travis CI R documentation](https://docs.travis-ci.com/user/languages/r/)
