### ISSUE TITLE
The Nix language page doesn't mention caching

### ISSUE THREAD

**Issue by expipiplus1** [travis-ci/travis-ci#6604]
CC @domenkozar @garbas @matthewbauer 

Given how great caching is in Nix it would be nice to mention this here: https://docs.travis-ci.com/user/languages/nix

This could either be some text mentioning that caching `/nix/store/` isn't possible, or that it's done and speeds up builds when the inputs don't change.

**Comment by garbas** [comment]
i currently use ``nix-push`` to create binary cache and push that to my server using ``rsync`` (example: https://github.com/garbas/nixpkgs-python/blob/master/.travis.yml#L25) 

maybe we could setup this by default with travis and use travis's cache.

**Comment by expipiplus1** [comment]
Using Travis's cache would certainly save you bandwidth, and may be a lot faster as the files would be local.

**Comment by domenkozar** [comment]
@expipiplus1 as far as I know they're loaded from S3, which is the same as loading from Nix cache.

It would be useful in terms of doing only one request and the fact that it would preserve built store paths.

**Comment by expipiplus1** [comment]
@domenkozar that's true for things built by the public hydra instance, but there could be things built only locally which would be good to cache.

**Comment by deepfire** [comment]
As of current, specifying
```
cache:
  directories:
    - /nix
```
result in a 400M cache for https://github.com/deepfire/reflex-glfw, and the following failure to use the cache:
```
attempting to download cache archive

fetching master/cache-linux-trusty-4d60acb93719bff708debb4cbfb796078bf8b48d378cf6b3d98973d224945e3e.tgz

found cache
adding /nix to cache

running `casher add/nix` took longer than 180 seconds and has been aborted
```

**Comment by fosskers** [comment]
>  as far as I know they're loaded from S3, which is the same as loading from Nix cache.

@domenkozar If their actual infrastructure runs on AWS, then pulling from S3 is essentially the same as the files being local, it's pretty damn fast.

**Comment by stephengroat** [comment]
@deepfire you can override the `travis` cache timeout with the following `yaml` in `.travis.yml`:

```yaml
cache:
  timeout: 10000
```

**Comment by fosskers** [comment]
I did some experimenting. Unless my caching settings are wrong, then it isn't worth it to cache (i.e. Nix itself is fast enough). Here's the original `.travis.yml`. **The build takes ~18 minutes.**

```yaml
language: nix

before_install: nix-env --install --attr nixpkgs.haskellPackages.hpack

script:
  - hpack
  - nix-build --attr vectortiles release.nix
```
Some digging led me to discover that avoiding "running in containers", we can speed things up. Adding the following **reduces build time to ~3 minutes**:
```yaml
sudo: true
```
This is installing `hpack` and downloading all packages from `nixpkgs`, building, and testing the library in 3 minutes. Not bad! To see if caching improves that further, I added:
```yaml
cache:
  directories:
    - /nix/store
```
The first run with this took **~5 minutes** - I guess 2 extra minutes to write the cache? The next run, which both pulled this new cache and wrote a new one, took **~6.5 minutes**. And it seemed to be pulling all the nix packages fresh anyway, like the cache wasn't being respected at all.

What's next to try?

**Comment by matthewbauer** [comment]
It's all going to depend on what you're actually building. The cache has really helped me, but that's only because I'm building a bunch of packages not in the binary cache (like Emacs packages).

**Comment by expipiplus1** [comment]
Perhaps @fosskers's findings could be added to the travis documentation page

**Comment by pierrebeaucamp** [comment]
This took me way too long to figure out & debug, but I might as well share my final findings here, so others can profit. Thank you @fosskers for the groundwork.

The simplest configuration took **~9 minutes**:
```yml
language: nix
```

Disabling Docker saw a significant speed improvement - this time, the build took **~3 minutes**
```yml
language: nix
sudo: required
```

Next, I tried saving `/nix/store` as a cache. This didn't work at all and increased to build to **4:30 minutes**. It took ~30 seconds to load the cache, then it wasn't actually being used and afterwards travis uploaded a new cache (~60 seconds)
```yml
language: nix
sudo: required
cache:
  directories:
    - /nix/store
```

I figured that the reason why caching `/nix/store` alone didn't work is that `/nix/var/nix/` stores references to the store? I don't really know the internals of nix and this was just an assumption, but caching the entirety of `/nix` seemed to improve things again to **~3 minutes**:
```yml
language: nix
sudo: required
cache:
  directories:
    - /nix
```

This successfully prevented nix from re-downloading dependencies, but travis still uploads a new cache after each build. This makes sense, as building a derivation using `nix-build` will add it to `/nix/store`. To circumvent this, I ended up with the following, somewhat hacky solution and reduced the build time to **2:30 minutes**
```yml
language: nix
sudo: required

install: |
  if [ "$(ls -A $HOME/nix-cache)" ]; then
    sudo rm -rf /nix/*
    cp -a $HOME/nix-cache/* /nix
  fi

before_cache: |
  if [ ! "$(ls -A $HOME/nix-cache)" ]; then
    cp -a /nix/* $HOME/nix-cache
  fi

cache:
  directories:
    - $HOME/nix-cache
```

Essentially, I cache an entirely different directory and copy it to `/nix` if it's not empty during installation, but only populate it if it was empty. This means I have to manually delete a cache from travis before it will build a new one.

---

At this point, the build performance is somewhat on par with other CI systems (I'm mostly using CircleCI and wanted to experiment with travis since they have `nix` somewhat built in). However the fact that the build doesn't run inside a docker container, but a real VM means the boot & setup phases can take a huge toll - I've run each step to get somewhat of an average number for each configuration, but the setup phase fluctuates highly between 20 to 120 seconds. (As compared to a consistent <10 second setup on CicleCI). 

Anyway, I hope that this helps someone or makes it into the documentation. It's too bad the issue was already closed, but I guess that's what you get from using a stale-bot ¯\_(ツ)_/¯
