### ISSUE TITLE
Android emulator: "Target id is not valid"

### ISSUE THREAD

**Issue by tir38** [travis-ci/travis-ci#6606]
I'm trying to start an SDK 22 emulator. I know that this component doesn't come pre installed. So I make sure to include it in my `components` list. However I still get an error:

```
Error: Target id is not valid. Use 'android list targets' to get the target ids.
```

This is my relevant .travis.yml:

```
language: android
jdk: oraclejdk8
sudo: false
android:
  components:
    - tools
    - build-tools-24.0.2
    - android-24
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - sys-img-armeabi-v7a-android-22 # <---- This should add the system image
install: 
  - bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - ./vendor/bundle
before_script:
  - android list targets # list pre-installed targets # <---- list all installed targets
  - android list sdk --no-ui --all --extended | grep -E '^id:' | awk -F '"' '{$1=""; print $2}' # <---- list all available components
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a # <---- this is failing, "Target id is not valid"
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script:
  - bundle exec ruby ./build-script/build-android.rb
```

What am I missing?

**Comment by ardock** [comment]
`- android-22`

Check [this](http://stackoverflow.com/questions/38865798/cant-build-project-with-travis-ci-and-android)

**Comment by tir38** [comment]
ahh thanks

**Comment by AsifDev21** [comment]
Same issue in my place , please help , I tried  - android-22 , still not working
****************yem file starts*****************
language: android
jdk: oraclejdk8
sudo: false

android:
  components:

    - extra-android-support
    - extra-google-google_play_services
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-24
    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t - android-22 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script: ./gradlew ExampleInstrumentedTest
****************yem file ends*****************



I want to do espresso test and also unit test , please help

**Comment by milosmns** [comment]
@AsifDev21 You don't have 22, you have 24:
```yml
android:
  components:
    - android-24
```
You should add both 24 and 22 in there.
