### ISSUE TITLE
Travis build failes with unexpected errors for PHP language with nodejs

### ISSUE THREAD

**Issue by vcernomschi** [travis-ci/travis-ci#6623]
Summary: 
For PHP project, I need to use nodejs script to save different backend/frontend coverage reports in AWS S3 (I implemented some `cache functionality` between concurrency jobs - it was not implemented in Travis).

Steps to reproduce:
1. Use .travis.yml with PHP and install nodejs in `before_install`.
```
language: php
sudo: required
cache:
  edge: true
  directories:
    - $HOME/.composer/cache
    - $(npm root -g)
    - node_modules
    - deep_modules
    - $(npm config get prefix)/bin
branches:
  only:
    - master
    - dev
    - stage
    - test
dist: trusty
group: edge
php:
  - 5.5
  - 5.6
  - 7
before_install:
  - sudo rm -rf ~/.nvm
  - 'curl -sL "https://deb.nodesource.com/setup_${NODE_RELEASE}" | sudo -E bash -'
  - sudo apt-get install -y nodejs
  - cp bin/test/package.json .
install:
  - composer install-deps
script:
  - composer test
after_success:
  - npm run coverage
after_script:
  - npm run remove-coverage
env:
  global:
    - NODE_RELEASE=4.x
    - 'MAJOR_VERSIONS=master,stage'
    - DEEP_NO_INTERACTION=1
    - E2E_TESTING=none
```
2. Install locally some dependencies in `install` phase:
`npm install istanbul-combine@0.3.x`
3. Check istanbul-combine.
Expected result:  istanbul-combine was installed successfully and can be used in `script` phase.
Actual result:  istanbul-combine was installed, build failed with error:

```
npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! path /home/travis/build/AdTechMedia/drupal-module/node_modules/.bin/istanbul-combine
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall unlink
npm ERR! Error: EACCES: permission denied, unlink '/home/travis/build/AdTechMedia/drupal-module/node_modules/.bin/istanbul-combine'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, unlink '/home/travis/build/AdTechMedia/drupal-module/node_modules/.bin/istanbul-combine']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'unlink',
npm ERR!   path: '/home/travis/build/AdTechMedia/drupal-module/node_modules/.bin/istanbul-combine' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/AdTechMedia/drupal-module/npm-debug.log
```

It looks like travis tried to unlink `istanbul-combine` after install script.

The full log is located: https://travis-ci.org/AdTechMedia/drupal-module/jobs/161316964
