### ISSUE TITLE
Travis CI for Mac fails with "Your Xcode (6.1) is outdated"

### ISSUE THREAD

**Issue by jay** [travis-ci/travis-ci#6627]
[curl/curl](https://github.com/curl/curl) mac ci recently [failed](https://travis-ci.org/curl/curl/jobs/162021559) with "Your Xcode (6.1) is outdated". Our [travis.yml](https://github.com/curl/curl/blob/master/.travis.yml) uses 'osx'. I read in your [doc](https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version) that other versions can be used, but I'm not sure if this is a bug that the standard 'osx' doesn't appear to be working since our most recent ci run.

```
Warning: You are using macOS 10.9.
We (and Apple) do not provide support for this old version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
Error: Your Xcode (6.1) is outdated
Please update to Xcode 6.2.
Xcode can be updated from the App Store.
```

/cc @bagder @snikulov

**Comment by jay** [comment]
This might be brew related?
`The command "if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install openssl libidn rtmpdump libssh2 c-ares libmetalink libressl nghttp2; fi" failed and exited with 1 during .`

If we are in the wrong my apologies I don't work with OS X I'm not sure what is supposed to happen here.

/cc @DomT4

**Comment by DomT4** [comment]
Should be fixed now? I reverted the problematic commit a few hours ago. There's a replacement pending with a special exemption for Travis, but not merged yet.

**Comment by SlySven** [comment]
Might be related, but I took the opportunity to try to force my Projects dual-OS built to use the next XCode version up with a `osx_image: beta-xcode6.2` but I can't see how to insert it into the build matrix, I thought this would work:

```
language: cpp
os:
  - osx
  - linux
compiler:
  - gcc
  - clang
env:
  - Q_OR_C_MAKE=qmake
  - Q_OR_C_MAKE=cmake
matrix:
# The previous default of osx_image: beta-xcode6.1 no longer works, certainly as of 2016-09-22! - SlySven
  include:
    - os: osx
      osx_image: beta-xcode6.2
# Something goes wrong internally in Qt (5.0.2) for CMake Clang builds on Linux
  allow_failures:
    - os: linux
      compiler: clang
      env: Q_OR_C_MAKE=cmake
```
However as well as the expected matrix of 2(`os`s) x 2(`compiler`) x 2(`env`) but with the osx ones WITHOUT the osx_image value I got an extra one WITH the latter but the Job Config for that reads:
```
{
  "language": "cpp",
  "os": "osx",
  "compiler": [
    "gcc",
    "clang"
  ],
  "env": "Q_OR_C_MAKE=qmake Q_OR_C_MAKE=cmake",
```
_some install and other irrelevant entries omitted!_
```
  "group": "stable",
  "dist": "precise",
  "osx_image": "beta-xcode6.2"
}
```

 A previous test reveals that a `os: linux` configuration gets _confused_ by a presence of an `osx_image` setting so how do we set the osx_image parameter for __just__ the `os: osx` case?  I will try again later to verify that `os:linux` vs. `osx_image` clash because I may have had an error in the `.travis.yml` file then, but the documentation on dual platforms is not as clear as it could be IMHO.
