### ISSUE TITLE
Build matrix exclude doesn't work

### ISSUE THREAD

**Issue by emn178** [travis-ci/travis-ci#6650]
Hi,

I have setting like this:
```yaml
sudo: required

addons:
  apt:
    packages: haveged

services:
  - docker

language: ruby

rvm:
  - "2.1"
  - "2.3"

gemfile:
  - "gemfiles/rails_4.0.gemfile"
  - "gemfiles/rails_4.1.gemfile"
  - "gemfiles/rails_4.2.gemfile"
  - "gemfiles/rails_5.0.gemfile"

env:
  - CASSANDRA_VERSION: 2.1
  - CASSANDRA_VERSION: 2.2

script: script/ci-unit-test

bundler_args: '--without=debug'

matrix:
  exclude:
  - rvm: 2.1
    gemfile: gemfiles/rails_5.0.gemfile
```

But it still run 2.1 + rails 5.0: [builds](https://travis-ci.org/cequel/cequel/builds/162680845)

How to set up correctly?
