### ISSUE TITLE
Allow failure by env key

### ISSUE THREAD

**Issue by theofidry** [travis-ci/travis-ci#6661]
Basically if we have a configuration along the lines of:

```yaml
language: php

php:
  - '7.0'
  - nightly

matrix:
  include:
    # Eloquent bridge
    - php: '7.0'
      env:
        - COVERAGE='true'
        - ELOQUENT_VERSION='~5.0.0'
        - COMPOSER_FLAGS='--prefer-lowest'
    - php: '7.0'
      env:
        - ELOQUENT_VERSION='~5.1.0'
    - php: '7.0'
      env:
        - ELOQUENT_VERSION='~5.2.0'
    - php: '7.0'
      env:
        - ELOQUENT_VERSION='~5.3.0@dev'

    - php: '7.0'
      env:
        - COVERAGE='true'
        - SYMFONY_VERSION='~3.0.0'
        - COMPOSER_FLAGS='--prefer-lowest'
    - php: '7.0'
      env: SYMFONY_VERSION='~3.1.0'
    - php: '7.0'
      env: SYMFONY_VERSION='~3.2.0@dev'

  allow_failures:
    - php: nightly
    - env: ELOQUENT_VERSION='~5.3.0@dev'
    - env: SYMFONY_VERSION='~3.2.0@dev'
```

only two builds will be allowed to fail: the one with the PHP version `nightly` and the one with  `SYMFONY_VERSION='~3.2.0@dev'`.

I tried several things, but I couldn't figure out how to make so that both `SYMFONY_VERSION='~3.2.0@dev'` and `ELOQUENT_VERSION='~5.3.0@dev'`.

There already suggestions like https://github.com/travis-ci/travis-ci/issues/6021 but I would like to know if there is any solution at the moment.

/cc @Soullivaneuh

**Comment by BanzaiMan** [comment]
When you allow jobs to fail in a build matrix, the conditions must match exactly.

Your job is defined with:

```yaml
    - php: '7.0'
      env:
        - ELOQUENT_VERSION='~5.3.0@dev'
```

but allowed to fail with:

```yaml
  allow_failures:
    - php: nightly
    - env: ELOQUENT_VERSION='~5.3.0@dev'
    - env: SYMFONY_VERSION='~3.2.0@dev'
```

The `env` value in the `allow_failures` is a string, while the job is defined with an array. They do not match, and therefore the `ELOQUENT_VERSION` job is not allowed to fail.

**Comment by BanzaiMan** [comment]
See https://travis-ci.org/BanzaiMan/travis_production_test/builds/164423236, https://travis-ci.org/BanzaiMan/travis_production_test/builds/164423236 and their respective configurations.

**Comment by theofidry** [comment]
@BanzaiMan I guess as much, but this doesn't answer my question on *how* to solve this, the following doesn't work either:

```yaml
language: php

php:
  - '7.0'
  - nightly

matrix:
  include:
    # Eloquent bridge
    - php: '7.0'
      env:
        - COVERAGE='true'
        - ELOQUENT_VERSION='~5.0.0'
        - COMPOSER_FLAGS='--prefer-lowest'
    - php: '7.0'
      env:
        - ELOQUENT_VERSION='~5.1.0'
    - php: '7.0'
      env:
        - ELOQUENT_VERSION='~5.2.0'
    - php: '7.0'
      env:
        - ELOQUENT_VERSION='~5.3.0@dev'
        - 'ALLOW_FAIURE=true'

    - php: '7.0'
      env:
        - COVERAGE='true'
        - SYMFONY_VERSION='~3.0.0'
        - COMPOSER_FLAGS='--prefer-lowest'
    - php: '7.0'
      env: SYMFONY_VERSION='~3.1.0'
    - php: '7.0'
      env:
        - 'SYMFONY_VERSION=~3.2.0@dev
        - 'ALLOW_FAIURE=true'

  allow_failures:
    - php: nightly
    - env: 'ALLOW_FAIURE=true'
```

**Comment by BanzaiMan** [comment]
In your new configuration, there is no job that has the `env` value `'ALLOW_FAILURE=true'` exactly. Your jobs are defined with arrays.

**Comment by BanzaiMan** [comment]
I think #6021 is a different issue. #6021 proposes a new environment variable depending on whether or not the job is allowed to fail, whereas you are proposing a new environment variable that dictates whether or not a job is allowed to fail regardless of all other conditions.

**Comment by theofidry** [comment]
I see it needs to be an exact match, perfect this did the trick. It's a bit redundant with the job declaration maybe it would be easier to just declare the jobs that are allowed to failed in `allow_failures`, instead of referencing a declared job in that section, i.e.:

```yaml
language: php

php:
  - '7.0'

matrix:
  allow_failures:
    - php: nightly
```

instead of:

```yaml
language: php

php:
  - '7.0'
  - nightly

matrix:
  allow_failures:
    - php: nightly
```

Which would make it far easier and less verbose when having more complex builds. Or maybe playing with keys?

```yaml
language: php

php:
  - '7.0'
  - nightly

matrix:
  include:
    - id: 10
       php: '7.1'
       env: 'FOO=BAR'
  allow_failures:
    - php: nightly
    - id: 10
```

But anyway, at least it works now, thanks for that @BanzaiMan!

**Comment by VoR0220** [comment]
I too am struggling with this concept. Currently I am trying to make an OS X testing suite, one using docker-machine and the other an allowed failure for docker-for-mac, both running on golang and at the same version. 

```
os: osx

language: go

go: 1.7.3

env:
  global:
    - TEST_ON_MACOSX=true
    - MACHINE_NAME="eris-test-osx-$TRAVIS_BUILD_ID"
matrix:
  allow_failures:
    #Native Docker job, expect potential failures as it's still fresh
    - env:
        - DOCKER_NATIVE=true
  include:
    #Docker machine job, expect this to pass
    - env:
        - DOCKER_MACHINE=true
      after_script: 
        - tests/dm_cleanup.sh
    - env:
        - DOCKER_NATIVE=true
```

I get the allowed failure, but I am also getting a second job for the DOCKER_NATIVE=true in the include section. So basically I have 3 jobs when I'm really only expecting 2. Any idea as to how to fix this so that I can get what I need?

**Comment by ganjarpanji** [comment]
currently, i also want to mark a script result as allowed failure 

`matrix:
  include:
    - language: android
      os: linux
      sudo: required
      cache:
        directories:
          - node_modules
          - $PROJ_DIR/node_modules
      before_install:
        - chmod +x travis/scripts/platformchecker.sh
      allow_failures:
        before_install: 
        - ./travis/scripts/platformchecker.sh
        - npm install -g rnpm
        - nvm install 6`

**Comment by chrisjsewell** [comment]
Why does adding the `allow_failure` section in the config below cause the travis build to throw an error? (it works fine without this section)

```yaml
matrix:
 include:
    - os: linux
      sudo: required
      python: 2.7
      dist: trusty 
      env: ALLOW_FAILURE=false
    - os: linux
      sudo: required
      python: 3.6
      dist: trusty
      env: ALLOW_FAILURE=false
    - os: osx
      language: generic
      env: ALLOW_FAILURE=true
      before_install:
        - brew update
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate
  allow_failure:
      env: ALLOW_FAILURE=true
```
