### ISSUE TITLE
Allow failure based on environment key

### ISSUE THREAD

**Issue by theofidry** [travis-ci/travis-ci#6664]
While working on https://github.com/theofidry/AliceDataFixtures I noticed that if I had the following:

```yaml
language: php
php:
  - '7.0'
  - '7.1'
  - nightly
matrix:
  fast_finish: true
  include:
    - php: '7.0'
      env:
        - COVERAGE='true'
        - COMPOSER_FLAGS='--prefer-lowest'

    # Doctrine bridge
    - php: '7.0'
      env:
        - COVERAGE='true'
        - DOCTRINE_VERSION='~2.5.0'
        - COMPOSER_FLAGS='--prefer-lowest'

    - php: '7.0'
      env:
        - DOCTRINE_VERSION='~2.5.0'

    # Eloquent bridge
    - php: '7.0'
      env:
        - COVERAGE='true'
        - ELOQUENT_VERSION='~5.0.0'
        - COMPOSER_FLAGS='--prefer-lowest'
    - php: '7.0'
      env:
        - ELOQUENT_VERSION='~5.1.0'
    - php: '7.0'
      env:
        - ELOQUENT_VERSION='~5.2.0'
    - php: '7.0'
      env:
        - ELOQUENT_VERSION='~5.3.0@dev'

    # Symfony bridge
    - php: '7.0'
      env:
        - COVERAGE='true'
        - SYMFONY_VERSION='~3.0.0'
        - COMPOSER_FLAGS='--prefer-lowest'
    - php: '7.0'
      env: SYMFONY_VERSION='~3.1.0'
    - php: '7.0'
      env: SYMFONY_VERSION='~3.2.0@dev'

    # Symfony bridge with Doctrine
    - php: '7.0'
      env:
        - COVERAGE='true'
        - DOCTRINE_VERSION='~2.5.0'
        - SYMFONY_VERSION='~3.0.0'
        - COMPOSER_FLAGS='--prefer-lowest'
    - php: '7.0'
      env:
        - DOCTRINE_VERSION='~2.5.0'
        - SYMFONY_VERSION='~3.1.0'

    # Symfony bridge with Eloquent
    - php: '7.0'
      env:
        - COVERAGE='true'
        - ELOQUENT_VERSION='~5.0.0'
        - SYMFONY_VERSION='~3.0.0'
        - COMPOSER_FLAGS='--prefer-lowest'
    - php: '7.0'
      env:
        - ELOQUENT_VERSION='~5.0.0'
        - SYMFONY_VERSION='~3.1.0'

  allow_failures:
    - php: nightly
    - php: '7.0'
      env:
        - ELOQUENT_VERSION='~5.3.0@dev'
    - php: '7.0'
      env: SYMFONY_VERSION='~3.2.0@dev'

#...
```

The build with `PHP 7.0` and no environment is caught in the "allowed failures", as you can see here: https://travis-ci.org/theofidry/AliceDataFixtures/builds/164423951

**Comment by BanzaiMan** [comment]
Your `'7.0'` jobs have multiple elements in the sequence defined in `env`. They must match *exactly* in order to be allowed to fail.

**Comment by BanzaiMan** [comment]
As you see in the build, the jobs that match *exactly* are allowed to fail.

**Comment by theofidry** [comment]
@BanzaiMan I'm not sure to follow, I have no `allowed_failures` build with just the `php: '7.0'` key, they all have an environment besides it

**Comment by BanzaiMan** [comment]
@theofidry I missed this response of yours.

The job defined is:

```yaml
php: '7.0'
env:
  - ELOQUENT_VERSION='~5.3.0@dev'
```

while the one excluded is

```yaml
php: '7.0'
env: ELOQUENT_VERSION='~5.3.0@dev'
```

They do not match.
