### ISSUE TITLE
JDK8u101

### ISSUE THREAD

**Issue by andrejserafim** [travis-ci/travis-ci#6668]
Is there any way to upgrade to this jdk patch version?

I've tried all the suggestions in https://github.com/travis-ci/travis-ci/issues/3259, but they all come up with u65, perhaphs I'm missing something. 

This is so we can run the versioneye plugin - it's upgraded it's security certs. More details: https://bitbucket.org/versioneye/versioneye/issues/276/ssl-certificate-issues-when-using-maven

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

This should work:

```yaml
language: java

addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk8
```

https://travis-ci.org/BanzaiMan/travis_production_test/builds/164745072#L256
