### ISSUE TITLE
HHVM version builds are failing

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#6672]
```yaml
language: php
php:
  - hhvm-3.12
```

would fail with

> "phpenv global hhvm-3.12 2>/dev/null" failed and exited with 1 during .

This was caused by a recent fix of HHVM nightly builds (see https://github.com/travis-ci/travis-ci/issues/6616).

This needs to be fixed.
