### ISSUE TITLE
Issue with debugging Android builds

### ISSUE THREAD

**Issue by JordyLangen** [travis-ci/travis-ci#6678]
I noticed the `debug build` button this morning, and decided to try it!

So I SSH'd into the VM, and ran `./gradlew assemble` which then failed because, as it turns out, it tried compiling my project with Java 7, while it should use Java 8.

So I ran `java -Xmx32m -version`, which then printed out

```
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
```

That looked good, so next I did `echo $JAVA_HOME`. It told me its JAVA_HOME directory was set to java 7, and not java 8. Running `export JAVA_HOME=/usr/lib/jvm/java-8-oracle` fixed that issue and I was able to build my project.

**Comment by BanzaiMan** [comment]
I cannot reproduce this.

Which job did you try running with the debug option? With `jdk: oraclejdk8` in `.travis.yml`, I get this upon logging in:

```sh-session
travis@testing-gce-37fce68f-f9c7-48bd-9ee6-157492b0a7e6:~/build/travis-pro/test-project$ env | grep HOME
GEM_HOME=/home/travis/.rvm/gems/ruby-2.3.1
MY_RUBY_HOME=/home/travis/.rvm/rubies/ruby-2.3.1
JAVA_HOME=/usr/lib/jvm/java-8-oracle
PERLBREW_HOME=/home/travis/.perlbrew
HOME=/home/travis
```

**Comment by BanzaiMan** [comment]
Oh, it's an Android build. I don't think we change the Java runtime for Android projects. The default Java 7 is used.

**Comment by BanzaiMan** [comment]
You can set Java version with the `jdk` key on Android builds. But with:

```yaml
language: android
jdk: oraclejdk8
```

I get

```sh-session
travis@testing-gce-71e768e6-b5cf-42c1-b893-bec08fd983b4:~/build/travis-pro/test-project$ env | grep HOME | sort
GEM_HOME=/home/travis/.rvm/gems/ruby-2.3.1
HOME=/home/travis
JAVA_HOME=/usr/lib/jvm/java-8-oracle
MY_RUBY_HOME=/home/travis/.rvm/rubies/ruby-2.3.1
PERLBREW_HOME=/home/travis/.perlbrew
```

**Comment by JordyLangen** [comment]
Hi, 

This is our (slightly masked) travis config:

```
env:
  global:
  - MALLOC_ARENA_MAX=2
  - ADB_INSTALL_TIMEOUT=10
sudo: required
dist: precise
language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-google-google_play_services
  - build-tools-24.0.2
  - android-24
  licenses:
  - android-sdk-license-.+
before_script:
  - [deleted]
script: ".travis/execute.sh"
branches:
  only:
  - "/(?!^\\d+$)^.+$/"
notifications:
  - [deleted]
after_success:
  - [deleted]
before_deploy:
  - [deleted]
deploy:
  - [deleted]

```

I just noticed we use the legacy containers for this project:

```
sudo: required
dist: precise
```
