### ISSUE TITLE
Add support for Chrome unit tests for dart

### ISSUE THREAD

**Issue by alextekartik** [travis-ci/travis-ci#6683]
@a14n, @devoncarew
I gave up trying to use content-shell, even locally where I use dartium. However being able to perform browser test is a big need. Currently many components test on firefox in travis (firebase3 for example).
I personally would like to be able to test on Chrome or Chromium. I cannot tell what get installed by default but it seems Chrome is not (https://travis-ci.org/alextekartik/travis-test.dart/builds/165477651). What would be the solution to run `pub run test -p chrome` and have the tests run in Chrome or Chromium?

**Comment by a14n** [comment]
The following yaml should do the trick:

```yaml
language: dart
sudo: required
dist: trusty

before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb

script:
 - "t=0; until (xdpyinfo -display :99 &> /dev/null || test $t -gt 10); do sleep 1; let t=$t+1; done"
 - "pub run test -p vm -p chrome -p firefox"
```
