### ISSUE TITLE
Bash regex syntax doesn't work in before_deploy or on: conditional:

### ISSUE THREAD

**Issue by respondcreate** [travis-ci/travis-ci#6686]
Here's the before_deploy block in my current travis.yml:
```yml
before_deploy:
  - echo $TRAVIS_TAG
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
  - if [[ $TRAVIS_TAG =~ ^prod-release_[0-999].[0-999]$ ]]; then zip -r "$TRAVIS_TAG.zip" * && mv "$TRAVIS_TAG.zip" "dpl_cd_upload/$TRAVIS_TAG.zip"; fi
```

And here's the raw output from a build, note the value of $TRAVIS_TAG:

```
$ echo $TRAVIS_TAG
prod_release-0.1

$ zip -r latest *
  [ console output of zip file being built ]

$ mkdir -p dpl_cd_upload

$ mv latest.zip dpl_cd_upload/latest.zip

$ if [[ $TRAVIS_TAG =~ ^prod-release_[0-999].[0-999]$ ]]; then zip -r "$TRAVIS_TAG.zip" * && mv "$TRAVIS_TAG.zip" "dpl_cd_upload/$TRAVIS_TAG.zip"; fi
```

A second zip file is not created as the regex conditional fails (note: this conditional works just fine in my local bash: GNU bash, version 3.2.57). In this same build I have a deploy section configured like so:

```yml
- provider: codedeploy
  access_key_id: [redacted]
  secret_access_key: [redacted]
  bucket: [redacted]
  key: release/latest.zip
  bundle_type: zip
  application: [redacted]
  deployment_group: [redacted]
  on:
    repo: [redacted]
    tags: true
    condition: "$TRAVIS_TAG =~ ^prod-release_[0-999].[0-999]$"
```

In the same build as above (where `$TRAVIS_TAG` is `prod-release_0.1`) this section does not deploy with the following message: "Skipping a deployment with the codedeploy provider because a custom condition was not met"

Again, running this conditional locally (GNU bash, version 3.2.57) works as expected. Test proof:

```bash
$ export TRAVIS_TAG=prod-release_0.1
$ if [[ $TRAVIS_TAG =~ ^prod-release_[0-999].[0-999]$ ]]; then echo "It's a match."; fi
It's a match.
```

Is there some quirk to the Travis bash conditional syntax for regexes that's different from GNU bash 3.2.57?
