### ISSUE TITLE
fix irc notification documentation

### ISSUE THREAD

**Issue by wenzowski** [travis-ci/travis-ci#669]
Interpolation of `%{repository_url}` is [documented](http://about.travis-ci.org/docs/user/build-configuration/) but does not currently work.

```
You can interpolate the following variables:

repository_url: your GitHub repo URL.
build_number: build number.
branch: branch build name.
commit: shorten commit SHA
author: commit author name.
message: travis message to the build.
compare_url: commit change view URL.
build_url: URL of the build detail.
```

Example:

```
notifications:
  irc: 
    template:
      - "[repository_url] %{repository_url}"
```

produces

```
18:26 < travis-ci> [travis-ci] [repository_url]
```
