### ISSUE TITLE
Global environment variables are not merged with matrix includes

### ISSUE THREAD

**Issue by raphaelstolt** [travis-ci/travis-ci#6703]
This might be a bug or a misconfiguration on my end.

Assumed I if have the following configuration:
``` yaml
env:
  global:
    - excludegroup=travis-ci-exclude
    - disable-xdebug=true
    - lint=false

matrix:
  include:
    - php: hhvm
      env: disable-xdebug=false
    - php: nightly
      env: disable-xdebug=false
    - php: 7.1
      env: disable-xdebug=false lint=true
    - php: 7.0
    - php: 5.6
      env: excludegroup=travis-ci-exclude-56
```
On the build jobs I would expect the following environment variables set:
```text
hhvm: excludegroup=travis-ci-exclude disable-xdebug=false lint=false
nightly: excludegroup=travis-ci-exclude disable-xdebug=false lint=false
7.1: excludegroup=travis-ci-exclude disable-xdebug=false lint=true
7.0: excludegroup=travis-ci-exclude disable-xdebug=true lint=false
5.6: excludegroup=travis-ci-exclude-56 disable-xdebug=true lint=false
```
But it seems like the global enviroment variables are __not__ `merged` with the ones set in the matrix include so that I end up with the following environment variables set:
```text
hhvm: disable-xdebug=false
nightly: disable-xdebug=false
7.1: disable-xdebug=false lint=true
7.0: 
5.6: excludegroup=travis-ci-exclude-56
```

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

I tested

```yaml
env:
  global:
    - excludegroup=travis-ci-exclude
    - disable-xdebug=true
    - lint=false

matrix:
  include:
    - php: hhvm
      env: disable-xdebug=false
    - php: nightly
      env: disable-xdebug=false
    - php: 7.1
      env: disable-xdebug=false lint=true
    - php: 7.0
    - php: 5.6
      env: excludegroup=travis-ci-exclude-56
```

(https://github.com/BanzaiMan/travis_production_test/blob/b1ddff8d948e24b602f7e8a9b55178e81c111c96/.travis.yml) and got what you expect. https://travis-ci.org/BanzaiMan/travis_production_test/builds/166555701

**Comment by BanzaiMan** [comment]
Oh. Did you mean you wanted environment variables whose names contain `-`?

**Comment by raphaelstolt** [comment]
Nope I want the environment variables defined as global to be merged with the ones set in the matrix.

**Comment by BanzaiMan** [comment]
`-` is an illegal character is a bash environment variable, and it doesn't work. In https://travis-ci.org/raphaelstolt/lean-package-validator/jobs/166436499#L127-L130, you see that we set 2 of the environment variables defined in https://github.com/raphaelstolt/lean-package-validator/blob/109bc0da6302c55689fd0ad27da1711cdd09d3e0/.travis.yml#L3-L7:

```sh-session
$ export excludegroup=travis-ci-exclude
$ export xdebug=true
$ export lint=false
```

Notice that we are exporting `xdebug=true`, because characters up to (and including) the last illegal character (`-` in this case) is implicitly dropped. (This might be misleading, actually. Perhaps we should be more explicit about this.)

The other two are exported.

**Comment by raphaelstolt** [comment]
Okay didn't know that `-` is an illegal character in an bash environment variable. 

Fixed it with [b279e](https://github.com/raphaelstolt/lean-package-validator/commit/b279e3b106f6633b1dd4e89dc356a60feb7ec507) and the global set envirionment variables are still lost. You can see it at PHP 7 where the environment variables should be `$EXCLUDEGROUP=travis-ci-exclude $DISABLE_XDEBUG=true $LINT=false` but Travis CI says `no environment variables set`.

**Comment by BanzaiMan** [comment]
The build page (e.g., https://travis-ci.org/raphaelstolt/lean-package-validator/builds/166636690) does not show the environment variables that are set globally, since they are not defining characteristics of the jobs.

They are set just fine. https://travis-ci.org/raphaelstolt/lean-package-validator/jobs/166636694#L127-L130

I don't think there is a bug here. We should deal with illegal characters, but that should be a separate issue.

**Comment by raphaelstolt** [comment]
So how does one set an environment variable available on all `php` versions?

Something that avoids the duplication of `OPCODE_CACHE`  shown next.
```yaml
matrix:
  include:
    - php: hhvm
      env:
      - OPCODE_CACHE=apc
    - php: nightly
      env:
      - OPCODE_CACHE=apc
    - php: 7.1
      env:
      - OPCODE_CACHE=apc
    - php: 7.0
      env:
      - OPCODE_CACHE=apc
      - DISABLE_XDEBUG=true
      - LINT=true
    - php: 5.6
      env:
      - OPCODE_CACHE=apc
      - DISABLE_XDEBUG=true
    - php: 5.5
      env:
      - OPCODE_CACHE=apc
      - DISABLE_XDEBUG=true
    - php: 5.4
      env:
      - OPCODE_CACHE=apc
      - DISABLE_XDEBUG=true
    - php: 5.3
      env:
      - OPCODE_CACHE=apc
      - DISABLE_XDEBUG=true
```
