### ISSUE TITLE
travis-ci.com dist trusty with postgis is failing to install with postgresql 9.5

### ISSUE THREAD

**Issue by billxinli** [travis-ci/travis-ci#6711]
I have a private repo that has `shp2pgsql` as a binary dependency which is installed from postgis, however postgis is conflicting with postgresql 9.5. The fix would be using postgresql 9.6, however travis is currently not supporting postgresql 9.6

```
language: node_js
dist: trusty

node_js:
  - "6.7.0"

services:
  - redis-server
  - postgresql

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpixman-1-dev libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev graphicsmagick build-essential gcc g++ postgresql-9.5-postgis-2.2 postgresql-9.5-postgis-scripts postgis
  - type shp2pgsql

before_script:
  - cp config/application.travis.js config/application.js
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d travis_ci_test
  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d travis_ci_test
  - NODE_ENV=test gulp db:migrate

compiler:
  - gcc
  - clang
env:
  - CXX=g++-4.8

addons:
  postgresql: 9.5
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - precise-pgdg-9.5
    packages:
    - gcc-4.8
    - g++-4.8
    - postgresql-9.5
    - postgresql-contrib-9.5

cache:
  directories:
    - node_modules
    - bower_components
```

```
Refused to start PostgreSQL 9.6, because PostgreSQL 9.5 is currently running! You should first stop 9.5 instance...
invoke-rc.d: initscript postgresql, action "start" failed.
dpkg: error processing package postgresql-9.6 (--configure):
 subprocess installed post-installation script returned error exit status 13
dpkg: dependency problems prevent configuration of postgresql-9.6-postgis-2.3:
 postgresql-9.6-postgis-2.3 depends on postgresql-9.6; however:
  Package postgresql-9.6 is not configured yet.
dpkg: error processing package postgresql-9.6-postgis-2.3 (--configure):
 dependency problems - leaving unconfigured
Setting up postgresql-9.6-postgis-2.3-scripts (2.3.0+dfsg-2.pgdg14.04+1) ...
No apport report written because the error message indicates its a followup error from a previous failure.
dpkg: dependency problems prevent configuration of postgresql-contrib-9.6:
 postgresql-contrib-9.6 depends on postgresql-9.6 (= 9.6.0-1.pgdg14.04+1); however:
  Package postgresql-9.6 is not configured yet.
dpkg: error processing package postgresql-contrib-9.6 (--configure):
 dependency problems - leaving unconfigured
Setting up postgresql-9.5-postgis-scripts (2.3.0+dfsg-2.pgdg14.04+1) ...
No apport report written because the error message indicates its a followup error from a previous failure.
Processing triggers for libc-bin (2.19-0ubuntu6.9) ...
Errors were encountered while processing:
 postgresql-9.6
 postgresql-9.6-postgis-2.3
 postgresql-contrib-9.6
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command "sudo apt-get install -y libpixman-1-dev libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev graphicsmagick build-essential gcc g++ postgresql-9.5-postgis-2.2 postgresql-9.5-postgis-scripts postgis" failed and exited with 100 during .
```
