### ISSUE TITLE
Problem with PyQT5, python 3 and Qt platform plugin "xcb"

### ISSUE THREAD

**Issue by algorys** [travis-ci/travis-ci#6747]
I develop an application in python3 with PyQt5. All my tests and runs work on local but I can't get running on Travis.

When I run `nosetests`, I've the following issue : 

`This application failed to start because it could not find or load the Qt platform plugin "xcb" in "".`

I've tried to search for a workaround here and on your doc, but can't find a correct setting for my travis file.

Here is what I have:

```yaml
language: python
sudo: true
python:
  # - "2.7_with_system_site_packages"
  - "3.5"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

install:
  - bash test/setup_test.sh

script:
  # so to help eventual debug: knowing what exact versions are in use can be rather useful.
  - pip freeze
  # Code static analysis
  - pep8 --max-line-length=100 --exclude='*.pyc, *.cfg, *.log' --ignore='E402' alignak_app/*
  - pylint --rcfile=.pylintrc alignak_app/
  # - cd test
  - coverage erase
  #- cd test/
  - nosetests -xv --nologcapture --with-coverage --cover-package=alignak_app test/test_*.py
  - ls -la
  - coverage combine
  - cat .coverage
  #- cd ..
  - coverage report -m

after_success:
  - coveralls -v
```

My Travis log: https://travis-ci.org/Alignak-monitoring-contrib/alignak-app/builds/168647190

I think it's a problem of path, because in log, it seems to be under PyQt5 package : 

`#L147 /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so`

Is there a way to solve that ?

Do I have to add **PyQt5** by an other way ?

Thanks.
