### ISSUE TITLE
apt addon version constraint

### ISSUE THREAD

**Issue by stephengroat** [travis-ci/travis-ci#6766]
basically, the idea is to be able to version constrain packages that are installing, i.e. 

```
addons:
  apt:
    packages:
    - mingw-w64 version='>=4.7'
```

could also apply to #6463
