### ISSUE TITLE
R builds failing with "An error occurred while generating the build script"

### ISSUE THREAD

**Issue by cfhammill** [travis-ci/travis-ci#6767]
Hi @craigcitro, @hadley and @jimhester

As of around 2 today my R build array has started dying with the build script error above. Multiple restarts have failed to resolve the problem.

Unsure what the issue could be, my .travis.yml hasn't changed in weeks.

pertinent parts of .travis.yml:

```
matrix:
  include:
    -  os: linux
       dist: trusty
    -  os: osx

language: r
sudo: required

repos:
  bioCsoft: http://bioconductor.org/packages/3.3/bioc
```

Hopefully this is a transient issue
