### ISSUE TITLE
The command "make test" exited with 2.

### ISSUE THREAD

**Issue by JefferyHus** [travis-ci/travis-ci#6771]
this is my travis file it always fails the tests with the same error i dunno why, I have tried lot of ways to fix it but it always fails.
my repository that I am trying to test: https://github.com/JefferyHus/jcomments
```yml
sudo: false

language: node_js

node_js:
  - "0.10.45"
  
before_install:
  - "curl https://install.meteor.com/ | sh"
```
