### ISSUE TITLE
No log output on build

### ISSUE THREAD

**Issue by lucasvickers** [travis-ci/travis-ci#6776]
Hello,

I'm writing an overly simplified OS X build so that I can better understand how the matrix works for `osx_image`.  When the build runs on Travis-CI, it fails with no output message.

Details:
* [Project](https://github.com/lucasvickers/travis-ci-osx-matrix)
* [.travis.yml](https://github.com/lucasvickers/travis-ci-osx-matrix/blob/master/.travis.yml)
* [build results](https://travis-ci.org/lucasvickers/travis-ci-osx-matrix/builds/169988999)

It's quite possible that Travis doesn't want to work with gcc or g++ directly, and I could remedy this by moving to make -- but I still think there should be some type of log output.

Thanks

**Comment by joepvd** [comment]
`osx_image` does not accept a list. Please try replacing the `osx_image`-block with the following:

```yaml
matrix:
  include:
  - os: osx
    osx_image: xcode7.3
  - os: osx
    osx_image: xcode8
```
