### ISSUE TITLE
The environment variable as api_key - bug or feature?

### ISSUE THREAD

**Issue by paulcarroty** [travis-ci/travis-ci#6786]
If I use 

```
deploy:
  provider: releases
  api_key:
    secure:  xxxxxxxxxxxxxxxxxxxxxxxxxxx
```

it works. If setup in repo settings the variable "GITHUBKEY=xxxxxxxxxxx" and rewrite config in other way:

```
deploy:
  provider: releases
  api_key: $GITHUBKEY
```
got the error `invalid option "--api_key="`. Logs and complete configs is here: [1](https://travis-ci.org/paulcarroty/mock-travis/builds/170913480), [2](https://travis-ci.org/paulcarroty/mock-travis/builds/170908465).

`$SUBJ`.
