### ISSUE TITLE
build fails before publish to S3 with error: Ruby ruby-1.9.3-p551 is not installed.

### ISSUE THREAD

**Issue by bmarks-mylo** [travis-ci/travis-ci#6789]
One of our builds that publishes artifacts to S3 has started to fail right before the publish step with the following output: 

```
Ruby ruby-1.9.3-p551 is not installed.

The command "rvm 1.9.3 --fuzzy do ruby -S gem install dpl" failed and exited with 2 during .
```

Our build script:

```
sudo: required

env:
  global:
    - RELEASE_BRANCH=master
    # COVERAGE_AWS_SECRET_ACCESS_KEY
    - secure: <redacted>
    # NPM_TOKEN
    - secure: <redacted>
    - BROWSERSTACK_USERNAME=<redacted>
    # BROWSERSTACK_ACCESSKEY
    - secure: <redacted>

branches:
  only:
  - master
  - develop
  - "/.*-ci$/"

language: node_js

node_js:
  - '6'

before_install:
  - sudo pip install awscli
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
script:
  - npm run build
  - npm run build:min
  - npm run test
  - npm run secure
  - ./node_modules/.bin/tag-repo

after_success:
  - ./node_modules/.bin/publish-coverage health-buyflow

deploy:
  - provider: s3
    access_key_id: <redacted>
    secret_access_key:
      secure: <redacted>
    bucket: "<redacted>"
    region: "us-west-2"
    skip_cleanup: true
    acl: public_read
    local_dir: build
    upload-dir: modules
    on:
        branch:
        - master
        - develop
```

**Comment by jeremysf** [comment]
Check out the workaround mentioned here: https://github.com/travis-ci/travis-ci/issues/5239

**Comment by Odinodin** [comment]
We just got a similar error, using provider elasticbeanstalk. The build was fine earlier today and we have not touched the build config since then.

**Comment by jeremysf** [comment]
Seems to be working for me again.

**Comment by BanzaiMan** [comment]
Is there a build log that we can look at?

Or was the problem transient (perhaps network-related) and no longer valid?

**Comment by jeremysf** [comment]
I don't think it was network related. An example failed build log is attached.

I tried restarting the build using the travis-ci.com user interface a few times with no success. 

I waited a few hours and tried restarting the build again (strictly using the travis-ci.com user interface) and it passed (i.e. no longer complains about Ruby being not installed).

The error (as you can see from the log) is:

> Ruby ruby-1.9.3-p551 is not installed.
> The command "rvm 1.9.3 --fuzzy do ruby -S gem install dpl" failed and exited with 2 during .
> Your build has been stopped.

[rawbuildlog.txt](https://github.com/travis-ci/travis-ci/files/557574/rawbuildlog.txt)

**Comment by chearon** [comment]
Getting the [same thing](https://travis-ci.org/chearon/node-canvas-prebuilt) (different ruby version in the error) when deploying to GitHub with a nodejs image, also [this was posted](http://stackoverflow.com/questions/40344231/travis-build-fails-ruby-ruby-2-2-5-is-not-installed) to stack overflow an hour ago

**Comment by scottwakefield** [comment]
I'm suddenly seeing something similar:

```
Ruby ruby-2.2.5 is not installed.

The command "rvm 2.2.5 --fuzzy do ruby -S gem install dpl" failed and exited with 2 during .
```

**Comment by mattijsf** [comment]
I'm seeing the same error. Builds were running fine earlier today. Haven't done any changes to the travis config.

```
The command "./gradlew assembleDevelopmentDebug" exited with 0.
Ruby ruby-2.2.5 is not installed.
The command "rvm 2.2.5 --fuzzy do ruby -S gem install dpl" failed and exited with 2 during .
Your build has been stopped.
```

This is my travis yml:
```yaml
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-24.0.2
  - android-24
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-android-support
  - extra-google-google_play_services
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
before_install:
- chmod +x gradlew
branches:
  only:
  - travisci
jdk:
- oraclejdk8
language: android
script:
- "./gradlew assembleDevelopmentDebug"
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: travisci
```
