### ISSUE TITLE
Matrix include compiler expansion bug

### ISSUE THREAD

**Issue by stephengroat** [travis-ci/travis-ci#6796]
https://travis-ci.org/unicorn-engine/unicorn/jobs/171546084

````
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
matrix:
  include:
  - os: osx
    env: MACOS_UNIVERSAL=yes
````

seems to produce `export CC=["clang", "gcc"]` for one of the builds. For a `cc` variable, this is obviously a problem for a build.

Is this expected behavior?
