### ISSUE TITLE
Provide a more helpful error message when trying to run Python on OS X

### ISSUE THREAD

**Issue by alexwlchan** [travis-ci/travis-ci#6825]
I just tried to run a Python build on OS X, and it failed. Much sadness. But the error message it produces isn't very helpful:

```
3.5 is not installed; attempting download
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.

The command "sudo tar xjf python-3.5.tar.bz2 --directory /" failed and exited with 1 during .
```

That sounds like maybe I just got unlucky with a bad download, or I need to add `sudo: true` to my `.travis.yml`. It wasn't until Googling around that I stumbled upon #2312, which eventually led me back to the [Travis docs](https://docs.travis-ci.com/user/languages/python):

> Python builds are not available on the OSX environment.

It would be better if there was a friendly message at the top of the Travis log which gave me this explanation, and pointed me at the relevant documentation. Then I can disable the job immediately, rather than having to Google around to find this restriction.

<details>
<summary>Contents of `.travis.yml`</summary>
```
language: python

sudo: false

python:
    - "3.5"
    - "3.6-dev"

os:
    - osx
    - linux

cache:
    directories:
        - $HOME/.cache/pip

script:
    - py.test test.py

install:
    - "pip install -r requirements.txt"
    - "pip install -r test-requirements.txt"

# Handle submodules ourselves.  http://stackoverflow.com/a/24600210/1558022
git:
    submodules: false

before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
```
</details>

<details>
<summary>Full Travis log</summary>
```
travis_fold:start:worker_info
[0K[33;1mWorker information[0m
hostname: worker-jupiter-brain:ba2dcc25-c2d7-486f-8fbf-b11d3337b0c9
version: v2.3.1-52-ga9eb435 https://github.com/travis-ci/worker/tree/a9eb4353f9171a7762f88eeeb57cce31bed8dbb8
instance: 3ef573f8-9deb-476b-8b42-4817f94008ff:travis-ci-osx10.11-xcode7.3-1475610688
startup: 1m27.028387982s
travis_fold:end:worker_info
[0Ktravis_fold:start:system_info
[0K[33;1mBuild system information[0m

Build language: python

Build group: stable

Build dist: precise

Build id: 173188988

Job id: 173188989

travis-build version: 85ef71082

travis_fold:end:system_info
[0K

travis_fold:start:fix.CVE-2015-7547
[0K$ export DEBIAN_FRONTEND=noninteractive

travis_fold:end:fix.CVE-2015-7547
[0KFix WWDRCA Certificate

$ rvm use

Warning! PATH is not properly set up, '/Users/travis/.rvm/gems/ruby-2.0.0-p648/bin' is not at first place,

         usually this is caused by shell initialization files - check them for 'PATH=...' entries,

         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',

         to fix temporarily in this shell session run: 'rvm use ruby-2.0.0-p648'.

[32mUsing /Users/travis/.rvm/gems/ruby-2.0.0-p648[0m

[33;1m3.5 is not installed; attempting download[0m

tar: Unrecognized archive format

tar: Error exit delayed from previous errors.



[31;1mThe command "sudo tar xjf python-3.5.tar.bz2 --directory /" failed and exited with 1 during .[0m



Your build has been stopped.

/Users/travis/build.sh: line 138: shell_session_update: command not found
```
</details>

**Comment by mj-harvey** [comment]
Best to install a Miniconda environment in the travis install: section

> install:
>  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;bash miniconda.sh -b -p $HOME/miniconda; export PATH="$HOME/miniconda/bin:$PATH" ;  fi

**Comment by carlosperate** [comment]
Completely agree with Alex here, not exactly a straightforward error message.

**Comment by ssbarnea** [comment]
It seems that I am just another victim of lack of Python support in OSX Travis and the current experience is **very confusing**.

A block like the one below should never give the errors we see on https://travis-ci.org/ssbarnea/InfraRed/jobs/185722298 

```
matrix:
    include:
        - os: osx
          sudo: required
          python: 2.7
          env: TOXENV=py27
```
And what is even more interesting is that installing a python interpreter on OSX can be done much easier than on other platforms, and it would not require any `sudo`.
