### ISSUE TITLE
trusty R builds: requesting R-devel, getting R-release

### ISSUE THREAD

**Issue by pboesu** [travis-ci/travis-ci#6829]
I have a matrix build for an R package that is supposed to build against R-devel and R-release on Ubuntu and OSX. However, the trusty Ubuntu builds appear to use R-release for the devel build: https://travis-ci.org/pboesu/rucrdtw/jobs/173574133#L688

This is my travis.yml
```
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

# Use Ubuntu 14.04 Trusty support for better C++11 support
sudo: required
dist: trusty

language: R
sudo: true
cache: packages
warnings_are_errors: true

matrix:
 include:
   - os: linux
     r: release
     r_packages: covr
     after_success: Rscript -e 'covr::codecov()'
   - os: linux
     r: devel
   - os: osx
     r: release
   - os: osx
     r: devel
     r_packages:
      - Rcpp
      - testthat
      - knitr
      - rmarkdown
      - dtw
      - microbenchmark
 fast_finish: true


notifications:
  email:
    on_success: change
    on_failure: change
```

Some build history:
Up to build 3 I was using precise, and the correct R version was used (https://travis-ci.org/pboesu/rucrdtw/jobs/169075130#L432)

Since build 4 (trusty) the R version that is used is a release version (https://travis-ci.org/pboesu/rucrdtw/jobs/169077410#L690) even though the [config](https://travis-ci.org/pboesu/rucrdtw/jobs/169077410/config) shows `r: devel`:

```
{
  "sudo": true,
  "dist": "trusty",
  "language": "r",
  "cache": "packages",
  "r_github_packages": [
    "jimhester/covr"
  ],
  "after_success": [
    "Rscript -e 'covr::codecov()'"
  ],
  "group": "stable",
  "os": "linux",
  "r": "devel"
}
```

any ideas @craigcitro, @hadley and @jimhester?
