### ISSUE TITLE
SonarQube: Killed sonar-scanner

### ISSUE THREAD

**Issue by alexchiraples** [travis-ci/travis-ci#6903]
Hello,

I'm trying to configure sonar-scanner for PHP. Initial issue was #6631
Right now, it fails with `/home/travis/build.sh: line 57: xxx Killed sonar-scanner -Dsonar.login=$SONAR_TOKEN`. 
I've managed to have one successful build, but only one. 
Failed [stacktrace](https://travis-ci.org/gov-ithub/maisimplu.gov.ro/builds/177273101)

This is my current configuration:

```
dist: trusty
language: php
php:
  - '5.4'
sudo: false

addons:
  sonarqube: true

env:
  global:
    - JAVA_OPTS='-Xmx3072m'
    - SONAR_RUNNER_OPTS="-Xmx2048m -XX:MaxPermSize=1024m -XX:ReservedCodeCacheSize=512m"
    - secure: # add your code here ...

before_script:
  - echo $SONAR_RUNNER_OPTS

script:
  # other script steps might be done before running the actual SonarQube analysis
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN
```

Thanks,
Alex
