### ISSUE TITLE
Allow specifying which package manager should be used (npm/yarn)

### ISSUE THREAD

**Issue by Nevon** [travis-ci/travis-ci#6922]
In some situations, you might want Travis to use npm instead of yarn, even though you provide a yarn lockfile. For example, see saguijs/sagui#280.

Defaulting to using yarn if there is a lockfile is a reasonable default, but it would be nice to be able to force Travis to use npm if you want to.

**Comment by BanzaiMan** [comment]
Could you elaborate on how you would want to switch the package manager?

**Comment by Nevon** [comment]
Well, now that I think about it, maybe this is already supported through the `install` section of the travis.yml. It's a bit more work to make sure that you're installing npm correctly etc, but maybe that's okay since you're deviating from the default path.

If we really wanted to make a simple switch for it, maybe it could be part of the `addons` section. Something like:

```
addons:
  node_js:
    package_manager: yarn || npm
```

**Comment by BanzaiMan** [comment]
Specifying with `.travis.yml` itself will bind the package manager to the commit. In other words, the configuration like:

```yaml
addons:
  node_js:
    package_manager: yarn
```

will only use one package manager in the build. Then, it is just as easy to specify which package manager to use by:

```yaml
install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash # until yarn is
  - export PATH=$HOME/.yarn/bin:$PATH                 # pre-installed
  - yarn # or "npm install"
```

If you want to have different package managers within a build matrix, this is also straightforward with the use of environment variables.

```yaml
language: node_js
node_js:
  - '6'
  - '4'
env:
  - INSTALL_CMD="yarn"
  - INSTALL_CMD="npm install"
install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash # until yarn is
  - export PATH=$HOME/.yarn/bin:$PATH                 # pre-installed
  - $INSTALL_CMD
```
