### ISSUE TITLE
Slack template fails to trigger sending a notification

### ISSUE THREAD

**Issue by chris-fa** [travis-ci/travis-ci#6930]
When using the template described as a example in [the docs](https://docs.travis-ci.com/user/notifications/#Slack-notifications), when the build completes, it won't notify.

Without the template section, it does.

```
notifications:
  slack:
    secure: "my-secure-foo-bar"
    template:
      - "%{repository}#%{build_number} (%{branch} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
```

**Comment by BanzaiMan** [comment]
Is this still a problem? If so, please show which builds did not send the notification.

**Comment by tdmalone** [comment]
Hi @BanzaiMan, just came across this issue as I experienced the same problem.
Two examples of builds that didn't send notifications:
https://travis-ci.org/tdmalone/slackemon/builds/241653138
https://travis-ci.org/tdmalone/slackemon/builds/241655067

The relevant part of my travis.yml:
```
notifications:
  slack:
    secure: ....................
    template:
      - "Build <%{build_url}|#%{build_number}> %{build_id} (<%{compare_url}|%{commit}>) of %{repository}:%{branch} by %{author} %{result} in %{duration}\n_%{commit_message}_\n*%{message}*"
```

This is from the second build above. For the first example build I tried separate entries, as implied in the docs, under `template:` instead of the `\n` line breaks.
