### ISSUE TITLE
builds: Extra job with no env variables set

### ISSUE THREAD

**Issue by goldylucks** [travis-ci/travis-ci#6944]
In all my builds I have this one [extra job](https://travis-ci.org/goldylucks/dual-n-back/builds/179354467) with no env variable set.

It doesn't bother me much, just seem like a waste to you :)

Here's [my repo](https://github.com/goldylucks/dual-n-back), and the travis file:

```
language: node_js

node_js:
  - 'node'

sudo: false

env:
  global:
    # GITHUB_TOKEN (deploy to github pages)
    - secure: SGmI2gSHYSL7iM9KIWYsOdZ3iS0KpVxXsJsTaobEvvY6n0tpDM6BVlatrDSggQjX/YT4V6vz14Fv3SXLaL/eZGQ3K0gOK7NMv7kkg4pEkLwVMjUe4DvSyLOp2GDDfQR3SKXy/+5iRHIX+gLf2QJMlK2T92cyftt3DgnBiZPke7LUa9roMP1jPaWacRwgu3TNEmd7wQ7sdf8QZNWhQDxIUQNjnQDrdXyta6ist4smzK3BNCdJh8NpsxK9gdi2Y3tvRlvfYAE70kkadIPwc/pZpZPxMaX2U3Ac4z7Dgjbv3gCGNt9kKZ4iBnRAzZ+gaQAkYV1v7AURT2Ccm2sPGD0yQX5ZUAqI+wWrjZdK52j6rI01A+0WsYxZYO5k+dGVUkBbPXJE93WFmaA1YDZ6G0ijojanMINwYKiPVfipZPe/aeD1/uxUFLRjx4n3aEe3GmJRkcbU6maX5dk7hVD+XLLQ7dUuBOdcrOuJNYtDXmbUeLFzHZLMOVc8fzyhrbKgVujgSTXn7X+Xn51fANUBKlbbTSJ7xWday7w/Ni3tuPm92HZTT3/Nnuc4uIiLHVIRJjZQ/9MYltDRn4uzcPBXzyYM+daMiD3b3Sza9PbDfdnyGr2bg6xNR0GOeV5YoSjOa+Kkc2EszNs5s6t9CjVki+h/G4ljAq5sep8fFhRusPJ/15w=
    # SAUCE_USERNAME (required by sauce-connect and nightwatch)
    - secure: rgZYURTu83ybnLloQki8m/MUZokd5bDPLzcrQrNcIYRpWcl5nxq3wLhQha7UKUMXObW1AyjYFeS27w58wLdlDFRb51/pUc+GyFv0Nowohe6tFXR7PRDV7Kmly2ABkgKzfVVYqWjAxSojACCVjcdzYJMXUswiOeCJCHFS7lLZrncQYWBDX7Qt66z6fYo+wlyJQtgqGg1HFW9l0lqHCs2NbLSc/xKSoss2ZTZas9T4Rk89923f7gWw9+CaXCk4wvRnt88KeNuwfq8bHeuCPg+q98TVTUG2/UB/LwyY8i68HJaXSPGsQK18voqYj/yhHeTVB5o2+787h5GJv8SxkmeoA4oaWc4flRuHqB8r3+XrKvn7l03VLNpRhs2GWVS3z6nM11Huq31ag0ZYTR/yWnpOnM3WNXdsnB8CYVL/ZWD0hu+nz2ENWskBbkIAhG6bBAgGUdLfkYuYNzwno08aLBoMyRlwJltbmS2rKlLGazWT0G35j1lh/6PaO3JeTjNV6n99VjH7EfvhmrUNzX+7Fca8LhcRfY1WM002i7U8Oi4n2oEtai1+kwIa3uoWoHoEif51b2rWOyaWiQURzDdY6ECHi4b3RMnIZJUexFc2zEt+tAolr/jF19zDRCZCDAn7cyvIBKjfVRymROkiQ919ZUmKMcZXDoPhvG5PT1YUSByva+c=
    # SAUCE_ACCESS_KEY (required by sauce-connect and nightwatch)
    - secure: b3n8iO8WQSIRRJPMhDayCaFcD26RvSMtaqPD15t7UbnHVKsuzooGnmoJ5QasDEu8y3Ks9R3e/gJnObaMK89dLIcRDnmakLc22fSo7KCJraduDa3btrIT5amwuwN7UggslD/FW0K3YUxNL3o4mR4y5u29GEq60U94OOmAG9duoaW31T4vpe/eNLzrMCDljQiIWBlbQYqGqUuEtHWuUbBqr/ltbLD2+UrCs9uq6lR/6tnXrW4RZMefmd6M4CSPzEBwQzaLBUtTyFO9KpjRhr3xIbscPXIicV834JIjwT0mTsut0r8XAObStyT4HDrGBwwaAeFoT4iSSCxCXzwCKVjHDPXZ8OOmPvKAYXrOhW1jq1BhPn8Gb8tV7SbH+Ef0uzw8Jq7tDAph2HtxjeRJHDMtbPxw9XPXCBS3MqelY4tsVvzv4TXDfTiruf8RmtfVC00xkZ6E8Cs8Dubgo8sQG8KF0Rr11/x3rHhM6e5WF5wUF/2JhZVHE3qQpozkw0tW4eRNiAcprmEnGiHxpjxnkIk1OjALco+XeovGzlqE/aeiiZ8sDq2KcFAMi98R2RUrK5XqY1E/hBpSvmf5ipBbAN08R/10M/ZZEUgzGUbT2BHTaVCHC66NCkxJqIs7xvi8uQZ5IiJnVKeZevk7f0toBso9qNUtMf0Y9TZc+Y3fW3VniyY=

branches:
  only:
  - master
  - "/v\\d\\./"

matrix:
  include:
  - env: SCRIPT=lint
  - env: SCRIPT=test
  - env: E2E:web=true
    addons:
      sauce_connect: true

cache:
  directories:
  - node_modules

script:
  - if [ "$SCRIPT" ]; then npm run $SCRIPT; fi
  - if [ "E2E:web" && SAUCE_ACCESS_KEY ]; then npm run $SCRIPT; fi
  - if [ "$E2E:web" ] && [ "$SAUCE_ACCESS_KEY" ]; then npm run build:web && sleep 10 && npm run e2e:web:ci; fi

after_success:
  - ./scripts/deploy-to-gh-pages-ci.sh
```

lemme know if there's anything else I can add to help
