### ISSUE TITLE
campfire notifications doesn't work

### ISSUE THREAD

**Issue by cs3b** [travis-ci/travis-ci#695]
based on [documentation](http://about.travis-ci.org/docs/user/build-configuration/) setup should look like 

``` yaml
notifications:
  campfire: [subdomain]:[api token]@[room id]
```

unfortunatelly doesn't work

what i found from reading source code:
- https://github.com/travis-ci/travis-core/blob/master/lib/travis/event/handler/campfire.rb
- https://github.com/travis-ci/travis-core/blob/master/lib/travis/event/config/campfire.rb
- https://github.com/travis-ci/travis-core/blob/master/lib/travis/task/campfire.rb

it should look more like 

``` yaml
notifications:
  campfire:
    rooms: 
     - [subdomain]:[api token]@[room id]
```

but this also doesn't work - could you let me know how I should setup it?

I'm using Travis Pro, for private repo - so encoding token is not necessary
