### ISSUE TITLE
Dart content_shell: Connection closed before test suite loaded.

### ISSUE THREAD

**Issue by RSSchermer** [travis-ci/travis-ci#6958]
After the VM tests finish, content_shell correctly runs the first ~9 files, then for the remaining files (~42) it fails with: `Connection closed before test suite loaded.`

Travis file:

```yaml
language: dart
sudo: false
with_content_shell: true
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - pub run test -p vm -p content-shell
```

Example: https://travis-ci.org/RSSchermer/bagl.dart/builds/180401811

Mentions as per the issue instructions: @a14n @devoncarew @sethladd

**Comment by a14n** [comment]
I don't really know what's going on. Perhaps `xvfb` has not started when you run your tests.

You shouldn't use this `.travis.yml` but rather :

```yaml
language: dart
sudo: false
with_content_shell: true
```

Thus you will get the default behaviour that is exactly what you seem to want (see https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/dart.rb#L98-L103)

**Comment by RSSchermer** [comment]
Thanks for the quick response. 

The default travis file results in the same behavior: https://travis-ci.org/RSSchermer/bagl.dart/builds/180544578

It also does not seem to fail at any particular test. I tried removing the first 8 test files and it still fails after about 8 or 9 test files.

**Comment by BanzaiMan** [comment]
Probably the process at the other end of the connection is dying because of resource starvation. Try using GCE with `sudo: required`.

**Comment by RSSchermer** [comment]
Am I correct in assuming that I only need to change `sudo` to `required` to force tests to run on GCE?

I tried running with the following `.travis.yml`:

```yaml
language: dart
sudo: required
with_content_shell: true
```

Still fails the content shell tests with the same error: https://travis-ci.org/RSSchermer/bagl.dart/builds/180640521

It does seem to change the order in which tests are run.
