### ISSUE TITLE
sudo trusty builds failing for PostGIS " ERROR:  could not access file "$libdir/postgis-2.3": No such file or directory"

### ISSUE THREAD

**Issue by akrherz** [travis-ci/travis-ci#6972]
My builds have been failing since the [1 December upgrade](https://docs.travis-ci.com/user/build-environment-updates/2016-12-01/).  Here is my [.travis.yml](https://github.com/akrherz/iem/blob/master/.travis.yml) and when I attempt to `create extension postgis;`, I now get this error

```
psql:init/mesosite.sql:1: ERROR:  could not access file "$libdir/postgis-2.3": No such file or directory
```

Thank you for the wonderful service.

**Comment by andershessellund** [comment]
We have the exact same problem. Any workarounds would be greatly appreciated.

**Comment by vvondra** [comment]
For us this worked:

```diff
diff --git a/.travis.yml b/.travis.yml
index 4f98fe9..6a9ff73 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -16,7 +16,7 @@ services:
     - docker
 
 install:
-    - sudo apt-get install -y postgresql-9.5-postgis-scripts
+    - sudo apt-get install -y postgresql-9.5-postgis-2.3
     - sudo service postgresql restart
     - echo "All Java installation will be done as dependencies of ./gradlew check"
     - cd e2e/rider-city-dz && npm install && cd $TRAVIS_BUILD_DIR
```

**Comment by sarasafavi** [comment]
Confirming the same issue here (with postgresql 9.5 & postgis 2.3, on Trusty). 

Alternate workaround, if you prefer to use apt addon:

```
  addons:
    postgresql: "9.5"
 +  apt:
 +    packages:
 +    - postgresql-9.5-postgis-2.3
```

**Comment by talos** [comment]
Just popped up for us too, that fix worked: https://travis-ci.org/CartoDB/bigmetadata/builds/181998680

**Comment by xrl** [comment]
I am having this issue as well, using the `dist: trusty`/`sudo: false` env.

**Comment by roji** [comment]
This has just started happening to me today: while 17 hours ago [my build went through just fine](https://travis-ci.org/npgsql/npgsql/builds/245394750), new builds fail when trying to set up PostGIS with the error above: [here's an example failing build](https://travis-ci.org/npgsql/npgsql/builds/245678694).

This seems to coincide with [the new trusty images being rolled out](https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch). However, trying to use the old image by adding `group: deprecated-2017Q2` as described in that blog post still fails with the same error, [as in this test build](https://travis-ci.org/npgsql/npgsql/jobs/245680131).

Adding the following in my .travis.yml works around the issue:

```yaml
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
```

**Comment by ericcj** [comment]
similarly, adding this fixes it for me but costs an extra 22s of build time so it would be nice to avoid it:

```
dist: trusty
sudo: false
addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5-postgis-2.3
```

**Comment by stepankuzmin** [comment]
PostGIS 2.4 anyone?

```yml
addons:
  postgresql: 9.6
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - postgresql-9.6-postgis-2.4
```

This does not work:

`ERROR:  could not access file "$libdir/postgis-2.3": No such file or directory`
