### ISSUE TITLE
SonarQube: 

### ISSUE THREAD

**Issue by 304NotModified** [travis-ci/travis-ci#6977]
I get the message 
> skipping SonarQube Scan because this branch is not master or it does not match declared branches
> ...
> INFO: SonarQube Scanner analysis skipped

[build log](https://travis-ci.org/NLog/NLog/builds/181513836)

But I have configured my branch (`sonarqube`). What am I missing?

Config (.travis.yml)

```yaml
language: csharp
solution: src/NLog.mono.sln
dist: trusty
addons:
  sonarqube: true
  branches:
    - sonarqube
    - master

    
 
install:
  - nuget restore src/NLog.mono.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release src/NLog.mono.sln
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe "./build/bin/Release/Mono 2.x/NLog.UnitTests.dll"
```

sourcecode: https://github.com/NLog/NLog/tree/sonarqube

**Comment by BanzaiMan** [comment]
I think the document is incorrect; `branches` should be under `addons.sonarqube` instead of `addons`:

```yaml
addons:
  sonarqube: true
    branches:
      - sonarqube
      - master
```

Could you try it?

**Comment by 304NotModified** [comment]
tried that, gave me an error

**Comment by vhamon** [comment]
In your sonar-project.properties, try  `sonar.branch=sonarqube`

**Comment by 304NotModified** [comment]
> In your sonar-project.properties, try sonar.branch=sonarqube

and removing the branch filter from .travis.yml?

**Comment by vhamon** [comment]
```
addons:
  sonarqube:
    branches:
      - sonarqube
```

and 

`sonar.branch=sonarqube`

It works for me.

**Comment by jalazawa** [comment]
I have this in my .`travis.yml `

```
addons:
  sonarqube:
    branches:
    - jalazawaSonar

```

and in my sonar-project.properties 

`sonar.branch=jalazawaSonar`

and I have always this 


`Skipping SonarQube Scan because this branch is not master or it does not match declared branches`


.travis.yml and sonar-project.properties are not in my master branch yet, it's a issue? 


all message 
```CMD

SonarQube addon

addon hash: 187bb90a8521235b4b8c8a4e70fb431b

Preparing SonarQube Scanner CLI

Archive:  /home/travis/.sonarscanner/sonar-scanner.zip

   creating: /home/travis/.sonarscanner/sonar-scanner-2.8/

  inflating: /home/travis/.sonarscanner/sonar-scanner-2.8/bin/sonar-scanner.bat  

  inflating: /home/travis/.sonarscanner/sonar-scanner-2.8/bin/sonar-scanner-debug  

  inflating: /home/travis/.sonarscanner/sonar-scanner-2.8/lib/sonar-scanner-cli-2.8.jar  

  inflating: /home/travis/.sonarscanner/sonar-scanner-2.8/bin/sonar-scanner  

  inflating: /home/travis/.sonarscanner/sonar-scanner-2.8/conf/sonar-scanner.properties  

  inflating: /home/travis/.sonarscanner/sonar-scanner-2.8/bin/sonar-runner.bat  

  inflating: /home/travis/.sonarscanner/sonar-scanner-2.8/bin/sonar-runner  

  inflating: /home/travis/.sonarscanner/sonar-scanner-2.8/bin/sonar-scanner-debug.bat  

$ export SONAR_SCANNER_HOME=$HOME/.sonarscanner/sonar-scanner-2.8

Preparing build wrapper for SonarSource C/C++ plugin

Using cached build wrapper

Skipping SonarQube Scan because this branch is not master or it does not match declared branches

$ export SONARQUBE_SKIPPED=true

0.41s$ sonar-scanner

INFO: Scanner configuration file: /home/travis/.sonarscanner/sonar-scanner-2.8/conf/sonar-scanner.properties

INFO: Project root configuration file: /home/travis/build/rte-antares-rpackage/antares-rpackagePivotAntares/sonar-project.properties

INFO: SonarQube Scanner analysis skipped
```
