### ISSUE TITLE
Travis includes an older version of Packer with a bug that causes hidden files to not be copied over

### ISSUE THREAD

**Issue by davidvuong** [travis-ci/travis-ci#6986]
I have the following `travis.yml` file:

```yml
language: generic
services:
- docker
script:
- packer build packer/template.json
```

Inside my Packer config, I have this:

```jso
...
  "provisioners": [
    {
      "type": "file",
      "source": "{{pwd}}/",
      "destination": "/root/app"
    },
...
```

My problem is that the version of Packer installed on the build machine:

```
packer --version
0.10.1
```

has a bug where hidden files aren't copied over when I provision my Docker image (ref: https://github.com/mitchellh/packer/issues/3142). This issue is fixed in later versions.

Is there anyway for me to specify the version of Packer I want to be on the build machines?

**Comment by BanzaiMan** [comment]
I think the best way would be to update Packer yourself.

**Comment by davidvuong** [comment]
Hey @BanzaiMan

So something like:

```yml
langauge: generic
services:
- docker
after_install:
- wget https://releases.hashicorp.com/packer/0.12.0/packer_0.12.0_linux_amd64.zip
- unzip packer_0.12.0_linux_amd64.zip
script:
- ./packer build packer/template.json
```

I foresee having quite a few builds in the next few months (both on travis and travis-pro) and having to include the packer install step for all build configs seems like a bit of a hassle.

Do you see `packer` updating to the latest version any time soon?
