### ISSUE TITLE
Allow looser match in the branch condition for deployment

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#6989]
Currently the branch-conditional deployment requires literal match.

```yaml
deploy:
  provider: X
  on:
    branch:
      - qa-12345
```

It is often useful to have some sort of rule to have a match, for example:

```yaml
deploy:
  provider: X
  on:
    branch:
      - qa-*
```
