### ISSUE TITLE
endless loop when building java/ant project

### ISSUE THREAD

**Issue by mitoskalandiel** [travis-ci/travis-ci#7009]
as can be seen in https://travis-ci.org/mitoskalandiel/JokerLibs/builds/182963955 the build succeeds then simply starts again (and again, and again ...)

my `travis.yml` contains instructions to first `ant test` then `ant jar`

the only way to break this loop is to rename `.travis.yml` to `.travis.yml.old` (or any other 'invalid' filename)

I really cannot wrap my head around this.

I've been battling this for the past 6 or so hours so any insight into this would be greatly appreciated.

**Comment by BanzaiMan** [comment]
Sorry about the issue. The build has finished cleanly now. Could you confirm?

**Comment by mitoskalandiel** [comment]
if you compare the .travis.yml from the above mentioned build against the currently succeeding build you can see that there is a big chunk of 'script' commented out as it wasn't working.

so yeah at the moment it's running but not in the desired fashion.

the code in question out of .travis.yml : (specifically look at the after_success part)

```
after_success:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git push -q https://${GH_TOKEN}@github.com/mitoskalandiel/JokerLibs.git --tags
deploy:
  provider: releases
  skip_cleanup: true
  api-key:
    secure: [redacted]
  file:
  - dist/JokerLibs.jar
  on:
    tags: false
    all_branches: true
branches:
  except:
  - "/^*-v[0-9]/"
```

**Comment by BanzaiMan** [comment]
Are you saying that if you run the script that's commented out the issue resurfaces?

**Comment by mitoskalandiel** [comment]
correct :) sorry if I didn't elaborate on that..

since github releases only allows deployment of a finished build if it's tagged, I try to run this script to apply a tag after succesfull build.

hope that makes sense.

**Comment by BanzaiMan** [comment]
What is the end goal you would like to achieve? I thought this issue was about "endless loop", but now you are talking about deployment. Are these issues related? If so, could you point to a build log URL that shows the problem? The one in the description doesn't seem to indicate any problem.

**Comment by mitoskalandiel** [comment]
right ok,i ran into this issue (endless looping of the travis build) as I was trying to implement a script, that would automatically tag a release, and deploy it to github.

what would happen is, that the build would succeed it's initial run (including unit tests) then it would run again for the deployment (which is the intended behaviour).

say for example I had pushed to master, then the script would create a tag master-v1.0.{travis-buildnumber} and deploy the resulting .jar file to github.
at this step the script would now run-away and create another tag : master-v.1.0.master-v1.0.{travis-buildnumber}.{buildnumber} and then again this time master-v1.0.{travis-buildnumber}.{buildnumber}.{buildnumber} etc

the only way to interrupt this cycle was to 
 a) remove the .travis.yml
 b) delete branches/tags from github
c) hope that it stops at some point lol

I hope that clears it up a bit more.

**Comment by BanzaiMan** [comment]
OK, so you created a new commit to the same repository during the build without any escape clause. This naturally results in infinite loop. You can build conditionally https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches so that only `master` and tags that fits a desired pattern `master-v1.0.{travis-buildnumber}` are built.

**Comment by mitoskalandiel** [comment]
you mean like above?

```
 on:
    tags: false
    all_branches: true
branches:
  except:
  - "/^*-v[0-9]/"
```
