### ISSUE TITLE
dotnet (core) builds now broken; NuGet gives "SendChunked should be true"

### ISSUE THREAD

**Issue by kierenj** [travis-ci/travis-ci#7010]
I've been successfully using .NET Core support for a few months.  Just recently (around a week ago?) the last part of my build process, using `nuget` to push packages to a private MyGet feed, stopped working.

Verbose `nuget` output below.

```
An error was encountered when fetching 'PUT https://www.myget.org/F/redriversoftware/api/v2/package/'. The request will now be retried.
SendChunked should be true.
  PUT https://www.myget.org/F/redriversoftware/api/v2/package/
System.AggregateException: One or more errors occurred. ---> System.Net.ProtocolViolationException: SendChunked should be true.
  at System.Net.HttpWebRequest.BeginGetRequestStream (System.AsyncCallback callback, System.Object state) [0x00000] in <filename unknown>:0 
```

I've run the same process locally (albeit on Windows), without problems.  I've checked by MyGet key.  I've re-run the last old build which succeeded, but that fails too - weirdly, with a "command `gulp` was not found - did you mean `gslp`".  I've fixed that part of it locally by explicitly `npm install -g gulp`-ing rather than doing a `yarn`.

Anyway - I *know* this may not be a Travis CI issue, but I'm at a loss as to what to do next to get more information or diagnose further.  It could be mono, which I use to invoke NuGet, or NuGet, or MyGet - was there some environment change or dotnet support tweak recently here?

My `.travis.yml`:

```yml
language: csharp
#cache:
#  directories:
#    - $HOME/.npm
#    - $HOME/.yarn-cache
#    - node_modules
os: linux
dist: trusty
sudo: required
env: DOTNETCORE=1
dotnet: 1.0.0-preview2-003121
mono: 4.0.5
before_install:
  - time npm install -g gulp
  - time npm install
before_script:
  - time sudo mozroots --import --machine --sync
#  - yes | sudo certmgr -ssl -m https://go.microsoft.com
#  - yes | sudo certmgr -ssl -m https://nugetgallery.blob.core.windows.net
#  - yes | sudo certmgr -ssl -m https://nuget.org
  - time wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
#  - time mono --runtime=v4.0.30319 ./nuget.exe update -self
#  - time mono --runtime=v4.0.30319 ./nuget.exe locals all -Clear
  - dotnet --version
script:
  - time gulp restore && time gulp build && if [ $TRAVIS_BRANCH = 'v0.2' ] &&  [ $TRAVIS_PULL_REQUEST = 'false' ]; then time gulp package; fi
```

cc @joshua-anderson @akoeplinger @nterry
