### ISSUE TITLE
Jdk7 broken on container based trusty

### ISSUE THREAD

**Issue by offa** [travis-ci/travis-ci#7019]
The Jdk7 is broken on container based trusty. While `JAVA_HOME` points to Jdk7, the actual executable `java` is set to Jdk8:

- `java -version`: 1.8.0_111
- `JAVA_HOME`:  /usr/lib/jvm/java-7-oracle

Unlike #6983 (sudo enabled builds) the workaround using `group: deprecated` isn't working; neither do `beta` or `edge`.

Jdk8 builds are still fine.

### Build log (exceprt):

```
[…]
$ jdk_switcher use oraclejdk7
Switching to Oracle JDK7 (java-7-oracle), JAVA_HOME will be set to /usr/lib/jvm/java-7-oracle
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
[…]
$ mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
Error: JAVA_HOME is not defined correctly.
  We cannot execute /usr/lib/jvm/java-7-oracle/bin/java
The command "eval mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V" failed. Retrying, 2 of 3.
[…]
```

### Travis.yml

```yml
language: java

dist: trusty

jdk:
    - openjdk7
    - oraclejdk7
    - oraclejdk8

cache:
    directories:
        - $HOME/.m2
```

There's no difference whether `sudo: false` is present or not.

### Workaround

Remove all Jdk7 builds ( 😞 ).

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by offa** [comment]
Oh, yes:

- https://travis-ci.org/offa/NBCndUnit/builds/182341374 (Cron)
- https://travis-ci.org/offa/NBCndUnit/builds/183347227
- https://travis-ci.org/offa/NBCndUnit/builds/183343694

Last two are some try-to-fix builds.

**Comment by BanzaiMan** [comment]
Do you have one with `sudo: required`? Your repository is new to Travis, so it defaults to `sudo: false` if the `sudo` key is absent.

**Comment by offa** [comment]
No java one yet, but I'll check again with sudo enabled.

**Comment by offa** [comment]
Adding `sudo: required` [worked](https://travis-ci.org/offa/NBCndUnit/builds/183354967).

**Comment by offa** [comment]
Any news on this?

**Comment by tbroyer** [comment]
`sudo: required` does not work for me (i.e. I already had it and it still fails): https://travis-ci.org/tbroyer/gradle-apt-plugin/jobs/194450268

Notice how `javac` still points to 9-ea (probably not the source of the failure, but still not normal).  
The build later fails with:
```
> Could not find tools.jar. Please check that /usr/lib/jvm/java-7-openjdk-amd64 contains a valid JDK installation.
```
FWIW, the error comes from https://github.com/gradle/gradle/blob/REL_2.14/subprojects/base-services/src/main/java/org/gradle/internal/jvm/JdkTools.java#L57, and the `getToolsJar()` that returns `null` is from https://github.com/gradle/gradle/blob/REL_2.14/subprojects/base-services/src/main/java/org/gradle/internal/jvm/Jvm.java#L231

So it looks like `/usr/lib/jvm/java-7-openjdk-amd64/lib/tools.jar` does not exist (among other files, because there should be a `bin/javac`, `bin/jar` and `bin/javadoc` too, at a minimum).

Note that I use `group:edge` too to get JDK 9 (see https://github.com/travis-ci/travis-ci/issues/5520)

**Comment by BanzaiMan** [comment]
Sorry about the delay.

The problem is twofold.

1. The switch to a different JDK is happening after `sudo` is disabled on the container. This is addressed in https://github.com/travis-ci/travis-build/pull/944.
1. With this PR, we get the warning that many [alternatives do not exist](https://staging.travis-ci.org/BanzaiMan/travis_staging_test/jobs/538322#L414-L445). This, I think, is due to some packages missing.

We'll investigate this.

**Comment by offa** [comment]
Any news on this? The issue is still present.

**Comment by zentol** [comment]
I just encountered this as well when switching from precise to trusty, see https://travis-ci.org/zentol/flink/builds/245786522.

**Comment by offa** [comment]
After the latest update the **OpenJDK 7** seems to **_work_**, however, the **Oracle JDK7** is **_still broken_** (#7964).

**Comment by bootstraponline** [comment]
I'm also encountering this issue.

> ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/java-7-oracle

```yaml
sudo: false
dist: trusty
language: java
env:
  global:
    - GRADLE_OPTS="-Xmx512m"
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2
    - ./build
    - ./.gradle
script:
  ./gradlew check --info
after_success:
  - bash <(curl -s https://codecov.io/bash)
```

https://travis-ci.org/googleapis/toolkit/builds/255731293
