### ISSUE TITLE
travis_wait removes quotes

### ISSUE THREAD

**Issue by joepvd** [travis-ci/travis-ci#7020]
See: https://travis-ci.org/joepvd/travis-experiment/builds/183363007

```yaml
sudo: false
language: ruby
dist: trusty
script:
    - awk 'BEGIN{print ARGC-1; for (i=1; i<ARGC; i++)print ARGV[i]}' $a
    - awk 'BEGIN{print ARGC-1; for (i=1; i<ARGC; i++)print ARGV[i]}' "$a"
    - travis_wait awk 'BEGIN{print ARGC-1; for (i=1; i<ARGC;i++)print ARGV[i]}' "$a"
install: true
env:
    global:
        a="one two three"
notifications:
    email: false
```

This produces:

```
The command "awk 'BEGIN{print ARGC-1; for (i=1; i<ARGC;i++)print ARGV[i]}' $a" exited with 0.
0.01s$ awk 'BEGIN{print ARGC-1; for (i=1; i<ARGC;i++)print ARGV[i]}' "$a"
1
one two three
The command "awk 'BEGIN{print ARGC-1; for (i=1; i<ARGC;i++)print ARGV[i]}' "$a"" exited with 0.
$ travis_wait awk 'BEGIN{print ARGC-1; for (i=1; i<ARGC;i++)print ARGV[i]}' "$a"
Still running (1 of 20): awk BEGIN{print ARGC-1; for (i=1; i<ARGC;i++)print ARGV[i]} one two three
The command awk BEGIN{print ARGC-1; for (i=1; i<ARGC;i++)print ARGV[i]} one two three exited with 1.
Log:
awk: cmd. line:1: BEGIN{print
awk: cmd. line:1:            ^ unexpected newline or end of string
/home/travis/build.sh: line 151:  1417 Terminated              travis_jigger $! $timeout $cmd
The command "travis_wait awk 'BEGIN{print ARGC-1; for (i=1; i<ARGC;i++)print ARGV[i]}' "$a"" exited with 1.
```
