### ISSUE TITLE
Travis unable to use compiled output in command line to test and see if build does not crash.

### ISSUE THREAD

**Issue by AraHaan** [travis-ci/travis-ci#7021]
So, I have an issue with my project I have a link to what the build returns.

The build fails because of this issue. I am not sure why it does not work when it should unless it is entirely in my ``.travis.yml`` that I had to code in all by myself. I would like to do this to test an crash on the C build that it has (yes it has both C and C++ linkage).

the ``.travis.yml`` here: https://github.com/AraHaan/bin2c/edit/master/.travis.yml

build output from latest commit here: https://travis-ci.org/AraHaan/bin2c/builds/183246244

I would like to have help on fixing this so that way it can suit my needs for not only building the tests but the tests are really for checking to see if it crashes or not. Although it would be nice if I could add something to that C code to help track down the crash (crash only happens when ``_USE_C_VERSION`` is defined by compiler).

Also what if I had python code + C# + C++ code in 1 project like you can see here: https://github.com/AraHaan/Els_kom_new
Could I do such thing for travis to build / check all 3?

**Comment by BanzaiMan** [comment]
I think your `.travis.yml` has many issues. To begin, what is `$bin2c` supposed to point to? There is no variable of this name when the execution gets to https://travis-ci.org/AraHaan/bin2c/jobs/183246248#L299, so it is empty. The command, then, becomes `/custvar "IMAGE_VP" /nohead /infile "./tests/VP.jpg" /outfile "./tests/VP.h" /basefolder "./tests/"`, but `/custvar` does not exist, so your build fails.

If you are expecting to execute the compiled file in the previous line, you need `./bin2c`, not `$bin2c`. Also, do understand that `/custvar` will refer to a file in `/`, unless you do some argument processing. Please keep in mind that your builds will run on a Linux VM, not Windows.

**Comment by BanzaiMan** [comment]
I'm closing this now. I do not think this is an issue on our side.

**Comment by AraHaan** [comment]
I tried executing that with ``./bin2c`` and well this.

```
bin2c_c /custvar "IMAGE_VP" /nohead /infile "./tests/VP.jpg" /outfile "./tests/VP.h" /basefolder "./tests/"
/home/travis/build.sh: line 57: ./bin2c_c: Permission denied
```

**Comment by BanzaiMan** [comment]
This is an issue with your tooling. Please review your code.

**Comment by AraHaan** [comment]
Well then what do I change this to then since I never really used linux before. :stuck_out_tongue:?

```yml
language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
sudo: required
dist: trusty
script:
  - $CC -c -O3 -std=c++11 bin2c.cpp -o "bin2c"
  - $CC -c -O3 -D _USE_C_VERSION bin2c.cpp -o "bin2c_c"
  - export bin2c=./bin2c
  - export bin2c_c=./bin2c_c
  - echo $PATH
  - $bin2c /custvar "IMAGE_VP" /nohead /infile "./tests/VP.jpg" /outfile "./tests/VP.h" /basefolder "./tests/"
  - $CC -c -O3 -std=c++11 ./tests/VP.cpp -o ./tests/VP
  - $bin2c /custvar "IMAGE_VP" /nohead /infile "./tests/VP.jpg" /outfile "./tests/VP.h" /basefolder "./tests/"
  - $CC -c -O3 -std=c++11 ./tests/VP.cpp -o ./tests/VP
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "dCRZoMHNI3Qg/D8FrCzSKQ1zsPVgxMZCXSbuTsBXzcVcN6ujF3Q1UnycsMpOOu/QYItFQX3dOg0UrrV3RmUooBGLeW5h3H4RQvYs4/UXg3PgDOjcaLXIJJHb8ijapQphnkjZt4vS1fCVM0i/X6tQwhbEIseswoe8sOTVb1JTyE6zyMEwLGESpn1v/RMQOgFMqaF6PZfYRkXDx+kANoaFx+H4coCElwP0ikqZLbklDKgCEgqAgkMXQQGpeVGfEkn07heOtwqyTJHKdSV2/01ZbAVpzukRYx7e7pXT5ZZdGrcb+1oEGZMyUIUX2nGmc+7NnuwZSTPmSJFiTIP1ars35gIE712pIYI0Vap+XjIc0/+30S9aZitwQUgQ/6yMPpHjPMjOCWM/5wf9+LPL6U1bj+jQFt2KJz+gUo11VL+6S1+4kVCNv+dgyn4eR0+pBNLiFLleTLRzH8q1h9Wze7NnymH/mZfU0LHz/P+Fd/500J9XwU65eEwWAiH+LbRk6RtBH0FbQK3C+V7itYOcScHsV8Gt/EMyepkhdG37cT+xXwxq8b8xA3c3cnQnTR7F4nSl1KO7CbBs4UKM3oeKv5iYSEop6uJmIo1fDtMpDVcDoNz1n55KwMjvXoxx5oS7x0Z2gvi9oOGl6NLnXVfNDbYtNxQI1q5NCORfv9BuX7s2fbc="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "AraHaan/bin2c"
      description: "Build submitted via Travis CI"
    notification_email: seandhunt_7@yahoo.com
    build_command_prepend: "./configure; make clean"
    build_command:   "clang -c -std=c++14 -O3 -ftime-report bin2c.cpp -o bin2c"
    branch_pattern: coverity_scan
```
