### ISSUE TITLE
Allow build for iOS and Android

### ISSUE THREAD

**Issue by LazyChild** [travis-ci/travis-ci#7023]
Is it possible to config a repository that have both iOS and Android code?

**Comment by BanzaiMan** [comment]
This should be possible with `matrix.include`.

For example,

```yaml
language: android
matrix:
  include:
    - language: objective-c
⋮ # rest
```

You will need to differentiate jobs by inspecting various characteristics of each job and vary the build process, so that the jobs can do what they are supposed to do.
