### ISSUE TITLE
using clang3.9

### ISSUE THREAD

**Issue by bloodstalker** [travis-ci/travis-ci#7036]
I'm trying to use Clang3.9 as a compiler but whatever i do it fails. I'm not using Cmake. I'm just using make.
How it fails is, it will not use clang3.9. it will just go back to using clang3.4. How can i make it use clang3.9?
here's my yml file:
```yaml
dist: ubuntu-precise
language: cpp
compiler: clang
addons: 
   apt: 
      packages: 
        - clang-3.9
        - libclang-3.9-dev
        - libllvm3.9
script: make
```
