### ISSUE TITLE
Improved support for permutations of environment variables in build matrix

### ISSUE THREAD

**Issue by jfinkels** [travis-ci/travis-ci#7041]
Suppose I have two environment variables, each of which represents a Boolean. As far as I can tell, the way to set each permutation of these in the Travis configuration file is

```yaml
env:
  - VAR1=true VAR2=true
  - VAR1=true VAR2=false
  - VAR1=false VAR2=true
  - VAR1=false VAR2=false
```

It would be nice if Travis could automatically interpolate all permutations of a given range of values for an environment variable. I'm not sure exactly how the syntax would work, but something like

```yaml
env:
  permutations:
    - VAR1: [true, false]
    - VAR2: [true, false]
```

I'm not sure if there is already a better way to do this, so please let me know if I've missed something.
