### ISSUE TITLE
matrix.allow_failures partial environment matching

### ISSUE THREAD

**Issue by NiklasRosenstein** [travis-ci/travis-ci#7053]
I expected the following to "just work"

```yaml
env:
  - C4DVERSION=12.032 ALLOW_FAILURE=yes
  - C4DVERSION=13.051 ALLOW_FAILURE=yes
  - C4DVERSION=14.041 ALLOW_FAILURE=yes
  - C4DVERSION=15.064
  - C4DVERSION=16.021
  - C4DVERSION=16.050
  - C4DVERSION=17.048
  - C4DVERSION=18.030

matrix:
  allow_failures:
    - env: ALLOW_FAILURE=yes
```

But instead I have to use

```yaml
matrix:
  allow_failures:
    - env: C4DVERSION=12.032 ALLOW_FAILURE=yes
    - env: C4DVERSION=13.051 ALLOW_FAILURE=yes
    - env: C4DVERSION=14.041 ALLOW_FAILURE=yes
```

Is it supposed to work this way? Personally I would much prefer the first version to work.
