### ISSUE TITLE
Secure environmental variables not visible to Travis.

### ISSUE THREAD

**Issue by Fengson** [travis-ci/travis-ci#7056]
My travis.yml :
```
language: objective-c
osx_image: xcode8.2
env:
  global:
    - secure: "0m0cYvje+xL ( ... ) oNkvjBB0="
    - secure: "kMOh+CxTGVL ( ... ) AVc="
    - TEST=123
before_install:
- echo -e "machine github.com\n login $CI_USER_TOKEN" >> ~/.netrc
before_script:
- gem install fastlane
script:
- "./fastlane/travis.sh"
```

Travis config:
```
{
  "language": "objective-c",
  "osx_image": "xcode8.2",
  "before_install": [
    "echo -e \"machine github.com\\n login $CI_USER_TOKEN\" >> ~/.netrc"
  ],
  "before_script": [
    "gem install fastlane"
  ],
  "script": [
    "./fastlane/travis.sh"
  ],
  "global_env": "TEST=123",
  "group": "stable",
  "dist": "osx",
  "os": "osx"
}
```

I've tried adding variables through console on travis-ci.com as well as terminal.
It only works when they are public and visible, but when I secure them, my `CI_USER_TOKEN` variable cannot be read and I cannot authenticate. Any help please?

I've added variables using command:
`travis encrypt CI_USER_TOKEN=my_token`

I tried with and without quotation marks.

I've also tried Travis dashboard in `Settings -> Environment Variables`.
Only when they are public (Display value in build log is ON) it works.
