### ISSUE TITLE
Travis CI gets the wrong distribution when a PR is open from pushing a branch

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [travis-ci/travis-ci#7063]
It works when the PR is created from Github UI.

I don't have a lot of information or the root cause, so I will post here my investigation to see if this can shed some light.

**Comment by FagnerMartinsBrack** [comment]
**Project's .travis.yml file**

```
language: node_js

sudo: required
dist: trusty

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

env:
  global:
    secure: <omitted>

before_install:
  - echo "@tabdigital:registry=https://artifactory.tabdigital.com.au/artifactory/api/npm/npm/" >> ~/.npmrc
  - echo "//artifactory.tabdigital.com.au/artifactory/api/npm/npm/:_password=\${NPMPASS}" >> ~/.npmrc
  - echo "//artifactory.tabdigital.com.au/artifactory/api/npm/npm/:username=travis-ci" >> ~/.npmrc
  - echo "//artifactory.tabdigital.com.au/artifactory/api/npm/npm/:email=travis-ci@tabdigital.com.au" >> ~/.npmrc
  - echo "//artifactory.tabdigital.com.au/artifactory/api/npm/npm/:always-auth=true" >> ~/.npmrc
  - npm install -g npm

install:
  - "sudo pip install awscli"

before_script:
  - "export DISPLAY=:99"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - npm install
  - export CHROME_BIN=/usr/bin/gnome-www-browser

script:
  - grunt build
  - echo "Run unit tests"
  - grunt test
  - echo
  - echo "Run acceptance tests"
  - "cp -f ./app/scripts/configuration.ci.js ./app/scripts/configuration.js"
  - grunt e2e

after_failure:
  - ./script/copy-screenshots.sh

cache:
  directories:
    - node_modules

notifications:
  hipchat:
    rooms:
      - <ommitted>
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
    on_success: change
    on_failure: change
```
