### ISSUE TITLE
allow_failures won't build 

### ISSUE THREAD

**Issue by fmaussion** [travis-ci/travis-ci#7064]
Hi,

Travis seems to ignore my allow_failures job requests. Here is my matrix:

```
matrix:
  fast_finish: true
  include:
  - python: 2.7
    env: CONDA_ENV=py27-all
  - python: 3.5
    env: CONDA_ENV=py35-all
  - python: 3.5
    env: CONDA_ENV=py35-min
  - python: 3.5
    env: CONDA_ENV=py35-xr
  allow_failures:
  - python: 3.5
    env: CONDA_ENV=py35-all-rc
```

And the current build: https://travis-ci.org/fmaussion/salem 

Removing the allowed failure lines runs just fine (tested [here](https://travis-ci.org/fmaussion/salem/builds/185735017) for example).

Any idea on what is going wrong? Thanks a lot!

**Comment by fmaussion** [comment]
I forgot to send a link to my travis.yml file: https://github.com/fmaussion/salem/blob/master/.travis.yml

**Comment by BanzaiMan** [comment]
In order to be allowed to fail, a job needs to be included first.

**Comment by fmaussion** [comment]
Aaaaah alright, so the matrix should look like:

```
matrix:
  fast_finish: true
  include:
  - python: 2.7
    env: CONDA_ENV=py27-all
  - python: 3.5
    env: CONDA_ENV=py35-all
  - python: 3.5
    env: CONDA_ENV=py35-min
  - python: 3.5
    env: CONDA_ENV=py35-xr
  - python: 3.5
    env: CONDA_ENV=py35-all-rc
  allow_failures:
  - python: 3.5
    env: CONDA_ENV=py35-all-rc
```

That makes sense, thanks a lot @BanzaiMan
