### ISSUE TITLE
Missing apt packages when build

### ISSUE THREAD

**Issue by erguotou520** [travis-ci/travis-ci#7090]
My `.travis.yml` is:
```yaml
osx_image: xcode7.3

sudo: required
dist: trusty

language: c

matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - icnsutils
      - graphicsmagick
      - xz-utils
      - rpm

cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.cache

addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - icnsutils

before_install:
  - mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.2.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.2.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull

install:
- nvm install 6
- npm install electron-builder
- npm install
- npm prune

script:
- npm run build

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
```
There are 4 packages need to be installed, but only is installed, the actual config is (reference to `view config in web`)
```json
{
  "osx_image": "xcode7.3",
  "sudo": "required",
  "dist": "trusty",
  "language": "c",
  "addons": {
    "apt": {
      "packages": [
        "libgnome-keyring-dev",
        "icnsutils"
      ]
    }
  },
  "cache": {
    "directories": [
      "node_modules",
      "app/node_modules",
      "$HOME/.electron",
      "$HOME/.cache"
    ]
  },
  "before_install": [
    "mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.2.1/git-lfs-$([ \"$TRAVIS_OS_NAME\" == \"linux\" ] && echo \"linux\" || echo \"darwin\")-amd64-1.2.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull"
  ],
  "install": [
    "nvm install 6",
    "npm install electron-builder",
    "npm install",
    "npm prune"
  ],
  "script": [
    "npm run build"
  ],
  "group": "stable",
  "compiler": "clang",
  "env": "CC=clang CXX=clang++ npm_config_clang=1",
  "os": "linux"
}
```
