### ISSUE TITLE
Stop sending email for "BUILD PASSED" for every new pull request

### ISSUE THREAD

**Issue by mnapoli** [travis-ci/travis-ci#7097]
When I'm working on a repository of mine, every time I push a new branch I get an email when the build passes.

This is a lot of useless noise, I would like to disable that but couldn't find an option for that. I'm looking for an option to do that globally.

(note that this is specifically about build passing, build fails are interesting)

**Comment by BanzaiMan** [comment]
If you do not wish to be notified of the passing builds, you can disable that with

```yaml
notifications:
  email:
    on_success: never
  ⋮ # rest
```
