### ISSUE TITLE
How to build with linux+osx and multiple versions of nodejs and multiple env variables?

### ISSUE THREAD

**Issue by Ks89** [travis-ci/travis-ci#7099]
I want a config file to do these builds:
- linux, nodejs 6.0,        3 env vars (blabla_1, blabla_2, blabla_3) and 2 secure vars (sec_1 and sec_2)
- linux, nodejs 6 latest, 3 env vars (blabla_1, blabla_2, blabla_3) and 2 secure vars (sec_1 and sec_2)
- linux, nodejs 7.0,        3 env vars (blabla_1, blabla_2, blabla_3) and 2 secure vars (sec_1 and sec_2)
- linux, nodejs 7 latest, 3 env vars (blabla_1, blabla_2, blabla_3) and 2 secure vars (sec_1 and sec_2)
- osx, nodejs 6.0,        3 env vars (blabla_1, blabla_5, blabla_6) and 2 secure vars (sec_1 and sec_2)
- osx, nodejs 6 latest, 3 env vars (blabla_1, blabla_5, blabla_6) and 2 secure vars (sec_1 and sec_2)
- osx, nodejs 7.0,        3 env vars (blabla_1, blabla_5, blabla_6) and 2 secure vars (sec_1 and sec_2)
- osx, nodejs 7 latest, 3 env vars (blabla_1, blabla_5, blabla_6) and 2 secure vars (sec_1 and sec_2)

PS: every build uses 3+2 env vars at the same time. I don't want to multiply builds (only 8 builds)
Also, note that blabla_1 is the same for all linux build, but could be different for the other osx builds
How can I write a .travis.yml for this configuration?

I made many tests without success.
My actual .travis.yml is:

```
language: node_js
matrix:
  include:
    - os: linux
      node_js:
        - '7'
        - '7.0'
        - '6'
        - '6.0'
      env:
        global:
          - secure: secure.var.1
          - secure: secure.var.2
        matrix:
          - blabla_1=value blabla_2=val blabla_3=val
    - os: osx
      node_js:
        - '7'
        - '7.0'
        - '6'
        - '6.0'
      env:
        global:
          - secure: secure.var.1
          - secure: secure.var.2
        matrix:
          - blabla_1=anotherval blabla_5=val blabla_6=val
sudo: required
addons:
  firefox: latest
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - bash my_script.sh
cache:
  apt: true
  bundler: true
  directories:
    - node_modules
```

Checking this .travis.yml with the official travisci validation online tool i get:
```
in addons section: unexpected key apt, dropping
in matrix.include.node_js section: does not support multiple values, dropping 7.0
in matrix.include.node_js section: does not support multiple values, dropping 6
in matrix.include.node_js section: does not support multiple values, dropping 6.0
in matrix.include section: dropping env section: unexpected pair, unexpected pair
```

**Comment by BanzaiMan** [comment]
You can define a 2x4 build matrix with `os` and `node_js`, along with the common env vars, then export `blabla_2`, `blabla_3`, `blabla_5`, `blabla_6` based on the `$TRAVIS_OS_NAME` value. The rest (`blabla_1`, `sec_1`, `sec_2`) should be defined globally.

**Comment by Ks89** [comment]
Ok thank u, I modified my config file in this way:

```
language: node_js
node_js:
  - "7"
  - "7.0"
  - "6"
  - "6.0"
os:
  - linux
  - osx
env:
  global:
    - secure: secure.var.1
    - secure: secure.var.2
  matrix:
    - blabla_1=value blabla_2=val blabla_3=val blabla_4=val blabla_5=val blabla_6=val
sudo: required
addons:
  firefox: latest
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - bash my_script.sh
cache:
  apt: true
  bundler: true
  directories:
    - node_modules
```

Now I'm able to run 8 builds but all with the same env variables.

I don't understand this phrase: `then export blabla_2, blabla_3, blabla_5, blabla_6 based on the $TRAVIS_OS_NAME value.`. 

Can you provide an example?

Thank u.
