### ISSUE TITLE
Update OS X and Linux compilers (g++, clang) to latest version

### ISSUE THREAD

**Issue by AraHaan** [travis-ci/travis-ci#7100]
Please install g++-6 or newer (g++-7 and gcc-7 from source) for the projects that use C++ 14~17, besides it has some bug fixes and some performance fixes as well.

Example being like this especially clang 3.9 requirements on projects fails when someone uses ``std::experimental::filesystem`` in the ``<experimental/filesystem>`` header in C++ 14, in C++ 17 it will move to ``std::filesystem`` and the header would be renamed to ``<filesystem>``

https://travis-ci.org/AraHaan/bin2c/builds/188047806 As you can see all the OSX builds fail because clang 3.9 and g++-6 are not present. But the gcc 6 build of it on linux works just fine. Note: I try to manually hack the compilers and the clang version to 3.9 using the build matrix method.

Besides a lot of projects requires g++-6, gcc-6, and clang 3.9 only to build and any versions before that would be no dice. Mainly I want OSX and the linux VM's to at least always have the latest compilers so I don't have to hack my ``.travis.yml`` just to have it install it and waste some time before build just to make it work. An example compile that also comes with latest gcc option is at gcc.godbolt.org but it does not include osx building. So updating the compilers to the latest on those VM's by default should help make all the C++14~17 programmers happy.

**Comment by AraHaan** [comment]
Also seems that homebrew is not installed and so using homebrew to download latest gcc and clang fails as well.

**Comment by AraHaan** [comment]
Ok, so turns out I could use this on the linux side of things, however for OSX this would require homebrew being present on the travis VM's:

```yaml
language: cpp
sudo: required
dist: trusty

addons:
#  coverity_scan:
#    project:
#      name: "AraHaan/bin2c"
#      version: 0.15.0
#      description: "bin2c Conversion Tool."

    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
        packages:
            - g++-6
            - clang-3.9

    notification_email: seandhunt_7@yahoo.com
#    build_command_prepend: " -O3 -std=c++14 bin2c.cpp -o bin2c"
#    build_command: $CXX
#    branch_pattern: coverity_scan

matrix:
  include:
    - compiler: gcc
      env: COMPILER=g++-6

    - compiler: clang
      env: COMPILER=clang++-3.9

before_install:
    - if [ "$TRAVIS_OS_NAME" = "linux"  ]; then sudo apt-get -qq update;    fi

before_script:
    - if [ "$COMPILER" = "g++-6"        ]; then export CXX="g++-6" CC="gcc-6";              fi
    - if [ "$COMPILER" = "clang++-3.9"  ]; then export CXX="clang++-3.9" CC="clang-3.9";    fi
```

This should hopefully help those who depend on newer compilers to compile C++ 14 or newer.

Note: The configureation would have to be completely different on OSX unless it is set up to use the apt part and call some other package manager that would resolve the dependencies (or in this case the compilers themselves) instead. Otherwise it would require having to install homeprew using ruby as admin. However doing that with sudo will not work with travis sadly.
