### ISSUE TITLE
Android SDK Build-Tools 25.0.2 license problem

### ISSUE THREAD

**Issue by mirhoseini** [travis-ci/travis-ci#7110]
I found that there is a problem with Android SDK Build-Tools version 25.0.2.

Here is my build using **25.0.2**:
[https://travis-ci.org/mmirhoseini/Android-coding-challenge/builds/188873875](https://travis-ci.org/mmirhoseini/Android-coding-challenge/builds/188855508
)
which stoped by this error:
```
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Build-Tools 25.0.2].
```

I downgrade my SDK to **25.0.0** and problem solved temporarily:
[https://travis-ci.org/mmirhoseini/Android-coding-challenge/builds/188873875](https://travis-ci.org/mmirhoseini/Android-coding-challenge/builds/188873875)

**Comment by jehy** [comment]
Same here when not using versions. In my travis.yml I wrote

```yml
android:
  components:
    - tools
    - build-tools
    - platform-tools
```

I also tried to put
```yml
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
```

But it had no effect.

**Comment by jehy** [comment]
Ok, somehow I managed to get it working.
My .travis.yml:

```yml
language: android
sudo: false
android:
  components:
    - tools
    - build-tools-25.0.2
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support
    # The BuildTools version used by your project
    #- build-tools-19.1.0

    # The SDK version used to compile your project
    - android-16
    - android-21
    - android-22
    - android-25

    # Additional components

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-16
    - sys-img-armeabi-v7a-android-21
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-25
jdk: oraclejdk8
os:
  - linux
```

My build.gradle:
```gradle

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
```
