### ISSUE TITLE
Jobs with `language: objective-c` should always show Mac logo in build page

### ISSUE THREAD

**Issue by llafuente** [travis-ci/travis-ci#7144]
.travis.yml
```yml
language: objective-c

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.3
```

Run osx twice, ignoring Linux.

`language: csharp` solve the problema and now run osx and Linux.

This is one of the errored builds: https://travis-ci.org/llafuente/unity-platformer/builds/190976729

If you take a look at `Worker information` both are osx.
