### ISSUE TITLE
Exclude jobs based on branch name

### ISSUE THREAD

**Issue by lmazuel** [travis-ci/travis-ci#7149]
Hello,

I'm sorry if this topic is covered somewhere in the documentation, I wasn't able to find an answer anywhere.

I want to exclude jobs from my matrix depending of the branch name.
For instance, let's say I have two Python jobs:
```yaml
language: python
python:
  - "2.7"
  - "3.6"
```
I want to exclude "2.7" if branch names startswith "deploy", but do everything if not ("master", PRs, etc.).

Deployment framework already allows me to deploy only if "python" is "3.6", but the other job are still executed (for nothing, waste of time and resources).

I was looking for a way to declare that in "exclude" of "matrics" (of anywhere else to achieve the goal :))

Workaround tentative: is there a way to skip a job from a before_install step (so I can check `$TRAVIS_TAG` and exit)?

Thank you!

**Comment by fgregg** [comment]
```yaml
matrix:
  - python: "3.6"
  - python: "2.7"
    before_install:
      - if ! [[ $TRAVIS_TAG ]]; then exit 0; fi
```
works to bail out early, but you still need to wait for the machine to be provisioned and the setup that takes happens `before_install`

**Comment by BanzaiMan** [comment]
This feature is useful for Build Stages.

**Comment by nfantone** [comment]
Same requirement over here. We are building an Android `.apk` on a `- language: android` matrix and it takes several minutes to boot and startup before bailing thanks to `- if [ -z "$TRAVIS_TAG" ]; then travis_terminate 0; fi;`.

It'd be nice if it could be skipped altogether. Something like an `on:` clause for every `include` in the `matrix`, perhaps?

**Comment by felix-zg** [comment]
This feature is super useful for partial builds.

**Comment by evan-scott-zocdoc** [comment]
> it takes several minutes for the environment to boot and startup before bailing

Same issue on our side. The "deploy" job still has to boot up and run even for PR builds where we definitely do not want to deploy code.

**Comment by keradus** [comment]
feature was already approved , more info at https://github.com/travis-ci/beta-features/issues/11

**Comment by BanzaiMan** [comment]
While it is considered beta (some future changes are possible), our recent release of the Build Stages feature makes this possible. https://blog.travis-ci.com/2017-09-12-build-stages-order-and-conditions

In the use case of OP:

> I want to exclude "2.7" if branch names startswith "deploy", but do everything if not ("master", PRs, etc.).

One can write:

```yaml
language: python
python:
  - "3.6"
matrix:
  include:
    - python: "2.7"
      if: branch =~ ^deploy
```

**Comment by scottx611x** [comment]
@BanzaiMan I had success with your suggestion by flipping the order of the `if`
``` yaml
language: python
python:
  - "3.6"
matrix:
  include:
    - if: branch =~ ^deploy
      python: "2.7"
```
