### ISSUE TITLE
[question] Travis Deploy Ignoring the Failure of Other Builds

### ISSUE THREAD

**Issue by ickc** [travis-ci/travis-ci#7156]
Example:

```yaml
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
deploy:
  provider: pypi
...
  on:
    tags: true
    python: "3.5"
```

Say, if the "2.7" build failed, but the "3.5" build succeeded. Then the "3.5" build will continue to deploy it on pypi, ignoring the failure in all other builds. Are there any way to deploy only when *all* builds (except `allow_failures`) passes?

If it can be done, perhaps the documentation in [Deployment - Travis CI](https://docs.travis-ci.com/user/deployment) should be improved to reflect this.

If it cannot be done, perhaps this issue becomes a [feature-request]. Thanks!
