### ISSUE TITLE
Can't use sudo npm on build

### ISSUE THREAD

**Issue by luispcosta** [travis-ci/travis-ci#7159]
Here's my `.travis.yml` file:

```yml
sudo: required
dist: trusty
language: node_js
node_js:
  - "6"
script:
  - sudo npm install -g sequelize -y
  - sequelize db:migrate --migrations-path=server/migrations --models-path=server/models
  - npm run test-server
services:
  - mysql
before_install:
  - mysql -e 'DROP DATABASE IF EXISTS reddit_clone_test;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS reddit_clone_test;'
  - mysql -e 'CREATE USER "localdev"@"127.0.0.1" IDENTIFIED BY "localdev"'
  - mysql -u root -e 'GRANT ALL PRIVILEGES ON reddit_clone_test.* TO "travis"@"127.0.0.1" IDENTIFIED BY ""'
  - mysql -u root -e 'GRANT ALL PRIVILEGES ON reddit_clone_test.* TO "localdev"@"127.0.0.1" IDENTIFIED BY "localdev"'
```

The command that fails is the `sudo npm install -g sequelize -y`, with the message:
`sudo: npm: command not found`

I've tried doing `sudo $(which npm) install -g sequelize -y` but it doesn't work.

I need to install sequelize globally because just running `npm install --save sequelize` doesn't create a binary entry in `node_modules/.bin`, and the only way to access it is via global installation.

What am I doing wrong here?

The code repository is this: https://github.com/luispcosta/reddit_clone
Thanks!
