### ISSUE TITLE
Hexo command can't work

### ISSUE THREAD

**Issue by aimer1124** [travis-ci/travis-ci#7176]
When i push my repo, the travis build fail. 

- Github Address: [https://github.com/aimer1124/aimer1124.github.io/tree/raw](https://github.com/aimer1124/aimer1124.github.io/tree/raw)
- My travis build: [https://travis-ci.org/aimer1124/aimer1124.github.io/builds/192951655](https://travis-ci.org/aimer1124/aimer1124.github.io/builds/192951655)
- `.travis.yml`file content:

```
language: node_js
node_js:
  - "4.4.1"

before_install:
  - git config --global push.default matching
  - git config --global user.name "aimer1124"
  - git config --global user.email "380774061@qq.com"

install:
  - npm install hexo-cli -g
  - npm install hexo --save
  - npm install
  - npm install hexo-generator-feed --save
  - npm install hexo-deployer-git --save
  - npm install hexo-renderer-ejs --save
  - npm install hexo-renderer-stylus --save
  - npm install hexo-renderer-marked --save
  - npm install hexo-renderer-sass --save

script:
  - hexo clean
  - hexo generate

after_success:
  - cd ./public
  - git init
  - git add --all .
  - git commit -m "Auto Builder From Travis"
  - git push --quiet --force https://$DEPLOY_REPO@github.com/aimer1124/aimer1124.github.io.git master

branches:
  only:
    - raw
cache:
  directories:
    - node_modules
```

<img width="616" alt="travis" src="https://cloud.githubusercontent.com/assets/5865980/22058141/dd1f9e60-dda2-11e6-9dce-aabb73687f44.png">

I have checked  hexo it was installed ok, please help me.
