### ISSUE TITLE
Allow failures for OS and env variables.

### ISSUE THREAD

**Issue by sledgehammer999** [travis-ci/travis-ci#7179]
Sorry for bothering you but I can't find a solution. I searched the docs, google and stackoverflow but there wasn't an answer specific to my question.

I am trying to allow failures when the os is osx **AND** when some env row is set. But it doesn't work. Here is the snippet of my yml
```yaml
language: cpp

os:
  - linux
  - osx
osx_image: xcode7.3

env:
  matrix:
    # Uncomment when Travis upgraded "Ubuntu 12.04 LTS" to a newer version whose repo will have a more up-to-date libtorrent package
    #- lt_branch=dist gui=true
    #- lt_branch=dist gui=false
    - lt_branch=RC_1_0 qt=5 gui=true
    - lt_branch=RC_1_0 qt=5 gui=false
    - lt_branch=RC_1_0 qt=4 gui=true
    - lt_branch=RC_1_0 qt=4 gui=false
  allow_failures:
    - os: osx
      env: lt_branch=RC_1_0 qt=4 gui=true
    - os: osx
      env: lt_branch=RC_1_0 qt=4 gui=false
  global:
    - secure: "OI9CUjj4lTb0HwwIZU5PbECU3hLlAL6KC8KsbwohG8/O3j5fLcnmDsK4Ad9us5cC39sS11Jcd1kDP2qRcCuST/glVNhLkcjKkiQerOfd5nQ/qL4JYfz/1mfP5mdpz9jHKzpLUIG+TXkbSTjP6VVmsb5KPT+3pKEdRFZB+Pu9+J8="
    - coverity_branch: coverity_scan
```

I want to allow fails for these 2 jobs:
1. osx **AND** lt_branch=RC_1_0 qt=4 gui=true
2. osx **AND** lt_branch=RC_1_0 qt=4 gui=false

What am I doing wrong?
