### ISSUE TITLE
Conditional build matrices based on tavis event type.

### ISSUE THREAD

**Issue by dlewissandy** [travis-ci/travis-ci#7181]
This issue is motivated by the desire to have fast integration builds that can be run for each pull request (e.g. running smoke tests and building only using the most recent compiler) and more exhaustive builds that run on chron jobs ( more testing and larger build matrix ).

Presently, both the cron and pull request triggered events utilize the same travis.yml file. Although it is possible to conditionally execute tests by testing the TRAVIS_EVENT_TYPE environment variable, there does not appear the necessary syntax to conditionally include/exclude the jobs in the build matrix. For example:
```
matrix:
    include:
        - os: osx
           event-type: [ chron ]
```
As an alternative to introducing additional syntax to the travis.yml file, the same objective could be achieved by allowing a user to select the yml file that they wish to execute for each chron job.

**Comment by phil-davis** [comment]
The problem with the current ways of making this work is that every job in the build matrix is always fired up. Even if it is short-circuited in some way to do "almost nothing" when it sees certain values of TRAVIS_EVENT_TYPE, it still chews up a job slot for a minute or so.
Some way to only start a subset of the build matrix based on TRAVIS_EVENT_TYPE would be great.

**Comment by untoreh** [comment]
or just `condition: ...` so e.g. jobs can be run if `$TRAVIS_TAG` has a prefix

**Comment by andy-maier** [comment]
I'm also interested in this ability, exactly as described by @dlewissandy .

**Comment by steveklabnik** [comment]
👍 , this would be very useful in the Rust world, as we could build nightly on a nightly job, beta on a weekly job, and stable all the time.

**Comment by terinjokes** [comment]
I expected to be able to do something similar to the OP, exclude a subset of the matrix when the tag is set:

```yaml
env:
  - VERSION=0.9.4
  - VERSION=0.9.5
  - […]
  - VERSION=edge

matrix:
  exclude:
    - env: VERSION=0.9.4 TRAVIS_EVENT_TAG=cron
    - env: VERSION=0.9.5 TRAVIS_EVENT_TAG=cron
```

**Comment by BanzaiMan** [comment]
While it is considered beta (some future changes are possible), our recent release of the Build Stages feature makes this possible. https://blog.travis-ci.com/2017-09-12-build-stages-order-and-conditions

In the use case of OP:

> I want to exclude "2.7" if branch names startswith "deploy", but do everything if not ("master", PRs, etc.).

One can write:

```yaml
language: python
python:
  - "3.6"
matrix:
  include:
    - os: "osx"
      if: type = cron
```
