### ISSUE TITLE
SonarQube.com will not authorize

### ISSUE THREAD

**Issue by mcred** [travis-ci/travis-ci#7182]
Based on the instructions from https://docs.travis-ci.com/user/sonarqube/, I have not been successful getting SonarQube to run. It always fails with the following error:

```
ERROR: Error during SonarQube Scanner execution
ERROR: Not authorized. Please check the properties sonar.login and sonar.password.
```

.travis.yml
```
language: php
php:
  - '7.1'
dist: trusty
install:
  - composer install
  - ant
script:
  - phpunit
addons:
  code_climate:
    repo_token: 56febcaeeb8e4a22efa0e5c8dd2ea0c824cc5c9fec32ecc6f35a1154e2d892d5
  sonarqube:
    token:
      secure: "rp6RZlfgpFzDtbZbR0a8tLqw26P2dabuhxLF968to/I4ZePO64SmWymSO0ohORQLQvjXoGJ4tg2/hS0+I+/3wWHgJFwJ54yijbDJVOvk2gEKLIubBXYS2OWKErbPcgT4qTPkK3+CmoqBN8uQwoTbBJB7GH5ub0QXpoJtaFd0AkMkZjNOUYYQGooOpNgaBHFc7mEpKQPeqq7Gt8Q1dt8cOHrPRLFtXfDvOENdReNl9mB0IzSaTcu64xYu1B1NGIaACZe/Bwk3NsTclGy1MNHtOAMUC9GiGsrE6a7jXGeI94p8f2xsicGDgWjzLm2S517xvUSIF0EeGSvxlLL9Mxna8vX7TwDAgxuqoqSvl45BCV+6A0ttVKwPXdEWDxByPToQJlR6QZtP1hfNiJxsMRQyP7ca1+PHThgamZtHu/q6UM7IjGlBE1LbtT28iQuS9mcnZDQ4UWkNW51t38x4PwkBBbWAPCFw2+ZuSVi3cOYqz1II17mKIQShHiIDDRaX5f9atN+MEbb7EFX8Jte8yXAHClyTRmzrHmtpolW9B874VYNeQjWslgXKUTjjstC5NhlMKW4qgFqnBK8w5x+HfcS7JQ+OPiZs8Jj5AOlCj3JDw0HZGbBYFqA86VOEHS/QK1xtIJZIchPLKj/No/N3pJZiTqxFdQi6HSSiZVmiGkQEvzk="
after_success:
  - vendor/bin/test-reporter
  - vendor/bin/coveralls -v
  - sonar-scanner
```

sonar-projects.properties
```
sonar.sources=./src
sonar.tests=./tests

sonar.language=php
sonar.sourceEncoding=UTF-8

# Reusing PHPUnit reports
sonar.php.coverage.reportPath=build/logs/clover.xml
sonar.php.tests.reportPath=build/logs/phpunit/index.xml
```

The documentation makes is seems this is all that is needed. I have tried alternatively adding `SONAR_TOKEN` to my repository setting, but it still can not authorize. Is there an extra step needed to ensure that my project tries to authorize with my User Authentication Token?

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by mcred** [comment]
Yes. 

https://travis-ci.org/mcred/Developer-Ipsum/jobs/193208283

**Comment by BanzaiMan** [comment]
Could you double check the value you encrypted conforms to the value Sonarqube is expecting?

**Comment by mcred** [comment]
This is likely the issue. I switch to using repo variables:
```
  sonarqube:
    token: $SONAR_TOKEN
```

And this fixed the auth issue.

**Comment by VioletGiraffe** [comment]
I started experiencing the same issue recently (noticed it yesterday). It last worked on August 9th according to Sonar Qube's web site. I have literally not changed anything in my .travis.yml nor on Sonar Qube's website, and I'm using plain-text for the "secure" attribute value.

**Comment by BanzaiMan** [comment]
> and I'm using plain text for the "secure" attribute value.

That is the problem. https://travis-ci.community/t/deploy-fails-with-aws-signaturedoesnotmatch/5835/4

**Comment by VioletGiraffe** [comment]
@BanzaiMan, thanks for replying.
I don't understand, it was suggested to use `$SONAR_TOKEN` instead, but where do I set the value of this variable?

**Comment by BanzaiMan** [comment]
@VioletGiraffe The discussion in the community forum post tells you to _drop_ the `secure` key.

```
addons:
  sonarcloud:
    organization: "violetgiraffe"
    token: $SONAR_TOKEN
```
