### ISSUE TITLE
Deploy to github releases recreates deleted tag

### ISSUE THREAD

**Issue by victorhurdugaci** [travis-ci/travis-ci#7183]
Here's how to repro it:

1. Create a github repo and integrate it with travis releases:

```
...
deploy:
  provider: releases
  api_key: ...
  file: ...
  skip_cleanup: true
  on:
    tags: true
```

2. Push everything to master
3. Create a branch from master
4. Make a change in that branch, push it, and create a PR
    Expected: PR is built by travis.
    Actual: as expected

5. Create tag "foo" from that branch
    Expected: the tag is build and a deploy takes place
    Actual: as expected

6. Delete that tag and the release from github (don't delete the brach or close the PR!)
7. Make a change in the branch, squash against master (not 100% sure squash is needed)
8. Force push the changes in the branch
    Expected: PR is built by travis
    Actual: PR is built by travis but there's another build triggered for the tag and the release + tag are recreated
