### ISSUE TITLE
Postgres pg_config binary missing

### ISSUE THREAD

**Issue by chochkov** [travis-ci/travis-ci#7209]
I'm trying to build this project `https://travis-ci.org/adjust/dumbo` which requires building a PostgreSQL extension at test-runtime. For that I need the `pg_config` binary that gets distributed with postgres. However the binary isn't there under `/usr/lib/postgresql/9.5/bin/` as I'd expect and the one found under `/usr/bin/pg_config` is from Postgres 9.6, which is useless as I can't start the 9.6. server.

Here's my config:

```yml
services:
  - postgresql

addons:
  postgresql: "9.5"

sudo: required
dist: precise
```
