### ISSUE TITLE
OSX Builds for private Repos Randomly fail to start

### ISSUE THREAD

**Issue by Vratislav** [travis-ci/travis-ci#7211]
Given this .travis.yml:

```YAML
language: objective-c
cache:
 - cocoapods
 - bundler

osx_image: xcode8.2

before_install:
    - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
    - bundle install
    - carthage bootstrap

script:
    - bundle exec fastlane ci

```

Our builds randomly fails (with a❗️instead of ❌ as the job status) to start with this message:

```
Worker information
hostname: worker-jupiter-brain:a75a07bc-6c19-446f-a130-283ddd5d0764
version: v2.6.1 https://github.com/travis-ci/worker/tree/82ed3060354f6c4bedd90a7aeaf97950193697f1
instance: 21ebfa7b-7a1a-4a3e-9576-88ca41aa0e48:travis-ci-macos10.12-xcode8.2-1481567376
startup: 2m56.936961675s


No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

When I restart the build from the Travis UI, it usually proceeds to build our commit. It seems random, maybe connected with the load on the Travis CI platform. I would say that 1 in 10 times the build fails in such way. Can we do something so that this does not happen to us so often?
