### ISSUE TITLE
Include jobs in matrix based on event

### ISSUE THREAD

**Issue by hawkrives** [travis-ci/travis-ci#7215]
I would like to include some jobs into my build matrix, dependent on the build event.

---

Some background: I've got a three-job `include` matrix, with two linux and one osx job. The thing is, the OS X job often takes more than an hour to start up, so I would like to only run it at night, via cron.

I can't just short-circuit the job in `before_install`, because my delays happen before the job boots.

---

My request, then, is that we be able to exclude or include some jobs from the matrix based on the build event type. 

Something like this, which would allow the two linux builds to run normally, on push, pr, and cron, and only run the OS X build when started from a cron job:

```yaml
matrix:
  include:
    - os: linux
      language: node_js

    - os: linux
      language: php

    - os: osx
      osx_image: xcode8.1
      build_event:
        push: false
        pull_request: false
        cron: true
```

Is there any interest in doing this, or should I try to figure out a different way of accomplishing my goal?
