### ISSUE TITLE
Any way to exit current stage and jump to the next one?

### ISSUE THREAD

**Issue by IchHabRecht** [travis-ci/travis-ci#7225]
I would like to have an early return for my build according to some env vars. I noticed I can achieve this with using travis_terminate - but unfortunately this doen't call any other stage but kills the current build. Is there any way
- to either and the stage the build is in
- or to trigger caching manually before terminating?

**Comment by BanzaiMan** [comment]
Could you elaborate on your use case? If you are running a process in your build, getting out of it in any way should move the build forward to the next phase in the build.

If you want to skip a command based on an env var, something crude is possible:

```yaml
before_script:
  - command_1 || SKIP_REST=true
  - test $SKIP_REST || command_2
  - test $SKIP_REST || command_3
  ⋮
```

When you say "trigger caching", I assume that you mean uploading of the cache archive. This is not possible at this time. It will happen at the end of the job.

**Comment by IchHabRecht** [comment]
Thanks for your answer. About my use case: I have 3 env vars COMMAND1, COMMAND2, COMMAND3 that should trigger only one command in my build and execute afterwards.  Without any env vars the other script parts should be executed. This should speed up my builds as I prevent running the same commands in my matrix when not necessary. For readability I want to prevent having multiple if statements in the code and having to care about a SKIP_TEST var and simply exit after the related command was executed.

**Comment by BanzaiMan** [comment]
How do you decide which one of `COMMAND1`, `COMMAND2`, and `COMMAND3` to run?

Whatever it is, perhaps a complete `.travis.yml` to understand the use case better.

**Comment by IchHabRecht** [comment]
Those are environment variables in my matrix

**Comment by BanzaiMan** [comment]
@IchHabRecht Could you post the entire `.travis.yml`? If you'd rather not, you can also send us email at support@travis-ci.com.

**Comment by IchHabRecht** [comment]
```yaml
language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: TYPO3=^8.0
    - php: 7.1
      env: TYPO3=^7.6
    - php: 7.0
      env: TYPO3=^8.0
    - php: 7.0
      env: TYPO3=^8.0 CODE_ANALYSIS=yes
    - php: 7.0
      env: TYPO3=^8.0 STYLE=yes
    - php: 7.0
      env: TYPO3=^7.6
    - php: 7.0
      env: TYPO3=^7.6 CODE_ANALYSIS=yes
    - php: 7.0
      env: TYPO3=^6.2 CODE_ANALYSIS=yes
    - php: 5.6
      env: TYPO3=^7.6
    - php: 5.6
      env: TYPO3=^6.2
    - php: 5.5
      env: TYPO3=^7.6
    - php: 5.5
      env: TYPO3=^6.2
    - php: 5.4
      env: TYPO3=^6.2
    - php: 5.3
      env: TYPO3=^6.2

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi

before_script:
  - composer require typo3/cms="$TYPO3"
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    if [ "$CODE_ANALYSIS" == "yes" ]; then
      travis_fold start before_phpstan;
      travis_time_start;
      echo "Running php static analysis";
      git clean -dffx;
      composer require typo3/cms="$TYPO3" phpstan/phpstan="^0.6" --ignore-platform-reqs;
      git checkout composer.json;
      travis_time_finish;
      travis_fold end before_phpstan;
      echo;
      echo;
      .Build/bin/phpstan analyse --level 5 ext_localconf.php Classes Tests;
      export TRAVIS_TEST_RESULT=$?
      travis_terminate $TRAVIS_TEST_RESULT;
    fi
  - >
    if [ "$STYLE" == "yes" ]; then
      echo "Running php-cs-fixer";
      echo;
      echo;
      .Build/bin/php-cs-fixer fix --verbose --dry-run --diff;               
      export TRAVIS_TEST_RESULT=$?
      travis_terminate $TRAVIS_TEST_RESULT;
    fi

  - >
    echo;
    echo "Running unit tests";
    echo;
    echo;
    .Build/bin/phpunit -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/UnitTests.xml Tests/Unit/;

  - >
    echo;
    echo "Running php lint";
    echo;
    echo;
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;;
```
