### ISSUE TITLE
Question on fast_finish setting

### ISSUE THREAD

**Issue by scottolsen** [travis-ci/travis-ci#7231]
I've split up our specs and cucumbers to run on 2 different build jobs and I'd like to make it so if a spec or feature fails that both builds fail right away. Is that possible with the `fast_finish` settings? 

Here is what I currently have in my `.travis.yml` file but it isn't working:

```yml
env:
  matrix:
    - TEST_SUITE=specs
    - TEST_SUITE=features
matrix:
  fast_finish: true
```

Thanks!
