### ISSUE TITLE
Cloudfoundry deployment from specific directory

### ISSUE THREAD

**Issue by jadekler** [travis-ci/travis-ci#7233]
Hello! I have a [project structure](https://github.com/pivotal-cf/pivotal-ui) like this:

```
- project
  - library
  - styleguide
  - styleguide_new
```

Both `styleguide` and `styleguide_new` get deployed... separately. Is it possible to do the following somehow:

```
deploy:
   - provider: cloudfoundry
     api: https://api.run.pivotal.io
     local_dir: styleguide
   - provider: cloudfoundry
     api: https://api.run.pivotal.io
     local_dir: styleguide_new
```

(provide a way to 'cd' into a specific dir before starting deploy)

I've considered `before_deploy`, but that would put me into only one of the two appropriate directories. :/
