### ISSUE TITLE
Not able to run npm publish with semantic release

### ISSUE THREAD

**Issue by thekalinga** [travis-ci/travis-ci#7244]
I have a js package that I'm trying to publish to npm registry using semantic release

The `build` script generates `dist` folder which is part of `.gitignore`. I am trying to `cd` into `dist` folder after the build is run & then run `npm publish`, which is failing saying

` 1: cd: can't cd to /home/travis/build/1tontech/ngx-http-interceptor/dist`

Here is my `.travis.yml`

```yml
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
after_success:
  - npm run semantic-release
deploy:
  skip_cleanup: true
branches:
  only:
    - /^angular\d+$/
```

And scripts portion on my `package.json` looks like this

```json
"scripts": {
    "clean": "npm prune && rimraf .tmp && rimraf dist",
    "transpile": "ngc",
    "package": "rollup -c",
    "minify": "./node_modules/uglify-js/bin/uglifyjs dist/bundles/x-ng2-http-interceptor.umd.js --screw-ie8 --compress --mangle --comments --output dist/bundles/x-ng2-http-interceptor.umd.min.js",
    "generateDistPackageJson": "node .scripts/generatePackageJson.js",
    "build": "npm run clean && npm run transpile && npm run package && npm run minify && npm run generateDistPackageJson",
    "commit": "git-cz",
    "semantic-release": "semantic-release pre && npm build && cd dist && npm publish && cd .. && semantic-release post"
  }
```
