### ISSUE TITLE
Java JDK 9 should be updated.

### ISSUE THREAD

**Issue by GotoFinal** [travis-ci/travis-ci#7253]
Version used on travis of JDK 9 contains compiler bug:
```
java.lang.AssertionError
	at jdk.compiler/com.sun.tools.javac.comp.LambdaToMethod.setVarargsIfNeeded(LambdaToMethod.java:795)
	at jdk.compiler/com.sun.tools.javac.comp.LambdaToMethod.access$1900(LambdaToMethod.java:81)
	at jdk.compiler/com.sun.tools.javac.comp.LambdaToMethod$MemberReferenceToLambda.expressionInvoke(LambdaToMethod.java:971)
	at jdk.compiler/com.sun.tools.javac.comp.LambdaToMethod$MemberReferenceToLambda.lambda(LambdaToMethod.java:845)
```
It isn't present in newest version (build 153).

Java bug report: http://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8171993
It is still unresolved here for some reason, but I added it by myself and it was fixed in one of next builds after 149.

**Comment by BanzaiMan** [comment]
This is a variant of #3259, so the configs shown in https://github.com/travis-ci/travis-ci/issues/3259#issuecomment-93881360 should work while we wait for the build images to be updated.

```yaml
language: java
sudo: false
dist: trusty
jdk: oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer
```
