### ISSUE TITLE
"docker: unrecognized service" on precise+sudo matrix build

### ISSUE THREAD

**Issue by jdub** [travis-ci/travis-ci#7256]
Relevant [`.travis.yml`](https://github.com/jdub/smash-docker-mysql/blob/380f883b8673653ff6027ca7acdcaac87b9c6697/.travis.yml) snippet:

```yaml
matrix:
  include:
    - sudo: required
      dist: precise
      env:
        ENV: precise-vm

services:
  - docker
```

These parameters are reflected in the [build configuration](https://travis-ci.org/jdub/smash-docker-mysql/jobs/197611416/config), and here's the resulting [build failure](https://travis-ci.org/jdub/smash-docker-mysql/jobs/197611416).

I'm certain I've used the Docker daemons with precise+sudo before, without being an arm of a matrix build.
