### ISSUE TITLE
docker: unrecognized service

### ISSUE THREAD

**Issue by guyskk** [travis-ci/travis-ci#7269]
https://travis-ci.org/opticspy/lightpipes/jobs/198312267

> build-linux-x64.sh: line 3: docker: command not found

Here is .travis.yml:
```
sudo: required

language: python

services:
  - docker

matrix:
  include:
    - env: TARGET=linux-x32
    - env: TARGET=linux-x64

script:
- "bash build-${TARGET}.sh"
```

It seems fail after I add matrix, but I don't know why it fail, how to solve the problem?

**Comment by BanzaiMan** [comment]
Looks like a duplicate of #7177.

**Comment by guyskk** [comment]
@BanzaiMan It works after I remove matrix:

```yaml
sudo: required

language: python

services:
  - docker

cache:
  directories:
    - .cache/pip

# matrix:
#   include:
#     - env: TARGET=linux-x32
#     - env: TARGET=linux-x64

script:
  # - "bash build-${TARGET}.sh"
  - "bash build-linux-x64.sh"
```
https://travis-ci.org/opticspy/lightpipes/builds/198497012

**Comment by guyskk** [comment]
@BanzaiMan It also works by this:
```yaml
sudo: required

language: python

services:
  - docker

cache:
  directories:
    - .cache/pip

env:
  - TARGET=linux-x32
  - TARGET=linux-x64

script:
  - "bash build-${TARGET}.sh"
```
https://travis-ci.org/opticspy/lightpipes/builds/198502416
