### ISSUE TITLE
Build matrix creates invalid PHP builds as phpenv global [7.0, 7.1, "nightly"]

### ISSUE THREAD

**Issue by photodude** [travis-ci/travis-ci#7283]
Build matrix creates invalid PHP builds.  results in phpenv global [7.0, 7.1, "nightly"] rather than a single php version. see this build https://travis-ci.org/photodude/dbal/jobs/198937522

Goal is to have a simpler martix, with conditional addon and service start. If there is a better way to do this please let me know. 

### Travis YML
```yml
language: php

sudo: false

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

php:
  - 7.0
  - 7.1
  - nightly

env:
  - DB=sqlite
  - DB=mysql
  - DB=mysqli

matrix:
  fast_finish: true
  include:
    - env: DB=mariadb MARIADB_VERSION=10.0
      addons:
        mariadb: 10.0
    - env: DB=mariadb MARIADB_VERSION=10.1
      addons:
        mariadb: 10.1
    - env: DB=pgsql POSTGRESQL_VERSION=9.2
      addons:
        postgresql: "9.2"
      services:
        - postgresql
    - env: DB=pgsql POSTGRESQL_VERSION=9.3
      addons:
        postgresql: "9.3"
      services:
        - postgresql
    - env: DB=pgsql POSTGRESQL_VERSION=9.4
      addons:
        postgresql: "9.4"
      services:
        - postgresql
    - env: DB=pgsql POSTGRESQL_VERSION=9.5
      addons:
        postgresql: "9.5"
      services:
        - postgresql
    - env: DB=pgsql POSTGRESQL_VERSION=9.6
      addons:
        postgresql: "9.6"
      services:
        - postgresql
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge # until the next Trusty update
      addons:
        mariadb: 10.0
      env: DB=mariadb MARIADB_VERSION=10.0

    - php: hhvm
      sudo: true
      dist: trusty
      group: edge # until the next Trusty update
      addons:
        mariadb: 10.1
      env: DB=mariadb MARIADB_VERSION=10.1

    - php: hhvm
      sudo: true
      dist: trusty
      group: edge # until the next update
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
      services:
        - mysql
      env: DB=mysql
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge # until the next update
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
      services:
        - mysql
      env: DB=mysqli
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge # until the next update
      addons:
        postgresql: "9.2"
      services:
        - postgresql
      env: DB=pgsql POSTGRESQL_VERSION=9.2
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge # until the next update
      addons:
        postgresql: "9.3"
      services:
        - postgresql
      env: DB=pgsql POSTGRESQL_VERSION=9.3
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge # until the next update
      addons:
        postgresql: "9.4"
      services:
        - postgresql
      env: DB=pgsql POSTGRESQL_VERSION=9.4
    - php: hhvm
      sudo: true
      dist: trusty
      addons:
        postgresql: "9.5"
      services:
        - postgresql
      env: DB=pgsql POSTGRESQL_VERSION=9.5
    - php: hhvm
      sudo: true
      dist: trusty
      addons:
        postgresql: "9.6"
      services:
        - postgresql
      env: DB=pgsql POSTGRESQL_VERSION=9.6
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge # until the next update
      env: DB=sqlite
  allow_failures:
    - php: hhvm
    - php: nightly
      env: DB=pgsql POSTGRESQL_VERSION=9.5
    - php: 7.0
      env: DB=pgsql POSTGRESQL_VERSION=9.5
    - php: 7.1
      env: DB=pgsql POSTGRESQL_VERSION=9.5
    - php: nightly
      env: DB=pgsql POSTGRESQL_VERSION=9.6
    - php: 7.0
      env: DB=pgsql POSTGRESQL_VERSION=9.6
    - php: 7.1
      env: DB=pgsql POSTGRESQL_VERSION=9.6

before_install:
  # Force hhvm PHP 7 mode
  - if [[ $TRAVIS_PHP_VERSION = hhv* ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi

install:
  - travis_retry composer install

before_script:
  - if [ '$DB' = 'pgsql' ]; then sudo service postgresql stop; sudo service postgresql start $POSTGRESQL_VERSION; fi

script: ./vendor/bin/phpunit --configuration tests/travis/$DB.travis.xml
```

**Comment by BanzaiMan** [comment]
This is basically a duplicate of #4681. You need to specify the `php` version in each of the jobs defined in `matrix.include`.

**Comment by photodude** [comment]
@BanzaiMan what I really am after is something like the following

```yml
language: php

sudo: false

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

php:
  - 7.0
  - 7.1
  - nightly

env:
  - DB=sqlite
  - DB=mysql
  - DB=mysqli
  - DB=mariadb MARIADB_VERSION=10.0
  - DB=mariadb MARIADB_VERSION=10.1
  - DB=pgsql POSTGRESQL_VERSION=9.2
  - DB=pgsql POSTGRESQL_VERSION=9.3
  - DB=pgsql POSTGRESQL_VERSION=9.4
  - DB=pgsql POSTGRESQL_VERSION=9.5
  - DB=pgsql POSTGRESQL_VERSION=9.6

addons:
  - if [ '$DB' = 'mariadb' ]; then mariadb: $MARIADB_VERSION; fi
  - if [ '$DB' = 'pgsql' ]; then postgresql: $POSTGRESQL_VERSION; fi
```
