### ISSUE TITLE
Are composer global packages installed correctly?

### ISSUE THREAD

**Issue by natanmoraes** [travis-ci/travis-ci#7289]
When I run `composer global require drupal/coder`, the vendor files are installed in `~/.config/composer`.

See build screenshot:

![screenshot from 2017-02-07 14 40 20](https://cloud.githubusercontent.com/assets/2085556/22704400/ba865b08-ed4e-11e6-9366-45db4b52be8e.png)

I was expecting they would be installed under `~/.composer`.

Is this by design?

My .travis.yml file:
```yml
language: php
sudo: required
dist: trusty

php:
  - 5.6

install:
  # Remove xdebug to make composer faster.
  - phpenv config-rm xdebug.ini
  # add composer's global bin directory to the path
  # see: https://github.com/drush-ops/drush#install---composer
  - export PATH="$HOME/.config/composer/vendor/bin:$PATH"

  # Install PHP_CodeSniffer and Drupal config
  - composer global require drupal/coder
  - phpcs --config-set installed_paths ~/.config/composer/vendor/drupal/coder/coder_sniffer

before_script:
  # This slows things down but it ensures all remote branches are fetched.
  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
  - git fetch --unshallow
  - git fetch origin

script: ./scripts/travis-build.sh
```
