### ISSUE TITLE
Unable to deploy build wheel to artifactory

### ISSUE THREAD

**Issue by rajashekhar1121** [travis-ci/travis-ci#7298]
```yaml
language: python
python:
  - "2.7.3"
install: 
  - pip install -U --force-reinstall .
  - pip install -U --force-reinstall -r test-requirements.txt
before_script: 
  - nosetests tests
  - tox -e pep8
script:
  - virtualenv buildwheel
  - . buildwheel/bin/activate
  - pip install -U pip wheel requests[security]
  - python setup.py bdist_wheel
  - pip wheel --wheel-dir=wheelhouse .
  - deactivate
deploy:
    provider: pypi
    user: xxxxxx
    password: xxxxxx
    server: https://xxxx-xxxx-xxxx-pypi-local/
    distributions: "bdist_wheel" 
```
