### ISSUE TITLE
Skipping a deployment with the s3 provider because this branch is not permitted

### ISSUE THREAD

**Issue by cashman04** [travis-ci/travis-ci#7300]
This has been asked before, but I don't see a clear answer anywhere on what the problem is.   Example build is [here](https://travis-ci.org/fort-kickass/searchlist.org/builds/200167412).

I have different buckets for different branches, but for some reason it only works on the master branch.  Any others and it throws this "branch is not permitted" error. How can I get around this? Is it a bug?

**Comment by BanzaiMan** [comment]
By default, deployment is restricted to the `master` branch. If you want it happen elsewhere, you'd need to specify this. See https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A

**Comment by domenkozar** [comment]
It would be super useful for error message to link there or explain that by default just master is allowed.

**Comment by solvingJ** [comment]
This is happening to me on master branch:

https://travis-ci.org/solvingJ/go-github-release-test/jobs/249031151

>  git clone --depth=50 --branch=master https://github.com/solvingJ/go-github-release-test.git 

> Skipping a deployment with the bintray provider because this branch is not permitted

**Comment by ademidun** [comment]
This is what I tried:

```yml
deploy:
  provider: s3
  access_key_id: $aws_access_key_id
  secret_access_key: $secret_access_key
  bucket: "demo.atila.ca"
  skip_cleanup: true
  local_dir: build
  on:
    all_branches: true
```
see: https://docs.travis-ci.com/user/deployment#conditional-releases-with-on
