### ISSUE TITLE
Different setting for sudo in one travis file

### ISSUE THREAD

**Issue by zjffdu** [travis-ci/travis-ci#7307]
Sorry first if this is not the right place to ask question. I didn't find other places for asking travis question. My travis has a build matrix, and I want some build to use docker based for performance speed up and some build use sudo-enabled for more memory. Is there any way to set different setting for one travis file ? Thanks

**Comment by BanzaiMan** [comment]
You could add a job with `sudo` overridden and add it via `matrix.include`. For example:

```yaml
language: python
sudo: false
matrix:
  include:
    - sudo: required
⋮
```
