### ISSUE TITLE
Chromedriver issue:

### ISSUE THREAD

**Issue by reach2jeyan** [travis-ci/travis-ci#7317]
I am trying to run my cucumber tests in travis using chrome. But I get the following error

```
unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"4892.1","isDefault":true},"id":1,"name":"","origin":"://"}
        (Session info: chrome=56.0.2924.87)
        (Driver info: chromedriver=2.7.236843,platform=Linux 4.4.0-51-generic x86_64) (Selenium::WebDriver::Error::UnknownError)
```

```

My `.travis.yml` looks like

sudo: required
language: ruby
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable


script: bundle exec cucumber


before_script:
        - bundle install
        - gem install watir
        - gem install colorize
        - gem install rspec
        - gem install cucumber
        - gem install rake
        - gem install chromium
        - wget http://chromedriver.storage.googleapis.com/2.7/chromedriver_linux64.zip
        - unzip chromedriver_linux64.zip
        - sudo apt-get install libnss3
        - sudo apt-get --only-upgrade install google-chrome-stable
        - sudo cp chromedriver /usr/local/bin/.
        - sudo chmod +x /usr/local/bin/chromedriver
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3


branches:
  only:
    - master

notifications:
  email:
    - iamsmj@gmail.com
```
