### ISSUE TITLE
Packages not caching despite `cache: packages` being set

### ISSUE THREAD

**Issue by philmikejones** [travis-ci/travis-ci#7321]
@jimhester @craigcitro

Issue below based on this [twitter conversation](https://twitter.com/jimhester_/status/831885195431256064)

My Travis builds are taking a long time (>20 minutes) for a build that should only take 3 or 4 minutes.
In trying to find the source of the issue I've noticed that packages are being installed each time I run a build.

My `.travis.yml` looks like this:

```
sudo: required
dist: trusty

language: r

cache: packages
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - libv8-dev

notifications:
  on_success: change
  on_failure: change

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov(token = "[key-here]")'
```

The addon packages are largely for spatial libraries (rgdal, etc).

I've attached the log file. It's a private repository but I'm happy to add you if there's something else you need to see; just tell me what you need.

Do you have any suggestions why the packages aren't caching? Thanks.
[hrsim-travis-log.txt](https://github.com/travis-ci/travis-ci/files/777519/hrsim-travis-log.txt)
