### ISSUE TITLE
Filter notifications to master branch only

### ISSUE THREAD

**Issue by sankethkatta** [travis-ci/travis-ci#7336]
We use a common pattern of locking down our master branches (which represent production). We develop on other branches which consistently have failures as they are being developed on. Having notifications repo-wide adds way too much noise for them to be useful.

Something like the syntax of deployment's [conditional releases][1] would be nice:
```yaml
notifications:
  slack:
    rooms:
      - <account>:<token>#development
  on:
    branch: master
```
This is a duplicate of #1405, however that thread was locked to contributors in 2014 with no resolution.

Any thoughts on whether this would be a feature Travis plans on supporting?

[1]: https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A
