### ISSUE TITLE
Upgrade OpenJDK 8 to 8u121

### ISSUE THREAD

**Issue by nirvdrum** [travis-ci/travis-ci#7337]
It would be very helpful if the OpenJDK packages could be upgrade to 8u121. In addition to the normal set of security updates and new features, it's a requirement for using the latest version of the Graal compiler with Java 8.

**Comment by BanzaiMan** [comment]
This is a variant of #3259, so the configs shown in https://github.com/travis-ci/travis-ci/issues/3259#issuecomment-93881360 should work while we wait for the build images to be updated.

**Comment by BanzaiMan** [comment]
OpenJDK update has to wait until our APT source is updated: https://launchpad.net/~openjdk-r/+archive/ubuntu/ppa

**Comment by BanzaiMan** [comment]
For non-java builds, just using this should switch JDK to Java 8:

```yaml
addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default
```

https://travis-ci.org/BanzaiMan/travis_production_test/builds/209809966#L276
