### ISSUE TITLE
Compiler in matrix include is being combined rather than replacing

### ISSUE THREAD

**Issue by sitsofe** [travis-ci/travis-ci#7358]
Description of the problem
Sometimes travis combines compilers rather than using one at a time.

Steps to reproduce:
1. Clone the repo https://github.com/sitsofe/travis-test.git which has the following .travis.yml
```
language: c
os:
  - linux
compiler:
  - clang
  - gcc
matrix:
  include:
    - os: osx
      osx_image: xcode8.2
  exclude:
    - os: osx
      compiler: gcc
```
2. Do a push that kicks off a travis build.

Expected results
Three builds to be done (1 Linux clang, 1 Linux gcc, 1 OSX clang with xcode8.2 settings)

Actual result
Three builds are done but one has a strange non-nonsensical compiler (1 Linux clang, 1 Linux gcc, 1 OSX gcc,clang with xcode8.2 settings)

How reproducible is the issue?
Reproducible every time.
