### ISSUE TITLE
Update Fastlane for Deploy

### ISSUE THREAD

**Issue by dcordero** [travis-ci/travis-ci#7361]
With this configuration:

```
[...]
language: objective-c
osx_image: xcode8.2

before_install:
  - gem update --system
  - gem install fastlane --no-rdoc --no-ri --no-document --quiet
install: true
script:
  - fastlane test
[...]
```

Travis is, as expected, using the latests version of Fastlane to run the tests. Currently 2.18.1

On the other hand:
```
[...]
language: objective-c
osx_image: xcode8.2

before_deploy:
  - gem update fastlane
deploy:
  skip_cleanup: true
  provider: script
  script:
    - fastlane deploy
  on:
    branch: whatever
[...]
```

Uses an old version of Fastlane in the deploy script, exactly the version 1.111.0.

I can see in the traces that `before_deploy` is executed successfully, and it installs 2.18.1. But once the script is executed the available version of Fastlane is 1.111.0 instead.

I very simple project reproducing the problem can be found here:
https://github.com/dcordero/Travis-Issue-7361

**Comment by BanzaiMan** [comment]
I believe the issue is described here: https://docs.travis-ci.com/user/deployment/script#Deployment-is-executed-by-Ruby-1.9.3

**Comment by dcordero** [comment]
Thanks @BanzaiMan, using `rvm $TRAVIS_RUBY_VERSION` I am indeed able to get the expected Fastlane version.

**Comment by RafaelPlantard** [comment]
@dcordero How I should use it?

**Comment by dcordero** [comment]
@RafaelPlantard just adding `rvm $TRAVIS_RUBY_VERSION do` to your fastlane command

Using the previous example used to report  the issue it would be:

```
[...]
language: objective-c
osx_image: xcode8.2

before_deploy:
  - gem update fastlane
deploy:
  skip_cleanup: true
  provider: script
  script: rvm $TRAVIS_RUBY_VERSION do fastlane deploy
  on:
    branch: whatever
[...]
```
