### ISSUE TITLE
Build react-native project in multi OS environment with Travis-CI

### ISSUE THREAD

**Issue by ganjarpanji** [travis-ci/travis-ci#7371]
Currently our RN project contains 2 native projec = Android and iOS, we are planning to run autobuild in travis for each of these natives project if there are any pushes (commits in the native side).

Q: is it possible to set up all of the dependencies, like Android SDK,Xcode etc in one travis.yml file?

i already read the documentation here https://docs.travis-ci.com/user/multi-os/ but i still confused.

should i specify condition like `if [[ "$TRAVIS_OS_NAME" == "osx" ]];` everytime i want to install any dependencies in OSX? 
for instance `if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then carthage update ; fi ` which for updating carthage. 

any similiar project with travis.yml config sample will be so much appreciated. Thanks!

**Comment by duddu** [comment]
The docs suggest to put all the os-related logic (tha various `if`) into an external script, so you don't need to "soil" the the .travis.yml.
Anyway, if you don't like it, you can always abuse the `matrix` and specify different phases for different os (note that this is not standard and the yaml linter will hate you - but it's cool):
```
matrix:
  include:
    - language: android
      os: linux
      jdk: oraclejdk7
      android:
        components:
          - android-21
          - ...
      before_install:
         - whatever
    - language: objective-c
      os: osx
      osx_image: xcode7.3
      before_install:
         - carthage update
```
