### ISSUE TITLE
Can't create 1-1 mandate pass and allow failure matrix

### ISSUE THREAD

**Issue by VoR0220** [travis-ci/travis-ci#7373]
I'm currently trying to set up something for my go environment that will allow me to run one job that is mandated to pass (a docker machine implementation) and allow failure for a native docker implementation. My current file looks something like this:

```yaml
os: osx

language: go

env:
  global:
    - TEST_ON_MACOSX=true
    - MACHINE_NAME="eris-test-osx-$TRAVIS_BUILD_ID"
matrix:
  allow_failures:
    #Native Docker job, expect potential failures as it's still fresh
    - env:
        - DOCKER_NATIVE=true
  include:
    #Docker machine job, expect this to pass
    - go: 1.7.3
      env:
        - DOCKER_MACHINE=true
      after_script: 
        - tests/dm_cleanup.sh
        #Native Docker job, expect potential failures as it's still fresh
    - go: 1.7.3
      env:
        - DOCKER_NATIVE=true


install:
  - brew update
  - brew install jq
  - brew install caskroom/cask/brew-cask
  - test "$DOCKER_MACHINE" = true && brew install docker docker-machine || brew cask install docker
  - docker --version
  - go install ./cmd/eris

script:
  - ./tests/test.sh
```

This currently creates 3 jobs (I want 2). I can't seem to get it to make 1 job that is mandated to pass (the DOCKER_MACHINE env one), and one that is allowed to fail (the NATIVE_DOCKER env one). Any suggestions or things I'm doing wrong here?

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by VoR0220** [comment]
I do! Here it is right here: https://travis-ci.org/eris-ltd/eris/builds/205554952

**Comment by BanzaiMan** [comment]
Looks like a duplicate of #4681. Your build includes a default Go job. From your description, you'd need something like:

```yaml
os: osx

language: go

go: 1.7.3

env:
  matrix:
    - DOCKER_NATIVE=true
  global:
    - TEST_ON_MACOSX=true
    - MACHINE_NAME="eris-test-osx-$TRAVIS_BUILD_ID"
matrix:
  allow_failures:
    #Native Docker job, expect potential failures as it's still fresh
    - env:
        - DOCKER_NATIVE=true
  include:
    #Docker machine job, expect this to pass
    - go: 1.7.3
      env:
        - DOCKER_MACHINE=true
      after_script: 
        - tests/dm_cleanup.sh
```

**Comment by VoR0220** [comment]
Well...that leaves me with a matrix that looks like this: https://travis-ci.org/eris-ltd/eris/builds/206011717

It's missing the "allowed failures" field.

**Comment by BanzaiMan** [comment]
`allowed_failures` job needs the `go` key, since it's not the default value.

**Comment by VoR0220** [comment]
@BanzaiMan so something like 

```
go: 1.7.3
```

?

**Comment by BanzaiMan** [comment]
The top level `go: 1.7.3` should remain.

**Comment by VoR0220** [comment]
got it. Let me try that.

**Comment by VoR0220** [comment]
:/ still getting this: https://travis-ci.org/eris-ltd/eris/builds/206254500

**Comment by BanzaiMan** [comment]
Sorry about the back-and-forth. I figured this out. The correct config looks like this:

```yaml
os: osx

language: go

go: 1.7.3

env:
  matrix:
    - DOCKER_NATIVE=true
  global:
    - TEST_ON_MACOSX=true
    - MACHINE_NAME="eris-test-osx-$TRAVIS_BUILD_ID"
matrix:
  allow_failures:
    #Native Docker job, expect potential failures as it's still fresh
    - go: 1.7.3 # this is not necessary, as it turns out
      env: DOCKER_NATIVE=true
  include:
    #Docker machine job, expect this to pass
    - go: 1.7.3
      env:
        - DOCKER_MACHINE=true
      after_script: 
        - tests/dm_cleanup.sh
```

The key is that, in the job in `matrix.allow_failures`, the `env` value should be a scalar, since that's what each job gets in the configuration.
