### ISSUE TITLE
Add condition before install android depedencies like `before-components` ?

### ISSUE THREAD

**Issue by ganjarpanji** [travis-ci/travis-ci#7381]
currently i have condition for autobuild which not always bulding the project for android language, other flow is only just run .JS bundler whiches no need to install android component dependencies.
**so we could just make the build times shorter.**

is there anyway to add some conditions before triggering to install android components ?

thanks!

**Comment by BanzaiMan** [comment]
Split the tests into two or more jobs, and specify `language: node_js` (or another suitable language) with `matrix.include`. For example:

```yaml
language: android
android:
  components:
    - build-tools-24.0.2
    ⋮ # android build confi
matrix:
  include:
    - language: node_js
      node_js: 7
      ⋮ # node_js build config
```

**Comment by ganjarpanji** [comment]
matrix use to run 2 job parallel, but id rather to run one job which could run android+JS(install components) or JS only(without android components).

matrix is not the answer i think, its redudant

**Comment by BanzaiMan** [comment]
It is not clear to me what you mean by "run 2 jobs in parallel" without a build matrix. Do you want to run two processes in the same build?

**Comment by ganjarpanji** [comment]
correct! i want to trigger only one job but it has two processes without matrix involved. matrix take resources

**Comment by BanzaiMan** [comment]
The Android image has `nvm` pre-installed, so you can install the version of Node.js you want with it.

```yaml
language: android
android:
  components:
    ⋮
before_install:
  - nvm install 7
    ⋮
```
