### ISSUE TITLE
Nunit Parallel Execution

### ISSUE THREAD

**Issue by spottlacheru** [travis-ci/travis-ci#7391]
Is there a way to execute Nunit Scripts Parallel from Travis?

As of now I can execute Nunit scripts Parallel on Browser Stack, but when I run the same scripts from Travis, test are executed sequentially. 

here is my yml config.

```yaml
language: csharp
solution: "Test.Automation.sln"
script: 
- xbuild /p:Configuration=DebugBSMobile Test.Automation.sln
before_install:
  - sudo apt-get install nunit-console
addons:
  browserstack:
    username: "xxxxxxx"
    access_key: "xxxxxxxxxxxx"
    matrix:
after_script: 
  - nunit-console Test.Automation.FunctionalTest/bin/DebugBSMobile/Test.Automation.FunctionalTest.dll
```

Appreciate any help.
@joshua-anderson @akoeplinger @nterry
