### ISSUE TITLE
[support request] 

### ISSUE THREAD

**Issue by stefan-niedermann** [travis-ci/travis-ci#7425]
The [nextcloud notes client for android](https://github.com/stefan-niedermann/nextcloud-notes/tree/travis-ci) can successfully be built on my local machine. I wanted to integrate Travis CI. Sadly i'm not able to get managed this even after [many many tries](https://github.com/stefan-niedermann/nextcloud-notes/pull/188).
Can anyone please help and explain what i am doing wrong?

---

[Console output](https://travis-ci.org/stefan-niedermann/nextcloud-notes/builds/207920481):

```
Valid ABIs: no ABIs.

Error: Invalid --abi armeabi-v7a for the selected target.

The command "echo no | android create avd --force -n test -t android-25 --abi armeabi-v7a" failed and exited with 1 during .

Your build has been stopped.
```
---

[yml-file](https://github.com/stefan-niedermann/nextcloud-notes/blob/travis-ci/.travis.yml):

```yml
sudo: false

language: android

jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.1
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-supportsys
    - sys-img-armeabi-v7a-android-25
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - '.+'

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-25 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
- adb shell input keyevent 82 &
```

**Comment by bgeVam** [comment]
i can confirm this issue. did you find a solution yet?

**Comment by stefan-niedermann** [comment]
The built itself does run now, you can have a look at the repository i linked above. so for me this issue can be closed. If @bgeVam still has this problem, feel free to keep it open.

**Comment by fractalwrench** [comment]
I can also confirm this issue. I've included my YML file below, and a link to a StackOverflow post I've created which has some additional details.

The build seems to pass on all other API levels that I've tried, apart from API 25. I'd be grateful for any pointers on whether this is down to user error, or whether it's a bug.

https://stackoverflow.com/questions/45100298

```
language: android

android:
  components:
    - tools
    - platform-tools
    - tools # appears twice as per Travis docs
    - build-tools-23.0.1
    - build-tools-25.0.2
    - android-4
    - android-10
    - android-19
    - android-23
    - android-25
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-25

env:
  matrix:
    - ANDROID_TARGET=android-4 ANDROID_ABI=armeabi
    - ANDROID_TARGET=android-10 ANDROID_ABI=armeabi
    - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-25 ANDROID_ABI=armeabi-v7a

before_script:
  # Create and start emulator
  - android list targets
  - jdk_switcher use oraclejdk8
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - while [[ `adb shell pm path android` == 'Error'* ]]; do sleep 2; done
  - adb shell input keyevent 82 &

script: ./gradlew --info connectedAndroidTest

sudo: false
```
