### ISSUE TITLE
Hipchat: no user notifications

### ISSUE THREAD

**Issue by fernandoaleman** [travis-ci/travis-ci#7438]
I am new to travis-ci and after creating my `.travis.yml` file (below), when I push a commit up to GitHub, I get the notification in the HipChat room, but it won't trigger the user notification. I've tested the HipChat API using curl in a shell script and it worked there. Am I perhaps putting the `notifications` in the wrong place in the `.travis.yml` file?

I am using the 40 character length API key from the room, so it is using HipChat API v2.

I am on a 2016 MacBook Pro touchbar with MacOS Sierra 10.12.3.

Any help would be appreciated.

```yaml
notifications:
  hipchat:
    rooms:
      - XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX@travis-ci
    notify: true

sudo: required

env:
  DOCKER_COMPOSE_VERSION: 1.11.1

language: ruby
ruby:
  - 2.2.1

services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - docker-compose build
  - docker-compose up -d

script:
  - docker-compose exec demo bundle exec ruby test.rb
  - docker-compose exec demo bundle exec ruby check.rb
```
