### ISSUE TITLE
Problems with npm

### ISSUE THREAD

**Issue by nvdv** [travis-ci/travis-ci#7440]
Hi, my builds started to fail a few weeks ago, but I haven't made any changes to `.travis.yml`
```yml
sudo: required
dist: trusty
language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

addons:
  apt:
    packages:
      - npm

before_install:
    - nvm install node

install:
  - python setup.py deps_install

script:
  - python setup.py lint
  - python setup.py test
  - python setup.py e2e_test
```
Here are build logs: https://travis-ci.org/nvdv/vprof/jobs/209323341
