### ISSUE TITLE
Deploying to S3 prior to Lambda causes Travis to try Create Function rather than Update

### ISSUE THREAD

**Issue by chrislewisdev** [travis-ci/travis-ci#7461]
We have a Travis build that, in addition to deploying a .NET Core build to an existing Lambda, also archives the build package onto S3.

Since the role of Travis in our infrastructure is to *update* the Lambda and not to create any, the AWS credentials that Travis uses do not have permission for the lambda:CreateFunction action.

We noticed while adding in the S3 deploy that, if we place the S3 deploy *before* the Lambda deploy, the Lambda deploy will fail with the following error:

```
/home/travis/.rvm/gems/ruby-2.2.5/gems/aws-sdk-core-2.8.6/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': User: arn:aws:iam::XXXXX is not authorized to perform: lambda:CreateFunction on resource: arn:aws:lambda:ap-southeast-2:XXXXXX(Aws::Lambda::Errors::AccessDeniedException)
```

If we place the S3 deploy *after* the Lambda deploy, it works fine.

To my understanding, the sequencing of Travis deploys is not supposed to have any impact whatsoever, so I can only imagine this is a bug.

E.g. the following build structure fails due to attempting to Create the Lambda function:
```yaml
language: csharp
sudo: required
dist: trusty

before_install:
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get install -y dotnet-dev-1.0.0-preview2-003156

script:
  - ./build.sh

deploy:
- provider: s3
  bucket: XXXXXX
  region: ap-southeast-2
  local_dir: XXXXXX
  upload-dir: XXXXXX
  skip_cleanup: true
  access_key_id: 
    secure: XXXXXX
  secret_access_key: 
    secure: XXXXXX

- provider: lambda
  edge:
    branch: v1.8.29
  function_name: XXXXXX
  role: XXXXXX
  handler_name: XXXXXX
  access_key_id: 
    secure: XXXXXX
  secret_access_key: 
    secure: XXXXXX
  zip: XXXXXX
  region: ap-southeast-2
  runtime: dotnetcore1.0
  timeout: 60
  module_name: XXXXXX
```

If we swap around the S3/Lambda blocks, everything works fine.
