### ISSUE TITLE
Rackspace CloudFiles deployment failing 

### ISSUE THREAD

**Issue by JamesFrost** [travis-ci/travis-ci#7478]
I have the following in my .travis.yml:

```yml
language: node_js
node_js:
- '6'
before_install:
- npm install -g gulp
- npm install -g bower
install:
- npm install --silent
- bower install --silent
- gulp sass
- gulp js --prod
script: true
deploy:
  - provider: cloudfiles
    username: "$RS_USERNAME"
    api_key: "$RS_API_KEY"
    region: "LON"
    container: "test-site-staging"
    skip_cleanup: true
    on:
      branch: master
  - provider: cloudfiles
    username: "$RS_USERNAME"
    api_key: "$RS_API_KEY"
    region: "LON"
    container: "test-site"
    skip_cleanup: true
    on:
      tags: true
```
Travis is **successfully** updating the contents of the CloudFiles container. However, the Travis task is failing with:

```bash
Deploying application
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```
As the contents of the CloudFile container have been updated, I would expect the Travis build to pass.

The build is private. The CloudFiles container is used to host a static website.

I don't think `travis_wait` would be appropriate in this situation.
