### ISSUE TITLE
jwt SAUCE_ACCESS_KEY is not available to PRs

### ISSUE THREAD

**Issue by tinayuangao** [travis-ci/travis-ci#7479]
Related to https://github.com/travis-ci/travis-ci/issues/7223
Not sure it is a bug or intended behavior. 

**Steps I used**: 
`travis encrypt SAUCE_ACCESS_KEY="some-secret-key"`
Get output and add it to `addons: jwt:` section
```
addons:
  jwt:
     secure: "output-from-encrypt-sauce"
```
Create a PR and try to use `SAUCE_ACCESS_KEY`

**Result**: 
Using the same command, the jwt encrypted variable `SAUCE_ACCESS_KEY` is available for my test repo(of my own) but is not working for another repo(under other username). 
There's no error message and no `Initializing JWT` output on console. 

**Questions**
Is there any restriction on who can use `addons.jwt`? Does the user have to be the owner of the repo? 
Is there any way to debug and check why `addons.jwt` is not triggered?

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by tinayuangao** [comment]
The URL is https://travis-ci.org/angular/material2/jobs/211858969

The `TRAVIS_SECURE_ENV_VARS` is false and `SAUCE_ACCESS_KEY` is empty.

**Comment by BanzaiMan** [comment]
We do not decrypt `jwt` addon without the accompanying `sauce_connect`. The addon is not designed to be standalone. https://github.com/angular/material2/blob/b9df5be1b6677d0696052017316bb85e46810ffe/.travis.yml#L7-L11

**Comment by tinayuangao** [comment]
Also tried using `sauce_connect` in `addons` but it still failed: 
Tried with 
```
addons:
  sauce_connect:
     username: sauce_username
  jwt:
     secure: "output-from-encrypt-sauce"
```
https://travis-ci.org/angular/material2/jobs/211903009

Also tried with 
```
addons:
  sauce_connect: true
  jwt:
     secure: "output-from-encrypt-sauce"
env:
  SAUCE_USERNAME: sauce_username
```
Also failed:
https://travis-ci.org/angular/material2/jobs/211900991

The one that works is:
https://travis-ci.org/tinayuangao/test/builds/211860023
I didn't add `sauce_connect` in the `.travis.yml` file, but the `SAUCE_ACCESS_KEY` is available.
