### ISSUE TITLE
Webhook notification configuration doesn't support environment variables

### ISSUE THREAD

**Issue by jacobtomlinson** [travis-ci/travis-ci#7486]
I've found that I'm unable to use environment variables when configuring webhook notifications. 

### Works
```yaml
notifications:
  webhooks:
    - http://www.example.com/my/webhook
```

### Doesn't work
```yaml
notifications:
  webhooks:
    - $MY_WEBHOOK_URL  # Set in repo settings on travis-ci.org
```

**Comment by BanzaiMan** [comment]
As it stands right now, the notifications are configured at the onset of the build. Therefore, the values defined during the build are not available.

We may revisit this implementation in the future, but for now, this is not possible.

There have been similar issues opened in the past; e.g., #2711.

**Comment by jacobtomlinson** [comment]
Thanks for the clarification @BanzaiMan 

Is there a workaround for this that doesn't require me to put my url in my open source repository?

**Comment by BanzaiMan** [comment]
You can encrypt the webhook endpoint.

```yaml
notifications:
  webhooks:
    - secure: XXXXXX
```

but this will prevent PR builds from sending notifications.
