### ISSUE TITLE
"Branch not permitted", even though I'm not specifying a branch

### ISSUE THREAD

**Issue by rbrtmrtn** [travis-ci/travis-ci#7515]
I'm attempting to run a Node.js build that deploys to S3. The bucket name comes from an environment variable `S3_BUCKET` which is set based on `TRAVIS_BRANCH`. This is my deployer:

```
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  skip_cleanup: true
```

So far I've been getting the error:

    Skipping a deployment with the s3 provider because this branch is not permitted

I can't seem to figure out why this is happening, since I'm not specifying any branches for the provider. I've double-checked that `S3_BUCKET` is being populated correctly and it is.

* [Full .travis.yml](https://github.com/CityOfPhiladelphia/mapboard/blob/develop/.travis.yml)
* [Sample build](https://travis-ci.org/CityOfPhiladelphia/mapboard/builds/214489259)

**Comment by BanzaiMan** [comment]
This behavior is explained here: https://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A

Since you do not have `branch` in the `deploy` section, we are matching it against `master`, which [this build](https://travis-ci.org/CityOfPhiladelphia/mapboard/builds/214489259) is not.

**Comment by BanzaiMan** [comment]
Oh, right. The fix would be to either specify `branch`, or set `all_branches: true`.

**Comment by lpeabody** [comment]
For those finding their way here whilst questing for ideal conditional stages, I ended up having a single deploy job with `all_branches: true` as part of a deploy stage, and the conditional logic for determining whether or not to deploy is contained entirely within the stage configuration:

```
stages:
  - test
  - name: deploy
    if: (branch = master OR branch = develop) AND tag IS blank AND type != pull_request
...
jobs:
  include:
    - name: "Lightning Tests"
      env: BUILD_SITE=default
    - name: "Corporate Tests"
      env: BUILD_SITE=bax_commercial
    - name: "Education Tests"
      env: BUILD_SITE=bax_education
    - name: "Specialty Tests"
      env: BUILD_SITE=bax_specialty
    - stage: deploy
      before_script: skip
      script: skip
      deploy:
        - provider: script
          script: "${DOCKSAL_DIR}/scripts/travis/deploy_branch"
          skip_cleanup: true
          on:
            all_branches: true
```
