### ISSUE TITLE
Yarn in a ruby project

### ISSUE THREAD

**Issue by pauldambra** [travis-ci/travis-ci#7542]
I have a Jekyll project I build with Travis. After build I'd like to run some tools over the site that are only available as npm modules (and I'd like to use Yarn)

I have a yarn.lock at the root of the project but travis is not including Yarn.

You can [see an example build here](https://travis-ci.org/pauldambra/blog_source/builds/216905436)

My travis.yml file is:

```yaml
language: ruby
cache:
  yarn: true
  bundler: true
before_script:
  yarn
install:
- bundle install
script:
  - "./build.sh"
  - "./amp-validate.sh"
after_success:
  - "./deploy.sh"
  - "./htmltest.sh"
  - "./verify.sh"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: ASECRET
```

It's the script `./verify.sh` that requires yarn
