### ISSUE TITLE
Deploy multiple packages to Bintray

### ISSUE THREAD

**Issue by pauldraper** [travis-ci/travis-ci#7567]
I have a couple dozen packages that need deploy to Bintray (working on packaging AWS C++ SDK https://github.com/lucidsoftware/aws-sdk-cpp-deb).

The Bintray descriptor should have an JSON array of packages.

**Comment by BanzaiMan** [comment]
Not sure if this suffices for your use case, but it is worth noting here that you can define multiple deployment providers.

```yaml
deploy:
  - provider: bintray
    ⋮
  - provider: bintray
    ⋮
```
