### ISSUE TITLE
C# .NET Core build fails

### ISSUE THREAD

**Issue by lecaillon** [travis-ci/travis-ci#7586]
I try to build a .NET Core app running these 2 commands: **dotnet restore** and then **dotnet build**.
The NuGet package restoration seems to work just fine. But when it starts the build it fails because it does not find any reference... 

Here is my .travis.yml:

```yml
language: csharp
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
sudo: required
mono: none
dotnet: 1.0.1
script:
  - dotnet restore
  - dotnet build -c Release -f netcoreapp1.1
```

And my build: https://travis-ci.org/lecaillon/Evolve/jobs/219479249

Thanks you

@joshua-anderson @akoeplinger @nterry
