### ISSUE TITLE
Encrypted environment variables: only encrypt value

### ISSUE THREAD

**Issue by OliverJAsh** [travis-ci/travis-ci#7613]
I only want to encrypt the value of my environment variables. By making the key readable, it's clear in my `.travis.yml` which env vars are being provided.

Is this possible? I tried:

``` yml
env:
  global:
    - KEY:
      secure: "encrypted value"
```

… to no avail.

**Comment by BanzaiMan** [comment]
It is not possible to encrypt just the value, as `env` key defines `NAME=VALUE` pair.

I should also add that

```yaml
env: # I'll assume that you forgot a colon here
  global:
    - KEY:
      secure: "encrypted value"
```

is valid, but defines a data structure that is not suitable for use.
