### ISSUE TITLE
Set release name automatically after building

### ISSUE THREAD

**Issue by Amet13** [travis-ci/travis-ci#7624]
Hello!
I'm using TravisCI in my repository https://github.com/Amet13/master-thesis
I'm building my project in Docker and after I upload new release to GitHub.
Here is my `.travis.yml`:
```
language: generic
services:
  - docker
script:
  - make docker

deploy:
  provider: releases
  api_key: $TOKEN
  file: master-thesis.pdf
  skip-cleanup: true
```

After successful building new release push to GitHub with release name such as `untagged-451e863dca8b1ced7376`, here is an [example](https://github.com/Amet13/master-thesis/releases/tag/untagged-451e863dca8b1ced7376).
How can I set release name automatically, for example `master-thesis.pdf-$DATE` or `master-thesis-v1.0.0.pdf`?

I'm not found info about this in docs: https://docs.travis-ci.com/user/deployment/releases

Thanks!

**Comment by rogerioit** [comment]
I thought exactly about this today.
It'd be sweet if Travis gives us the possibility to define the release name.

Specifically for me, I'd put the name like this: `"${TRAVIS_BUILD_NUMBER}-${TRAVIS_BRANCH}-${TRAVIS_BUILD_ID}"`


Thanks in advance.

**Comment by BanzaiMan** [comment]
Most of the options that you specify in `.travis.yml` are passed through to Octokit. If Octokit recognizes the option, it should work. https://github.com/octokit/octokit.rb/blob/7bc49beb839818974e6c8aa568a348bd5f2cca54/lib/octokit/client/releases.rb#L48 says that `#update_release` takes the `name` option.

This is completely untested, but it might work:

```yaml
deploy:
  provider: releases
  api_key: $TOKEN
  file: master-thesis.pdf
  skip-cleanup: true
  name: master-thesis-$(date +'%F-%T').pdf # you want the file extension at the end
```

Note: `$()` construct at the end may not work.

**Comment by rogerioit** [comment]
Well, I didn't think of that. 😄 

Thanks for the help, it worked perfectly here.

**Comment by Amet13** [comment]
Hiro, thank you very much.
Now I'm looking pretty release name:
![screenshot at 2017-04-19 10-52-14](https://cloud.githubusercontent.com/assets/5184847/25169043/4ec11412-24ee-11e7-9458-a8b9fbe27c0e.png)

WIth:
```
deploy:
  provider: releases
  api_key: $TOKEN
  file:
    - "master-thesis.pdf"
    - "presentation/presentation.pdf"
  name: Build $(date +'%d.%m.%Y %R')
  skip-cleanup: true
```
