### ISSUE TITLE
Build based on the new 'Ubuntu Trusty' image failed on accessing DB 

### ISSUE THREAD

**Issue by avpet** [travis-ci/travis-ci#7640]
I have a Scala sbt-based build with `sudo: required`. The build runs tests using MySQL database. This build is working on the 'Ubuntu Precise' image (for example, this run was successful  - https://travis-ci.com/avpet/gdox/builds/44528847). When I switch to Ubuntu Trusty, tests failed on DB access, stating that `travis` user does not have access to the newly created test database:

```
[error] c.j.b.h.AbstractConnectionHook - Failed to obtain initial connection Sleeping for 0ms and trying again. Attempts left: 0. Exception: null.Message:Access denied for user 'travis'@'%' to database 'gdox_test'
```
Failing build link is https://travis-ci.com/avpet/gdox/builds/44532818 , but because it is provate repository, 
Here is `.travis.yml` configuration:
```
sudo: required
dist: trusty
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
language: scala
services: mysql
before_script:
- export TZ=America/New_York
- date
- mysql -e 'create database gdox_test;'
- cat conf/application.conf | sed s/db.default.user=root/db.default.user=travis/ |
  sed s/db.default.password=\"root\"/db.default.password=\"\"/ > conf/testing.conf
- mv conf/testing.conf conf/application.conf
- mkdir -p $HOME/.sbt/launchers/0.13.8/
- curl -L -o $HOME/.sbt/launchers/0.13.8/sbt-launch.jar http://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.jar
- find $HOME/.sbt -name "*.lock" | xargs -r rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs -r rm
script: sbt ++2.11.7 -jvm-opts travis/jvmopts "test"
notifications:
  slack: gdox:SjSd6IBW2tatBnEOAe4SkDQa
```

Switching back to `dist: precise` results in successful build.

I am also attaching both build logs.  

[trusty_failed_build_log.txt](https://github.com/travis-ci/travis-ci/files/948267/trusty_failed_build_log.txt)
[precise_sucessful_build_log.txt](https://github.com/travis-ci/travis-ci/files/948268/precise_sucessful_build_log.txt)
