### ISSUE TITLE
Multi-entry scripts do not work on deploys

### ISSUE THREAD

**Issue by jacobcabantomski-ct** [travis-ci/travis-ci#7641]
Unlike the standard `script` entry, the script field for deploys does not support multiple statements.

```yaml
# Works
deploy:
  provider: script
  script: echo "Foo" && echo "Bar"
  on:
    all_branches: true
```

```yaml
# Fails with:
# /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.31/lib/dpl/cli.rb:54:in `system': wrong first argument (ArgumentError)
#	from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.31/lib/dpl/cli.rb:54:in `shell'
#	from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.31/lib/dpl/provider/script.rb:18:in `push_app'
#	from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.31/lib/dpl/provider.rb:146:in `block in deploy'
#	from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.31/lib/dpl/cli.rb:41:in `fold'
#	from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.31/lib/dpl/provider.rb:146:in `deploy'
#	from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.31/lib/dpl/cli.rb:32:in `run'
#	from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.31/lib/dpl/cli.rb:7:in `run'
#	from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.31/bin/dpl:5:in `<top (required)>'
#	from /home/travis/.rvm/gems/ruby-2.2.5/bin/dpl:23:in `load'
#	from /home/travis/.rvm/gems/ruby-2.2.5/bin/dpl:23:in `<main>'

deploy:
  provider: script
  script:
    - echo "Foo"
    - echo "Bar"
  on:
    all_branches: true
```

**Comment by BanzaiMan** [comment]
This is documented in https://docs.travis-ci.com/user/deployment/script:

> `script` must be a scalar pointing to an executable file or command.

**Comment by jacobcabantomski-ct** [comment]
@BanzaiMan Is there a reason it does not follow the syntax/format of the top level script command?

**Comment by BanzaiMan** [comment]
> Is there a reason it does not follow the syntax/format of the top level script command?

The script provider is meant to be a minimal implementation to execute a command. If you want to execute a few commands, you can string them together with `&&`; if you have more complex logic, you can write a script to do it.

**Comment by davesnx** [comment]
Hey, would you like to add an error message on this case?

**Comment by justinmchase** [comment]
I'm getting this exact same error even in the case of a scalar, how is that possible?

https://github.com/justinmchase/commit-karma/blob/master/.travis.yml#L21

```
deploy:
  - provider: script
    strategy: bash scripts/deploy.sh
    skip_cleanup: true
    on:
      branch: master
```
