### ISSUE TITLE
Building mono for dotnet standard fails

### ISSUE THREAD

**Issue by tzachshabtay** [travis-ci/travis-ci#7642]
@joshua-anderson @akoeplinger @nterry

Hi, I converted my PCL to target dotnet standard, which triggered the CI build to fail (both Linux and Mac).
<details>
<summary>The first script:</summary>

```
language: csharp
solution: MonoAGS.sln

matrix:
  include: 
    - os: linux
      mono: latest
      env: BUILD_CONFIG=DesktopRelease BUILD_PLATFORM="Any CPU"
    - os: osx
      mono: latest
      env: BUILD_CONFIG=DesktopRelease BUILD_PLATFORM="Any CPU"
 
install:
 - nuget restore MonoAGS.sln
 - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
 - xbuild /p:Configuration=$BUILD_CONFIG /p:Platform="$BUILD_PLATFORM" MonoAGS.sln
 - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Source/Tests/bin/Release/Tests.dll
```

</details>
<details>
<summary>And the first error:</summary>

```
        CSC: error CS0518: The predefined type `System.Object' is not defined or imported
	CSC: error CS0518: The predefined type `System.ValueType' is not defined or imported
	CSC: error CS0518: The predefined type `System.Attribute' is not defined or imported
	CSC: error CS0518: The predefined type `System.Int32' is not defined or imported
	CSC: error CS0518: The predefined type `System.UInt32' is not defined or imported
	CSC: error CS0518: The predefined type `System.Int64' is not defined or imported
	CSC: error CS0518: The predefined type `System.UInt64' is not defined or imported
	CSC: error CS0518: The predefined type `System.Single' is not defined or imported
	CSC: error CS0518: The predefined type `System.Double' is not defined or imported
	CSC: error CS0518: The predefined type `System.Char' is not defined or imported
	CSC: error CS0518: The predefined type `System.Int16' is not defined or imported
	CSC: error CS0518: The predefined type `System.Decimal' is not defined or imported
	CSC: error CS0518: The predefined type `System.Boolean' is not defined or imported
```

</details>
Link to actual build: https://travis-ci.org/tzachshabtay/MonoAGS/builds/222915421

---------

I also had the same error on my Appveyor windows build.
Googling the error told me to try using the dotnet core cli and do "dotnet restore" (nuget restore not enough anymore? Weird because it did compile on my Mac with Xamarin Studio without having dotnet core installed).
Anyway, adding dotnet restore solved the issue on the windows build, but not for travis.
I tried with the built-in dotnet:
<details>
<summary>The script:</summary>

```
language: csharp
solution: MonoAGS.sln
matrix:
  include: 
    - os: linux
      mono: latest
      env: BUILD_CONFIG=DesktopRelease BUILD_PLATFORM="Any CPU"
      sudo: required
      dist: trusty
      dotnet: 1.0.1
    - os: osx
      mono: latest
      env: BUILD_CONFIG=DesktopRelease BUILD_PLATFORM="Any CPU"
      dotnet: 1.0.1

install:  
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
 - dotnet restore
 - nuget restore MonoAGS.sln
 - xbuild /p:Configuration=$BUILD_CONFIG /p:Platform="$BUILD_PLATFORM" MonoAGS.sln
 - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Source/Tests/bin/Release/Tests.dll
```

</details>
<details>
<summary>The error:</summary>

```
/home/travis/build/tzachshabtay/MonoAGS/Source/AGS.API/AGS.API.csproj(224,3): error MSB4019: The imported project "/usr/share/dotnet/sdk/1.0.1/Microsoft/Portable/v5.0/Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```

</details>
Link to actual build: https://travis-ci.org/tzachshabtay/MonoAGS/builds/224194385

---------

Not sure, but the log seems to indicate that the MSBuildExtensionsPath32 variable is taking to the dotnet core installation instead to the mono installation, which I believe might be the issue? Or maybe I shouldn't have used dotnet core in the first place, but there's another solution to the first issue?

---------

I tried with installing dotnet core myself. It actually worked with the preview dotnet on linux:
<details>
<summary>The script:</summary>

```
language: csharp
solution: MonoAGS.sln
matrix:
  include: 
    - os: linux
      mono: latest
      env: BUILD_CONFIG=DesktopRelease BUILD_PLATFORM="Any CPU"
      sudo: required
      dist: trusty
    - os: osx
      mono: latest
      env: BUILD_CONFIG=DesktopRelease BUILD_PLATFORM="Any CPU"
      dotnet: 1.0.1

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install dotnet-dev-1.0.0-preview2-003121 -y; fi  
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
 - dotnet restore
 - nuget restore MonoAGS.sln
 - xbuild /p:Configuration=$BUILD_CONFIG /p:Platform="$BUILD_PLATFORM" MonoAGS.sln
 - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Source/Tests/bin/Release/Tests.dll
```

</details>
Link to actual build: https://travis-ci.org/tzachshabtay/MonoAGS/jobs/224573547

--------

But not on Mac:
<details>
<summary>The script:</summary>

```
language: csharp
solution: MonoAGS.sln
sudo: required
dist: trusty
addons:  
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
matrix:
  include: 
    - os: linux
      mono: latest
      env: BUILD_CONFIG=DesktopRelease BUILD_PLATFORM="Any CPU"
    - os: osx
      mono: latest
      env: BUILD_CONFIG=DesktopRelease BUILD_PLATFORM="Any CPU"

before_install:  
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; openssl; fi
install:  
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "latest" --install-dir "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
 - dotnet restore
 - nuget restore MonoAGS.sln
 - xbuild /p:Configuration=$BUILD_CONFIG /p:Platform="$BUILD_PLATFORM" MonoAGS.sln
 - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Source/Tests/bin/Release/Tests.dll
```

</details>
<details>
<summary>The error:</summary>

```
/Users/travis/build/tzachshabtay/MonoAGS/Source/AGS.API/AGS.API.csproj(224,3): error MSB4019: The imported project "/Users/travis/build/tzachshabtay/MonoAGS/.dotnetcli/sdk/1.0.0-rc4-004917/Microsoft/Portable/v5.0/Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```

</details> 
Link to actual build: https://travis-ci.org/tzachshabtay/MonoAGS/jobs/223816328

---

I wanted to check with installing dotnet 1.0.1 myself on linux, but I can't install it due to some dependency error?
<details>
<summary>The script:</summary>

```
language: csharp
solution: MonoAGS.sln
matrix:
  include: 
    - os: linux
      mono: latest
      env: BUILD_CONFIG=DesktopRelease BUILD_PLATFORM="Any CPU"
      sudo: required
      dist: trusty
    - os: osx
      mono: latest
      env: BUILD_CONFIG=DesktopRelease BUILD_PLATFORM="Any CPU"
      dotnet: 1.0.1

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install dotnet-dev-1.0.1 -y; fi  
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
 - dotnet restore
 - nuget restore MonoAGS.sln
 - xbuild /p:Configuration=$BUILD_CONFIG /p:Platform="$BUILD_PLATFORM" MonoAGS.sln
 - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Source/Tests/bin/Release/Tests.dll
```

</details>
<details>
<summary>The error:</summary>

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 dotnet-dev-1.0.1-rc4-004851 : Depends: libstdc++6 (>= 5.2) but 4.8.4-2ubuntu1~14.04.3 is to be installed
 dotnet-dev-1.0.1-rc4-004864 : Depends: libstdc++6 (>= 5.2) but 4.8.4-2ubuntu1~14.04.3 is to be installed
 dotnet-dev-1.0.1-rc4-004906 : Depends: libstdc++6 (>= 6) but 4.8.4-2ubuntu1~14.04.3 is to be installed
 dotnet-dev-1.0.1-rc4-004939 : Depends: libstdc++6 (>= 6) but 4.8.4-2ubuntu1~14.04.3 is to be installed
 dotnet-dev-1.0.1-rc4-004941 : Depends: libstdc++6 (>= 5.2) but 4.8.4-2ubuntu1~14.04.3 is to be installed
 dotnet-dev-1.0.1-rc4-004947 : Depends: libstdc++6 (>= 6) but 4.8.4-2ubuntu1~14.04.3 is to be installed
 dotnet-dev-1.0.1-rc4-004953 : Depends: libstdc++6 (>= 5.2) but 4.8.4-2ubuntu1~14.04.3 is to be installed
E: Unable to correct problems, you have held broken packages.
```

</details>
Link to actual build: https://travis-ci.org/tzachshabtay/MonoAGS/jobs/224571544

---

Finally, here's my branch with all my experiments:
https://github.com/tzachshabtay/MonoAGS/tree/Fix_Build

Any help would be appreciated, thanks.
