### ISSUE TITLE
dpl/lib/cli.rb: deployment (script) fails due to "'system': wrong wirst argument"

### ISSUE THREAD

**Issue by arekkas** [travis-ci/travis-ci#7649]
My deployments [fail](https://travis-ci.com/ory/sites-app/builds/44567008#L508) due to this error:

![grafik](https://cloud.githubusercontent.com/assets/3372410/25315486/c40f4f6c-2855-11e7-8c32-7f4512883738.png)

My deploy section looks like this (nothing fancy):

```yaml
deploy:
  provider: script
  skip_cleanup: true
  script:
    - git checkout -b travis-tag-$(git describe --tag)
    - npm version --no-git-tag-version $(git describe --tag)
    - git add package.json
    - "git commit package.json -m \"package: bump to version $(git describe --tag)\""
    - git push -u origin master
  on:
    branch: master
```

I tried both linux and osx images but both fail here.
