### ISSUE TITLE
Run script before android install

### ISSUE THREAD

**Issue by AllanWang** [travis-ci/travis-ci#7653]
The following is part of my travis configuration:

```yml
language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-25
before_install:
- chmod +x ./overlay-verify.sh
- "./overlay-verify.sh"
```

My goal is to run overlay-verify.sh before anything is installed, as it has its internal commands that don't require any android tools or library. However, Travis seems to install the package tools first, since android isn't a part of the "install" section.

I know this is an unlikely behaviour, but is there any way around this so that a script can be executed before anything else possibly starts? This could greatly reduce my build time as the tool downloads is the longest process by far (4 minutes out of 4.5 minutes)
