### ISSUE TITLE
Cannot run travis on private repo with private dependencies

### ISSUE THREAD

**Issue by JackStat** [travis-ci/travis-ci#7657]
I cannot use travis for our private repo that depends on another private repo.  I have tried using Rscript in the `before_installing` section to install the dependency with the auth_token.  I have also tried to set it up as an enironmental variable so `devtools::install_github` is can pick it up (explicit export and used travis CLI).  Any help would be greatly appreciated and thank you for your work on this great OSS.

@craigcitro, @hadley, and @jimhester

**Comment by jimhester** [comment]
I gather something like this is what you have tried, and it should work.
```yaml
before_install:
  - RScript -e 'devtools::install_deps(dep = TRUE, auth_token = "XYZ")'
```

Unfortunately if that is what you did and it did not work I don't have any great suggestions, I don't have a way to test using private repositories.

**Comment by JackStat** [comment]
Trying your method a bit and expanding on it this is what I am trying

```yaml
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
- export GITHUB_PAT="<token>"
- Rscript -e 'install.packages("devtools")'
- Rscript -e 'devtools::install_deps(dep = TRUE, auth_token = "<token>")'

script:
- run_tests
```

I am now receiving this error 

```yaml
The command "eval sudo apt-get install -y r-cran-devtools " failed. Retrying, 2 of 3.
```
