### ISSUE TITLE
Travis CI linter not handling ": " in curl script

### ISSUE THREAD

**Issue by tlawrie** [travis-ci/travis-ci#7658]
The Travis CI linter will not handle a : then a <space> in the Script provider

**Not Handled**
```
 - provider: script
   script: curl -H 'X-JFrog-Art-Api: ${artifactory_api_key}' -T 'target/random.jar' '$URL'
   on:
     tags: true
```

Yet handles : in the middle of -u ${username}:${password} and with the URL

**Comment by BanzaiMan** [comment]
What exactly did you feed the linter?

This is valid:

```yaml
language: ruby
deploy:
 - provider: script
   script: curl -H 'X-JFrog-Art-Api:${artifactory_api_key}' -T 'target/random.jar' '$URL'
   on:
     tags: true
```

![validate_your__travis_yml_file](https://cloud.githubusercontent.com/assets/25666/25380117/1df5ba16-297d-11e7-8426-93203ac5d04b.png)
