### ISSUE TITLE
Skipping Deployment with Heroku provider because this branch is not permitted...

### ISSUE THREAD

**Issue by MoonTahoe** [travis-ci/travis-ci#7659]
I am trying to deploy anything on the staging branch to one heroku app, and anything on the master branch to another heroku app. 

```
language: node_js
node_js:
- 4.6.1
- 6.9.1

branches:
  only:
  - staging
  - master

deploy:

  provider: heroku
  api_key:
    secure: ...
  app: staging-moonhighway
  on:
    repo: eveporcello/moonhighway
    branch: staging

  provider: heroku
  api_key:
    secure: ...
  app: moonhighway
  on:
    repo: eveporcello/moonhighway
    branch: master

```

It will not deploy to staging, because the [error](https://travis-ci.org/eveporcello/moonhighway/jobs/225449552) it says that the branch is not permitted.  

Realistically I would like to deploy all commits to master to the staging server and all tagged commits to the production server.

**Comment by BanzaiMan** [comment]
Your [`deploy` definition](https://github.com/eveporcello/moonhighway/blob/e8f7edac4323c7eb9355cddc7e318e22431b2334/.travis.yml#L11-L27) has duplicate keys, so only the last one (which defines the one for the `master` branch) is effective.

You'd probably want:

```yaml
deploy:

  - provider: heroku
    api_key:
      secure: ...
    app: staging-moonhighway
    on:
      repo: eveporcello/moonhighway
      branch: staging

  - provider: heroku
    api_key:
      secure: ...
    app: moonhighway
    on:
      repo: eveporcello/moonhighway
      branch: master
```
