### ISSUE TITLE
`allow_failures` seems to break build with several jobs

### ISSUE THREAD

**Issue by dpobel** [travis-ci/travis-ci#7663]
In one of our repository, we recently added `allow_failures` in our matrix as described in https://docs.travis-ci.com/user/customizing-the-build/#Matching-Jobs-with-allow_failures

It seems like this breaks the matrix ie instead of executing several jobs only one is actually run.

Here is the build after adding `allow_failure` https://travis-ci.org/ezsystems/PlatformUIBundle/builds/218391808 and here is an example of build before that change https://travis-ci.org/ezsystems/PlatformUIBundle/builds/218079305

As you can see right after the change, only one job is executed.

**Comment by BanzaiMan** [comment]
Hello. Thanks for taking the time to open the issue.

I think there is a misunderstanding of how `matrix.allow_failures` works. `matrix.allow_failures` will exclude the jobs thus indicated from affecting the build result; they can pass or fail, but they do not matter. They have to be included in the build matrix, however.

By *changing* `matrix.include` to `matrix.allow_failures`, you have effectively removed the definitions of the jobs. In [the current configuration](https://github.com/ezsystems/PlatformUIBundle/blob/e12d748df0c7d7810d4e160f69b5b106779eeb48/.travis.yml), for example, there is only one job actually defined, which is the default job.

If you want to run the jobs you previously `include`d **_and_** you want to allow them to fail, you have to do both:

```yaml
matrix:
    fast_finish: true
    include:
        - php: 5.6
          env: BEFORE="./bin/travis/prepare_behat.sh" TEST_CMD="./bin/travis/runbehat.sh" AFTER_SUCCESS='echo "After success"' RUN_INSTALL=1 COMPOSE_FILE="doc/docker-compose/base-prod.yml:doc/docker-compose/selenium.yml" SYMFONY_ENV=behat SYMFONY_DEBUG=0
        - env: BEFORE="./bin/travis/setupnode.sh" TEST_CMD="./bin/travis/runnode.sh" AFTER_SUCCESS="./bin/travis/generate_apidoc.sh"
        - php: 7.0
          env: BEFORE="./bin/travis/setupphpunit.sh" SYMFONY_VERSION="^2.8" TEST_CMD="./vendor/bin/phpunit -c phpunit.xml" AFTER_SUCCESS='echo "After success"'
        - php: 7.1
          env: BEFORE="./bin/travis/setupphpunit.sh" SYMFONY_VERSION="^3.2" TEST_CMD="./vendor/bin/phpunit -c phpunit.xml" AFTER_SUCCESS='echo "After success"'
        - php: 5.6
          env: BEFORE='./bin/travis/setupphpunit.sh' TEST_CMD="./vendor/bin/phpunit -c phpunit.xml" AFTER_SUCCESS='echo "After success"'
    allow_failures:
        - php: 5.6
          env: BEFORE="./bin/travis/prepare_behat.sh" TEST_CMD="./bin/travis/runbehat.sh" AFTER_SUCCESS='echo "After success"' RUN_INSTALL=1 COMPOSE_FILE="doc/docker-compose/base-prod.yml:doc/docker-compose/selenium.yml" SYMFONY_ENV=behat SYMFONY_DEBUG=0
        - env: BEFORE="./bin/travis/setupnode.sh" TEST_CMD="./bin/travis/runnode.sh" AFTER_SUCCESS="./bin/travis/generate_apidoc.sh"
        - php: 7.0
          env: BEFORE="./bin/travis/setupphpunit.sh" SYMFONY_VERSION="^2.8" TEST_CMD="./vendor/bin/phpunit -c phpunit.xml" AFTER_SUCCESS='echo "After success"'
        - php: 7.1
          env: BEFORE="./bin/travis/setupphpunit.sh" SYMFONY_VERSION="^3.2" TEST_CMD="./vendor/bin/phpunit -c phpunit.xml" AFTER_SUCCESS='echo "After success"'
        - php: 5.6
          env: BEFORE='./bin/travis/setupphpunit.sh' TEST_CMD="./vendor/bin/phpunit -c phpunit.xml" AFTER_SUCCESS='echo "After success"'
```
