### ISSUE TITLE
Non-rectangular matrix

### ISSUE THREAD

**Issue by Suor** [travis-ci/travis-ci#7697]
I have non-rectangular matrix like:
```yaml
matrix:
  include:
    - python: 2.7
      env:
        - TOXENV=lint
        - TOXENV=py27-dj17
        - TOXENV=py27-dj18
        - TOXENV=py27-dj19
        - TOXENV=py27-dj110
        - TOXENV=py27-dj111
    - python: 3.3
      env:
        - TOXENV=py33-dj17
        - TOXENV=py33-dj18
    - python: 3.4
      env:
        - TOXENV=py34-dj17
        - TOXENV=py34-dj18
        - TOXENV=py34-dj19
        - TOXENV=py34-dj110
        - TOXENV=py34-dj111
        - TOXENV=py34-djmaster
    - python: 3.5
      env:
        - TOXENV=py35-dj18
        - TOXENV=py35-dj19
        - TOXENV=py35-dj110
        - TOXENV=py35-dj111
        - TOXENV=py35-djmaster
    ...
 ```
But it looks like env vars are not expanded. Is there a way or it's only manual expansion?

I know that I can exclude from matrix, but that would be very confusing too, especially considering that `tox.ini` lists them explicitely (but consice).

Full travis config [here](https://github.com/Suor/django-cacheops/blob/3fa921def23a850779475f095bd26269b67bf0c5/.travis.yml), tox config is [here](https://github.com/Suor/django-cacheops/blob/3fa921def23a850779475f095bd26269b67bf0c5/tox.ini) for comparison.

I want every combination to be separate task, to see what is failing faster and to allow failures granullary.
