### ISSUE TITLE
Tests failing after Travis environment update

### ISSUE THREAD

**Issue by iriberri** [travis-ci/travis-ci#7706]
Moved from https://github.com/travis-ci/docs-travis-ci-com/issues/1152 (by @cqx931)

----

 Ant tests now fail due to missing junit.jar.
![image](https://cloud.githubusercontent.com/assets/3056154/25740667/0a5a9e0a-31ba-11e7-897a-5ed6a80f2a5a.png)

https://travis-ci.org/dhowe/RiTa/builds/229034737

If I go back to the previous default image, the tests are passing.
https://travis-ci.org/dhowe/RiTa/builds/229036438

**Comment by clementval** [comment]
For me installing those package solve the issue when `junit` executed from `ant`: 

```yaml
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ant
            - ant-optional
```
