### ISSUE TITLE
shell script termination not recognized

### ISSUE THREAD

**Issue by tkruse** [travis-ci/travis-ci#771]
Hi, 
I used these lines:

``` YAML
env:
  - PYYAML=3.09
install:
  - pip install "pyyaml<=$PYYAML" > pyaml-warnings.log 2> &1 || (cat pyaml-warnings.log && false)
```

(with an invalid blank before &1)

in build:
https://travis-ci.org/vcstools/vcstools/jobs/3300523

But the script did not recognize the termination, so it went on until:
"Executing your install (pip install "pyyaml<=$PYYAML" >> pyaml-warnings.log 2> &1 || (cat pyaml-warnings.log && false)) took longer than 15 minutes and was terminated."

It's not a big problem, but might be fixable still, to fail early.

(Edited by @henrikhodne, 2012-11-21 14:53 -0600: formatting)
