### ISSUE TITLE
.NET Core: "No solution or script defined, exiting"

### ISSUE THREAD

**Issue by acastaner** [travis-ci/travis-ci#7760]
Trying Travis CI to build a fairly simple ASP.NET Core website but the builds stops with an error message saying `No solution or script defined, exiting`

I'm referencing the solution name in the .travis.yml file (source [here](https://github.com/acastaner/acastaner.fr-mvc6/blob/master/.travis.yml)):

```
language: csharp
solution: acastaner-mvc6.sln
sudo: false
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
os:
  - linux
branches:
  only:
    - master
    - release
mono: none
dotnet: 1.0.3
```
The source project is there: https://github.com/acastaner/acastaner.fr-mvc6

Not sure what I must be doing wrong for Travis not to pick up my solution name?

cc @joshua-anderson @akoeplinger @nterry
