### ISSUE TITLE
Create separate releases for osx and Linux in same build

### ISSUE THREAD

**Issue by mohtamohit** [travis-ci/travis-ci#7761]
In the same build, I want to create two separate releases - one for osx and one for linux. Is there a way out?

**Comment by BanzaiMan** [comment]
You can specify multiple deployment providers in a build. https://docs.travis-ci.com/user/deployment/#Deploying-to-Multiple-Providers

**Comment by mohtamohit** [comment]
@BanzaiMan No, that's not what I mean. 
I have to create a Github Release for OSX and Linux. I want to specify different files (for release) in those packages. It's something like this 

If( OS is Linux) : 
deploy :
 provider: releases
  api_key: '$GITHUB_API_KEY'
  file : 
    - "A"
    - "B'
  skip_cleanup: true
  on:
    tags: true

If( OS is osx) : 
deploy :
 provider: releases
  api_key: '$GITHUB_API_KEY'
  file : 
    - "A"
    - "C'
  skip_cleanup: true
  on:
    tags: true

Since, it will run on both, I want to create two separate releases. Is that possible?

**Comment by BanzaiMan** [comment]
Use conditional deployment. Described just below the section I indicated earlier.

**Comment by iriberri** [comment]
Hi @mohtamohit!

As @BanzaiMan mentioned, adding two deployment providers in your configuration should allow you to achieve this.

In this case, you can condition the deployments on `tags: true` and the `TRAVIS_OS_NAME ` environment variable to make sure that each job (Linux/OS X) performs the release of the corresponding files for each OS.

```
deploy:
  - provider: releases
    api_key: "GITHUB API KEY"
    file:
      - "A"
      - "B"
    skip_cleanup: true
    on:
      condition: $TRAVIS_OS_NAME = linux
      tags: true
  - provider: releases
    api_key: "GITHUB API KEY"
    file:
      - "A"
      - "C"
    skip_cleanup: true
    on:
      condition: $TRAVIS_OS_NAME = osx
      tags: true
```

This will create two separate releases in your Linux and OS X jobs. Hope this helps!

Would this work for you? If this doesn't match with your use case, please don't hesitate to give us some more details so that we can help you further!

**Comment by mohtamohit** [comment]
See this build : https://travis-ci.org/inordertotest/CppSharp/builds/232863509 

What I was trying to do was the same tagged release would make a released package for OSX and a package for Linux. Although, what's happening is : both the builds are run and file releases from both the builds are uploaded in the same sector, see : https://github.com/inordertotest/CppSharp/releases/tag/14.0 (grouping or separate packaging, I mean is possible or not?).

**Comment by BanzaiMan** [comment]
If you want files to go to different releases, you need to tag them differently.

**Comment by mohtamohit** [comment]
I see. But, then again same .yml file will be called on the two builds. Is there a way to specify that in a particular tag file packaged would be for osx and in the orher release it would be for linux?

**Comment by BanzaiMan** [comment]
You can apply two tags to the same commit. It's not possible to vary the build matrix based on the tag name in that case, though, so you will have to run the same build twice.

**Comment by iriberri** [comment]
There's also some logic you can add to use two tags for your OS X and Linux build and avoid these deployments to run twice because of the build running two times.

Imagine you use tags of the format: `1.1.1.linux` and `1.1.1.osx` (the regexps below are set for this, but of course feel free to edit them!). Then, you can check the OS in which the build is running (TRAVIS_OS_NAME) as well as the tag (TRAVIS_TAG) to know if the job should deploy your release or not.

If your build with the below configuration runs twice for `1.1.1.linux` and `1.1.1.osx`, you'd only get two different releases (one for Linux and one for OSX) with these conditions:

```yaml
matrix:
  include:
  - os: osx
    osx_image: xcode8.3
    env: OSX_DEPLOY="false" LINUX_DEPLOY="false"
    language: ruby
  - dist: trusty
    language: ruby
    sudo: false
    env: OSX_DEPLOY="false" LINUX_DEPLOY="false"

[...]

before_deploy:
- if [[ ("$TRAVIS_OS_NAME" == "osx") && ("$TRAVIS_TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.osx$) ]]; then export OSX_DEPLOY="true"; fi
- if [[ ("$TRAVIS_OS_NAME" == "linux") && ("$TRAVIS_TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.linux$) ]]; then export LINUX_DEPLOY="true"; fi

[...]

deploy:
  # your OS X deploy
  - provider: releases
    api_key: "YOUR API KEY"
    file:
      - "A"
      - "B"
    skip_cleanup: true
    on:
      condition: $OSX_DEPLOY = "true"
      tags: true
  # your Linux deploy
  - provider: releases
    api_key: "YOUR API KEY"
    file:
      - "A"
      - "C"
    skip_cleanup: true
    on:
      condition: $LINUX_DEPLOY = "true"
      tags: true
```
