### ISSUE TITLE
Stages not working with PHP 7, can't solve PHPUnit failure

### ISSUE THREAD

**Issue by tgolen** [travis-ci/travis-ci#7775]
Hi, I've boiled the issue down to the most basic of scenarios. The following config works fine:

```
jobs:
  include:
    - stage: unit tests
      script: echo one
    - stage: unit tests
      script: echo two
```

![image](https://cloud.githubusercontent.com/assets/1228807/26159485/eb7fee38-3adb-11e7-9d29-ecda2efb56cc.png)

However, if I add PHP to the mix, then there is a new stage called "test" that shows up and ends up failing. This test doesn't appear to be under my control and I can't continue with building out the rest of our test scripts.

```
jobs:
  include:
    - stage: unit tests
      script: echo one
    - stage: unit tests
      script: echo two
language: php
php:
    - 7.0
```

![image](https://cloud.githubusercontent.com/assets/1228807/26159600/406d0a20-3adc-11e7-86a1-11b7d9602096.png)

The failure is:

![image](https://cloud.githubusercontent.com/assets/1228807/26159622/50764cc4-3adc-11e7-8c4e-af64cab7d1cd.png)

Can you help me figure out how to get this working with PHP? If I don't use stages, and just use a normal matrix, it works just fine.
