### ISSUE TITLE
in configuration with ten or more stages, the tenth stage runs first

### ISSUE THREAD

**Issue by mykmelez** [travis-ci/travis-ci#7776]
In a configuration with ten or more stages, including an explicit test stage, the tenth stage runs first. I would expect the test stage to run first, and the tenth stage to run tenth.

To demonstrate the behavior, over in https://github.com/mykmelez/test-travis-build-stages, I've defined this simple .travis.yml configuration, with ten stages (including the test stage), all of which succeed except for the tenth one, which fails:

```yaml
language: generic
jobs:
  include:
    - stage: test
      script: sh -c true
    - stage: two
      script: sh -c true
    - stage: three
      script: sh -c true
    - stage: four
      script: sh -c true
    - stage: five
      script: sh -c true
    - stage: six
      script: sh -c true
    - stage: seven
      script: sh -c true
    - stage: eight
      script: sh -c true
    - stage: nine
      script: sh -c true
    - stage: ten
      script: sh -c false
```

Based on my understanding of the build stages feature, I would expect the test stage to run first, followed by stage two, stage three, and so on, with stage ten running last, such that the first nine stages succeed before the tenth one fails.

But https://travis-ci.org/mykmelez/test-travis-build-stages/builds/233317979 shows that stage ten actually runs first, and the other stages are all cancelled after it fails.

And https://travis-ci.org/mykmelez/test-travis-build-stages/builds/233318979 shows that a retriggered build runs both the test stage and stage ten simultaneously, with the test stage succeeding, and stage ten failing, after which stages two through nine are cancelled.

(I've tested this with up to 17 stages, and it always seems to be the tenth stage that runs first.)
