### ISSUE TITLE
Default Test Stage Bug

### ISSUE THREAD

**Issue by aldochristiansense** [travis-ci/travis-ci#7777]
I set my first stage with name `setup cron`.
But why it always run `Test` stages even though i didn't define it in my travis.yml file ?

This is my configuration: 
```
jobs:
  include:
    - stage: setup cron
      script: ./scripts/travis/setup_cron.sh
    - stage: build checker
      script:
        - source ./scripts/travis/checker.sh
        - if $ABORT_TASK; then exit; fi
    - stage: setup emulator
      script:
        - emulator -avd test -no-audio -no-window -wipe-data -no-skin &
        - ./gradlew check -PdisablePreDex
        - android-wait-for-emulator
        - adb shell input keyevent 82 &
    - stage: run build
      script: ./scripts/travis/deploy.sh
```

![failing](https://cloud.githubusercontent.com/assets/17135819/26189999/84fdf49c-3bd1-11e7-955a-67b9fa33505b.png)

Please fix this :)
