### ISSUE TITLE
Deploy on master and tags

### ISSUE THREAD

**Issue by steazzalini** [travis-ci/travis-ci#7780]
I'm trying to deploy on `master` and all `tags`.
As `script` as deploy provider I managed to do so using a condition on the `on` clause as following:

```yaml
deploy:
  provider: script
  script: .ci/travis/deploy
  skip_cleanup: true
  on:
    condition: $TRAVIS_BRANCH == "master" || -n $TRAVIS_TAG
```

I'd expect the same using `s3`, but it seems like that it not the case.
I got `Skipping a deployment with the s3 provider because this branch is not permitted`.

```yaml
deploy:
  provider: s3
  access_key_id: [secret]
  secret_access_key:
    secure: [secret]
  bucket: [secret]
  acl: public_read
  region: eu-west-2
  skip_cleanup: true
  local-dir: dist
  on:
    condition: $TRAVIS_BRANCH == "master" || -n $TRAVIS_TAG
```

Bug or wrong approch?

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by steazzalini** [comment]
Sure @BanzaiMan

`s3 `deployment:
https://travis-ci.org/kiitoscpp/llvm/jobs/233110277

`script `deployment:
https://travis-ci.org/kiitoscpp/toolchain/jobs/233510388

**Comment by BanzaiMan** [comment]
The distinction is not that of the deployment provider (S3 vs script), but, rather, that of the branch vs tag. In https://travis-ci.org/kiitoscpp/toolchain/jobs/233502168#L1884, you see that the S3 provider was invoked on a tag build and the file uploaded successfully.

This is a case where `$TRAVIS_BRANCH` is set to the tag name (i.e., `v0.0.1` in https://travis-ci.org/kiitoscpp/toolchain/jobs/233510388), and therefore the custom condition is not met. (So, basically, this is a different manifestation of https://github.com/travis-ci/travis-ci/issues/4745.) There is an internal ticket to look at this issue.

For your use case, however, can be resolved right now by setting up two almost identical deployment providers which differ in just the `condition`; one should test `branch`, and the other `tag`.

```yaml
deploy:
  - provider: s3
    access_key_id: [secret]
    secret_access_key:
      secure: [secret]
    bucket: [secret]
    acl: public_read
    region: eu-west-2
    skip_cleanup: true
    local-dir: dist
    on:
      branch: "master"
  - provider: s3
    access_key_id: [secret]
    secret_access_key:
      secure: [secret]
    bucket: [secret]
    acl: public_read
    region: eu-west-2
    skip_cleanup: true
    local-dir: dist
    on:
      tags: true
```

**Comment by steazzalini** [comment]
Thanks for the quick solution!
Anyway I still do not grasp it since in the condition is an `or` stmt and it should be evaluated as `true` in any case.

Hypothetically, if I define:

```yml
deploy:
  provider: s3
  ...
  on:
    condition: true
```

will this deploy in all cases (all branches and tags)?

**Comment by BanzaiMan** [comment]
Yes, that works, but if you want to deploy on all branches and tags, we have a special one: `all_branches`.

**Comment by steazzalini** [comment]
I tested and using `condition: true` the deployment is skipped.
I think this can be labeled as :bug:

**Comment by BanzaiMan** [comment]
Please include the build log URL.

**Comment by BanzaiMan** [comment]
I think I misled you with the previous comment.

```yaml
deploy:
  on:
    condition: true
```

is always true, to it is basically a no-op. This means that the deployment will trigger under the default condition, which is "only on the `master` branch". It will thus skip on https://travis-ci.org/kiitoscpp/toolchain/jobs/233717284 (a tag build).
