### ISSUE TITLE
Build fails when using stages and jdk defined as an array

### ISSUE THREAD

**Issue by orzeh** [travis-ci/travis-ci#7786]
For `.travis.yml`:

````yaml
language: java
install: true
sudo: required

jdk: 
  - oraclejdk8

script: ./gradlew build -s

jobs:
  include:
    - stage: release
      script: skip
      deploy:
        provider: script
        script: ./gradlew deploy
        on:
          tags: true
````

job in _release_ stage fails with:
````
$ jdk_switcher use ["oraclejdk8"]
Sorry, but JDK '[oraclejdk8]' is not known.
The command "jdk_switcher use ["oraclejdk8"]" failed and exited with 1 during .
````

If I change to `jdk: oraclejdk8` it works as expected.

Travis logs and config [here](https://travis-ci.org/bmuschko/gradle-docker-plugin/jobs/233929468)
