### ISSUE TITLE
Build Stages and allow_failures do not work well together

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#7789]
# Problem

When Build Stages is defined, as well as `allow_failures`, queuing order is incorrect.

## configuration
```yaml
language: php
sudo: false
dist: trusty
jobs:
  fast_finish: true
  allow_failures:
    - php: "hhvm"
  include:
    - php: "7.0"
    - php: "7.1"
    - php: "hhvm"
    - stage: next stage
      php: "5.6"

script: if [[ $TRAVIS_PHP_VERSION = "hhvm" ]]; then false; else true; fi
```

# Expected result

The default "Test" stage contains 3 jobs, 7.0, 7.1, and hhvm, and they are queued first. In this particular case, the hhvm job fails with `false` but is allowed to fail, so upon completion of the "Test" stage, the execution moves on to the "next stage". This, too, will pass, and the build is marked a success.

# Actual result

https://travis-ci.org/BanzaiMan/travis_production_test/builds/234179350

![build__3643_-_banzaiman_travis_production_test_-_travis_ci](https://cloud.githubusercontent.com/assets/25666/26268768/d591c378-3cbe-11e7-88c2-f9caa4f631ab.png)

The "Test" stage contains 2 jobs ("7.0", and "7.1"), which are queued first. They pass, and the execution moves on to the "next stage". The "5.6" job passes, and the "hhvm" job fails; the latter is allowed to fail, though, so the build is marked a pass.

# Preliminary discussion

It appears that the [logic to queue allowed-to-fail jobs](https://github.com/travis-ci/travis-scheduler/pull/59) is taking precedence over the stage queuing logic.

In addition, the allowed-to-fail jobs have lost their visual representation to explicitly mark the job allowed to fail. (This is a separate table in the normal build configuration, but such separation in the Build Stage display might be confusing and undesirable.
