### ISSUE TITLE
Can't get build tools v26.0.0-rc2 or Android O

### ISSUE THREAD

**Issue by SUPERCILEX** [travis-ci/travis-ci#7792]
This seems to be a recurring issue, is there a way I can force a refresh?
Here's part of my `.travis.yml`:
```yml
before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
android:
  components:
    # https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
    - tools
    - tools
    - build-tools-26.0.0-rc2
    - android-O
    - platform-tools
    - extra-android-m2repository
    - extra-google-m2repository
```

**Comment by alouanemed** [comment]
did you able to fix this?

**Comment by alouanemed** [comment]
change this     
`- build-tools-26.0.0-rc2
` to 
`- build-tools-26.0.0-preview`

**Comment by SUPERCILEX** [comment]
@alouanemed That worked for the build tools (thanks! 😄), but not for the android version. How do I get the O preview? I tried `android-o`, `android-preview`, and `android-o-preview`.

**Comment by alouanemed** [comment]
Here you go : "platforms;android-O" 
Sorry for the late answer.

**Comment by SUPERCILEX** [comment]
@alouanemed Thanks for the hint! That didn't work out in the end, but I figured it out.

For anyone wondering, here's my `.travis.yml`:
```yml
android:
  components:
    # https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
    - tools
    - tools
```

And here's my install script:
```sh
${ANDROID_HOME}tools/bin/sdkmanager --channel=3 \
  "tools" "platform-tools" "build-tools;${BUILD_TOOLS_VERSION}" "platforms;android-O" \
  "extras;google;google_play_services"
```

It's awesome because I now have complete control over my deps! 😄
