### ISSUE TITLE
Starting 'xvfb' in a separate shell causes Java UI tests to fail

### ISSUE THREAD

**Issue by JordanMartinez** [travis-ci/travis-ci#7798]
When I follow the xfvb instructions exactly, so that the `xvfb start` command is run in the `.travis.yml` file's "before_install" phase, this build succeeds:
````yml
language: java

matrix:
  include:
    - os: linux
      dist: precise
      jdk: oraclejdk8
    - os: linux
      dist: trusty
      jdk: oraclejdk8

# enable Java 8u45+, see https://github.com/travis-ci/travis-ci/issues/4042
addons:
  apt:
    packages:
      - oracle-java8-installer

# run in container
sudo: false

# use framebuffer for UI
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install: true

script:
  - chmod +x .ci/script.sh
  - .ci/script.sh

# See https://docs.travis-ci.com/user/languages/java/#Caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
````

However, when I extract those commands to a separate shell file, it fails:
````yaml
language: java

matrix:
  include:
    - os: linux
      dist: precise
      jdk: oraclejdk8
    - os: linux
      dist: trusty
      jdk: oraclejdk8

# enable Java 8u45+, see https://github.com/travis-ci/travis-ci/issues/4042
addons:
  apt:
    packages:
      - oracle-java8-installer

# run in container
sudo: false

# use framebuffer for UI
before_install:
  - chmod +x .ci/before_install.sh
  - .ci/before_install.sh

install: true

script:
  - chmod +x .ci/script.sh
  - .ci/script.sh

# See https://docs.travis-ci.com/user/languages/java/#Caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
````

Where `.ci/before_install.sh` is:
````bash
#!/usr/bin/env bash

# Linux OS: use frame buffer
export DISPLAY=:99.0
sh -e /etc/init.d/xvfb start
````

At the very least, the [xvfb documentation](https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI) should be updated to notify users of this quirk until it gets fixed
