### ISSUE TITLE
Neo4j Bolt URL

### ISSUE THREAD

**Issue by Snugug** [travis-ci/travis-ci#7801]
Using `neo4j-driver` for a Node project attempting to connect to the neo4j service on Travis with `bolt://localhost:7474` I'm getting the following error:

```
Error: 140503947536192:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
```

Does the Neo4j service on Travis support `bolt` URLs? If not, can it?

**Comment by BanzaiMan** [comment]
It is probably due to the old version we have on our images.

**Comment by Snugug** [comment]
Is it possible to get it updated? We're running on Travis Enterprise (so I know it's a little behind) but it's blocking us from being able to run tests.

Thank yoU!

**Comment by BanzaiMan** [comment]
The build image updates will probably take time to roll out, so I suspect you'd have to update the installation yourself.

```yaml
sudo: required
before_install:
  - wget -O - https://debian.neo4j.org/neotechnology.gpg.key | sudo apt-key add -
  - echo 'deb https://debian.neo4j.org/repo stable/' | sudo tee /etc/apt/sources.list.d/neo4j.list
  - sudo apt-get update
  - sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install neo4j
  - sudo neo4j restart
```

**Comment by Snugug** [comment]
Thanks!

**Comment by BanzaiMan** [comment]
Looks like Neo4j on Precise is old, too, so you'll need:

```yaml
dist: trusty
```

According to my testing, this will get you Neo4j 3.2.0.

**Comment by Snugug** [comment]
It says in the documentation that Neo4j doesn't ship with `trusty`. Can I install it via `apt` on it?

**Comment by BanzaiMan** [comment]
I've tested this:

```yaml
sudo: required

dist: trusty

addons:
  apt:
    sources:
      - sourceline: 'deb https://debian.neo4j.org/repo stable/'
        key_url: 'https://debian.neo4j.org/neotechnology.gpg.key'
    packages:
      - neo4j
```

**Comment by BanzaiMan** [comment]
I should mention that the `apt` addon may stop working when we should Neo4j with the Trusty image, as we may tweak the configuration files and overwriting them requires user interaction, which is not possible with the addon.

**Comment by Snugug** [comment]
For now, I'm able to get this all working as follows:

```yaml
dist: trusty
sudo: required

addons:
  apt:
    sources:
      - sourceline: 'deb https://debian.neo4j.org/repo stable/'
        key_url: 'https://debian.neo4j.org/neotechnology.gpg.key'
    packages:
      - neo4j

# Sets password for user `neo4j` to `password` because neo4j doesn't like you attempting to use it with the default password
before_install:
  - >
    curl -H "Content-Type: application/json" -X POST -d '{"password":"password"}' -u neo4j:neo4j http://localhost:7474/user/neo4j/password
```
