### ISSUE TITLE
[Question] use different centos version with docker 

### ISSUE THREAD

**Issue by chvalean** [travis-ci/travis-ci#7816]
Hello,

I have 2 questions please:
1. Is it possible to run different centos docker images? Currently I see it defaults to v7.3, even if in my yaml file I'm trying to define a different one, for eg:

> sudo docker pull centos:7.2.1511
> or
> sudo docker pull centos:centos7.2.1511

Either way, at job runtime I always have see this:

> centos7: Pulling from library/centos
> Status: Downloaded newer image for centos:centos7

2. If the first question is possible, then I'm trying to figure out if in a single travis job I can test some code on different centos versions - any feedback is welcome here 👍 

Thank you!

**Comment by BanzaiMan** [comment]
When you run `docker pull`, you will be pulling down Docker images from Docker Hub. We do not have control over them.

If you want to run jobs using different images, you can use the build matrix:

```yaml
sudo: required
dist: trusty
env:
  - CENTOS=centos # default
  - CENTOS=centos:7.2.1511
  - CENTOS=centos:7.1.1503
before_script:
  - docker pull $CENTOS
  ⋮
```
