### ISSUE TITLE
Ubuntu JavaFX maven build fail

### ISSUE THREAD

**Issue by cbrnrd** [travis-ci/travis-ci#7844]
Using this configuration:
```yaml
{
  "language": "java",
  "sudo": false,
  "addons": {
    "apt": {
      "packages": [
        "oracle-java8-installer"
      ]
    }
  },
  "before-install": [
    "sudo apt-get update -q",
    "sudo apt-get install openjfx -y"
  ],
  "script": "mvn clean install",
  "group": "stable",
  "dist": "precise",
  "os": "linux"
}
```

A library using the JavaFX API and maven fails to build, as it fails on install. However, using `"dist":"trusty"`, the build works fine. I believe this is because even after `oracle-java8-installer` is installed on Ubuntu, the system doesn't use it for the build. The full build history for the project is [here](https://travis-ci.org/cbrnrd/AlertFX/builds).

### `mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V` trusty output (successful)

```
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=192m; support was removed in 8.0
Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 15:22:22+0000)
Maven home: /usr/local/maven
Java version: 1.8.0_131, vendor: Oracle Corporation  <------
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.8.12-040812-generic", arch: "amd64", family: "unix"
```

### Ubuntu output (failed)

```
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_76, vendor: Oracle Corporation  <------
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.8.12-040812-generic", arch: "amd64", family: "unix"
```

**Comment by BanzaiMan** [comment]
I think the issue here was that installing Java 8 is not sufficient. As described in https://docs.travis-ci.com/user/languages/java#Testing-Against-Multiple-JDKs, you'd need to specify the `jdk` value as shown.

Your failing jobs (e.g., https://travis-ci.org/cbrnrd/AlertFX/builds/238790747) ran on Precise, with Java 7 as the default, and failed. Your recent jobs are running on Trusty, which has Java 8 as the default.

The same result should have been achieved by:

```yaml
language: java
dist: precise
jdk:
  - oraclejdk8
⋮
```

I'm closing this now.
