### ISSUE TITLE
allow_failures not parsed well

### ISSUE THREAD

**Issue by HanXHX** [travis-ci/travis-ci#7861]
Hi team!

My travis.yml file is not parsed well. The "allow_failures" features seems not working with 2 variables env. Result => https://travis-ci.org/HanXHX/ansible-nginx/builds/239906638

Cheers!

EM

-----------------------------------------

```yaml
env:
  - PLATFORM='docker-debian-jessie'           ANSIBLE_VERSION='ansible>=2.2,<2.3'
  - PLATFORM='docker-debian-jessie-backports' ANSIBLE_VERSION='ansible>=2.2,<2.3'
  - PLATFORM='docker-debian-jessie-dotdeb'    ANSIBLE_VERSION='ansible>=2.2,<2.3'
  - PLATFORM='docker-debian-jessie'           ANSIBLE_VERSION='ansible>=2.3,<2.4'
  - PLATFORM='docker-debian-jessie-backports' ANSIBLE_VERSION='ansible>=2.3,<2.4'
  - PLATFORM='docker-debian-jessie-dotdeb'    ANSIBLE_VERSION='ansible>=2.3,<2.4'
  - PLATFORM='docker-debian-stretch'          ANSIBLE_VERSION='ansible>=2.3,<2.4'

matrix:
  allow_failures:
    - env: PLATFORM='docker-debian-stretch' ANSIBLE_VERSION='ansible>=2.3,<2.4'
  fast_finish: true

sudo: required

dist: trusty

language: python

services:
  - docker

before_install:
  - wget https://releases.hashicorp.com/vagrant/1.9.5/vagrant_1.9.5_x86_64.deb
  - sudo dpkg -i vagrant_1.9.5_x86_64.deb

install:
  - pip install "$ANSIBLE_VERSION"

script:
  - VAGRANT_DEFAULT_PROVIDER=docker vagrant up $PLATFORM
  - >
    VAGRANT_DEFAULT_PROVIDER=docker vagrant provision $PLATFORM
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - VAGRANT_DEFAULT_PROVIDER=docker vagrant status

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
```
