### ISSUE TITLE
Firebase deploy fails

### ISSUE THREAD

**Issue by andreasonny83** [travis-ci/travis-ci#7869]
I tried to follow the documentation for setting up a Firebase deployment using TravisCI but it always report the following error:

```
Error: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth
```

Here the link to [my Travis report](https://travis-ci.org/andreasonny83/rock-paper-scissors-pwa/builds/240382663)

I generated a firebase token with:

```
firebase login:ci
```

Then I generated a travisCI secure token with:

```
travis encrypt FIREBASE_TOKEN=1/MY_FIREBASE_TOKEN
```

and I copy/pase the result inside my `.travis.yml` file like this:

```
deploy:
  provider: firebase
  skip_cleanup: true
  on:
    branch: master
    tags: true
  token:
    secure: N+r8wC2J5Z66t+ZknveBFWcbh6TI......
  project: rock-paper-scissors-pwa
```

The project I' working on is hosted on GitHub at https://github.com/andreasonny83/rock-paper-scissors-pwa

Any help with this configuration would be great. Thanks
