### ISSUE TITLE
Add light log background option

### ISSUE THREAD

**Issue by j-f1** [travis-ci/travis-ci#7876]
Some people (like me) prefer a light background on code. Would it be possible to add a toggle to change the log background to white?

**Comment by j-f1** [comment]
Here’s what I’ve got so far:

<img width="357" alt="screen shot 2017-10-28 at 13 52 38" src="https://user-images.githubusercontent.com/25517624/32137077-532b84fc-bbe7-11e7-921e-1ba325becb45.png">

```css
.job-log {
  filter: invert() brightness(1.1);
}

#tail {
  filter: invert() brightness(0.9);
}

.download-log-button:hover,
.toggle-log-button--dark:hover {
  background-color: #5f605f;
}
.toggle-log-button {
  border-color: #ccc;
  filter: invert() brightness(0.9)
}

.log-body p:hover {
  background-color: #333 !important;
}
.log-body p.highlight {
  background-color: #666;
}
```
