### ISSUE TITLE
TRAVIS_PULL_REQUEST_BRANCH is undefined during Travis build

### ISSUE THREAD

**Issue by dschinkel** [travis-ci/travis-ci#7900]
I'm trying to get my js script to pull the TRAVIS_PULL_REQUEST_BRANCH value but it comes up undefined when my js script runs.  Not sure what I'm doing wrong here:

**deploy-pull-request.js**

```
    const chalk = require('chalk'),
      _ = require('lodash'),
      green = chalk.green,
      info = chalk.yellow,
      Deploy = require('./deployApi')
    
    // require('dotenv').config()
    // const { env } = process
      let options = {
        awsKey: process.env.AWS_ACCESS_KEY_ID,
        awsSecret: process.env.AWS_SECRET_ACCESS_KEY,
        localBuildFolder: 'build',
        domain: 'admin-'
    }
    
    const branch = process.env.FAKE_PULL_REQUEST_BRANCH || process.env.TRAVIS_PULL_REQUEST_BRANCH
```
.. rest of the code...

**travis.yml**

```
    language: node_js
    node_js:
      - 8
    cache:
      yarn: true
      directories:
        - node_modules
    deploy:
      provider: s3
      access_key_id: $AWS_ACCESS_KEY_ID
      secret_access_key: $AWS_SECRET_ACCESS_KEY
    before_script:
      - pip install --user awscli
      - yarn run build
      - yarn run test
    script:
      - babel-node ./src/client/deploy/deploy-pull-request.js
```
