### ISSUE TITLE
Cache directory fails to upload after build

### ISSUE THREAD

**Issue by njlr** [travis-ci/travis-ci#7902]
I am using [Linuxbrew](http://linuxbrew.sh/) to install some dependencies required for my build. This takes a while, so I want to cache the Linuxbrew folder for future builds. Here is my repo: [njlr/buck-travis-example](https://travis-ci.org/njlr/buck-travis-example). 

Linuxbrew puts dependencies into `/home/linuxbrew/`. 

Here is my `.travis.yml`: 

```
sudo: required
dist: trusty
language: generic

before_install:
  # Install Linuxbrew
  - ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
  - PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
  - echo 'export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"' >>~/.bash_profile
  - brew --version
  # Install Buck
  - brew tap facebook/fb
  - brew install buck
  - buck --version
  # Install GCC
  - brew install gcc

script:
  - buck build :hello

branches:
  except:
    - gh-pages

cache:
  directories:
    - /home/linuxbrew/
```

As you can see, I have marked the Linuxbrew folder as cached. 

However, after a successful build, I get this error: 

```
changes detected, packing new archive

FAILED: tar -Pzcf /home/travis/.casher/push.tgz 

tar: Cowardly refusing to create an empty archive

Try 'tar --help' or 'tar --usage' for more information.

uploading archive

failed to upload cache

curl: Can't open '/home/travis/.casher/push.tgz'!

curl: try 'curl --help' or 'curl --manual' for more information
```

And for subsequent builds, the cache cannot be fetched: 

```
0.65sattempting to download cache archive

fetching master/cache-linux-trusty-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.tgz

could not download cache
```

Why is my cache folder not working?
