### ISSUE TITLE
Database does not exist even running psql

### ISSUE THREAD

**Issue by alexanmtz** [travis-ci/travis-ci#7903]
As described here in Stack Overflow:

https://stackoverflow.com/questions/44521233/running-mocha-on-travis-with-sequelize-migration-throws-a-database-does-not-exi

With the following travis configuration:
```
sudo: required
dist: trusty
language: node_js
env:
  - DB=gitPay
addons:
  artifacts:
    paths:
      - .karma/
      - ./mocha.js
before_script:
  - psql -c 'create database gitPay;' -U postgres
node_js:
  - "7.8.0"
services:
  - postgresql
  - mysql
before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - sudo apt-get install libgconf2-4 libnss3-1d libxss1
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb
script:
    - npm run test
    - npm run test-unit

```

It triggers a failure like this exection, even creating the database successfully:
`database "gitPay" does not exist`

in the job like this: https://travis-ci.org/worknenjoy/gitpay/builds/242391063
