### ISSUE TITLE
Google Play Services 11.0.1 

### ISSUE THREAD

**Issue by anna-b** [travis-ci/travis-ci#7926]
Recently, there were released a new version of Google Play Services - 11.0.1 https://developers.google.com/android/guides/releases
When using the dependency with this version in Android project e.g.
compile "com.google.android.gms:play-services-cast-framework:11.0.1" 
Travis build fails with the error saying that license agreements are not accepted.

Here is a part of my Travis yml that is responsible for dependencies:
```yaml
language: android
cache: false
sudo: required
jdk:
    - oraclejdk8
env:
  global:
  - TERM=dumb
  - GRADLE_OPTS="-Xmx8048M -XX:MaxPermSize=2048M"
  - CONTINUOUS_INTEGRATION=true
  - MALLOC_ARENA_MAX=2
  - ADB_INSTALL_TIMEOUT=10
  - ANDROID_TARGET=android-25
  - ANDROID_BUILD_TOOLS_VERSION=26.0.0
  - ANDROID_ABI=armeabi-v7a

android:
  components:
    - $ANDROID_TARGET
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
  licenses:
    - 'android-sdk-license-.+'
    - 'android-sdk-preview-license-.+'
    - 'google-gdk-license-.+'
```
