### ISSUE TITLE
secure: variables doesn't seems to be working when multiple deployment syntax is used

### ISSUE THREAD

**Issue by Vdragon** [travis-ci/travis-ci#7931]
While [this syntax](https://github.com/l10n-tw/l10n-tw-logo/blob/d02e53b277dc6d58b2395357de4826f93ef0bef7/.travis.yml) [works perfectly](https://travis-ci.org/l10n-tw/l10n-tw-logo/builds/245002437): 

```yaml
deploy:
  provider: releases
  api_key:
    secure: X...=
```

[this](https://github.com/l10n-tw/l10n-tw-logo/blob/93a9fe35f1226a6f735bb034f4202678c9c93360/.travis.yml) doesn't and [GitHub returns](https://travis-ci.org/l10n-tw/l10n-tw-logo/builds/245197040) `401 - Bad credentials // See: https://developer.github.com/v3 (Octokit::Unauthorized)`:

```yaml
deploy:
  - provider: releases
    api_key:
      secure: X...=
  - provider: pages
    github_token: 
      secure: X...=
```

## Workaround
Use environment variables instead

```
deploy:
  - provider: releases
    api_key: $GITHUB_ACCESS_TOKEN_HIDDEN
  - provider: pages
    github_token: $GITHUB_ACCESS_TOKEN_HIDDEN
```
