### ISSUE TITLE
npm elm package installation appears to succeed but isn't working since Trusty update

### ISSUE THREAD

**Issue by 97jaz** [travis-ci/travis-ci#7953]
We have the following in our `.travis.yml`:
```yaml
before_install:
  - npm install elm@0.18.0
before_script:
  - bundle exec rails db:test:prepare
  - bundle exec rails assets:precompile
```

But during the asset pre-compilation job, we get the following error: `Elm::Compiler::ExecutableNotFound: Elm::Compiler::ExecutableNotFound`. The npm installation step *appears* to succeed, but, as the error message indicates, the compiler isn't available.

(This did work before the Trusty update.)
