### ISSUE TITLE
allow_failures is completely ignored

### ISSUE THREAD

**Issue by karimsa** [travis-ci/travis-ci#7955]
The `allow_failures` part of my build matrix is being ignored by travis. My `.travis.yml` looks like this:

```
language: node_js
matrix:
  include:
  - node_js: 4
  - node_js: 6
  - node_js: 7
  allow_failures:
  - node_js: stable
deploy:
  provider: npm
  email: karim@alibhai.co
  api_key:
    secure: WhEVrFbEfSvff3PrhUhOk9Rr9RjtnYFlOdVtro7FPB6Agju7W4uzsA0W1urtVxqDX/IO0Fjq+PWhccTUz3OHdUzilLvpTmbcMYm9G4ssNNa+OJrp4s1QNEoTDiIavV46CQ152qq+TG82CIele0bkfHjF3KtKalNiZsZSAYKr3iECLZQLWraDVdhf3jcf0yz/B7TpPUQ4GSxFRPL9Fdhm0ptMp1C7otESd8rUm3x4CtJXsM3FzILv8ZF9mOrv9ysx/9ukkY5W/3+mEzDSqv322KFgNa6DSbEa86gFyyrtvxyfEcsgcFu8pxh1tZ/33/b4fw56qwIPbMjNyDoMF1yAgy/SpWxHDMB+yXfm1kZs6uzV5kF2HgzUrNYxk7h/o7gQ+AmWlr1s41//JtFVh+VzCDA5MlDgmXd2V4bixBwZ1MkM+28FqZwm5m7vOXNhMLwKda7JqHmfwqm1yYLjW7wzA+neqjJtQ33PZM0GS5Q5drhDmcRbhA+SaAenHeX/X0iQGQwHgwRC6OxcyOZsktPdX9vDGjN+qRYpVLUNhXJ96Hx6OBwG8tgveHbIKvJPJBSWi581cbamN37pY2M+2NUsSpsXc9r6z/Z4PtTadGkaUIsssFCnpGwBziqHhoTr27KGB+HhuwcCzmcB8rkBdKCDlfmj7guo2BuUOcw/cKhryhc=
  on:
    tags: true
    repo: hoppjs/hopp
    branch: master
```

The builds are working for the `include` part of the matrix but the `allow_failures` is not running. Here is the latest build with this config: https://travis-ci.org/hoppjs/hopp/builds/245976439
