### ISSUE TITLE
deploy: Permission denied mkdir .dpl (EACCES) with June 21 Trusty sudo change

### ISSUE THREAD

**Issue by sevagh** [travis-ci/travis-ci#7995]
Hello, since the trusty update on June 21:

>This job is running on our Trusty, sudo: required environment which was updated on Wednesday, June 21st. Read all about it on our blog and take note that you can add group: deprecated-2017Q2 in your .travis.yml file to use the previous version.

My deploy has been breaking (simple script which does a curl upload to Artifactory):

```
dpl.1
Installing deploy dependencies
!!! Script support is experimental !!!
/home/travis/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/fileutils.rb:228:in `mkdir': Permission denied @ dir_s_mkdir - .dpl (Errno::EACCES)
  ...
failed to deploy
```

When I add `group: deprecated-2017Q2`, it goes back to working.

```
language: generic

group: deprecated-2017Q2

cache:
  directories:
    - $HOME/.cargo-docker-cache

services:
  - docker

script: make -f Makefile.docker

before_deploy:
  - make -f Makefile.docker release

deploy:
  provider: script
  script: ".travis/deploy.sh"
  skip_cleanup: true
```

I can provide additional info on request. This is a private build from our private org/pro Travis account, is there a better way to file this? I can share the build logs/URLs via private support.
