### ISSUE TITLE
Should build stop when one command fail?

### ISSUE THREAD

**Issue by jcubic** [travis-ci/travis-ci#8015]
I have this in my travis file:

```yaml
language: node_js
node_js:
  - "node"
install:
  - npm install
script:
  - make
  - make lint
  - make test
after_script:
  - make coveralls
```

And it take 6 minutes to run on travis, even when I have bug in style and make lint fail (eslit), can I speed this up by breaking the script when `make lint` fail and don't run `after_script` when `script` fail? Can I use `make && make lint && make test`?

It would be nice if this was done automatically.
