### ISSUE TITLE
Firefox - error (Browser disconnected)

### ISSUE THREAD

**Issue by marclundgren** [travis-ci/travis-ci#8052]
Update
==
Updating firefox from `latest` to `latest-beta` in `.travis.yml` resolves this issue.

Failing build output
==
Errors begin at line `939`: https://travis-ci.com/rallio/revv/builds/49668512

Errors
====
```
not ok 54 Firefox - error
    ---
        message: >
            Error: Browser disconnected
            Stderr: 
             
            (firefox:5537): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed
...
```

`.travis.yml` (has not changed in months)
==
```
language: node_js
sudo: false
dist: trusty

node_js:
  - '7.8.0'

addons:
  firefox: "latest"

cache:
  directories:
  - node_modules

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm config set spin false
  - npm install -g npm@^2
  - npm install -g bower ember-cli@2.6.0

install:
  - npm install
  - bower install
```

Successful build output (local, Firefox 54)
==
https://gist.github.com/marclundgren/61411dc54d329cb96bcadbf90d95b489

[Travis Build Failures guide](https://github.com/travis-ci/travis-ci/blob/master/CONTRIBUTING.md#build-failures)
==
* 3rd party dependencies missing
* Minor differences between OS X and Linux (such as whether the filesystem is case-sensitive or not).

Neither of these items has changed for several months.
