### ISSUE TITLE
GitHub Releases causes multiple releases with linux and osx

### ISSUE THREAD

**Issue by stefanfoulis** [travis-ci/travis-ci#8053]
I'm building a linux and osx binary and have setup to automatically add a release for them on github. I've setup the name of the release to be the tag, so it is the same for both the linux and osx build.
Still travis is adding two releases with the same tag/name instead of putting both binaries on the same release.
What am I doing wrong?

```yaml
language: python
os: linux

matrix:
  include:
    - language: generic
      os: osx
      before_install:
        - brew update
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate
    - language: python
      os: linux
      python: 3.6

script: "./scripts/build-unix.sh"

deploy:
  provider: releases
  api_key:
    secure: <token>
  file_glob: true
  file: "binary/divio-*"
  skip_cleanup: true
  overwrite: true
  draft: true
  name: $TRAVIS_TAG
  on:
    repo: divio/divio-cli
    tags: true
```

I also build on appveyor for the windows binary. That works fine (it either creates a new or adds to the existing release with the same name).
