### ISSUE TITLE
Feature: allow specific tag on package published on npm

### ISSUE THREAD

**Issue by birdy-** [travis-ci/travis-ci#8055]
When you run `npm publish` you can specify `--tag` to publish with a specific tag (default is `latest`).
It would be great if an option was available in deploy section for this feature. Without this, it's a pain to tag with `after_deploy` section since in this part of the script we lost NPM credentials :(

For more information about our usecase: we are deploying prerelease in `develop` branch (x.x.x-xx) and release on our `master` branch (x.x.x). These releases are tagged as `production`.

For example:
```
deploy:
  - provider: npm
    email: 'me@mail.com'
    api_key: "4p1k3y"
    npm_tag: "production"
    on:
      branch: master
  - provider: npm
    email: 'me@mail.com'
    api_key: "4p1k3y"
    npm_tag: "preproduction"
    on:
      branch: develop
```
