### ISSUE TITLE
Travis fails to publish npm package

### ISSUE THREAD

**Issue by cebor** [travis-ci/travis-ci#8063]
With following .travis.yml it's not possible to publish npm packages:

```yml
dist: trusty
sudo: false
language: node_js
node_js:
  - '6'
  - '8'
cache: yarn
before_deploy:
  - cd ./dist
deploy:
  provider: npm
  email: *removed*
  api_key:
    secure: *removed*
  on:
    tags: true
    repo: cebor/angular-highcharts
```

Travis Log:

```log
[33mPreparing deploy[0m
NPM version: 5.0.3
Authenticated with email *removed*
Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`. See https://docs.travis-ci.com/user/deployment/#Uploading-Files.
Saved working directory and index state WIP on (no branch): c20030a bump version to 3.3.4
sh: 0: getcwd() failed: No such file or directory
mv: cannot move â€˜/home/travis/dplâ€™ to â€˜.dplâ€™: No such file or directory

travis_fold:end:dpl.2
travis_fold:start:dpl.3
[33mDeploying application[0m
[33mDeploying application[0m
NPM API key format changed recently. If your deployment fails, check your API key in ~/.npmrc.
http://docs.travis-ci.com/user/deployment/npm/
~/.npmrc size: 48
path.js:1163
          cwd = process.cwd();
                        ^

Error: ENOENT: no such file or directory, uv_cwd
    at Object.resolve (path.js:1163:25)
    at Function.Module._resolveLookupPaths (module.js:408:17)
    at Function.Module._resolveFilename (module.js:480:22)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at /home/travis/.nvm/versions/node/v8.1.3/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/home/travis/.nvm/versions/node/v8.1.3/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)

travis_fold:end:dpl.3
sh: 0: getcwd() failed: No such file or directory
fatal: Unable to read current working directory: No such file or directory
```

Full Run: https://travis-ci.org/cebor/angular-highcharts/jobs/251949098

It seems that the `dist` dir gets lost before the deploy. Don't know why, in the past all works fine.
