### ISSUE TITLE
Ruby version specified in .travis.yml is not honored after casher runs if the project has a .ruby-version file depending on preinstalled ruby versions

### ISSUE THREAD

**Issue by iriberri** [travis-ci/travis-ci#8069]
If a project has a `.ruby-version` file but a specific Ruby version is specified in the .travis.yml via the `rvm` option, this option is only having affect before casher runs. After that, the version in the `.ruby-version` file is used.

This seems to only manifests when the version in the `.ruby-version` file is not installed in the system (see `group: stable` vs `group: edge` in Trusty).

### How to reproduce:

https://github.com/iriberri/travis-linux-experiments/blob/d99436c9f23cf71562ffae5cd5b9f7fe095ce32e/.travis.yml

```
dist: trusty
sudo: required

cache: bundler

language: ruby

rvm: 2.3.3

matrix:
  include:
  - group: stable
    env: GROUP=stable
  - group: edge
    env: GROUP=edge

install: true

script:
- true
```

the project also has this .ruby-version file: https://github.com/iriberri/travis-linux-experiments/blob/d99436c9f23cf71562ffae5cd5b9f7fe095ce32e/.ruby-version

I tried several approaches, such as using `rvm: 2.3.4` and Ruby version 2.4.1 in the file, which shows the opposite behavior.
