### ISSUE TITLE
Trusty as default Linux is coming leaves no way to run PHP 5.2 jobs

### ISSUE THREAD

**Issue by ntwb** [travis-ci/travis-ci#8072]
It was announced overnight that Travis CI are going to switch to Trusty as the default:
> https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming

To not be forced to the new Trusty distro I updated my `.travis.yml` configuration to this:
```yml
sudo: false
dist: trusty

language: php

matrix:
  include:
    - php: 7.1
    - php: 5.6
    - php: 5.2
      sudo: required
      dist: precise

script: phpunit
```

Now unfortunately this leaves those who test against PHP 5.2 in a a bit of a pickle:

PHP 5.2 current availability:

• ✅ `dist: precise` with `sudo: false`
• ❌  `dist: trusty` with `sudo: false`
• ❌  `dist: precise` with `sudo: required`

The only workaround I see currently is not specify `sudo: required` for the PHP 5.2 job, though this will be overwritten beginning September 2017 if all goes to plan pe the announcment:
> The tentative plan is to begin overwriting configurations that specify `dist: precise` to include `sudo: required` beginning in September 2017.

Is there any other solution to make available PHP 5.2 in a Travis CI job?
