### ISSUE TITLE
Builds not triggered

### ISSUE THREAD

**Issue by stoffeastrom** [travis-ci/travis-ci#808]
Since I changed the repository (https://github.com/stoffeastrom/touche) default branch to gh-pages no builds are triggered with test hook or commit. I've tried syncing with github, doing on/off but still doesn't work. Maybe the account needs a reset?

My travis file looks like this;

``` YAML
language: node_js
node_js:
  - 0.8
branches:
  only:
    - gh-pages
```

and as I understand it this should work.

Br Christoffer
