### ISSUE TITLE
Trusty image prevents port 5432 from being used

### ISSUE THREAD

**Issue by MrHen** [travis-ci/travis-ci#8087]
I have the following travis file:

```
language: generic

services:
  - docker

script:
  - docker-compose up --exit-code-from test test
```

The docker-compose file contains the following:

```
version: '2'
services:
  postgres:
    image: postgres:9.4
    ports:
      - "5432:5432"

  base:
    build: ./
    working_dir: /worker/
    volumes:
      - ./:/worker
    ports:
      - "9299:9299"
    environment:
      - DB_PORT=5432
      - DB_NAME=foo
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_ADAPTER=postgres
      - DB_POOL=5

  worker:
    extends:
      service: base
    command: bundle exec shotgun -p 9299 --host 0.0.0.0
    links:
      - postgres:postgres.dev
    environment:
      - RACK_ENV=development
      - DB_HOST=postgres.dev

  test:
    extends:
      service: base
    command: rake db:load test rubocop
    links:
      - postgres:postgres.test
    environment:
      - RACK_ENV=test
      - DB_HOST=postgres.test
```

The build fails with the following error:

```
Creating foo_postgres_1 ... 
Creating foo_postgres_1
ERROR: for foo_postgres_1  Cannot start service postgres: driver failed programming external connectivity on endpoint foo_postgres_1 (01f07841aa1f327961519938d327bd293178bae55cef620d92e0deb7f2fc023b): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use
ERROR: for postgres  Cannot start service postgres: driver failed programming external connectivity on endpoint foo_postgres_1 (01f07841aa1f327961519938d327bd293178bae55cef620d92e0deb7f2fc023b): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use
ERROR: Encountered errors while bringing up the project.
The command "docker-compose up --exit-code-from test test" exited with 1.
```

If I rollback the Trusty update, it succeeds:

```
group: deprecated-2017Q3
language: generic

services:
  - docker

script:
  - docker-compose up --exit-code-from test test
```

It appears that something is holding port 5432 on the trusty image? Is this intended?

**Comment by localzjaz** [comment]
Had the same issue with the update this week: I'm working around it through this comment https://github.com/travis-ci/travis-ci/issues/4842#issuecomment-311527059

**Comment by MrHen** [comment]
The rollback target I was using stopped working today for some unknown reason but I solved the problem a different way. There is no particularly good reason to expose the `postgres` container on localhost since I was linking the `test` app directly. I was simply misunderstanding how docker ports worked.

I replaced the docker-compose file with the following and things worked just fine:

```
version: '2'
services:
  postgres:
    image: postgres:9.4
    ports:
      - "5432"

  base:
    build: ./
    working_dir: /worker/
    volumes:
      - ./:/worker
    ports:
      - "9299:9299"
    environment:
      - DB_PORT=5432
      - DB_NAME=foo
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_ADAPTER=postgres
      - DB_POOL=5

  worker:
    extends:
      service: base
    command: bundle exec shotgun -p 9299 --host 0.0.0.0
    links:
      - postgres:postgres.dev
    environment:
      - RACK_ENV=development
      - DB_HOST=postgres.dev

  test:
    extends:
      service: base
    command: rake db:load test rubocop
    links:
      - postgres:postgres.test
    environment:
      - RACK_ENV=test
      - DB_HOST=postgres.test
```
