### ISSUE TITLE
Build fail, when I push some commits to a pr

### ISSUE THREAD

**Issue by wpzero** [travis-ci/travis-ci#8094]
Our teams other people don't have this problem, But I have. Almost, only the first time, I create the pr, this will trigger the ci. when I push some commits to this pr, all will not trigger the ci. I have to reopen the pr to trigger it. I don't what the problem, I don't you can help me find the problem.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by wpzero** [comment]
https://github.com/mycolorway/zhiren/pull/6083 this a private ,  I don't know if you can access it.

**Comment by wpzero** [comment]
I reopen many times, :), the only different thing, I don't have local branch, I modify My .git/config
as follow:
```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = git@github.com:mycolorway/zhiren.git
	fetch = +refs/heads/*:refs/remotes/*
```
I just push commit hash to remote branch. but I think this will not affect the ci.

**Comment by BanzaiMan** [comment]
Which build should we look at? If you'd rather discuss this in private, please close this issue and send email to support@travis-ci.com with details.

**Comment by BanzaiMan** [comment]
Is your PR up to date with the base branch?

**Comment by wpzero** [comment]
up to date with the base branch? You mean I need rebase on base branch. yeah 

<img width="735" alt="screen shot 2017-07-14 at 10 40 06 pm" src="https://user-images.githubusercontent.com/7711386/28216798-6fa6143a-68e5-11e7-917a-a2d700a56911.png">

master is the base branch, and HEAD is the pr branch.

**Comment by wpzero** [comment]
And what "not included per configuration" mean?

**Comment by BanzaiMan** [comment]
@wpzero It means that, in your branch's `.travis.yml`, there is a `branches` key that prevents your branch build from starting. https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches

**Comment by wpzero** [comment]
@BanzaiMan ,thx, I will read it carefully, I hope I can resolve the problem, very thx.

**Comment by wpzero** [comment]
@BanzaiMan the up build you can look, I think ok. And I checked the configuration, I think this is ok,as follow:

```
sudo: false #use container-based infrastructure
language: ruby

branches:
  only:
    - master
    - v2.0

cache:
  bundler: true

services:
  - redis-server

install:
  - bundle config gems.contribsys.com dddddddd
  - bundle install --without development --path vendor/bundle

before_script:
  - export TZ=Asia/Shanghai
  - date -R
  - mv config/application.yml.sample config/application.yml
  - mv config/database.yml.sample config/database.yml
  - mkdir tmp

script:
  - bundle exec rails db:create db:migrate RAILS_ENV=test
  - ENABLE_COVERAGE_REPORT=true bundle exec rails test -f

addons:
  code_climate:
    repo_token: xxxx
notifications:
  slack:
    secure: xxxx

```

And I found this repo has github codeowner settings like this:

```
/app/views/xxx/*    @ichord @chunlea
/app/models/xxxx/*    @ichord @chunlea
/app/controllers/xxxx/*    @ichord @chunlea
/app/jobs/xxxx/*    @ichord @chunlea

```

And my commit is about the xxx code, I don't know if this will affect the ci.

**Comment by wpzero** [comment]
@BanzaiMan I read the document, I fount this https://docs.travis-ci.com/user/pull-requests/, I don't know what "Rather than test the commits that have been pushed to the branch the pull request is from, we test the merge between the origin and the upstream branch." mean?

what the merge? and what origin? and upstream branch? 
for example I make a pr from feature/add-image-upload to master

so what origin ? master? 

and what upstream ? the upstream is not relative to my local branch?

I am so confused about that.

**Comment by wpzero** [comment]
@BanzaiMan I am not sure if I don't set local branch will affect the ci? 
I don't set like this:

```
[branch "master"]
        remote = origin
        merge = refs/heads/master
[branch "br01"]
        remote = origin
        merge = refs/heads/br01-remote
[branch "br03"]
        remote = origin
        merge = refs/heads/br03
```

I just directly ``git push origin -u HEAD:refs/heads/feature/add-image-upload`` or use hashcode

``git push origin -u hashcode:refs/heads/feature/add-image-upload``

I think this will not affect the ci.

This config should only affect my local ``git push`` or ``git pull`` command performance.

I think the import thing should be commit node not branch.

**Comment by BanzaiMan** [comment]
Local git configuration does not have effect on whether or not we approve the build request.

What is important is the content of `.travis.yml`. According to https://github.com/travis-ci/travis-ci/issues/8094#issuecomment-315495311, you have:

```yaml
branches:
  only:
    - master
    - v2.0
```

So your Pull Request builds (e.g., with the base branch `master` and head `yixin-migrate-cross-leaves`) will be approved and processed, but the push build to the topic branch (say, `yixin-migrate-cross-leaves`) will be rejected.

This 

---

The question from https://github.com/travis-ci/travis-ci/issues/8094#issuecomment-315497014:

> Or this mean they will test the merge commit node produced by feature/add-image-upload automatically?

Yes, that is what PR builds do. We test the pseudo commit that is the resultant of the merge.
