### ISSUE TITLE
Python pexpect module import fail with latest Trusty environment 

### ISSUE THREAD

**Issue by gbtami** [travis-ci/travis-ci#8108]
[https://github.com/pychess/pychess/blob/master/.travis.yml](url) without group: deprecated-2017Q3 fails to import pexpect. It was OK before Trusty update.

From failing log https://travis-ci.org/pychess/pychess/builds/249937206
```
$ sudo pip3 install pexpect
Downloading/unpacking pexpect
  Downloading pexpect-4.2.1-py2.py3-none-any.whl (55kB): 55kB downloaded
Downloading/unpacking ptyprocess>=0.5 (from pexpect)
  Downloading ptyprocess-0.5.2-py2.py3-none-any.whl
Installing collected packages: pexpect, ptyprocess
Successfully installed pexpect ptyprocess
Cleaning up...
install.4
3.33s$ virtualenv --python=$PYTHON --system-site-packages _venv
Running virtualenv with interpreter /opt/python/3.6.1/bin/python3
Using base prefix '/opt/python/3.6.1'
New python executable in /home/travis/build/pychess/pychess/_venv/bin/python3
Also creating executable in /home/travis/build/pychess/pychess/_venv/bin/python
Installing setuptools, pip, wheel...done.
install.5
0.01s$ source _venv/bin/activate
0.51s$ xvfb-run -a $PYTHON ./setup.py build sdist
Traceback (most recent call last):
  File "./setup.py", line 130, in <module>
    exec(open("pgn2ecodb.py").read())
  File "<string>", line 8, in <module>
  File "lib/pychess/Savers/pgn.py", line 13, in <module>
    import pexpect
ModuleNotFoundError: No module named 'pexpect'
```

**Comment by furushchev** [comment]
We have the similar issue from the latest update on travis image.
@BanzaiMan 
Is there any "right" way to write in `.travis.yml` for using system python?
Since our projects heavily depend on system python, we don't want to use other python than system at all.

**Comment by bogdanap** [comment]
I realize this reply comes very late, but hoping it might still be useful for some:

@gbtami: since you are using `language: generic` and not `language: python`, no virtualenv is created, so you need to use `pip install --user` for python packages.

@furushchev Assuming you don't want to use the virtualenv we automatically create for the supported versions of Python (or just want to create your own), you can try using `language: generic`, which shouldn't do any additional setup (and only provide the default python versions supplied with Ubuntu)

**Comment by gbtami** [comment]
@bogdanap thx for suggestion! Finally I understand that I can drop all virtualenv usage because pygobject has no packages on pypi so I have to use system python anyway.
This .rtavis.yml works OK now:

```
# group: deprecated-2017Q2
language: generic

matrix:
  include:
    - os: linux
      sudo: required
#      dist: trusty
      language: generic
      env: PYTHON="python3" PACKAGES="python3-cairo python3-gi python3-gi-cairo python3-sqlalchemy python3-psutil python3-pip"

install:
 - sudo apt-get update -q
 - sudo apt-get install -y xvfb gobject-introspection gir1.2-glib-2.0  gir1.2-gtk-3.0 gir1.2-rsvg-2.0 gir1.2-gtksource-3.0 $(echo $PACKAGES)
 - sudo pip3 install pexpect
 - sudo pip3 install coverage
 - sudo pip3 install codecov
 - sudo pip3 install flake8
# - virtualenv --python=$PYTHON --system-site-packages _venv
# - source _venv/bin/activate

script:
 - /usr/local/bin/flake8 --exclude=lib/pychess/external/ lib/pychess/
 - xvfb-run -a $PYTHON ./setup.py build sdist
 - cd testing
 - PYTHONPATH=../lib xvfb-run -a coverage run --omit=../lib/pychess/external/* --source ../lib -m unittest discover -p "*.py"
 - codecov
```
