### ISSUE TITLE
[Dart] Command-line args for dartfmt?

### ISSUE THREAD

**Issue by Qwerp-Derp** [travis-ci/travis-ci#8110]
Currently, `dartfmt` doesn't support the use of extra command-line arguments, and therefore applies to the whole folder.

I only want `dartfmt` to format a specific folder, `lib/src` in my project [here](https://github.com/Qwerp-Derp/bullseye).

Through the command-line, I would do

    dartfmt -n lib/src

But there isn't an option to add command-line args to `dartfmt` in `.travis.yml`.

**Comment by Keksinautin** [comment]
Hi to all. Any news about the issue?

**Comment by a14n** [comment]
The `dartfmt` task does not support such command-line arguments. You have to add this command in a custom `script` or `before_script`. For instance:

```yaml
language: dart
before_script: dartfmt -n lib/src
dart_task:
- test
- dartanalyzer: --fatal-warnings lib
```
