### ISSUE TITLE
Sudo fails on new Trusty VM

### ISSUE THREAD

**Issue by tuckermcclure** [travis-ci/travis-ci#8129]
I have no real experience with CI services, but I've had two knowledgeable people ask me to write up this issue.

I have a simple `.travis.yml` file that doesn't specify either `dist` or `sudo`. I created this today. By default, my runs got a Trusty VM. My application has dependencies that call `sudo apt-get install <whatever>`, and this failed with the following:

```
INFO: Building HDF5
/usr/bin/sudo: 1: /usr/bin/sudo: [[: not found
================================[ ERROR: HDF5 ]=================================
LoadError: failed process: Process(`sudo apt-get install hdf5-tools`, ProcessExited(1)) [1]
while loading /home/travis/.julia/v0.6/HDF5/deps/build.jl, in expression starting on line 44
```

According to tkelman over at Julia's Discourse page:

> What that looks like to me is that /usr/bin/sudo in the VM your job got routed to was probably replaced by Travis with a bash script, but it’s trying to be executed by /bin/sh which is dash on Ubuntu so doesn’t recognize the bashism [[ which must be somewhere in an if statement in the (hypothetical) bash script. Sounds like a bug that should be reported on Travis CI’s issue tracker.

Using either `sudo: required` or `dist: precise` in my `.travis.yml` file fixed the problem.

If I've missed something, please feel free to close the issue.

**Comment by BanzaiMan** [comment]
If your repo requires `sudo` indirectly and if we cannot detect its use, the builds are routed to the default infrastructure, which is containers. There, `sudo` is not available, as @tkelman points out. These differences are explained in https://docs.travis-ci.com/user/reference/precise/#Virtualization-environments.

It is not clear to me why `dist: precise` would solve your problem; maybe the dependency is already met there?

**Comment by tkelman** [comment]
Yep so the precise image happens to have libhdf5 already installed, the trusty image doesn't. But I went and looked and indeed `/usr/bin/sudo` is a shell script in the container based workers (https://travis-ci.org/JuliaIO/HDF5.jl/builds/255638841) but it's missing a `#!/bin/bash` shebang line to indicate that it uses bashisms. I'd recommend Travis add a shebang and/or remove the bashism from the script if it's not too much trouble to do so.

**Comment by BanzaiMan** [comment]
@tkelman Thanks for the extra information. We can add the shebang line, certainly.

**Comment by tkelman** [comment]
Though I wonder why in the log I posted the message still came across, when it may have been missing from @tuckermcclure's run?

**Comment by BanzaiMan** [comment]
The shebang line fix has been deployed.

@tuckermcclure Not clear to me how you got into that situation before. If it's still happening to you, please point to the build log URL that shows the problem. If it's eradicated, please close this issue.

**Comment by BanzaiMan** [comment]
Can this be closed now?

**Comment by tuckermcclure** [comment]
Sorry for the delay; was out of the office. Things are fine on my end. I don't know how I got into the situation. It was a recently-created repo and Travis account. The offending .travis.yml file was:

```
## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999

after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("HDF5Logger")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("HDF5Logger")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
```

For me, the fix was simply to add in a `sudo: required` line. My part now works, and that's all I can really comment on. I'm perfectly happy closing the ticket; was reporting for others' sake.
