### ISSUE TITLE
`sonarcloud:` is gone from my run config.

### ISSUE THREAD

**Issue by jgebal** [travis-ci/travis-ci#8140]
Our build is failing on:
[sonar-scanner: command not found](https://travis-ci.org/utPLSQL/utPLSQL/jobs/256140540#L4093)
The travis.yml contains config:
```
sudo: required
language: python

addons:
  apt:
    packages:
      - unzip
      # Java8 Required for Sonar and SQLCL
      - oracle-java8-installer
      - oracle-java8-set-default
  sonarcloud:
    organization: utplsql
    token:
      secure: ${SONAR_TOKEN}
    branches:
      - develop
      - master
...
```
But the [job config](https://travis-ci.org/utPLSQL/utPLSQL/jobs/256140540/config) is showing:
```
  "sudo": "required",
  "language": "python",
  "addons": {
    "apt": {
      "packages": [
        "unzip",
        "oracle-java8-installer",
        "oracle-java8-set-default"
      ]
    }
  },
  "services": [
    "docker"
  ],
```
We've recently changed the `sonarqube` to `sonarcloud` in the config entry.

Can you advice why the jobs are failing?
