### ISSUE TITLE
"nvm use" and "nvm exec" are not available

### ISSUE THREAD

**Issue by evan-scott-zocdoc** [travis-ci/travis-ci#8159]
nvm provides the ability to execute a script within a different version of node via `nvm run {version} {script}` and `nvm exec {version} {script}`. The semantics are slightly different, but that's unrelated.

It seems like the permissions on the required executable are not granted for the default travis user:

```
$ nvm run 6 npm run lambda:publish
Running node v6.9.4 (npm v3.10.10)
/home/travis/.nvm/nvm.sh: line 2920: /home/travis/.nvm/nvm-exec: Permission denied
```

If I add `sudo` before it, it says nvm cannot be found.

Here's a stripped down version of our yml:

```yml
sudo: required
language: node_js
node_js: 8
notifications:
    email: false
branches:
  only:
    - master
services:
  - docker
env:
   global:
     - DOCKER_VERSION=1.10.1-0~trusty
     - DOCKER_COMPOSE_VERSION=1.6.0
     - DOCKER_CONTAINER=dist_search-service
install:
  - npm install --ignore-scripts
  - npm prune
script:
 - nvm run 6 npm run lambda:publish
```
