### ISSUE TITLE
Build hangs when I set wrong environment variable

### ISSUE THREAD

**Issue by bartlomiejdanek** [travis-ci/travis-ci#817]
For instance

``` yaml
language: ruby
rvm:
  - 1.9.3
env:
  - DB=postgres
  - RAILS_ENV=test
  - CUSTOM_FIREFOX=/usr/local/firefox/firefox-bin # <- this file doesn't exist - yet...
before_script:
  - "wget http://download.cdn.mozilla.net/pub/mozilla.org/firefox/releases/13.0.1/linux-x86_64/en-GB/firefox-13.0.1.tar.bz2"
  - "bzip2 -dc firefox-13.0.1.tar.bz2 | tar -xf -"
  - "sudo mv firefox /usr/local/"
  - "psql -c 'create database db_name;' -U postgres"
  - "mv config/.database.travis.yml config/database.yml"
  - "bundle"
  - "bundle exec rake db:structure:load db:seed"
install: sudo apt-get install xvfb
script: "bundle exec rake ci"
```
