### ISSUE TITLE
Upgrade Docker for multi-stage build support

### ISSUE THREAD

**Issue by MrSaints** [travis-ci/travis-ci#8181]
We recently updated our repository to use a multi-stage build in Docker. The build failed, and it looks like it is because Travis CI is using `Version:      17.03.1-ce`, but multi-stage build was introduced in `17.05.0-ce`. It would be nice to upgrade Docker in Travis CI (there might already be a way to do so, but I am not sure how).

**Comment by BanzaiMan** [comment]
You can update the `docker-ce` package as follows:

```yaml
addons:
  packages:
    - docker-ce
⋮ # rest
```

The pre-installed packages will be updated as time goes on.

**Comment by MrSaints** [comment]
Cool, that did the trick. Cheers.

**Comment by gaieges** [comment]
@BanzaiMan 's response wasn't quite clear (adding just that didn't work for me), so I'll amend that for others. It should be:

```
addons:
  apt:
    packages:
      - docker-ce
```
