### ISSUE TITLE
Github Release Uploading claims branches are not supported... but they are

### ISSUE THREAD

**Issue by ezyang** [travis-ci/travis-ci#8185]
In https://docs.travis-ci.com/user/deployment/releases/ it says "Please note that deploying GitHub Releases works only for tags, not for branches." But actually, it seems Travis makes an anonymous tag in this case, for example https://github.com/ezyang/ci-experiments/releases

**Comment by BanzaiMan** [comment]
I've confirmed this bug.

The unwanted releases must be removed by the user, unfortunately. You can do this manually, or use the API https://developer.github.com/v3/repos/releases/#delete-a-release.

The following Ruby script should do the job as well (assuming that you have done `gem install octokit` and it is available):

```ruby
# /usr/bin/env ruby
require "octokit"

API_TOKEN = YOUR_API_TOKEN # with either "public_repo" or "repo" scope
api = Octokit::Client.new(:access_token => API_TOKEN)
releases = api.releases YOUR_REPO_SLUG # of the form OWNER/REPO
releases.select {|rel| rel.tag_name.start_with? "untagged"}.map(&:url).each {|url| api.delete_release(url)}
```

**Comment by BanzaiMan** [comment]
Here's what's happening.

During the deployment, we create a draft release (`{:draft => true}`). GitHub API happily creates this draft release, even when there is no tag associated with the present commit and we pass an empty string as the required `tag_name` argument, and gives the name `untagged-HEX`.  (See https://github.com/travis-ci/dpl/pull/390 for the rationale behind this behavior.)

In contrast, if we attempt to create a release without `{:draft => true}`, the attempt to create a release would (basically) fail, and we would end up with an exception.

Presently, when we are not working on a tagged commit (i.e., when `$TRAVIS_TAG` is empty), we still carry on with the deployment, but I reckon this is not the right behavior. We should just bail.

**Comment by BanzaiMan** [comment]
We revert https://github.com/travis-ci/travis-build/pull/1145 with https://github.com/travis-ci/travis-build/pull/1146.

**Comment by BanzaiMan** [comment]
We will leave this behavior as before, and document the deployment provider a little better.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/docs-travis-ci-com/pull/1383 explains this behavior, and effectively closes it. Your feedback on the documentation PR is appreciated.

**Comment by chowdaryidavalapati** [comment]
Github release is becoming as draft when I use Travis.
```
language: python
python:
- '2.7'
install:
- pip install .
script:
- python -m doctest -v Test/Ramips.py
deploy:
  provider: releases
  tag_name: 0.3
  name: Test-0.3
  skip_cleanup: true
  api_key:
    secure: [secure key]
  file:
    - README.md
    - setup.py
    - __init__.py
    - Ramips.py
  on:
    repo: chowdaryidavalapati/Test
```
https://i.stack.imgur.com/weZMe.jpg
