### ISSUE TITLE
Timeout error with Android's emulator

### ISSUE THREAD

**Issue by AllanWang** [travis-ci/travis-ci#8188]
I've tried a whole bunch of combinations to get the emulator to install, and I finally settled on the following configuration (based on the travis file for google maps):

```yml
...
env:
  global:
  - ANDROID_API_LEVEL=26
  - EMULATOR_API_LEVEL=22
  - ANDROID_BUILD_TOOLS_VERSION=26.0.1
  - ANDROID_ABI=armeabi-v7a
  - ANDROID_TAG=google_apis
#  - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)
android:
  components:
  - tools # to get the new `repository-11.xml`
  - platform-tools
  - tools # to install Android SDK tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - extra-android-m2repository
  - extra-google-m2repository
  - android-$EMULATOR_API_LEVEL
  - sys-img-armeabi-v7a-google_apis-$EMULATOR_API_LEVEL
  licenses:
  - ".+"
...
before_script:
- echo no | android create avd --force -n test -t "android-"$EMULATOR_API_LEVEL --abi $ANDROID_ABI --tag $ANDROID_TAG
- emulator -avd test -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &
...
```

However, it seems like the emulator either doesn't start or doesn't properly launch, as I get the following error after its creation:

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself
```

this is preceded by 

```
qemu-system-armel: -audio: invalid option
```

but I'm not sure if that's related.

The build log can be found [here](https://travis-ci.org/AllanWang/KAU/builds/259153118) and the previous commits and tests can be found [ere](https://github.com/AllanWang/KAU/commits/travis-instrumentation-test)

I'm also going to link to another android project [here](https://travis-ci.org/anjlab/android-inapp-billing-v3/jobs/256795558), which has a much simpler travis config and works I'm not sure if the issue is me using android-26, but those configs didn't work for me.

**Comment by sbaar** [comment]
I've seen this issue on more than the 26 api level, including  24 (why is there no arm image for 25 on travis?). Only 23 gets past this, but then I get the 0 tests found error, when it finds the tests on my local machine.

**Comment by extmkv** [comment]
I have same problem here. @AllanWang you found the solution?

**Comment by AllanWang** [comment]
Unfortunately not, but I haven't tried in a while

**Comment by joaomneto** [comment]
Also have the same problem. 23 works?

**Comment by radzio** [comment]
Have anyone found any solution?

**Comment by comodoro** [comment]
I may have found a solution. According to this question:

https://stackoverflow.com/questions/40272884/running-android-emulator-with-noaudio-option-returns-qemu-system-i386-exe-au

the switch `-no-audio` no longer works on newer emulators. As (sort of) suggested in the answer, I changed the emulator invocation to 

`QEMU_AUDIO_DRV=none emulator -avd test -no-window &`

and the emulator appears. I get failed tests, but it may not be related as according to the log they are run now.

By the way, is switching audio off for Travis even necessary?

**Comment by kashifmin** [comment]
I ran into a similar situation. But after hours of running Travis builds on debug mode, I could figure out a working combination.
Here's my build config:
```
language: android
sudo: required
jdk: oraclejdk8

before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
 directories:
 - $HOME/.gradle/caches/
 - $HOME/.gradle/wrapper/

env:
 global:
 - ANDROID_API=25
 - EMULATOR_API=24
 - ANDROID_BUILD_TOOLS=25.0.2
 - ADB_INSTALL_TIMEOUT=5 # minutes

android:
 components:
 - tools
 - platform-tools
 - build-tools-$ANDROID_BUILD_TOOLS
 - android-$ANDROID_API
 - android-$EMULATOR_API_LEVEL
 - extra-google-m2repository
 - extra-android-m2repository # for design library
 - addon-google_apis-google-25 # google play services
 - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
 - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL # the fix!

 licenses:
 - android-sdk-preview-license-.+
 - android-sdk-license-.+
 - google-gdk-license-.+

before_install:
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- chmod +x gradlew
- echo y | android update sdk --no-ui --all --filter "tool,extra-android-m2repository,extra-android-support,extra-google-google_play_services,extra-google-m2repository"
- echo y | $ANDROID_HOME/tools/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
- ./gradlew dependencies || true # DON'T ADD unless you are getting "Install missing components using SDK manager"
#Source: https://medium.com/@oldergod/constraint-layout-and-circleci-travis-d50342696d2

before_script:
- echo "y" | android update sdk -a --no-ui --filter android-24
- echo "y" | android update sdk -a --no-ui --filter sys-img-armeabi-v7a-android-24
- android list targets | grep -E '^id:' | awk -F '"' '{$1=""; print $2}' # list all targets
- echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
- emulator -avd test -no-skin -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &

script:
- "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"
```
