### ISSUE TITLE
Missing java command when using openjdk6 with Trusty VM

### ISSUE THREAD

**Issue by xerial** [travis-ci/travis-ci#8199]
java command is not available when using openjdk6:
 - https://travis-ci.org/xerial/sqlite-jdbc/jobs/260357576

Because of this maven (mvn) doesn't work with openjdk6.

According to the file list of openjdk6-jdk package for Trusty, java command is totally missing:
https://packages.ubuntu.com/en/trusty/amd64/openjdk-6-jdk/filelist

**Comment by BanzaiMan** [comment]
So, OpenJDK 6 does not work on Trusty at all?

**Comment by abelsromero** [comment]
> So, OpenJDK 6 does not work on Trusty at all?

Nor 6, nor 7

**Comment by rosslamont** [comment]
I'm having this issue too for my fork of mojo-hays xml-maven-plugin.  Seems the original must still be using precise, but my new fork picked trusty.  I can't very easily justify modifying .travis.yml as it works fine for those guys.

**Comment by felixbarny** [comment]
Any updates on this? Will java 6 eventually be supported on trusty vms?

**Comment by BanzaiMan** [comment]
OpenJDK 6 was removed from our Trusty images to save space.

If you need it, you can install `openjdk-6-jdk` package (which will also install `openjdk-6-jre-headless`, which provides the `java` command):

```yaml
addons:
  apt:
    packages:
      - openjdk-6-jdk

jdk: openjdk6
```

**Comment by BanzaiMan** [comment]
If you need to use this in a build matrix, remove `openjdk6` from `jdk` key, then add:

```yaml
matrix:
  include:
    - addons:
        apt:
          packages:
            - openjdk-6-jdk
      jdk: openjdk6
```
