### ISSUE TITLE
PHPUnit has problems with PHP 7.0 and dist:trusty

### ISSUE THREAD

**Issue by s3b4stian** [travis-ci/travis-ci#8211]
After Trusty replaced Precise, the build with PHP 7.0 began to fail, others work fine.
Phpunit seems the problem.
Build Log: [https://travis-ci.org/linna/app/jobs/261545618](https://travis-ci.org/linna/app/jobs/261545618)

.travis.yml file:
```yml
language: php
php:
- 7.0
- 7.1
- 7.2
- nightly

matrix:
  allow_failures:
  - php: nightly
  - php: 7.2

before_script:
- composer install

script: 
- phpunit
```
