### ISSUE TITLE
R language apt_package broken?

### ISSUE THREAD

**Issue by gdkrmr** [travis-ci/travis-ci#8220]
@craigcitro, @hadley, and @jimhester

```yaml
apt_package:
  - coinor-libclp-dev
```
 did not work for me, I had to do 
```yaml
addons:
  apt:
    packages:
      - coinor-libclp-dev
```
is this reproducible?
