### ISSUE TITLE
allow deploy on: r: release (or expose another environmental variable)

### ISSUE THREAD

**Issue by maxheld83** [travis-ci/travis-ci#8224]
cc @jimhester @craigcitro (sorry for the flood).

I'm trying to deploy from only those jobs in a matrix builds with the current `r: release`. 

I understood from #5841 and @BanzaiMan's latest comment that something like this should work:

```
deploy:
    provider: pages
    github_token: $GITHUB_PAT
    local_dir: _site/
    skip_cleanup: true
    on:
      branch: master
      condition: "$TRAVIS_OS_NAME = linux"
      r: release
```

This, however, appears not to work, but skips deploy on [*all* jobs](https://travis-ci.org/maxheld83/pensieve/builds/262257912) with `Skipping a deployment with the pages provider because this is not on the required runtime`, including where `r: release`.

By contrast, a manual condition works just fine, and skips on [all *except* the release job](https://travis-ci.org/maxheld83/pensieve/builds/262268167), as intended.

```
deploy:
    provider: pages
    github_token: $GITHUB_PAT
    local_dir: _site/
    skip_cleanup: true
    on:
      branch: master
      condition: "$TRAVIS_OS_NAME = linux && $TRAVIS_R_VERSION = '3.4.1'"
```

That's a little inconvenient, however, because it'd have to change the version numbers quite frequently.

---

It would be great if R travis could support the `on: r: release` syntax for runtimes, as some of the other languages.

Alternatively, would it be possible to simply **expose** the `devel`/`release`/ `oldrel` flags as an **environment variable**, say `$TRAVIS_R_CHANNEL`?
