### ISSUE TITLE
Unable to access Sauce Labs with the JWT Addon

### ISSUE THREAD

**Issue by jeremypress** [travis-ci/travis-ci#8237]
Hi,
When using the JWT addon, my access_key is set to undefined. 

`You used username 'my-username' and access key 'undefined' to authenticate, which are not valid Sauce Labs credentials.`

travis.yml file
```
language: node_js
node_js:
- '6'
addons:
  sauce_connect:
    username: "my-username"
  jwt:
    secure: "output from travis encrypt --add addons.jwt SAUCE_ACCESS_KEY=my-access-key"
before_script:
- python -m SimpleHTTPServer &
- sleep 2
script: yarn run ci
cache: yarn
```

And here's how I access said variables  (using node)
`process.env.SAUCE_USERNAME`
`process.env.SAUCE_ACCESS_KEY`

Additional info:
this change is being submitted as a PR, but from my understanding this should run fine because it uses the JWT addon. I tried the environment variables with both quotes and no quotes in the travis.yml. Is there anything additional I need to do on the sauce lab side?

Thanks for the help!
