### ISSUE TITLE
PHP Memory Limit Errors During Travis Builds

### ISSUE THREAD

**Issue by kumana4** [travis-ci/travis-ci#8241]
Hi All

I'm getting memory allocation issues while running the travis build. I made some changes in travis.yml file but still I'm facing the issues.
I updated the memory limit in travis.yml file, I added these lines in before_install.

echo "memory_limit = 2048M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
echo "mysqlnd.mempool_default_size = 16000" >> ~/.phpenv/versions/$(phpenv version- name)/etc/php.ini
I tried in different way to add the memory allocation using travis.php.ini file. I added these lines in before_script in travis.yml file

Increase Memory Limit
phpenv config-add travis.php.ini
ERROR:
phpenv: no such command `config-add'
The command "phpenv config-add travis.php.ini" failed and exited with 1 during .

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by kumana4** [comment]
Sorry, I'm not able to provide the lo due to security concerns. I'm getting the Following error while increasing the memory in travis.yml.
Error:
phpenv: no such command `config-add'
The command "phpenv config-add travis.php.ini" failed and exited with 1 during .

Travis.yml:
```
sudo: required
language: php
dist: trusty

php:
  - 5.6

matrix:
  fast_finish: true

cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "$HOME/.npm"
  - "$HOME/.nvm"
  - "vendor"

  
before_install:
  # Enable aliases for non-interactive shell.
  # Additional PHP config
  - shopt -s expand_aliases
  - composer selfupdate
  - sudo apt-get install -y xvfb
  - dpkg -L xvfb
  - sudo cp $TRAVIS_BUILD_DIR/scripts/xvfb /etc/init.d/
  # Disable xdebug.
  # - sudo apt-get install -y xvfb
  # - phpenv config-rm xdebug.ini
  # - cat /home/travis/.phpenv/versions/5.6/etc/conf.d/travis.ini
  # - cat /home/travis/.phpenv/versions/5.6/etc/php.ini
  - echo "memory_limit = 2048M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "mysqlnd.mempool_default_size = 16000" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  # - grep "memory" ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  # - phpenv config-rm xdebug.ini
  # Enable $_ENV variables in PHP.
  - echo 'variables_order = "EGPCS"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # Ensure that always_populate_raw_post_data PHP setting: Not set to -1 does not happen.
  - echo "always_populate_raw_post_data = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - git config --global user.name "Travis-CI"
  - git config --global user.email "noreply@travis-ci.org"
  - sudo /etc/init.d/mysql start
  - mysql -u root -e "CREATE DATABASE drupal; CREATE USER 'drupal'@'localhost' IDENTIFIED BY 'drupal'; GRANT ALL ON drupal.* TO 'drupal'@'localhost';"

install:
  # Load composer dependencies.
  - composer validate --no-check-all --ansi
  - composer install
  - export PATH=$TRAVIS_BUILD_DIR/vendor/bin:$PATH
  # Install proper version of node for front end tasks.
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  - export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh"
  - source ~/.bashrc
  - nvm install 4.4.1
  # - nvm install 4.4.1
  - nvm use 4.4.1
  # Initialize drupal console default configuration.
  #- drupal init
  # Initialize xvfb (see https://docs.travis-ci.com/user/gui-and-headless-browsers)
  # Installs chromedriver to vendor/bin.
  - ./vendor/acquia/blt/scripts/linux/install-chrome.sh $TRAVIS_BUILD_DIR/vendor/bin
  # Use JDK 8.
  - jdk_switcher use oraclejdk8

before_script:
# Increase Memory Limit
  - phpenv config-add travis.php.ini  
# Clear drush release history cache, to pick up new releases.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  #
  - rm -f ~/.drush/cache/download/*---updates.drupal.org-release-history-*
  # Verify that no git diffs (caused by line ending variation) exist.
  # - git diff --exit-code
  # The local.hostname must be set to 127.0.0.1:8888 because we are using drush runserver to run the site on Travis CI.
  - yaml-cli update:value blt/project.yml project.local.hostname '127.0.0.1:8888'
  # Make temp dir writable for drupal.
  - "mkdir -m 755 -p docroot/sites/default/files/tmp/"

script:
  - blt -Dbehat.run-server=true -Dcreate_alias=false -Dbehat.launch-phantom=true ci:build:validate:test -Dblt.verbose=true

```
