### ISSUE TITLE
Cannot switch to oraclejdk8 using matrix

### ISSUE THREAD

**Issue by ice1000** [travis-ci/travis-ci#8247]
https://travis-ci.org/ice1000/algo4j/jobs/263985456

Key information in the config file:

```yml
matrix:
  include:
    - language: cpp
      compiler:
        - gcc
      os:
       - linux
    - language: java
      jdk:
        - oraclejdk8
```

Message:

```
$ jdk_switcher use ["oraclejdk8"]
Sorry, but JDK '[oraclejdk8]' is not known.
The command "jdk_switcher use ["oraclejdk8"]" failed and exited with 1 during .
```

**Comment by BanzaiMan** [comment]
You need to define a scalar for `jdk`, not an array.

```yaml
matrix:
  include:
    - language: java
      jdk: oraclejdk8
```
