### ISSUE TITLE
Tying GitHub Releases to existing tags

### ISSUE THREAD

**Issue by philippgille** [travis-ci/travis-ci#8248]
When deploying to GitHub Releases and using `deploy.on.tags: true`, I'd expect the release to be tied to the tag that triggered the build.

But independent from using the [Octokit option](https://octokit.github.io/octokit.rb/Octokit/Client/Releases.html#create_release-instance_method) `target_commitish`, this isn't the case. At least not when using `deploy.draft: true`. `target_commitish` is what I thought could be the necessary option, because its description is:
> Specifies the commitish value that determines where the Git tag is created from

But `deploy.target_commitish: $TRAVIS_TAG` doesn't work at all (build error) and `deploy.target_commitish: $TRAVIS_COMMIT` doesn't help either, because when Travis CI is finished deploying and clicking on the draft release on GitHub, some generated value is in the tag field, like `untagged-aac676aeb120b7a2eb95` and publishing the draft would lead to the tag being created (and to another automatic build because of the new tag).

With a lot of trial and error I figured out you can define `deploy.tag_name: $TRAVIS_TAG` and **only in combination with `deploy.target_commitish: $TRAVIS_COMMIT`** this leads to a correctly tagged draft release and publishing it leads to the release being correctly tied to the pushed tag.

**But this is not documented anywhere.** [This page](https://docs.travis-ci.com/user/deployment/releases/) doesn't mention `deploy.tag_name` at all and the section [Advanced options](https://docs.travis-ci.com/user/deployment/releases/#Advanced-options) only says that
> you can use any valid Octokit option

while the [Octokit options](https://octokit.github.io/octokit.rb/Octokit/Client/Releases.html#create_release-instance_method) doesn't include `tag_name`, instead that's a mandatory parameter.

So:
1. Why doesn't Travis CI pass the tag of the build as `tag_name` by default?
2. Why doesn't `target_commitish` default to the commit that the tag points to?
3. Why doesn't `target_commitish` accept tags?
4. Why is the possibility to overwrite the `tag_name` not mentioned in the documentation?
5. Why do `tag_name` and `target_commitish` have to be combined to tie a release to the tag that triggered the build (a tag already points to a commit so this shouldn't be necessary)?

If that's by intention, or if I understood anything wrong, please see this issue as a question, otherwise as bug report / improvement suggestion :) .

**Comment by BanzaiMan** [comment]
What are you trying to achieve?

The required parameter `tag_name` is derived from `$TRAVIS_TAG` (or `git describe --tags --exact-match` if this is undefined). At least, this is the design. If you managed to override it, then it _might be_ a bug, you are working too hard to accomplish what you want, or both.

**Comment by philippgille** [comment]
Sorry my ticket description was too complicated.

Assuming a repository without any tags, the following two `.travis.yml` deployment configurations lead to a GitHub Releases draft as shown in the screenshot further below

```yml
deploy:
  provider: releases
  overwrite: true
  skip_cleanup: true
  target_commitish: $TRAVIS_COMMIT
#  tag_name: $TRAVIS_TAG # <------------------ tag_name commented out
  name: hello-netcoreapp $TRAVIS_TAG
  body: Automated release from Travis CI with added files from AppVeyor build
  draft: true
  file_glob: true
  file:
    - artifacts/*.tar.gz # FDDs and SCDs
    - artifacts/*.AppImage # AppImage
  api_key:
    secure: [removed for brevity]
  on:
    tags: true
```

```yml
deploy:
  provider: releases
  overwrite: true
  skip_cleanup: true
#  target_commitish: $TRAVIS_COMMIT # <--------- target_commitish commented out
  tag_name: $TRAVIS_TAG
  name: hello-netcoreapp $TRAVIS_TAG
  body: Automated release from Travis CI with added files from AppVeyor build
  draft: true
  file_glob: true
  file:
    - artifacts/*.tar.gz # FDDs and SCDs
    - artifacts/*.AppImage # AppImage
  api_key:
    secure: [removed for brevity]
  on:
    tags: true
```

Both lead to:

![image](https://user-images.githubusercontent.com/170670/29486364-497f11ce-84e4-11e7-8b54-0b6c4cd5598d.png)

(Note: Usually with files being uploaded correctly, just not in this screenshot that I created for the purpose of showing only the issue)

Things that are wrong here:
- Wrong tag - I pushed `v0.1.0`, not `untagged-aac676aeb120b7a2eb95`
- Wrong branch - I tagged a commit that's only on the develop branch!

That's what I meant with saying that the created release is **not tied to an existing tag**.

But the following (note both options are commented in), leads to the GitHub Releases draft as shown in the screenshot at the bottom of this comment:

```yml
deploy:
  provider: releases
  overwrite: true
  skip_cleanup: true
  target_commitish: $TRAVIS_COMMIT # <--------both used
  tag_name: $TRAVIS_TAG # <--------both used
  name: hello-netcoreapp $TRAVIS_TAG
  body: Automated release from Travis CI with added files from AppVeyor build
  draft: true
  file_glob: true
  file:
    - artifacts/*.tar.gz # FDDs and SCDs
    - artifacts/*.AppImage # AppImage
  api_key:
    secure: [removed for brevity]
  on:
    tags: true
```

Leads to:

![image](https://user-images.githubusercontent.com/170670/29486742-b6bbf4ce-84ed-11e7-9463-314fd09184ba.png)

Here you can see that the correct tag was recognized and the release gets tied to the tag and thus to the commit that was tagged instead of to the `HEAD` of `master`.

**Comment by BanzaiMan** [comment]
So, it sounds to me this is very much a duplicate of #8185. You are seeing these issues because we are creating a draft release even when there is no tag associated with the commit we are building.

If you actually push tags, the resulting builds should not exhibit this behavior.

Please read #8185 carefully, and if you agree that this is a duplicate, please close this.

Thank you.

**Comment by philippgille** [comment]
Although #8185 doesn't mention how the `.travis.yml` looked when the behaviour occured, you can see in the [release history](https://github.com/ezyang/ci-experiments/releases) of the mentioned [test project](https://github.com/ezyang/ci-experiments) that the commit that lead to the `untagged-`-Release is `efba49a461a759f988eff37391645f12f6a0c660`, where the `.travis.yml` looks like this:

```yml
language: c
dist: trusty
env: MODE=apple
os: linux
script:
- echo "$MODE" > $HOME/$MODE
deploy:
  provider: releases
  api_key:
    secure: [removed for brevity]
file: $HOME/$MODE
```
(See [source](https://github.com/ezyang/ci-experiments/blob/efba49a461a759f988eff37391645f12f6a0c660/.travis.yml))

Note that there's no `on.tags: true` option set.

Whereas in my case:
1. My `.travis.yml` contains `on.tags: true`, so the deploy should only be triggered when pushing a tag
2. I **did** actually push a tag

If you want, I can create two test repositories and two related Travis CI build jobs for easier reproduction.

**Comment by BanzaiMan** [comment]
> If you want, I can create two test repositories and two related Travis CI build jobs for easier reproduction.

Please do.

**Comment by BanzaiMan** [comment]
We now skip GitHub Releases deployment if the build is not a tag build. Please test it again.

**Comment by PhrozenByte** [comment]
Any updates on this?

I'm not sure whether it got clear what the problem is: As soon as I add `deploy.draft: true` to my `.travis.yml`, Travis no longer sets the release's tag to the tag that triggered the Travis build.

This config

```yaml
deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  on:
    tags: true
```

results in

![bildschirmfoto von 2018-04-07 23-15-05](https://user-images.githubusercontent.com/920356/38460436-fbc5dfbc-3ab9-11e8-879b-ca7a63e07976.png)

whereas this config

```yaml
deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  draft: true
  on:
    tags: true
```

results in

![bildschirmfoto von 2018-04-07 23-29-06](https://user-images.githubusercontent.com/920356/38460511-85b342b8-3abb-11e8-8516-09fb8aace085.png)

The reason why it says "Existing tag" is not because this tag actually exists (the tag that triggered this Travis build is `v2.0.0-beta.3`), but because GitHub silently and unsolicitedly creates this tag as soon as you hit "Publish"... :unamused:
