### ISSUE TITLE
How to disable a specific build

### ISSUE THREAD

**Issue by jarun** [travis-ci/travis-ci#8257]
This would probably reduce to a general query but is there any way to disable a specific build?

I have three packages I want to build:

```
packages:
  archlinux:
    builddeps:
      - make
    deps: 
      - python-urllib3
      - python-requests
      - python-cryptography
      - python-beautifulsoup4
      - python
  fedora25:
    builddeps:
      - make
    deps:
        - python3-beautifulsoup4
        - python3-cryptography
        - python3-requests
        - python3-urllib3
        - python3
  ubuntu17.10:
    builddeps:
      - make
    deps:
        - python3-urllib3
        - python3-requests
        - python3-cryptography
        - python3-bs4
        - python3
```

How can I disable the package build for fedora25? I am trying to avoid entire entry removal.
