### ISSUE TITLE
Trusty images do not have a means to start X server

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#8262]
The instructions given in https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI do not work on Trusty images.

To use X window system on Trusty, we need to install `xvfb` and start the server ourselves.

```yaml
env:
  global:
    - DISPLAY=:99

before_script:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24"
  - sleep 3
```

(The invocation of `sh -e /etc/initi.d/xvfb start` basically amounts to `/sbin/start-stop-daemon …` above.)

**Comment by WolfgangFahl** [comment]
I have tried his in a simpler project to no avail:

https://travis-ci.org/BITPlan/com.bitplan.javafx

testIcons(com.bitplan.javafx.TestGUI): Unable to open DISPLAY

**Comment by BanzaiMan** [comment]
```yaml
addons:
  apt:
    packages:
      - xvfb
env:
  global:
    - DISPLAY=:99

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24"
  - sleep 3
```

I indicated in the description above that you need to install `xvfb`. I figured it was implicitly understood (e.g., https://docs.travis-ci.com/user/installing-dependencies#Installing-Packages-with-the-APT-Addon), but I do apologize for this assumption.

> Please update the documentation and also make things a lot more readable and use more comments what this all is about. My tests today where frustrating as hell because travis is so slow and mostly things fail if not configured exactly correct.

Your suggestions are more than welcome to improve documentation.

I am sorry to hear about your frustrating day, but sometimes you _*do*_ need exact the correct configuration.

**Comment by WolfgangFahl** [comment]
I have now rewritten my configuration and included the comments that I would have expected. Also I changed the lines you suggested to use the DISPLAY variable that has been declared for the xvfb start.

```
# 
# this is a java project using maven
language: java
# 
# Java 8
#  
# to avoid Unsupported major.minor version 52.0 we need to specify the JDK to be used
# https://stackoverflow.com/a/40208648/1497139
jdk: oraclejdk8
# support for headless Swing tests and other gui stuff
# see https://docs.travis-ci.com/user/gui-and-headless-browsers/ 
# 
# as of  2017-08 precise is only available as an option
#
# uncomment the following lines to use xvfb with precise
#dist: precise
#before_script:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3 # give xvfb some time to start
#
# 2017-08-20: trusty xvfb configuration
# see https://github.com/travis-ci/travis-ci/issues/8262#issue-251064430
#
# set the X11 Display variable as a global environment variable
env:
  global:
    - DISPLAY=:99
# start xvfb using the the DISPLAY port
before_script:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- $DISPLAY -ac -screen 0 1280x1024x24"
  - sleep 3
before_install: sudo apt-get install xvfb
# switch off gpg handling
# and split install and test phase of maven since xvfb will only
# be available in test phase
# let's first compile without tests
install: mvn install -DskipTests=true -Dgpg.skip=true
# do the tests separately after xvfb has been installed
script: mvn test
# we need a few extra packages to be installed
# 1. for Java FX support the latest oracle-java8 needs to be installed
# 2. xvfb is needed to run GUI tests and avoid headless mode
addons:
  apt:
    packages:
      - oracle-java8-installer
      - xvfb
```
