### ISSUE TITLE
I have script overwritten in build stage when it show create two build in one stage

### ISSUE THREAD

**Issue by lipemorais** [travis-ci/travis-ci#8264]
With [this .travis.yml](https://github.com/lipemorais/serenata-toolbox/blob/8c6cb5fe614bd7f4d38c4ca9a693de49e2223a9b/.travis.yml) I was expecting that one stage called test with two builds but it didn't happened as expected.

```
    - stage: test
      script: coverage run -m unittest discover tests/unit
      script: coverage run -m unittest discover tests/journey
```
I thought that this piece of code would do the jobs as it says on documentation [here](https://docs.travis-ci.com/user/build-stages/#How-to-define-Build-Stages%3F) and [here](https://docs.travis-ci.com/user/build-stages/#Naming-your-Build-Stages).

But I got [just one build inside test stage](https://travis-ci.org/lipemorais/serenata-toolbox/builds/265666523)
![image](https://user-images.githubusercontent.com/5021565/29434018-cc62a38a-8377-11e7-949e-b6275adfa857.png)

Looks on logs that the `script:` for unit test is overwritten by the second one for journey tests.

**Comment by BanzaiMan** [comment]
That portion of `.travis.yml` is a sequence with one map, so only the second `script:` is effective.

To get what you describe, you need to have two elements in the `jobs.include` sequence.

```yaml
    - stage: test
      script: coverage run -m unittest discover tests/unit
    - script: coverage run -m unittest discover tests/journey
```
