### ISSUE TITLE
Failed to run Dartium on simple build config

### ISSUE THREAD

**Issue by arthurdeschamps** [travis-ci/travis-ci#8273]
This issue is also on [SO](https://stackoverflow.com/questions/45722324/travis-trying-to-test-angulardart-with-dartium).

With the following configuration:

```
matrix:
  include:
    - language: dart
      sudo: false
      dart: stable
      dist: trusty
      before_install:
        - cd $TRAVIS_BUILD_DIR/webapp-angular
      install_dartium: true
      script:
        - pub get && pub run test --platform dartium test/


    - language: java
      jdk: oraclejdk8
      sudo: false
      script:
        - mvn clean verify
```

I get the error 

`Failed to load "test/data_services/app/company/Coordinates_test.dart": Failed to run Dartium: Dartium failed with exit code 1..` 

after trying tu run `pub get && pub run test --platform dartium test/`.

Is this an error on my part ?

**Comment by BanzaiMan** [comment]
Please mention @nex3 and @a14n for Dart inquiries, as documented in https://docs.travis-ci.com/user/languages/dart. Thanks.

**Comment by nex3** [comment]
The `install_dartium` field is only meaningful [within `dart_task`](https://docs.travis-ci.com/user/languages/dart/#Running-Tests). It won't do anything at the top level of your configuration (or of a matrix entry).

**Comment by arthurdeschamps** [comment]
Ok, but it says "either at the top level or for a particular task" so I figured I could use as a way to globally install Dartium on the VM.

Anyway, I had already tried using `dart_task` but I was getting the same error message every time: "An error occurred while generating the build script.". 
I've just tried again and the same message shows up with this configuration:

```
matrix:
  include:
    - language: dart
      sudo: false
      dart: stable
      dist: trusty
      before_install:
        - cd $TRAVIS_BUILD_DIR/webapp-angular
      dart_task:
        - test: --platform dartium
          install_dartium: true
```

Any idea ?
