### ISSUE TITLE
docker no longer found in deploy

### ISSUE THREAD

**Issue by ashic** [travis-ci/travis-ci#8285]
I have a build that looks like the following:

```
services:
- docker
script:
- export REPO=heartysoft/alpine-confluent-kafka
- docker build -t $REPO:python-3.6-0.9.4 --build-arg KAFKA_VERSION=0.9.4 - < Dockerfile.alpine.py3
- docker build -t $REPO:python-3.6-0.11.0 --build-arg KAFKA_VERSION=0.11.0 - < Dockerfile.alpine.py3
deploy:
  provider: script
  script: docker tag $REPO:python-3.6-0.9.4 $REPO:python-3.6-0.9.4-$TRAVIS_TAG && \
          docker tag $REPO:python-3.6-0.11.0 $REPO:python-3.6-0.11.0-$TRAVIS_TAG && \
          docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASS" && \
          docker push $REPO
  on:
    tags: true
```

The previous version of this (which last ran successfully four months ago) is:

```
services:
- docker
script:
- export REPO=heartysoft/alpine-confluent-kafka
- docker build -t $REPO:python-3.6 - < Dockerfile.alpine.py3
deploy:
  provider: script
  script: docker tag $REPO:python-3.6 $REPO:python-3.6-$TRAVIS_TAG && docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASS" && docker push $REPO
  on:
    tags: true
```

(Kept out the encrypted secrets for brevity).

I made the change today, and it builds the containers fine, but then when it gets to deploy, I get:

```
1.21sSuccessfully installed dpl-1.8.40
1 gem installed
dpl.1
Installing deploy dependencies
!!! Script support is experimental !!!
dpl.2
Preparing deploy
Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`. See https://docs.travis-ci.com/user/deployment/#Uploading-Files.
No local changes to save
dpl.3
Deploying application
sh: 1:  docker: not found
No stash found.
Script failed with status 127
failed to deploy
```

Any idea why it can't find docker during deployment?
