### ISSUE TITLE
Yarn is hanging while installing packages

### ISSUE THREAD

**Issue by rojha-mdsol** [travis-ci/travis-ci#8287]
Hi Team,
I am having some issue in using yarn in travis.

## Here is the description
**One line statement**
`yarn` is hanging while installing the packages and hence `travis` is erroring out.

**Configuration**
Node: v6.1
Yarn: v0.27.5
Ubuntu: 14.04.5 LTS

### Description/way to reproduce it.
When i tried to move away from `npm` to `yarn` i continued with the same configuration then yarn got stuck while installing the packages and travis errored out, here is the screenshot

<img width="1050" alt="screen shot 2017-08-23 at 1 55 00 am" src="https://user-images.githubusercontent.com/13253843/29586223-8c12c70e-87a7-11e7-86b4-f746ec8c9616.png">

Now, after going through this [**issue**](https://github.com/yarnpkg/yarn/issues/764), i thought maybe its node version so i upgraded node to **v6.11.2**, and this time travis succeeded.

But, just to give it a try i again downgraded node to my old version i.e `v6.1` and this time travis against my understanding succeeded. So i am not sure what is happening here.
If someone can give me a bit of explanation, why it behaves this way, that would be really great.

Again, i don't know whether this is a known issue or there is something wrong with my travis config.

**travis config**
```yml
language: ruby
cache:
  yarn: true
  bundler: true
  directories:
  - node_modules
rvm:
- 2.4.0
branches:
  only:
  - master
  - "/^release.*$/"
sudo: required
dist: trusty
group: edge
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
env:
  global:
  - TRAVIS_NODE_VERSION=6.11.2
  - RAILS_ENV=test
  - DEBIAN_FRONTEND=noninteractive
bundler_args: "--jobs=3 --retry=3 --deployment --without development --without production"
before_install:
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm
  && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm
  install $TRAVIS_NODE_VERSION
- yarn cache clean
- node --version
- npm rebuild node-sass
- yarn
before_script:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- yarn run build
- yarn run test
- yarn run lint
after_success:
- bundle exec rake pact:publish
after_failure:
- cat /home/travis/build/mdsol/ract_ui/npm-debug.log
notifications:
  slack:
    secure: <secure string>
  email:
    recipients:
    - <email>
    on_success: never
    on_failure: always
```

Team, Please help me to explain this
**Note:** i won't be able to share the logs link, as it is a private repo.
