### ISSUE TITLE
Skipping deployment because this branch is not permitted

### ISSUE THREAD

**Issue by dylandechant** [travis-ci/travis-ci#8289]
I am running into this strange error all of the sudden

`.travis.yml`: 
```yaml
language: node_js
node_js:
- 7.10.1
deploy:
  provider: elasticbeanstalk
  access_key_id: "$access_key_id"
  secret_access_key:
    secure: "$secret_access_key"
  region: us-east-1
  app: my-app
  env: my-env
  bucket_name: my-bucket
  on:
    repo: my-org/my-repo
  branches:
    only:
      - master
notifications:
  slack:
    secure: "$slackkey"
```

I get the error:
```
The command "npm test" exited with 0.
Skipping a deployment with the elasticbeanstalk provider because this branch is not permitted
Done. Your build exited with 0.
```

`travis lint` passes fine, am I missing something somewhere?

edit: I should add that if i take out the "branches" section, it deploys just fine, but as expected every branch is deployed.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

The message indicates that the build happened on a commit that is not the `matter` branch.

**Comment by dylandechant** [comment]
@BanzaiMan https://travis-ci.com/PerkinsAndWill-IO/SAP/jobs/87846730

I am seeing this:
```
0.57s$ git clone --depth=50 --branch=master git@github.com:PerkinsAndWill-IO/SAP.git PerkinsAndWill-IO/SAP
Cloning into 'PerkinsAndWill-IO/SAP'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
remote: Counting objects: 332, done.
remote: Compressing objects: 100% (206/206), done.
remote: Total 332 (delta 144), reused 286 (delta 108), pack-reused 0
Receiving objects: 100% (332/332), 1.20 MiB | 0 bytes/s, done.
Resolving deltas: 100% (144/144), done.
$ cd PerkinsAndWill-IO/SAP
$ git checkout -qf 40f3345d6e2d578a084d674928c77adaf5e6ab7f
```

**Comment by BanzaiMan** [comment]
The build configuration you showed in the description and the configuration for this job do not match, so I'll speak in general terms.

When you want to limit your deployment based on the branch, you need `on.branches` *under* the deployment configuration. Your `branches` appears in a wrong place. In other words, 

```yaml
deploy:
  provider: elasticbeanstalk
  access_key_id: "$access_key_id"
  secret_access_key:
    secure: "$secret_access_key"
  region: us-east-1
  app: my-app
  env: my-env
  bucket_name: my-bucket
  on:
    repo: my-org/my-repo
    branches:    # ← new!
      only:      # ← new!
        - master # ← new!
notifications:
  slack:
    secure: $slackkey
```

See https://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A for more details.

Test the configuration above, and let us know how it goes for you.

**Comment by dylandechant** [comment]
@BanzaiMan this solved it, thank you!

**Comment by ianaya89** [comment]
I am facing the same issue, I have a conditional deployment based on branches: `master` and `develop`.  The branch master is working ok but `develop` throws this message:

```
Skipping a deployment with the elasticbeanstalk provider because this branch is not permitted
```

Here is my `.travis.yml` setup:

```
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "sa-east-1"
  app: "mtn"
  env: "dev"
  on:
    branch: develop
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "sa-east-1"
  app: "mtn"
  env: "prod"
  on:
    branch: master
```

**Comment by BanzaiMan** [comment]
@ianaya89 You have a hash, not an array, for `deploy`, so only the last one of each of `provider`, `access_key_id`, `secret_access_key`, `region`, `app`, `env`, and `on` is effective. If you want to define 2 deployment targets, each deploying for `develop` and `master` branches, you need an array.

```yaml
deploy:
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: "sa-east-1"
    app: "mtn"
    env: "dev"
    on:
      branch: develop
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: "sa-east-1"
    app: "mtn"
    env: "prod"
    on:
      branch: master
```

**Comment by ianaya89** [comment]
That worked 😀
I didn't know arrays in `yml`. Thanks!

**Comment by iFlameing** [comment]
@BanzaiMan I am also facing the same problem 
`Skipping a deployment with the pages provider because this branch is not permitted`

this is my travis.yml setup
```
language: node_js
node_js: 10.1.0
cache:
  yarn: true
  directories:
  - "./tests/gatsby-plone-site/.cache"
  - "./tests/gatsby-plone-site/public"
before_install:
  - cd tests/gatsby-plone-site
install: yarn install
before_script: sed -i "s|'/',|'/gatsby-theme-plone/',|" ./gatsby-config.js
script: "./node_modules/.bin/gatsby build --prefix-paths"
deploy:
  provider: pages
  github-token: "$GITHUB_TOKEN"
  local-dir: "./tests/gatsby-plone-site/public"
  target-branch: gh-pages
  keep-history: false
  skip-cleanup: true
  on:
    branch: master
```
https://travis-ci.org/iFlameing/gatsby-theme-plone/jobs/498827333
