### ISSUE TITLE
Support parallel Build Stages

### ISSUE THREAD

**Issue by timvaillancourt** [travis-ci/travis-ci#8293]
Hey guys,

First of all the Build Stages feature is great!

I would love it if the Build Stages feature allowed some stages to execute in parallel. In my example I have my first stage build my project and all other stages run tests on my build that do not need to be sequential. My build would complete probably 2-5x faster if it ran some or all tasks in parallel. This is similar to https://github.com/travis-ci/travis-ci/issues/7769.

My idea is adding a flag to build stages to allow a stage to asynchronous, perhaps 'async: true'. If this was set to 'true' the stage could execute in parallel, 'false' would make it sequential (default).

I imagine parallel builds could create odd race conditions in the caching features (specifically saving/updating the cache), so it might be good to also support a 'read only' version of the cache that loads but does not save the cache. In my use case all stages after build benefit from loading the cache but they do not need to "save"/update the cache at the end. This should probably be a different PR (I can create it).

Any thoughts? Thanks!

Tim

**Comment by BanzaiMan** [comment]
If the jobs are meant to be run in parallel, put them in the same stage. Allowing concurrency among stages (instead of jobs) seems rather unnecessary.

**Comment by timvaillancourt** [comment]
Thanks @BanzaiMan, I read more about build matrixing and that sounds like a combination of Build Stages and Build Matrix will answer my need.

Is it possible to have two build stages that use two different matrixes? I tested it out and it seems to only run on the first of the matrix variables at the moment. Perhaps this needs to be a new feature.

I need to build my project based on 1 x matrix and integration test (in a 2nd stage) on a different matrix list. I can see one way to do it all without Build Stages but it would be a bit less elegant.

Thanks!

**Comment by BanzaiMan** [comment]
Each job in `job.include` must specify exactly one job. No matrix expansion takes place except at the top level.

**Comment by timvaillancourt** [comment]
Ok, thanks @BanzaiMan. I will close this and open a different request later if required

**Comment by fuhbar** [comment]
@BanzaiMan What is the reason behind this (no matrix expansion for build stages)? Because  somehow this understanding of matrix and build stages naturally emerges while reading your docs. It even is a common requirement.

To put it differently: What are the design decisions or limitations which prevents us from using matrix expansion for all the build stages?

**Comment by ORESoftware** [comment]
I am confused. I have this:

```yaml
language: c
services: docker
jobs:
  include:
    - stage: nodejs_8
      script: ./scripts/travis/run.sh 8
    - stage: nodejs_9
      script: ./scripts/travis/run.sh 9
    - stage: nodejs_10
      script: ./scripts/travis/run.sh 10
    - stage: nodejs_11
      script: ./scripts/travis/run.sh 11
    - stage: nodejs_12
      script: ./scripts/travis/run.sh 12
```

it looks nice in the UI

<kbd>
<img width="1276" alt="Screen Shot 2019-06-06 at 5 44 20 PM" src="https://user-images.githubusercontent.com/11139560/59074921-c2fd0a80-8882-11e9-8115-c619bd0f03aa.png">
</kbd>

**but** they are running series. How can I get them to run in parallel? If put them as jobs not stages, than the UI results do not look as organized?

**Comment by ORESoftware** [comment]
Nevermind, I was able to use scripts instead of stages like so:


```yaml
language: c
services: docker
git:
  depth: 1

jobs:
  include:
   - script: ./scripts/travis/run.sh 8
     name: nodejs_8
   - script: ./scripts/travis/run.sh 9
     name: nodejs_9
   - script: ./scripts/travis/run.sh 10
     name: nodejs_10
   - script: ./scripts/travis/run.sh 11
     name: nodejs_11
   - script: ./scripts/travis/run.sh 12
     name: nodejs_12
```

and the result:

<kbd>
<img width="1004" alt="Screen Shot 2019-06-06 at 6 01 26 PM" src="https://user-images.githubusercontent.com/11139560/59075405-2d16af00-8885-11e9-9831-ae881f905830.png">
</kbd>
