### ISSUE TITLE
Support Matrix expansion per-stage in Build Stages feature

### ISSUE THREAD

**Issue by timvaillancourt** [travis-ci/travis-ci#8295]
Hey guys,

I would like the ability for travis-ci to support per-Build-Stage Matrix expansion. In pseudo-code, this is how I would like to create a build:

In my example I build my project on 4 x different OSs via Docker. I then want to integration test each of the 4 x OS-specific builds against 5 x different versions/configurations of MongoDB launched in Docker (just for simple integration tests with the server).

If the Build Stages feature allowed per-stage matrixes I could:
1. Build my project on the 4 x distribution/OSs in a stage called 'Build' (4 x jobs).
2. Integration test my 4 x OS-specific builds against the 5 x database versions (20x jobs).

Today, with the Matrix feature without Stages the best I could do was:
1. All 20x jobs (4 OS x 5 DB Version) build the entire project.
2. All 20x jobs run the integration tests.

As the 5x database versions exists only for API integration it would be more efficient to only build the project only 4 times (once per OS) and test 20 times instead of build AND test 20 times - supporting per-stage matrix would allow this.

Lastly in my example I want to upload the builds for each of the 4 x OSs. In this scenario every job builds the project so that becomes a bit messy.

Here is pseudo-code of what I'm proposing, ((OS HERE)) was used to show that the test stage matrix would repeat for each OS.
```
language: python
cache:
  pip: true
services:
  - docker
jobs:
  include:
  - stage: build
    matrix:
      include:
      - python: 3.4
        env: DIST=centos6
      - python: 3.4
        env: DIST=centos7
      - python: 3.4
        env: DIST=debian8
      - python: 3.4
        env: DIST=debian9
      - python: 2.7
        env: DIST=centos6
      - python: 2.7
        env: DIST=centos7
      - python: 2.7
        env: DIST=debian8
      - python: 2.7
        env: DIST=debian9
  - stage: test
    matrix:
      include:
      - python: 3.4
        env:
        - DIST=((OS HERE))
        - MONGODB_DOCKER_VERSION=3.4
        - USE_CSRS=yes
      - python: 3.4
        env:
        - DIST=((OS HERE))
        - MONGODB_DOCKER_VERSION=3.2
        - USE_CSRS=yes
      - python: 3.4
        env:
        - DIST=((OS HERE))
        - MONGODB_DOCKER_VERSION=3.2
        - USE_CSRS=no
      - python: 3.4
        env:
        - DIST=((OS HERE))
        - MONGODB_DOCKER_VERSION=3.0
        - USE_CSRS=yes
      - python: 3.4
        env:
        - DIST=((DIST HERE))
        - MONGODB_DOCKER_VERSION=3.0
        - USE_CSRS=no
```

Thanks!

**Comment by timvaillancourt** [comment]
Example updated/corrected. Thanks

**Comment by timvaillancourt** [comment]
Another update! While what I am requesting here would be easier, I've managed to do what I've described after following this example https://docs.travis-ci.com/user/build-stages/warm-cache/.

Essentially I was unaware that specifying the same stage name many times with different inputs creates a parallel build. I've now been able to create many parallel stages within each Build Stage!

**Comment by danielbachhuber** [comment]
> Essentially I was unaware that specifying the same stage name many times with different inputs creates a parallel build stage. I've now been able to create many parallel stages within each Build Stage!

I've confirmed this works for me too: https://github.com/wp-cli/wp-cli/pull/4487/commits/61833241a176450711b8b925a178fe944eb371fb

Hopefully this is a feature, not a bug :)

**Comment by kaimast** [comment]
Could you link the github issue or the workaround in the docs? https://docs.travis-ci.com/user/build-stages/matrix-expansion/

It took me like half a day to realize that this is a bug in travis.

**Comment by ssbarnea** [comment]
Indeed someone from @travis-ci really needs to update the documentation as it required as in its current form is useless. 

Only @danielbachhuber merged workfix was useful.

**Comment by BanzaiMan** [comment]
Documentation PRs are welcome. Thank you.

**Comment by sdunster** [comment]
Just to be clear a documentation update would be great but this feature request is still pretty important for me because there appears to be no parsing done beyond `env` in build stages. I'd like to be able to use `global` to set some things that applied to the matrix and some that are. I don't like pumping all my env secrets to all of my build tools - I'm sure something in there will leak it or log it somewhere eventually.

My configs have also become quite unwieldy:
https://github.com/NSWSESMembers/availability-poc/blob/master/.travis.yml

**Comment by theory** [comment]
I'd very much appreciate a method to create matrices in stages independent of the matrix in the default stage without tons of duplication. If, for example, I want to test multiple version of Perl in a "windows" stage, I currently have to [define the stage multiple times](/theory/winperl-travis#windows-matrix-stage) while changing only a single line in each (the perl version). The same challenge exist in [a project](/sqitchers/sqitch) in which I'd like to add a stage to test multiple versions of Postgres, another to test multiple versions of MySQL, and so on.

IOW, a big +1 from me requesting this functionality.

**Comment by theory** [comment]
Okay, trying to figure out how to add testing of multiple versions of Postgres in [this `.travis.yml`](/sqitchers/sqitch/blob/pgsql-versions/.travis.yml), but so far, [it's not adding any jobs from that matrix](https://travis-ci.com/sqitchers/sqitch/builds/97404597). I must be overlooking something…

**Comment by bencoman** [comment]
@theory, I think thats off topic, but anyway try...
```
language: perl
services:
  - docker
perl:
  - "5.28"
  - "5.26"
env: 
      - PGVERSION=11
      - PGVERSION=10
```
and if that works, add a ``global:`` section for ``PGVERSION=system`` per... 
https://docs.travis-ci.com/user/environment-variables/

**Comment by theory** [comment]
I don't want a 2 x 2 matrix. I just want to add tests for each version of Postgres to test only on Perl 5.28.

**Comment by BanzaiMan** [comment]
@theory It is worth pointing out that code duplication is easily avoided by the use of YAML aliases and anchors. For example, in your example:

```yaml
strawberry: &strawberry
      stage: Strawberry
      os: windows
      language: shell
      env:
      - PERL_VERSION: 5.28.1.1
      before_install:
        - cinst -y strawberryperl --version $PERL_VERSION
        - export "PATH=/c/Strawberry/perl/site/bin:/c/Strawberry/perl/bin:/c/Strawberry/c/bin:$PATH"
      install:
        - cpanm --notest --installdeps .
      script:
        - perl Makefile.PL
        - gmake
        - gmake test


jobs:
  include:
    - <<: *strawberry
    - <<: *strawberry
      env:
      - PERL_VERSION: 5.26.3.1
```

**Comment by jdalrymple** [comment]
@theory I noticed a slight problem with this. It can be seen in https://travis-ci.org/jdalrymple/node-gitlab/jobs/517886018. If the duplicated stage doesn't contain the script tag, it defaults without inheriting it.  Is this a possible bug?

**Comment by theory** [comment]
I don't really understand your config, @jdalrymple. You declare a bunch of aliases with `&`, but then don't use them anywhere with `*`. For example, the Sqitch config now tests several versions of Postgres with this bit:

``` yaml
    - &postgres
      stage: 🐘 Postgres
      if: branch = master
      env: POSTGRES=11
      before_install:
        - source dev/linux-postgres
        - source dev/linux-prereqs
      script:
        - LIVE_PG_REQUIRED=1 prove -lr --directives --comments t/pg.t
    - <<: *postgres
      env: POSTGRES=10
    - <<: *postgres
      env: POSTGRES=9.6
    - <<: *postgres
      env: POSTGRES=9.5
```

The `&postgres` creates the anchor, and then It gets reused with `*postgres` multiple times, in each case changing only the value of the `POSTGRES` environment variable.

**Comment by jdalrymple** [comment]
Youre 100% lol, I misread the syntax! Sorry about that :rofl: I caused my own problem

**Comment by NullVoxPopuli** [comment]
How do you do the variable thing with multiple stages?

Trying something like this, and I don't think I have the nesting quite right
```yaml
---
language: node_js
node_js:
  - "10"

sudo: false
dist: xenial

addons:
  chrome: stable
  firefox: latest
cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1


before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

before_script:
  - google-chrome --version
  - lsb_release -a
  - uname -a

install:
  - ./run yarn install --non-interactive

matrix:
  allow_failures:
    - name: "Check Types"
    - name: "Acceptance Tests (a11y)"

tests: &tests
  - stage: "Tests"
    name: "Unit Tests"
    script: time ./run yarn test:named Unit
  - name: "Helper Tests"
    script: time ./run yarn test:named Helper
  - name: "Integration Tests"
    script: time ./run yarn test:named Integration
  - name: "Acceptance Tests"
    script: time ./run yarn test:named Acceptance
  - name: "a11y"
    script: PERCY_ENABLE=0 time ./run yarn test:named Acceptance --query enableA11yAudit=true

quality: &quality
  - stage: "Quality"
    name: "Lint JS/TS"
    script: time ./run yarn lint:js
  - name: "Lint Templates"
    script: time ./run yarn lint:hbs
  - name: "Lint Styles"
    script: time ./run yarn lint:sass
  - name: "Check Types"
    script: time ./run yarn tsc
  - name: "Translations"
    script: time ./run yarn lint:i18n

jobs:
  fail_fast: true

  include:
    - <<: *quality

    - <<: *tests
      env:
      - CI_BROWSER=chrome

    - <<: *tests
      env:
      - CI_BROWSER=firefox
  
```
