### ISSUE TITLE
Deployment fails if there is on branch setting inside deploy

### ISSUE THREAD

**Issue by MichaelOrtho** [travis-ci/travis-ci#8310]
If there is this `.travis.yml` file:
```
deploy:
  - provider: heroku
    edge: true
    app: something-dev
    api_key:
      secure "{hidden}"
    on:
      branch: dev
  - provider: heroku
    edge: true
    app: something-qa
    api_key:
      secure "{hidden}"
    on:
      branch: qa
```
I think the problem is because during installation and script Travis detaches from the deploying branch and it is not coming back for deployment so filter on branch is not seeing original branch but detached head one.

This example is with Heroku provider, but same happened for other project and AzureWebApp provider. 

My fix that `WORKED`:
- I abandoned all artifacts during script and checkout proper branch again.

Added:
```
before_deploy:
  - git checkout .
  - git checkout $(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
```
