### ISSUE TITLE
GOARCH=xx not honored in env key

### ISSUE THREAD

**Issue by mh-cbon** [travis-ci/travis-ci#8313]
When i declare

```yml
env:
  matrix:
    - GOARCH=amd64 OSARCH=amd64
```

somehow, the env is exported then blanked before the build start,

see this build log for details,
https://travis-ci.org/mh-cbon/go-bin-deb/jobs/269565822#L686

see this build for a version where is replace that var name with OKARCH 
https://travis-ci.org/mh-cbon/go-bin-deb/jobs/269567113
