### ISSUE TITLE
AWS CodeDeploy deployments are currently not working due to the newest aws-sdk gem release

### ISSUE THREAD

**Issue by cotsog** [travis-ci/travis-ci#8316]
We've received reports telling that [AWS CodeDeploy deployments](https://docs.travis-ci.com/user/deployment/codedeploy/) are currently not working on Travis CI. We are thinking that this is a side effect of [the newest version of the aws-sdk gem](https://github.com/aws/aws-sdk-ruby/releases/tag/v2.10.35) (i.e 2.10.35) that got released earlier today. Sorry for the inconvenience.

We are currently looking into it and we will update this issue with any news/fix on that front ASAP.

Thank you for your patience!

**Comment by BanzaiMan** [comment]
If you are seeing this problem, could you try this tentative fix?

```yaml
deploy:
  - provider: s3
    edge:
      branch: aws-sdk-2
    ⋮ # rest of S3 configuration
  - provider: codedeploy
    edge:
      branch: aws-sdk-2
    ⋮ # rest of CodeDeploy configuration
```
