### ISSUE TITLE
Access denied for user 'travis'@'%' to database (trusty and mysql)

### ISSUE THREAD

**Issue by sue445** [travis-ci/travis-ci#8331]
I'm using weekly build on travis.

Last week build was successful. 
https://travis-ci.org/sue445/index_shotgun/jobs/268298728

But, this week build is failure.
https://travis-ci.org/sue445/index_shotgun/jobs/271175914 

```
Mysql2::Error: Access denied for user 'travis'@'%' to database 'index_shotgun_test': CREATE DATABASE `index_shotgun_test` DEFAULT CHARACTER SET `utf8` COLLATE `utf8_unicode_ci`
/home/travis/build/sue445/index_shotgun/gemfiles/vendor/bundle/ruby/2.1.0/gems/mysql2-0.4.9/lib/mysql2/client.rb:120:in `_query'
/home/travis/build/sue445/index_shotgun/gemfiles/vendor/bundle/ruby/2.1.0/gems/mysql2-0.4.9/lib/mysql2/client.rb:120:in `block in query'
/home/travis/build/sue445/index_shotgun/gemfiles/vendor/bundle/ruby/2.1.0/gems/mysql2-0.4.9/lib/mysql2/client.rb:119:in `handle_interrupt'
/home/travis/build/sue445/index_shotgun/gemfiles/vendor/bundle/ruby/2.1.0/gems/mysql2-0.4.9/lib/mysql2/client.rb:119:in `query'
```

Setting for to connect to mysql is following. (via. https://docs.travis-ci.com/user/database-setup/#Using-MySQL-with-ActiveRecord)

```yml
test:
  adapter: mysql2
  database: index_shotgun_test
  username: travis
  encoding: utf8
```

I think that it is caused by changing from precise to trusty.
Successful build was precise and failed build was trusty. (code is no changed!)

Has the setting to connect between precise and trusty changed?
Or is this a problem with travis-ci?

Thank you.

# Workaround
Add `dist: precise` to `.travis.yml`

```
#.travis.yml
dist: precise
```

My build was successful.
https://travis-ci.org/sue445/index_shotgun/builds/271184012

**Comment by mloskot** [comment]
I can confirm this issue.

We are experiencing the same problem in SOCI project:
* `dist: precise` - all tests work
* `dist:trusty` - access denied as explained by OP (eg. https://travis-ci.org/SOCI/soci/jobs/272195748)

**Comment by CaliforniaMountainSnake** [comment]
This helped me:
```yml
addons:
    mariadb: "10.4"

before_install:
    - sudo mysql -u root -e "CREATE USER 'test_user' IDENTIFIED BY 'test_password';"
    - sudo mysql -u root -e 'CREATE DATABASE `application_database`;'
    - sudo mysql -u root -e 'GRANT ALL ON *.* TO `test_user`;'
    - sudo mysql -u root -e 'FLUSH PRIVILEGES;'
```
