### ISSUE TITLE
"FROM microsoft/aspnetcore-build:1.1 AS BUILD-ENV" leads to 'invalid reference format'

### ISSUE THREAD

**Issue by pkhodos** [travis-ci/travis-ci#8344]
Hi, I have a Dockerfile:

line 1: FROM microsoft/aspnetcore-build:1.1 AS BUILD-ENV
...

It works fine locally, but it fails on Travis-CI

```
Step 1/10 : FROM microsoft/aspnetcore-build:1.1 AS BUILD-ENV
Error parsing reference: "microsoft/aspnetcore-build:1.1 AS BUILD-ENV" is not a valid repository/tag: invalid reference format
```

How can I avoid this error? 
I've used Dockerfile as example from https://docs.docker.com/engine/examples/dotnetcore/#prerequisites, so it must be supported somehow.

**Comment by msepahvand** [comment]
Same issue here. Somebody was saying the capital casing on BUILD-ENV could be causing it, but it still happens to me with lowercase:

Dockerfile:
```
FROM microsoft/dotnet:2.0-sdk AS build-env
COPY . /app
WORKDIR /app
RUN dotnet publish -c Release -o out -r linux-x64
EXPOSE 80/tcp
RUN chmod +x ./entrypoint.sh
CMD /bin/bash ./entrypoint.sh
```

travis.yml:
```
language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 2.0.0
services:
 - docker
before_install:
 - pip install --user awscli
 - export PATH=$PATH:$HOME/.local/bin
install:
 - export DOTNET_CLI_TELEMETRY_OPTOUT=1
before_script:
 - chmod a+x ./build.sh
 - chmod a+x ./deploy.sh
script:
 - ./build.sh
after_script:
 - ./deploy.sh
deploy:
  - provider: script
    script: ./deploy.sh $TRAVIS_TAG $SA_PASSWORD
    skip_cleanup: true
    on:
      tags: true
env:
  global:
  - secure: .......
```
And the `deploy.sh` which throws the error:
```
#!/bin/bash
set -ev
eval $(aws ecr get-login --region ap-southeast-2)
docker-compose build
docker tag org/web:latest 599080142044.dkr.ecr.ap-southeast-2.amazonaws.com/org/web:latest
docker push 599080142044.dkr.ecr.ap-southeast-2.amazonaws.com/org/web:latest
```

**Comment by pkhodos** [comment]
That's true "AS build-env" also does not work with Travis-CI

**Comment by BanzaiMan** [comment]
Is this a new construct in Dockerfile?

**Comment by pkhodos** [comment]
I'm not sure. It's in a simplest example for .Net Core application: https://docs.docker.com/engine/examples/dotnetcore/#prerequisites

**Comment by pkhodos** [comment]
Looks like Travis-CI does not support it. Have to write Dockerfile without using "AS".

**Comment by BanzaiMan** [comment]
If this is a construct supported by newer version, you can try updating Docker.

```yaml
addons:
  apt:
    packages:
      - docker-ce
```

Or try one of the methods shown in https://docs.travis-ci.com/user/docker#Installing-a-newer-Docker-version
