### ISSUE TITLE
Default for older repos is sudo-enabled Trusty

### ISSUE THREAD

**Issue by scottohara** [travis-ci/travis-ci#8349]
The [Build Environment Overview](https://docs.travis-ci.com/user/reference/overview/) page indicates that **container-based Trusty** environment is now the:

> Default as of August 2017

Similarly, the (albeit outdated) [Migrating from legacy](https://docs.travis-ci.com/user/migrating-from-legacy/) page indicates:

> Container-based infrastructure is the default for new repositories, but if you want to set it explicitly or have an older repository, add the following line to your .travis.yml: `sudo: false`

One of my repositories (created 3 years ago, so I guess this counts a "an older repository") doesn't specify either `sudo` or `dist` in `.travis.yml`.

When it builds, it seems to default to:
* `dist: trusty` 😄 
* `sudo: required` 😞 

I base this assumption on the presence of `instance: testing-gce-*`, as noted [here](https://blog.travis-ci.com/2017-08-31-trusty-as-default-status):

`instance: testing-gce-a2f25f3f-2e40-41a2-b748-0114384e1205:travis-ci-garnet-trusty-1499451966 (via amqp)`

Obviously I can simply add `sudo: false` to explicitly request container-based;  but I was wondering if there is a way to 'upgrade' my older repos, so that they have the **same defaults** as a newly created repo?

Are there any other differences between older repos and newer ones; other than the default for `sudo`? (and if so, are they documented anywhere?)

**Comment by MariadeAnton** [comment]
Hi @scottohara - 

Thanks for the detailed report - I just run a quick test seems the default image is the right one, **container-based Trusty**  https://travis-ci.org/MariadeAnton/hola/jobs/272508675#L2
Is it possible that you're [using Docker](https://docs.travis-ci.com/user/docker) within your builds?  That would send them toward `sudo: required` in any case. 

Could you point us to the build in which this happened? If a private one, please send it along to support@travis-ci.com :)

**Comment by scottohara** [comment]
Hi @MariadeAnton,

Thanks for your offer to look into this. An example build where this is happening is:
https://travis-ci.org/scottohara/loot/jobs/272263055

The source `.travis.yml` file for this build can be seen here: https://github.com/scottohara/loot/blob/master/.travis.yml

**Comment by scottohara** [comment]
Just following up on this, as with the new 2017-12-12 Trusty environment this still seems to be occurring.

Example: https://travis-ci.org/scottohara/loot/builds/324892812

I'm assuming sudo-required Trusty was used based on the presence of `*-gce` in the host name, e.g. 
`hostname: fd00341b-8ae3-46a2-a3eb-3c9b15988e17@1.production-5-worker-org-c-1-gce`

Below is an excerpt from my `.travis.yml` file.

As you can see, it doesn't use Docker or `sudo: required`.

However it *does* install Chrome stable and CodeClimate test reporter.  Is it possible that one of these is preventing container-based Trusty from being used?

```yaml
language: ruby

cache:
  bundler: true
  directories:
    - node_modules

addons:
  chrome: stable

before_install:
  - nvm install
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

install:
  - bundle install --without production --path=${BUNDLE_PATH:-vendor/bundle}
  - npm install

before_script: bundle exec rake db:create db:migrate

script:
  - bundle exec rubocop -DESP
  - bundle exec rake
  - npm test

after_script:
  - ./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.backend.json coverage/backend/.resultset.json
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.frontend.json coverage/frontend/lcov.info
  - ./cc-test-reporter sum-coverage coverage/codeclimate.*.json -p 2
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi
```
