### ISSUE TITLE
git stash being called even when skip_cleanup is set

### ISSUE THREAD

**Issue by n1474335** [travis-ci/travis-ci#8351]
My GitHub releases have started failing with no changes to the `.travis.yml` config. It seems from the logs that `git stash --all` is being called which then leads to the files not being available to upload:

```
Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`. See https://docs.travis-ci.com/user/deployment/#Uploading-Files.
```
```
Dropped refs/stash@{0} (594f4cbcfad20960d547a54ad28b0fcfba021fe6)
/home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/client/releases.rb:86:in `initialize': No such file or directory @ rb_sysopen - build/prod/cyberchef.htm (Errno::ENOENT)
```

My deployment config looks like this:

```
  - provider: releases
    skip_cleaup: true
    api_key:
      secure: "..."
    file:
      - build/prod/cyberchef.htm
      - build/node/CyberChef.js
    on:
      repo: gchq/CyberChef
      tags: true
```

I can't see why the stash is happening at all. Any ideas?

[Failed build](https://travis-ci.org/gchq/CyberChef/builds/272109362)
[`.travis.yml` file](https://github.com/gchq/CyberChef/blob/v5.18.0/.travis.yml)
