### ISSUE TITLE
Enable decision of yarn vs npm by env vars

### ISSUE THREAD

**Issue by maybeec** [travis-ci/travis-ci#8359]
Is there an opportunity to build a node project once with yarn and once with npm?
We maintain an open source project, which is supporting both. Due to the docs o ftravis, it however, determines the build tool on its own as of the existence of yarn.lock.

**Comment by BanzaiMan** [comment]
That decision can be overridden.

Set up two env vars, and override `install` step with it.

```yaml
env:
  - INSTALL_CMD=yarn
  - INSTALL_CMD=npm
install:
  - $INSTALL_CMD
⋮
```
