### ISSUE TITLE
Java: Ant build using Ivy fails; bad path (no such file or directory)

### ISSUE THREAD

**Issue by jmibanez** [travis-ci/travis-ci#8373]
On my project, builds have suddenly started to fail after the switch to the Trusty image. From what I can tell, the failure is due to the configured install step on my project (the `bootstrap` Ant task, which fetches dependencies using Ivy) not persisting files for some reason — the actual build step complains of a bad path element/no such file or directory (`bad path element`, e.g. ` warning: [path] bad path element "/home/travis/build/jmibanez/jmeter-rmi-plugin/lib/development/udunits-4.5.5.jar": no such file or directory`), and the specific error doesn't show up locally if the `lib` directory is missing or empty. The oddest part is that the class files seem to have been built, but the build only fails because Ant can't find the JUnit JAR and therefore can't create the JUnit task.

This used to work on Precise before the switchover.

The relevant config is very simple:

```
language: java
jdk:
  - oraclejdk8
install: ant bootstrap
script: ant clean test jar
deploy:
  provider: releases
  api_key:
    secure: // elided
  file: build/ApacheJMeter_rmi.jar
  skip_cleanup: true
  on:
    tags: true
```

I tried retrying a previous successful build, and it also failed (but was run on Precise); the failure was at the same point, but the errors about the libraries did not show up.

As there were no changes in the configuration, nor in the code, this looks to be an issue in the Travis CI environment.

Reference: [https://travis-ci.org/jmibanez/jmeter-rmi-plugin]; see [https://travis-ci.org/jmibanez/jmeter-rmi-plugin/builds/269508825] and [https://travis-ci.org/jmibanez/jmeter-rmi-plugin/builds/272471630].
