### ISSUE TITLE
stages feature

### ISSUE THREAD

**Issue by abacaphiliac** [travis-ci/travis-ci#8383]
hi Team,

thanks for the great project. i use it daily. Stages is awesome. i'm testing it for the first time today.

i would love to have a pre-test stage, to validate things like syntax and style. is it possible?

**Comment by BanzaiMan** [comment]
You can define a separate stage. What have you tried?

**Comment by abacaphiliac** [comment]
i have created 2 additional stages: Lint and Coverage. i would like to run the Syntax and Style jobs in Lint before the default Test stage executes, because these are less expensive jobs to run.

**Comment by BanzaiMan** [comment]
Please include the bills log URL(s).

**Comment by abacaphiliac** [comment]
here is one example:
https://travis-ci.org/enlitepro/enlite-monolog/builds/273696435

thank you for taking the time to explore this with me : )

**Comment by BanzaiMan** [comment]
So, this is not impossible, but tedious, because the matrix expansion at the moment happens only in the first Build Stage, which is named `Test` by default. You can change the name of this stage, but then the matrix happens there as a result.

You'll have to write something like:

```yaml
jobs:
  include:
    - stage: "pre-test"
      script: DO_STUFF
    - stage: "test"
      php: "5.4"
      env: DEPS="latest"
    - stage: "test"
      php: "5.4"
      env: DEPS="lowest"
    - stage: "test"
      php: "5.5"
      env: DEPS="latest"
    - stage: "test"
      php: "5.5"
      env: DEPS="lowest"
    - stage: "test"
      php: "5.6"
      env: DEPS="latest"
    - stage: "test"
      php: "5.6"
      env: DEPS="lowest"
⋮
    - stage: "lint"
      php: "7.1"
      env: DEPS="latest"
    - stage: "lint"
      php: "7.1"
      env: DEPS="lowest"
    - stage: "coverage"
      php: "5.4"
      env: DEPS="latest"
```

This shortcoming of the matrix expansion is addressed elsewhere, though. This issue should be a duplicate, but I can't locate which one.
