### ISSUE TITLE
skip_cleanup fails on elastic beanstalk

### ISSUE THREAD

**Issue by dylandechant** [travis-ci/travis-ci#8385]
trying to figure this one out, it may be a bug or something travis just does not support yet, here is my .travis.yaml:

```yaml
language: node_js
node_js:
- 7.10.1
branches:
  only:
    - master
    - staging
before_script:
  - npm install -g @angular/cli
script:
  - NODE_ENV=test npm test
  - if [ "$TRAVIS_BRANCH" = "staging" ]; then ng build --env=staging; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then ng build --env=prod; fi
deploy:
  - provider: elasticbeanstalk
    edge: true
    access_key_id: "$prod_access_key_id"
    secret_access_key:
      secure: "$prod_secret_access_key"
    region: us-east-1
    app: my-cool-app
    env: my-cool-app-env
    bucket_name: "$my-cool-bucket"
    skip_cleanup: true
    on:
      repo: myOrg/my-repo
      branch: master
```

I have a backend nodejs, and a separate frontend here.  I'm trying to build the ng2/4 frontend in travis. everything works fine when i remove `skip_cleanup: true`, i'm trying to keep my `dist` folder out of version control by using `skip_cleanup: true`

when i do include it as seen above i get this error on travis:
```
Deploying application
/home/travis/.rvm/gems/ruby-2.2.7/gems/rubyzip-1.2.1/lib/zip/entry.rb:378:in `lstat': No such file or directory @ rb_file_s_lstat - dist/scripts.bundle.js.map (Errno::ENOENT)
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/rubyzip-1.2.1/lib/zip/entry.rb:378:in `file_stat'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/rubyzip-1.2.1/lib/zip/entry.rb:512:in `gather_fileinfo_from_srcpath'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/rubyzip-1.2.1/lib/zip/file.rb:272:in `add'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.43.travis.2280.5/lib/dpl/provider/elastic_beanstalk.rb:120:in `block (2 levels) in create_zip'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.43.travis.2280.5/lib/dpl/provider/elastic_beanstalk.rb:118:in `each'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.43.travis.2280.5/lib/dpl/provider/elastic_beanstalk.rb:118:in `block in create_zip'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/rubyzip-1.2.1/lib/zip/file.rb:101:in `open'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.43.travis.2280.5/lib/dpl/provider/elastic_beanstalk.rb:117:in `create_zip'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.43.travis.2280.5/lib/dpl/provider/elastic_beanstalk.rb:47:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.43.travis.2280.5/lib/dpl/provider.rb:154:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.43.travis.2280.5/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.43.travis.2280.5/lib/dpl/provider.rb:154:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.43.travis.2280.5/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.43.travis.2280.5/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.43.travis.2280.5/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
failed to deploy
```

i hoped adding `edge: true` would solve but i get the same results regardless.

Thanks

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by dylandechant** [comment]
https://travis-ci.com/PerkinsAndWill-IO/SAP/builds/54183862

**Comment by BanzaiMan** [comment]
The option is most certainly respected. Otherwise, you would see the message:

    Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`.  See https://docs.travis-ci.com/user/deployment/#Uploading-Files.

We get the list of files to pack in an archive with `git ls-files -z` at the deployment time. Does `dist/scripts.bundle.js.map` exist then?

**Comment by dylandechant** [comment]
I mean the build spits that file out locally and the build finishes successfully on Travis, I don't know why Travis would think that file exists if it doesn't?

**Comment by BanzaiMan** [comment]
Hi, @dylandechant I see that your recent deployments are successful. Were you able to sort things out?

**Comment by dylandechant** [comment]
@BanzaiMan it is still not resolved: https://travis-ci.com/PerkinsAndWill-IO/SAP/builds/54949226

it works if i comment out `skip_cleanup: true`, which doesn't help me too much

**Comment by dylandechant** [comment]
@BanzaiMan I've made some progress with this but still is not working how i would expect in travis here is my .travis.yml file now:

```yaml
language: node_js
node_js:
- 7.10.1
branches:
  only:
    - master
    - staging
before_script:
  - npm install -g @angular/cli
script:
  - NODE_ENV=test npm test
  - if [ "$TRAVIS_BRANCH" = "staging" ]; then ng build --env=staging; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then ng build --env=prod; fi
  - git add .
  - git commit -m 'commit for deploy'
deploy:
  - provider: elasticbeanstalk
    edge: true
    access_key_id: "$prod_access_key_id"
    secret_access_key:
      secure: "$prod_secret_access_key"
    region: us-east-1
    app: my-cool-app
    env: my-cool-app-env
    bucket_name: "$my-cool-bucket"
    skip_cleanup: true
    on:
      repo: myOrg/my-repo
      branch: master
- provider: elasticbeanstalk
    edge: true
    access_key_id: "$access_key_id"
    secret_access_key:
      secure: "$secret_access_key"
    region: us-east-1
    app: my-cool-app-staging
    env: my-cool-app-staging
    bucket_name: "$my_questionable_bucket"
    skip_cleanup: true
    on:
      repo: myOrg/my-repo
      branch: staging
```

You'll notice i am running `git add .` and git commit -m 'commit things'`.  This works but now have to check the dist folder into version control which i am trying to avoid. Thank you for looking into this!
