### ISSUE TITLE
How to build on both Android and non-Android Java?

### ISSUE THREAD

**Issue by Pr0methean** [travis-ci/travis-ci#8402]
I've tried the following entries in my .travis.yml:
```
language:
  - java
  - android
jdk:
  - oraclejdk9
  - oraclejdk8
  - openjdk8
env:
  - MODE=tests-combined
  - MODE=benchmark
```
I would've expected these to create a 4x2 test matrix, with Android being treated as a 4th JDK. Instead, I get the same 3x2 matrix as when I specify only `language: java`. How do I use Travis-CI to check that my Java library works on both Android and other JVMs?

**Comment by BanzaiMan** [comment]
`language` is not a matrix expansion key, and only the first is recognized. As such, you'll have to create the other 3x2 matrix for `android` manually.

```yaml
language:
  - java
jdk:
  - oraclejdk9
  - oraclejdk8
  - openjdk8
env:
  - MODE=tests-combined
  - MODE=benchmark
matrix:
  include:
    - language: android
      jdk: oraclejdk9
      env: MODE=tests-combined
    - language: android
      jdk: oraclejdk9
      env: MODE=benchmark
    - language: android
      jdk: oraclejdk8
      env: MODE=tests-combined
  ⋮
```
