### ISSUE TITLE
before_deploy + deploy script: deps installed are not available

### ISSUE THREAD

**Issue by caarlos0** [travis-ci/travis-ci#8445]
Seems like what is installed inside the `before_deploy` section is not available in the `deploy` section itself.

Config used to reproduce the problem:

```yaml
dist: trusty
sudo: required
language: go
go: 1.9
services:
  - docker
install: go get ./...
script: go test ./...
before_deploy:
  - gem install fpm
  - which fpm # /home/travis/.rvm/gems/ruby-2.4.1/bin/fpm
deploy:
  skip_cleanup: true
  provider: script
  script: which fpm # fails
notifications:
  email: false
```

**Comment by BanzaiMan** [comment]
This is described in more detail in https://docs.travis-ci.com/user/deployment/script#Ruby-version.

```yaml
deploy:
  provider: script
  script: rvm $TRAVIS_RUBY_VERSION do which fpm
  ⋮
```

**Comment by caarlos0** [comment]
@BanzaiMan 

tried:

```
script: rvm $TRAVIS_RUBY_VERSION do curl -sL https://git.io/goreleaser | bash
```

it shows:

```
`rvm do curl -sL https://git.io/goreleaser` was removed, use `rvm 1.9.2,1.9.3 do curl -sL https://git.io/goreleaser` or `rvm all do curl -sL https://git.io/goreleaser` instead.
```

**Comment by caarlos0** [comment]
`script: rvm $TRAVIS_RUBY_VERSION do which fpm`

also didn't work

**Comment by BanzaiMan** [comment]
Ah. Sorry. You're running a Go build, so `$TRAVIS_BUILD_VERSION` is undefined. Also, the current `rvm` invocation is wrong.

Since the version of Ruby on this image is 2.4.1, you can use that value.

```yaml
deploy:
  provider: script
  script: rvm use 2.4.1 do which fpm
```

The document should also be improved.

**Comment by caarlos0** [comment]
yeah, that's what I end up doing...



> The document should also be improved.

that would be great, thanks :)

**Comment by mattstratton** [comment]
Just to clarify, if I was to add this to my yaml...

```
deploy:
  - provider: script
    skip_cleanup: true
    script: rvm use 2.4.1 do curl -sL http://git.io/goreleaser | bash
```

and the version of Ruby was updated on the images in Travis, it would start failing builds, so I would just have to change the version at that point, right? On a go build machine there is no way to get what the "current" ruby is, right?

No big deal if that is the case; just checking.

**Comment by mattstratton** [comment]
For what it's worth, this isn't working. That exact setup results in the following output from travis:

```
   • CREATING LINUX PACKAGES WITH FPM
   ⨯ release failed            error=fpm not present in $PATH
```

You can see that `fpm` is in there:
```
0.01s$ ls $HOME/.rvm/gems/ruby-2.4.1/bin/
bundle
bundler
dotenv
fpm
mustache
please-manage-user
pleaserun
ruby_executable_hooks
rubygems-cabin-test
```

It's even in the first thing in the $PATH:

```
0.01s$ echo $PATH
/home/travis/.rvm/gems/ruby-2.4.1/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.8.linux.amd64/bin:/home/travis/bin:/home/travis/bin:/home/travis/.local/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v7.4.0/bin:/home/travis/.kiex/elixirs/elixir-1.4.5/bin:/home/travis/.kiex/bin:/home/travis/.rvm/gems/ruby-2.4.1/bin:/home/travis/.rvm/gems/ruby-2.4.1@global/bin:/home/travis/.rvm/rubies/ruby-2.4.1/bin:/home/travis/gopath/bin:/usr/local/phantomjs/bin:/usr/local/phantomjs:/usr/local/neo4j-3.2.1/bin:/usr/local/clang-3.9.0/bin:/home/travis/.gimme/versions/go1.7.4.linux.amd64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin
```

@caarlos0 - can you help me figure out where I'm being stupid? Here's an example of the failing build:
https://travis-ci.org/devopsdays/devopsdays-cli/jobs/281603197

**Comment by caarlos0** [comment]
@mattstratton this is what I did, didn't test if it is still working

https://github.com/goreleaser/example/blob/master/.travis.yml

**Comment by mattstratton** [comment]
Yeah, that’s totally different since I’m using the container-based infrastructure. I try to avoid the vm’s because of speed issues, but I was about to go down the path of doing a vm and using docker for fpm. Seems heavier than it should need to be though. Lol

**Comment by caarlos0** [comment]
yeah :/

**Comment by mattstratton** [comment]
It totally worked on the container infra - although I took out the snap stuff.

**Comment by caarlos0** [comment]
can you share the .travis.yml you used?

**Comment by mattstratton** [comment]
Sure. I'm monkeying around with mine to get bintray uploads, but here's an older version that worked fine:

```
dist: trusty
sudo: false
language: go
addons:
  apt:
    packages:
    - rpm
go: 1.9
install:
- make install
script: go test ./...
before_deploy:
- gem install fpm
deploy:
  skip_cleanup: true
  provider: script
  script: curl -sL https://git.io/goreleaser | rvm 2.4.1 do bash
  on:
    tags: true
notifications:
  email: false
```
