### ISSUE TITLE
openjdk6 builds failed with "NB: JAVA_HOME should point to a JDK not a JRE"

### ISSUE THREAD

**Issue by shuaichang** [travis-ci/travis-ci#8452]
Recent openjdk6 builds failed with below messages, one example https://travis-ci.org/aliyun/fc-java-sdk/jobs/276211613,  `java -Xmx32m -version` shows java 1.8. I saw a similar issue https://github.com/travis-ci/travis-ci/issues/8423 that was closed as a duplicate of https://github.com/travis-ci/travis-ci/issues/7884, but that only mentioned switching from oraclejdk7 to openjdk7.

Any idea what happened to openjdk6?

```
$ export PATH=$JAVA_HOME/bin:$PATH
$ java -Xmx32m -version
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
$ javac -J-Xmx32m -version
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
javac 1.8.0_144
0.02s$ mvn clean package install -DskipTests -Dgpg.skip
The JAVA_HOME environment variable is not defined correctly
This environment variable is needed to run this program
NB: JAVA_HOME should point to a JDK not a JRE
```

**Comment by shuaichang** [comment]
Seems openjdk6 is not coming along with trusty VM as described in https://github.com/travis-ci/travis-ci/issues/8199#issuecomment-327246053

To make everything working, below travis config can be helpful, credit: https://github.com/travis-ci/enterprise-installation/issues/14#issuecomment-329983790

```
language: java

addons:
  apt:
    packages:
      - openjdk-6-jdk

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk8

install:
  - echo "Downloading Maven 3.0";
  - wget https://archive.apache.org/dist/maven/binaries/apache-maven-3.0-bin.zip || travis_terminate 1
  - unzip -qq apache-maven-3.0-bin.zip || travis_terminate 1
  - export M2_HOME=$PWD/apache-maven-3.0
  - export PATH=$M2_HOME/bin:$PATH
  - mvn -version
  - mvn clean package install -DskipTests -Dgpg.skip
script:
  - mvn test
```
