### ISSUE TITLE
GAE Deploy - Skip Cleanup Not Working

### ISSUE THREAD

**Issue by bursu** [travis-ci/travis-ci#8458]
When deploying to Google App Engine, the `skip_cleanup: true` flag does not register. I have tried adding a `.npmignore` file and changing the `.gitignore` file to not include the files that should not be removed.

`.travis.yml`
```
language: node_js
node_js:
- '7'
cache:
  directories:
  - node_modules
deploy:
  provider: gae
  keyfile: client-secret.json
  project: febbit-175116
  skip_cleanup: true
  no_promote: false
  no_stop_previous_version: false
before_install:
- openssl aes-256-cbc -K $encrypted_05e5e85cd5af_key -iv $encrypted_05e5e85cd5af_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar -xvf secrets.tar
before_deploy:
  - ls
  - rm .gitignore
  - cp .gitignore.travis .gitignore
  - ls
```
