### ISSUE TITLE
All Stack --nix builds suddenly started failing

### ISSUE THREAD

**Issue by chris-martin** [travis-ci/travis-ci#8474]
I use this basic setup for a lot of Haskell projects:

```yaml
language: nix

env:
  - LC_ALL=en_US.UTF-8

cache:
  directories:
    - $HOME/.stack

before_install:
  - nix-env -i stack

script:
  - stack --nix --no-terminal test

notifications:
  email: false
```

This was working for a while, but now all of my builds are now failing like this:

```
*** Downloading ‘https://cache.nixos.org/nar/00ai1a23s0byw5wqwj811h6yqlkdc69f4p3bam95gffdic8ryhy1.nar.xz’ to ‘/nix/store/mzz1d91aqib0n7b4j0a0by93n0q89lis-stdenv’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9168  100  9168    0     0   9168      0  0:00:01 --:--:--  0:00:01  373k

rain-water-0.1.0.0: configure (lib + test)
/home/travis/.stack/setup-exe-cache/x86_64-linux-nix/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2: streamingProcess: runInteractiveProcess: exec: does not exist (No such file or directory)


The command "stack --nix --no-terminal test" exited with 1.
store build cache

nothing changed, not updating cache


Done. Your build exited with 1.
```

What changed?
