### ISSUE TITLE
Feature request: every-nth-build option

### ISSUE THREAD

**Issue by Pr0methean** [travis-ci/travis-ci#8476]
I currently have 12 OSX jobs in my build, but I don't think 8 of them really need to run every time as long as they're run every so often. Why not add the option to designate in the matrix/include that a particular job should run only where the build number was equivalent to M modulo N (including cron jobs), for some specified values of M and N, or when the previous run had failed or been canceled? For example, suppose I set the following on build 1337:
```
matrix:
  include:
    - language: java
      os: osx
      osx_image: xcode8.3
      env: OP=unit-tests
      every-nth-build: 8
      offset: 0
    - language: java
      os: osx
      osx_image: xcode8.2
      env: OP=benchmark
      every-nth-build: 8
      offset: 1
```
On Build 1336, both of those jobs had passed.
1337 mod 8 is 1, so the xcode8.2 job would run on builds 1337, 1345, 1353 and so on. The xcode8.3 job would run on builds 1344, 1352, 1360 and so on.
If the xcode8.2 job failed on build 1345, then it would run again on build 1346. If it failed again or got cancelled, it would also run on build 1347; but if it passed that time, it wouldn't run again until 1353.
