### ISSUE TITLE
string together build stages

### ISSUE THREAD

**Issue by ncullen93** [travis-ci/travis-ci#8485]
Hi ! thanks for the amazing product.. I want to run two sets of builds (linux + mac) with three identical stages each... making sure that each stage environment carries over to the next. Are there any tips from my starting point? Thanks!!

```yml
jobs:
  include:

    - stage: make itk
      script:
        - ./configure_ITK_External.sh
        - export ITK_DIR=~/itkbuild/itkbuild
      os: linux
      python: 3.6
    - stage: make itk
      script:
        - ./configure_ITK_External.sh
        - export ITK_DIR=~/itkbuild/itkbuild
      os: osx
      sudo: required
      language: generic

    - stage: install
      script: |
        travis_retry pip install --upgrade pip setuptools wheel
        travis_retry pip install -r requirements.txt --only-binary=scipy
        python setup.py install
      os: linux
      python: 3.6
    - stage: install
      script: |
        travis_retry pip install --upgrade pip setuptools wheel
        travis_retry pip install -r requirements.txt --only-binary=scipy
        python setup.py install
      os: osx
      sudo: required
      language: generic

    - stage: test
      script:
        - ./tests/run_test.sh
      os: osx
      sudo: required
      language: generic
    - stage: test
      script:
        - ./tests/run_test.sh
      os: linux
      python: 3.6
```
