### ISSUE TITLE
My job get Status: Errored

### ISSUE THREAD

**Issue by jcubic** [travis-ci/travis-ci#8490]
Last build was success full and I've remove the tag update README commit and then add tag again (I did it before it was fine) and now the status is Errored, here is the link to build

https://travis-ci.org/jcubic/jquery.terminal/builds/279155204?utm_source=email&utm_medium=notification

What's wrong? There are no logs?

**Comment by jcubic** [comment]
It's now canceled and last build is successful but something was wrong.

**Comment by BanzaiMan** [comment]
> Last build was successful and I've remove the tag update README commit and then add tag again (I did it before and it was fine) and now the status is Errored

Could you elaborate on what you did? What command did you run, in which sequence, what did you expect to happen, and what happened instead?

**Comment by jcubic** [comment]
I think that the commands don't even started because there is no logs. After that errored email, I get canceled one and the build was rerun and it was successful it seems temporary glitch. But maybe you want to investigate because it may be a bug.

But just in case my .travis.yml look like this:
```yaml
language: node_js
node_js:
  - "node"
install:
  - npm install
script:
  - make
  - make lint
  - make test
after_script:
  - make coveralls
```
and make is running bash commands like sed/grep/git, you can see the [Makefile](https://github.com/jcubic/jquery.terminal/blob/master/Makefile) for details.
