### ISSUE TITLE
Upload all branch artifacts to S3

### ISSUE THREAD

**Issue by simlu** [travis-ci/travis-ci#8492]
I'm trying to push the latest artifact to s3 for every branch. Something like the following used to work sometime in 2016, however it doesn't seem to work anymore.

Can this still be achieved with plain Travis or do I need to write a custom deploy script in `after_success`?

```
deploy:
  provider: s3
  access_key_id: $S3_ACCESS_KEY_ID
  secret_access_key:
    secure: "Pp91ag...hrw="
  bucket: $S3_BUCKET
  region: $S3_REGION
  upload-dir: build/$TRAVIS_BRANCH
  local-dir: $TRAVIS_BUILD_DIR/target/build
  skip_cleanup: true
  acl: public_read
  on:
    repo: $DEPLOY_REPO
    all_branches: true
    jdk: oraclejdk8
```

**Comment by simlu** [comment]
Not as secure unfortunately, but something like this seems to work fine:
```
after_success:
  - "mvn -DskipTests package"
  - "pip install --user awscli"
  - "~/.local/bin/aws s3 cp $TRAVIS_BUILD_DIR/target/build/voxelshop-bin.zip s3://$S3_BUCKET/build/$TRAVIS_BRANCH/voxelshop-bin.zip --region=$S3_REGION"
```

Defining AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY.

Still curious if there is a better way here.

**Comment by BanzaiMan** [comment]
Could you point to a couple of build log URLs that illustrate the problem you are reporting, please?

1. Log with a successful deployment from "some time in 2016"
1. Log with a failed deployment in the recent weeks

Thanks.

**Comment by simlu** [comment]
1. I'll need to dig through some old logs. But should be able to provide this. Will edit this post with details.
2. There is no failure. It just doesn't trigger anymore.

**Comment by BanzaiMan** [comment]
You appear to have omitted a critical detail in the original description of this issue.

In https://github.com/simlu/voxelshop/blob/1923b4e5526cfff37f1a98662b8452e5a127d01c/.travis.yml#L39, I see:

```yaml
deploy:
  - provider: releases
    tags: true
    ⋮
```

This means that the deployment is triggered _**exactly when**_ there is a tag. You can see this in https://travis-ci.org/simlu/voxelshop/builds/279338364.

I should note that the current configuration has two occurrences of `deploy` keys, (https://github.com/simlu/voxelshop/blob/1923b4e5526cfff37f1a98662b8452e5a127d01c/.travis.yml#L29 and https://github.com/simlu/voxelshop/blob/1923b4e5526cfff37f1a98662b8452e5a127d01c/.travis.yml#L42), but only the last one is effective.

I am not sure what exactly you want to accomplish, but you'd probably want to put them in an array.

For example:

```yaml
deploy:
  - provider: releases
    on:
      branch: qa
    ⋮
  - provider: releases
    on:
      branch: master
    ⋮
```

At any rate, I don't think there is much to do here. I'm closing this.
