### ISSUE TITLE
Issue with Travis and RGeo Ruby gem

### ISSUE THREAD

**Issue by Zank94** [travis-ci/travis-ci#8500]
Hi everyone,

I've got an issue when I run a build on Travis due to the RGeo gem dependency with proj4.

I'm using ruby 2.2.7 and no matter how many libs related to geos and proj I install before the bundle exec, I always get the same errors:
- Proj4 is not supported. Some actions won't work
- RGeo::Error::UnsupportedOperation: Proj4 is not supported because the proj4 library was not found at install time

Tests work fine in local.

When I run `which proj` and `find /usr | grep libproj.so` on my machine, it returns:
```
/usr/bin/proj
/usr/lib/x86_64-linux-gnu/libproj.so
/usr/lib/x86_64-linux-gnu/libproj.so.9
/usr/lib/x86_64-linux-gnu/libproj.so.9.1.0
```

However, on Travis I get:
```
/usr/bin/proj
/usr/lib/libproj.so
/usr/lib/libproj.so.0
/usr/lib/libproj.so.0.7.0
```

Here is the travis.yml file:
```
language: ruby
bundler_args: "--full-index --without development"
cache: bundler
rvm:
- 2.2.7
before_install: test/ci/before_install
before_script: test/ci/before_script
script: xvfb-run bundle exec rake test:models test:libs test:controllers DRIVER=webkit
services:
- redis-server
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=COVERALLS_REPO_TOKEN
  email: false
  slack:
    secure: v1/ya/fyroy3BmW9FDMmKi3lwamnzY6ktQAU/vEJCg4AgvauY0QJthMsLXOBb3RnhFWao2Kj2H40XjI7VtH3z46VEq6DPLURBqmAc24c30ZMi/XIM9YqauYeEPHPhM0nDQY+s0ovU2uX/1w7uv/atNjy0n643An61Em+qPwIW5U=
```

Here is the before_install file:
```
#!/bin/bash

sudo apt-get update -qq

echo ""
echo "--------------------------------------------------------------------------------"
echo "Install packages:"

# Force stop to prevent conflict with existing PostgreSQL
sudo /etc/init.d/postgresql stop

# Install needed packages including PostgreSQL
echo "Removing old Postgres versions."
sudo apt-get remove postgresql-client-9.1 postgresql-client-9.2 postgresql-client-9.3 postgresql-client-9.4 postgresql-client-9.5
echo""
echo "Dependencies install..."
echo""
sudo apt-get install -f -qq postgresql-9.6-postgis-2.3 graphicsmagick tesseract-ocr tesseract-ocr-fra tesseract-ocr-eng tesseract-ocr-spa pdftk libreoffice poppler-utils poppler-data qt5-default libqt5webkit5-dev gstreamer1.0-x gstreamer1.0-tools gstreamer1.0-plugins-base libgeos-dev libproj-dev
echo ""
echo "Dependencies installed!"
echo ""

# Configure PostgreSQL port to 5432
sudo sed -i -r 's/port\s*=\s*[0-9]+/port = 5432/g' /etc/postgresql/9.6/main/postgresql.conf

# Grant access to all
sudo sed -i '1i local all all trust' /etc/postgresql/9.6/main/pg_hba.conf

# Force PostgreSQL restart
sudo /etc/init.d/postgresql stop
sudo /etc/init.d/postgresql start 9.6
```

You can find the build [here](https://travis-ci.org/ekylibre/ekylibre/builds/279578364), any help with this would be much appreciated!

Thanks
