### ISSUE TITLE
Use npm scripts at script deployment

### ISSUE THREAD

**Issue by kthjm** [travis-ci/travis-ci#8505]
relate: #5538 
This is just report and intended to inform other Node.js users.

Using npm scripts to setup [script deployment](https://docs.travis-ci.com/user/deployment/script/)  as with lifecycle hook may be throwd error 127.  
The problematic case is to refer `cli.js`  via `node_modules/.bin`.  

To avoid error, should refer `cli.js` directly and not to rely on `node_modules/.bin` from scripts field.

.travis.yml:
```yml
deploy:
  provider: script
  script: yarn succeed
  skip_cleanup: true
  on:
    tags: true
```
package.json:
```json
scripts: {
  "fail": "foo",
  "succeed": "node ./node_modules/foo/cli.js"
}
```

This is probably a problem with path, But I don't know the details.
I would be pleased if getting a detailed explanation.
