### ISSUE TITLE
Trigger deployment on tag push not working

### ISSUE THREAD

**Issue by ArtFlag** [travis-ci/travis-ci#8518]
Hi,

I'm trying to understand how to use the deploy section to release my software on GitHub.

I've spent hours figuring out why Travis won't trigger when I push a tag in order to deploy, or why pushing some commits then a tag still shows "Skipping a deployment with the releases provider because this is not a tagged commit"

Here is what I do:

1. `git commit` some stuff
1. `git tag -a v1.0 -m "v1"`
1. `git push` (to master)
1. `git push --tags` (to master too)

The build starts, tells me there is no tag (but Github shows my tag, so there is a tag).

```
.travis.yml:
language: python
branches:
  only:
  - master
python:
- '2.7'
before_install:
- if [ -z "$TRAVIS_TAG" ]; then exit 0; fi
- wget https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh -O ~/.nvm/nvm.sh
- source ~/.nvm/nvm.sh
- nvm install 5
- node --version
install:
- pip install -U pip
- pip install -r requirements.txt
- npm install -g grunt-cli
- npm install -g yarn
- npm install -g bower
- yarn add global ruby
- bower install
- gem install sass
script:
- grunt release
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ANIqYltOl+jdI
  file: $TRAVIS_BUILD_DIR/theme.tar.gz
  on:
    repo: repo/theme
    tags: true
```

What am I doing wrong?

I also tried pushing a tag only, it does not trigger the build. 

I've noodled quite a bit with my tags (deleting them on the remote and locally, etc), not sure if that has any impact.

One extra question: if I have to push some commits and then push my tags, how does Travis know to stop the first build and start when the tags are pushed? I'm not sure I understand how to use this properly.

Thanks for any pointers.

(My repo is private, let me know if you need extra info on the commits)
