### ISSUE TITLE
Concurrent jobs per stage

### ISSUE THREAD

**Issue by jakubsikora** [travis-ci/travis-ci#8527]
Hi, 

I'm following https://docs.travis-ci.com/user/build-stages/#How-to-define-Build-Stages%3F and it says "This configuration creates the build from the screencast above. I.e. it creates a build with three jobs, two of which start in parallel in the first stage (named test), while the third job on the second stage (named deploy) starts only after the test stage completes successfully.".

I'm trying to run 1st stage with 1 job and 2nd stage with 2 jobs. 

```
jobs:
    include:
      - stage: caching
        script: ./bin/test1
      - stage: testing
        script: ./bin/test2
        script: ./bin/test3
```

However I can only see:
![screen shot 2017-10-03 at 14 24 18](https://user-images.githubusercontent.com/3074083/31127366-9beab2ee-a846-11e7-86d8-8391bb9d4e92.png)

I would like to have 2 concurrent jobs in my `testing` stage.

**Comment by jakubsikora** [comment]
Sorry, 

I cannot read properly:)

```
jobs:
    include:
      - stage: caching
        script: ./bin/test1
      - stage: testing
        script: ./bin/test2
      -
        script: ./bin/test3
```

works.
