### ISSUE TITLE
Please add PostgreSQL 10.0

### ISSUE THREAD

**Issue by Majkl578** [travis-ci/travis-ci#8537]
Hello,

PostgreSQL 10.0 has been released today: https://www.postgresql.org/about/news/1786/.
Can we please have it added to the build environment? 🎉 

Thanks.

**Comment by Majkl578** [comment]
@BanzaiMan Is there any ETA for this please? There seems to be an increasing demand.

**Comment by AMDmi3** [comment]
For ones interested, a quick&dirty way to enable pg10 manually:

```yaml
addons:
  postgresql: "9.6"  # I'm just using this, if you're using another version, might need to fix the pg_hba.conf path below
before_install:
  # stop old version
  - sudo /etc/init.d/postgresql stop
  # add postgresql 10 repository
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs 2>/dev/null)-pgdg main" >> /etc/apt/sources.list.d/postgresql.list'
  # install new version
  - sudo apt-get update -qq
  - sudo apt-get install -qq postgresql-10 postgresql-client-10
  # clone auth config (might need to fix source path for another version)
  - sudo cp /etc/postgresql/9.6/main/pg_hba.conf /etc/postgresql/10/main/pg_hba.conf
  # start new version
  - sudo /etc/init.d/postgresql restart
  # I haven't investigated or tried to fix, but pg10 uses another port
  # for some reason, so tell applications to use correct port
  - export PGPORT=5433
```

**Comment by PillowPillow** [comment]
@BanzaiMan Any ETA for this please?

**Comment by BanzaiMan** [comment]
Preliminary work to get it on the build image is https://github.com/travis-ci/travis-cookbooks/pull/923, but it is still WIP.

**Comment by damianobarbati** [comment]
@BanzaiMan any news on this?

**Comment by Majkl578** [comment]
@BanzaiMan Anything? It's been almost 2 months already. :/

**Comment by simPod** [comment]
10.1 is out

**Comment by therealmarv** [comment]
workaround suggestion: Use a docker based CI like gitlab CI, Circle CI or Drone CI. It's easy to integrate the latest official [Postgres docker image](https://hub.docker.com/_/postgres/) and build a docker based infrastructure on CI tests without relying on the integration speed of the CI vendor on fat CI test images.

**Comment by mpugach** [comment]
@AMDmi3 `sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/10/main/postgresql.conf` fixes port issue if placed before postgres restart

**Comment by simPod** [comment]
@BanzaiMan any ETA? Already two months 🌋🦖🦕

**Comment by eritiro** [comment]
:sob:

**Comment by Majkl578** [comment]
For anyone who is tired of waiting, here's probably the easiest way without external repos and different port. 
1) Create file called i.e. `install-postgres-10.sh`:
```bash
#!/usr/bin/env bash

set -ex

echo "Installing Postgres 10"
sudo service postgresql stop
sudo apt-get remove -q 'postgresql-*'
sudo apt-get update -q
sudo apt-get install -q postgresql-10 postgresql-client-10
sudo cp /etc/postgresql/{9.6,10}/main/pg_hba.conf

echo "Restarting Postgres 10"
sudo service postgresql restart
```
2) Add job parameters:
```yaml
  sudo: required
  services:
    - postgresql
  addons:
    postgresql: "9.6"
  before_script:
    - bash install-postgres-10.sh
```
3) Enjoy Postgres 10. 🚢

**Comment by damianobarbati** [comment]
This is turning troublesome, I've not been using Travis for long and I've just migrated my customers to it but I wonder: 
- will this slow upgrading process happen also for 10.x versions? Or is it just for major versions?

**Comment by Majkl578** [comment]
@damianobarbati PostgreSQL changed versioning scheme so 10.x no longer means "major release with features", that would now be 11.0. See https://www.postgresql.org/about/news/1786/:
> This release also marks the change of the versioning scheme for PostgreSQL to a "x.y" format. This means the next minor release of PostgreSQL will be 10.1 and the next major release will be 11.

**Comment by manuelmeurer** [comment]
@Majkl578 I had to add this line to the end of your script to make it work:

```
sudo psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
```

Otherwise I would get errors like `FATAL: role "travis" does not exist`.

**Comment by Majkl578** [comment]
@manuelmeurer Right, or you can use `postgres` superuser directly (as we do). :)

**Comment by manuelmeurer** [comment]
@Majkl578 What do you mean? Can you elaborate? Thanks! 👍

**Comment by celsoMartins** [comment]
Using the fix by @manuelmeurer, the script provided by @Majkl578 works like a charm. Thanks.

**Comment by osteele** [comment]
I had success with @Majkl578's fix to @manuelmeurer's script.

My build was not previously sudo-enabled. I needed to add these lines to `.travis.yml`:

```yaml
dist: trusty  # necessary for postgres 10 workaround
sudo: required
```

Note: Switching from container-based virtualization does, [as documented](https://docs.travis-ci.com/user/reference/trusty/#Container-based-with-sudo%3A-false), increase build times even over the extra time just required to install PostgreSQL (which install can therefore not be cached).

**Comment by Majkl578** [comment]
> @Majkl578 What do you mean? Can you elaborate? Thanks! 👍

You don't need to add role to `travis` user, you can use `postgres` user directly in your tests. That's what i.e. [Doctrine does](https://github.com/doctrine/dbal/blob/master/tests/travis/pgsql.travis.xml#L15).

> Switching from container-based virtualization does, as documented, increase build times

The slowdown is not a significant issue - i.e. [Doctrine tests](https://travis-ci.org/doctrine/dbal/builds/335288120) are slown down only by ~20-30% maybe for PGSQL 10 stages.

Anyway, this issue is getting 4 months old and noone from Travis seems to even care or give ETA...

**Comment by roji** [comment]
Mid-February and still nothing... Having standard tools in such bad shape is a serious problem for a build platform...

**Comment by roji** [comment]
It's now almost 6 months since PostgreSQL 10 has been released, there are 60 votes on the issue and no mention of anything here. You guys need to at least communicate to the community and clarify when you expect this to be addressed - this isn't looking good.

**Comment by iquad** [comment]
@roji it is planned to deploy with 2.7 but there are still issues on 2.7 milestone, so we need to wait for them. Until that time, you can use a script to replace the related lines.

**Comment by roji** [comment]
@iqud thanks for that, any estimate on when 2.7 will be out? Is there any place where travis communicates on this kind of thing?

**Comment by Majkl578** [comment]
> it is planned to deploy with 2.7 but there are still issues on 2.7 milestone

What does this actually mean? What is "2.7"? There is no such milestone in this repo or in travis-cookboks repo. This issue is not milestoned either...
There is already PostgreSQL 10.3. PostgreSQL 11 is scheduled to Q3 2018 - that is 3-6 months away, less than it takes to even add PostgreSQL 10.

**Comment by AMDmi3** [comment]
Why is this tied to some milestone at all? In https://blog.travis-ci.com/2017-12-01-new-update-schedule-for-linux-build-images "frequent and regular updates (once a month)" were promised.

**Comment by iquad** [comment]
@Majkl578 @roji I'm so sorry, I tought it is the discussion on doctrine/dbal repository. You guys can skip what I told there, my bad.

**Comment by AMDmi3** [comment]
It seems it was finally fixed, at least I've got this from Travis docs and it works for me
```yaml
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
#      - postgresql-server-dev-10  # only if you rely on pg_config
env:
  global:
    - PGPORT=5433
...
script:
  - sudo -u postgres psql -c "..."  # note that `psql -U postgres` does not work
```

**Comment by Majkl578** [comment]
That is not a proper fix, you still need sudo-enabled build and install postgres manually.

Should look like this for 9.6:
```yml
    - stage: Test
      services:
        - postgresql
      addons:
        postgresql: "9.6"
```

**Comment by Dantemss** [comment]
While playing with @AMDmi3's configuration, I noticed the postgresql addon creates a travis superuser and a travis database. Incidentally, your scripts run as the travis user, so you can just give that user a password using psql peer auth:

```
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5433
before_script:
  - psql -c "ALTER USER travis WITH PASSWORD 'travis';"
```

Or you can probably connect directly with your app if the library you use supports peer auth.

Connect as username travis, password travis to database travis on port 5433 or use psql to create another DB.

**Comment by seanlinsley** [comment]
The above configs are setting `PGPORT` to 5433 but that seems to be the default. Additionally, `psql` seems to expect 5432. I tried setting `PGPORT` to 5432 but it didn't seem to make a difference.
```sh
$ pg_lsclusters 
Ver Cluster Port Status Owner    Data directory               Log file
9.2 main    5432 down   postgres /var/lib/postgresql/9.2/main /var/log/postgresql/postgresql-9.2-main.log
9.3 main    5432 down   postgres /var/lib/postgresql/9.3/main /var/log/postgresql/postgresql-9.3-main.log
9.4 main    5432 down   postgres /var/lib/postgresql/9.4/main /var/log/postgresql/postgresql-9.4-main.log
9.5 main    5432 down   postgres /var/lib/postgresql/9.5/main /var/log/postgresql/postgresql-9.5-main.log
9.6 main    5432 down   postgres /var/lib/postgresql/9.6/main /var/log/postgresql/postgresql-9.6-main.log
10  main    5433 online postgres /var/lib/postgresql/10/main  /var/log/postgresql/postgresql-10-main.log
$ psql
psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
$ psql -p 5432
psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
$ psql -p 5433
psql (10.3 (Ubuntu 10.3-1.pgdg14.04+1))
Type "help" for help.

travis=# \q
$ psql --version
psql (PostgreSQL) 10.3 (Ubuntu 10.3-1.pgdg14.04+1)
```

**Comment by roji** [comment]
Still nothing on this since October 2017, 71 likes... Appveyor just announced their Linux build - with PostgreSQL 10 and Ubuntu 18.04, maybe it's time to give it a try.

**Comment by seanlinsley** [comment]
I have no idea what's happening at Travis internally, but @Dantemss's configuration worked for me (though the `before_script` wasn't needed).

**Comment by samuelcolvin** [comment]
This is a complete joke. The same thing happened when postgres 9.6 was released #4264, similar situation for python 3.5 and 3.6 #4990.

The docs incredibly still [say](https://docs.travis-ci.com/user/database-setup/#Using-a-different-PostgreSQL-Version) the default postgres version is 9.1, which I think (hope!) is wrong.

Heorku manages to have new versions of popular software available the day they're released, travis take months or years.

It amazes me that travis continues to have the trust of the development community when they so abjectly fail on stuff like this.

**Comment by eritiro** [comment]
lol I received an email from travis. I thought they are shutting down their business, but no. they are launching new products :joy:

**Comment by merrill-oakland** [comment]
Still waiting...

**Comment by ttwd80** [comment]
seems fixed?
https://docs.travis-ci.com/user/database-setup/#PostgreSQL

**Comment by Majkl578** [comment]
Not really. The documented steps are only a hack/workaround. it's still not installed by default and unable to use standard port.

**Comment by ttwd80** [comment]
works for me.
https://github.com/ttwd80/november/blob/master/.travis.yml
it's still not installed by default  - correct. add on
unable to use standard port - correct. your program needs to use port 5433
but i think it is acceptable. it sort of forced me to rely on environment variables and it made my app comply with 12-factor apps.

**Comment by merrill-oakland** [comment]
That's still the round-about way. It is not included, you are apt-get installing it, which you could always do...

**Comment by davisokoth** [comment]
Really, Travis? Really?

**Comment by galdor** [comment]
Is there any news ? It is mind boggling that PostgreSQL 10 does not just work, 9 months after it has been released.

**Comment by Majkl578** [comment]
@BanzaiMan Can you please give us an official statement on this? Thanks!

**Comment by tnesztler** [comment]
I am able to use Postgres 10.4 on the standard port 5432 using the `xenial` distribution and `sudo`.
I need `sudo` to temporary fix an issue with Python 3.7 (#9815) so I do not know if it will work without it.

Here is my config relevant to Postgres:
```dist: xenial
language: python
python: 3.7
sudo: true
services:
  - postgresql
addons:
  postgresql: "10"
```

I am using the `travis` user without a password and the `travis` database.

**Comment by jherdman** [comment]
Did you have to work around config issues? I found we needed to also stop
the old PG running and restart the new one (along with moving conifg files
and modifying ports used)

**Comment by tnesztler** [comment]
No, not since I am using this configuration with Xenial.

**Comment by Dantemss** [comment]
Unless this changed recently, only trusty was available with `sudo: false` anyway, so you need sudo for xenial.

**Comment by jamonkko** [comment]
If `sudo: true` is ok for you, (then at the time this comment was written) combining the official instructions from [travis docs](https://docs.travis-ci.com/user/database-setup/#using-a-different-postgresql-version) and comments from @Majkl578 @mpugach above you can setup PG 10 with default port and working `postgres` user (same auth config as 9.6 uses):

```yaml
dist: trusty
sudo: true
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

before_script:
    # Use default port
    - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/10/main/postgresql.conf
    # Use 9.6 auth config:
    - sudo cp /etc/postgresql/{9.6,10}/main/pg_hba.conf
    - sudo service postgresql restart
```

The `xenial` config suggested by @tnesztler above might work also, but it does not seem to be officially supported by Travis (yes it is 2018 and latest dist is 14.02 trusty, I hope they get xenial out soon). It looks like a cleaner config but It did not work for us though, build failed half way with `No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.`. Might be because one of our build takes over 30 mins (I know too long!) and maybe there is some time limit on the _not documented_ xenial builds.

**Comment by roji** [comment]
FYI, while it's possible to set up newer versions of PostgreSQL as described above, various packages for Ubuntu trusty are no longer updated (e.g. postgresql-10-postgis-2.5 doesn't exist).

The degree to which things are becoming outdated on travis is honestly unacceptable, especially as this been raised and requested so many times. I'm personally going to drop Travis.

**Comment by SeinopSys** [comment]
My VPS literally upgraded to PostgreSQL 11 today when I ran `apt-get upgrade`, you'd think it's about time

**Comment by simlu** [comment]
@roji We've moved to circle now for a bunch of reasons. They're not perfect by any means, but I love how their workflows work and that you can use contexts. Full control over (multiple linked) containers is perfect and allows for clean separation. Not looking back.

**Comment by jwg2s** [comment]
Any official update here from Travis? @DrTorte I noticed you've been committing to this repo. Any word?

**Comment by BanzaiMan** [comment]
The upcoming Xenial image will have PostgreSQL 10. https://travis-ci.org/BanzaiMan/travis_production_test/builds/452082999#L465

**Comment by damianobarbati** [comment]
LOL, now that we have Postgres 11.

**Comment by teeparham** [comment]
I was able to get PG 10 + PostGIS 2.4 to work with these changes:

https://github.com/rgeo/activerecord-postgis-adapter/pull/295/commits/0ebfa7be750dc6b9969157020b499a125ee96cb5

Essentially:

```
addons:
  postgresql: 10
  apt:
    packages:
      - postgresql-10-postgis-2.4
      - postgresql-10-postgis-2.4-scripts
      - postgresql-client-10
env:
  global:
    - PGUSER=travis
    - PGHOST=""
    - PGPORT=5433
```

**Comment by BanzaiMan** [comment]
We'll track PostgreSQL 11.1 [here](https://travis-ci.community/t/postgresql-11-1/793) for Xenial.

If you need PostgreSQL 10, use Xenial, or workarounds indicated in this issue.

**Comment by Majkl578** [comment]
Xenial is not documented nor stable, that's not a solution...

**Comment by tdmalone** [comment]
> We'll track PostgreSQL 11.1 here for Xenial.
@BanzaiMan Why split issues across two places?

**Comment by BanzaiMan** [comment]
@tdmalone GitHub Issues will be disabled.

**Comment by sperrys** [comment]
What's the correct solution for postgres 10 on xenial? Trying the apt method with the custom port still fails for our build.

**Comment by gabfl-confiant** [comment]
@sperrys 
> What's the correct solution for postgres 10 on xenial? Trying the apt method with the custom port still fails for our build.

```yml
dist: xenial
addons:
  postgresql: "10"
```

If you want to install associated packages like `postgresql-server-dev-10`:

```yml
dist: xenial
addons:
  postgresql: "10"
before_install:
  - sudo apt-get update
  - sudo apt-get install --yes postgresql-server-dev-10
  - sudo /etc/init.d/postgresql restart
```

**Comment by gabfl** [comment]
@sperrys 
> What's the correct solution for postgres 10 on xenial? Trying the apt method with the custom port still fails for our build.

```yml
dist: xenial
addons:
  postgresql: "10"
```

If you want to install associated packages like `postgresql-server-dev-10`:

```yml
dist: xenial
addons:
  postgresql: "10"
before_install:
  - sudo apt-get update
  - sudo apt-get install --yes postgresql-server-dev-10
  - sudo /etc/init.d/postgresql restart
```

**Comment by sperrys** [comment]
I appreciate the reply. Unfortunately, the above configuration^ still fails for our build. Can you confirm if you are using a custom port like the docs suggest. Do you inlcude postgresql as a service as well? 

Here is the relevant travis config. 

```
- stage: server
      dist: xenial
      language: node_js
      node_js:
        - "8.12"
      env:
        global:
          - NODE_CONFIG_ENV=travis
          - PGUSER=postgres
          - PGPORT=5433
      addons:
        postgresql: "10"
      before_install:
        - sudo apt-get update
        - sudo apt-get install --yes postgresql-10
        - sudo apt-get install --yes postgresql-client-10
        - sudo /etc/init.d/postgresql restart
        - sleep 2
      install:
        - npm install
        - ls ./src
        - ls ./src/koh
        - npm install --prefix ./src/koh
        - npm install --prefix ./src/mobile
        - npm install --prefix ./src/server
      before_script:
        - psql -c 'create database test;' -U postgres
        - psql -d  test -c 'create extension if not exists citext;' -U postgres
        - cd ./src/server && npm run migrate up
      script:
        - npm run lint
        - cd ../..
        - npm run flow
        - cd src/server
        - npm run check-env
        - npm run test
```

Any further insight or advice is greatly appreciated.

**Comment by ryanhiebert** [comment]
@sperrys : Since it's no longer a hacky install, you don't need to override the `PGPORT` anymore.

**Comment by gabfl** [comment]
@ryanhiebert is correct, the port is 5432 (default) and you need to remove this section:

```yml
      before_install:
        - sudo apt-get update
        - sudo apt-get install --yes postgresql-10
        - sudo apt-get install --yes postgresql-client-10
        - sudo /etc/init.d/postgresql restart
        - sleep 2
```

**Comment by JoeWoodward** [comment]
I had some issues with the now supported pg v10 addon. Had to cp the old pg_hba.conf to PG 10 to get it to work
```yaml
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
before_install:
  - sudo cp /etc/postgresql/{9.6,10}/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
env:
  global:
    - PGPORT=5433
```
Without changing this the local connection authentication is set to peer where the old version is set to trust. This isn't mentioned in the travis docs anywhere unfortunately

**Comment by adrianhelvik** [comment]
I had issues with the v10 addon as well. Used @JoeWoodward's solution and it worked.

**Comment by michal-samluk** [comment]
@JoeWoodward Thank you! That worked for me as well.

**Comment by Destroy666x** [comment]
Anyone got 11.x to work on Xenial? Shame that popular db updates take so long in a partially paid CI solution

**Comment by narqo** [comment]
After a day of struggling, the following configuration works for me

```yaml
sudo: false
language: go
go:
  - 1.x

jobs:
  include:
    - stage: test
      dist: xenial
      addons:
        postgresql: 10
      before_script:
        - psql -c "create database testdb;" -U postgres
```
