### ISSUE TITLE
Android Build hang at 95% and Times out

### ISSUE THREAD

**Issue by naeems** [travis-ci/travis-ci#8538]
I have been facing this issue from last week. I managed to make it work by change distribution to "precise" and "sudo required". But from yesterday onward its stop building again and stops at 95%. It. Following is my .travis.yml file. Any suggestions or thoughts
```
language: android
dist: precise
sudo: required
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-21
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  timeout: 600
  directories:
    - "`pwd`/android-ndk-r10e"
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
env:
  - GRADLE_OPTS="-Dorg.gradle.parallel=true"
before_install:
   - ./tools/travis-setup.sh
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r10e
install:
  - sudo apt-get install --yes doxygen
script:
  - cd sdk && ./gradlew --stacktrace test build
```

**Comment by aaalaniz** [comment]
I am seeing similar issue with my builds. My builds hang downloading the gradle dependencies. Here is my .travis.yml

```
language: android
sudo: required
dist: precise

android:
  components:
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository,
    - extra-android-support
    - extra-google-gcm
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-intel-Hardware_Accelerated_Execution_Manager
    - extra-android-support
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'intel-android-extra-license-.+'
    - 'mips-android-sysimage-license-.+'

jdk:
  - oraclejdk8

before_script:
   #######################################
   #
   # Gradle
   #
   ######################################

   # Add gradle properties
   - touch $HOME/.gradle/gradle.properties
   # Disable gradle daemon
   - echo 'org.gradle.daemon=false' > $HOME/.gradle/gradle.properties
   # Ensure all dependencies are installed before building
   - ./gradlew dependencies || true

   #######################################
   #
   # Android SDK
   #
   ######################################
   - mkdir "$ANDROID_HOME/licenses" || true
   - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"

   #######################################
   #
   # Google Cloud SDK
   #
   ######################################
   - wget -q https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-167.0.0-linux-x86_64.tar.gz
   - tar xzf google-cloud-sdk-167.0.0-linux-x86_64.tar.gz
   - ./google-cloud-sdk/install.sh --usage-reporting=true --path-update=false --bash-completion=false --additional-components alpha beta gcloud gsutil
   - rm -rf google-cloud-sdk-167.0.0-linux-x86_64.tar.gz
   - ./google-cloud-sdk/bin/gcloud config set --installation component_manager/disable_update_check true

   #######################################
   #
   # Android NDK Setup
   #
   ######################################
   - pushd ~
   - wget -q https://dl.google.com/android/repository/android-ndk-r12b-linux-x86_64.zip
   - unzip -qo android-ndk-r12b-linux-x86_64.zip
   - export ANDROID_NDK_HOME="$HOME/android-ndk-r12b"
   - popd

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

script:
    - ./gradlew clean library:assemble library:testDebugUnitTest

```
