### ISSUE TITLE
com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: Failed to establish session

### ISSUE THREAD

**Issue by vanniktech** [travis-ci/travis-ci#8540]
I'm trying to run an Android Simulator with SDK >= 23 on Travis. However, I'm not able to get it up and running. Here are the [logs](https://travis-ci.org/vanniktech/RxPermission/builds/283722161?utm_source=github_status&utm_medium=notification). And this is my [YAML file](https://github.com/vanniktech/RxPermission/blob/8a04a7b9394f30c4c0b833f720ee253d2965120b/.travis.yml):

```yaml
language: android

android:
  components:
    # Update tools and then platform-tools explicitly so lint gets an updated database. Can be removed once 3.0 is out.
    - tools
    - platform-tools

jdk:
  - oraclejdk8

before_install:
  - pip install --user codecov
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  # Install the rest of tools (e.g., avdmanager)
  - sdkmanager tools
  # Install the system image
  - sdkmanager "system-images;android-25;google_apis;armeabi-v7a"
  # Create and start emulator for the script. Meant to race the install task.
  - echo no | avdmanager create avd --force -n test -k "system-images;android-25;google_apis;armeabi-v7a"
  - $ANDROID_HOME/emulator/emulator -avd test -no-skin -no-audio -no-window &

install: ./gradlew clean assemble assembleAndroidTest --stacktrace

before_script:
  - android-wait-for-emulator
  - adb shell input keyevent 82

script: ./gradlew check connectedCheck --stacktrace

after_success:
  - .buildscript/deploy_snapshot.sh
  - codecov

env:
  global:
    - secure: "Y84zGKgBbYtwOG9SLc5QOeKOaQO7QXmMO63Mc7chmKraW3FyRLJfMs8Qwq9+WQ2davpZI/yVyo0V0Ka7Jwx2163iQve1QskDhTrEHRLlAZDjqV+7S7y1O04ehPl3ix3fTuf3Dkwfxj1nKbpWpFAUTc8Isgltiev2b2ge5h03pbNIHxYDQvhExy+m+hc2ffme2w7jlFmnYMQQNNROo2X21B/7OYH8VY1ajVcMZ0Do9QPAeu1dPwwYBqMTtUal/8CoLSE8p8e0gW0KE4c+c8Y8qndmKyCYtlsgXMG/PMLV2uJy6zZ/57edxNWELwA92ChlXfK731W0kpSLk9n4n7XAkcYGa0+wX/45V8VsDYyFCV4WeNWKc3jgLaD/MYKE2R3KMSFaVvipcnmLr8fl+GEVNDI+TsW60df1rEVKui50L6nSLCYyJK3hTnMGE8mZidqOiGcNCDseWCoZBnUbpZcduW2FghdsZRUsemBWkJd3jeBmHaRxTaV1YyfGJqW5i3ECxbDn8l9QFt4gcWzzhp3/ER2xtccY6ZFCGg7c6lfv7OhVgL32ntaPzbmNJoHC+ejltj0ZN0649ByRxAEo2Nyf2GoM2QmeBuUdO1gnPzT5PVbjqE2Iq60lfWDVs65vZx/MMIgX/6bBMX97Ck5N5tAWLDYCK3d2ad5QcweXb5W/ANA="
    - secure: "XdQnTpfB1jUoN6ps6ENHzXhH7u7CcE1I244kyVlEJ9hF5KK0MiuOmO1fomAkfyRPaztXZsYHCfHCBGCA3S35kDrSVzlaDKRuNI796nZsI8pw/xMcf5czFXU210NReDexTTgi+LIs7ktjFHwrSp3GeBoXToSEuGgnU5As0/FLh47g4HsEKETqfxk66PHlvcrlez3qg3A/sZz5IzkDBd58b9eHuGVdtsQTtvWZV320Yv/M0WUByaGIYOAZQ4Rk7IMffbYwOFoPBlvLR0GcHBqKiSUmVn38dP98aMTChdUZ7jgyVfQnIYBB3ZCSX1QiExo7m90ZpyI6ElyL/AaEy4WhVgKKGxuzaLRxj1cQstikH/MvOnJLF+OaQeoDoqPWFPA3hBy10z5b3hsV5ZeiBRdal1J7KqZtZId7yaSKRXqEkjZhjzB2LvbTBFrMtCKP20pj4A/396mSvAxi6W7/SFLL7lzKjkWbakv20NI032s91B0dvNZQtGxFbqoP8gdBoXoTN3H6zR6rwQhVFywVAQ+Bqrvc4QMqOdygWGC03lNQ3WuEVqG2gPu2r9uHUZX/oYI0DsKH91c5KPYkP2cPRv+1Lnc7QnVT/ZItJTfjJy62uvh1DV0MxVtA/us0lIN7tbOgwTxyGvV9j5mUY/d8CMxhTpAagRsLwithrX/H2hqe19U="
    - ADB_INSTALL_TIMEOUT=8 # minutes (2 minutes by default)

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2
```

I've also tried different versions. None of which seemed to work.

- system-images;android-23;default;x86
- system-images;android-23;default;x86_64
- system-images;android-23;google_apis;x86_64
- system-images;android-24;default;x86
- system-images;android-24;default;x86_64
- system-images;android-25;google_apis;x86
- system-images;android-25;google_apis;x86_64
- system-images;android-25;google_apis;armeabi-v7a

Do you have any hints / assistance on this?
