### ISSUE TITLE
Deployment condition fails if $(command)

### ISSUE THREAD

**Issue by bfred-it** [travis-ci/travis-ci#8549]
# Failing condition

```
condition: $(npm run can-release --silent)
```

As per the [docs](https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A), `condition` is run inside `if [[ <condition> ]]; then <deploy>; fi`

And my condition works correctly in that position in a shellscript:

```sh
#! /bin/bash
if [[ $(npm run can-release --silent) ]]; then
echo yep
else
echo nope
fi
```

# Log

https://travis-ci.org/sindresorhus/refined-github/builds/285089101#L2412

```
sh: 1: [[: not found
sh: 1: [[: not found
sh: 1: [[: not found
sh: 1: [[: not found
```

# Configuration

https://github.com/sindresorhus/refined-github/blob/57ebfc0f769df5d2b572df6262d3ee7e8044d8d6/.travis.yml

```yml
deploy:
  provider: script
  skip_cleanup: true
  script: npm run release
  on:
    branch: master
    condition: $(npm run can-release --silent)
```
