### ISSUE TITLE
Passing builds are failing now

### ISSUE THREAD

**Issue by AmitBarjatya** [travis-ci/travis-ci#8579]
I'm trying my hands on travis CI for an android project. But I'am not able to figure out what is causing my builds to fail. Travis complains that it couldn't access package manager but the builds were passing with the same config few hours back. Can someone help?

Here:
https://travis-ci.org/AmitBarjatya/RealmMvp

Here is the .travis.yml file:
```
language: android
jdk: oraclejdk8
sudo: required
env:
  matrix:
    - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.2
    - $ANDROID_TARGET
    - android-26
    - sys-img-armeabi-v7a-$ANDROID_TARGET
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - chmod +x gradlew
  - ./gradlew dependencies || true
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

script: ./gradlew connectedAndroidTest
```
