### ISSUE TITLE
[Jobs]: Python 3.6 with pypy3 broken

### ISSUE THREAD

**Issue by sdruskat** [travis-ci/travis-ci#8603]
I've come across what looks like a bug in Travis' activation of a Python 3 virtualenv with pip3.

## `.travis.yml`

```yaml
branches:
  only:
  - src

matrix:
  include:
    - language: ruby
      rvm:
        - 2.3.1
      install:
        - bundle install
      script:
        - bundle exec jekyll build

    - language: python
      python: 
        - "3.6"
        - "pypy3"
      install:
        - pip install pypandoc
        - pip install frontmatter
        - sudo apt-get install pandoc
      script:
        - build-pdfs.py
    
    - language: ruby
      rvm:
        - 2.3.1
      install:
        - bundle install
      script:
        - bundle exec rake site:deploy --quiet

exclude: [vendor]

sudo: false
```

## Log

````
Worker information
hostname: d0589b5f-7b64-48d5-ab7a-3f06ce54c598@1.production-4-worker-org-b-2-gce
version: v3.1.0 https://github.com/travis-ci/worker/tree/5b106cb773802277034d07b0a865af58d67bb1d2
instance: testing-gce-57288d09-d235-475d-9139-dc52918657a3:travis-ci-garnet-trusty-1503972833 (via amqp)
startup: 21.260629422s
/home/travis/.travis/job_stages: line 418: syntax error in conditional expression
/home/travis/.travis/job_stages: line 418: syntax error near `"pypy3"]/bin/activate'
/home/travis/.travis/job_stages: line 418: `if [[ ! -f ~/virtualenv/python["3.6", "pypy3"]/bin/activate ]]; then'
travis_run_configure: command not found
travis_run_checkout: command not found
travis_run_prepare: command not found
travis_run_disable_sudo: command not found
travis_run_export: command not found
travis_run_setup: command not found
travis_run_setup_casher: command not found
travis_run_setup_cache: command not found
travis_run_announce: command not found
travis_run_debug: command not found
travis_run_before_install: command not found
travis_run_install: command not found
travis_run_before_script: command not found
travis_run_script: command not found
travis_run_before_cache: command not found
travis_run_cache: command not found
travis_run_after_success: command not found
travis_run_after_failure: command not found
travis_run_after_script: command not found
travis_run_finish: command not found
Done. Your build exited with .
````

**Comment by BanzaiMan** [comment]
You can't have an array for the `python` value inside `matrix.include`. There is no matrix expansion at that level.

You need:

```yaml
matrix:
  include:
    - language: ruby
      rvm:
        - 2.3.1
      install:
        - bundle install
      script:
        - bundle exec jekyll build

    - language: python
      python: "3.6"
      install:
        - pip install pypandoc
        - pip install frontmatter
        - sudo apt-get install pandoc
      script:
        - build-pdfs.py
    
    - language: python
      python: "pypy3"
      install:
        - pip install pypandoc
        - pip install frontmatter
        - sudo apt-get install pandoc
      script:
        - build-pdfs.py
    
    - language: ruby
      rvm:
        - 2.3.1
      install:
        - bundle install
      script:
        - bundle exec rake site:deploy --quiet
```

**Comment by BanzaiMan** [comment]
Alternatively, you should move the python jobs to the top level:

```yaml
language: python
python: "pypy3"
install:
  - pip install pypandoc
  - pip install frontmatter
  - sudo apt-get install pandoc
script:
  - build-pdfs.py

matrix:
  include:
    - language: ruby
      rvm:
        - 2.3.1
      install:
        - bundle install
      script:
        - bundle exec jekyll build
    - language: ruby
      rvm:
        - 2.3.1
      install:
        - bundle install
      script:
        - bundle exec rake site:deploy --quiet
```
