### ISSUE TITLE
Overwritting/Deleting existing pre-release on GitHub with Travis

### ISSUE THREAD

**Issue by oliexdev** [travis-ci/travis-ci#8622]
Is it possible to overwrite or delete existing GitHub releases?
My goal is that only **one** dev build generated by Travis is always shown as a pre-release on GitHub.  But on every automatically build (commit) by Travis a new pre-release entry on GitHub is generated.

Currently my `.travis.yml` looks like

```
language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-24
    - extra-android-m2repository

deploy:
  provider: releases
  api-key: $GITHUB_API_KEY
  file: $HOME/openScale-dev-build.apk
  skip_cleanup: true
  name: "openScale dev build"
  body: "Automatically openScale dev build by Travis CI"
  prerelease: true
  overwrite: true

after_success:
 - chmod +x ./upload_apk.sh
 - ./upload_apk.sh

script: cd android_app && ./gradlew assembleDebug
```

**Comment by kmactavish** [comment]
I'm trying to do pretty much the same thing. I want to have a release that follows the latest commit in the master branch. I would imagine it something like this: if the release exists, and overwrite is true, then travis would use octokit's update_release/update_release_asset [documented here](https://octokit.github.io/octokit.rb/Octokit/Client/Releases.html#update_release-instance_method).
```
deploy:
  provider: releases
  name: master-latest
  overwrite: true
  tag_name: master-latest
  prerelease: true
  file: releasefile.txt
  skip_cleanup: true
  on:
    repo: me/myrepo
    branch: master
  api_key: $GITHUB_API_KEY
```
