### ISSUE TITLE
Python 3.6-dev can't be downloaded (misformatted S3 URL) using multi-stage builds

### ISSUE THREAD

**Issue by purohit** [travis-ci/travis-ci#8627]
I'm using the multistage beta feature, and ran into an issue where if I specify Python's version in a job as 3.6-dev, the build fails because it uses brackets in the name. Example relevant parts of config file:

```
 jobs:
     include:
         - stage: test
           language: python
           services:
               - postgresql
           python:
               - "3.6-dev"
```

Resulting build failure, because it's using brackets for some reason:

```
[3.6-dev] is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-[3.6-dev].tar.bz2
The command "curl -s -o python-["3.6-dev"].tar.bz2 ${archive_url}" failed and exited with 3 during .
Your build has been stopped.
```
