### ISSUE TITLE
(Random error: ) The module was compiled against a different Node.js version

### ISSUE THREAD

**Issue by hovancik** [travis-ci/travis-ci#8629]
Hi there, I have an [electron project](https://github.com/hovancik/stretchly) which uses node module with need to be recompiled. 

When I run tests, they randomly exit with error: 

```
 Uncaught Error: The module '/Users/travis/build/hovancik/stretchly/app/node_modules/@paulcbetts/system-idle-time/build/Release/system_idle_time.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 54. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
 at require (internal/module.js:20:19)
 at bindings (app/node_modules/bindings/bindings.js:76:44)
 at Object.<anonymous> (app/node_modules/@paulcbetts/system-idle-time/addon.js:1:99)
 at Object.Module._extensions.(anonymous function) [as .js] (/Users/travis/.nvm/versions/node/v7.9.0/lib/node_modules/istanbul/lib/hook.js:109:37)
 at require (internal/module.js:20:19)
 at NaturalBreaksManager.get idleTime [as idleTime] (app/utils/naturalBreaksManager.js:9:1393)
 at Timeout.timer.setInterval [as _onTimeout] (app/utils/naturalBreaksManager.js:9:1780)
 at _combinedTickCallback (internal/process/next_tick.js:77:11)
 at Immediate._tickDomainCallback (internal/process/next_tick.js:128:9)
```

I do not see any pattern (happens both mac and linux, 32 and 64), it seems to be random and I would say maybe more then 50% of time. All I need to do to have green status is to rerun the test until it's green. 

Right now I am on node 7.9.0, my `.travis.yml` is: 

```
language: node_js

os:
  - linux
  - osx

node_js: "7.9.0"


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update && sudo apt-get install -q libxss-dev; fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start && sleep 3; fi

script:
  - npm install -g istanbul
  - istanbul cover ./node_modules/mocha/bin/_mocha

notifications:
  email:
    on_success: never

on_failure: change

after_success:
  - bash <(curl -s https://codecov.io/bash)
```
