### ISSUE TITLE
Build failing with An error occurred while generating the build script.

### ISSUE THREAD

**Issue by e-e-e** [travis-ci/travis-ci#8675]
My build is failing with `An error occurred while generating the build script.`
https://travis-ci.org/loanmarket/react-router-redux-multi/builds/295185164

The config is super simple.
```yml
language: node_js
node_js:
- '6'
script: npm run test
```
and was passing moments before. The only change in the repo was to my `readme.md`.
