### ISSUE TITLE
ruby-1.9.3-p362 is not installed

### ISSUE THREAD

**Issue by ai** [travis-ci/travis-ci#868]
I have common [Ruby project](https://github.com/ai/plain_record) with `.travis.yml`:

``` yml
language: ruby
bundler_args: --without development
rvm:
  - 1.8.7
  - ruby-1.9.3
  - jruby-18mode
  - rbx-18mode
  - rbx-19mode
```

But, when I push new commits today I [get](https://travis-ci.org/ai/plain_record/builds/4283375) error in `ruby-1.9.3` build:

```
Using worker: ruby3.worker.travis-ci.org:ruby-5
2
3$ cd ~/builds
4$ git clone --branch=master --depth=100 --quiet git://github.com/ai/plain_record.git ai/plain_record
5$ cd ai/plain_record
6$ git checkout -qf c2c764a87625b916c0d30ec7f44f3b8d76acbd0b
7$ rvm use ruby-1.9.3
8ruby-1.9.3-p362 is not installed.
9To install do: 'rvm install ruby-1.9.3-p362'
10
11Done. Build script exited with: 1
```
