### ISSUE TITLE
jdk_switcher: command not found on Trusty

### ISSUE THREAD

**Issue by surli** [travis-ci/travis-ci#8681]
Hi,

I'm trying to use `jdk_switcher` in a bash script but I get a command not found: see https://travis-ci.org/INRIA/spoon/jobs/295354425#L2499

I'm using it in the following script:
```bash
#!/bin/bash

jdk_switcher use oraclejdk9
mvn -Djava.src.version=1.9 test
```

Is there a specific path to use jdk_switcher? 

Here's the complete .travis.yml:

```yml
language: java

sudo: required
dist: trusty

group: edge

env:
  - SCRIPT=travis-jdk9.sh
  - SCRIPT=travis-jdk8.sh
  - SCRIPT=travis-coverage.sh
  - SCRIPT=travis-verify.sh

script: ./chore/travis/$SCRIPT

cache:
  directories:
  - $HOME/.m2

before_cache:
- rm -rf $HOME/.m2/fr/inria/ # delete all to be sure we always get last snapshot of spoon
```
