### ISSUE TITLE
Scala sbt project hangs indefinitely during tests.

### ISSUE THREAD

**Issue by tmccombs** [travis-ci/travis-ci#8682]
In my xtract project (https://github.com/lucidsoftware/xtract) the travis-ci build consistently hangs and eventually times out, usually while the tests are running, but sometimes during compilation. 

This doesn't happen if I run sbt locally, or even if I run it a the travisci-ci-garnet docker container. When I run the test myself they take seconds.

I have tried several things to try and fix this including:

- trying sudo both false and true
- different versions of sbt
- splitting and combining the compile and test sbt commands
- with and without forking enabled for tests
- using both opnejdk8 and oraclejdk8

The build worked 4 months ago, but started breaking consistently, after I made a small change in september. 

My most recent .travis.yml file:

```yaml
language: scala

scala:
  - 2.11.11
  - 2.12.3

jdk:
  - openjdk8

dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/

after_success:
  - sbt ++$TRAVIS_SCALA_VERSION package
  - |
    if [ -n "$TRAVIS_TAG" ] || ([ "$TRAVIS_PULL_REQUEST" == false ] && [ "$TRAVIS_BRANCH" == master ])
    then
      mkdir ~/.pgp
      echo $PGP_PUBLIC | base64 --decode > ~/.pgp/pubring
      echo $PGP_SECRET | base64 --decode > ~/.pgp/secring
      echo "Publishing snapshot"
      sbt ++$TRAVIS_SCALA_VERSION xtract/publishSigned xtractTesting/publishSigned
    fi
deploy:
  api_key: $GITHUB_AUTH
  file:
    - xtract-core/target/**/*.jar
    - testing/target/**/*.jar
  file_glob: true
  provider: releases
  skip_cleanup: true
  on:
    tags: true

script:
  - sbt ++$TRAVIS_SCALA_VERSION compile
  - travis_wait sbt -debug ++$TRAVIS_SCALA_VERSION test

install: sbt ++$TRAVIS_SCALA_VERSION update
before_cache:
  #Avoid unncessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock" -print -delete
```
