### ISSUE TITLE
View Config doesn't display Deploy options

### ISSUE THREAD

**Issue by tarunlalwani** [travis-ci/travis-ci#8708]
I have a simple `.travis.yml`

```yaml
udo: required # is required to use docker service in travis

language: python

before_install: true
install: true
before_script: true
script: true
 
deploy:
  provider: script
  script: echo "Tarun lalwani"
  skip_cleanup: true
```

But the View Config shows

```json
{
  "sudo": "required",
  "language": "python",
  "before_install": true,
  "install": true,
  "before_script": true,
  "script": true,
  "group": "stable",
  "dist": "trusty",
  "os": "linux"
}
```

Below is the link to the build

https://travis-ci.org/tarunlalwani/test-travis/jobs/297508339/config

Why is config missing the deploy in JSON? Though the deployment script is still executed
