### ISSUE TITLE
Conditional builds issue.

### ISSUE THREAD

**Issue by isuruf** [travis-ci/travis-ci#8721]
We have the following in our travis.yml
```
jobs:
  include:
    - if: (fork IN (true)) OR (type IN (pull_request))
      os: osx
      osx_image: xcode6.4

    - if: (fork IN (false)) AND (NOT (type IN (pull_request)))
      os: linux
      sudo: false
```

If the repo is not a fork, the osx build is run for PRs and the linux build for branches.
When the repo is a fork, the linux build is run, but we want the osx build to run.
Any idea why this is happening?

cc @jakirkham

https://github.com/conda-forge/staged-recipes/blob/master/.travis.yml
