### ISSUE TITLE
redundant comma is added to environment variables

### ISSUE THREAD

**Issue by newser** [travis-ci/travis-ci#8722]
I found travis added a redundant comma to environment variables. 

My travis.yml:
```
matrix:
    include:
        - language: c
          os: linux
          dist: trusty
          env:
              global:
                  - JOB='Linux'
                  - GENERATOR='Unix Makefiles'
                  - CMAKE_FLAGS='-DPLATFORM_BUILD_SHARED=TRUE -DPLATFORM_ENABLE_DEBUG=FALSE'
...
```

During building, a "," is added to the variable GENERATOR:
```
$ export GENERATOR='Unix Makefiles'", "
$ export CMAKE_FLAGS='-DPLATFORM_BUILD_SHARED=TRUE -DPLATFORM_ENABLE_DEBUG=FALSE'", "
```
Note the ending "," is not as expected, and thus building failed as CMake does not accept the variable GENERATOR:
```
$ cmake -G "${GENERATOR}" ${CMAKE_FLAGS} ..
CMake Error: Could not create named generator Unix Makefiles, 
```

My yml:
https://github.com/newser/TitanSDK/blob/master/.travis.yml
Build log:
https://travis-ci.org/newser/TitanSDK/jobs/298945763

**NOTE**
This issue does not exist two month ago, the build succeeded with same .travis.yml, see my last successful build log:
https://travis-ci.org/newser/TitanSDK/jobs/274074333

**Comment by BanzaiMan** [comment]
There are a couple of things at play.

The first is your use of `env.global` in each of the `matrix.include` jobs. `env.global` is meant for environment variables that are *_shared_* by _*all*_ the jobs in the matrix.

Here, your definition of `env.global` inside `matrix.include` ends up being a Ruby array (which is implementation details, but significant) and processed as `["JOB='linux'", "GENERATOR='Unix makefiles'", "…`.

The second is the recent change in how we process this information into `export` statements; with this change, you end up with:

    global=["JOB='Linux'"

instead.

So, how can you solve this?

Try:
```yaml
matrix:
include:
    - language: c
      os: linux
      dist: trusty
      env: JOB='Linux' GENERATOR='Unix Makefiles' CMAKE_FLAGS='-DPLATFORM_BUILD_SHARED=TRUE -DPLATFORM_ENABLE_DEBUG=FALSE'
```
