### ISSUE TITLE
Multiple Deployments Broken

### ISSUE THREAD

**Issue by HaoZeke** [travis-ci/travis-ci#8738]
According to the docs, this should work

```yaml
deploy:
  - provider: cloudcontrol
    email: "YOUR CLOUDCONTROL EMAIL"
    password: "YOUR CLOUDCONTROL PASSWORD"
    deployment: "APP_NAME/DEP_NAME"
  - provider: heroku
    api_key: "YOUR HEROKU API KEY"
```

However actually when I lint this file, I get 

```bash
Warnings for .travis.yml:
[x] in deploy section: has multiple provider entries, keeping last entry
```

Naturally I tried 2 deploy segments,

```yaml
deploy:
  - provider: cloudcontrol
    email: "YOUR CLOUDCONTROL EMAIL"
    password: "YOUR CLOUDCONTROL PASSWORD"
    deployment: "APP_NAME/DEP_NAME"

deploy:
  - provider: heroku
    api_key: "YOUR HEROKU API KEY"
```

Which again brought me to the expected

```bash
Warnings for .travis.yml:
[x] has multiple deploy entries, keeping last entry
```

Any suggestions?

**Comment by BanzaiMan** [comment]
The linter is unfortunately out of date. The documentation is correct and the first one should work. Do you have a build log to suggest that it does not?

**Comment by HaoZeke** [comment]
I have since moved to using an after_success rule..

The builds simply ignore the first provider segment, doesn't even show up in the logs...

**Comment by BanzaiMan** [comment]
If you are using the second form, that's because you are defining two `deploy`s, and the second overrides the first. That's how YAML works.

If you are not interested in getting this resolved with the first form, please close this.

**Comment by HaoZeke** [comment]
This was my config file:

```yaml
deploy:
  provider: pages
  local_dir: ./docs
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  provider: surge
  project: ./docs/
  domain: zenyoda.surge.sh
```

And the relevant job log portion:

```
The command "tup" exited with 0.
dpl.0
6.41sSuccessfully installed dpl-1.8.43
1 gem installed
4.32s
dpl.1
Installing deploy dependencies
dpl.2
Preparing deploy
dpl.3
Deploying application
    Surge - surge.sh
              email: [secure]
              token: *****************
       project path: /home/travis/build/HaoZeke/zenYoda/docs
               size: 22 files, 198.1 KB
             domain: zenyoda.surge.sh
               plan: Free
              users: [secure]
         IP Address: 45.55.110.124
    Success! Project is published and running at zenyoda.surge.sh
Done. Your build exited with 0.
```

**Comment by BanzaiMan** [comment]
Same problem. You have multiple occurrences of `deploy.provider`, and only the last one is effective.

Try

```yaml
deploy:
  - provider: pages
    local_dir: ./docs
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
      branch: master
  - provider: surge
    project: ./docs/
    domain: zenyoda.surge.sh
```
