### ISSUE TITLE
Suddenly getting  Local gulp not found while doing npm publish

### ISSUE THREAD

**Issue by amir20** [travis-ci/travis-ci#8760]
I am creating an issue in hopes that someone else may find this helpful as I have still not found a solution to it. 

I have a `package.json` file that has the following 

```
"scripts": {
    "lint": "eslint . && flow check",
    "test": "npm run lint && jest",
    "pretest": "gulp build:test",
    "prepublishOnly": "gulp build"
  }
```

I have `npm publish` on tags using `.travis.yml`. My file looks like:

```
sudo: false
language: node_js
node_js:
- stable
- '9'
- '8'
- '7'
cache:
  directories:
    - "node_modules"
deploy:
  provider: npm
  email: findamir@gmail.com
  api_key:
    secure: **********
  on:
    tags: true
    repo: amir20/phantomjs-node
before_script:
  - npm install -g gulp-cli
before_install:
- npm install -g codecov
after_success:
- codecov
```

Starting recentely, I am getting an error when I tag and push. Example failed job is [here](https://travis-ci.org/amir20/phantomjs-node/jobs/301791681). 

The error is:

```
NPM version: 5.5.1
Authenticated with email findamir@gmail.com
Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`. See https://docs.travis-ci.com/user/deployment/#Uploading-Files.
Saved working directory and index state WIP on (no branch): 144397a 4.0.7
dpl.3
Deploying application
NPM API key format changed recently. If your deployment fails, check your API key in ~/.npmrc.
http://docs.travis-ci.com/user/deployment/npm/
~/.npmrc size: 48
> phantom@4.0.7 prepublishOnly .
> gulp build
[15:47:45] Local gulp not found in ~/build/amir20/phantomjs-node
[15:47:45] Try running: npm install gulp
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantom@4.0.7 prepublishOnly: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantom@4.0.7 prepublishOnly script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2017-11-14T15_47_45_655Z-debug.log
``` 

I have followed the documentation and made sure that `npm install -g gulp-cli` works. If you look at the log then it does install it. However, I still get this error. It seems like during publishing, it is uses a different path where `gulp` is not found. 

Any body have this issue?
