### ISSUE TITLE
apt-get install dotnet-sdk-2.0.3 failing

### ISSUE THREAD

**Issue by Shockolate** [travis-ci/travis-ci#8778]
cc @joshua-anderson @akoeplinger @nterry

[Build](https://travis-ci.org/Shockolate/Liquor-Cabinet/builds/303231088)
```
E: Unable to locate package dotnet-sdk-2.0.3
E: Couldn't find any package by glob 'dotnet-sdk-2.0.3'
E: Couldn't find any package by regex 'dotnet-sdk-2.0.3'

The command "sudo apt-get install -qq dotnet-sdk-2.0.3" failed and exited with 100 during .
```
config:
```yaml
language: csharp
mono: none
dotnet: 2.0.3
dist: trusty
```

Hopefully this is a dup of #8774 . Since it's a different step, I created this issue.
