### ISSUE TITLE
Support arrays/lists in build matrix

### ISSUE THREAD

**Issue by KOLANICH** [travis-ci/travis-ci#8783]
```yaml
matrix:
  include:
    - os: linux
      python:
        - 3.4
        - 3.5
        - 3.6
        - 3.7
        - nightly
        - pypy3
        - pypy3-nightly
    - os: osx
      python:
        - nightly
        - pypy3
        - pypy3-nightly
```

for every matrix instance there is no expansion of ```python``` key, the build system instead joins the lists into strings and uses the resulting string as a value of ```python```.
