### ISSUE TITLE
Build fails when test command exits with 2, but tests are passing.

### ISSUE THREAD

**Issue by mrbernnz** [travis-ci/travis-ci#8784]
## Expected Behavior
That test should pass and build should exit with 0

## Context
I would really like my environments to match up.  I have followed the steps to test the container locally. Builds were passing.

## Screenshot
![screen shot 2017-11-21 at 06 57 46](https://user-images.githubusercontent.com/9615028/33071417-5fbfd100-ce89-11e7-87f0-f5cdfe3b6e1a.png)

## Config
```Yaml
language: ruby
bundler_args: --without production
cache: bundler
services:
  - postgresql
env:
  global:
  - DB=postgresql
  - CC_TEST_REPORTER_ID=8938d99c071bc6c279e944a21950a32434dd769b3c24e667fe137746f910730c
before_script:
  # - psql -c 'create database dailydozen_api_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake test
after_script:
  if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
```

## Gemfile
```
source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

ruby '2.4.2'

gem 'rails', '~> 5.1.4'
gem 'pg', '~> 0.18'
gem 'puma', '~> 3.7'
gem 'bcrypt', '~> 3.1.7'
gem 'rack-cors'
# gem 'jbuilder', '~> 2.5'
# gem 'redis', '~> 3.0'
# gem 'capistrano-rails', group: :development

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'faker', '~> 1.8', '>= 1.8.4'
  gem 'minitest-reporters', '~> 1.1', '>= 1.1.18'
  gem 'factory_bot_rails', '~> 4.8', '>= 4.8.2'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring', '~> 2.0', '>= 2.0.2'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'pry-rails', '~> 0.3.6'
  gem 'guard', '~> 2.14', '>= 2.14.1'
  gem 'guard-rails', require: false
  gem 'guard-minitest', '~> 2.4', '>= 2.4.6'
end

gem 'simplecov', :require => false, :group => :test

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'graphql', '~> 1.7', '>= 1.7.4'
```

## Your Environment
* Version used:  Ubuntu Trusty 14.04
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):  Rails 5.1.4 on ruby 2.4.2
* Operating System and version: MacOS Sierra 10.12.6
* Link to your project:  https://github.com/mrbernnz/dailyDozenAPI
