### ISSUE TITLE
Invalid `deploy:` configuration is crashing travis-build

### ISSUE THREAD

**Issue by cotsog** [travis-ci/travis-ci#8786]
Here's the configuration:

```yaml
deploy:
  provider: script
  script: echo "Foo"
  on:
    - master
    - dev
    - test
```

Full .travis.yml file is here => https://github.com/cotsog/travis_ci_prod_regular/blob/43af30d5d74e2c34a844abd1f37151ff8bb4e39d/.travis.yml

And resulting build => https://travis-ci.org/cotsog/travis_ci_prod_regular/builds/305455209

Here's the output:

```
There was an error in the .travis.yml file from which we could not recover.
Unfortunately, we do not know much about this error.
Please review https://docs.travis-ci.com, or contact us at support@travis-ci.com with the error ID: 5fc22722fc064b14b6f70dc2e28e13a2
```
