### ISSUE TITLE
tox not running pyhton test on OSX image

### ISSUE THREAD

**Issue by moscoquera** [travis-ci/travis-ci#8802]
hi there :)
a month ago  the OSX tests of my fork were running correctly, but if i run the same commit now, Tox is not working anymore and no output is show, so i don't know what else look to find why this isn't running anymore.

note: the tests runs as usual on linux.

this is the .travis file:
```
language: python
sudo: false
cache: pip

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

env: 

matrix:
  fast_finish: true
  allow_failures:
    - python: "nightly"
  include:
    - os: osx
      language: generic
      python: "3.6"
      install:
        - brew update
        - brew install python3
        - python3 -m venv venv
        - source venv/bin/activate
        - pip3 install tox-travis filelock codecov coverage
      script:
        - tox
  
install:
  - pip install tox-travis filelock codecov coverage

script:
  - tox

after_success: codecov
```

this is tox.ini
```
[tox]
envlist=py27,py36
toxworkdir=/tmp/tox

[testenv]
setenv = TOX_ENV_NAME={envname}
sitepackages = True
commands = py.test tests --cov=pyupdater

deps =
    pytest
    pytest-datadir==0.2.0
    pytest-cov
    pytest-xdist
    pytest-remove-stale-bytecode
    tox-pyenv
    codecov>=1.4.0
    filelock
    -rrequirements.txt
    --upgrade
```

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by BanzaiMan** [comment]
This might be a variation of #8829; if you are using `language: generic` on the Mac to run Python builds, you are responsible for providing necessary commands.

**Comment by moscoquera** [comment]
hi @BanzaiMan.
my bad, i sorted it this weekend and forgot this issue.
actually, the problem was the lack of env declarations on the .travis.yml file, this's how matrix looks now:

```
matrix:
  fast_finish: true
  allow_failures:
    - python: "nightly"
  include:
  - os: osx
    language: generic
    python: "3.6"
    env: "TOXENV=py36"
    install:
      - brew update
      - brew install python3
      - python3 -m venv venv
      - source venv/bin/activate
      - pip3 install tox-travis filelock codecov coverage
    script: tox
  - os: osx
    language: generic
    python: "2.7"
    env: "TOXENV=py27"
    install:
      - pip install tox-travis filelock codecov coverage
    script: tox 
```
