### ISSUE TITLE
Best way to install dotnet with additional runtimes?

### ISSUE THREAD

**Issue by AnthonyLloyd** [travis-ci/travis-ci#8815]
@joshua-anderson @akoeplinger @nterry

e.g. I want to install the 2.0.3 SDK plus the 1.1.5 runtime.

Here is my current solution which does work:

https://github.com/haf/expecto/blob/master/.travis.yml

**Comment by akoeplinger** [comment]
You can use this instead to install 2.0.3 SDK + 1.1.5 runtime + 2.0.0 runtime:

```yaml
language: csharp
os: linux
dist: trusty
sudo: false
dotnet: 2.0.3
mono: none

addons:
  apt:
    packages:
    - dotnet-dev-1.1.5
    - dotnet-runtime-2.0.0

script:
  - dotnet --info
```
