### ISSUE TITLE
Feature request: concurrent stages

### ISSUE THREAD

**Issue by Pr0methean** [travis-ci/travis-ci#8817]
In https://github.com/Pr0methean/BetterRandom/blob/master/.travis.yml I have four kinds of jobs: Linux unit tests, OSX unit tests, Linux long tests and OSX long tests. What I'd like to do is start the OSX unit tests *and* the Linux long tests once the Linux unit tests pass, and the OSX long tests once the OSX unit tests pass, but allow the OSX long tests to run concurrently with the Linux long tests. Is it possible to specify a dependency graph that isn't a single path, for this purpose?
```
          Linux unit tests
                 |
     ____________|____________
    |                         |
    V                         V
OSX unit tests        Linux long tests
      |                       :
      V                       :
OSX long tests                :
      :                       :
```

**Comment by 1138-4EB** [comment]
Same question here: https://github.com/travis-ci/beta-features/issues/28#issuecomment-348851212

**Comment by Pr0methean** [comment]
This is still relevant.

**Comment by mansona** [comment]
I would still quite like this to be open 🎉

**Comment by amleszk** [comment]
+1 for this feature please 🙏 

Our use case is we have a 2nd stage which runs unit tests, and a 3rd stage that runs UI tests. Both of these can be run in parallel, but currently not possible using travis. 
I know a workaround is to make these be in the same stage, but we do not want that because of other conditions of the build require these 2 stages to be separate. See example `.travis.yml`

```
stages:

  - stage1
  - stage2

# stage 3 and 4 only run after PR merge or if commit message contains 'uitest'
# https://github.com/travis-ci/travis-conditions
  - name: stage3
    if: type != pull_request OR commit_message =~ uitest
  - name: stage4
    if: type != pull_request OR commit_message =~ uitest
```

![image](https://user-images.githubusercontent.com/501631/49703344-e267f300-fbd1-11e8-8f9a-bbd329f9531a.png)
