### ISSUE TITLE
doubts about building on mac

### ISSUE THREAD

**Issue by Yordrar** [travis-ci/travis-ci#8830]
So I'm trying to build a nodejs app that uses electron (I use electron-builder to build the final executable) and I couldn¡t get it to work, how can I do it? This is my travis.yml file:

```
matrix:
include:
  - os: osx
    osx_image: xcode9.0
    language: node_js
    node_js: "8"
    env:
      - ELECTRON_CACHE=$HOME/.cache/electron
      - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

  - os: linux
    language: node_js

install: npm install
script: npm run build

notifications: 
  email: false
```
I will also appreciate any kind of tip or advise when building with travis, I'm a bit noob using it and the docs are quite confusing for me.
Thanks.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by Yordrar** [comment]
Unfortunately, no. The build on Mac just doesnt start whereas the build on Linux works perfectly. I have literally no clue on whats going on

**Comment by BanzaiMan** [comment]
I see. If the configuration is verbatim what you gave above, then you are not defining jobs in the build correctly, so there is only one job.

You probably mean:
```yaml
matrix:
  include:
    - os: osx
      osx_image: xcode9.0
      language: node_js
      node_js: "8"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      language: node_js
```

Note the indentation. And please review https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix.

Thanks.
