### ISSUE TITLE
Regression: Chrome fails to start due to incorrect default chrome-sandbox permissions

### ISSUE THREAD

**Issue by pimterry** [travis-ci/travis-ci#8836]
See https://travis-ci.org/pimterry/mockttp/jobs/309509522 for an example.

Chrome fails to start in my tests, using the Chrome addon and running XVFB, with:

```
Cannot start Chrome
[4315:4315:1130/133541.781662:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper
binary was found, but is not configured correctly. Rather than run without sandboxing I'm
aborting now. You need to make sure that /opt/google/chrome/chrome-sandbox is owned
by root and has mode 4755.
```

My config is very simple, but in case it's interesting:

```yaml
language: node_js
node_js:
    - 'node'
    - '8'
    - '7'
    - '6'
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
addons:
    chrome: stable
```

I'm going to try to work around this by moving to sudo, and manually changing the chrome-sandbox owner and permissions, but it seems like this should work by default.

**Comment by pimterry** [comment]
Furthermore, I can confirm this is a regression in Travis itself (either the OS setup, or the Chrome version used has changed). This build passed a month ago:

* https://travis-ci.org/pimterry/mockttp/builds/296020369

This push of exactly the same commit on a new branch fails with the error above:

* https://travis-ci.org/pimterry/mockttp/jobs/309516697

**Comment by AviVahl** [comment]
Saw this on our repo as well:
https://travis-ci.org/wix/wix-react-tools/jobs/309479737#L3034

**Comment by pimterry** [comment]
As a workaround https://github.com/pimterry/mockttp/commit/852849ff41b84842a66cdd4a0a8282ca87f1c6ca has fixed it for me: use `sudo: required`, chown & chmod chrome-sandbox to have the correct permissions, and everything starts up correctly.

**Comment by rwwagner90** [comment]
Nice workaround @pimterry! I just noticed this regression on all my travis jobs this morning as well. Any official fixes coming or should we add that workaround?

**Comment by cotsog** [comment]
Hey everyone,

We are still looking into the contributing factors for this issue.

In the meantime, could someone confirm if just adding the following to your .travis.yml file also work?

```yaml
addons:
  chrome: stable
```

Thanks!

**Comment by Leooo** [comment]
@cotsog check https://github.com/pimterry/mockttp/commit/852849ff41b84842a66cdd4a0a8282ca87f1c6ca

**Comment by Turbo87** [comment]
@cotsog that is what we have in https://github.com/emberjs/ember-test-helpers/blob/ca52448c55f510551389853d6188150a7f0a0ece/.travis.yml#L9-L10 and it still seems to fail.

also we're *not* using xvfb, but using the `--headless` mode with `sudo: false` instead, but are experiencing the same issues.

**Comment by pimterry** [comment]
@cotsog My fix is to a travis file that already contains that addons line. On its own, that doesn't work.

**Comment by cotsog** [comment]
@Turbo87, @pimterry: thanks for the confirmation. I've updated my comment above to include the current working workarounds i.e. 

>Please either use @pimterry's [suggestion](https://github.com/travis-ci/travis-ci/issues/8836#issuecomment-348198699) or the following:
>
>```yaml
>sudo: required
>addons:
>  chrome: stable
>```

Thank you for your patience!

**Comment by QuantumInformation** [comment]
Will this effect me and my nightwatch tests?

```json
{
  "src_folders" : ["tests"],
  "output_folder" : "reports",
  "custom_commands_path" : "",
  "custom_assertions_path" : "",
  "page_objects_path" : "",
  "globals_path" : "",

  "selenium" : {
    "start_process" : true,
    "server_path" : "./node_modules/selenium-server-standalone-jar/jar/selenium-server-standalone-3.7.1.jar",
    "log_path" : "",
    "host" : "127.0.0.1",
    "port" : 4444,
    "cli_args" : {
      "webdriver.chrome.driver" : "./node_modules/chromedriver/bin/chromedriver",
      "webdriver.ie.driver" : ""
    }
  },

  "test_settings" : {
    "default" : {
      "launch_url" : "http://127.0.0.1:3000/",
      "selenium_port"  : 4444,
      "selenium_host"  : "localhost",
      "silent": true,
      "screenshots" : {
        "enabled" : false,
        "path" : ""
      },
      "desiredCapabilities": {
        "browserName": "chrome",
        "javascriptEnabled": true,
        "acceptSslCerts": true
      }
    }
  }
}
```

I can't get selenium to connect.

Error retrieving a new session from the selenium server
Connection refused! Is selenium server started?

**Comment by cespinoza-loga** [comment]
@QuantumInformation I have the exact same problem as you, maybe it is related to this. I'm trying @pimterry's workaround right now

**Comment by QuantumInformation** [comment]
this didn't help me

```yml
language: node_js
node_js:
  - "7"
install:
  - npm --prefix ./client install ./client
  - npm --prefix ./client/nightwatch install ./client/nightwatch
cache:
  directories:
  - node_modules
  - client/node_modules
  - client/nightwatch/node_modules
before_script:
  - npm --prefix ./client start ./client &
script: npm run test-ci
sudo: required
addons:
 chrome: stable
```
