### ISSUE TITLE
Bash parameter substitution not working in script deployment target

### ISSUE THREAD

**Issue by zglueck** [travis-ci/travis-ci#8841]
We conduct a parameter substitution in one of our script deployment targets to remove the preceding "v" character (the `${TRAVIS_TAG#"v"}`):

```
  # Publish release distributions to the Artifactory repository
  - provider: script
    script: node ./travis/publishFolderToArtifactory $ARTIFACTORY_API_KEY ./build/dist /artifactory/web/${TRAVIS_TAG#"v"}
    skip_cleanup: true
    on:
      tags: true
```

As of November 14th, the parameter was successfully being removed as indicated the deployment from the travis run:
https://travis-ci.org/NASAWorldWind/WebWorldWind/builds/302222052

However, today (November 30th), the same travis configuration file and project failed to remove the `v` character:
https://travis-ci.org/NASAWorldWind/WebWorldWind/builds/309635500

I setup a parameter substitution test case for travis and found that it doesn't seem to be evaluating the substitution (line 762 should be `0.0.19-RC2`):
https://travis-ci.org/f17d911/WebWorldWind/builds/309704094#L762

We can adjust our script, but wanted to check we weren't missing something or if there were restrictions on bash operations in the script deployment. Thanks!
