### ISSUE TITLE
travis-build: CACHE_NAME cannot be set from TRAVIS_xxx_VERSION, CC, CXX and other variables

### ISSUE THREAD

**Issue by grooverdan** [travis-ci/travis-ci#8858]
CACHE_NAME formed from some of the Default Environment variables would be a logical choice. An example would be "compiler: gcc" vs clang ($CC) for ccache.
https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables

In the build process it seems the variables are set as follows:

1. env global variables
1. env matrix variables
1. lib/travis/build/script/*rb (export function) https://github.com/travis-ci/travis-build/tree/master/lib/travis/build/script/...

The order means settings a global or matrix environment variable CACHE_NAME based on any Default Environment Variable would be impossible.

**Comment by BanzaiMan** [comment]
I do not think `CACHE_NAME` is an environment variable we set.

**Comment by grooverdan** [comment]
No, its one available for a user to set (https://docs.travis-ci.com/user/caching#Caches-and-build-matrices).

**Comment by BanzaiMan** [comment]
# Steps to reproduce

```yaml
language: node_js
node_js:
  - '8'
env:
  global:
    - MY_VAR=${TRAVIS_NODE_VERSION}_hello
```

# Expected behavior

`$MY_VAR` is set to `8_hello`

# Actual behavior

`$MY_VAR` is set to `_hello`

**Comment by BanzaiMan** [comment]
Hmmm. On a second thought, setting built-in env vars first will allow them to be overridden by users, and that does not seem like a good idea.

**Comment by grooverdan** [comment]
How about an extra re-interpolation of CACHE_NAME before its used?

So:

```
language: node_js
node_js:
  - '8'
env:
  matrix:
    - CMAKE_BUILD_TYPE=RelWithDebInfo
    - CMAKE_BUILD_TYPE=Debug
  global:
    - CACHE_NAME=\${TRAVIS_NODE_VERSION}_\${CMAKE_BUILD_TYPE}
```

Expected behaviour:

`CACHE_NAME`=`8_Debug`  or `8_RelWithDebInfo`
