### ISSUE TITLE
Making jobs conditional on the commit text

### ISSUE THREAD

**Issue by randombit** [travis-ci/travis-ci#8861]
I have a CI setup with ~20 different jobs testing different build configurations, etc. However some of them are fairly expensive to run, so I'd like to only run them if explicitly requested rather than every time. This will cut down our CI turnaround times, and also GCP bills for you ;) The specific goal is if the commit message contains "[expensive tests]" then run all jobs, otherwise just run the fast subset.

It appears like the conditional jobs support does exactly what I want. But when matching against `TRAVIS_COMMIT_MESSAGE` the job seems to always be enabled regardless. Here is what I'm trying to do:

```
matrix:
  include:
    - os: linux
      compiler: gcc
      env: BUILD_MODE="shared"
    - if: env(TRAVIS_COMMIT_MESSAGE) =~ expensive tests
      os: osx
      compiler: clang
      env: BUILD_MODE="shared"
```

(example build https://travis-ci.org/randombit/botan/builds/311353116)

It's not totally clear from the docs if this is supposed to work; the docs say "The function env currently only supports environment variables that are given in your build configuration (e.g. on env or env.global), not environment variables specified in your repository settings." but doesn't say anything one way or another about the implicit variables like TRAVIS_COMMIT_MESSAGE.

I can skip the conditional jobs thing and have the `script` block check the commit message and exit immediately if we don't want to run. However that still requires the VM be created, and probably the biggest driver to doing this is the very long wait times for OSX builds, which would still be a problem with this approach. I'd like to be able to skip the builds entirely.
