### ISSUE TITLE
Cannot run tests for .NET Core 1.1 app

### ISSUE THREAD

**Issue by Saibamen** [travis-ci/travis-ci#8866]
I cannot test .NET Core 1.1 app.
Job: https://travis-ci.org/Saibamen/BriskChat/jobs/312668821

CC: @joshua-anderson @akoeplinger @nterry

**Comment by akoeplinger** [comment]
You should be able to install .NET Core 1.1 runtime with this .travis.yml:

```yml
addons:
  apt:
    packages:
    - dotnet-sharedframework-microsoft.netcore.app-1.1.2
```
