### ISSUE TITLE
Additional email addresses for notifications, while also keeping the defaults

### ISSUE THREAD

**Issue by torokati44** [travis-ci/travis-ci#8868]
Although the email addresses to which Travis sends notifications about build successes/failures is configurable, adding any address will override the default setting of notifying the author and the committer. Currently there is no way to configure email notifications in a way that will keep notifying the committer and the author, but will also notify some additional, fixed addresses.

I want to do this because I manage the CI config of an open source project, and I want to be notified about any build failures, regardless of who made the latest/triggering commit. But I also want to keep them notified. I'm interested because a failure might be caused by a broken/outdated CI configuration, not just by the recent code changes being bad, and I don't want to keep polling the builds every day.

The same feature was already requested by someone else a while ago, on StackOverflow:
https://stackoverflow.com/questions/34202148/email-author-committer-and-another-specified-email-address-in-travis

**Comment by alextrastero** [comment]
I was trying to accomplish something similar, I wanted another email to get notified if CRON jobs were failing... but no luck.
```yml
notifications:
  email:
    recipients:
      - xxx@yyy.com
    on_success: never
    on_failure: always
  on:
    condition: $TRAVIS_EVENT_TYPE = "cron"
```
