### ISSUE TITLE
Can't build and test through. Android-27 , build-tools-27.0.2

### ISSUE THREAD

**Issue by XinyueZ** [travis-ci/travis-ci#8874]
Can any one help me? 

Stuck from my side.

https://travis-ci.org/XinyueZ/mvvm-template/jobs/313586340

I can 't build (./gradlew test) it.

my ```yml``` is 

```
language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.2
    - android-27
    - add-on
    - extra
licenses:
    - 'android-sdk-license-.+'
jdk:
    - oraclejdk8
script:
    - ./gradlew :repository:testMockDebugUnitTest :repository:testProdDebugUnitTest :repository:testProdReleaseUnitTest
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
```

```
    buildToolsVersion = '27.0.2'
```

I have tried 27.0.1  as well, same failed. 

I had one or three times successed, just 2 hours later, something went wrong.

same ```yml```,  no change.

**Comment by magneticflux-** [comment]
I encountered the same issue.

My build log: https://travis-ci.org/Pattonville-App-Development-Team/Android-App/builds/313576794

StackOverflow question: https://stackoverflow.com/a/47719835/9073728

**Comment by cotsog** [comment]
It seems Google uploaded a new version of the android-27 package and the checksum is now different and the download fails. It might be caused because we are using the old `android` CLI to install the Android SDKs under the hood. I'm not sure how fast we'll be able to fix that but in the meantime, I was wondering if you could try to install it yourself using the `sdkmanager` CLI instead? Here's what you would need to add to your .travis.yml file: 

```yaml
before_install:
  - yes | sdkmanager "platforms;android-27"
```

Please let us know if this helps or not.

Thanks!

**Comment by magneticflux-** [comment]
@cotsog It looks like that fixed it!

Here's my first successful build: https://travis-ci.org/Pattonville-App-Development-Team/Android-App/builds/313658277

**Comment by XinyueZ** [comment]
it works, thanks to all .

**Comment by XinyueZ** [comment]
@cotsog It works, however, we need final solution.

**Comment by nagkumar** [comment]
where is  .travis.yml this file located..

**Comment by magneticflux-** [comment]
@nagkumar I placed it after `android` `components` and before `script`. I don't think it matters though since they're all labeled.

**Comment by msridhar** [comment]
Should this issue be re-opened until there is a proper fix?

**Comment by XinyueZ** [comment]
I reopen

**Comment by kfieldi5** [comment]
This should be re-opened. Still no proper fix.

**Comment by eduardomoroni** [comment]
Yes, Just created a new pipeline. Failed over and over. Only way to make it works was:
```
      android:
        components:
          - build-tools-26.0.2
          - android-26

      before_install:
        - yes | sdkmanager "platforms;android-26"
```
