### ISSUE TITLE
Leaking secure environment variables.

### ISSUE THREAD

**Issue by jmalloc** [travis-ci/travis-ci#889]
I've just noticed that my builds have been leaking secure environment variables for around 4 days. An example of such a build is [here](https://travis-ci.org/IcecaveStudios/chassis/jobs/4447281). In this case the environment variables was a GH token, which I've obviously since revoked!

From the build console, I see ...

```
$ export ICECAVE_PUBLISH_COVERAGE=[secure]
$ export ICECAVE_GITHUB_TOKEN=*MY ACTUAL TOKEN*
```

Whereas previous the output was ...

```
$ export ICECAVE_PUBLISH_COVERAGE=[secure] ICECAVE_GITHUB_TOKEN=[secure]
```

There have been no changes to the `.travis.yml` file, which is:

``` yaml
language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

matrix:
  # Use PHP 5.4 for coverage reporting.
  include:
    - php: 5.4
      env:
        - secure: "M1kq6DyvqIpvt3EMdbJU+n2vlnTI5JKlsHsPgCauGcyuvzXgThK5UDr6Nhv6\nc7dJHcYqznYrIZ7gYjrAl4CpFUsQ+zmfxXYfC4Ubxe0EEX3Y98QQQv354R77\nMU2cXDyceHrNmW1t0WZ+HJS0owdg0vPzKS6JenqirArgRbLQ+YM="

  # PHP 5.5 is still in alpha, so ignore build failures.
  allow_failures:
    - php: 5.5

install: composer install --dev --prefer-source
script:  ./vendor/bin/travis-build
```
