### ISSUE TITLE
Cannot install RabbitMQ 3.7.0 after trusty update

### ISSUE THREAD

**Issue by acogoluegnes** [travis-ci/travis-ci#8906]
Getting this after trusty update (https://travis-ci.org/reactor/reactor-rabbitmq/jobs/315885285):

```
Setting up rabbitmq-server (3.7.0-1) ...

Installing new version of config file /etc/init.d/rabbitmq-server ...

Installing new version of config file /etc/logrotate.d/rabbitmq-server ...

/var/lib/dpkg/info/rabbitmq-server.postinst: 14: /opt/jdk_switcher/jdk_switcher.sh: [[: not found

/var/lib/dpkg/info/rabbitmq-server.postinst: 21: /opt/jdk_switcher/jdk_switcher.sh: [[: not found

/var/lib/dpkg/info/rabbitmq-server.postinst: 28: /opt/jdk_switcher/jdk_switcher.sh: [[: not found

/var/lib/dpkg/info/rabbitmq-server.postinst: 35: /opt/jdk_switcher/jdk_switcher.sh: [[: not found

/var/lib/dpkg/info/rabbitmq-server.postinst: 42: /opt/jdk_switcher/jdk_switcher.sh: [[: not found

/var/lib/dpkg/info/rabbitmq-server.postinst: 49: /opt/jdk_switcher/jdk_switcher.sh: [[: not found

/var/lib/dpkg/info/rabbitmq-server.postinst: 56: /opt/jdk_switcher/jdk_switcher.sh: [[: not found

/var/lib/dpkg/info/rabbitmq-server.postinst: 62: /opt/jdk_switcher/jdk_switcher.sh: [[: not found

/var/lib/dpkg/info/rabbitmq-server.postinst: 62: /opt/jdk_switcher/jdk_switcher.sh: [[: not found

/var/lib/dpkg/info/rabbitmq-server.postinst: 62: /opt/jdk_switcher/jdk_switcher.sh: [[: not found

/var/lib/dpkg/info/rabbitmq-server.postinst: 109: /opt/jdk_switcher/jdk_switcher.sh: Syntax error: "(" unexpected (expecting "fi")

dpkg: error processing package rabbitmq-server (--configure):

 subprocess installed post-installation script returned error exit status 2

Processing triggers for libc-bin (2.19-0ubuntu6.13) ...

Processing triggers for ureadahead (0.100.0-16) ...

Errors were encountered while processing:

 rabbitmq-server

W: --force-yes is deprecated, use one of the options starting with --allow instead.

E: Sub-process /usr/bin/dpkg returned an error code (1)

apt-get.diagnostics

apt-get install failed

$ cat ~/apt-get-update.log

Ign:1 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty InRelease

Hit:2 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty-updates InRelease

Hit:3 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty-backports InRelease

Hit:4 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty Release

Ign:5 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 InRelease

Hit:7 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 Release

Ign:8 http://dl.google.com/linux/chrome/deb stable InRelease

Hit:10 http://dl.google.com/linux/chrome/deb stable Release

Hit:11 http://apt.postgresql.org/pub/repos/apt trusty-pgdg InRelease

Ign:6 http://toolbelt.heroku.com/ubuntu ./ InRelease

Get:9 http://dl.bintray.com/apache/cassandra 39x InRelease [3,168 B]

Hit:13 http://security.ubuntu.com/ubuntu trusty-security InRelease

Hit:14 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty InRelease

Hit:12 http://toolbelt.heroku.com/ubuntu ./ Release

Hit:15 https://dl.hhvm.com/ubuntu trusty InRelease

Ign:16 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty InRelease

Ign:17 https://dl.bintray.com/rabbitmq/debian trusty InRelease

Hit:18 https://download.docker.com/linux/ubuntu trusty InRelease

Get:21 https://dl.bintray.com/rabbitmq/debian trusty Release [40.1 kB]

Get:23 https://dl.bintray.com/rabbitmq/debian trusty Release.gpg [821 B]

Hit:24 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty InRelease

Hit:25 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty InRelease

Ign:27 https://packages.erlang-solutions.com/ubuntu trusty InRelease

Hit:28 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty InRelease

Hit:29 https://packagecloud.io/computology/apt-backport/ubuntu trusty InRelease

Get:30 https://dl.bintray.com/rabbitmq/debian trusty/main amd64 Packages [420 B]

Get:31 https://packages.erlang-solutions.com/ubuntu trusty Release [3,687 B]

Get:32 https://dl.bintray.com/rabbitmq/debian trusty/main i386 Packages [420 B]

Hit:33 https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease

Get:34 https://packages.erlang-solutions.com/ubuntu trusty Release.gpg [836 B]

Hit:35 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty InRelease

Hit:36 https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu trusty InRelease

Hit:37 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty Release

Get:38 https://packages.erlang-solutions.com/ubuntu trusty/contrib amd64 Packages [166 kB]

Get:40 https://packages.erlang-solutions.com/ubuntu trusty/contrib i386 Packages [162 kB]

Fetched 377 kB in 2s (138 kB/s)

Reading package lists...

W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)

The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install esl-erlang=1:20.1 rabbitmq-server=3.7.0-1" failed and exited with 100 during .
```

There used to be warnings, but the installation would work (https://travis-ci.org/reactor/reactor-rabbitmq/jobs/315341974):
```
Setting up rabbitmq-server (3.7.0-1) ...

Installing new version of config file /etc/init.d/rabbitmq-server ...

Installing new version of config file /etc/logrotate.d/rabbitmq-server ...

/var/lib/dpkg/info/rabbitmq-server.postinst: 14: /opt/jdk_switcher/jdk_switcher.sh: [[: not found

/var/lib/dpkg/info/rabbitmq-server.postinst: 21: /opt/jdk_switcher/jdk_switcher.sh: [[: not found

/var/lib/dpkg/info/rabbitmq-server.postinst: 28: /opt/jdk_switcher/jdk_switcher.sh: [[: not found

/var/lib/dpkg/info/rabbitmq-server.postinst: 35: /opt/jdk_switcher/jdk_switcher.sh: [[: not found

/var/lib/dpkg/info/rabbitmq-server.postinst: 42: /opt/jdk_switcher/jdk_switcher.sh: [[: not found

/var/lib/dpkg/info/rabbitmq-server.postinst: 49: /opt/jdk_switcher/jdk_switcher.sh: [[: not found

/var/lib/dpkg/info/rabbitmq-server.postinst: 55: /opt/jdk_switcher/jdk_switcher.sh: [[: not found

/var/lib/dpkg/info/rabbitmq-server.postinst: 55: /opt/jdk_switcher/jdk_switcher.sh: [[: not found

/var/lib/dpkg/info/rabbitmq-server.postinst: 55: /opt/jdk_switcher/jdk_switcher.sh: [[: not found

 * Starting message broker rabbitmq-server

   ...done.
```

First script used for installation:
```
sudo apt-get update -y
sudo apt-get install -y init-system-helpers socat adduser logrotate

cd /tmp/
wget https://dl.bintray.com/rabbitmq/rabbitmq-server-deb/rabbitmq-server_3.7.0-1_all.deb
sudo dpkg --install rabbitmq-server_3.7.0-1_all.deb
sudo rm rabbitmq-server_3.7.0-1_all.deb
```

With `addons` from `.travis.yml`:
```yaml
addons:
  apt:
    sources:
      - sourceline: deb https://packages.erlang-solutions.com/ubuntu trusty contrib
        key_url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
      - sourceline: deb https://dl.bintray.com/rabbitmq/debian trusty main
        key_url: https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc
    packages:
      - esl-erlang=1:20.1
      - rabbitmq-server=3.7.0-1
```

Both now fails.

Configuration file: https://github.com/reactor/reactor-rabbitmq/blob/master/.travis.yml

**Comment by BanzaiMan** [comment]
Thanks for the report. This is rather strange; the apt package installation's `postinst` script is invoking `jdk_switcher.sh` for whatever reason. And even more curiously, `jdk_switcher.sh` contains a syntax error (perhaps due to empty environment variables at the time of execution).

**Comment by cotsog** [comment]
Cross-linking the documented issue: https://github.com/travis-ci/travis-ci/issues/8870#issuecomment-351749483. Explanation and workaround are pending.

**Comment by BanzaiMan** [comment]
My guess, then, is that `dpkg` now takes these syntax errors and bails instead of letting go. Which I guess is a good thing.

**Comment by BanzaiMan** [comment]
`postinst` is using `sh` (https://staging.travis-ci.org/BanzaiMan/travis_staging_test/builds/676444#L1160), which does not recognize the Bash syntax `if [[ … ]]` and so on.

**Comment by BanzaiMan** [comment]
It is not clear to me if we can overcome this without some considerable amount of work on the build image, or user intervention.

To intervene, the user can:

 1. move the offending `apt` package from the `addons.apt.packages` and convert the equivalent `sudo apt-get install …` to `before_install`
1. remove `/opt/jdk_switcher/jdk_switcher.sh` before `sudo apt-get install …`

For example, @acogoluegnes's 

```yaml
addons:
  apt:
    sources:
      - sourceline: deb https://packages.erlang-solutions.com/ubuntu trusty contrib
        key_url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
      - sourceline: deb https://dl.bintray.com/rabbitmq/debian trusty main
        key_url: https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc
    packages:
      - esl-erlang=1:20.1
      - rabbitmq-server=3.7.0-1
```

would become

```yaml
addons:
  apt:
    sources:
      - sourceline: deb https://packages.erlang-solutions.com/ubuntu trusty contrib
        key_url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
      - sourceline: deb https://dl.bintray.com/rabbitmq/debian trusty main
        key_url: https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc
    packages:
      - esl-erlang=1:20.1
before_install:
  - sudo rm -f /opt/jdk_switcher/jdk_switcher.sh
  - sudo apt-get install rabbitmq-server=3.7.0-1
```

**Comment by BanzaiMan** [comment]
If `jdk_switcher` is needed afterwards, it will need to be preserved.

**Comment by acogoluegnes** [comment]
@BanzaiMan, following your suggestion, I did this:

```yaml
addons:
  apt:
    sources:
      - sourceline: deb https://packages.erlang-solutions.com/ubuntu trusty contrib
        key_url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
      - sourceline: deb https://dl.bintray.com/rabbitmq/debian trusty main
        key_url: https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc
    packages:
      - esl-erlang=1:20.1
before_install:
  - sudo mv /opt/jdk_switcher/jdk_switcher.sh /tmp
  - sudo apt-get install rabbitmq-server=3.7.0-1
  - sudo mv /tmp/jdk_switcher.sh /opt/jdk_switcher/
```

It worked. Thanks a lot for the follow-up!
