### ISSUE TITLE
Build stages: Add support for environment matrix

### ISSUE THREAD

**Issue by avoinea** [travis-ci/travis-ci#8907]
# What I am trying to accomplish:

```yml
jobs:
  include:
    - stage: code
      env:
        - CHECK=jslint
        - CHECK=pylint
        - CHECK=i18n
        - CHECK=zptlint
      script:
        - echo $CHECK

    - stage: test
      env:
        - PLONE=4
        - PLONE=5
      script:
        - echo $PLONE
```
* [.travis.yml](https://github.com/collective/eea.facetednavigation/blob/94b2f860cd8d14955ee18741624ae53df12dc592/.travis.yml)
* [travis-ci.org](https://travis-ci.org/collective/eea.facetednavigation/builds/315822312)

# How did I manage to accomplish it:

```yml
jobs:
  include:
    - stage: code
      env:
        - CHECK=jslint
      script:
        - echo $CHECK

    - stage: code
      env:
        - CHECK=pylint
      script:
        - echo $CHECK

    - stage: code
      env:
        - CHECK=i18n
      script:
        - echo $CHECK

    - stage: code
      env:
        - CHECK=zptlint
      script:
        - echo $CHECK

    - stage: test
      env:
        - PLONE=4
      script:
        - echo $PLONE

    - stage: test
      env:
        - PLONE=5
      script:
        - echo $PLONE
```
* [.travis.yml](https://github.com/collective/eea.facetednavigation/blob/master/.travis.yml)
* [.travis-ci](https://travis-ci.org/collective/eea.facetednavigation/builds/315846803)

# Request

* Support `env matrix` within `build stages`. 
* Or maybe I'm missing something?!
