### ISSUE TITLE
Job stage conditions are not working correctly

### ISSUE THREAD

**Issue by elsteelbrain** [travis-ci/travis-ci#8948]
```ruby
require 'travis/conditions'

str  = '(NOT branch IN (master, alpha, staging, prod) AND ((NOT env(ANY_SERVICES_FILES_CHANGED) IS blank) OR (NOT env(FRONTEND_FILES_CHANGED) IS blank) OR (NOT env(SENSITIVE_FILES_CHANGED) IS blank)))'
data = {
    branch: 'mybranch',
    env: { ANY_SERVICES_FILES_CHANGED: 'services/api/handler.js', FRONTEND_FILES_CHANGED: '', SENSITIVE_FILES_CHANGED: '' }
}
puts Travis::Conditions.eval(str, data)
```
This above prints true when we run it locally. But doesn't work when the same conditions are applied as job stage `if`, e.g.:
```
jobs:
  include:
  - stage: test
    if: NOT branch IN (master, alpha, staging, prod) AND ((NOT env(ANY_SERVICES_FILES_CHANGED) IS blank) OR (NOT env(FRONTEND_FILES_CHANGED) IS blank) OR (NOT env(SENSITIVE_FILES_CHANGED) IS blank))
```

I've wasted so many hours trying to debug this issue but and the conclusion I've reached is that there is bug in Travis.

Please look into this. Thanks
