### ISSUE TITLE
bundle command failing due to RubyGems bug

### ISSUE THREAD

**Issue by jnimety** [travis-ci/travis-ci#8969]
This started happing on our builds yesterday. We have made no changes to .travis.yml in the past few weeks.
```
./bin/bundle:104:in `load': cannot load such file -- /home/travis/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/exe/bundle (LoadError)
	from ./bin/bundle:104:in `<main>'
```

```
sudo: false
dist: trusty
language: ruby
cache:
  bundler: true
  yarn: true
rvm:
  - 2.4.2
bundler_args: --without "development debug"
env:
  matrix:
    # Run the quickest builds first to get them out of the way
    - TEST_SCRIPT=./script/ci/database_test.sh
    - TEST_SCRIPT=./script/ci/javascript_specs.sh
    - TEST_SCRIPT=./script/ci/simple_ruby_specs.sh
    - TEST_SCRIPT=./script/ci/flickering_specs.sh
    - TEST_SCRIPT=./script/ci/non_feature_specs.sh
    - TEST_SCRIPT=./script/ci/feature_specs.sh
    - TEST_SCRIPT=./script/ci/scss_lint.sh
    - TEST_SCRIPT=./script/ci/bundle_audit.sh
before_install:
  # prep node and yarn
  - nvm install 6.9.1
  - nvm use 6.9.1
  - npm install -g yarn
  # Prep gem and bundler
  - export PATH=./bin:./node_modules/.bin:./script/ci:$PATH
  - gem update --system
  - gem install bundler
before_script:
  - yarn install
  - RAILS_ENV=development webpack
  - RAILS_ENV=development webpack
  # Print versions for debugging
  - gem --version
  - node --version
  - yarn --version
  - eslint --version
  - phantomjs --version
  # this gives ElasticSearch time to start before the tests start
  - sleep 10
script: "${TEST_SCRIPT}"
branches:
  except:
    - /^[0-9]/
...
```
