### ISSUE TITLE
Build stages that are allowed to fail

### ISSUE THREAD

**Issue by charleschenster** [travis-ci/travis-ci#8998]
Is it possible to allow a stage to fail and still continue with the rest of the build phases? For example with build matrixes we can set `allow_failures` to allow an item to fail without failing the entire build

For my use-case, I've split up my test phase into unit and integration tests. I'd like the travis build to still succeed even if the integration tests fail. For example:

```
jobs:
  include:
    - stage: test
      script: ./run-unit-tests.sh
      after_success:
        - ./docker_push.sh
    - stage: test
      script: ./run-integration-tests.sh
```

**Comment by BanzaiMan** [comment]
If all the jobs in a stage is allowed to fail, the build should proceed to the next stage.

**Comment by charleschenster** [comment]
@BanzaiMan Thanks for the quick reply! The build stages documentation don't specify how I can set that a stage can be allowed to fail. Can you provide an example? 

Also, I only want the integration tests to be allowed to fail, while the unit tests should fail the build if they do not succeed. Based on your response, it doesn't seem possible yet but I just wanted to double check.

**Comment by BanzaiMan** [comment]
https://docs.travis-ci.com/user/customizing-the-build#Rows-that-are-Allowed-to-Fail

See https://github.com/travis-ci/travis-build/blob/af4b84614590336a137310a1b82688f3d32a03e4/.travis.yml#L23-L40 for an example. Here, you see that two conditions exist for marking a job as being allowed to fail. Since the two stages `test update_static_files Rake task` and `:ship: it to Quay.io` has only jobs which are allowed to fail, the execution of the build always moves on to the next stage.

**Comment by anastasia2140** [comment]
hi @BanzaiMan 
is it possible somehow allow to fail all stages at once e.g. 
`allow_failures:
    script: any` 
etc. ?

**Comment by BanzaiMan** [comment]
@anastasia2140 There is no wild card which matches everything.

**Comment by dtasev** [comment]
For people coming here from google that want wild card matches, you can use an env variable for your stage to mark everything in it as allowed to fail:
 
```
jobs:
  allow_failures: 
    env:
      - CAN_FAIL=true
  include:
    - stage: this can fail
       env: CAN_FAIL=true
       script: ... everything here can fail ...
```
This will allow a stage to fail completely. If you want to make this for the whole build just set it on a top-level `env: CAN_FAIL=true` so that all stages have it, and everything can fail. The `CAN_FAIL` env variable name is arbitrary and can be anything else.

**Comment by VassilisVassiliadis** [comment]
This wouldn't work for me out of the box. I had to change the `env` key in the `include` item to be an array of strings instead of a string.

```yaml
jobs:
  allow_failures: 
    env:
      - CAN_FAIL=true
  include:
    - stage: this can fail
      env:
       - CAN_FAIL=true
      script: ... everything here can fail ...
```

**Comment by alexislefebvre** [comment]
According to [this page](https://docs.travis-ci.com/user/build-matrix/#matching-jobs-with-allow_failures), the top-level `env:` is necessary.

So it should work with this configuration:

```yaml
env:
  - CAN_FAIL=false

jobs:
  allow_failures: 
    env:
      - CAN_FAIL=true
  include:
    - stage: this can fail
      env:
       - CAN_FAIL=true
      script: ... everything here can fail ..

```

Example: https://travis-ci.org/github/alexislefebvre/AsyncTweetsBundle/builds/707200258
