### ISSUE TITLE
YAML engine issues on 1.9.2 and than on 1.8.7

### ISSUE THREAD

**Issue by ifesdjeen** [travis-ci/travis-ci#90]
Psych (YAML engine on 1.9.2) does not merge keys, following won't work:

```
base: &base
  username: postgres
  pool: 5

development:
  <<: *base
  database: travis_development
```

Tenderlove suggests to downgrade back to Sych: https://github.com/tenderlove/psych/issues/8 by adding YAML::ENGINE.yamler = 'syck' 
Although Ruby 1.8.7 does not have YAML::ENGINE yet, so we need to take care of it and check whether constant exists.
