### ISSUE TITLE
Set an  encrypted variable in .travis.yml, but not work

### ISSUE THREAD

**Issue by xiangge** [travis-ci/travis-ci#9007]
Hi,
I met an issue with setting the encrypted variable in .travis.yml and "Environment Variables"
I set a variable in with:

`travis encrypt PROACCESS="token" --add`

And then try to use the security "PROACCESS", but I can't it in the script part, could anyone do me a favor about this?
Even I set the it in "Environment Variables", I can't get it.

```
language: ruby
cache: bundler
rvm:
- 2.2.2
install:
- bundle install --jobs=3 --retry=4
script:
- bundle exec rake test
- |
  if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
    echo $PROACCESS
    PRONTO_GITHUB_ACCESS_TOKEN=$PROACCESS pronto run -f github_pr -c origin/${TRAVIS_BRANCH}
  fi
env:
  global:
  - PRONTO_PULL_REQUEST_ID=${TRAVIS_PULL_REQUEST}
  secure: nH69L5tk+KVdP5n/8XmM...
```

**Comment by BanzaiMan** [comment]
I'll assume you are inquiring about https://github.com/product-definition-center/pdc-ruby-gem/pull/45.

In the failing build https://travis-ci.org/product-definition-center/pdc-ruby-gem/builds/324942129#L539, you notice that only `PRONTO_PULL_REQUEST_ID` is defined. This is due to [the unexpected data structure of `env`](https://github.com/xiangge/pdc-ruby-gem/blob/cfa9f97228bf4aa32126f63259778c692b4be3ba/.travis.yml#L25-L28), where `env.secure` is in the wrong place.

This looks to me like a bug in the CLI client, but the long story short, you can fix this by switching to this:

```yaml
env:
  global:
  - PRONTO_PULL_REQUEST_ID=${TRAVIS_PULL_REQUEST}
  - secure: nH69L5tk+KVdP5n/8XmM...
```
