### ISSUE TITLE
Extracting and creating cache is very slow

### ISSUE THREAD

**Issue by delijah** [travis-ci/travis-ci#9009]
We are caching `node_modules` to achieve a faster build time on travis ci. I have discovered, that downloading and extracting the cache, but also creating and uploading the cache takes a very long time.

`Setting up build cache` around 90s
`store build cache` if nothing has changed between 10s and 80s
otherwise between 90s and 180s

The size of the compressed node_modules directory is about 160mb.

If i compress the directory on my computer with the command `tar zcf node_modules.tgz ./node_modules` it takes about 20s.

If i extract the contents of the archive with the command `tar zxf node_modules.tgz -C ./node_modules` it takes about 12s.

This would mean, for the extraction part, that downloading the archive takes about 78s (since extracting takes about 12s) which does not really makes sense, does it? Downloading around 160mb should maybe take 5 seconds, but not longer?

### Conclusion
On travis, to download and extract the cached node_modules directory it takes around 90s, but only 17s locally if i do the same on the command line. This feels wrong to me.

It is also pretty weird, that cache times vary that much.

We work with travis-ci.com.

### Our travis.yml
```
env:
  matrix:
  - NPM_RUN_SCRIPT=ci:lint-and-build
  - NPM_RUN_SCRIPT=ci:test:unit
  - NPM_RUN_SCRIPT=ci:test:visual
  global:
  - NODE_VERSION=8.9.1
  - NPM_VERSION=5.5.1
  - CXX=g++
  # ...

os: osx
language: node_js
node_js: $NODE_VERSION

sudo: false

cache:
  directories:
  - node_modules

before_install:
- if [[ `npm -v` != $NPM_VERSION ]]; then npm install -g npm@$NPM_VERSION; fi
- npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

install:
- npm install

before_script:
- chmod u+x env.sh
- source ./env.sh

script:
- npm run $NPM_RUN_SCRIPT

deploy:
 # ...
```
