### ISSUE TITLE
Regexp syntax doesn't work in deploy-on block or in if condition

### ISSUE THREAD

**Issue by kotya341** [travis-ci/travis-ci#9040]
our goal is to deploy our version via hockey-app and depends on branch it should be beta-release version or just dev version.
the rule for beta-release version is `rc_` prefix

```
deploy:
- provider: script
  script: ./gradlew uploadDevToHockeyapp;
  skip_cleanup: true
  on:
    branch: develop
- provider: script
-  script: ./gradlew uploadBetaToHockeyapp;
   skip_cleanup: true
-  on:
-    condition: $TRAVIS_BRANCH =~ ^release\/rc_.*
```
this is out current version and it works for dev, but script never worked for rc.
Moreover we tried to use just if condition like this: 
`script: if [[ "$TRAVIS_BRANCH" =~ ^release\/rc_.* ]]; then ./gradlew uploadBetaToHockeyapp; fe`

and result is the same

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here? Please also include the one that shows that “it works for dev.”

**Comment by kotya341** [comment]
this is a good scenario build with a [dev](https://travis-ci.com/foodora/logistics-rider-app-android/builds/63187229) 
and this is a build with a [problem](https://travis-ci.com/foodora/logistics-rider-app-android/builds/63119659)

**Comment by BanzaiMan** [comment]
Could you confirm that you are pointing to the right build?

If you are, then, this is working as documented. In the "problematic" one, I believe the provider in question is configured this way:

```yaml
deploy:
  - provider: script
    script:
      - if [[ "$TRAVIS_BRANCH" =~ ^release\/rc_.* ]]; then ./gradlew uploadBetaToHockeyapp; fe
    skip_cleanup: true
```

(Incidentally, this is different from the YAML you included in the description of this ticket. I should also mention that `script` ends with `fe`, which should be `fi`.)

Since this build ran on `release/rc_2.7.0`, and the `branch` condition is not present on this provider, it is assumed to run on the `master` branch, and therefore this provider is skipped. You can see this in the second "skip" message:

```
Skipping a deployment with the script provider because this branch is not permitted
```

If you want to deploy when the branch name is unknown ahead of time, you should pass `on.all_branches: true`, as explained in https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A:

> `branch`: name of the branch. If omitted, this defaults to the `app`-specific branch, or `master`. If the branch name is not known ahead of time, you can specify `all_branches: true` *instead of* `branch: ` and use other conditions to control your deployment.

**Comment by BanzaiMan** [comment]
Try

```yaml
deploy:
  - provider: script
    script: ./gradlew uploadBetaToHockeyapp
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^release\/rc_.*
```

**Comment by BanzaiMan** [comment]
@kotya341 Were you able to resolve it?

**Comment by kotya341** [comment]
Thanks a lot for the fix it works

**Comment by kotya341** [comment]
guys I'm trying to use this config and again I'm facing with a problem
**Skipping a deployment with the script provider because this branch is not permitted**

this is a link to the [build](https://travis-ci.com/foodora/logistics-rider-app-android/builds/69571346)

branch name is _release/rc_2.7.4_ and deploy script is 

```
deploy:
- provider: script
  script: ./scripts/build_post_version_to_github_beta.sh
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^release\/rc_.*
```
