### ISSUE TITLE
Pushing android apk to GitHub release files

### ISSUE THREAD

**Issue by jahirfiquitiva** [travis-ci/travis-ci#9067]
Hello

For me it has been really difficult to understand how to setup travis properly. This might not be a real "issue" but I hope someone around here could help me achieve what I want.

Basically, I want Travis to generate an apk and upload it as an attachment/binary when I create a new release for [my project](https://github.com/jahirfiquitiva/Frames/) but only for releases to  `master` branch.

If that's not possible, I have seen a project that creates the apk and uploads it as a new release directly from Travis, but it get overwritten every time so there's a single release with a unique tag for this. This behavior would also work but I would prefer the first one.

This is the configuration file I am using right now, and I have literally no idea of what I am doing there. I have basically tried to copy/paste/adjust the configs of other android projects I have found on GitHub, but whatever I try it just does not work :(

I don't see any errors or anything on Travis logs that could point me to where the issue could be so that's why I am asking for help as I have already tried a lot without success.

I would appreciate any help on this. Thanks in advance. :)

----

```yml
language: android

env:
  global:
  - ANDROID_API=27
  - ANDROID_BUILD_TOOLS=27.0.3

android:
  components:
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - ".+"
  
jdk:
- oraclejdk8

script: if [[ "$TRAVIS_BRANCH" == "master" ]]; then ./gradlew clean :app:assembleRelease --stacktrace; else ./gradlew clean test --stacktrace; fi

branches:
  except:
  - images
  - gh-pages
  - travis-build
  - i18n
  
notifications:
  email: false
  slack:
    rooms: jahirfiquitiva:StCMaxV85iad38DdSMBY43xW
    template:
    - 'Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}: ''%{commit_subject}''>)  by
      %{author} for %{repository_name}@%{branch}, %{result} in %{duration}. <%{build_url}|Check
      details>.'
      
sudo: false

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

before_script:
- chmod +x gradlew

before_install:
- yes | sdkmanager "platforms;android-27"

before_deploy:
  - git tag -f "travis-build"

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file_glob: true
  file: $TRAVIS_BUILD_DIR/app/build/outputs/apk/release/*.apk
  skip_cleanup: true
  overwrite: true
  prerelease: true
  target_commitsh: $TRAVIS_COMMIT
  on:
    branch: master
    repo: jahirfiquitiva/Frames
    
after_deploy:
  - rm -rf $TRAVIS_BUILD_DIR/app/build/outputs
```
