### ISSUE TITLE
Python 3.7 will require OpenSSL 1.0.2+; 3.7-dev, 3.8-dev (nightly) do not work on Trusty

### ISSUE THREAD

**Issue by tiran** [travis-ci/travis-ci#9069]
PSA,

Python 3.7's ssl module will not work on Ubuntu 14.04 any more. I'm going to push several patches soon that depend on OpenSSL 1.0.2 or 1.1.0 APIs. See https://mail.python.org/pipermail/python-dev/2018-January/151718.html

**Comment by BanzaiMan** [comment]
Related: #9119

**Comment by yan12125** [comment]
I got the following error when trying to install CPython git-master via pyenv:
```
The Python ssl extension was not compiled. Missing the OpenSSL lib?
```
(https://travis-ci.org/yan12125/python3-android/jobs/335168981)

I guess it's related to this issue? The CPython commit that requires OpenSSL 1.0.2+ is merged 3 days ago: https://github.com/python/cpython/commit/61d478c71c5341cdc54e6bfb4ace4252852fd972

**Comment by tiran** [comment]
It's very likely. The ssl module in 3.7 no longer compiles with OpenSSL from Ubuntu 14.04.

Check your configure output. On a system with compatible libssl, it looks like this:
```
checking whether compiling and linking against OpenSSL works... yes
checking for X509_VERIFY_PARAM_set1_host in libssl... yes
checking for --with-ssl-default-suites... python
```

If the second line ends with ``no``, then either OpenSSL is too old or you have LibreSSL.

**Comment by BanzaiMan** [comment]
@yan12125 You are using pyenv, so I believe the fix will come from that tool, not Travis.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/docs-travis-ci-com/pull/1710 adds a note to inform users that recent `*-dev` and `nightly` do not work.

**Comment by dcrosta** [comment]
Is there a timeline for resolution here?

**Comment by pfreixes** [comment]
I would like to have some visibility of the future plans for this issue.

**Comment by ambv** [comment]
As the simplest workaround, change the following in your .travis.yml:
- switch to Xenial
- require sudo
- in `before_install`, add the very well maintained [deadsnakes PPA](https://launchpad.net/%7Edeadsnakes/+archive/ubuntu/ppa)
- in `install`, for the "3.7-dev" environment, [replace the virtualenv with one from deadsnakes](https://github.com/ambv/black/blob/master/.travis_py37_workaround.sh).

This [solved the issue for me](https://travis-ci.org/ambv/black/jobs/368457331).
See my example [.travis.yml](https://github.com/ambv/black/blob/master/.travis.yml).

Note: switching to Xenial is important. While deadsnakes also include a `python3.7` build for Trusty, that version doesn't include SSL support and we're back on Square 1.

**Comment by ambv** [comment]
Unfortunately I find "xenial" quite flaky. They relatively often fail to boot or find `/var/lib/dpkg/lock` locked by something else (but what?). Restarting build jobs helps.

**Comment by jamadden** [comment]
For those that were already using pyenv to manually manage multiple Python versions, gevent has [a forked pyenv](https://github.com/gevent/pyenv) that builds and [installs](https://github.com/gevent/gevent/blob/master/scripts/install.sh#L111) both OpenSSL and CPython 3.7b3. (This was easy because it already built OpenSSL on the Mac, we just had to modify it to do so on Travis.) Something is not quite right in the build because we have to set [LD_LIBRARY_PATH](https://github.com/gevent/gevent/blob/master/Makefile#L200) at runtime to use SSL, but it basically works.

Perhaps someone will find that useful. (It comes with no guarantees so if you'd like to use it you will probably want to fork it.)

**Comment by Monkeyboy2805** [comment]
I should probably point out that Python 3.7 is due to be released next month so if this could be solved in the near future

**Comment by BanzaiMan** [comment]
Currently, we are working on getting the Xenial image out. Thanks for your patience.

**Comment by htgoebel** [comment]
@BanzaiMan I suggest skipping xenial, which is two years already.

**Comment by BanzaiMan** [comment]
The work on Bionic is not too far behind. Thanks!

**Comment by scivision** [comment]
@BanzaiMan That's good that Ubuntu 18.04 is coming for Travis-CI, because with Travis-CI currently lacking even Ubuntu 16.04, I have been switching progressively to AppVeyor for Linux tests...
(AppVeyor has Ubuntu 16.04)

**Comment by dcrosta** [comment]
@BanzaiMan do you have a rough estimate of when this might be available?

**Comment by ambv** [comment]
@dcrosta, the Xenial image is stable finally \o/ I configured it like this: https://github.com/ambv/black/blob/master/.travis.yml

**Comment by dcrosta** [comment]
@ambv is it really slow for you, too? Or did I just get an unlucky host?

**Comment by ambv** [comment]
It used to hang sometimes, these days it runs just as fast as the old image.

**Comment by dcrosta** [comment]
It's still significantly flakey for me :\

**Comment by alex** [comment]
I just wanted to flag that at this point 3.7 has been released, so I imagine there'll be an unptick of interest in this.

**Comment by 76creates** [comment]
@alex was right :) 
`Python requires an OpenSSL 1.0.2 or 1.1 compatible libssl with X509_VERIFY_PARAM_set1_host()`

built with `--with-openssl=/usr/bin`

```
which openssl
/usr/bin/openssl

openssl version
OpenSSL 1.1.0h  27 Mar 2018
```

Am I doing anything wrong?

**Comment by webknjaz** [comment]
To run Python 3.7 in Travis, according to https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-401756442, use the following config:
```yaml
language: python
python: 3.7
dist: xenial
sudo: true
```

**Comment by Flimm** [comment]
Thanks @webknjaz . To build upon that, here's how to test against multiple Python versions (xenial doesn't support the older versions):


```yml
sudo: true
language: python
matrix:
  include:
    - python: "2.7"
      dist: xenial
    - python: "3.3"
      dist: trusty
    - python: "3.4"
      dist: trusty
    - python: "3.5"
      dist: xenial
    - python: "3.6"
      dist: xenial
    - python: "3.7"
      dist: xenial
    - python: "pypy"
      dist: trusty
```

**Comment by cclauss** [comment]
My favorite...  Only use xenial and sudo when you have to...
```
group: travis_latest
language: python
cache: pip
jobs:
    include:
      - python: 2.6    # 2.6.9  pip  9.0.1
      - python: 2.7    # 2.7.14 pip  9.0.1
      - python: 3.3    # 3.3.6  pip  8.1.2
      - python: 3.4    # 3.4.6  pip  9.0.1
      - python: 3.5    # 3.5.5  pip  9.0.1
      - python: 3.6    # 3.6.3  pip  9.0.1
      - python: 3.7    # 3.7.0  pip 10.0.1
        dist: xenial
        sudo: true
      - python: 3.8-dev
        dist: xenial
        sudo: true
      - python: nightly
        dist: xenial
        sudo: true
      - python: pypy   # 2.7.13 pip  9.0.1
      - python: pypy3  # 3.5.3  pip  9.0.1
matrix:
    allow_failures:
        - python: 3.8-dev
        - python: nightly
script:
    - python --version
    - pip --version
```
