### ISSUE TITLE
Unable to lock the administration directory

### ISSUE THREAD

**Issue by fpoli** [travis-ci/travis-ci#9080]
In the last two weeks our builds fail very often on a `sudo apt-get install`:
```
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
```
For example, see the builds [here](https://travis-ci.org/viperproject/viper/jobs/329495928#L434), [here](https://travis-ci.org/viperproject/viper/jobs/329495929#L509), [here](https://travis-ci.org/viperproject/viper-sys/jobs/328709476)...

Our `.travis.yml` files ([here](https://github.com/viperproject/viper/blob/c6d4b994c5e8ca6981d879498ba35994bb49d42c/.travis.yml) and [here](https://github.com/viperproject/viper-sys/blob/0f4a34e8980fd221199f9ce35a8f8e6a6ccc413c/.travis.yml)) begin with:
```yml
language: rust
cache: cargo
dist: xenial
sudo: true

rust:
  - stable
  - beta
  - nightly

jdk:
  - oraclejdk8

# ... rest of .travis.yml
```

Does this usually happen to others? Is there a workaround?
