### ISSUE TITLE
Using 'travis encrypt "key" --add' with jobs/stages and multiple deploy providers

### ISSUE THREAD

**Issue by Chadsr** [travis-ci/travis-ci#9082]
Hi,

This possibly has a very simple solution, but after some hours of searching I have not found one. It's also possible that I have gravely misunderstood some of the syntax I am attempting.

I have a rather complex .travis.yml which I am trying to add encrypted keys to, using the cli tool like so:
`travis encrypt "some_key" --add some.path`

My problem arises when I have a yml with many key/value pairs such as:

```
jobs:
  include:
    stage: some_stage
      deploy:
        - provider: provider1
          key:
        - provider: provider2
          key:
```

So in this mock-example, I am attempting to add an encrypted secret to each of the providers. I'm unable to find a way to reference the provider value (e.g. provider1) so that travis encrypt will insert the secret like so:

```
jobs:
  include:
    stage: some_stage
      deploy:
        - provider: provider1
          key:
            secure: some_encrypted_secret
        - provider: provider2
          key:
            secure: some_other_encrypted_secret
```

So, in summary i'd like to ask if what I am attempting is possible and if so, how exactly can I add a secure key to a provider with `--add` in a structure such as above?

Thanks for your time.
