### ISSUE TITLE
Why is this stuck

### ISSUE THREAD

**Issue by kennedyshead** [travis-ci/travis-ci#9083]
https://travis-ci.org/kennedyshead/py-melissa-climate/builds/329631780

tested in docker and it works fine.

It also have ruby as language but i set it to python?

```yaml
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
  - "nightly"
# command to install dependencies
cache: pip
install:
  - pip install -e . mock
# command to run tests
script:
  - python -m unittest discover -s tests -p "test_*.py"
```
