### ISSUE TITLE
Build Stages: Part of the job gets duplicated and moved outside the job

### ISSUE THREAD

**Issue by fsih** [travis-ci/travis-ci#9090]
Here's the content of our build config, according to https://travis-ci.org/LLK/scratch-l10n/jobs/298151653/config:
```
{
  "language": "node_js",
  "node_js": 6,
  "cache": {
    "directories": [
      "node_modules"
    ]
  },
  "jobs": {
    "include": [
      {
        "stage": "npm release",
        "if": "branch IN (env(RELEASE_BRANCHES))",
        "node_js": 6,
        "script": "npm run build",
        "before_deploy": [
          "VPKG=$($(npm bin)/json -f package.json version)",
          "export VERSION=${VPKG/%?/}$(date +%Y%m%d%H%M%S)",
          "npm --no-git-tag-version version $VERSION"
        ],
        "deploy": {
          "provider": "npm",
          "skip_cleanup": true,
          "email": "$NPM_EMAIL",
          "api_key": "$NPM_TOKEN",
          "true": {
            "all_branches": true
          }
        }
      }
    ]
  },
  "group": "stable",
  "dist": "trusty",
  "before_deploy": [
    "VPKG=$($(npm bin)/json -f package.json version)",
    "export VERSION=${VPKG/%?/}$(date +%Y%m%d%H%M%S)",
    "npm --no-git-tag-version version $VERSION"
  ],
  "if": "branch IN (env(RELEASE_BRANCHES))",
  "script": "npm run build",
  "stage": "npm release",
  "os": "linux"
}

```

And here is the content of our [.travis.yml](https://github.com/LLK/scratch-l10n/blob/master/.travis.yml):
```
language: node_js
node_js:
- 6
- node
cache:
  directories:
  - node_modules
jobs:
  include:
    - stage: npm release
      if: branch IN (env(RELEASE_BRANCHES))
      node_js: 6
      script: npm run build
      before_deploy:
      - VPKG=$($(npm bin)/json -f package.json version)
      - export VERSION=${VPKG/%?/}$(date +%Y%m%d%H%M%S)
      - npm --no-git-tag-version version $VERSION
      deploy:
        provider: npm
        skip_cleanup: true
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        on:
          all_branches: true
```

It looks like a bunch of pieces of our job have been duplicated and moved out of the job (everything below the job object). Is it possible that that part is getting run twice unnecessarily? If this is caused by an issue with our syntax, can we get help fixing the syntax?
