### ISSUE TITLE
`addons: chrome: stable` can't pass linter

### ISSUE THREAD

**Issue by Deilan** [travis-ci/travis-ci#9098]
The following `.travis.yml` file is not valid according to [Travis WebLint](https://lint.travis-ci.org/)

```yaml
language: node_js

addons:
  chrome: stable
```

The errors are:
> - value for addons section is empty, dropping
> - in addons section: unexpected key chrome, dropping

According to [the docs](https://docs.travis-ci.com/user/chrome) it's valid though.
