### ISSUE TITLE
Why can't I use my encrypted data?

### ISSUE THREAD

**Issue by Stzx** [travis-ci/travis-ci#9110]
Hi!

I added the encrypted data to my .travis.yml file based on the guidance of https://docs.travis-ci.com/user/encrypin-keys/, but I always get [secure] when I build it.

It's like this:
```
env:
  global:
   - secure: "jILe8B/XNihzO1lJDHgiCiTJ2keKvMajXuHzH/11eWL9/XeaZm0IKpz/hkRiHZ/w7oS/P2WfVRtDaBJkyjTu09Qj3tEuT+PrrYRusMbv85irmmsGweDr2LNpbC6I85j9sbmg8NpAGjJ4XXD5IlDqMVbnNgJ+qrO+t6yWRLDb1ZPcudRzbA574lPSYcgAR0tTHS3xlS2QssWaJVGs0vJTFgEo0G2s4uc6fHcNRzC2/PApnZ9NZwymzprTUz7rmSIIS7gBwJXP+l3FW2/AETJKFZLRdgoFp+wo6CrcESafln6TQl8JWeYABTohqSqka94555KB0zkQzaLRn5WwF+1/4d78iM9LccdPMIwM3Li9mKLtwivUAyXiMg9g7Qx8UuAv8F4z8cNUl5jCTxJa2jPQRor2bnWWsOAq6ywzIAtx6XH3ALhnAga8fHBmCqtZUMik/QEQXRntthNK1RrlJwkSNOPPytIVc4g/KDvmJJk7nkUXdarHEtz+ERd6NWRlNJA9lninsQxatVH4wW3LPiPyQ4ko2CTNKpe/goYcF1ZTfrIvm9ZmnuP7Bc5elGMIaLYjw3o4Ht/taYH8BwY9/9/ufdbjQaTE7lymY2Z4SSVhoabOujLIc6tfYpsexBWGcopwGe+TRNzYOG/tnIvil1LD0clmWswCWFCtEWROlt3q0OU="

before_install:
   - openssl aes-256-cbc -K $TEST -in test.enc -out test -d
```

The $TEST was not decrypted at build time, so I got [secure] and caused the build to fail.

I wonder why? Did my configuration go wrong? :)
