### ISSUE TITLE
Parenthesis in conditional build expressions result in always true

### ISSUE THREAD

**Issue by jcrist** [travis-ci/travis-ci#9117]
I have two conditional expressions that should evaluate the same:

```
    - env:
      - DEMO=2
      if: type != pull_request OR head_branch =~ not-the-branch-name

    - env:
      - DEMO=3
      if: (type != pull_request) OR (head_branch =~ not-the-branch-name)
```

The only difference is parenthesis around each conditional. What I'm seeing is that when parenthesis are used, the conditional expression always evaluates to True.

Example PR: https://github.com/jcrist/dask/pull/6
Travis PR build: https://travis-ci.org/jcrist/dask/builds/331978585

In this case I'd expect neither `DEMO=2` or `DEMO=3` to be built, but `DEMO=3` is built anyway.
