### ISSUE TITLE
Confusing behavior of conditional job expressions

### ISSUE THREAD

**Issue by jondegenhardt** [travis-ci/travis-ci#9118]
I use a build matrix in `.travis.yml`. I want to conditionalize jobs to a minimal set when building on a fork repository, and use a more complete set when building on the main repository. I tried using the `if:  fork = [true|false]` expression. This did what I wanted, but the values seem backwards. I'm hoping you can clarify.

Specifically, I tried the following form:
```
matrix:
  include:
    - os: osx
      osx_image: xcode9
      language: d
      d: ldc
      env: DUBTEST=1 MAKETEST=1 APPLTO=off
      if: fork = false
```

I expected this `if:` expression to have the effect causing the job to run if it was the source repository, and not a fork. However, it out to be the opposite. To have the job run on the source repository and not a fork the form needed to be:
```
      if: fork = true
```

It all works fine, but I'm clearly not understanding something basic. It would be great if someone can explain.

**Comment by BanzaiMan** [comment]
The current implementation and the documentation do not match.

**Comment by jondegenhardt** [comment]
It appears to be even a bit more complex. After merging a pull request from a fork, the behavior on the source repository has changed, now neither fork nor the source repository are treating starting the jobs with an `if: fork = true`.

To summarize the behavior seen so far, when the line contains `if: fork = true`:

| Case  |  Result |
| ----- | ------- |
| Fork repository, master branch | Job not run |
| Fork repository, non-master branch | job not run |
| Source repository, Pull Request from fork | job is run |
| Source repository, master branch | job not run |

It would be very helpful to have documentation that describes these actually work. Especially right now, when there is a shortage of MacOS processing capacity. I'd really like to reduce my usage to minimal, one way to do this is to run different test sets on forks and source repositories.

**Comment by JimiC** [comment]
Actually `if` is not working properly at all.
Using the following config:
```yaml
sudo: required
language: generic
services:
  - docker
jobs:
  include:
  - name: build if fork
    if: fork = true
    script: bash -c 'echo fork'
  - name: build if main
    if: fork = false
    script: bash -c 'echo main'
```
build run in both `main` and `fork` repo executing `build if main` job.

If I revert to
```yaml
sudo: required
language: generic
services:
  - docker
jobs:
  include:
  - name: build if fork
    if: fork = false
    script: bash -c 'echo fork'
  - name: build if main
    if: fork = true
    script: bash -c 'echo main'
```
then build run in both `main` and `fork` repo executing `build if fork` job.
