### ISSUE TITLE
deploy fails due to permission problems

### ISSUE THREAD

**Issue by jleni** [travis-ci/travis-ci#9139]
Since yesterday, there are problems when deploying to pypi.
I have tried to preinstall 38.4.0 so there is no need for the travis deploy script to make changes..

I have also tried to go for a workaround:
    - sudo chmod -R 0777 /usr/lib/python2.7/
    - sudo chmod -R 0777 /usr/local/lib
but that does not seem to work either.
Has anyone seen this problem before?

Here is a log to a broken build:
https://travis-ci.org/theQRL/qryptonight/jobs/333186291

> Collecting setuptools
>  Downloading setuptools-38.4.0-py2.py3-none-any.whl (489kB)
>    100% |████████████████████████████████| 491kB 1.9MB/s 

....

>   Found existing installation: setuptools 38.2.4
>     Uninstalling setuptools-38.2.4:
> Exception:
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
>     status = self.run(options, args)
>   File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 342, in run
>     prefix=options.prefix_path,
>   File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 778, in install
>     requirement.uninstall(auto_confirm=True)
>   File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 754, in uninstall
>     paths_to_remove.remove(auto_confirm)
>   File "/usr/local/lib/python2.7/dist-packages/pip/req/req_uninstall.py", line 115, in remove
>     renames(path, new_path)
>   File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 267, in renames
>     shutil.move(old, new)
>   File "/usr/lib/python2.7/shutil.py", line 303, in move
>     os.unlink(src)
> OSError: [Errno 13] Permission denied: '/usr/local/bin/easy_install'

**Comment by Monkeyboy2805** [comment]
You need to actually ask about permissions to have sudo access.

**Comment by jleni** [comment]
Sorry, I am not sure what you mean. The configuration has:

>   "sudo": "required",
>   "dist": "trusty",
>   "services": "docker",
>   "language": "cpp",

and the `chmod` commands are just and example of a workaround I tried but it was not the original problem scenario.

**Comment by BanzaiMan** [comment]
@jleni Sorry for the issue. Could you try:

```yaml
deploy:
  provider: pypi
  edge:
    branch: sudo-pypi
  ⋮ # rest
```

to test https://github.com/travis-ci/dpl/pull/747?

Thanks.

**Comment by martinpitt** [comment]
I have the same issue, examples:

 - https://travis-ci.org/martinpitt/python-dbusmock/jobs/347969381
 - https://travis-ci.org/martinpitt/python-dbusmock/jobs/347965354

My .travis.yml should look like by the book:
```yaml
deploy:
  - provider: pypi
    user: "Martin.Pitt"
    password:
      secure: "[redacted]"
    skip_cleanup: true
    on:
      tags: true
      condition: -z "$RELEASE"
```

As #747 was rejected, I have not tried that.

**Comment by dbogdanov** [comment]
Same issue here: https://api.travis-ci.org/v3/job/386724044/log.txt

Is there any recommended workaround? 

```
deploy:
  - provider: pypi
    server: https://testpypi.python.org/pypi
    distributions: sdist bdist_wheel
    user: dbogdanov
    password:
      secure: [...]
    on:
branch: master
```


```
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/bin/pip'
Consider using the `--user` option or check the permissions.

You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

travis_fold:end:dpl.1
Couldn't install pip, setuptools, twine or wheel.
failed to deploy
```
