### ISSUE TITLE
RVM dependency when using docker

### ISSUE THREAD

**Issue by lbrito1** [travis-ci/travis-ci#9146]
I'm currently working on a multiple-container Docker project using docker-compose. Some of the containers are Ruby apps.

I'm currently trying to optimize our build, and one of the things I thought unnecessary was that  the travis.yml specified a ruby version. If the app is containerized, there is no need to use Ruby at all on the host.

```
sudo: required

language: ruby
rvm:
    - 2.4.1

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.7.0
  TESTING: true
  ROOT_URL: https://github.com/docker/compose/releases/download
  FILE: docker-compose-Linux-x86_64

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

install:
  - git clone ...
  - docker-compose up -d my_project

script:
  - docker exec -e my_project bundle exec rake spec

notifications:
  email: false
```

However, upon removing the Ruby/rvm entries, the build errors with the following:

```
# ...
$ rvm use $(< .ruby-version) --install --binary --fuzzy
curl: (22) The requested URL returned error: 404 Not Found
 is not installed - installing.
curl: (22) The requested URL returned error: 404 Not Found
Searching for binary rubies, this might take some time.
Requested binary installation but no rubies are available to download, consider skipping --binary flag.
 do rvm gemset create ' first, or append '--create'.
The command "rvm use $(< .ruby-version) --install --binary --fuzzy" failed and exited with 2 during .
```

I am at a loss here. Afaik Ruby (or any other language software) should definitively not be necessary in the host of a containerized app (although the [official travis docker guide](https://docs.travis-ci.com/user/docker/) uses `language: ruby`). Is this some kind of caching problem?
