### ISSUE TITLE
py.test fails with python3

### ISSUE THREAD

**Issue by pzhokhov** [travis-ci/travis-ci#9153]
Hello, 
I have a build that runs tests with pytest-xdist; and it used to work with both python2 and 3; but recently (last cron job, no code modifications on my side) python3 jobs started failing with 
the following pattern:
```
[gw1] node down: Not properly terminated
Replacing crashed slave gw1
[gw16] linux Python 3.6.3 cwd: /home/travis/build/studioml/studio
[gw0] node down: Not properly terminated
Replacing crashed slave gw0
[gw17] linux Python 3.6.3 cwd: /home/travis/build/studioml/studio
[gw2] node down: Not properly terminated
Replacing crashed slave gw2
``` 
(can be also found here: https://travis-ci.org/studioml/studio/jobs/334215390)
and so on till the max 10000 lines of output. 
I tried running it without parallel tests, got similar error (although slightly less convoluted):
```
$ py.test -v --durations=0
============================= test session starts ==============================
platform linux -- Python 3.6.3, pytest-3.3.0, py-1.5.2, pluggy-0.6.0 -- /home/travis/virtualenv/python3.6.3/bin/python
cachedir: .cache
rootdir: /home/travis/build/SentientTechnologies/studio, inifile:
plugins: xdist-1.22.0, forked-0.2
collecting ... /home/travis/.travis/job_stages: line 57:  2974 Aborted                 (core dumped) py.test -v --durations=0
```
Here is my .travis.yml file:
```
dist: trusty

language: python
python:
    - "2.7"
    - "3.6"

script:
    - git fetch --unshallow
    - pip install -e .
    - pip install -r test_requirements.txt

    - py.test -n 16 -v --durations=0
    - pycodestyle --show-source --exclude=.eggs .

jobs:
  include:
    - stage: deploy
      python: 2.7
      script: 
        - git fetch --unshallow
        - python setup.py sdist

      provider: pypi
      distributions: "sdist"
      user: pzhokhov
      password: 
        secure: "FkfIvyF3PReaXOuCNSeqlg9SAiocc8WxCzlbqnfssG6JxsIBWNuoOPtgKtiYmMO+LBXnzpZ8CkTjoHT2oWWBD8r92QNmdIOze1MPs5xQmGxu12TEc5dEgMUnvenV3vkOZGC/hhwbio16Dqfd8PlHYBRkduvvqrvRD1xJPsggx9tgZwZ+Vvv0h51/BpOIMxm0xV3qu1U5A3BIvyzTUucvCAPbmHeZj+tWtiTq3OEwpc812PsCNkFNEOIBUkwafu1VE15tFcud/pZyFYwEK8/z35CJDGY4oVKWZyoC5/Gp9w658ps6MnjWP36Y1GNj4wpQPL2ftvGzRfXvfZ/FcSi4mreon24YPYFlY76ezLibWq8m2/ZBlQQwchFi48nGoalDJ7a92hyVkrRr1UP87+fbrZW8u4l/2HiKYKgotAixnoKKVOaWcmhraLve+kLE5F6e0lwmwCOHQwO9Cz4PECiZtxf8ePdDj+Dr9RLI3rKehRATpL+kXkR4WzKXPJAfDiPS6WiOz/melZJIttQcFZpOUVCs79yKWj8E95atbEy0jFaGn1PR+lFHqFYsg8TTe9Q9L/qMc+ECzBzQ4ryClCKDMYylCqbfDpOmCtHZw0a79IKmSyyvNbjnFMhAcn+GHFp+O46iF7Zxb1fAmp45AZ48bG/FCVqp66EXr590Fy1gjh0="
      on:
        branch: master
        repo: studioml/studio
        condition: $TRAVIS_EVENT_TYPE == "push"
```
Thanks!
