### ISSUE TITLE
build stages "if:" conditional execution is wrong

### ISSUE THREAD

**Issue by gonewest818** [travis-ci/travis-ci#9160]
In https://github.com/gonewest818/lein-sysutils I added the following build stages configuration in this commit https://github.com/gonewest818/lein-sysutils/commit/785e21110cbcfd0e2fd02441ae9d6b594c2578c7
```
env:
  matrix:
    - VERSION=1.7 TARGET=test
    - VERSION=1.8 TARGET=test
    - VERSION=1.9 TARGET=test
  global:
    - secure: "<encrypted string>"
    - secure: "<encrypted string>"
stages:
  - name: test
  - name: check
  # Deploy only from the home repo where the credentials can be
  # properly decrypted. Never deploy from a pull request job.
  # In addition, ensure we're on the master branch (snapshots)
  # or a tagged version (releases).
  - name: deploy
    if: repo = gonewest818/lein-sysutils
        AND type != pull_request
        AND (branch = master OR tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+.*$)
```

Which, if you read my inline comments, you can see what I'm trying to achieve with the deploy stage. However, when I commit to a branch in this repo the deploy stage is enumerated, and it runs.  

But why?

I would have expected the conditional check to fail for the following reasons:

```
    if: repo = gonewest818/lein-sysutils             # << this part is true
        AND type != pull_request                     # << this is true
        AND (branch = master                         # << this is FALSE
             OR tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+.*$)  # << I think this is FALSE?
```

and to confirm this I edited the job to print the `TRAVIS_*` environment variables. See an example log here: https://travis-ci.org/gonewest818/lein-sysutils/jobs/334884907

The relevant (as far as I can tell) environment variables are:
```
TRAVIS_REPO_SLUG=[secure]/lein-sysutils
TRAVIS_PULL_REQUEST=false
TRAVIS_TAG=
TRAVIS_BRANCH=1-no-deploy-from-forks
TRAVIS_PULL_REQUEST_BRANCH=
```

And unless I misunderstand how the conditionals are supposed to work, this says there's something broken with how these conditional stages are working right now.

Let me know if you need more information?

thanks
