### ISSUE TITLE
configure cron jobs via `.travis.yml`

### ISSUE THREAD

**Issue by gotcha** [travis-ci/travis-ci#9162]
`.travis.yml` is the configuration of a repo at `travis-ci.com` so I think it would be a nice place to describe the `cron` job configuration.

@BanzaiMan answered that:
>  `cron` information is a repository-level concern, so https://travis-ci.com/OWNER/REPO/settings is the right place.

Is'nt it true that `.travis.yml` is describing repository-level concerns ?

**Comment by BanzaiMan** [comment]
`.travis.yml` governs the commit-level information, though.

What sort of configuration do you want to define in `.travis.yml`?

**Comment by gotcha** [comment]
Something like:

```
cron:
    - branch: master
       interval: monthly
       options: always run
    - branch: devel
       interval: daily
       options: not if last 24h
```
