### ISSUE TITLE
[Feature request][Python] Support last stable version

### ISSUE THREAD

**Issue by Kristinita** [travis-ci/travis-ci#9180]
### 1. Summary

It would be nice, if would be possible, that Travis CI can automatically set the latest Python **stable** version, that developers doesn't need to set specific version.

### 2. Argumentation

I develop Python packages. I want, that my packages works on latest stable Python version. Part of my example `.travis.yml` file:

```yaml
language: python
python:
  - "3.6.4"
```

When new Python version release, I need to change `3.6.4` to `3.6.5` in each my project, then I should change value to `3.6.6`, `3.7.0` and so on. It may take a lot of time.

### 3. Expected behavior

Example part of `.travis.yml`:

```yaml
language: python
python:
  - "stable"
```

Travis CI will automatically use the latest stable Python version, what is available on Travis CI.

It already realized in Travis CI for nightly Python versions:

```yaml
language: python
python:
  - "nightly"
```

Thanks.
