### ISSUE TITLE
Failed: No such file or directory -> at the 

### ISSUE THREAD

**Issue by ndoteddy** [travis-ci/travis-ci#9186]
https://travis-ci.org/ndoteddy/Project-Polistack-Web/jobs/337895781

![image](https://user-images.githubusercontent.com/35088152/35848099-61d3c912-0b4f-11e8-95ca-1c7ced19ec88.png)

Rsync: change_dir "/home/travis/build/ndoteddy/Project-Polistack-Web/build" failed: No such file or directory

```yaml
language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
```
with this config - why ya directory is missing ? is there anything wrong in my travis.yml?
apps : react(node js)
thanks
