### ISSUE TITLE
Add support for the latest PHP Release Candidate

### ISSUE THREAD

**Issue by hjr3** [travis-ci/travis-ci#920]
It is always really challenging to get users to test against the PHP release candidates. I think it would be great if people were able to add a version of php that was tracking the latest build RC. The PHP internals team would just tag a version "next" and it would rebuild nightly.

I imagine something like this:

```
language: php

php:
    - 5.3
    - 5.4
    - next

matrix:
  allow_failures:
    - php: next

script: phpunit --configuration app/
```

This makes it really easy for any project, open source or private, to see how their code does on the highest version release candidate. This also provides  a lot of fast and informative feedback to the internals team.

This is different from just tracking HEAD. The HEAD of php-src is not very stable and has historically been used for experimental code. This is tracking the next build RC, such as the next php 5.5 release.
