### ISSUE TITLE
deploy: missing github_token. suggest: support Deploy keys

### ISSUE THREAD

**Issue by sinkcup** [travis-ci/travis-ci#9213]
"Deploy keys" is safer than "Personal access tokens", I want to use it to deploy user pages to github master, but failed. CI: https://travis-ci.org/openwrtio/openwrtio.github.io/jobs/340501800

error: 

> !!! GitHub Pages support is experimental !!! missing github_token

shell:

```
sudo gem install travis
travis login
ssh-keygen -t rsa -b 4096 -C "deploy@travis-ci.org"
travis encrypt-file id_rsa -r openwrtio/openwrtio.github.io
```

`.travis.yml` https://github.com/openwrtio/openwrtio.github.io/blob/ddc24f8be6a3c388f539271699d4729d7676073b/.travis.yml

```

language: python
before_install:
  - openssl aes-256-cbc -K $encrypted_62f3167d5387_key -iv $encrypted_62f3167d5387_iv -in id_rsa.enc -out id_rsa -d
install:
  - pip install mkdocs
script:
  - mkdocs build --clean
after_success:
  # Add the ssh key
  - eval "$(ssh-agent)"
  - chmod 600 id_rsa
  - ssh-add id_rsa
deploy:
  provider: pages
  skip-cleanup: true
  on:
    branch: mkdocs
  local-dir: site
  target-branch: master
```
