### ISSUE TITLE
Some times build passes, sometimes build fails for same .travis.yml

### ISSUE THREAD

**Issue by abinrm** [travis-ci/travis-ci#9234]
I am using Travis CI for my Xcode project private repo.
 My .travis.yml looks like
```
language: objective-c
osx_image: xcode9.2

cache:
  directories:
    - Carthage

env:
  #environment variables
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - PROJECT_NAME="MyProject.xcodeproj"
    - SCHEME_TVOS_FRAMEWORK="framework_tvOS"
    - SCHEME_TVOS="MyProject"
    - TVOS_SDK=appletvsimulator11.2
  matrix:
    - DESTINATION="OS=11.0,name=Apple TV 1080p" SCHEME="$SCHEME_TVOS_FRAMEWORK" SDK="$TVOS_SDK"
    - DESTINATION="OS=11.0,name=Apple TV 1080p" SCHEME="$SCHEME_TVOS" SDK="$TVOS_SDK"

before_install:
  - brew update || true
  - brew outdated carthage || brew upgrade carthage
  - gem install xcpretty-travis-formatter

script:
  - set -o pipefail
  - xcodebuild clean test -project "$PROJECT_NAME" -scheme "$SCHEME" -destination "$DESTINATION" -sdk "$SDK" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcpretty -f `xcpretty-travis-formatter`
```
When I build, sometimes the build fails for the 2nd job (scheme: MyProject), but when I trigger another build the build passes (The travis config script is same for both builds, It successfully builds in local, no changes made before rebuilding). The error is given below. What could be the possible reason for this
![screen shot 2018-02-16 at 11 41 37](https://user-images.githubusercontent.com/36157771/36304323-87d4c658-130f-11e8-8c55-849822d45fb8.png)

 Is there something wrong with my script? Is it necessary to run brew commands for Carthage caching? I can see the Carthage is preinstalled in Travis, I added `brew update` by following Carthage [instructions](https://github.com/Carthage/Carthage#use-travis-ci-to-upload-your-tagged-prebuild-frameworks). It will be very helpful if someone can explain the steps for Carthage caching. I can't find any information related to Carthage on Travis CI [documentation](https://docs.travis-ci.com/user/caching/). Do I need to include the following in my travis config script
```
before_script:
  - carthage bootstrap
```
