### ISSUE TITLE
Golang v1.10 is parsed as 1.1

### ISSUE THREAD

**Issue by nezorflame** [travis-ci/travis-ci#9247]
# What happened

Adding Go version `1.10` to the .travis.yml is counted as `1.1`.

## .travis.yml

```yml
language: go
go:
        - 1.7
        - 1.8
        - 1.9
        - 1.10
        - tip
install:
        - go get -d -v ./...
        - go get -d -v golang.org/x/tools/cmd/cover
        - go get golang.org/x/time/rate
script:
- go test -v -cover ./...
```

## Build results

[Builds](https://travis-ci.org/nezorflame/go-smpp/builds/343414502)

![default](https://user-images.githubusercontent.com/3906766/36429882-db0954c6-1664-11e8-984c-cf54f7442302.png)

Log for #3.4:
```
...
$ gimme version
v1.3.0
$ go version
go version go1.1 linux/amd64
go.env
$ go env
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/travis/gopath"
GORACE=""
GOROOT="/home/travis/.gimme/versions/go1.1.src"
GOTOOLDIR="/home/travis/.gimme/versions/go1.1.src/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-g -O2 -fPIC -m64 -pthread"
CGO_ENABLED="1"
...
```

# How to fix

Versions have to be wrapped in brackets in order for Travis to parse them correctly:

```yml
language: go
go:
        - "1.7"
        - "1.8"
        - "1.9"
        - "1.10"
        - "tip"
...
```
