### ISSUE TITLE
allow_failures doesn't correctly check if an environmental variable is set

### ISSUE THREAD

**Issue by recursion-ninja** [travis-ci/travis-ci#9256]
```
matrix:
  include:
    - env FOO=foo

    - env FOO=too BAR=bar

    - env FOO=moo BAR=bar

  allow_failures:
    - env: BAR=bar
```
This should allow all builds to fail. Instead it does not allow any build to fail. This seems to be because it is becking for string equality of the `"env"` key.
