### ISSUE TITLE
Conditional build branch = master also triggers on "pull_request" builds

### ISSUE THREAD

**Issue by blimmer** [travis-ci/travis-ci#9260]
I had a build stage that looked like this:

```yaml
    - stage: tag-new-release-if-applicable
      if: branch = master
      before_script:
        - things
      script:
        - things
```

It was very surprising to me to see that this was building on `pull_request` type builds. It makes sense why this is the case (because it merges the default branch into the PR for testing), but that behavior was not at all obvious to me.

Changing my config to look like this is a workaround for the problem:

```
    - stage: tag-new-release-if-applicable
      if: branch = master and type != pull_request
      before_script:
        - things
      script:
        - things
```

However, this behavior could easily bite other people and some consideration should be given to changing it.
