### ISSUE TITLE
iOS test passed locally, but failed on Travis

### ISSUE THREAD

**Issue by yingmu52** [travis-ci/travis-ci#9267]
`.travis.yml`
```
 language: objective-c
 osx_image: xcode9
 xcode_sdk: iphonesimulator10.0

 branches:
   only:
     - develop

 before_install:
   - gem install xcpretty -N
   - brew update
   - brew install swiftlint || true

 script:
 - travis_retry xctool -workspace Snakepit.xcworkspace -scheme "Snakepit" -destination "platform=iOS Simulator,name=iPhone 6" -sdk iphonesimulator run-tests
```
