### ISSUE TITLE
Custom deploy message for gh-pages

### ISSUE THREAD

**Issue by dcastil** [travis-ci/travis-ci#9287]
I try to change the default commit message for gh-pages to one with an environment variable of the build. My deploy configuration in .travis.yml looks like this:
```
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: build
  github-token: $GITHUB_TOKEN
  keep-history: true
  commit_message: "Deploy release ${TRAVIS_TAG}"
  on:
    branch: master
    tags: true
```

But Travis is still deploying with the default commit message and I couldn't find any solution to this after further research. Am I missing something?
