### ISSUE TITLE
 Net::ReadTimeout Error with capybara / selenium / chrome (headless)

### ISSUE THREAD

**Issue by mnyrop** [travis-ci/travis-ci#9306]
Hello, 

I'm encountering a new error with selenium and headless chrome. The same error happens locally but arbitrarily (i.e., there's a roughly 50/50 chance it will throw the error on an unchanged test), which makes me think it is a problem with `selenium-webdriver`, `chromedriver-helper`, or chrome itself...?

For reference, I'm on `selenium-webdriver 3.10.0` and `chromedriver-helper 1.2.0`. I've tried both `chrome: stable` and `chrome: beta` in my `.travis.yml`.

__Error (from [Build #91](https://travis-ci.org/mnyrop/sudanphoto/builds/350158009)):__

```bash
Failures:
  1) en/photos has a search bar.
     Failure/Error: visit(baseurl + "/" + search_page + perma_ext)
     
     Net::ReadTimeout:
       Net::ReadTimeout
     # ./vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.10.0/lib/selenium/webdriver/remote/http/default.rb:121:in `response_for'
     # ./vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.10.0/lib/selenium/webdriver/remote/http/default.rb:76:in `request'
     # ./vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.10.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
     # ./vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.10.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
     # ./vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.10.0/lib/selenium/webdriver/remote/oss/bridge.rb:579:in `execute'
     # ./vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.10.0/lib/selenium/webdriver/remote/oss/bridge.rb:50:in `get'
     # ./vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.10.0/lib/selenium/webdriver/common/navigation.rb:30:in `to'
     # ./vendor/bundle/ruby/2.4.0/gems/capybara-2.18.0/lib/capybara/selenium/driver.rb:49:in `visit'
     # ./vendor/bundle/ruby/2.4.0/gems/capybara-2.18.0/lib/capybara/session.rb:274:in `visit'
     # ./vendor/bundle/ruby/2.4.0/gems/capybara-2.18.0/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
     # ./spec/quoll_spec.rb:12:in `block (3 levels) in <top (required)>'
```

__.travis.yml file:__
```yaml
dist: trusty
sudo: required
language: ruby
rvm:
  - 2.4
addons:
  apt:
    packages:
      - google-chrome-stable
script:
  - bundle exec jekyll build
  - bundle exec rake wax:test
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
branches:
  only:
  - master
```

(Same error happens with `addons: chrome: stable`.)

__spec_helper.rb:__
```ruby
require 'rspec'
require 'selenium/webdriver'
require 'capybara/dsl'
require 'rack/jekyll'
require 'rack/test'

RSpec.configure do |config|
  config.include Capybara::DSL

  Capybara.register_driver :chrome do |app|
    Capybara::Selenium::Driver.new(app, browser: :chrome)
  end

  Capybara.register_driver :headless_chrome do |app|
    capabilities = Selenium::WebDriver::Remote::Capabilities.chrome(
      chromeOptions: { args: %w(headless disable-gpu) }
    )

    Capybara::Selenium::Driver.new app,
      browser: :chrome,
      desired_capabilities: capabilities
  end

  Capybara.javascript_driver = :headless_chrome
  Capybara.current_driver = Capybara.javascript_driver
  Capybara.app = Rack::Jekyll.new(:force_build => false)
end
```

**Comment by mnyrop** [comment]
__UPDATE:__ Same error with Firefox headless. So It's gotta be something with Selenium on Travis?? 
(using `geckodriver-helper 0.0.4` / `env: MOZ_HEADLESS=1` /  `addons: firefox: latest`)

**Comment by SamuelGarratt** [comment]
@mnyrop I’m not sure where it is failing for you but I can show you my config that works. I was getting Timeout recently until I got latest version of Firefox (59.0.1). I’m using Rails.

Gem versions
selenium-webdriver 3.8.0 # Not the latest as you have
capybara 2.17.0

My rails_helper.rb
```
Capybara.register_driver :selenium do |app|
    require 'selenium/webdriver'
    Selenium::WebDriver::Firefox.driver_path = `which chromedriver`
    Capybara::Selenium::Driver.new(app, :browser => :firefox)
  end
```

Important parts of my config which is working now is

language: ruby
rvm:
  - 2.3
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.0/geckodriver-v0.20.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.20.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

**Comment by mnyrop** [comment]
Hi @SamuelGarratt. Thanks for your response! 

I'm a bit confused—if you're using Firefox, why is your path set on `which chromedriver`?
Also, your set up isn't headless, correct?

**Comment by SamuelGarratt** [comment]
Sorry my mistake. I tried to simplify my code and added chromedriver by mistake. It should be ‘which geckodriver’. I use “export DISPLAY=:99.0” and xvfb so I’m not running Firefox in headless mode but normally

**Comment by BanzaiMan** [comment]
If anyone is interested in troubleshooting this further with the debug mode, we are happy to enable that feature for your repository. https://docs.travis-ci.com/user/running-build-in-debug-mode/

**Comment by kasperite** [comment]
Just in case anyone is still stuck on this, I did two things to make my build passed in travis:

1. Install chrome stable(>= v65)
2. Pass `--no-sandbox` flag to the chrome executable

selenium-webdriver 3.10, chromedriver 2.38

**Comment by maestromac** [comment]
Thanks @kasperite ! `--no-sandbox` totally solved it for me. I like to add that `sudo: required` is required.

**Comment by jondoesntgit** [comment]
This line in `spec/spec_helper.rb` helped me:

```
  Capybara.register_driver :headless_chrome do |app|
    capabilities = Selenium::WebDriver::Remote::Capabilities.chrome(
      chromeOptions: { 'args' => %w{headless disable-gpu} }
    )
    Capybara::Selenium::Driver.new(app, browser: :chrome, desired_capabilities: capabilities)
  end

  Capybara.javascript_driver = :headless_chrome
```

Not sure what all is needed or not, but this is my .travis.yml

```
dist: trusty
sudo: required
language: ruby
rvm: 2.6.2
before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11  
  - sudo apt-get install chromium-browser chromium-chromedriver
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.20.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver  
before_script:
  - psql --version
  - psql -c 'CREATE DATABASE {{database_name}};' -U postgres
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
  - cp config/database.yml.travis config/database.yml
script: bundle exec rake spec
services:
  - postgresql
addons:
  postgresql: "11.2"
  firefox: latest
  chrome: stable
env:
  - MOZ_HEADLESS=1
```

The postgresql is for another workaround, so you can probably ignore it if you don't need it.
