### ISSUE TITLE
Is there a way for Travis CI to "save" previously downloaded apt packages?

### ISSUE THREAD

**Issue by arnavb** [travis-ci/travis-ci#9320]
I've recently started using Travis CI, and I love its power and simplicity. However, I have one issue: Build time.

**Specifics:**
- I am building a C++ Travis CI project
- Every time I push changes for said project, Travis CI has to install the packages `g++-7`, `gcc-7`, and `cmake` from an apt-repository. According to Travis, this is a total of **_110 MB_** of data that needs to be retrieved. Obviously, this can take a significant amount of time. 5-7 minutes amount of time (This doesn't seem like a lot, but for a build that should take less than 30 seconds, it is). As a comparison, my OSX builds take ~2 minutes to build using brew to install GCC.

**Is there a way for Travis CI to _reduce_ this time by maybe having the packages mentioned above _pre installed_ for these builds? This would significantly reduce my build time since all that fetching from an external apt-repository could be removed.**

Here is my `.travis.yml`:

```
dist: trusty
sudo: require
language: cpp
compiler: gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-7
            - gcc-7
            - cmake
before_script:
    - export CC=gcc-7
    - export CXX=g++-7
    - chmod +x ./travis_script.sh

script: ./travis_script.sh
```

Here is [my complete project](https://github.com/arnavb/cpp-project-template)
