### ISSUE TITLE
Travis wildcard is nonrecursive 

### ISSUE THREAD

**Issue by alexmozzhakov** [travis-ci/travis-ci#9322]
After 
```
Creating app bundle: /home/travis/build/alexmozzhakov/vk_notifier_GUI/build/jfx/native/NotifierforVK
```
Travis returns 
```
/home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/client/releases.rb:94:in `read': Is a directory @ io_fread - build/jfx/native/NotifierforVK (Errno::EISDIR)
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/client/releases.rb:94:in `upload_asset'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-releases-1.9.0/lib/dpl/provider/releases.rb:130:in `upload_file'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-releases-1.9.0/lib/dpl/provider/releases.rb:111:in `block in push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-releases-1.9.0/lib/dpl/provider/releases.rb:102:in `each'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-releases-1.9.0/lib/dpl/provider/releases.rb:102:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.0/lib/dpl/provider.rb:194:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.0/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.0/lib/dpl/provider.rb:194:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.0/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.0/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.0/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
failed to deploy
```
Even with 
```
language: java
script:
- gradle check
- gradle jfxNative
deploy:
  provider: releases
  api_key:
    secure: some_api_key
  file_glob: true
  skip_cleanup: true
  file: "build/jfx/native/*"
  on:
    repo: alexmozzhakov/vk_notifier_GUI
````
