### ISSUE TITLE
Problem with a command "docker login", unauthorized: incorrect username or password

### ISSUE THREAD

**Issue by proshik** [travis-ci/travis-ci#9334]
I have a problem

`Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password`

## log
https://api.travis-ci.org/v3/job/353308027/log.txt

## travis.yml
```
sudo: required

language: java
jdk: oraclejdk8

addons:
  apt:
    packages:
      - docker-ce

script: mvn clean test -B

after_success:
  - bash <(curl -s https://codecov.io/bash)

  # TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - export APPLEPRICESBOT=proshik/applepricesbot
  - export COMMIT=${TRAVIS_COMMIT::7}
  
  - docker build -t $APPLEPRICESBOT:$COMMIT .
  - docker tag $APPLEPRICESBOT:$COMMIT $APPLEPRICESBOT:$TAG
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $APPLEPRICESBOT:$TAG
```

But for other a similar configuration everything is all right:

## log 
https://api.travis-ci.org/v3/job/353281578/log.txt

## travis.yml
```
sudo: required

language: go

go:
  - "1.9"

addons:
  apt:
    packages:
      - docker-ce

script: make cover

after_success:
  - make cover
  - bash <(curl -s https://codecov.io/bash)

  # export
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - export GITHUBSTATBOT=proshik/githubstatbot
  - export COMMIT=${TRAVIS_COMMIT::7}

  # docker
  - docker build -t $GITHUBSTATBOT:$COMMIT .
  - docker tag $GITHUBSTATBOT:$COMMIT $GITHUBSTATBOT:$TAG
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $GITHUBSTATBOT:$TAG
```
