### ISSUE TITLE
Bintray authentication failing

### ISSUE THREAD

**Issue by bpteague** [travis-ci/travis-ci#9335]
Hello Travis CI,

First and foremost -- I think your service is awesome.  Thank you for your support of open-source projects!

Second, I am trying to deploy a few artifacts to Bintray at the end of a successful build, but I am getting failures in authentication.  Precisely the same configuration worked a little over a month ago.  For example, [this build](https://travis-ci.org/bpteague/cytoflow/jobs/339528063) from Feb 9 worked, while [this build]( https://travis-ci.org/bpteague/cytoflow/jobs/351803466) from yesterday failed.

The relevant section of my travis.yml file:
```
  - provider: bintray
    file: packaging/bintray.json
    user: bpteague
    key:
      secure: "ign6ESQuyEYnp1LJ0i/S+h2ZXtEP5P89EbmW7nRmFK1vvBAgD72sVI2y6tji+sErEErIke/ERZHRtLh4q8LvZT4J7LhJradRGYXa6Y1S56wb/bn2xRS1lKXJz3HUD+WxqYD3ZZ+q7AEcD51TkDv6Bmo5hXlkyHEzATBRwZl7kC2GPIatCva+KWd1YB1kUBPvrhCvgn1fCE0Xzcdzf5EKu7/uN2KkKLghUJKhOsXkWyREvfSlsMDSn/NWDp2KBIh1sv9JzRXmZhFAAaiVT74LfSPTwJKEAIV1RgAmSbEX60iS/5gCs2ntwoG8D6q5va+gSXwGjpk97kf9qhsocbf8w0L6vEq1Iw5CJwxY9P3gISGPmOGN6l3geksnpQgewNXMgIeZ0HvtxFJWc4HpiEZZZc0ZpVrGJY+WZZ5Bi3njNIbnW8A8g5+llJf+g2U7xnsqEs/oqzAKhbCnZvpXUH3TQjs58FmDegGCOI1hhZtxu4Vf0fE1yOu9nDW1nqxke7a8et3wLPGLXODR/zP+jz2opJe/UY87EstSSR6e7JMnGmgKbkImGrkvY0s4ul2ITeGTWoaZVKrWW7CKXS/MexVjDpKBdwUHhKeYcEszMOhyK1t3K75WTla3YIQW6Xmf5Nhxte6qCq1SDaamic6hjW9vCRSrlhcAqMuauja0MiKNxKc="
    dry-run: false
    skip_cleanup: true
    on:
      branch: packaging
```

and my descriptor file:
```
{
    "package": {
        "name": "cytoflow",
        "repo": "cytoflow",
        "subject": "bpteague"
    },
    "version": {
        "name": "latest"
    },
   
    "files":
        [
            {"includePattern" : "dist/(.*)", 
             "uploadPattern" : "$1",
             "matrixParams": {"override": 1 } }
        ],
   "publish": true 
}
```

Uploading to the bintray project with cURL works fine.  Based on the bintray.rb source, I think I'm uploading to the same URL that the deploy provider is using.

I've had a look at the dpl project's commit history, and I think the only change to bintray.rb in the relevant time period is [6191af](https://github.com/travis-ci/dpl/commit/6191af71954aa42959aea362d2164ceecf2be6b9).

I can't find any evidence that the bintray API changed in that time, and I haven't found any other (recent) reports of bintray auth failures.

Thanks again for all your awesomeness!  Let me know if there's any more information I can get you.
