### ISSUE TITLE
travis_wait command can't be found when used inside deploy

### ISSUE THREAD

**Issue by fredericojordan** [travis-ci/travis-ci#9336]
Hi! I'm currently having a problem when trying to use `travis_wait`.

From my `.travis.yml`:
```
deploy:
- provider: heroku
  app: <APP>
  api_key:
    secure: <KEY>
  on:
    repo: <REPO>
    branch: <BRANCH>
  run: travis_wait python manage.py migrate
```

And the [build](https://travis-ci.com/SingularityUniversity/singularity-directory-backend/builds/68223082) outputs this:
```
Running "travis_wait python manage.py migrate"
No dependent apps defined, exiting!
bash: travis_wait: command not found
```

I'd like some help as to why I the `travis_wait` command can't be found!
Thanks!
