### ISSUE TITLE
invalid configuration crash without explanation.

### ISSUE THREAD

**Issue by steffenix** [travis-ci/travis-ci#9337]
Hi,
I got the error: `There was an error in the .travis.yml file from which we could not recover.`

And this is my .travis.yml file.

```
matrix:
  include:
    - language: elixir
      elixir:
        - '1.6.3'
      otp_release:
        - 20.1
      script:
        - cd api/
        - mix local.rebar --force
        - mix local.hex --force
        - mix deps.get
        - mix credo --strict
      services:
        - postgresql
      addons:
        postgresql: "9.4"
    - language: node_js
      node_js:
        - "stable"
      cache:
        directories:
        - node_modules
      script:
        - cd frontend
        - npm install
        - npm test
        - npm run build
```

URL: https://travis-ci.org/CityOfZion/neochat
