### ISSUE TITLE
Sauce connect doesn't run with `sauce_connect: true` (after setting sauce credentials via environment variables)

### ISSUE THREAD

**Issue by rsimha** [travis-ci/travis-ci#9350]
The AMP HTML team is switching away from JWT encrypted Sauce credentials due to the [impending deprecation](https://blog.travis-ci.com/2018-01-23-jwt-addon-is-deprecated), and we're running into problems with `sauce_connect` on Travis while following the instructions [here](https://docs.travis-ci.com/user/sauce-connect/#Setting-up-Sauce-Connect).

Here are some lines we're using in `.travis.yml`:

```
env:
  global:
    - SAUCE_USERNAME="<username>"
    - SAUCE_ACCESS_KEY="<access key>"

addons:
  sauce_connect: true
```

With this, I'm seeing that `travis_start_sauce_connect` is not being started even though `SAUCE_USERNAME` and `SAUCE_ACCESS_KEY` are available in the environment. See the logs from this [test build](https://travis-ci.org/ampproject/amphtml/jobs/354382018).

Any idea what's going on here? Am I missing an undocumented step?
