### ISSUE TITLE
Failed to Deploy. Using '+' in a file name stalls and fails deployment

### ISSUE THREAD

**Issue by kevinta893** [travis-ci/travis-ci#9355]
Hi, 

So my Github Release deployments are failing during the deploy phase due to this error:

## Error during deploy 
```
/Users/travis/.rvm/rubies/ruby-2.2.9/lib/ruby/2.2.0/openssl/buffering.rb:326:in`

 `syswrite': Broken pipe (Faraday::ConnectionFailed)
	from /Users/travis/.rvm/rubies/ruby-2.2.9/lib/ruby/2.2.0/openssl/buffering.rb:326:in `do_write'
	from /Users/travis/.rvm/rubies/ruby-2.2.9/lib/ruby/2.2.0/openssl/buffering.rb:344:in `write'
	from /Users/travis/.rvm/rubies/ruby-2.2.9/lib/ruby/2.2.0/net/protocol.rb:211:in `write0'
	from /Users/travis/.rvm/rubies/ruby-2.2.9/lib/ruby/2.2.0/net/protocol.rb:185:in `block in write'
	from /Users/travis/.rvm/rubies/ruby-2.2.9/lib/ruby/2.2.0/net/protocol.rb:202:in `writing'
	from /Users/travis/.rvm/rubies/ruby-2.2.9/lib/ruby/2.2.0/net/protocol.rb:184:in `write'
	from /Users/travis/.rvm/rubies/ruby-2.2.9/lib/ruby/2.2.0/net/http/generic_request.rb:187:in `send_request_with_body'
	from /Users/travis/.rvm/rubies/ruby-2.2.9/lib/ruby/2.2.0/net/http/generic_request.rb:120:in `exec'
	from /Users/travis/.rvm/rubies/ruby-2.2.9/lib/ruby/2.2.0/net/http.rb:1412:in `block in transport_request'
	from /Users/travis/.rvm/rubies/ruby-2.2.9/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
	from /Users/travis/.rvm/rubies/ruby-2.2.9/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
	from /Users/travis/.rvm/rubies/ruby-2.2.9/lib/ruby/2.2.0/net/http.rb:1384:in `request'
	from /Users/travis/.rvm/rubies/ruby-2.2.9/lib/ruby/2.2.0/net/http.rb:1377:in `block in request'
	from /Users/travis/.rvm/rubies/ruby-2.2.9/lib/ruby/2.2.0/net/http.rb:853:in `start'
	from /Users/travis/.rvm/rubies/ruby-2.2.9/lib/ruby/2.2.0/net/http.rb:1375:in `request'
	from /Users/travis/.rvm/gems/ruby-2.2.9/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:80:in `perform_request'
	from /Users/travis/.rvm/gems/ruby-2.2.9/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:38:in `block in call'
	from /Users/travis/.rvm/gems/ruby-2.2.9/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
	from /Users/travis/.rvm/gems/ruby-2.2.9/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:33:in `call'
	from /Users/travis/.rvm/gems/ruby-2.2.9/gems/faraday-0.14.0/lib/faraday/response.rb:8:in `call'
	from /Users/travis/.rvm/gems/ruby-2.2.9/gems/faraday-0.14.0/lib/faraday/response.rb:8:in `call'
	from /Users/travis/.rvm/gems/ruby-2.2.9/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /Users/travis/.rvm/gems/ruby-2.2.9/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /Users/travis/.rvm/gems/ruby-2.2.9/gems/faraday-0.14.0/lib/faraday/rack_builder.rb:143:in `build_response'
	from /Users/travis/.rvm/gems/ruby-2.2.9/gems/faraday-0.14.0/lib/faraday/connection.rb:387:in `run_request'
	from /Users/travis/.rvm/gems/ruby-2.2.9/gems/faraday-0.14.0/lib/faraday/connection.rb:175:in `post'
	from /Users/travis/.rvm/gems/ruby-2.2.9/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	from /Users/travis/.rvm/gems/ruby-2.2.9/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'
	from /Users/travis/.rvm/gems/ruby-2.2.9/gems/octokit-4.6.2/lib/octokit/client/releases.rb:94:in `upload_asset'
	from /Users/travis/.rvm/gems/ruby-2.2.9/gems/dpl-releases-1.9.1/lib/dpl/provider/releases.rb:130:in `upload_file'
	from /Users/travis/.rvm/gems/ruby-2.2.9/gems/dpl-releases-1.9.1/lib/dpl/provider/releases.rb:111:in `block in push_app'
	from /Users/travis/.rvm/gems/ruby-2.2.9/gems/dpl-releases-1.9.1/lib/dpl/provider/releases.rb:102:in `each'
	from /Users/travis/.rvm/gems/ruby-2.2.9/gems/dpl-releases-1.9.1/lib/dpl/provider/releases.rb:102:in `push_app'
	from /Users/travis/.rvm/gems/ruby-2.2.9/gems/dpl-1.9.1/lib/dpl/provider.rb:194:in `block in deploy'
	from /Users/travis/.rvm/gems/ruby-2.2.9/gems/dpl-1.9.1/lib/dpl/cli.rb:41:in `fold'
	from /Users/travis/.rvm/gems/ruby-2.2.9/gems/dpl-1.9.1/lib/dpl/provider.rb:194:in `deploy'
	from /Users/travis/.rvm/gems/ruby-2.2.9/gems/dpl-1.9.1/lib/dpl/cli.rb:32:in `run'
	from /Users/travis/.rvm/gems/ruby-2.2.9/gems/dpl-1.9.1/lib/dpl/cli.rb:7:in `run'
	from /Users/travis/.rvm/gems/ruby-2.2.9/gems/dpl-1.9.1/bin/dpl:5:in `<top (required)>'
	from /Users/travis/.rvm/gems/ruby-2.2.9/bin/dpl:23:in `load'
	from /Users/travis/.rvm/gems/ruby-2.2.9/bin/dpl:23:in `<main>'
dpl.2
Preparing deploy
dpl.3
Deploying application
failed to deploy

```

## My .travis.yml
```
language: objective-c
osx_image: xcode9.2
rvm:
- 2.2         #see before_install for getting RVM stable.

env:
- TRAVIS_TAG="1.0" PROJECT_NAME="Unity+KinectV2+OpenCV3" UNITY_PROJECT_PATH="Unity+KinectV2+OpenCV3" UNITY_DOWNLOAD_CACHE="$(pwd)/unity_download_cache" DEPLOY_UNITYPACKAGE="path set in deploy script"


cache:
  directories:
    - $UNITY_DOWNLOAD_CACHE

    
before_install:
- rvm get stable
- chmod a+x ./travis-build/*.sh

install:
- cat /etc/hosts
- ./travis-build/install-unity.sh

script:
- ./travis-build/build.sh
- ./travis-build/run-tests.sh

after_success:
- ./travis-build/export-unity-package.sh

before_deploy:
- DEPLOY_UNITYPACKAGE="$(ls -a release/*.zip | head -n 1)"

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: $DEPLOY_UNITYPACKAGE
  skip_cleanup: true
  overwrite: true
  on:
    tags: true 
```

So my deployments work perfectly fine if the resulting release ZIP file does not already exist. Otherwise the deploy fails and stalls for 10 minutes and times out. Yes my travis deployment configuration has `overwrite: true`.

Build log of a successful build (first time, no release files):
https://travis-ci.org/kevinta893/Unity-KinectV2-OpenCV3/builds/354827095

Build log of a deployment stalled build (error on line 4131):
https://travis-ci.org/kevinta893/Unity-KinectV2-OpenCV3/builds/354882792

A repository that doesn't have the issue with multiple success streaks: 
https://github.com/kevinta893/unity3d-travis-ci

**Update: Replicating the issue:**
Midway writing this issue, I just managed to fix my own issue by removing the "+" characters on the zip file that I was trying to upload as a release and it fixed the issue. The deployment system seems to escape the '+' characters into '.' characters the first time around but it fails to afterwards. I'm not sure if there are other characters to escape. 

> Changed my deployment file name from *Unity+KinectV2+OpenCV3-v1.0.zip* to *Unity.KinectV2.OpenCV3-v1.0.zip*

Since changing my output file to use '-' instead, the zip file that I upload through travis' deployment github releases seems to character escape the '-' characters into '.' characters. Infact, if I manually try to upload the same '+' file through the browser on Github releases with an existing release zip file but with escaped characters, Github tells me that the file "An attachment with that filename already exists".

> Attempt to manually upload *Unity+KinectV2+OpenCV3-v1.0.zip* to my Github release that already has a zip *Unity.KinectV2.OpenCV3-v1.0.zip* results in already exists error.

I think Travis-CI didn't catch that file already exists response from the Github servers and decided to abort the deployment despite the configuration having `overwrite: true`.

Edit: fix formatting
Edit: Better formatting
