### ISSUE TITLE
travis say "Not currently on any branch" after deploy when using "on tag"

### ISSUE THREAD

**Issue by HaebinShin** [travis-ci/travis-ci#9364]
I deployed my python package to pypi.

The .travis.yml:
```yml
language: python

python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'

before_install:
- if [ "$TRAVIS_TAG" != "" ]; then sudo apt-get install pandoc; pip install pypandoc;
  fi

install:
- pip wheel --no-deps --wheel-dir=./dist .
- pip install dist/*.whl

before_script:
- pip install ddt

script: python -m unittest discover -s test

before_deploy:
- rm -rf dist/

deploy:
  provider: pypi
  user: ...
  password:
    secure: ...
  on:
    tags: true
    python: '3.6'
    all_branches: true
  distributions: bdist_wheel sdist
```

```sh
git add .
git commit -m "blahblah"
git tag v1.0.5
git push origin tag     # travis deploy at this time
```

It works fine and success deploying. But after deploy it say git error "Not currently on any branch".
https://travis-ci.org/HaebinShin/jamotools/jobs/355509208
```sh
Deploying application
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/jamotools
copying jamotools/__init__.py -> build/lib/jamotools
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/jamotools
copying build/lib/jamotools/__init__.py -> build/bdist.linux-x86_64/wheel/jamotools
running install_egg_info
running egg_info
creating jamotools.egg-info
writing jamotools.egg-info/PKG-INFO
writing dependency_links to jamotools.egg-info/dependency_links.txt
writing requirements to jamotools.egg-info/requires.txt
writing top-level names to jamotools.egg-info/top_level.txt
writing manifest file 'jamotools.egg-info/SOURCES.txt'
reading manifest file 'jamotools.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'jamotools.egg-info/SOURCES.txt'
Copying jamotools.egg-info to build/bdist.linux-x86_64/wheel/jamotools-0.1.5-py3.6.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/jamotools-0.1.5.dist-info/WHEEL
creating '/home/travis/build/HaebinShin/jamotools/dist/jamotools-0.1.5-py2.py3-none-any.whl' and adding '.' to it
adding 'jamotools/__init__.py'
adding 'jamotools-0.1.5.dist-info/DESCRIPTION.rst'
adding 'jamotools-0.1.5.dist-info/metadata.json'
adding 'jamotools-0.1.5.dist-info/top_level.txt'
adding 'jamotools-0.1.5.dist-info/WHEEL'
adding 'jamotools-0.1.5.dist-info/METADATA'
adding 'jamotools-0.1.5.dist-info/RECORD'
running sdist
running check
creating jamotools-0.1.5
creating jamotools-0.1.5/jamotools
creating jamotools-0.1.5/jamotools.egg-info
creating jamotools-0.1.5/test
copying files to jamotools-0.1.5...
copying LICENSE -> jamotools-0.1.5
copying MANIFEST.in -> jamotools-0.1.5
copying README.md -> jamotools-0.1.5
copying setup.cfg -> jamotools-0.1.5
copying setup.py -> jamotools-0.1.5
copying jamotools/__init__.py -> jamotools-0.1.5/jamotools
copying jamotools.egg-info/PKG-INFO -> jamotools-0.1.5/jamotools.egg-info
copying jamotools.egg-info/SOURCES.txt -> jamotools-0.1.5/jamotools.egg-info
copying jamotools.egg-info/dependency_links.txt -> jamotools-0.1.5/jamotools.egg-info
copying jamotools.egg-info/not-zip-safe -> jamotools-0.1.5/jamotools.egg-info
copying jamotools.egg-info/requires.txt -> jamotools-0.1.5/jamotools.egg-info
copying jamotools.egg-info/top_level.txt -> jamotools-0.1.5/jamotools.egg-info
copying test/test_apis.py -> jamotools-0.1.5/test
Writing jamotools-0.1.5/setup.cfg
Creating tar archive
removing 'jamotools-0.1.5' (and everything under it)
Uploading distributions to https://upload.pypi.org/legacy/
Uploading jamotools-0.1.5-py2.py3-none-any.whl
100%|██████████████████████████████████████| 17.6k/17.6k [00:01<00:00, 10.8kB/s]
Uploading jamotools-0.1.5.tar.gz
100%|██████████████████████████████████████| 28.9k/28.9k [00:01<00:00, 21.9kB/s]

Already up to date!
Not currently on any branch.
nothing to commit, working tree clean
Dropped refs/stash@{0} (689c7e927b7842dd0f362020ac8620c384ee6f92)


Done. Your build exited with 0.
```

I don't understand why travis execute git command after deploy.
Is there any way that git error does not show?
