### ISSUE TITLE
Unable to access Docker container from other container

### ISSUE THREAD

**Issue by shiftedreality** [travis-ci/travis-ci#9365]
I'm running Docker on Travis CI with next `docker-compose`

```
version: '2'
services:
...
  cli:
    hostname: cli.magento2.docker
    image: shiftedreality/cloud-docker-php:7.0-cli
    links:
      - db
    volumes_from:
      - appdata
    env_file:
      - ./docker/global.env
      - ./docker/config.env
      - ./docker/composer.env

  web:
    image: shiftedreality/cloud-docker-nginx:1.9
    ports:
      - "8080:80"
    links:
      - fpm
      - db
...
```

And `travis.yml`:
```
sudo: required
dist: trusty
git:
  depth: 1
services:
  - docker
language: generic
...
```

When I try to run `file_get_contents('http://web')` from `cli` container, it throws an error:

```
Warning: file_get_contents(): php_network_getaddresses: getaddrinfo failed: Name or service not known in
```

Locally it works well.
