### ISSUE TITLE
Matrix exclusion fails with multiple passed env variables

### ISSUE THREAD

**Issue by tobiasraabe** [travis-ci/travis-ci#9371]
Hey,

why does the following produce five jobs ([log](https://travis-ci.org/tobiasraabe/r-mice) and [commit](https://github.com/tobiasraabe/r-mice/commit/943d2a80a86ce20f76d103eb97ef140ee20ca022))
````
os:
  - linux
  - osx

env:
  - R_VERSION=r-base CONDA_ARCH=x86
  - R_VERSION=r-base CONDA_ARCH=x86_64
  - R_VERSION=mro-base CONDA_ARCH=x86_64

matrix:
  exclude:
    - os: osx
      env: R_VERSION=mro-base CONDA_ARCH=x86_64
````
whereas this one produces six ([log](https://travis-ci.org/tobiasraabe/r-mice/builds/356424643) and [commit](https://github.com/tobiasraabe/r-mice/commit/29f88c0c84e00d983ea39fb427edf296be7508ae))
````
os:
  - linux
  - osx

env:
  - R_VERSION=r-base CONDA_ARCH=x86
  - R_VERSION=r-base CONDA_ARCH=x86_64
  - R_VERSION=mro-base CONDA_ARCH=x86_64

matrix:
  exclude:
    - os: osx
      env: R_VERSION=mro-base
````
Why do I have to pass both environment variables to the exclude statement? Shouldn't the exclusion be less restrictive or am I missing something?
