### ISSUE TITLE
Ports exposure on tcp4 doesn't work through docker compose

### ISSUE THREAD

**Issue by kenshinji** [travis-ci/travis-ci#9374]
We have a docker container running ElasticSearch, we configured it through `docker-compse.yml` as following. 

```
version: '2'
services:
  elasticsearch:
    build: ./elasticsearch
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - 'esdata:/usr/share/elasticsearch/data'
```

Theoretically the ports 9200 and 9300 should be exposed, however when I check with `netstat -an|grep '9[0-9]00'`. What I can get is as below

```
tcp6       0      0 :::9200                 :::*                    LISTEN     
tcp6       0      0 :::9300                 :::*                    LISTEN    
```
How can I get `9200/9300` exposed through tcp4 on Travis CI?

btw: when I run it locally , ports `9200/9300` could be exposed both on tcp4 and tcp6.
