### ISSUE TITLE
Build Stage environment variable not working

### ISSUE THREAD

**Issue by CodingKoopa** [travis-ci/travis-ci#9420]
I'm having an issue with the build stage environment variable. The [documentation](https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables) says this:
> `TRAVIS_BUILD_STAGE_NAME`: The build stage in capitalzed form, e.g. Test or Deploy. If a build does not use build stages, this variable is empty ("").

My `.travis.yml` does use build stages:
```yml
    # Deploying stage.
    - stage: deploy
      # Deploys documentation to GitHub Pages.
      env: NAME="GitHub Pages Developer Documentation Publish"
      # This stage should only happen on the master branch.
      if: branch = master
      # Use Docker, for a newer Ubuntu container.
      services: docker
      # Install the dependencies.
      install: "./CI/Travis/Linux/InstallDockerDeps.sh"
      # Generate the documentation. The Doxyfile will be configured to quit upon any errors.
      script: "./CI/Travis/Linux/StartDockerDevDocBuild.sh"
      deploy:
        # Use GitHub Pages.
        provider: pages
        # Use the GitHub token specified in the dashboard.
        github-token: $GITHUB_TOKEN
        # Don't delete the build files, because that would remove the documentation.
        skip-cleanup: true
        # Use the built developer documentation.
        local-dir: "Docs/HTML"
```
My `sh` script uses the variable correctly, to my knowledge:
```bash
# If we are not in the deploying stage.
if [ "$TRAVIS_BUILD_STAGE_NAME" != "Deploy" ]; then
  # Disable HTML generation.
  echo "GENERATE_HTML          = NO" >> Doxyfile
fi
```
However, when running the job, the environment variable seems to be empty:
```bash
+ '[' '' '!=' Deploy ']'
+ echo 'GENERATE_HTML          = NO'
+ doxygen
```

Links:
- [Build](https://travis-ci.org/CodingKoopa/mk8studio/builds/360479869). The stage of interest is `Deploy`.
- [travis.yml](https://github.com/CodingKoopa/mk8studio/blob/dbba3539df50218e982817fea93300f5b69a8f68/.travis.yml)
- [Docker container starter script](https://github.com/CodingKoopa/mk8studio/blob/dbba3539df50218e982817fea93300f5b69a8f68/CI/Travis/Linux/StartDockerDevDocBuild.sh)
- [The script itself](https://github.com/CodingKoopa/mk8studio/blob/dbba3539df50218e982817fea93300f5b69a8f68/CI/Travis/Linux/BuildDevDocs.sh)
