### ISSUE TITLE
Multiplatform Build for language: swift always runs on OSX VM

### ISSUE THREAD

**Issue by dastrobu** [travis-ci/travis-ci#9424]
If trying to run Swift project on multiple platforms, i.e. Linux and OSX (macOS), the VM is always an OSX VM. 
The docs state, that different VMs are used, if `sudo: required` is specified. It has, however, no effect. 
I created a sample hello world like repo, illustrating the issue. It can be found [here](https://github.com/dastrobu/swift-travis) 
and the build on travis can be found [here](https://travis-ci.org/dastrobu/swift-travis). 

To summarise, here is the `.travis.yml`: 

```
language: swift
sudo: required
compiler: clang

matrix:
  include:
    - os: linux
      dist: trusty # Ubuntu 14.04 LTS
    - os: osx
      osx_image: xcode9.3beta

before_install:
  - uname -a
  - | 
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update
    fi
script:
  - echo "hello travis!"
```

The build works as expected, if language is set to e.g. `c`. One can of course also run the swift builds with language set to `c`, which is the current workaround. However, it did take me a while to find this workaround and I don't think this is the expected way to run a swift build on Linux and OSX.
