### ISSUE TITLE
Skipping a deployment with the foo provider because this is not a tagged commit

### ISSUE THREAD

**Issue by ssbarnea** [travis-ci/travis-ci#9437]
It seems that Travis lost ability to recognise tagged commits, not sure if this is global or is specific to usage of stages but the result is clear:

* two build are triggered, one for **push** and one for **tagged commit**, as expected
* the tagged commit build skips deploy actions with  messages like:
```
Skipping a deployment with the pypi provider because this is not a tagged commit
Skipping a deployment with the releases provider because this is not a tagged commit
```

Example: https://travis-ci.org/pycontribs/rtox/jobs/361282348 --- As you can observe this build is named "0.0.6" which is the tag name (there is no such branch). There is another sister one that has **master** there, see https://travis-ci.org/pycontribs/rtox/builds/361273273

[`.travis.yml`](https://github.com/pycontribs/rtox/blob/master/.travis.yml#L53) file is configured based on the docs with:
```
jobs:
  include:
  - stage: deploy
    script:
    - export PACKAGE_NAME=$(python setup.py --name)
    - export PACKAGE_VERSION=$(python setup.py --version)
    - make dist
    deploy:
    - provider: pypi
      user: pycontribs
      password:
        secure: ...
      distributions: sdist bdist_wheel
      skip_cleanup: true
      on:
        tags: true
```

When the deploy is reached it skips as it reports no tag, bug we do know very well that this was the tag build.
