### ISSUE TITLE
Logs appear to just stop and nothing happens

### ISSUE THREAD

**Issue by nunogoncalves** [travis-ci/travis-ci#9462]
Hi! 
I have no ideia about what I can do, but my logs get stuck like this: 

https://travis-ci.org/nunogoncalves/iOS-OctoPodium/builds/363973441

It just stops displaying and the build "passes". But my codecov doesn't get to be generated. 

Please help.

This is an iOS project.

Travis.yml:
```yml
language: swift
xcode_workspace: OctoPodium.xcworkspace
xcode_scheme: OctoPodium
osx_image: xcode9.3beta
before_install:
  - pod repo update
script:
  - xcodebuild -workspace OctoPodium.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' -scheme OctoPodium -sdk iphonesimulator -enableCodeCoverage YES ONLY_ACTIVE_ARCH=YES VALID_ARCHS=x86_64 -derivedDataPath build GCC_GENERATE_TEST_COVERAGE_FILES=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES build test | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'OctoPodium'
```

My codecov.yml:
```yml
coverage:
  precision: 2         
  round: down          
  range: 50...100      

  status:
    project:                   
      default:                 
        enabled: yes           
        target: 40%            
                               
                               
        branches:              
        threshold: null        
        if_no_uploads: error   
                               
        if_not_found: success  
        if_ci_failed: error    

    patch:             
      default:
        enabled: yes             
        target: 40%              
        branches: null           
        threshold: null          
        if_no_uploads: error     
                                 
        if_not_found: success
        if_ci_failed: error```
