### ISSUE TITLE
Can't run npm packages bins using `yarn *packagename*`

### ISSUE THREAD

**Issue by kabachook** [travis-ci/travis-ci#9477]
When I try to use scripts from `package.json` like `yarn build` in travis-ci, an error occurres:
```sh
$ yarn build
yarn run v1.3.2
$ cross-env NODE_ENV=production babel src -d dist
/bin/sh: 1: cross-env: not found
```
Dependencies are installed. I've tried adding yarn packages' bins to $PATH, but it doesn't work either.

My config:
```yaml
sudo: required

language: node_js
node_js: "9"

services:
  - docker

cache:
  yarn: true

jobs:
  include:
    - stage: build and test
      script:
        - export PATH=$PATH:`yarn bin`
        - yarn build
        - yarn test
    - stage: build docker image
      script:
        - docker build -t kabachook/telegram-pdf-bot
        - docker run kabachook/telegram-pdf-bot /bin/bash -c "cd /app;export PATH=$PATH:`yarn bin`;yarn test;"
```
Full details: https://travis-ci.org/kabachook/telegram-pdf-bot/jobs/365105727
