### ISSUE TITLE
allow prerelease to be based on a condition

### ISSUE THREAD

**Issue by vladak** [travis-ci/travis-ci#9483]
When using the Github releases, it seems there is no way to set the `prerelease` boolean based on a condition. To be able to generate both pre-release and release I had to basically duplicate the blocks like so:

```
deploy:
  # Pre-release
  - provider: releases
    prerelease: true
    ...
 # Full release
  - provider: releases
    prerelease: true
    ...
```

It would be nice to be able to say something like:

```
    prerelease: "$TRAVIS_TAG =~ rc[0-9]+$"
```
