### ISSUE TITLE
Job with conditional build stages doesn't exclude the stage

### ISSUE THREAD

**Issue by mrchief** [travis-ci/travis-ci#9485]
Trying to get travis to skip release stage for PR/non master branch builds but I can't seem to get the recipe right.

The travis config is listed [here](https://github.com/dowjones/react-dropdown-tree-select/blob/c93afeef9054ab5ee072243aee85bf8a93e7aa5f/.travis.yml)

```
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '8'
  - '6'
before_install:
  - npm install -g npm@5
  - npm install -g greenkeeper-lockfile@1
install:
  - yarn install --ignore-engines
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - yarn coveralls
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  include:
    - if: branch = master
    - stage: release
      node_js: lts/*
      script: echo "Deploying to npm ..."
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
```
I also tried

```
jobs:
  include:
    - stage: release
      if: branch = master
      node_js: lts/*
      script: echo "Deploying to npm ..."
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
```

and

```
jobs:
  include:
    -
      if: branch = master 
    - stage: release
      node_js: lts/*
      script: echo "Deploying to npm ..."
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
```

but travis always executes the release stage - it doesn't run npx semantic-release but it still goes through initializing, running tests etc.

Sample [build](https://travis-ci.org/dowjones/react-dropdown-tree-select/builds/365606501)
