### ISSUE TITLE
Using 'mrkdwn' in a custom Slack template

### ISSUE THREAD

**Issue by tdmalone** [travis-ci/travis-ci#9487]
_Splitting this out from #6930 - original issue is definitely stale but this was a current side problem raised within._

When setting a custom `template` on a Slack notification:

```
  slack:
    rooms:
      - secure: ..........
    template:
      - "Build <%{build_url}|#%{build_number}> %{build_id} (<%{compare_url}|%{commit}>) of %{repository}:%{branch} by %{author} %{result} in %{duration}"
      - "_%{commit_message}_"
      - "*%{message}*"
```

If that template contains 'mrkdwn' (Slack's slightly custom interpretation of markdown), Slack does not render it as such. This is because with message attachments, the Slack API has mrkdwn parsing off by default.

Therefore it would be great if you could send `"mrkdwn_in": [ "text" ]` to the Slack API as one of the [message attachment properties](https://api.slack.com/docs/message-formatting#message_formatting).
