### ISSUE TITLE
Unable to deploy to PyPi from NodeJS environment

### ISSUE THREAD

**Issue by ross-bragg** [travis-ci/travis-ci#9491]
Our developers have a theme for Sphinx that we build with NodeJS and deploy to an internal PyPi server. Sphinx is a Python application, and themes are packaged as Python packages.

We're building the theme itself in a NodeJS language environment without issue, but I'm unable to push this build to our internal PyPi.

If I use the standard Sudo Trusty environment, I get `Couldn't install pip, setuptools, twine or wheel.` and the build outright fails.

If I use one of the edge versions I've found on several issues to get around the issue (edge: branch: v1.8.45 or edge: branch: twine-user-install), python setuptools builds a dist for me but I get `sh: 1: twine: not found` on attempted deployment.

How can I get my python development environment in the right state so that I can deploy the artifact?

The .travis.yml, sanitized:
```
sudo: required
dist: trusty

language: node_js
node_js:
  - "6.1"

before_script:
  - npm install -g gulp

script: gulp preprocess

cache:
  directories:
    - node

deploy:
  skip_cleanup: true
  skip_upload_docs: true
  provider: pypi
  user: nope
  password: nope
  server: nope
  distribution: bdist_wheel
```
