### ISSUE TITLE
How can I ensure that the deploy stage runs EXACTLY ONCE for a given tag?

### ISSUE THREAD

**Issue by dlenski** [travis-ci/travis-ci#9492]
Is there any way to convince Travis-CI not to attempt to run the same `deploy` stage multiple times? (For multiple jobs corresponding to the same commit or tag.)

Here's my problem:

1. My config specifies deployment on every tagged commit:
```yaml
deploy:
  provider: pypi
  user: moxfyre
  password:
    secure: 
      BLAHBLAHBLAH==
  on:
    tags: true
    repo: dlenski/python-zxing
```
2. But it _also_ specifies multiple Python versions, causing Travis to run multiple build jobs for each commit (**desirable**)
4. … but this also causes Travis to attempt to deploy the same version multiple time after each tagged commit (**undesirable**)

This is bad because PyPI (and other deploy providers) reject multiple uploads for the same version… so the second and subsequent builds appear failing, even though all that's really failing is that PyPI is rejecting a repeat upload of the same version of the package.

Two ideas for how to fix this:

* Quick-and-dirty: add an option to ignore `deploy`-stage failures as part of the build status
* Fancier: add an option to the `on`-trigger to ensure that the `deploy` stage never runs more than once for a given commit/tag/whatever, e.g.:

```yml
deploy:
  on:
    tags: exactly_once # instead of true
```
