### ISSUE TITLE
MySQL Access denied for user ''@'localhost' (using password: NO)

### ISSUE THREAD

**Issue by michalderdak** [travis-ci/travis-ci#9517]
I am building integration tests with .NET Core and want to use Travis to execute the tests. Tests are dependent on MySQL database which I try to access trough following connection string `server=127.0.0.1;database=accountdb;uid=root;`

However when the tests are executed following exception is produced `MySql.Data.MySqlClient.MySqlException : Access denied for user ''@'localhost' (using password: NO)`

For some reason the user is not picked up as root user and no matter what I do it always end up with "blank" user

I am not really sure if I am doing something horribly wrong or I came across known issue.

my travis yml:
```
language: csharp
mono: none
sudo: required
dist: trusty
solution: InvoiceManager.sln
dotnet: 2.1.4
services:
  - mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
before_script:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade
  - sudo service mysql restart
  - dotnet build InvoiceManager.sln
script:
  - dotnet test --no-build InvoiceManager.Service.Account.Test/InvoiceManager.Service.Account.Test.csproj
  - dotnet test --no-build InvoiceManager.Service.Invoice.Test/InvoiceManager.Service.Invoice.Test.csproj
  - dotnet test --no-build InvoiceManager.Service.Customer.Test/InvoiceManager.Service.Customer.Test.csproj
notifications:
  email: false
```

Thank you for any feedback
