### ISSUE TITLE
Cleaner script arguments

### ISSUE THREAD

**Issue by YakDriver** [travis-ci/travis-ci#9521]
It would be great if there were a cleaner way to pass arguments to a deploy script. If there is already, treat this as a question. Otherwise, this is an enhancement request.

The current script argument mechanism is harder to maintain than the regular YAML key/values. If there is a reasonable length of arguments, it becomes a mess. _[This API key does not correspond to anything useful.]_

```yaml
deploy:
  - provider: script
    script: python release_script.py tag_name="$VERSION" release_body="$BODY" secure_api_key="D/CSApheY3BplCUXb4jyR8NrPIHnwUJNrADjq1ZkfvtMNYl7Vu7gbnQCtLkt9HyXzKgiaeIcK4DBxmZ7Esong0kdcdmnLnUX2gTDp4kg09mXKgpI1ItosdQL1N+gNSO4IQgRdeK6WM6WuPVPbsjRGFwtFz+EjX3Iz8qoDuw+WAY/jAjR0Lte+IqGFinZp5vwCm0yG8cSEZ890fqtudwmTyJL+WtMg3UoY9xnNqMVKrT8nXuNDq+gbDUQZXSsfC5iAkOFF6r5D2qlXlUios/C+h/pVZ8v8mVI/JK/SuGfTwq8QewPjMx1+tChgmyCYcmM6FdwBwsKKx7uw1q2qm4wJMIoY/G53wEQQc2jVczx1HxIn86McWGx6FTx9eqatHI4njHJ/iw+Uv7HESb2SxeG6z5GiIls0gVTNMYfpLjxIJfvqUd68IdYD8ZMEThD7ZeeX0H2nvCxE8aD+7UOj2bUzRUemulvk74cGdIexeBxCAYt9bWx5NNyCjoBHo1AZzHOzaRbBhuU/533wb7n+nZFXPozGapb+A1XDjWWNCRxgkq/6SatVMRxO03eV3m0Cz34YStYF299BILcdbmcyozTCXfoqg31wldmZSEtHPPXX0Il8DW+/YdrCgW5dlV96kkBJNLI1eI8cKRImHsV85cjSwmPlIlaXmNkOWFOVkRC+kQ=" 
    skip_cleanup: true
    on:
      branch: master
      repo: YakDriver/mjukvarulage
      condition: '"$TOXENV" == *"py36"*'
```

Instead, I would expect to be able to specify key/values in the `.travis.yml` under the `deploy.provider: script` collection and have Travis CI pass the key/values as arguments to the script or populate them as environment variables. Basically, anything Travis doesn't use, pass as an argument to the script, or provide a sub-collection under `deploy.script` for arguments.

```yaml
deploy:
  - provider: script
    script: python release_script.py
    skip_cleanup: true
    tag_name: $VERSION
    release_body: $BODY
    abc_xyz: $ALL_PASSED 
    api_key:
      secure: D/CSApheY3BplCUXb4jyR8NrPIHnwUJNrADjq1ZkfvtMNYl7Vu7gbnQCtLkt9HyXzKgiaeIcK4DBxmZ7Esong0kdcdmnLnUX2gTDp4kg09mXKgpI1ItosdQL1N+gNSO4IQgRdeK6WM6WuPVPbsjRGFwtFz+EjX3Iz8qoDuw+WAY/jAjR0Lte+IqGFinZp5vwCm0yG8cSEZ890fqtudwmTyJL+WtMg3UoY9xnNqMVKrT8nXuNDq+gbDUQZXSsfC5iAkOFF6r5D2qlXlUios/C+h/pVZ8v8mVI/JK/SuGfTwq8QewPjMx1+tChgmyCYcmM6FdwBwsKKx7uw1q2qm4wJMIoY/G53wEQQc2jVczx1HxIn86McWGx6FTx9eqatHI4njHJ/iw+Uv7HESb2SxeG6z5GiIls0gVTNMYfpLjxIJfvqUd68IdYD8ZMEThD7ZeeX0H2nvCxE8aD+7UOj2bUzRUemulvk74cGdIexeBxCAYt9bWx5NNyCjoBHo1AZzHOzaRbBhuU/533wb7n+nZFXPozGapb+A1XDjWWNCRxgkq/6SatVMRxO03eV3m0Cz34YStYF299BILcdbmcyozTCXfoqg31wldmZSEtHPPXX0Il8DW+/YdrCgW5dlV96kkBJNLI1eI8cKRImHsV85cjSwmPlIlaXmNkOWFOVkRC+kQ=
    on:
      branch: master
      repo: YakDriver/mjukvarulage
      condition: '"$TOXENV" == *"py36"*'
```
An alternate implementation:
```yaml
deploy:
  - provider: script
    script: python release_script.py
    arguments: {
      tag_name: $VERSION,
      release_body: $BODY,
      abc_xyz: $ALL_PASSED,
      api_key:
        secure: D/CSApheY3BplCUXb4jyR8NrPIHnwUJNrADjq1ZkfvtMNYl7Vu7gbnQCtLkt9HyXzKgiaeIcK4DBxmZ7Esong0kdcdmnLnUX2gTDp4kg09mXKgpI1ItosdQL1N+gNSO4IQgRdeK6WM6WuPVPbsjRGFwtFz+EjX3Iz8qoDuw+WAY/jAjR0Lte+IqGFinZp5vwCm0yG8cSEZ890fqtudwmTyJL+WtMg3UoY9xnNqMVKrT8nXuNDq+gbDUQZXSsfC5iAkOFF6r5D2qlXlUios/C+h/pVZ8v8mVI/JK/SuGfTwq8QewPjMx1+tChgmyCYcmM6FdwBwsKKx7uw1q2qm4wJMIoY/G53wEQQc2jVczx1HxIn86McWGx6FTx9eqatHI4njHJ/iw+Uv7HESb2SxeG6z5GiIls0gVTNMYfpLjxIJfvqUd68IdYD8ZMEThD7ZeeX0H2nvCxE8aD+7UOj2bUzRUemulvk74cGdIexeBxCAYt9bWx5NNyCjoBHo1AZzHOzaRbBhuU/533wb7n+nZFXPozGapb+A1XDjWWNCRxgkq/6SatVMRxO03eV3m0Cz34YStYF299BILcdbmcyozTCXfoqg31wldmZSEtHPPXX0Il8DW+/YdrCgW5dlV96kkBJNLI1eI8cKRImHsV85cjSwmPlIlaXmNkOWFOVkRC+kQ=
    }
    skip_cleanup: true
    on:
      branch: master
      repo: YakDriver/mjukvarulage
      condition: '"$TOXENV" == *"py36"*'
```
For now, it seems that the workaround is to set environment variables in `before_deploy` and then access those environs from the script. This is cleaner but suffers from documentation/maintainability defects since it is not immediately clear which values the script relies on when looking at the YAML.
