### ISSUE TITLE
Confused on Build Matrix Configuration

### ISSUE THREAD

**Issue by aarongodin** [travis-ci/travis-ci#9523]
Hello! Apologies if this is not the place to ask questions, but I believe I have a pretty straightforward use case that could also be a bug.

I'm using `node_js` as my language and wanted to run the build across three versions of node. I've done this before and knew it was straightforward, but I couldn't get it to work using this config:

```yaml
langauge: node_js
node_js: 
  - "7.6"
  - "8"
  - "9"
```

After trying other methods, I ended up with a verbose version that works:

```yaml
langauge: node_js
matrix:
  include:
  - node_js: "7.6"
  - node_js: "8"
  - node_js: "9"
```

Here is a link to my full config:

https://github.com/aarongodin/turnup/blob/0632db9653161a6a4f10a3cf2b4734b7486650ec/.travis.yml

What's strange to me is that `ruby` is inferred as an additional language from my config. For example, the config in travis looks like this:

```json
{
  "os": "linux",
  "dist": "trusty",
  "cache": {
    "yarn": true
  },
  "group": "stable",
  "script": [
    "yarn run lint",
    "yarn test"
  ],
  "install": [
    "yarn"
  ],
  "node_js": "7.6",
  "langauge": "node_js",
  "language": "ruby"
}
```

Am I missing something, or is there a value in my config that is causing travis to use ruby? I believe this is why it wasn't inferring the matrix from the `node_js` key.
