### ISSUE TITLE
 Can't build and test (Warning: License for package Android SDK Build-Tools 27.0.3 not accepted.)

### ISSUE THREAD

**Issue by Anastat** [travis-ci/travis-ci#9536]
I have the next log report:

Warning: License for package Android SDK Build-Tools 27.0.3 not accepted.
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':app'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     build-tools;27.0.3 Android SDK Build-Tools 27.0.3

I tried to resolve the problem by adding:
before_install: 
    - yes | sdkmanager "platforms;android-27"

but it doesn't work. How can I fix it?
 
https://travis-ci.org/Anastat/StudyCardsApp/jobs/370725879

Thank you in advance

**Comment by kfieldi5** [comment]
In your .travis.yml, if you have your components set properly, build tools 27.0.3 will work. Also make sure your licenses section allows sdk-preview, sdk, and gdk licenses:

```
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - android-$EMULATOR_API
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-$ANDROID_API
  - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API
  - sys-img-armeabi-v7a-android-$EMULATOR_API
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
```
