### ISSUE TITLE
Add ability to test with multiple Postgres (databases?) versions

### ISSUE THREAD

**Issue by vitorbaptista** [travis-ci/travis-ci#954]
I'm setting this up for https://github.com/okfn/ckan, but it would be great if there was an easier way to do it. Something like:

``` yaml
language: python
postgres:
    - "8.4"
    - "9.0"
    - "9.1"
...
```

The same could be used for another databases. As in:

``` yaml
database:
    postgres:
        - "8.4"
        - "9.1"
    mysql:
        - "5.6"
```

Do you think it would be useful? If so, I would love to work on it :smile: 

Cheers!

**Comment by strk** [comment]
Did anything change about the possibility to use different PostgreSQL versions in  a build matrix ?
Or how did you solve the problem @vitorbaptista ?

**Comment by voltechs** [comment]
This seems like a very critical and necessary "feature" for any Continuous Integration offering.

**Comment by BanzaiMan** [comment]
Just a side point:

A possible workaround would be to use `env`, along with `sudo: required`. For example:

```yaml
language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'
env:
  - POSTGRESQL_VERSION = 9.5
  - POSTGRESQL_VERSION = 9.6
before_install:
  - sudo service postgresql stop && sudo service postgresql start $POSTGRESQL_VERSION
⋮
```
