### ISSUE TITLE
deploying to ELB

### ISSUE THREAD

**Issue by lapots** [travis-ci/travis-ci#9544]
Hi there!

I am trying to deploy to AWS Elasticbeanstalk.

```
deploy:
      provider: elasticbeanstalk
      access_key_id: $aws_access_key_id
      secret_access_key: $aws_secret_access_key
      region: "eu-central-1"
      app: "judge-rule-engine"
      env: "judge-rule-engine-env"
      bucket-name: "deploy-app-bucket"
```

But it deploys it with the names like this

    travis-0b554a97e42e587bea4fdc059802092d01f38ab1-1524768477.zip

How to change the name?

**Comment by BanzaiMan** [comment]
This is described in https://docs.travis-ci.com/user/deployment/elasticbeanstalk#Optional-settings.

**Comment by lapots** [comment]
I tried it like this
```
deploy:
  provider: elasticbeanstalk
  access_key_id: $aws_access_key_id
  secret_access_key: $aws_secret_access_key
  region: "eu-central-1"
  app: "judge-rule-engine"
  env: "judge-rule-engine-env"
  bucket-name: "deploy-app-bucket"
  zip_file: latest.zip
  skip_cleanup: true
```
but get this error

```
/home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-elastic_beanstalk-1.9.6/lib/dpl/provider/elastic_beanstalk.rb:127:in `initialize': No such file or directory @ rb_sysopen - /home/travis/build/lapots/judge-rule-engine/latest.zip (Errno::ENOENT)
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-elastic_beanstalk-1.9.6/lib/dpl/provider/elastic_beanstalk.rb:127:in `open'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-elastic_beanstalk-1.9.6/lib/dpl/provider/elastic_beanstalk.rb:127:in `open'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-elastic_beanstalk-1.9.6/lib/dpl/provider/elastic_beanstalk.rb:127:in `upload'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-elastic_beanstalk-1.9.6/lib/dpl/provider/elastic_beanstalk.rb:49:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/provider.rb:194:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/provider.rb:194:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.6/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
```
