### ISSUE TITLE
Conditional secure environment variables

### ISSUE THREAD

**Issue by rsimha** [travis-ci/travis-ci#9548]
I'm trying to set up conditional jobs for our project. Specifically, I'd like to add a secure environment variable  (let's call it `FOO=foo`) for just a certain subset of our push builds. 

**Here's what I'm doing:**
1. Travis encrypt `FOO=foo`
```
travis encrypt FOO=foo
secure: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=
```
2. Add it to `.travis.yml`
```
matrix:
  include:
    - if: <condition for non-master push build>
      env:
        - secure: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=
        - BAR="bar"
    - if: <some other condition>
      <etc.>
```

**Here's what I'm seeing in the Travis logs:**
```
Setting environment variables from .travis.yml
$ export xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=[secure]
$ export BAR="bar"
```

**Here's what I'm expecting to see in the Travis logs:**
```
Setting environment variables from .travis.yml
$ export FOO=[secure]
$ export BAR="bar"
```

Am I doing it wrong? Or is this unsupported? If so, how does one add secure environment variables in just a subset of push builds?

For context, I'm trying to do so because of the problem you describe in https://github.com/travis-ci/travis-ci/issues/7967#issuecomment-384148738, which is making our logs on `master` unreadable. The secure variable in our repo settings are not used for `master` builds, and are only used in a small subset of push builds from non-master branches.

**Comment by rsimha** [comment]
It turns out that there's a workaround to this, that involves encrypting all env vars...
```
travis encrypt FOO=foo BAR=bar
secure: xxxxxxxxxxxxxxxxxxxxxxxxxxxyyyyyyyyyyyyyyyyyyyyyyyyyyy=
```
... and including just one secure `env` entry under each condition...
```
matrix:
  include:
    - if: <condition for non-master push build>
      env:
        secure: xxxxxxxxxxxxxxxxxxxxxxxxxxxyyyyyyyyyyyyyyyyyyyyyyyyyyy=
    - if: <some other condition>
      <etc.>
```

Leaving this issue up, since the original issue remains, where it's not possible to have _some_ encrypted env vars under a conditional job.
