### ISSUE TITLE
Running "echo 1234 | grep -o '\w[0-9]+\w'" makes a Python .travis.yml run as if it was Ruby

### ISSUE THREAD

**Issue by vitorbaptista** [travis-ci/travis-ci#955]
Hi,

I've just stumbled upon a bug. I was changing my .travis.yml, and it got like this:

``` yaml
language: python
python:
  - "2.7"
env:
  - DBVERSION=9.1
  - DBVERSION=8.4
before_install:
  - sudo add-apt-repository -y ppa:pitti/postgresql
  - sudo apt-get update -qq
install:
  - "sudo apt-get install postgresql-$DBVERSION"
before_script:
  - "echo 1234 | grep -o '\w[0-9]+\w'"
script: pg_lsclusters
```

Then, suddenly, Travis started building it as if it was Ruby, and ignoring the build matrix (multiple DBVERSIONs). Check https://travis-ci.org/vitorbaptista/ckan/builds/5175060.

After a few tests, I could pinpoint the culprit for the regexp in grep. If I change this:

``` diff
diff --git a/.travis.yml b/.travis.yml
index e7e2afc..414edc8 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -9,7 +9,7 @@ before_install:
   - sudo apt-get update -qq
 install:
   - "sudo apt-get install postgresql-$DBVERSION"
-  - "echo 1234 | grep -oE '\w[0-9]+\w'"
+  - "echo 1234 | grep -o '2'"
 before_script:
   - echo $DBPORT
 script: pg_lsclusters
```

it starts running correctly (check https://travis-ci.org/vitorbaptista/ckan/builds/5175009).
