### ISSUE TITLE
build stage condition

### ISSUE THREAD

**Issue by Midnighter** [travis-ci/travis-ci#9551]
I'm having a problem with setting a condition on a build stage.

On Friday, on one repo I successfully used a condition on my deploy stage, like so

```yaml
stages:
  - test
  - name: deploy
    if: (repo = env(GITHUB_REPO)) AND (tag IS present)
```

Today on a different repo I tried the same plus after the condition had no effect additionally with a pattern on the tag, as follows

```yaml
stages:
  - test
  - name: deploy
    if: ( repo = env(GITHUB_REPO) ) AND ( tag IS present ) AND ( tag =~ ^\d+\.\d+\.\d+[a]?\d*$ )
```

but the deploy stage always runs... Did anything change? I just tried again today on the first repo and it also includes the deploy stage but did not before.

It's not a huge deal since I still use deploy conditions but it shouldn't happen.

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!

**Comment by Midnighter** [comment]
[Here you can see a normal commit to master without a tag which should not have a deploy stage.](https://travis-ci.org/Midnighter/dependency-info/builds/372692184)

**Comment by Midnighter** [comment]
This is still happening to me. Any clues? Does it depend on the definition of the deploy stage itself?

**Comment by BanzaiMan** [comment]
I think this is a bug that we recently fixed https://changelog.travis-ci.com/fixed-conditions-using-global-environment-variables-61017. Could you try pushing another commit?

Thanks.

**Comment by Midnighter** [comment]
There was a build just a few minutes ago where [it didn't work out](https://travis-ci.org/opencobra/memote/builds/384746831) as expected. The `.travis.yml` is below. Am I doing something fundamentally wrong in the config?

```yaml
language: python
node_js: "node"
os:
  - linux
python:
  - "3.6"
  - "3.5"
  - "2.7"
sudo: false
git:
  depth: 2
cache:
- pip: true
- directories:
  - "memote-report-app/node_modules"
branches:
  only:
  - master
  - develop
  - "/^\\d+\\.\\d+\\.\\d+[a]?\\d*$/"
env:
  global:
    - GITHUB_REPO=opencobra/memote
matrix:
  fast_finish: true
install:
- make reports
- pip install -U pip setuptools wheel tox tox-travis
script:
- travis_wait tox
after_success:
- pip install -U codecov
- codecov

stages:
  - test
  - name: deploy
    if: (repo = env(GITHUB_REPO)) AND (tag IS present)

jobs:
  include:
    - stage: deploy
      install: skip
      script:
        - make reports
        - pip install -U pip setuptools wheel
      after_success:
        - pip --version
      deploy:
        - provider: pypi
          skip_cleanup: true
          distributions: sdist bdist_wheel
          user: midnighter
          password:
            secure: kNj5W/9vLd77d9FXEi8QZxb+8NDJzqDQYrIrrqq5tqqVRcBt/PAkMQ5PrwuBeNxNJALun8RSM2Mq/hDYijQ6lqxyFMpECKXmtDXb5OeMgQvQ5y96OHo0VXqoA1nELdJJp6lHKUxKaH75bfp9s7506n9teHUvlGdP0eE+E17XtRax5zuWv/IOqolF//mT6TzdKIIMrnZFZ2XxxNYuqk7GNym7ywccuZNNRSLJn6lKEAYlsGUQlm76YbGSSvrDKMfTrB2nChzrjEzsfpPUZJfdqSjz8vjJgyLgGZhMJ/hfWM3i6buaAhpvxsVW9SXbUA9DTfQkMOUKd3RmhE6HgOp9Bd04g4oY7e7v72b3Agiz7H2edJCrtLlVMTS5uzqqzgoL0lfYfu3dn/g8xxla3FeQy2GFDdDmEJ3XhFTgUyLKhW8CCjmEX4Fgi0bf2CUqt/NXK3JU2iSrFndpvRfD+BvA3WCfPX5IhwSOkYh1HESxhc6POPw2hYj8L/Gpa30sbGh8XMTMW7mKp9se6xy/vfNVxB0J7fnKyh94API7U32Zsuw4CVIU/FXrgkjvZf7DR2lM0KXDKldixsyhyEbo3IdOkg5GHZE+PiREmUFioOAZfxD+GrcTj4Xw53WhDu2wi4RtH5J21PhdNDzM61gK1iiSSDt9At6XnJkHDz1z7jdDt0E=
          on:
            tags: true
            repo: $GITHUB_REPO
        - provider: releases
          skip_cleanup: true
          api_key: $GITHUB_TOKEN
          body: "Please see https://github.com/${GITHUB_REPO}/blob/${TRAVIS_TAG}/HISTORY.rst for the full release notes."
          on:
            tags: true
            repo: $GITHUB_REPO
        - provider: script
          skip_cleanup: true
          script: ci/travis/update_docker.sh
          on:
            tags: true
            repo: $GITHUB_REPO
notifications:
  email: false
  slack:
    secure: udevSzdcN71zqk9Y8Rev5zrf7gjHWdLQPMbz30YXrUD3uK2i4ofvXIKJhwctchFfqjxNQlm57QOb3YDksaiizHGskx7ljnEGPrrDoVBnTG7wI/wcw6JcTDOII9klA+sp/yMKniuBYHML5U7xiEuNpMblgnUg1P/q9qcoNDIgli1uS6ftzuq242kMDcPxf+L4XOvK8SLukfVUjAKqLJoywPvJ6hqcJPbfIRRBpCGSMRpbPbkoju7aFt7Maz4VY5CpKqPRNodldxyzn3ZvPQvdAPX0o5UW3ioF7b5/CCbPJNhREQvzWdAJlJP9tZYXkTBrGDrFNEEjaCHhUbkCVL5BhndGz4W+guWCXx+gOhQ/imdqVlfXYOnl9/StquhHF7Uc3aYJZ1uzHW1WAm1cyfYjemiORawVgswv1jPtxB4Fa474DPOMCIX6qGeck0CuS/gGn+NlitWdypggTK8PyN+SCH+vS/brJ/+OPpr5lj1UHd9qeI4O8OntZbxZgJH8saCzULVh/FszSusLJ61djlX6tn2fCvNnOxR1FdhaPvR3srKxhAOH2RpLm3kTVFAHf5a28umIRNK79M7KZUEbap+7GlH2dCtb23pVToUngdGc6paZ/RDe8qeZbG4obLbRCnX/VvWNlgHlYo5SMr3vhawmf/ErJDWQbc5ZuhhVRm3L/4g=
    on_success: never
    on_failure: always
    on_pull_requests: false
```
