### ISSUE TITLE
Travis-ci not posting to slack notification when build fails

### ISSUE THREAD

**Issue by mkendall07** [travis-ci/travis-ci#9553]
I can't seem to configure travis-ci to post failures to slack. I've configured like so:
```
notifications:
  slack:
    on_success: never
    on_failure: always
    on_pull_requests: false
    secure: <secure_key>
```

This previously was posting all build results regardless of build results ( fail, pass). Now it has stopped posting any build statuses. 

Here is a link to the config:
https://github.com/prebid/Prebid.js/blob/master/.travis.yml#L24

Please let me know if any additional information would be helpful and I can provide it. Thanks

**Comment by mkendall07** [comment]
Anyone else having this issue?  Any workarounds?

**Comment by BanzaiMan** [comment]
Your configuration appears incorrect. https://docs.travis-ci.com/user/notifications#Configuring-Slack-notifications

If you want to encrypt the channel, you'll need:

```yaml
notifications:
  slack:
    rooms:
      - secure: "sdfusdhfsdofguhdfgubdsifgudfbgs3453durghssecurestringidsuag34522irueg="
    on_success: always
```

Please see https://docs.travis-ci.com/user/notifications#Configuring-Slack-notifications.
