### ISSUE TITLE
Something odd about /tmp (permission denied)

### ISSUE THREAD

**Issue by eed3si9n** [travis-ci/travis-ci#9572]
## steps

https://travis-ci.org/eed3si9n/sbt/jobs/375126481 (installing OpenJDK 10 using `jabba`)

```yaml
matrix:
  include:
  - env: SBT_CMD="scripted java/*"
    before_install:
      - curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.9.4/install.sh | bash && . ~/.jabba/jabba.sh
    install:
      - /home/travis/.jabba/bin/jabba install openjdk@1.10
```

## problem

I get "permission denied" but not consistently.

```
49.45s$ /home/travis/.jabba/bin/jabba install openjdk@1.10
Downloading openjdk@1.10.0 (https://download.java.net/java/GA/jdk10/10.0.1/fb4372174a714e6b8c52526dc134031e/10/openjdk-10.0.1_linux-x64_bin.tar.gz) 
204885801/204885801
Extracting /tmp/jabba-d-024696137 to /home/travis/.jabba/jdk/openjdk@1.10.0 
open /home/travis/.jabba/jdk/openjdk@1.10.0/legal/java.base/ADDITIONAL_LICENSE_INFO: permission denied 
```

See https://travis-ci.org/eed3si9n/sbt/jobs/375120874/config. I have the same thing and it works:

```
50.09s$ /home/travis/.jabba/bin/jabba install openjdk@1.10
Downloading openjdk@1.10.0 (https://download.java.net/java/GA/jdk10/10.0.1/fb4372174a714e6b8c52526dc134031e/10/openjdk-10.0.1_linux-x64_bin.tar.gz) 
204885801/204885801
Extracting /tmp/jabba-d-316696575 to /home/travis/.jabba/jdk/openjdk@1.10.0 
openjdk@1.10 -> /home/travis/.jabba/jdk/openjdk@1.10.0 
```

## expectation

Files can be written to `/tmp/foo` and can be read without `sudo`.

## note

Using `sudo: required` seems to workaround this. But since it does work sometimes, I am guessing this is some kind of anomaly in the container environment.

I am also seeing potentially related issue in https://travis-ci.org/sbt/sbt/builds/375103023 (integration test of sbt) that downloads jars to /tmp/sbt-something/...` would fail. For that I am working around by downloading into some hardcoded directory under `/home/travis/`.

The common theme seems to be download something to a directory under `/tmp` and using it.
