### ISSUE TITLE
Unsupported docker-compose.yml version

### ISSUE THREAD

**Issue by alaxalves** [travis-ci/travis-ci#9573]
I'd like to be able to use version: '3.5' in my docker-compose.yml file, but travis outputs the following log: 
![image](https://user-images.githubusercontent.com/19597045/39665298-db425c7a-5067-11e8-9042-071721258bd9.png)

How can I fix this??

**Comment by alaxalves** [comment]
My docker-compose.yml

```yml
version: '3.5'
services:

  db:
    container_name: falko-database
    image: postgres:9.6
    networks:
      - falko-backend

  api:
    container_name: falko-api
    image: alaxalves/api:1.7
    command: ["sh", "scripts/sh/start-dev.sh"]
    environment:
      - CLIENT_ID=1254ef5e2765397c4fb4
      - CLIENT_SECRET=c566f60e74a49bd8e664033e2978a31d3b39748d
    volumes:
      - .:/Falko-2017.2-BackEnd
      - bundle-cache:/bundle-cache
    networks:
      - falko-backend
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  bundle-cache:

networks:
  falko-backend:
    name: falko-backend
```
