### ISSUE TITLE
Python script with 'sudo' and ImportError

### ISSUE THREAD

**Issue by networkop** [travis-ci/travis-ci#9588]
I need to use sudo in my test scripts, but when I do that it looks like the worker can't import the libraries installed by `pip install` during the install stage:
```
ImportError: No module named 'yaml'
```

I've tried adding both `pip install` and `sudo pip install` as shown below but there's no difference.
As soon as I remove `sudo` from in front of my script - everything works fine.

```yaml
language: python
python:
  - 3.6
sudo: required
install:
  - pip install git+https://github.com/networkop/arista-ceos-topo.git@dev
  - sudo pip install git+https://github.com/networkop/arista-ceos-topo.git@dev
jobs:
  include:
    - stage: Version 1 testing
      script:
        - sudo test/v1/v1-t1.sh
```

https://travis-ci.org/networkop/arista-ceos-topo/jobs/376257618
