### ISSUE TITLE
Add support for .NET Core SDK 2.1.300-RC1

### ISSUE THREAD

**Issue by olegburov** [travis-ci/travis-ci#9596]
Hi @joshua-anderson, @akoeplinger and @nterry

Could you please add support for [.NET Core SDK 2.1.300-rc1 ](https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.300-rc1)(`2.1.300-rc1-008673`)?

Currently I'm getting this error:
```
2.1.300-rc1-008673 is either an invalid version of dotnet or unsupported on this operating system.
View valid versions of dotnet at https://docs.travis-ci.com/user/languages/csharp/
```
When my `.travis.yml` file looks like:

```yml
language: csharp 
dist: trusty
mono: none
dotnet: 2.1.300-rc1-008673
branches:  
  only:  
    - master
before_script: cd src
script:  
  - dotnet restore 
  - dotnet build
```
