### ISSUE TITLE
Do not run after_script after deploy stage

### ISSUE THREAD

**Issue by SevenOutman** [travis-ci/travis-ci#9606]
Hi team, firstly thanks for your great service! 
I'm recently trying out the beta stage feature, and got confused by its flow. I have an `after_script` which runs `coverall` for my test config. I found that it also runs after my deploy stage finishes, which I don't expect. How can I prevent that?

Here's my build log:
```bash
$ echo "Deploying to NPM ..."
Deploying to NPM ...
The command "echo "Deploying to NPM ..."" exited with 0.
...
Preparing deploy
Deploying application
$ npm run coveralls
```

And here's my .travis.yml:
```yml
language: node_js
node_js:
  - 7.2.1

env:
  - BROWSER=ChromeCi
  - BROWSER=Firefox

cache:
  directories:
    - node_modules

after_script:
    - npm run coveralls

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

on:
  branch: master
  tags: true

jobs:
  include:
    - stage: "NPM publish"
      deploy:
        provider: npm
        email: "xxxx"
        api_key: $NPM_AUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true
```
