### ISSUE TITLE
Conditional Job overwrites default script

### ISSUE THREAD

**Issue by mrchief** [travis-ci/travis-ci#9614]
For PR builds with conditional build stages, the default script gets overwritten, even if the job condition is false. 

See the job and its config:

https://travis-ci.org/dowjones/react-dropdown-tree-select/jobs/378516103

https://github.com/dowjones/react-dropdown-tree-select/blob/e13defbe2233f23a45cd8a56a6fcd8b50bcc7252/.travis.yml

Job config on travis-ci
```
{
  "if": "branch = master",
  "os": "linux",
  "git": {
    "depth": 3
  },
  "dist": "trusty",
  "jobs": {
    "include": [
      {
        "if": "branch = master",
        "stage": "release",
        "deploy": {
          "script": [
            "npx semantic-release"
          ],
          "provider": "script",
          "skip_cleanup": true
        },
        "script": "echo \"Deploying to npm ...\"",
        "node_js": "lts/*"
      }
    ]
  },
  "cache": {
    "directories": [
      "node_modules"
    ]
  },
  "group": "stable",
  "stage": "release",
  "script": "echo \"Deploying to npm ...\"",
  "install": [
    "yarn install --ignore-engines"
  ],
  "node_js": "lts/*",
  "language": "node_js",
  "after_script": "greenkeeper-lockfile-upload",
  "before_script": "greenkeeper-lockfile-update",
  "before_install": [
    "npm install -g greenkeeper-lockfile@1"
  ]
}
```

**Comment by BanzaiMan** [comment]
This PR https://github.com/dowjones/react-dropdown-tree-select/pull/102 has the base branch `master`, so [this build](https://travis-ci.org/dowjones/react-dropdown-tree-select/builds/378516102)'s "branch" value is set to "master". So your conditional job is added to the build, and this is one that is getting executed. In the configuration, you are [overriding `script`](https://github.com/dowjones/react-dropdown-tree-select/blob/e13defbe2233f23a45cd8a56a6fcd8b50bcc7252/.travis.yml#L27), so this should be expected.

What might not be expected is that there is only one job in this build. This is due to your configuration having _exactly_ one job without the "Jobs". (See https://github.com/travis-ci/travis-ci/issues/4681#issuecomment-304919767 for more details.)

I suggest something like this instead:

```yaml
language: node_js
cache:
  directories:
    - node_modules
git:
  depth: 3
jobs:
  include:
    - stage: test
      node_js:
        - '8'
      before_install:
        - npm install -g greenkeeper-lockfile@1
      install:
        - yarn install --ignore-engines
      before_script: greenkeeper-lockfile-update
      after_script: greenkeeper-lockfile-upload
      script:
        - yarn coveralls
      branches:
        except:
          - /^v\d+\.\d+\.\d+$/
    # Define the release stage that runs semantic-release
    - stage: release
      if: branch = master
      node_js: lts/*
      # overwrite default `script` step to skip the tests
      script: echo "Deploying to npm ..."
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
```
