### ISSUE TITLE
password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by Dmitry-N-Medvedev** [travis-ci/travis-ci#9624]
hi!

I'm stuck a bit with connecting to postgres. Looked at stackoverflow - no luck.

here's my travis.yml part:
```yml
env:
  global:
    - PGPORT=5433
    - PGDATABASE=fcg
    - PGUSER=postgres
    - PGHOST=localhost
```

here's the error message:
```bash
(node:7203) UnhandledPromiseRejectionWarning: Error: Error creating database. Caused by: 'error: password authentication failed for user "postgres"'
    at createDb (/home/travis/build/frontier-car-group/sys/node_modules/postgres-migrations/src/create.js:44:15)
```

any hint will be greatly appreciated

**Comment by Dmitry-N-Medvedev** [comment]
> From the error itself and the timing of this issue, is it correct to assume that this is happening while trying to use Postgres 10?

yes, that's correct

> It would be useful if you could point us to a build in which this is happening.

please, have a look here: https://travis-ci.org/frontier-car-group/sys/builds/379389110

> To sort out these authentication issues with the postgres user, I recommend using the following additional configuration

I will try right away and report the result! thank you!

**Comment by Dmitry-N-Medvedev** [comment]
@iriberri please see succeeded build: https://travis-ci.org/frontier-car-group/sys/builds/379819390

**Comment by iriberri** [comment]
Awesome, thanks for testing @Dmitry-N-Medvedev! I'll go ahead and close this issue then, since the auth problem itself will be fixed when we include Postgres 10 in the images. To track this release, I'd recommend subscribing to: https://github.com/travis-ci/travis-ci/issues/8537

**Comment by cjancsar** [comment]
This should be added to https://docs.travis-ci.com/user/database-setup/#using-a-different-postgresql-version as the instructions there are incomplete.

**Comment by jcoleman** [comment]
@iriberri Could we get this added to the docs per @cjancsar's comment above? Currently the docs say you can use Postgres from apt, but don't say anything about needing this additional config.

**Comment by jcoleman** [comment]
FWIW I had to do the following to get it to work:

```
matrix:
  include:
    - addons:
        postgresql: "9.6"
    - addons:
        postgresql: "10"
    - addons:
        postgresql: "11"
        apt:
          packages:
            - postgresql-11
            - postgresql-client-11
            - postgresql-server-dev-11
            - postgresql-client-common
            - postgresql-common
      env:
        PGPORT: "5433"
        PGVERSION: 11
    - addons:
        postgresql: "12"
        apt:
          packages:
            - postgresql-12
            - postgresql-client-12
            - postgresql-server-dev-12
            - postgresql-client-common
            - postgresql-common
      env:
        PGPORT: "5433"
        PGVERSION: 12

services:
  - postgresql
before_install:
  - "if [ ! -z $PGVERSION ]; then sudo cp /etc/postgresql/{9.6,$PGVERSION}/main/pg_hba.conf; fi"
  - "if [ ! -z $PGVERSION ]; then sudo service postgresql restart $PGVERSION; fi"
```
