### ISSUE TITLE
question(parallel): spaces in the values of variables

### ISSUE THREAD

**Issue by Kristinita** [travis-ci/travis-ci#9634]
### 1. Summary

I can't find, how I can use spaces in variables names.

### 2. Purpose

In real project, I need for my site:

+ First virtual machine — run `grunt default`
+ Second virtual machine — run `grunt default && grunt http-server screenshots && grunt publish` command

I read [**Speeding up the build**](https://docs.travis-ci.com/user/speeding-up-the-build) page and [**this issue**](https://github.com/travis-ci/travis-ci/issues/1444), but I can't find, how I can do it in Travis CI.

### 3. Minimal example

See [**SashaMultipleBuilds branch**](https://github.com/Kristinita/SashaTravis/tree/SashaMultipleBuilds) of my demo repository.

`.travis.yml`:

```yaml
env:
- ECHO_COMMAND=Sasha
- ECHO_COMMAND=Sasha && echo Goddess

script:
- echo $ECHO_COMMAND

```

### 4. Expected behavior

As in AppVeyor:

`appveyor.yml`:

```yaml
environment:
  matrix:
  - ECHO_COMMAND: Sasha
  - ECHO_COMMAND: Sasha&& echo Goddess

build_script:
- echo %ECHO_COMMAND%
```

[**echo `Sasha`, then `Goddess` to console**](https://ci.appveyor.com/project/Kristinita/sashatravis/build/job/5oqxucp76bpsr51o):

```shell
Build started
git clone -q --branch=SashaMultipleBuilds https://github.com/Kristinita/SashaTravis.git C:\projects\sashatravis
git checkout -qf c41ff85ffed5ec75d0c2d4eb0fdc97774d52413f
echo %ECHO_COMMAND%
Sasha
Goddess
Discovering tests…OK
Build success
```

### 5. Actual behavior

I try, see [**Travis CI build history**](https://travis-ci.org/Kristinita/SashaTravis/builds):

+ `- ECHO_COMMAND=Sasha && echo Goddess`
+ `- ECHO_COMMAND="Sasha && echo Goddess"`
+ `- ECHO_COMMAND=echo Sasha && echo Goddess`
+ `- ECHO_COMMAND="echo Sasha && echo Goddess"`
+ `- ECHO_COMMAND="'echo Sasha && echo Goddess'"`
+ `- ECHO_COMMAND: "'echo Sasha && echo Goddess'"`

No effect.

Thanks.

**Comment by BanzaiMan** [comment]
Hmm. So, you are expecting the command(s) embedded in an environment variable to be executed? I don't think that's how it should work; I argue that AppVeyor's behavior is unexpected and wrong.

On my local machine, `bash` works like this:

```sh-session
bash-4.4$ CMD='foo && echo bar'
bash-4.4$ echo $CMD
foo && echo bar
```

If you want the embedded command to be executed, then you can `eval` instead.

```sh-session
bash-4.4$ eval echo $CMD
foo
bar
```

**Comment by Kristinita** [comment]
@BanzaiMan,

**Status: :grey_question: Question**

Is `eval` recommended method for problems as in this issue? `eval` not recommended for any programming language, which I studied. Argumentation for Bash:

+ [**Why should eval be avoided in Bash, and what should I use instead?**](https://stackoverflow.com/q/17529220/5951529)

Thanks.

**Comment by BanzaiMan** [comment]
Surely, `eval` in general is not a good idea for running your scripts when you don't know what the value is going to be.

Another approach to your problem is to define jobs with `matrix.include`:

```yaml
matrix:
  include:
    - script: grunt default
    - script: grunt default && grunt http-server screenshots && grunt publish
```

(with necessary modifications according to the rest of the configuration)

**Comment by BanzaiMan** [comment]
It is also possible to put everything in env var:

```yaml
env:
  - SCRIPT='grunt default'
  - SCRIPT='grunt default && grunt http-server screenshots && grunt publish'
script:
  - $SCRIPT
```

**Comment by Kristinita** [comment]
@BanzaiMan,

**Status: :crying_cat_face: Not fixed** for me

### 1. Put everything in env variable

Doesn't work (I already try it in my examples from first post).

#### 1.1. Demo

`.travis.yml`:

```yaml
env:
- ECHO_COMMAND="echo Sasha"
- ECHO_COMMAND="echo Sasha && echo Goddess"

script:
- $ECHO_COMMAND

```

[**Result**](https://travis-ci.org/Kristinita/SashaTravis/jobs/380835229#L441-L442):

```text
$ECHO_COMMAND
Sasha && echo Goddess
```

#### 1.2. Real project

Part of `.travis.yml`:

```yaml
env:
- GRUNT_COMMAND='grunt'
- GRUNT_COMMAND='grunt default && grunt http-server screenshots && grunt publish'

script:
- $GRUNT_COMMAND
```

[**Result**](https://travis-ci.org/Kristinita/KristinitaPelicanCI/jobs/380985733#L656-L657):

```text
$ $GRUNT_COMMAND
Warning: Task "&&" not found. Use --force to continue.
```

### 2. matrix.include

#### 2.1. Linting

If I lint `.travis.yml`, use official Travis CI client, I get:

```ruby
D:\SashaDemoRepositories\SashaTravis>travis lint
Warnings for .travis.yml:
[x] in matrix.include section: unexpected key script, dropping
```

See [**issue**](https://github.com/travis-ci/travis.rb/issues/376) for more details.

#### 2.2. Duplicating

Not a big problem, but these are I need to write duplicates. If I have another commands in `script` step, I need duplicate these commands. In my example I need duplicate `grunt validate remote travis`.

```yaml
matrix:
  include:
    - script:
      - grunt
      - grunt validate remote travis
    - script:
      - grunt default && grunt http-server screenshots && grunt publish
      - grunt validate remote travis
```

Travis CI doesn't have `test_script` step [**as AppVeyor**](https://www.appveyor.com/docs/appveyor-yml/) and I can't move my test commands to another step as `after_success`, because [**in this step no non-zero exit codes**](https://docs.travis-ci.com/user/customizing-the-build/#Breaking-the-Build).

Thanks.
