### ISSUE TITLE
[community:r] R version 3.5 does not work

### ISSUE THREAD

**Issue by clhunsen** [travis-ci/travis-ci#9654]
I just added R versions 3.4 and 3.5 to the matrix build of our private research repository (see below for the TravisCI script), but the build failed for version 3.5 when downloading something from Amazon cloud:

> $ curl -fLo /tmp/R-3.5-$(lsb_release -cs).xz https://s3.amazonaws.com/rstudio-travis/R-3.5-$(lsb_release -cs).xz
> curl: (22) The requested URL returned error: 403 Forbidden
> The command "eval curl -fLo /tmp/R-3.5-$(lsb_release -cs).xz https://s3.amazonaws.com/rstudio-travis/R-3.5-$(lsb_release -cs).xz " failed. Retrying, 2 of 3.
> ...

I checked the link and noticed that it works for R version **3.5.0**, but _not_ for version **3.5** (https://s3.amazonaws.com/rstudio-travis/R-3.5.0-trusty.xz vs. https://s3.amazonaws.com/rstudio-travis/R-3.5-trusty.xz). Also, versions 3.3 and 3.4 work without problems.

I found some code that may be the cause of the problem: https://github.com/travis-ci/travis-build/blob/271a31325b6ad383d690ed81149554495eda08e9/lib/travis/build/script/r.rb#L537-L545
→ Line 545 sets the version to `'3.5'`, but not `'3.5.0'`.

I hope you can fix this soon. Do not hesitate to ask for more details if you need some. Thanks for your effort!

/cc @craigcitro, @jimhester, @bockthom

----------------------------

#### (Parts of) Our `.travis.yml` file
```yaml
language: r
r:
  - 3.3
  - 3.4
  - 3.5

# TravisCI container
sudo: false
dist: trusty
warnings_are_errors: false

# R dependencies and information
cache: packages
repos:
  CRAN: https://cloud.r-project.org

[...]
```
