### ISSUE TITLE
travis does not advance to next build stage when fast_finish: true

### ISSUE THREAD

**Issue by maxheld83** [travis-ci/travis-ci#9677]
As per [this discussion](https://github.com/travis-ci/beta-features/issues/28#issuecomment-387182805) I understand that `fast_finish: true` *is* supported for build stages with matrix expansion and `allow_failures: `.

However, I observed that a later (deploy) stage did not start, before *all* earlier (test) jobs where finished, even though the missing one(s) were all allowed failures.

![no-fast](https://user-images.githubusercontent.com/5372770/40667942-9e9438b6-6363-11e8-8403-0a476dbd3667.jpg)

[Here's the build](https://travis-ci.com/maxheld83/pensieve/builds/74751710).

Here's the `.travis.yml` (please don't laugh at my clumsy R scripts).

```
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

# matrix ====
r:
  - oldrel
  - release
  - devel
os:
  - linux
  - osx

# general settings ====

warnings_are_errors: true

cache:
  packages: yes
  directories:
    - $HOME/bin

git:
  # accio submodule is used only for deploy, so skip generally
  submodules: false
  depth: 3

# these need not be in pensieve DESCRIPTION, but are still needed for deploy
# when mentioned here, they get cached
r_packages:
  - covr
  - pkgdown
  - rsconnect

notifications:
  email: false


# linux stuff ====

dist: trusty

sudo: false

addons:
  apt:
    packages:
      - pdf2svg
      - libudunits2-dev


# macOS stuff ====

disable_homebrew: false

brew_packages:
  - pandoc

# script is part of base travis R

jobs:
  fast_finish: true
  allow_failures:
    - r: devel
  include:
    - stage: deploy
      os: linux
      r: oldrel
      script:
        # run test coverage
        - Rscript -e 'covr::codecov()'
        # auth machine for github to get accio submodule
        - echo -e "machine github.com\n  login $GITHUB_PAT" >> ~/.netrc
        - git submodule update --init
        - R CMD INSTALL .
        # make website
        - Rscript -e 'pkgdown::build_site()'
        # repeated install is necessary, because packrat otherwise does not know where pensieve came from
        - Rscript -e "devtools::install_github(repo = 'maxheld83/pensieve', force = TRUE, ref = '${TRAVIS_BRANCH}')"
        # auth shiny
        - Rscript -e "rsconnect::setAccountInfo(name='maxheld83', token='${SHINYAPPS_TOKEN}', secret='${SHINYAPPS_SECRET}')"
      deploy:
        # accio
        - provider: script
          script:
          - Rscript -e "rsconnect::deployApp(appDir = 'inst/accio/', appName = 'accio')"
          skip_cleanup: true
          on:
          branch: master
        - provider: script
          script:
            - Rscript -e "rsconnect::deployApp(appDir = 'inst/accio/', appName = 'accio-${TRAVIS_BRANCH}')"
          skip_cleanup: true
          on:
            all_branches: true
            condition: "$TRAVIS_BRANCH != master"
        # site
        - provider: firebase
          token: $FIREBASE_TOKEN
          project: pensieve-169bf
          skip_cleanup: true
          on:
            branch: master
        - provider: pages
          github_token: $GITHUB_PAT
          local_dir: docs/
          skip_cleanup: true
          on:
            branch: dev
```
