### ISSUE TITLE
Travis Job doesn't start when using Dart

### ISSUE THREAD

**Issue by Gleydar** [travis-ci/travis-ci#9678]
Currently my travis builds do not start at all when I try to run them using dart as a language.
It just spits out: "An error occurred while generating the build script."
Below is my current Travis file:
```
os:
  - linux
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
jobs:
  include:
    - stage: Test
      language: dart
      dart_task:
      - dartfmt
      before_script:
        # file names are not allowed to include capital letters
        - chmod 777 ./.no_camel.sh
        - ./.no_camel.sh
        - git clone https://github.com/flutter/flutter.git -b beta --depth 1
        - ./flutter/bin/flutter analyze
      script:
        - ./flutter/bin/flutter test
    - stage: Deploy
      if: branch = master
      language: android
      android:
        components:
          # The BuildTools version used by your project
          - build-tools-27.0.2
          # The SDK version used to compile your project
          - android-27
          # Sys image for eventual virtual devices
          - sys-img-armeabi-v7a-android-26
      licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
      before_script:
        - git clone https://github.com/flutter/flutter.git -b beta --depth 1
        - ./flutter/bin/flutter doctor
      script:
        - ./flutter/bin/flutter -v build apk
cache:
  directories:
  - $HOME/.pub-cache
```

**Comment by Gleydar** [comment]
@nex3, @a14n

**Comment by a14n** [comment]
Do you have a public link to the build log?

**Comment by Gleydar** [comment]
I'm not really sure if it is public, but this is the link to the build log https://travis-ci.org/mobileappdevhm/team2/builds/385307016

**Comment by BanzaiMan** [comment]
There's an exception (this is not public):

<details>
<pre>
﻿﻿TypeError: no implicit conversion of Symbol into Integer
  from lib/travis/build/script/dart.rb:19:in `[]='
  from lib/travis/build/script/dart.rb:19:in `initialize'
  from lib/travis/build.rb:30:in `new'
  from lib/travis/build.rb:30:in `script'
  from lib/travis/api/build/app.rb:82:in `block in <class:App>'
  from sinatra/base.rb:1611:in `call'
  from sinatra/base.rb:1611:in `block in compile!'
  from sinatra/base.rb:975:in `block (3 levels) in route!'
  from sinatra/base.rb:994:in `route_eval'
  from sinatra/base.rb:975:in `block (2 levels) in route!'
  from sinatra/base.rb:1015:in `block in process_route'
  from sinatra/base.rb:1013:in `catch'
  from sinatra/base.rb:1013:in `process_route'
  from sinatra/base.rb:973:in `block in route!'
  from sinatra/base.rb:972:in `each'
  from sinatra/base.rb:972:in `route!'
  from sinatra/base.rb:1085:in `block in dispatch!'
  from sinatra/base.rb:1067:in `block in invoke'
  from sinatra/base.rb:1067:in `catch'
  from sinatra/base.rb:1067:in `invoke'
  from sinatra/base.rb:1082:in `dispatch!'
  from sinatra/base.rb:907:in `block in call!'
  from sinatra/base.rb:1067:in `block in invoke'
  from sinatra/base.rb:1067:in `catch'
  from sinatra/base.rb:1067:in `invoke'
  from sinatra/base.rb:907:in `call!'
  from sinatra/base.rb:895:in `call'
  from rack/deflater.rb:35:in `call'
  from sinatra/base.rb:954:in `forward'
  from sinatra/base.rb:1028:in `route_missing'
  from sinatra/base.rb:989:in `route!'
  from sinatra/base.rb:985:in `route!'
  from sinatra/base.rb:1085:in `block in dispatch!'
  from sinatra/base.rb:1067:in `block in invoke'
  from sinatra/base.rb:1067:in `catch'
  from sinatra/base.rb:1067:in `invoke'
  from sinatra/base.rb:1082:in `dispatch!'
  from sinatra/base.rb:907:in `block in call!'
  from sinatra/base.rb:1067:in `block in invoke'
  from sinatra/base.rb:1067:in `catch'
  from sinatra/base.rb:1067:in `invoke'
  from sinatra/base.rb:907:in `call!'
  from sinatra/base.rb:895:in `call'
  from rack/config.rb:17:in `call'
  from rack/protection/xss_header.rb:18:in `call'
  from rack/protection/path_traversal.rb:16:in `call'
  from rack/protection/json_csrf.rb:18:in `call'
  from rack/protection/base.rb:49:in `call'
  from rack/protection/base.rb:49:in `call'
  from rack/protection/frame_options.rb:31:in `call'
  from rack/nulllogger.rb:9:in `call'
  from rack/head.rb:13:in `call'
  from sinatra/base.rb:182:in `call'
  from sinatra/base.rb:2013:in `call'
  from sinatra/base.rb:954:in `forward'
  from sinatra/base.rb:1028:in `route_missing'
  from sinatra/base.rb:989:in `route!'
  from sinatra/base.rb:985:in `route!'
  from sinatra/base.rb:1085:in `block in dispatch!'
  from sinatra/base.rb:1067:in `block in invoke'
  from sinatra/base.rb:1067:in `catch'
  from sinatra/base.rb:1067:in `invoke'
  from sinatra/base.rb:1082:in `dispatch!'
  from sinatra/base.rb:907:in `block in call!'
  from sinatra/base.rb:1067:in `block in invoke'
  from sinatra/base.rb:1067:in `catch'
  from sinatra/base.rb:1067:in `invoke'
  from sinatra/base.rb:907:in `call!'
  from sinatra/base.rb:895:in `call'
  from raven/integrations/rack.rb:51:in `call'
  from rack/protection/xss_header.rb:18:in `call'
  from rack/protection/path_traversal.rb:16:in `call'
  from rack/protection/json_csrf.rb:18:in `call'
  from rack/protection/base.rb:49:in `call'
  from rack/protection/base.rb:49:in `call'
  from rack/protection/frame_options.rb:31:in `call'
  from rack/nulllogger.rb:9:in `call'
  from rack/head.rb:13:in `call'
  from sinatra/base.rb:182:in `call'
  from sinatra/base.rb:2013:in `call'
  from rack/ssl.rb:27:in `call'
  from rack/protection/xss_header.rb:18:in `call'
  from rack/protection/path_traversal.rb:16:in `call'
  from rack/protection/json_csrf.rb:18:in `call'
  from rack/protection/base.rb:49:in `call'
  from rack/protection/base.rb:49:in `call'
  from rack/protection/frame_options.rb:31:in `call'
  from rack/nulllogger.rb:9:in `call'
  from rack/head.rb:13:in `call'
  from sinatra/base.rb:182:in `call'
  from sinatra/base.rb:2013:in `call'
  from sinatra/base.rb:1487:in `block in call'
  from sinatra/base.rb:1787:in `synchronize'
  from sinatra/base.rb:1487:in `call'
  from puma/configuration.rb:224:in `call'
  from puma/server.rb:600:in `handle_request'
  from puma/server.rb:435:in `process_client'
  from puma/server.rb:299:in `block in run'
  from puma/thread_pool.rb:120:in `block in spawn_thread'
</pre>
</details>

The exception is raised from https://github.com/travis-ci/travis-build/blob/d8ca5c6d5e4742cbf4ae130a7a998eac2250576c/lib/travis/build/script/dart.rb#L19

Most likely due to malformed `dart_task` here: https://github.com/mobileappdevhm/team2/blob/69cbb85b88fdb53242a52cfdb5a6e52a12dbc4c2/.travis.yml#L16-L17

`dart_task` should be a map/hash/dictionary https://docs.travis-ci.com/user/languages/dart#Running-Tests

And the Dart build should fail gracefully. This can be achieved by `rescue`ing an exception like this and reraising `Travis::Build::CompilationError` (or one of its subclasses).

**Comment by Gleydar** [comment]
So it should be
```
dart_task:
-dartfmt: true
```
this?

**Comment by BanzaiMan** [comment]
Not sure what the expected format is, actually. I'll have to defer that to @a14n.

**Comment by a14n** [comment]
@Gleydar yes. See https://docs.travis-ci.com/user/languages/dart/#Formatter

**Comment by Gleydar** [comment]
Hm, I'm afraid that either I am making some mistake, or it's because of the stages. I have tried it now with different configurations, both
```
jobs:
  include:
    - stage: Test
      language: dart
      dart_task:
      - test: --platform vm
      - dartfmt
```
(like on the docs) and
```
jobs:
  include:
    - stage: Test
      language: dart
      dart_task:
      - test: --platform vm
      - dartfmt: true
```
and both failed.

**Comment by Gleydar** [comment]
@a14n

**Comment by a14n** [comment]
@BanzaiMan after a little test I think the issue is because `dart_task` should create a build matrix but it looks like it doesn't work in a stage. Not sure if this is intended to work but if yaml entries that trigger build matrix are not supported in stages there should be a better error message. WDYT ?

**Comment by a14n** [comment]
[My last comment](https://github.com/travis-ci/travis-ci/issues/9678#issuecomment-394255056) was waiting for an answer of @BanzaiMan . But looking at [its activity on its profil page](https://github.com/BanzaiMan) he seems Away From Keyboard since one month.

**Comment by BanzaiMan** [comment]
To clarify: matrix expansion takes place only at the top level. The configuration given in https://github.com/travis-ci/travis-ci/issues/9678#issuecomment-393231556: 
```yaml
jobs:
  include:
    - stage: Test
      language: dart
      dart_task:
      - test: --platform vm
      - dartfmt
```
will pass `["{ test: "--platform vm"}", "dartfmt"]` to the `dart_task` value in the "Test" job, which is most likely not what you want.

Matrix expansion code is quite complex, and allowing it to take place at *any arbitrary level* of the build configuration is going to be difficult and error-prone.
