### ISSUE TITLE
Add support for .NET Core SDK 2.1.300 (RTM)

### ISSUE THREAD

**Issue by olegburov** [travis-ci/travis-ci#9684]
Hi @joshua-anderson, @akoeplinger and @nterry

Could you please add support for the final version of [.NET Core SDK 2.1.300 ](https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.300)(`2.1.300`)?

Currently I'm getting this error:
```
The command "sudo apt-get install -qq dotnet-sdk-2.1.300" failed and exited with 100 during .
```
When my `.travis.yml` file looks like:

```yml
language: csharp 
dist: trusty
mono: none
dotnet: 2.1.300
branches:  
  only:  
    - master
before_script: cd src
script:  
  - dotnet restore 
  - dotnet build
```
