### ISSUE TITLE
How can I catch after_deploy error???

### ISSUE THREAD

**Issue by CodeNinjaEvan** [travis-ci/travis-ci#9687]
```
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: develop
after_deploy:
- "./gradlew test"
```
In after_deploy stage ,./gradlew test  false, but return 0 and build pass , How can I catch after_deploy error???
Looking forward to your reply
