### ISSUE TITLE
PHP setlocale() fails even if the locale is installed

### ISSUE THREAD

**Issue by briedis** [travis-ci/travis-ci#9688]
So I install the locales using:
```
addons:
    apt:
        packages:
            - language-pack-en
            - language-pack-de
```

But when I try to use `setlocale(LC_ALL, 'en_US');` it still returns false (I'm trying to test gettext).

You can see in this build, here I dump out locales installed and en_US shows up:
https://travis-ci.org/printful/php-gettext-cms/jobs/386364885#L580

Then I try `setlocale` and it fails:
https://travis-ci.org/printful/php-gettext-cms/jobs/386364885#L632

Ideas?
