### ISSUE TITLE
Error parsing sourceline apt sources in yaml anchors

### ISSUE THREAD

**Issue by ryndaniels** [travis-ci/travis-ci#9693]
I've been investigating an issue where sourceline apt sources don't seem to get parsed properly if they are in a yaml anchor in a `.travis.yml` config. To clarify with some examples:

The following works, as aliases for sources are strings:
```
addons:
  apt:
    sources: &anchor
       - chef-stable-trusty
jobs:
  include:
    - addons:
        apt:
          sources:
            - *anchor
```

The following works, since the sourceline is not inside the nested anchor part of the yaml:
```
addons:
  apt:
    sources: &anchor
       - ubuntu-toolchain-r-test
jobs:
  include:
    - addons:
        apt:
          sources:
            - *anchor
            - sourceline: 'deb https://packages.chef.io/repos/apt/stable trusty main'
```

The following does not work, and throws an error saying the `sourceline` key is missing from the sourceline source.
```
addons:
  apt:
    sources: &anchor
       - sourceline: 'deb https://packages.chef.io/repos/apt/stable trusty main'
jobs:
  include:
    - addons:
        apt:
          sources:
            - *anchor
```
@meatballhat and I were investigating and believe there is an issue with how sources are being parsed or symbolized (or not) in the apt addon (https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/addons/apt.rb#L122). We haven't gotten farther than this _yet_ but I wanted to document what we've been able to figure out and reproduce so far.

**Comment by BanzaiMan** [comment]
This particular example appears to be a problem with the data structure. This YAML fragment:

```yaml
addons:
  apt:
    sources: &anchor
       - sourceline: 'deb https://packages.chef.io/repos/apt/stable trusty main'
jobs:
  include:
    - addons:
        apt:
          sources:
            - *anchor
```

yields object:

```
{
  "addons": {
    "apt": {
      "sources": [
        {
          "sourceline": "deb https://packages.chef.io/repos/apt/stable trusty main"
        }
      ]
    }
  }, 
  "jobs": {
    "include": [
      {
        "addons": {
          "apt": {
            "sources": [
              [
                {
                  "sourceline": "deb https://packages.chef.io/repos/apt/stable trusty main"
                }
              ]
            ]
          }
        }
      }
    ]
  }
}
```

The problem appears to me that the anchor is a map/hash/dictionary instead of a sequence/array. With this, we now have `addons.apt.sources` with `[[{}]]`. We [flatten it](https://github.com/travis-ci/travis-build/blob/2a06db90048f8af22d726e118f77e9ec501d334a/lib/travis/build/addons/apt.rb#L209), but due to the structure, we retain the "array of a hash".

What we need instead, is:

**Comment by jimklimov** [comment]
Hello, we've got quite a similar problem, with a nuance that we need to list more than one source for some but not all matrix cases, and many of those individual sources are repetitive.

I tried a few ways to spell it, but failed so far :)

Using:
````
customsrc:
- sourceline: 'deb URL ./'
  key_url: 'URL'
````

We had:
````
sources: *customsrc
````
which works okay indeed. But for one source.

In a few cases we need extra sources, such as `ubuntu-toolchain-r-test`...
````
sources:
- *customsrc
- ubuntu-toolchain-r-test
````
fails with the error in this ticket.

Ad both of these:
````
sources:
*customsrc
- ubuntu-toolchain-r-test

sources: *customsrc
- ubuntu-toolchain-r-test
````
fail to parse. On a side note, I found Travis Web-UI has a hidden URL ".../requests" that lists the status of attempted build schedulings.

**Comment by jimklimov** [comment]
Also tried listing `sources:` twice, like:
````
sources: *customsrc
sources:
- ubuntu-toolchain-r-test
````
or
````
sources:
- ubuntu-toolchain-r-test
sources: *customsrc
````
but in both orders it was syntactically correct but practically failed. Only the last mentioned entry took effect, overwriting the earlier one, so some of the needed packages were not found.

**Comment by jimklimov** [comment]
Hooray, seems dropping the dash works:
````
customsrc: &customsrc
  sourceline: 'deb URL ./'
  key_url: 'URL'

sources:
- *customsrc
- ubuntu-toolchain-r-test
````

adds both sources AND allows use of aliases. Case re-closed, hope this helps someone later on ;)
