### ISSUE TITLE
AWS Codedeploy deployment does not support bucket and deployment group in different regions

### ISSUE THREAD

**Issue by Legogris** [travis-ci/travis-ci#9707]
We are using S3 / Codedeploy to deploy the same application in several regions.
When setting the `region` parameter as documented [here](https://docs.travis-ci.com/user/deployment/codedeploy/#AWS-region-to-deploy-to), this seems to set the region for both the bucket and the deployment group.
Travis seems to make the assumption that deployment groups and buckets are always in the same region.

When setting the `region` parameter to the region of the deployment group, deployment fails at the `DownloadBundle` step with `The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.`

One solution would be to set up codedeploy buckets in every region our application lives in, but this is considerable overhead and we don't want to get the risk of them being out of sync.

**Comment by BanzaiMan** [comment]
> Travis seems to make the assumption that deployment groups and buckets are always in the same region.

I reviewed the code, but I don't think this is true. S3 and CodeDeploy provider takes the `region` option independently (and each defaulting to `us-east-1` if unspecified):

```yaml
    deploy:
      - provider: s3
        region: X
        ⋮ # rest of S3 deployment for MyApp.zip
      - provider: codedeploy
        access_key_id: "YOUR AWS ACCESS KEY"
        secret_access_key: "YOUR AWS SECRET KEY"
        bucket: "S3 Bucket"
        key: latest/MyApp.zip
        application: MyApp
        deployment_group: MyDeploymentGroup  
        region: Y
```
