### ISSUE TITLE
Feature Request: alternate syntax for global secure env

### ISSUE THREAD

**Issue by probablyup** [travis-ci/travis-ci#9726]
When you encrypt a variable, the name of the environment variable is also encrypted, so it can be hard to figure out what is what when you have multiple variables that are encrypted.

E.g.

```bash
travis encrypt "foo=bar" --add
travis encrypt "bar=baz" --add
```

Ends up like:

```
env:
  global:
  - secure: DKMYb4iCZ17K2joMb5ygSZlzqRUXv9yaKuH280SO0gWZK1qQmoa9amG7XqhwwIiHHhVF/sqPM8cgCdLigC3b4XdS39FIq+Fn737pw3lIbNSWIWfPB4hQn0NpkCMEGN1kOQNKmq2nTD1BgnMsmNoSdEKcDL727LEKe6b8zrlib3LejFmRi0vJ59a5ZIL1sGrukJhNC8OUJWsVTkgs4rDd7sdM4YSkr0KivMCUOG5KYQY1NoDu7ybJfFm5qPeZBneHHETKM2Cu95vfQh+zUlNoG5FMVj1PIRrVe1Vdl02mXT2bQrByuRpFecjilpYG8Q2WOUtPae6ScYVH/bnvs6DtFM/ixq27+3HjQqUPWd8PZZwUglYoC0aaRikasllWQMXXjYclih0XDnmPoGTs0P47Gho7z+FYtZOt8vPhibVnsLctsJvvZ8zjIXzpOawGss5QE6u0Px7h8V1SVJLHRyZvy/TavOFrCw8c7Rl90l8u9cucdzHCFBD9mT9xTvWwdsTfAvrYuUkNVSd2GO3EyMHbRu8qbxdWQc9hxb/2MVvbFmYwOr8YxoXRMe5qjQfYLwdRYWyAccJAgXEQAtLhBRUdQxK0SWzlFNWu/MYCk/6nyjUhZhu3kUR/9iX/ME1s8qTopM76lsPT3Q8J13JiytJPtpRoQQWCMXnu2xUvTmrvRxw=
  - secure: IVFY7GoF4TE8TN2LpZ2ZrMfPMRXsPpPqPsoaUlKUpxpMbMjdTnK+1EFdUP9ISLRvbaCybEY1BLE+V6pcWY0WA519i0oD5XoTuLE8d4ztjWPgSyNPjVyH4Ohr45Tt6Et9fPHoYUsheeK6sIJHCSBdz9shoRKYtCxnxwWMPZufIcnfNUzFlwa58W2p5lgqYmReZrSYReKddQiBWwpQYWYcPdDrSeouMxnx4zi7UYApO++D2qS4EU1kuUvWqKNTrmMCyLF3CVMZvF+c6OhpRwJlHCNWWEuRaU/zQOwvPA7LcWMaJSecQeGSMarhdWQclQzKc4mlp/mD06Tj1jc0UH+Xl+21Gm+kXIjpiNbbiYo0l7YcAoOlOCMrJcpVfaYd2uhNK2hsae+Eqbze4JXZBlLGAZw+Gt/XX2k/x78AZLpTsLKxnw8hwbFfoqrtcEZqF6WUevxgGZY0D84yXDdDCphJjZCPB7tGm1LdrvV75hMELFZdsTHjwLUWgb9zuk0aH/EO8VdPF07tsvoSMoLhv2S5Xmf2bLNweideM3B3yyuZUKTP+Qiauyg2ugNIKRW0Hz3brlRJ8Gx0WhNzUpRmIW7TMZd8HscZzs1MBaGYJpw5EcRATi4U8XQnUOVpvfTK/SqR6dGyqDfD5ZGVKRkTeMwbdOcD2LufSTCTgQgHM7FTJpE=
```

If you need to come back at a later date and update them, it's impossible to tell which is which.

To help this situation, I'd like to propose an alternate syntax for adding them:

```yml
env:
  global:
  - name: foo
    secure: [encrypted-value]
  - name: bar
    secure: [encrypted-value]
```
