### ISSUE TITLE
Deploy android Xamarin application using Travis

### ISSUE THREAD

**Issue by artiOPSPL** [travis-ci/travis-ci#9743]
@joshua-anderson @akoeplinger @nterry I am unable to build and deploy xamarin project using Travis. 
.yml file:

```
os:
  - osx

android:
  components:
    - tools
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    # The SDK version used to compile your project
    - android-26
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26

env:
  global:
    - ANDROID_COMPONENTS=build-tools-25.0.1,android-24,extra-android-support,extra-google-google_play_services,extra-google-m2repository,extra-android-m2repository
    - ANDROID_LICENSES=android-sdk-license-c81a61d9
    - MONO_VERSION=4.6.2
    - MONO_ANDROID_VERSION=7.0.2-42

before_install:
  - yes | sdkmanager "platforms;android-27"

install:
  - curl -L https://raw.github.com/embarkmobile/android-sdk-installer/version-2/android-sdk-installer | bash /dev/stdin --install=$ANDROID_COMPONENTS --accept=$ANDROID_LICENSES
  - source ~/.android-sdk-installer/env
  - wget "http://download.mono-project.com/archive/${MONO_VERSION}/macos-10-universal/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.universal.pkg"
  - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.universal.pkg" -target /
  - wget "https://dl.xamarin.com/MonoforAndroid/Mac/xamarin.android-${MONO_ANDROID_VERSION}.pkg"
  - sudo installer -pkg "xamarin.android-${MONO_ANDROID_VERSION}.pkg" -target /
  - /Library/Frameworks/Mono.framework/Commands/nuget restore proj.Mobile.sln

script:
  - /Library/Frameworks/Mono.framework/Commands/xbuild /t:SignAndroidPackage /p:Configuration=Release proj.Mobile.Android.csproj
```

 No proper documentation available in Travis documentation regarding Xamarin. Any help would be appreciated.
