### ISSUE TITLE
Stalled build while removing existing node_modules/ before installation

### ISSUE THREAD

**Issue by wildlifehexagon** [travis-ci/travis-ci#9772]
Hi, I have run into an issue with builds stalling in two of my React web apps recently. Both of them terminate at the same position:

```
$ npm ci 
npm WARN prepare removing existing node_modules/ before installation

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

For reference, here is my `.travis.yml`:

```
language: node_js
node_js:
  - "10.4.0"

cache:
  directories:
    - node_modules

before_script:
  - mv src/utils/clientConfig.sample.js src/utils/clientConfig.js

script:
  - npm test

# safelist
branches:
  only:
  - master
  - develop
```

These timeouts appear to happen randomly. Most of the time my builds pass without issue, but these pop up every few commits or so. Is this a bug or a problem on my end?
