### ISSUE TITLE
commit msg with co-author borks up firebase deploy

### ISSUE THREAD

**Issue by maxheld83** [travis-ci/travis-ci#9783]
It seems like a firebase deploy chokes on commit messages with co-authors as as [this](https://github.com/maxheld83/pensieve/commit/23d11536e32562d5b4803636d1d78f32e32644ae)

```
factor out grid cell content #381
Co-Authored-By: Verena Kasztantowicz <VerenaKasztantowicz@gmail.com>
```

yields [this build](https://travis-ci.com/maxheld83/pensieve/jobs/130654571)

```
$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl
Successfully installed dpl-1.9.7
1 gem installed
invalid option "--message=factor out grid cell content #381\n\nCo-Authored-By: Verena Kasztantowicz <VerenaKasztantowicz@gmail.com>"
failed to deploy
```

I am guessing this is because of the special characters involved here.

Maybe shorten the commit message?

Here's my `.travis.yml`:

```
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

# matrix ====
r:
  - oldrel
  - release
  - devel
os:
  - linux
  - osx

# general settings ====

warnings_are_errors: true

cache:
  packages: yes
  directories:
    - $HOME/bin

git:
  # accio submodule is used only for deploy, so skip generally
  submodules: false
  depth: 3

# these need not be in pensieve DESCRIPTION, but are still needed for deploy
# when mentioned here, they get cached
r_packages:
  - covr
  - pkgdown
  - rsconnect

notifications:
  email: false


# linux stuff ====

dist: trusty

sudo: false

addons:
  apt:
    packages:
      - pdf2svg
      - libudunits2-dev
      - libpoppler-cpp-dev


# macOS stuff ====

disable_homebrew: false

brew_packages:
  - pandoc
  - cairo
  - pdf2svg

# script is part of base travis R

jobs:
  fast_finish: true
  allow_failures:
    - r: devel
  include:
    - stage: deploy
      os: linux
      r: oldrel
      script:
        # auth machine for github to get accio submodule
        - echo -e "machine github.com\n  login $GITHUB_PAT" >> ~/.netrc
        - git submodule update --init
        # test coverage
        - Rscript -e 'covr::codecov()'
        # make website
        - Rscript -e 'pkgdown::build_site()'
        # repeated install is necessary, because packrat otherwise does not know where pensieve came from
        - Rscript -e "devtools::install_github(repo = 'maxheld83/pensieve', force = TRUE, ref = '${TRAVIS_BRANCH}')"
        # auth shiny
        - Rscript -e "rsconnect::setAccountInfo(name='maxheld83', token='${SHINYAPPS_TOKEN}', secret='${SHINYAPPS_SECRET}')"
      deploy:
        # accio
        - provider: script
          script:
          - Rscript -e "rsconnect::deployApp(appDir = 'inst/accio/', appName = 'accio')"
          skip_cleanup: true
          on:
          branch: master
        - provider: script
          script:
            - Rscript -e "rsconnect::deployApp(appDir = 'inst/accio/', appName = 'accio-${TRAVIS_BRANCH}')"
          skip_cleanup: true
          on:
            all_branches: true
            condition: "$TRAVIS_BRANCH != master"
        # site
        - provider: firebase
          token: $FIREBASE_TOKEN
          project: pensieve-169bf
          message: $TRAVIS_COMMIT_MESSAGE
          skip_cleanup: true
          on:
            branch: master
        - provider: pages
          github_token: $GITHUB_PAT
          local_dir: docs/
          skip_cleanup: true
          on:
            branch: dev
```
