### ISSUE TITLE
Deploy Github Pages, Sphinxdoc, does not commit all files

### ISSUE THREAD

**Issue by vfdev-5** [travis-ci/travis-ci#9794]
Hello, 

I'm trying to configure travis to automatically deploy built documentation to github `gh-pages`:
```yaml
      # GitHub Pages Deployment: https://docs.travis-ci.com/user/deployment/pages/
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        local_dir: docs/build/html
        on:
          branch: master
```
and it appears that it does not commit all generated files. In the following example I already had a docs manually committed to gh-pages and here is the commit followed by travisci bot after `.travis.yml` deploy update:
```
Author: Deployment Bot (from Travis CI) <deploy@travis-ci.org>
Date:   Sun Jun 24 13:09:14 2018 +0000
    Deploy vfdev-5/ignite to github.com/vfdev-5/ignite.git:gh-pages
 .buildinfo                                        |   4 +
 _config.yml                                       |  28 --
 _modules/ignite/engine.html                       | 299 --------------
 _modules/ignite/engine/engine.html                | 456 ----------------------
 _modules/ignite/exceptions.html                   | 233 -----------
 _modules/ignite/handlers/checkpoint.html          | 408 -------------------
 _modules/ignite/handlers/early_stopping.html      | 285 --------------
 _modules/ignite/handlers/timing.html              | 377 ------------------
 _modules/ignite/metrics/binary_accuracy.html      | 259 ------------
 _modules/ignite/metrics/categorical_accuracy.html | 260 ------------
 ...
 28 files changed, 36 insertions(+), 5085 deletions(-)
cd -
```
There are 5085 deletions that should not happen and actually should be updated.

Could you help me to fix this ?
Thanks
