### ISSUE TITLE
How to configure travis to trigger pages build and deployment for each new tags ?

### ISSUE THREAD

**Issue by kopax** [travis-ci/travis-ci#9808]
This is my `.travis.yml`:

```yml
language: node_js
sudo: required
dist: trusty

# Blocklist
branches:
  except:
    - gh-pages # will be deployed to, no need to build it

cache:
  directories:
    - node_modules

before_install:
    - npm install -g npm
    # const
    - export PACKAGE_NAME=$(node -p "require('./package.json').name")
    - export PACKAGE_VERSION=$(node -p "require('./package.json').version")
    - export SONAR_VERSION=${PACKAGE_VERSION}-b${TRAVIS_BUILD_ID}-${TRAVIS_BRANCH}
    - export NODE_VERSION=$(node --version)
    - export NPM_VERSION=$(npm --version)

    # logging
    - npm --version || echo npm not installed
    - node --version || echo node not installed
    - echo "package version $PACKAGE_VERSION"

stages:
  - build
  - test
  - release
  - deploy

jobs:
  include:

    # Job: Build
    - stage: build
      node_js:
        - 'lts/*'
        - '10'
        - '8'
      script:
        - npm run build
    # Job: Test
    - stage: test
      node_js:
        - 'lts/*'
        - '10'
        - '8'
      addons:
        sonarcloud:
          organization: "yeutech-lab"
      script:
        - npm run test
        # - sonar-scanner -Dsonar.branch=${TRAVIS_BRANCH} -Dsonar.projectVersion=${SONAR_VERSION}
        - sonar-scanner -Dsonar.organization=yeutech-lab

    # Job: Release
    - stage: release
      if: branch = master
      node_js:
        - 'lts/*'
      skip_cleanup: true
      script:
        - npx semantic-release

    # Job: Page
    - stage: deploy
      if: branch = master
      node_js:
        - 'lts/*'
      script:
        - npm install
        # Replace variables (etc...)
        - npx rollup-umd-scripts doc variable PACKAGE_NAME=${PACKAGE_NAME}
        - npm run styleguide:build
      deploy:
        - provider: pages
          skip_cleanup: true
          github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
          keep_history: true
          local_dir: public/
```

The stage `release` is pushing a new tags, and I need the job deploy to build and deploy the page.

However, I never succeeded to block this step only when a tag is done, even when using `TRAVIS_TAG`, it seems that only PR and Push does trigger a build.

Can anyone help me understand how I could do ? I managed to do it like this :

```yml
    - stage: deploy
      if: branch = master
      node_js:
        - 'lts/*'
      script:
        - git fetch --tags
        - PACKAGE_VERSION=$(git describe --tags | awk -F '-' '{print $1}')
        - git checkout refs/tags/${PACKAGE_VERSION}
        - PACKAGE_VERSION=$(node -p "require('./package.json').version")
        - npm install
        # Replace variables
        - npx rollup-umd-scripts doc variable PACKAGE_NAME=${PACKAGE_NAME}
        - npm run styleguide:build
      deploy:
        - provider: pages
          skip_cleanup: true
          github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
          keep_history: true
          local_dir: public/
```

but that is bad because the job is building a doc even if it's not needed

**Comment by keradus** [comment]
```diff
     - stage: deploy
-      if: branch = master
+      if: tag IS present
```

**Comment by keradus** [comment]
`on` is condition for `deploy`, not for `stage`.
that means, when you have condition only for `deploy: on: ...` and not `stage: if: ...`, then stage is triggered, virtual machine launched, and then it figures out that deployment conditions (from `on: ...`) are not fulfilled and job finished without doing anything.

if you don't want this job to trigger on pull_request, include that in condition, like:
`if: type != pull_request AND tag IS present` (there are 4 types - pull request, regular push, cron and api)

**Comment by kopax** [comment]
> on is condition for deploy, not for stage.

We noticed that and we felt that it was not possible to trigger build on tag and that travis required us to run all job and configure the deployment part with condition (not bad if you think about it)

> if you don't want this job to trigger on pull_request, include that in condition, like:
`if: type != pull_request AND tag IS present` (there are 4 types - pull request, regular push, cron and api)

We did try to play with the `tag IS present`, but we never see any build where the tag was actually present.


We expect to be able to get the job only when a tag happen but maybe this is not how travis work ?

You can see here how we did try: 

- You can see here how we did try to build only for tags and using `TRAVIS_TAG`:   [.travis.yml](https://github.com/yeutech-lab/accept-dot-path/blob/a526eda454bb138a214a8e3a4fcd721ded6af19b/.travis.yml#L71) [travis build](https://travis-ci.org/yeutech-lab/accept-dot-path/jobs/396886059#L4143) , but scripts got executed for dev branch.

- You can see here how we did try to deploy only for tags :   [.travis.yml](https://github.com/yeutech-lab/accept-dot-path/blob/bba6fe966708d88c52c43f12c0fdeaa1f32ef470/.travis.yml#L91) [travis build](https://travis-ci.org/yeutech-lab/accept-dot-path/jobs/396903078)


Now we are solving our deployment with that ugly fix: 

```yml

    # Job: Release
    - stage: release
      if: branch = master
      node_js:
        - 'lts/*'
      skip_cleanup: true
      script:
        - npx semantic-release

    # Job: Page
    - stage: deploy
      if: branch = master
      node_js:
        - 'lts/*'
      script:
        - git fetch --tags
        - git checkout refs/tags/$(git describe --tags `git rev-list --tags --max-count=1`)
        - npm install
        - styleguide/prepare.sh
        - npm run styleguide:build
      deploy:
        - provider: pages
          skip_cleanup: true
          github_token: $GH_TOKEN 
          keep_history: true
          local_dir: public/

```


1. Can you please confirm that `if: tag IS present`, then the env `TRAVIS_TAG` should be set ?
1. We use [semantic-release](https://github.com/semantic-release/semantic-release), the plugin is doing a `git push origin master` then `git push --tags` during our release stage, the next job is deployment of GitHub page and we weren't able to get it build when the tags is done using the `TRAVIS_TAG` and `if: tag is present`. Is it ok to use semantic release ?

Usually, on gitlab, we just do the tag and trigger a doc build for that tag, I though travis could handle tags but never seen them working, is it my whole configuration preventing build to trigger ? Do you have open source project that demonstrate how to build on tag?
