### ISSUE TITLE
Timing out on original repo but not on fork?

### ISSUE THREAD

**Issue by sandervanhooft** [travis-ci/travis-ci#9813]
Hi,

I am getting a time out error on [this build](https://travis-ci.org/mollie/laravel-mollie/builds/397286962) while not on [the fork](https://travis-ci.org/sandervanhooft/laravel-mollie). It's because `no output was received`.

Travis script is the same for both (as is the code to be tested):
```yaml
language: php

php:
  - 7.0
  - 7.1
  - 7.2

sudo: false

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

install:
  - travis_wait 30 composer install --no-interaction

script:
  - composer validate --strict
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
```

Any suggestions here?
