### ISSUE TITLE
Add Python 3.7 option

### ISSUE THREAD

**Issue by Harmon758** [travis-ci/travis-ci#9815]
Now that [Python 3.7.0](https://www.python.org/downloads/release/python-370/) has been [released](https://pythoninsider.blogspot.com/2018/06/python-3.html).

The current workaround seems to be adding it to the build `matrix.include` configuration using xenial in `.travis.yml`:
```yml
# Existing Python versions
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
```
or alternatively:
```yml
matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
```

**Comment by webknjaz** [comment]
FWIW `pyenv` already updated it

**Comment by hugovk** [comment]
See also https://github.com/travis-ci/travis-ci/issues/9069.

**Comment by tomato42** [comment]
Note: There is a `3.7-dev` version of python that can be used to run code in Python 3.7-like environment

**Comment by mbeacom** [comment]
@tomato42 Sadly, the `3.7-dev` is using a fairly dated beta release that doesn't reflect the RC/stable 3.7.

**Comment by ssbarnea** [comment]
Apparently[ this is what happens ](https://travis-ci.org/pycontribs/jira/jobs/398749222)when you try to install python 3.7:
```
3.7 is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.7.tar.bz2
$ curl -sSf -o python-3.7.tar.bz2 ${archive_url}
curl: (22) The requested URL returned error: 403 Forbidden
Unable to download 3.7 archive. The archive may not exist. Please consider a different version.
```

**Comment by webknjaz** [comment]
@BanzaiMan hi, could you please shed some light on whether to expect Python 3.7.0 stable in Travis CI anytime soon? A lot of people really depend on it (https://twitter.com/pfreixes/status/1012654620634767365, https://github.com/HypothesisWorks/hypothesis/issues/1148#issuecomment-401451825)

**Comment by codingjoe** [comment]
Honestly for now, the saves bet is docker 😕

**Comment by webknjaz** [comment]
They didn't merge it either: https://github.com/docker-library/python/pull/297.
Well, there's manylinux1 image, which ships 3.7, but it has a different purpose.

**Comment by joepvd** [comment]
With the following snippet, you can use Python 3.7 in your builds:

```
language: python
python: 3.7
dist: xenial
sudo: true
```

**Comment by webknjaz** [comment]
BTW, I was able to build it under 14.04 as well.

**Comment by jmsv** [comment]
@joepvd As mentioned [here](https://github.com/jmsv/ety-python/pull/48), that snippet breaks Python 3.4 support. Is there any way to use both?

**Comment by webknjaz** [comment]
@jmsv I'm going to guess that adding that to a specific job only will fix your issue. (via `jobs.include`)

**Comment by webknjaz** [comment]
When I try @joepvd's recipe I get inconsistent log (failing):

```
Worker information
hostname: eacba1b9-478c-4813-a27b-9ab99178d13e@1.i-033fefd-production-2-worker-org-ec2.travisci.net
version: v3.8.2 https://github.com/travis-ci/worker/tree/c370f713bb4195cce20cdc6ce3e62f26b8cf3961
instance: 8b6e43d travisci/ci-garnet:packer-1512502276-986baf0 (via amqp)
startup: 510.164766ms
system_info
Build system information
Build language: python
Build group: edge
Build dist: xenial
Build id: 399123501
Job id: 399123512
Runtime kernel version: 4.14.12-041412-generic
travis-build version: e2813f549
Build image provisioning date and time
Tue Dec  5 20:11:19 UTC 2017
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
...
3.7 is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.7.tar.bz2
$ curl -sSf -o python-3.7.tar.bz2 ${archive_url}
curl: (22) The requested URL returned error: 403 Forbidden
Unable to download 3.7 archive. The archive may not exist. Please consider a different version.
```

Note the mix of xenial/trusty/14.04

**Comment by webknjaz** [comment]
Oh.. Okay.  It was because of `group: edge`. When I reset it, it started download from the correct URL.

**Comment by webknjaz** [comment]
@joepvd will there be a possibility to run that without `sudo: required`?

**Comment by webknjaz** [comment]
Wow, it attempts to access that invalid `14.04` URL without `sudo: required`. Weird.

**Comment by aluttik** [comment]
If anyone's still running into problems because Python 3.7 requires xenial while as other Python versions worked with trusty, try using a `matrix.include` like this:
```yaml
language: python
matrix:
    include:
        - python: 2.6
          dist: trusty
          sudo: false
        - python: 2.7
          dist: trusty
          sudo: false
        - python: 3.3
          dist: trusty
          sudo: false
        - python: 3.4
          dist: trusty
          sudo: false
        - python: 3.5
          dist: trusty
          sudo: false
        - python: 3.6
          dist: trusty
          sudo: false
        - python: 3.7
          dist: xenial
          sudo: true
        - python: pypy
          dist: trusty
          sudo: false
install:
    - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then pip install virtualenv==15.2.0; fi
    - pip install tox-travis
script: tox
```

**Comment by labrys** [comment]
Thanks @joepvd for the work-around.  It's a shame we can't do it without it though.

**Comment by jvesely** [comment]
I am able to run without "sudo: true", but it still needs xenial instead of the default trusty.

**Comment by ssbarnea** [comment]
Something fishy is going on because few days ago I was able to use the `dist: xenial` trick to enable py37 until few moments ago when this stopped working and now I am back to the old problem, even with **xenial**: https://travis-ci.com/pycontribs/jira/jobs/133521841
```
3.7 is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.7.tar.bz2
$ curl -sSf -o python-3.7.tar.bz2 ${archive_url}
curl: (22) The requested URL returned error: 403 Forbidden
Unable to download 3.7 archive. The archive may not exist. Please consider a different version.
```

**Comment by aluttik** [comment]
@ssbarnea: That job wasn't running on xenial. Expand the "Build System Information" in that log.
```
Build system information
Build language: python
Build group: stable
Build dist: xenial
Build id: 78479696
Job id: 133521841
Runtime kernel version: 4.14.12-041412-generic
travis-build version: 0b1d6addf
Build image provisioning date and time
Tue Dec  5 20:11:19 UTC 2017
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```
For some reason it's being run on trusty still and it's looking for the archive at the trusty url instead of the xenial one:
```
trusty: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.7.tar.bz2
xenial: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/16.04/x86_64/python-3.7.tar.bz2
```
Maybe try restarting the build? Idk. It could be a configuration problem.

**Comment by ssbarnea** [comment]
I did put back the sudo and it passed but I am afraid that may be only "chance". I think the result may be random,... or "determined" by the other in which the parallel stages are finishing.

**Comment by webknjaz** [comment]
@ssbarnea it's probably a bug and I guess Travisers are working on solving it. I've noticed that combined with different config options it sometimes results in wrong URL (I've mentioned this earlier). So for now the best thing to do is to have `sudo: required` just for job with 3.7.0.

**Comment by berrisfordjohn** [comment]
adding the following to the .travis.yml
language: python
python: 3.7 
dist: xenial 
sudo: true

worked for me.

**Comment by stephenhky** [comment]
@berrisfordjohn It does not work for me though, as somehow it cannot install tensorflow:

```
Collecting tensorflow (from mogu==0.2.1a0)
  Could not find a version that satisfies the requirement tensorflow (from mogu==0.2.1a0) (from versions: )
No matching distribution found for tensorflow (from mogu==0.2.1a0)
```

I already added the lines into my [.travis.yml](https://github.com/stephenhky/MoguNumerics/blob/py37test/.travis.yml).

**Comment by The-Compiler** [comment]
@stephenhky That seems like a Tensorflow issue, see e.g. https://github.com/tensorflow/tensorflow/issues/20517

**Comment by abotiamnot** [comment]
I can't sudo:true since it messes up with my build ( Travis has some bugs with FTP servers which don't work if you have sudo:true, you need sudo:false ). Is there any other alternative?

**Comment by abotiamnot** [comment]
Thanks @jvesely but that doesn't work :( . @rooterkyberian The problem I'm encountering is this, https://github.com/travis-ci/travis-ci/issues/9391 Sudo enabled breaks the FTP jobs, so I always need to explicitly mention sudo: false

**Comment by Koed00** [comment]
This keeps being an issue with Travis not being up to date with the latest Python version.
Come on guys, don't make me switch to the competition.

**Comment by facetoe** [comment]
+1 for 3.7 support.

**Comment by farrokhi** [comment]
I noticed you actually *can* build using python3.7. Here is an example build: 
https://travis-ci.org/chtd/psycopg2cffi

Here is the `.travis.yml` file for above build: https://github.com/chtd/psycopg2cffi/blob/master/.travis.yml

**Comment by webknjaz** [comment]
@farrokhi no, you are wrong. It's `sudo: true` specific to that specific job.

**Comment by farrokhi** [comment]
@webknjaz yes, you actually need to use `sudo: true` to trigger this. Otherwise `dist: xenial` would be ignored. I am actually using this trick to build against python 3.7 and 3.7-dev targets:
https://travis-ci.org/farrokhi/dnsdiag

**Comment by webknjaz** [comment]
Well, everyone is using this hack now.

**Comment by Juanlu001** [comment]
People are really holding off Python 3.7 support because of this issue and it makes me sad. I already switched to [Circle CI](http://circleci.com/), which is also free for F/OSS projects, and don't intend to look back. Don't take this as an attack on Travis CI: they probably have other priorities, so I'm just recommending another CI service that happens to work really well.

**Comment by jarun** [comment]
> which is also free for F/OSS projects

The free plan is limited: https://circleci.com/pricing/

**Comment by Harmon758** [comment]
@mgedmin Done.

**Comment by nickwilliams-eventbrite** [comment]
@mgedmin, that doesn't work for me. It just ignores the matrix completely and runs jobs only for Python 2.7, 3.4, 3.5, and 3.6. 🤔

**Comment by nickwilliams-eventbrite** [comment]
So I tried using `sudo: true` and `dist: xenial`, and now Python 2.7, 3.5, 3.6, and 3.7 run and pass, but Python 3.4 fails:

```
3.4 is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/16.04/x86_64/python-3.4.tar.bz2
$ curl -sSf -o python-3.4.tar.bz2 ${archive_url}
curl: (22) The requested URL returned error: 403 Forbidden
Unable to download 3.4 archive. The archive may not exist. Please consider a different version.
```

😞

**Comment by farrokhi** [comment]
@nickwilliams-eventbrite You only need to do the sudo trick for 3.7 (using the matrix). It is the reason 3.4 is failing.

**Comment by nickwilliams-eventbrite** [comment]
@farrokhi, as said [above](https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-411092103), when doing that (with matrix), Python 3.7 is completely ignored and never run.

**Comment by henryiii** [comment]
I've been something similar for a while: https://github.com/tomerfiliba/plumbum/blob/master/.travis.yml .  I belive the correct matrix line is:

```yml
sudo: false
dist: trusty
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.6
    - python: 3.5
    - python: 3.4
    - python: 2.7
```

(In the one I linked to, `sudo: true` was needed for all of them for other reasons)
