### ISSUE TITLE
s3 deployment: does `endpoint` really work?

### ISSUE THREAD

**Issue by zh99998** [travis-ci/travis-ci#9819]
I want to deploy my project to Aliyun OSS which has a S3 compatible api.
the `deploy` part of my .travis.yml is
```
deploy:
  provider: s3
  access_key_id: ...
  secret_access_key:
    secure: ...
  bucket: mycard
  skip_cleanup: true
  local-dir: dist
  upload-dir: mobile
  endpoint: oss-cn-hangzhou.aliyuncs.com
```
then I got an `Invalid S3 Access Key Id, Stopping Deploy` during deploy.
https://travis-ci.org/moecube/mycard-mobile/jobs/398087927

I have double checked my access key id it is correct.
then I download `dpl` rubygem and try to call it manually on my local develop computer, I got `Invalid S3 Access Key Id, Stopping Deploy` too.
and I open code of this gem, It don't has a endpoint param and seems only support upload to real amazon s3. no custom endpoint is supported.
