### ISSUE TITLE
`dist: xenial` + `apt: sources: [deadsnakes]`

### ISSUE THREAD

**Issue by asottile** [travis-ci/travis-ci#9827]
Following [this](https://docs.travis-ci.com/user/installing-dependencies#Installing-Packages-with-the-APT-Addon)

I have the following `.travis.yml`:

```yaml
language: python
dist: xenial
matrix:
    include:
        -   env: TOXENV=py37
install: pip install tox
script: tox
addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - python3.7-dev
```

which fails with:

```
Adding APT Sources (BETA)
Disallowing sources: deadsnakes
To add unlisted APT sources, follow instructions in https://docs.travis-ci.com/user/installing-dependencies#Installing-Packages-with-the-APT-Addon
```
