### ISSUE TITLE
matrix.include leads to additional unwanted job 

### ISSUE THREAD

**Issue by zoechi** [travis-ci/travis-ci#9843]
language: dart

```yaml
dart:
  - dev
#  - stable # TODO(zoechi) enable when Dart 2.0.0 was released

sudo: required
dist: trusty
group: edge
services:
  - docker

env:
  - SHARD=flutter
  - SHARD=shared
  - SHARD=backoffice_angular
  - SHARD=firebase
  - SHARD=project

matrix:
  include:
    - os: linux
      env: SHARD=flutter
      addons:
```

leads to 6 jobs instead of 5 where `flutter` is listed twice, once with the addons and once without.

How can I fix this

https://travis-ci.com/lookAtYouInc/lookatmybaby/builds/78146763

I found #4681 but still don't understand how to fix.

**Comment by zoechi** [comment]
Also found #3670 but still don't know how to fix.

I tried
```
matrix:
  exclude:
    - os: linux
      env: SHARD=flutter
  include:
    - os: linux
      env: SHARD=flutter
      addons:
         ...
```
but didn't help.

**Comment by zoechi** [comment]
This did it.
```
matrix:
  exclude:
    - env: SHARD=flutter
    - env: SHARD=shared
  include:
    - env: SHARD=flutter
      addons:
         ...
```
