### ISSUE TITLE
Default values for Travis CI build stages

### ISSUE THREAD

**Issue by Richienb** [travis-ci/travis-ci#9853]
The project I'm currently working on needs to include the following code on all build stages:

```yml
before_install:
  - git remote set-url origin https://Richienb:${github_token}@github.com/Richienb/ROS-Code.git
  - git config --global user.email "richiebendall@gmail.com"
  - git config --global user.name "Richienb"
```

I can't seem to find a way to make the code above execute on every single build job other than to specify it in every single on of them. In other words, how could I simplify the code below

```yml
jobs:
  include:
    - stage:                 optimisation
      language:              python
      python:                3.6.5
      branches:              master
      before_install:
        - git remote set-url origin https://Richienb:${github_token}@github.com/Richienb/ROS-Code.git
        - git config --global user.email "richiebendall@gmail.com"
        - git config --global user.name "Richienb"
      install:
        - pip install -r requirements.txt
      script:
        - cd src
        - BEFOREHASH=find /my/dir -mindepth 1 -type f -print0 | sort -z | sha1sum
        - $TRAVIS_BUILD_DIR/ci/autoop.sh
        - AFTERHASH=find /my/dir -mindepth 1 -type f -print0 | sort -z | sha1sum
        - $TRAVIS_BUILD_DIR/ci/verifycommit.sh
    - stage:                 code testing
      language:              python
      python:                3.6.5
      branches:              master
      before_install:
        - git remote set-url origin https://Richienb:${github_token}@github.com/Richienb/ROS-Code.git
        - git config --global user.email "richiebendall@gmail.com"
        - git config --global user.name "Richienb"
      install:
        - pip install -r requirements.txt
      script: # Code unrelated to this issue
    - stage:                 python building
      branches:              master
      cache:
        directories:
          - $TRAVIS_BUILD_DIR/python-source
          - $TRAVIS_BUILD_DIR/python-compiled
      addons:
        apt:
          packages:
            - build-essential
            - build-dep
            - python2.7
       script: # Code unrelated to this issue
    - stage:                 documentation deployment
      language:              python
      python:                3.6.5
      branches:              master
      before_install:
        - git remote set-url origin https://Richienb:${github_token}@github.com/Richienb/ROS-Code.git
        - git config --global user.email "richiebendall@gmail.com"
        - git config --global user.name "Richienb"
      install:
        - pip install -r requirements.txt
      script: # Code unrelated to this issue
```
