### ISSUE TITLE
Stages and deployment - exclude build is ignored

### ISSUE THREAD

**Issue by mohierf** [travis-ci/travis-ci#9858]
In my CI process, I created several stages. Especially, I would like to deploy to the Bintray provider if I am on the beanches master or develop, or if I am pushing a tagged commit.

To achieve this behavior I was obliged to create 2 stages, one for the branches deployment and one for the tag deployment because I could not use the `deploy.on` clause to indicate beanch in (master, develop) or tags IS true ... did I missed something about the `deploy.on` ?

So, I declared 2 stages in *travis.yml*:
```
    - stage: First stage
      if: branch IN (master, develop)
      deploy:
      - provider: bintray
        on:
          all_branches: true

    - stage: Second stage
      if: tags Is present
      deploy:
      - provider: bintray
        on:
          tags: true
```

And the 2 stages are executed whatever the branch and/or tag presence ... does it mean that the `if` clause is ignored in the stages ? Or did I also missed something ?

Many thanks in advance for any answer ....

The concerned github repo: https://github.com/Alignak-monitoring-contrib/alignak-backend
