### ISSUE TITLE
Object in python build matrix results in unexpected behaviour

### ISSUE THREAD

**Issue by ThomasHickman** [travis-ci/travis-ci#9882]
Example:
![image](https://user-images.githubusercontent.com/6304200/42767107-0f1bfb5c-8914-11e8-9ea1-53fabd113449.png)
The `.travis.yml` file is:
```
sudo: false
language: python
cache:
  pip: true
  directories:
    - .mypy_cache
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - python: 3.7
    dist: xenial
    sudo: true

os:
  - linux
jobs:
  include:
    - stage: release-test
      script: RELEASE_SKIP=head PYVER= ./release-test.sh
script: tox
install:
  - pip install tox-travis
notifications:
  email: false

```
URL of the PR which triggers this: https://travis-ci.org/common-workflow-language/schema_salad/builds/404488051?utm_source=github_status&utm_medium=notification
