### ISSUE TITLE
Build Error even after Travis CI Deploys

### ISSUE THREAD

**Issue by vkartik97** [travis-ci/travis-ci#9883]
I have used Travis CI to Deploy my project to AWS EC2, using SSH.

```
language:
- node_js
node_js:
- '9'
addons:
  ssh_known_hosts: ec2-52-206-3-72.compute-1.amazonaws.com
before_install:
- openssl aes-256-cbc -K $encrypted_2eb2d4c81e92_key -iv $encrypted_2eb2d4c81e92_iv -in coyote.enc -out /tmp/coyote -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/coyote
- ssh-add /tmp/coyote


script: 'true'


deploy:
  provider: script
  skip_cleanup: true
  script: sh ./deploy.sh
```

I got : <br>
![Build Error](https://i.stack.imgur.com/KuRdn.png)
<br>
<br>
 **continuous-integration/travis-ci/push** : https://travis-ci.org/vkartik97/CDTest
**Travis CI - Branch — Build Errored** : https://travis-ci.com/vkartik97/CDTest/builds/79102356
**Repository** : https://github.com/vkartik97/CDTest
<br>
<br>
For  **Travis CI - Branch — Build Errored** , I got

```
$ openssl aes-256-cbc -K $encrypted_2eb2d4c81e92_key -iv $encrypted_2eb2d4c81e92_iv -in coyote.enc -out /tmp/coyote -d
iv undefined

The command "openssl aes-256-cbc -K $encrypted_2eb2d4c81e92_key -iv $encrypted_2eb2d4c81e92_iv -in coyote.enc -out /tmp/coyote -d" failed and exited with 1 during .

Your build has been stopped.
```

But, for  **continuous-integration/travis-ci/push**, the `openssh` command was executed successfully with `-iv` flag.
From above, I have understood that the Protected env keys are not getting detected in **Travis CI - Branch — Build Errored**, even if my Push is not a PR.
How should I resolve it.
