### ISSUE TITLE
Use of `dart_task: dartfmt` doesn't run dartfmt

### ISSUE THREAD

**Issue by chalin** [travis-ci/travis-ci#9886]
The markdown package has had this `.travis.yml` file for a while: https://github.com/dart-lang/markdown/blob/4f6738cd4d7da9e3ff59e2af4776f476012a1293/.travis.yml#L5-L11

```yaml
dart_task:
  # Using the expanded reporter to work-around
  # https://github.com/dart-lang/markdown/issues/191
  - test: --reporter expanded
    xvfb: false
  - dartfmt
  - dartanalyzer
```

Use of `dart_task: dartanalyzer ` (i.e. the plain `dartanalyzer` entry) runs the analyzer: e.g., see [this Travis log](https://travis-ci.org/dart-lang/markdown/jobs/404605057).

But `dart_task: dartfmt` doesn't run dartfmt. Instead, as shown in [this Travis log](https://travis-ci.org/dart-lang/markdown/jobs/404605056), we get:

```console
dartfmt only supports 'sdk' as an optional argument value.
> unformatted=`dartfmt -n .`
The command "unformatted=`dartfmt -n .`" exited with 0.
```

I know that the docs say that we should instead be writing `dartfmt: true`, but since a plain `dartanalyzer` works, it is reasonable to expect `dartfmt` to work too.

cc @nex3 and @a14n @kevmoo @kwalrath
