### ISSUE TITLE
Overriding notifications on a per-stage basis

### ISSUE THREAD

**Issue by eisenbergrobin** [travis-ci/travis-ci#9888]
I'm trying to have different notification channels on Slack for separate stages, but I can't seem to get it to work. 

Example YAML (nodejs repo):
```
sudo: false
language: node_js
notifications:
  email: false
  slack:
    rooms:
      - my_slack_room_descriptor
    on_success: never
    on_failure: always

jobs:
  include:
    - stage: Lint & Unit Tests
      script:
        - yarn lint
        - yarn test

    - stage: Deploy to warehouse
      script: yarn build
      deploy:
        skip_cleanup: true
        provider: script
        script: script/travisDeploy

    - stage: Integration Tests
      script: ./integration/scripts/test-ci
      # I'd like to override this here so the slack channel we post to changes for this job:
      notifications:
        email: false
        slack:
          rooms:
              - my_*second*_slack_room_descriptor
          on_success: never
          on_failure: always
```

Is this supported ? I though it would be as part of YAML but I'm still getting the notifications on the base channel.
