### ISSUE TITLE
Build matrix not honoured after adding stages

### ISSUE THREAD

**Issue by andig** [travis-ci/travis-ci#9901]
Given the yml below the build should run 8 jobs; 3 for php plus 5 from the matrix. https://travis-ci.org/andig/volkszaehler.org/builds/403869329 shows that this was the behaviour before the `stage` feature was added.

Now the last `lint` job has been added using the new `stage` feature, the build only runs the 3 php features and ignores the matrix (see https://travis-ci.org/andig/volkszaehler.org/builds/405765731).

````
language: php

php:
  - 7.0
  - 7.1
  - 7.2

services:
  - mysql

env:
  # run composer by default
  global:
    - DEPENDENCIES=standard
    - TRAVIS_TEST_EXCLUDES="--exclude-group slow,jpgraph,pushserver"
  matrix:
    - DB=mysql

matrix:
  include:
    # postgres
    - php: 7.0
      services: postresql
      env: DB=pgsql
    # sqlite
    - php: 7.0
      env: DB=sqlite
    # httpd-based
    - php: 7.0
      env: DB=mysql COMPONENT=HTTPD
    # push-server
    - php: 7.0
      env: DB=mysql COMPONENT=PUSHD
    # from..to
    - php: 7.0
      env: DB=mysql DEPENDENCIES=lowest

# speedup build
cache:
  directories:
    - $COMPOSER_CACHE_DIR
    - $HOME/.composer/cache
    - node_modules

#
# default stage
#
before_install:
  # disable xdebug for composer performance
  - if [ -e /home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then rm /home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini; fi

install:
  - ...

script:
  - ...
````

added `lint` job:

````
jobs:
  include:
    - stage: lint
      language: javascript
      install:
        - npm install -g gulp
        - npm install
      script: gulp jshint
````

**Comment by andig** [comment]
ping @maintainers any feedback why `matrix` doesn't work with `stages`?

**Comment by AronNovak** [comment]
I have a similar issue in this PR:
https://github.com/Gizra/drupal-elm-starter/pull/203/files#diff-354f30a63fb0907d4ad57269548329e3R28

I'd like to break up this:
![image](https://user-images.githubusercontent.com/114076/43648581-172e14ee-973b-11e8-9d91-926def0e73dc.png)
(https://travis-ci.org/Gizra/drupal-elm-starter/builds/397719939)

into two stages: linting and testing.
I tried in several ways to specify 4 jobs for the linting, 3 jobs for the testing, current attempt:
```yml
jobs:
  include:
    - stage: lint
      matrix:
        env:
          - CODE_REVIEW=1 REVIEW_STANDARD="Drupal"
          - CODE_REVIEW=1 REVIEW_STANDARD="DrupalPractice"
          - SHELL_REVIEW=1
          - ELM_REVIEW=1
      script:
        - "$TRAVIS_BUILD_DIR/ci-scripts/install_coder.sh"
        - "$TRAVIS_BUILD_DIR/ci-scripts/install_elm_format.sh"
        - "$TRAVIS_BUILD_DIR/ci-scripts/install_shell.sh"
        - "$TRAVIS_BUILD_DIR/ci-scripts/test_coder.sh"
        - "$TRAVIS_BUILD_DIR/ci-scripts/test_shell.sh"
        - "$TRAVIS_BUILD_DIR/ci-scripts/test_elm_format.sh"
    - stage: test
      matrix:
        env:
          - BUILD_SERVER=1
          - BUILD_CLIENT=1
          - BUILD_WEBDRIVERIO=1 BUILD_SERVER=1 BUILD_GATLING=1
      script:
        - "$TRAVIS_BUILD_DIR/ci-scripts/install_client.sh"
        - "$TRAVIS_BUILD_DIR/ci-scripts/install_server.sh"
        - "$TRAVIS_BUILD_DIR/ci-scripts/install_webdriverio.sh"
        - "$TRAVIS_BUILD_DIR/ci-scripts/test_client.sh"
        - "$TRAVIS_BUILD_DIR/ci-scripts/test_webdriverio.sh"
        - "$TRAVIS_BUILD_DIR/ci-scripts/test_simpletest.sh"
        - "$TRAVIS_BUILD_DIR/ci-scripts/test_gatling.sh"
```
