### ISSUE TITLE
environment variables set in .travis.yml not exported

### ISSUE THREAD

**Issue by mdeceglie** [travis-ci/travis-ci#9903]
Using the below .travis.yml file, builds are failing, apparently because `REQ_FILE` never gets set. I would expect the build log to show `export REQ_FILE=... ` but it does not. 

```yml
sudo: false

language: python

python:
  - "2.7"
  - "3.6"

env:
  - REQ_FILE = "./ci/min_reqs.txt"
  - REQ_FILE = "./ci/reqs.txt"

before_install:
  - pip install -r $REQ_FILE

install:
  - pip install .

script:
  - tests/run_tests
```
Complete details: 
https://github.com/NREL/rdtools/tree/setup_CI_md
https://travis-ci.org/NREL/rdtools/builds/405012012
