### ISSUE TITLE
Deploy Script shouldn't set GIT_HTTP_USER_AGENT

### ISSUE THREAD

**Issue by chris-smith-zocdoc** [travis-ci/travis-ci#9905]
When using the script provider, we encountered an issue using git that doesn't occur when running in a normal `script:` or `after_success:` block. 

Example 

```yml
deploy:
  provider: script
  script: bash .travis/deploy.sh
  skip_cleanup: true
```

Example command that reproduces the bug (in our case triggered by [semantic-release](https://github.com/semantic-release/semantic-release) )
```
git push --dry-run https://$GH_TOKEN@github.com/org/repo HEAD:master
```

This would error out with 
```
remote: Not Found
fatal: repository 'https://$GH_TOKEN@github.com/org/repo HEAD:master' not found
```
exit code: 128

The command was failing because the environment variable `GIT_HTTP_USER_AGENT` was set with a custom value. It appears that github rejects requests when the user agent is not the default `git/version`

The value of `GIT_HTTP_USER_AGENT` was
```
travis/0.1.0 dpl/1.9.8 git/2.15.1
```

We were able to `unset GIT_HTTP_USER_AGENT` to work around this issue.

**Comment by iriberri** [comment]
I just stumbled upon a similar case where `go get` was failing with `repository not found` and unsetting the env var resolved the issue.

@joepvd do you happen to know where does `GIT_HTTP_USER_AGENT` come from?

**Comment by BanzaiMan** [comment]
I tracked this down to https://github.com/travis-ci/dpl/pull/197, which I believe was prompted by Heroku deployment via git-ssh. We should move this logic to the providers that actually need it.

**Comment by BanzaiMan** [comment]
Please test it with:

```yaml
deploy:
  provider: script
  edge:
    branch: no-git_http_user_agent
  ⋮ # rest
```
