### ISSUE TITLE
Deploying two PyPI targets broken

### ISSUE THREAD

**Issue by oskar456** [travis-ci/travis-ci#9908]
I have two branches in my [respository](https://github.com/oskar456/dzonegit) - `master` and `test`. My intent is to deploy `test` branch to the TestPyPI and `master` branch to the production PyPI.
My [.travis.yml](https://github.com/oskar456/dzonegit/blob/test/.travis.yml) contains two instances of PyPI deploy:

```
deploy:
 - provider: pypi
   server: https://test.pypi.org/legacy/
   user: oskar456
   password:
        secure: …
   distributions: "sdist bdist_wheel"
   on:
           repo: "oskar456/dzonegit"
           python: "3.6"
           tags: true
           branch: "test"
 - provider: pypi
   user: oskar456
   password:
        secure: …
   distributions: "sdist bdist_wheel"
   on:
           repo: "oskar456/dzonegit"
           python: "3.6"
           tags: true
           branch: "master"
```

However, when I tagged a version in [the test branch](https://github.com/oskar456/dzonegit/releases/tag/v0.8-test), Travis [deployed it to the production PyPI](https://travis-ci.org/oskar456/dzonegit/jobs/407593631#L652) and **did not** deploy it to TestPyPI. With just one deploy target set to TestPyPI, everything works properly. Am I missing something?
