### ISSUE TITLE
Python on OSX

### ISSUE THREAD

**Issue by felixdivo** [travis-ci/travis-ci#9929]
Suddenly, our Python tests on OSX seemed to have been broken.

This was our previous setup (only an excerpt):

```
matrix:
  include:
    - os: osx
      python: "3.6-dev"
    - os: osx
      python: "3.7-dev"
    - os: osx
      python: "nightly"
```

We also applied [this patch](https://github.com/hardbyte/python-can/pull/380/files#diff-354f30a63fb0907d4ad57269548329e3L34), but it did not work:

```
matrix:
  include:
    - os: osx
      python: "2.7"
    - os: osx
      python: "3.6"
    - os: osx
      python: "nightly"
```

The first setup worked once, but now doesn't any more. Is this a problem with the runners or with our configuration?

**Comment by ycombinator** [comment]
Ours as well, for example: https://travis-ci.org/elastic/beats/jobs/410580776. Specifically our OSX builds are failing with:

```
bash: virtualenv: command not found
make: *** [python-env] Error 127
```

**Comment by jsoriano** [comment]
@felixdivo in our case forcing the use of an older image with `osx_image: xcode9.3` fixed our issues.

**Comment by felixdivo** [comment]
Well, that would probably work in our case too, but would only postpone the actual problem.

**Comment by DrTorte** [comment]
Hey all,

We don't support Python on macOS at this time. https://docs.travis-ci.com/user/languages/python

**Comment by felixdivo** [comment]
Hm, but it was working before. Can't you enable the experimental support again?

**Comment by jsoriano** [comment]
@DrTorte `virtualenv` appears in the list of python related tools in the [OSX build environment documentation](https://docs.travis-ci.com/user/reference/osx#python-related-tools). Does it mean that it should be included? or that it can be installed during the build "`via pip`" ([this works](https://github.com/elastic/beats/pull/7866))?
As @felixdivo mentions, these tools worked at least in the previous osx image (`xcode9.3`).

**Comment by cotsog** [comment]
Most of these issues are indeed probably caused by us changing our default macOS image last Tuesday as @felixdivo [suggested](https://github.com/travis-ci/travis-ci/issues/9929#issuecomment-409556178) earlier. Sorry for the inconvenience.

You will be able to use the previous default image by adding the following snippet in your jobs defined in your .travis.yml file:

```yaml
os: osx
osx_image: xcode8.3
```

Please let us know if this helps or not. Thanks!

**Comment by jsoriano** [comment]
Yes, using `osx_image: xcode9.3` works, but I guess that this image is not going to be available forever :slightly_smiling_face: 

In our case we are fine if we can continue installing `virtualenv` with `pip`, but maybe this needs to be clarified in the python section of OSX build environment documentation.

**Comment by felixdivo** [comment]
No, [xcode9.3](https://travis-ci.org/hardbyte/python-can/builds/412596297) does not work, but [xcode**8**.3](https://travis-ci.org/hardbyte/python-can/builds/412598557) does. But this only solves the problem for now!

Adding some docs to the Python section of the OSX documentation would be really helpful!

**Comment by cotsog** [comment]
Glad to hear it helped!

Unfortunately, Python isn't supported at the same level as on our Linux environment right now. We'd like to get it on par but we don't have an ETA at the moment. As such, we are mentioning `Python builds are not available on the macOS environment.` on our [Python documentation](https://docs.travis-ci.com/user/languages/python/).  Sorry for the inconvenience.

Don't hesitate to open another issue for troubles you run into with Python builds on macOS. We would be happy to have a look but we cannot promise how timely we will. Thank you for your understanding.

**Comment by vuolter** [comment]
These days I'm spending a lot of time to work-around this and many other unexpected problems in my projects! 😠 

I just came up with this solution:
```
- stage: test
  os: osx
  language: sh
  env: TOXENV=py3
  addons:
    homebrew:
      update: true
      packages: python3
  before_install:
    - pip3 install virtualenv
    - virtualenv -p python3 ~/venv
    - source ~/venv/bin/activate
```
It's a single job (named `test`) for running my tox tests under osx with latest python 3.
Take a look here to better understand: https://travis-ci.org/pyload/pyload . 😉

**Comment by ppolewicz** [comment]
@vuolter this takes 11 minutes, but removing `homebrew.update: true` drops python from 3.7 to 3.6.5 and reduces the build time to less than a minute. Thanks for sharing your solution, wouldn't get anything done without it!

**Comment by vuolter** [comment]
> 
> 
> @vuolter this takes 11 minutes, but removing `homebrew.update: true` drops python from 3.7 to 3.6.5 and reduces the build time to less than a minute.

Yeah, you're totally right!
Basically this is my current configuration for testing pyLoad under OSX:
```
sudo: false

language: python
group: travis_latest

stages: test

python: 3.7

before_cache: rm -f "$HOME/.cache/pip/log/debug.log"
cache: pip

install: pip install --upgrade tox tox-travis
script: tox --sitepackages

jobs:
  allow_failures:
    - os: osx
    
  include:
    - stage: test
      os: osx
      language: sh
      env:
        - TOXENV=py3
        - HOMEBREW_NO_INSTALL_CLEANUP=1
        - HOMEBREW_NO_ANALYTICS=1
      before_cache:
        # - brew cleanup
        - rm -f "$HOME/Library/Caches/pip/log/debug.log"
      cache:
        directories:
          # - "$HOME/Library/Caches/Homebrew"
          - "$HOME/Library/Caches/pip"
      addons:
        homebrew:
          # update: true
          packages: python3
      before_install:
        - python3 -m pip install --upgrade virtualenv
        - virtualenv -p python3 --system-site-packages "$HOME/venv"
        - source "$HOME/venv/bin/activate"
```
As you can see I've enabled caching to lightly speed-up the process and, of course, disabled the slowest homebrew update (and its cache). I agree that Python 3.6 is enough. 😉 
But, I don't know if changing the `group` record could affect the available osx image... I've always used `travis_latest`. 😳

**Comment by ppolewicz** [comment]
I think you can also cache `$HOME/venv` and only create a fresh virtualenv and install dependencies, if `$HOME/venv` doesn't exist. Also, your indicated python version is 3.7 but you actually use 3.6. Other than that, I see some cool patterns in your config.

I would think [cache.pip](https://docs.travis-ci.com/user/caching/#pip-cache) would cache pip, but I see you are doing it manually to make it work (:

**Comment by vuolter** [comment]
Thanks for the kind words. 😄 
Yep, that's just a "piece", the original config has a lot of other stages with many jobs... I removed them, I left only the osx job.
So, don't care too much about the main `cache`, `before_cache` and `python` records (they was used by the jobs in the missing stages),
Right now, I have to say that a config ready to copy&paste (to an existing stage matrix) should be more like this:
```
jobs:
  allow_failures:
    - os: osx
    
  include:
    - stage: test
      os: osx
      language: sh
      env:
        - TOXENV=py3
        - HOMEBREW_NO_INSTALL_CLEANUP=1
        - HOMEBREW_NO_ANALYTICS=1
      before_cache:
        # - brew cleanup
        - rm -f "$HOME/Library/Caches/pip/log/debug.log"
      cache:
        directories:
          # - "$HOME/Library/Caches/Homebrew"
          - "$HOME/Library/Caches/pip"
      addons:
        homebrew:
          # update: true
          packages: python3
      before_install:
        - python3 -m pip install --upgrade virtualenv
        - virtualenv -p python3 --system-site-packages "$HOME/venv"
        - source "$HOME/venv/bin/activate"
      install: pip install --upgrade <your-packages>
      script: <your-script>
```
Of course, you can remove the `jobs.allow_failures.os.osx` to avoid the osx test to fail silently.
