### ISSUE TITLE
Inconsistent MODULE_NOT_FOUND errors

### ISSUE THREAD

**Issue by jdalrymple** [travis-ci/travis-ci#9965]
While running a build i keep receiving inconsistent results where the build fails due to a MODULE_NOT_FOUND error.

The build: https://travis-ci.org/jdalrymple/node-gitlab/jobs/413651850

Occasionally it says its missing `..pack.js` and sometimes `validate_npm_package_name`

The CI File:
```
language: node_js

stages:
  - lint and build
  - test
  - release

cache:
  directories:
    - node_modules # NPM packages
    - ~/.npm

notifications:
  email: false

jobs:
  include:
    - stage: lint and build
      node_js: 10.0.0
      script:
        - npm run lint
        - npm run build

    - stage: test
      node_js: 10.0.0
      before_script:
        ## Spin up container
        - cd test/docker/
        - docker-compose -f docker-compose.test.yml up -d

        ## Test for liveness
        # - docker exec -it gitlab bash -lc 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost/-/readiness)" != "200" ]]; do sleep 5; done'
        - sleep 240 

        - export PERSONAL_ACCESS_TOKEN=$(docker exec -it gitlab bash -lc 'printf "%q" "${PERSONAL_ACCESS_TOKEN}"')
        - export GITLAB_URL=$(docker exec -it gitlab bash -lc 'printf "%q" "${GITLAB_URL}"')
        - echo $GITLAB_URL
        - echo $PERSONAL_ACCESS_TOKEN
      script:
        - npm run test
        
    - stage: release
      node_js: 10.0.0
      script:
        - npm run semantic-release
```

I thought it was originally due to the node version so i restricted it to 10.0.0 which would sometimes pass the first two stages and fail on the third, or fail on the first stage.

Any suggestions?
