### ISSUE TITLE
An error occurred while generating the build script.

### ISSUE THREAD

**Issue by aliaksandrmikhailik** [travis-ci/travis-ci#9968]
I don't know what is wrong, because I haven't changed my travis.yml

```
language: java
jdk:
  - oraclejdk8
os:
  - linux
sudo: required
services:
  - docker

branches:
  only:
    - develop
    - test
    - prod

before_install:
  - curl -fsSL https://clis.ng.bluemix.net/install/linux | sh
  - docker pull ibmcom/cloudant-developer
  - docker run --detach --volume cloudant:/srv --name cloudant-developer --publish 5984:80 --hostname cloudant.dev ibmcom/cloudant-developer

# Skipping the Installation Step ./gradlew assemble
install: true

script:
  - ./gradlew cloudantmigrate test -PcloudantUrl=$CLOUDANT_URL_LOCAL --stacktrace

deploy:
  - provider: script
    skip_cleanup: true
    script:
      ./deploy.sh
    on:
      all_branches: true
```

but now I have "An error occurred while generating the build script."
