### ISSUE TITLE
Travis doesn't see job in Matrix if there is Jobs param

### ISSUE THREAD

**Issue by voronind** [travis-ci/travis-ci#9974]
My config:
```yaml
dist: bionic
sudo: false
cache: pip

language: python
python:
    - "3.5"
    - "3.6"

script: check code

matrix:
    include:
        - name: Docs
          python: "3.5"
          script: check docs

jobs:
    include:
        - stage: Codecov
          install: pip install codecov
          script: codecov
```

It produces Python 3.5 and Python 3.6 jobs on first stage and Codecov stage. It skips __Docs__ on first stage.  
__Is it OK?__
